SELECT
    id_debtor_external AS id_contract,
    id_collector_external AS id_negotiation,
    GET_JSON_OBJECT(payload, "$.contrato") AS id_contract_cyber,
    GET_JSON_OBJECT(payload, "$.cpfCnpj") AS id_client,
    invoice.idParcela AS id_invoice,
    GET_JSON_OBJECT(payload, "$.grupo") AS contract_group,
    status,
    status_reason,
    GET_JSON_OBJECT(payload, '$.tipoContato') AS contact_type,
    GET_JSON_OBJECT(payload, '$.cdAssessoria') AS agency,
    GET_JSON_OBJECT(payload, '$.periodicidade') AS frequency,
    GET_JSON_OBJECT(payload, '$.diasCarencia') AS grace_period_days,
    GET_JSON_OBJECT(payload, '$.formaPagamento') AS payment_method,
    GET_JSON_OBJECT(payload, '$.flgCampanhaBoletagem') AS is_boletagem,
    GET_JSON_OBJECT(payload, '$.cdTipoAcordo') AS agreement_type,
    GET_JSON_OBJECT(payload, "$.taxaMulta") AS fine_rate,
    GET_JSON_OBJECT(payload, "$.vlrEntrada") AS down_payment,
    GET_JSON_OBJECT(payload, '$.qtdParcelas') AS total_installments,
    GET_JSON_OBJECT(payload, '$.vlrNegociado') AS negotiated_amount,
    GET_JSON_OBJECT(payload, '$.vlrHonorariosParc') AS installment_honorarium_amount,
    invoice.vlrPrincipal AS invoice_main_amount,
    invoice.vlrMultaResidual AS invoice_residual_fine_amount,
    invoice.vlrJurosResiduais AS invoice_residual_interest_amount,
    invoice.vlrCustasResiduais AS invoice_residual_costs_amount,
    invoice.vlrHonorariosResiduais AS invoice_residual_honorarium_amount,
    installment.vlrJuros AS installment_fine_amount,
    installment.vlrSaldo AS installment_balance_amount,
    installment.dtInicial AS dt_installment_start,
    installment.taxaMulta AS installment_fine_rate,
    installment.vlrParcela AS installment_amount,
    installment.dtVencimento AS dt_due_installment,
    installment.numeroParcela AS installment_number,
    installment.vlrAmortizacao AS installment_amortization_amount,
    installment.taxaCartaoCredito AS installment_credit_card_fee,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRPRCAG' THEN discount.vlrComDesconto END) AS overdue_amount_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRPRCAG' THEN discount.vlrSemDesconto END) AS overdue_amount_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRPRCAVAG' THEN discount.vlrComDesconto END) AS to_due_amount_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRPRCAVAG' THEN discount.vlrSemDesconto END) AS to_due_amount_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRPRMUAGR' THEN discount.vlrComDesconto END) AS installment_fine_amount_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRPRMUAGR' THEN discount.vlrSemDesconto END) AS installment_fine_amount_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRMUREAG' THEN discount.vlrComDesconto END) AS residual_fine_amount_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRMUREAG' THEN discount.vlrSemDesconto END) AS residual_fine_amount_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRMUAG' THEN discount.vlrComDesconto END) AS agreement_fine_amount_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRMUAG' THEN discount.vlrSemDesconto END) AS agreement_fine_amountwithout_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRPRJUAG' THEN discount.vlrComDesconto END) AS interest_installments_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRPRJUAG' THEN discount.vlrSemDesconto END) AS interest_installments_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRJUREAG' THEN discount.vlrComDesconto END) AS residual_interest_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRJUREAG' THEN discount.vlrSemDesconto END) AS residual_interest_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRJUAG' THEN discount.vlrComDesconto END) AS agreement_interest_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRJUAG' THEN discount.vlrSemDesconto END) AS agreement_interest_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLCUSREAG' THEN discount.vlrComDesconto END) AS residual_costs_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLCUSREAG' THEN discount.vlrSemDesconto END) AS residual_costs_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLCUSTASAG' THEN discount.vlrComDesconto END) AS agreement_costs_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLCUSTASAG' THEN discount.vlrSemDesconto END) AS agreement_costs_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRHOREAG' THEN discount.vlrComDesconto END) AS residual_fees_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRHOREAG' THEN discount.vlrSemDesconto END) AS residual_fees_without_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRDESPJUD' THEN discount.vlrComDesconto END) AS judicial_expenses_with_discount,
    MAX(CASE WHEN UPPER(discount.campo) = 'U1VLRDESPJUD' THEN discount.vlrSemDesconto END) AS judicial_expenses_without_discount,
    ts_created AS ts_creation,
    GET_JSON_OBJECT(payload, '$.dataValidadeBoletagem') AS ts_due_boletagem
FROM datalake_trato_feito_clean.billing
LATERAL VIEW explode(from_json(get_json_object(payload, '$.parcelas'), 'array<struct<grupo:string, contrato:string, idParcela:string, vlrPrincipal:double, vlrMultaResidual:double, vlrJurosResiduais:double, vlrCustasResiduais:double, vlrHonorariosResiduais:double>>')) AS invoice
LATERAL VIEW explode(from_json(get_json_object(payload, '$.parcelasAgr'), 'array<struct<vlrJuros:double, vlrSaldo:double, dtInicial:string, taxaMulta:double, vlrParcela:double, dtVencimento:string, numeroParcela:int, vlrAmortizacao:double, taxaCartaoCredito:double>>')) AS installment
LATERAL VIEW explode(from_json(get_json_object(payload, '$.camposDesconto'), 'array<struct<campo:string, idAcordo:int, operador:string, vlrComDesconto:double, vlrSemDesconto:double, percentualDesconto:double>>')) AS discount
GROUP BY ALL
