SELECT
  c.id AS sk_contract,
  c.id AS id_contract,
  c.country_code,
  c.rent,
  c.first_rent_charged,
  c.billing_day_of_month AS day_month_due,
  c.guarantee_type AS guarantee,
  c.type,
  c.status,
  c.rental_administrator,
  c.paying_condo AS condo_payer,
  c.responsible_for_condo AS condo_responsible,
  c.paying_iptu AS iptu_payer,
  c.responsible_for_iptu AS iptu_responsible,
  c.rental_guarantee_installment AS rental_insurance_installments,
  c.rental_guarantee_value AS rental_insurance_value,
  c.home_insurance_installment AS home_insurance_installments,
  c.home_insurance_value AS home_insurance_value,
  c.fist_rent_comission_fee AS first_rental_commission,
  c.monthly_administration_fee,
  c.condo_price,
  c.iptu,
  c.tenant_service_fee,
  c.signature_type,
  c.status_closing AS closing_status,
  c.cancellation_reason,
  c.contract_version AS version,
  c.is_b2b,
  c.is_contract_b2b,
  c.contract_partner_type,
  c.b2b_type,
  c.b2b_prime_type,
  c.contract_plan,
  c.is_ongoing_contract,
  c.is_tenant_service_fee_opt_out,
  c.is_exit_inspection_opted_out,
  c.is_rental_paid_in_advance,
  c.dt_started AS dt_start,
  c.dt_entered AS dt_entrance,
  c.dt_contract_expected_end AS dt_intended_end,
  c.dt_termination AS dt_annulment,
  c.ts_created,
  c.ts_updated,
  c.ts_expected_termination,
  c.ts_signed AS ts_signature,
  c.ts_minuta_approved AS ts_draft_approved,
  c.ts_canceled,
  c.ts_tenant_service_fee_opt_out,
  c.ts_analyst_annulment_input,
  NOW() AS ts_load
FROM
    datalake_contract.contract AS c

