WITH
rj_itbi_main AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    CAST(NULL AS STRING) AS zipcode,
    COALESCE(address_details, property_address) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'rj_itbi_main' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.rj_itbi_main
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
go_goiania_cadastro_imobiliario AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(neighborhood_id AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'go_goiania_cadastro_imobiliario' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.go_goiania_cadastro_imobiliario
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
go_goiania_comprovacao_pagamento AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'go_goiania_comprovacao_pagamento' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.go_goiania_comprovacao_pagamento
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
go_goiania_informacoes_cadastrais AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    lot_area,
    building_area,
    private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    latitude,
    longitude,
    kind,
    usage_purpose,
    usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'go_goiania_informacoes_cadastrais' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.go_goiania_informacoes_cadastrais
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_osasco_itbi AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    assessed_iptu_value,
    assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'sp_osasco_itbi' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_osasco_itbi
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_osasco_pesquisa_cdc AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    is_active,
    dt_load,
    'sp_osasco_pesquisa_cdc' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_osasco_pesquisa_cdc
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
go_goiania_itbi AS (
  SELECT
    CAST(NULL AS INT) AS id,
    CAST(NULL AS STRING) AS id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    CAST(NULL AS STRING) AS state,
    CAST(NULL AS STRING) AS city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'go_goiania_itbi' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.go_goiania_itbi
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
go_goiania_itbi_certidao AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'go_goiania_itbi_certidao' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.go_goiania_itbi_certidao
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_osasco_extrato_iptu AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'sp_osasco_extrato_iptu' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_osasco_extrato_iptu
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
am_manaus_bci AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    real_estate_registry,
    building_year,
    lot_area,
    building_area,
    private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'am_manaus_bci' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.am_manaus_bci
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
ba_salvador_certidao_cadastral AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    lot_area,
    building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'ba_salvador_certidao_cadastral' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.ba_salvador_certidao_cadastral
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
pa_belem_certidao_cadastro_bairros AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    COALESCE(neighborhood_name, neighborhood_code) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'pa_belem_certidao_cadastro_bairros' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.pa_belem_certidao_cadastro_bairros
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
pa_belem_certidao_cadastro AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    lot_area,
    building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'pa_belem_certidao_cadastro' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.pa_belem_certidao_cadastro
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
bh_cnd_main AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'bh_cnd_main' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.bh_cnd_main
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
bsb_main_cadastro_territorial AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    lot_area,
    building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'bsb_main_cadastro_territorial' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.bsb_main_cadastro_territorial
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
bsb_main_certidao_geometria AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    lot_area,
    building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'bsb_main_certidao_geometria' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.bsb_main_certidao_geometria
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
bsb_main_fichas AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    lot_area,
    building_area,
    private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'bsb_main_fichas' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.bsb_main_fichas
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
pe_recife_certidao_narrativa_imob AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'pe_recife_certidao_narrativa_imob' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.pe_recife_certidao_narrativa_imob
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
rj_dados_cadastrais_main_busca AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'rj_dados_cadastrais_main_busca' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.rj_dados_cadastrais_main_busca
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
rj_dados_cadastrais_main_nirf AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'rj_dados_cadastrais_main_nirf' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.rj_dados_cadastrais_main_nirf
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
rj_dados_cadastrais_main_predio AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'rj_dados_cadastrais_main_predio' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.rj_dados_cadastrais_main_predio
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
rj_niteroi_e_cidade AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    CAST(NULL AS STRING) AS zipcode,
    COALESCE(address_details, property_address) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'rj_niteroi_e_cidade' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.rj_niteroi_e_cidade
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_dados_cadastrais_recadastramento_main AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'sp_dados_cadastrais_recadastramento_main' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_dados_cadastrais_recadastramento_main
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_osasco_pesquisa_cep AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    is_active,
    dt_load,
    'sp_osasco_pesquisa_cep' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_osasco_pesquisa_cep
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_osasco_proprietarios AS (
  SELECT
    CAST(NULL AS INT) AS id,
    CAST(NULL AS STRING) AS id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    CAST(NULL AS STRING) AS state,
    CAST(NULL AS STRING) AS city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'sp_osasco_proprietarios' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_osasco_proprietarios
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_osasco_compromissarios AS (
  SELECT
    CAST(NULL AS INT) AS id,
    CAST(NULL AS STRING) AS id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    CAST(NULL AS STRING) AS state,
    CAST(NULL AS STRING) AS city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'sp_osasco_compromissarios' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_osasco_compromissarios
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_santo_andre_itbi AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    real_estate_register,
    real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    lot_area,
    building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    assessed_iptu_value,
    assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'sp_santo_andre_itbi' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_santo_andre_itbi
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_santo_andre_iptu AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    lot_area,
    building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'sp_santo_andre_iptu' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_santo_andre_iptu
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_sao_paulo_itbi AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    CAST(NULL AS STRING) AS zipcode,
    COALESCE(address_details, property_address) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'sp_sao_paulo_itbi' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_sao_paulo_itbi
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
bsb_main_debitos AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'bsb_main_debitos' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.bsb_main_debitos
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
bsb_main_pauta AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'bsb_main_pauta' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.bsb_main_pauta
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
)
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  rj_itbi_main
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  go_goiania_cadastro_imobiliario
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  go_goiania_comprovacao_pagamento
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  go_goiania_informacoes_cadastrais
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_osasco_itbi
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_osasco_pesquisa_cdc
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  go_goiania_itbi
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  go_goiania_itbi_certidao
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_osasco_extrato_iptu
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  am_manaus_bci
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  ba_salvador_certidao_cadastral
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  pa_belem_certidao_cadastro_bairros
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  pa_belem_certidao_cadastro
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  bh_cnd_main
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  bsb_main_cadastro_territorial
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  bsb_main_certidao_geometria
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  bsb_main_fichas
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  pe_recife_certidao_narrativa_imob
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  rj_dados_cadastrais_main_busca
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  rj_dados_cadastrais_main_nirf
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  rj_dados_cadastrais_main_predio
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  rj_niteroi_e_cidade
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_dados_cadastrais_recadastramento_main
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_osasco_pesquisa_cep
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_osasco_proprietarios
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_osasco_compromissarios
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_santo_andre_itbi
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_santo_andre_iptu
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_sao_paulo_itbi
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  bsb_main_debitos
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  bsb_main_pauta
