WITH
rj_itbi_main AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    CAST(NULL AS STRING) AS zipcode,
    COALESCE(address_details, property_address) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'rj_itbi_main' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.rj_itbi_main
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
go_goiania_cadastro_imobiliario AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(neighborhood_id AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'go_goiania_cadastro_imobiliario' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.go_goiania_cadastro_imobiliario
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
go_goiania_comprovacao_pagamento AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'go_goiania_comprovacao_pagamento' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.go_goiania_comprovacao_pagamento
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
go_goiania_informacoes_cadastrais AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    neighborhood,
    street,
    address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    lot_area,
    building_area,
    private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    latitude,
    longitude,
    kind,
    usage_purpose,
    usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'go_goiania_informacoes_cadastrais' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.go_goiania_informacoes_cadastrais
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_osasco_itbi AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    CAST(NULL AS STRING) AS address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    real_estate_register,
    CAST(NULL AS STRING) AS real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    assessed_iptu_value,
    assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    CAST(NULL AS DOUBLE) AS is_active,
    dt_load,
    'sp_osasco_itbi' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_osasco_itbi
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
),
sp_osasco_pesquisa_cdc AS (
  SELECT
    CAST(NULL AS INT) AS id,
    id_municipal_house,
    CAST(NULL AS STRING) AS id_idactum,
    CAST(NULL AS STRING) AS id_patrimonial_assets,
    state,
    city,
    CAST(NULL AS STRING) AS neighborhood,
    CAST(NULL AS STRING) AS street,
    CAST(NULL AS STRING) AS address_number,
    CAST(NULL AS STRING) AS zipcode,
    address_details,
    CAST(NULL AS STRING) AS address_details_unit,
    CAST(NULL AS DOUBLE) AS address_details_building,
    CAST(NULL AS STRING) AS real_estate_register,
    real_estate_registry,
    CAST(NULL AS DOUBLE) AS building_year,
    CAST(NULL AS DOUBLE) AS lot_area,
    CAST(NULL AS DOUBLE) AS building_area,
    CAST(NULL AS DOUBLE) AS private_area,
    CAST(NULL AS DOUBLE) AS idactum_price_estimation,
    CAST(NULL AS STRING) AS idactum_price_estimation_quality,
    CAST(NULL AS DOUBLE) AS avg_annual_appreciation_idactum_estimation,
    CAST(NULL AS DOUBLE) AS estimated_annual_revenue,
    CAST(NULL AS DOUBLE) AS condominium_estimation,
    CAST(NULL AS DOUBLE) AS assessed_iptu_value,
    CAST(NULL AS DOUBLE) AS assessed_itbi_value,
    CAST(NULL AS DOUBLE) AS latitude,
    CAST(NULL AS DOUBLE) AS longitude,
    CAST(NULL AS STRING) AS kind,
    CAST(NULL AS STRING) AS usage_purpose,
    CAST(NULL AS STRING) AS usage_type,
    CAST(NULL AS INT) AS is_iptu_exempt,
    is_active,
    dt_load,
    'sp_osasco_pesquisa_cdc' AS source_spider,
    feed_source,
    feed_url,
    ts_accessed,
    referer_url,
    crawler_name,
    year,
    month,
    day
  FROM
    datalake_crawled_idactum_houses_clean.sp_osasco_pesquisa_cdc
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
)
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  rj_itbi_main
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  go_goiania_cadastro_imobiliario
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  go_goiania_comprovacao_pagamento
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  go_goiania_informacoes_cadastrais
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_osasco_itbi
UNION ALL
SELECT
  id,
  id_municipal_house,
  id_idactum,
  id_patrimonial_assets,
  state,
  city,
  neighborhood,
  street,
  address_number,
  zipcode,
  address_details,
  address_details_unit,
  address_details_building,
  real_estate_register,
  real_estate_registry,
  building_year,
  lot_area,
  building_area,
  private_area,
  idactum_price_estimation,
  idactum_price_estimation_quality,
  avg_annual_appreciation_idactum_estimation,
  estimated_annual_revenue,
  condominium_estimation,
  assessed_iptu_value,
  assessed_itbi_value,
  latitude,
  longitude,
  kind,
  usage_purpose,
  usage_type,
  is_iptu_exempt,
  is_active,
  dt_load,
  source_spider,
  feed_source,
  feed_url,
  ts_accessed,
  referer_url,
  crawler_name,
  year,
  month,
  day
FROM
  sp_osasco_pesquisa_cdc
