SELECT 132 AS id_country,'AF' AS abbreviation,'Afeganistão' AS description
UNION ALL
SELECT 7560,'ZA','África do Sul'
UNION ALL
SELECT 9001,'AX','Aland, Ilhas'
UNION ALL
SELECT 175,'AL','Albânia'
UNION ALL
SELECT 230,'DE','Alemanha'
UNION ALL
SELECT 370,'AD','Andorra'
UNION ALL
SELECT 400,'AO','Angola'
UNION ALL
SELECT 418,'AI','Anguilla'
UNION ALL
SELECT 9002,'AQ','Antártica'
UNION ALL
SELECT 434,'AG','Antigua e Barbuda'
UNION ALL
SELECT 477,'AN','Antilhas Holandesas'
UNION ALL
SELECT 531,'SA','Arábia Saudita'
UNION ALL
SELECT 590,'DZ','Argélia'
UNION ALL
SELECT 639,'AR','Argentina'
UNION ALL
SELECT 647,'AM','Armênia'
UNION ALL
SELECT 655,'AW','Aruba'
UNION ALL
SELECT 698,'AU','Austrália'
UNION ALL
SELECT 728,'AT','Áustria'
UNION ALL
SELECT 736,'AZ','Azerbaijão'
UNION ALL
SELECT 779,'BS','Bahamas, Ilhas'
UNION ALL
SELECT 809,'BH','Bahrein, Ilhas'
UNION ALL
SELECT 817,'BD','Bangladesh'
UNION ALL
SELECT 833,'BB','Barbados'
UNION ALL
SELECT 850,'BY','Belarus'
UNION ALL
SELECT 876,'BE','Bélgica'
UNION ALL
SELECT 884,'BZ','Belize'
UNION ALL
SELECT 2291,'BJ','Benin'
UNION ALL
SELECT 906,'BM','Bermudas'
UNION ALL
SELECT 973,'BO','Bolívia'
UNION ALL
SELECT 981,'BA','Bósnia-Herzegovina'
UNION ALL
SELECT 1015,'BW','Botsuana'
UNION ALL
SELECT 9003,'BV','Bouvet, Ilhas'
UNION ALL
SELECT 1058,'BR','Brasil'
UNION ALL
SELECT 1082,'BN','Brunei'
UNION ALL
SELECT 1112,'BG','Bulgária'
UNION ALL
SELECT 310,'BF','Burkina Faso'
UNION ALL
SELECT 1155,'BI','Burundi'
UNION ALL
SELECT 1198,'BT','Butão'
UNION ALL
SELECT 1279,'CV','Cabo Verde, República de'
UNION ALL
SELECT 1457,'CM','Camarões'
UNION ALL
SELECT 1414,'KH','Camboja'
UNION ALL
SELECT 1490,'CA','Canada'
UNION ALL
SELECT 1511,NULL,'Canárias, Ilhas'
UNION ALL
SELECT 1546,'QA','Catar'
UNION ALL
SELECT 1376,'KY','Cayman, Ilhas'
UNION ALL
SELECT 1538,'KZ','Cazaquistão'
UNION ALL
SELECT 7889,'TD','Chade'
UNION ALL
SELECT 1589,'CL','Chile'
UNION ALL
SELECT 1600,'CN','China'
UNION ALL
SELECT 1635,'CY','Chipre'
UNION ALL
SELECT 5118,'CX','Christmas,Ilha (Navidad)'
UNION ALL
SELECT 1651,'CC','Cocos (Keeling), Ilhas'
UNION ALL
SELECT 1694,'CO','Colômbia'
UNION ALL
SELECT 1732,'KM','Comores, Ilhas'
UNION ALL
SELECT 1775,'CG','Congo (Brazzaville)'
UNION ALL
SELECT 8885,'CD','Congo (Kinshasa)'
UNION ALL
SELECT 1830,'CK','Cook, Ilhas'
UNION ALL
SELECT 1872,'KP','Coréia do Norte'
UNION ALL
SELECT 1902,'KR','Coréia do Sul'
UNION ALL
SELECT 1937,'CI','Costa do Marfim'
UNION ALL
SELECT 1961,'CR','Costa Rica'
UNION ALL
SELECT 1988,'KW','Coveite (Kuwait)'
UNION ALL
SELECT 1953,'HR','Croácia'
UNION ALL
SELECT 1996,'CU','Cuba'
UNION ALL
SELECT 2003,NULL,'Curaçao'
UNION ALL
SELECT 2321,'DK','Dinamarca'
UNION ALL
SELECT 7838,'DJ','Djibuti'
UNION ALL
SELECT 2356,'DM','Dominica, Ilha'
UNION ALL
SELECT 2402,'EG','Egito'
UNION ALL
SELECT 6874,'SV','El Salvador'
UNION ALL
SELECT 2445,'AE','Emirados Árabes Unidos'
UNION ALL
SELECT 2399,'EC','Equador'
UNION ALL
SELECT 2437,'ER','Eritréia'
UNION ALL
SELECT 2470,'SK','Eslovaca, República'
UNION ALL
SELECT 2461,'SI','Eslovênia'
UNION ALL
SELECT 2453,'ES','Espanha'
UNION ALL
SELECT 2496,'US','Estados Unidos'
UNION ALL
SELECT 2518,'EE','Estônia'
UNION ALL
SELECT 2534,'ET','Etiópia'
UNION ALL
SELECT 2550,'FK','Falkland (Ilhas Malvinas)'
UNION ALL
SELECT 2593,'FO','Feroe, Ilhas'
UNION ALL
SELECT 8702,'FJ','Fiji'
UNION ALL
SELECT 2674,'PH','Filipinas'
UNION ALL
SELECT 2712,'FI','Finlândia'
UNION ALL
SELECT 1619,'TW','Formosa (Taiwan)'
UNION ALL
SELECT 2755,'FR','França'
UNION ALL
SELECT 2810,'GA','Gabão'
UNION ALL
SELECT 2852,'GM','Gâmbia'
UNION ALL
SELECT 2895,'GH','Gana'
UNION ALL
SELECT 2917,'GE','Geórgia'
UNION ALL
SELECT 9011,'GS','Geórgia/Sandwich do Sul, Ilhas'
UNION ALL
SELECT 2933,'GI','Gibraltar'
UNION ALL
SELECT 2976,'GD','Granada'
UNION ALL
SELECT 3018,'GR','Grécia'
UNION ALL
SELECT 3050,'GL','Groenlândia'
UNION ALL
SELECT 3093,'GP','Guadalupe'
UNION ALL
SELECT 3131,'GU','Guam'
UNION ALL
SELECT 3174,'GT','Guatemala'
UNION ALL
SELECT 3212,'GG','Guernsey'
UNION ALL
SELECT 3379,'GY','Guiana'
UNION ALL
SELECT 3255,'GF','Guiana Francesa'
UNION ALL
SELECT 3298,'GN','Guiné'
UNION ALL
SELECT 3344,'GW','Guiné-Bissau'
UNION ALL
SELECT 3310,'GQ','Guiné-Equatorial'
UNION ALL
SELECT 3417,'HT','Haiti'
UNION ALL
SELECT 9006,'HM','Heard e Mcdonald, Ilhas'
UNION ALL
SELECT 3450,'HN','Honduras'
UNION ALL
SELECT 3514,'HK','Hong Kong'
UNION ALL
SELECT 3557,'HU','Hungria'
UNION ALL
SELECT 3573,'YE','Iêmen'
UNION ALL
SELECT 3611,'IN','Índia'
UNION ALL
SELECT 3654,'ID','Indonésia'
UNION ALL
SELECT 3727,'IR','Irã'
UNION ALL
SELECT 3697,'IQ','Iraque'
UNION ALL
SELECT 3751,'IE','Irlanda'
UNION ALL
SELECT 3794,'IS','Islândia'
UNION ALL
SELECT 3832,'IL','Israel'
UNION ALL
SELECT 3867,'IT','Itália'
UNION ALL
SELECT 3913,'JM','Jamaica'
UNION ALL
SELECT 3999,'JP','Japão'
UNION ALL
SELECT 3930,'JE','Jersey, Ilha do Canal'
UNION ALL
SELECT 3964,NULL,'Johnston, Ilhas'
UNION ALL
SELECT 4030,'JO','Jordânia'
UNION ALL
SELECT 4111,'KI','Kiribati'
UNION ALL
SELECT 4200,'LA','Laos'
UNION ALL
SELECT 4235,NULL,'Lebuan, Ilhas'
UNION ALL
SELECT 4260,'LS','Lesoto'
UNION ALL
SELECT 4278,'LV','Letônia'
UNION ALL
SELECT 4316,'LB','Líbano'
UNION ALL
SELECT 4340,'LR','Libéria'
UNION ALL
SELECT 4383,'LY','Líbia'
UNION ALL
SELECT 4405,'LI','Liechtenstein'
UNION ALL
SELECT 4421,'LT','Lituânia'
UNION ALL
SELECT 4456,'LU','Luxemburgo'
UNION ALL
SELECT 4472,'MO','Macau'
UNION ALL
SELECT 4499,'MK','Macedônia, Republica da'
UNION ALL
SELECT 4502,'MG','Madagascar'
UNION ALL
SELECT 4525,NULL,'Madeira, Ilha da'
UNION ALL
SELECT 4553,'MY','Malásia'
UNION ALL
SELECT 4588,'MW','Malavi'
UNION ALL
SELECT 4618,'MV','Maldivas'
UNION ALL
SELECT 4642,'ML','Mali'
UNION ALL
SELECT 4677,'MT','Malta'
UNION ALL
SELECT 3595,'IM','Man, Ilha de'
UNION ALL
SELECT 4723,'MP','Marianas do Norte'
UNION ALL
SELECT 4740,'MA','Marrocos'
UNION ALL
SELECT 4766,'MH','Marshall, Ilhas'
UNION ALL
SELECT 4774,'MQ','Martinica'
UNION ALL
SELECT 4855,'MU','Maurício'
UNION ALL
SELECT 4880,'MR','Mauritânia'
UNION ALL
SELECT 4885,'YT','Mayotte (Ilhas Francesas)'
UNION ALL
SELECT 9014,'UM','Menores Distantes EUA, Ilhas'
UNION ALL
SELECT 4936,'MX','México'
UNION ALL
SELECT 930,'MM','Mianmar (Birmânia)'
UNION ALL
SELECT 4995,'FM','Micronésia'
UNION ALL
SELECT 4901,NULL,'Midway, Ilhas'
UNION ALL
SELECT 5053,'MZ','Moçambique'
UNION ALL
SELECT 4944,'MD','Moldávia'
UNION ALL
SELECT 4952,'MC','Mônaco'
UNION ALL
SELECT 4979,'MN','Mongólia'
UNION ALL
SELECT 4985,'ME','Montenegro'
UNION ALL
SELECT 5010,'MS','Montserrat, Ilhas'
UNION ALL
SELECT 5070,'NA','Namíbia'
UNION ALL
SELECT 5088,'NR','Nauru'
UNION ALL
SELECT 5177,'NP','Nepal'
UNION ALL
SELECT 5215,'NI','Nicarágua'
UNION ALL
SELECT 5258,'NE','Niger'
UNION ALL
SELECT 5282,'NG','Nigéria'
UNION ALL
SELECT 5312,'NU','Niue,Ilha'
UNION ALL
SELECT 5355,'NF','Norfolk,Ilha'
UNION ALL
SELECT 5380,'NO','Noruega'
UNION ALL
SELECT 5428,'NC','Nova Caledônia'
UNION ALL
SELECT 5487,'NZ','Nova Zelândia'
UNION ALL
SELECT 5568,'OM','Omã'
UNION ALL
SELECT 5738,'NL','Países Baixos (Holanda)'
UNION ALL
SELECT 5754,'PW','Palau'
UNION ALL
SELECT 5780,'PS','Palestina'
UNION ALL
SELECT 5800,'PA','Panamá'
UNION ALL
SELECT 5452,'PG','Papua Nova Guiné'
UNION ALL
SELECT 5762,'PK','Paquistão'
UNION ALL
SELECT 5860,'PY','Paraguai'
UNION ALL
SELECT 5894,'PE','Peru'
UNION ALL
SELECT 5932,'PN','Pitcairn, Ilha'
UNION ALL
SELECT 5991,'PF','Polinésia Francesa'
UNION ALL
SELECT 6033,'PL','Polônia'
UNION ALL
SELECT 6114,'PR','Porto Rico'
UNION ALL
SELECT 6076,'PT','Portugal'
UNION ALL
SELECT 6238,'KE','Quênia'
UNION ALL
SELECT 6254,'KG','Quirguiz, República'
UNION ALL
SELECT 6289,'GB','Reino Unido'
UNION ALL
SELECT 6408,'CF','República Centro-Africana'
UNION ALL
SELECT 6475,'DO','República Dominicana'
UNION ALL
SELECT 6602,'RE','Reunião, Ilha'
UNION ALL
SELECT 6700,'RO','Romênia'
UNION ALL
SELECT 6750,'RW','Ruanda'
UNION ALL
SELECT 6769,'RU','Rússia'
UNION ALL
SELECT 6858,'EH','Saara Ocidental'
UNION ALL
SELECT 9009,'BL','Saint Barthélemy'
UNION ALL
SELECT 663,'MF','Saint-Martin (França)'
UNION ALL
SELECT 6777,'SB','Salomão, Ilhas'
UNION ALL
SELECT 6904,'WS','Samoa'
UNION ALL
SELECT 6912,'AS','Samoa Americana'
UNION ALL
SELECT 6971,'SM','San Marino'
UNION ALL
SELECT 7102,'SH','Santa Helena'
UNION ALL
SELECT 7153,'LC','Santa Lúcia'
UNION ALL
SELECT 6939,'SB','São Bartolomeu'
UNION ALL
SELECT 6955,'KN','São Cristóvão e Neves, Ilhas'
UNION ALL
SELECT 7005,'PM','São Pedro e Miquelon'
UNION ALL
SELECT 7200,'ST','São Tomé e Príncipe, Ilhas'
UNION ALL
SELECT 7056,'VC','São Vicente e Granadinas'
UNION ALL
SELECT 7285,'SN','Senegal'
UNION ALL
SELECT 7358,'SL','Serra Leoa'
UNION ALL
SELECT 7370,'RS','Sérvia'
UNION ALL
SELECT 7315,'SC','Seychelles'
UNION ALL
SELECT 7412,'SG','Singapura'
UNION ALL
SELECT 7447,'SY','Síria'
UNION ALL
SELECT 7480,'SO','Somália'
UNION ALL
SELECT 7501,'LK','Sri Lanka'
UNION ALL
SELECT 7544,'SZ','Suazilândia'
UNION ALL
SELECT 7595,'SD','Sudão'
UNION ALL
SELECT 9012,'SS','Sudão do Sul'
UNION ALL
SELECT 7641,'SE','Suécia'
UNION ALL
SELECT 7676,'CH','Suíça'
UNION ALL
SELECT 7706,'SR','Suriname'
UNION ALL
SELECT 9013,'SJ','Svalbard e Jan Mayen, Ilhas'
UNION ALL
SELECT 7722,'TJ','Tadjiquistão'
UNION ALL
SELECT 7765,'TH','Tailândia'
UNION ALL
SELECT 7803,'TZ','Tanzânia'
UNION ALL
SELECT 7919,'CZ','Tcheca, República'
UNION ALL
SELECT 9004,'TF','Terras Austrais Francesas'
UNION ALL
SELECT 7811,'TF','Terras Autrais AntarT. Frances'
UNION ALL
SELECT 7820,'IO','Território Brit.Oc.Indico'
UNION ALL
SELECT 9008,'PS','Território Palestino'
UNION ALL
SELECT 7951,'TL','Timor Leste'
UNION ALL
SELECT 8001,'TG','Togo'
UNION ALL
SELECT 8109,'TO','Tonga'
UNION ALL
SELECT 8052,'TK','Toquelau,Ilhas'
UNION ALL
SELECT 8150,'TT','Trinidad e Tobago'
UNION ALL
SELECT 8206,'TN','Tunísia'
UNION ALL
SELECT 8230,'TC','Turcas e Caicos, Ilhas'
UNION ALL
SELECT 8249,'TM','Turcomenistão'
UNION ALL
SELECT 8273,'TR','Turquia'
UNION ALL
SELECT 8281,'TV','Tuvalu'
UNION ALL
SELECT 8311,'UA','Ucrânia'
UNION ALL
SELECT 8338,'UG','Uganda'
UNION ALL
SELECT 8451,'UY','Uruguai'
UNION ALL
SELECT 8478,'UZ','Uzbequistão'
UNION ALL
SELECT 5517,'VU','Vanuatu'
UNION ALL
SELECT 8486,'VA','Vaticano, Estado Cidade'
UNION ALL
SELECT 8508,'VE','Venezuela'
UNION ALL
SELECT 8583,'VN','Vietnã'
UNION ALL
SELECT 8630,'VG','Virgens,Ilhas (Britânicas)'
UNION ALL
SELECT 8664,'VI','Virgens,Ilhas (E.U.A.)'
UNION ALL
SELECT 8737,NULL,'Wake, Ilha'
UNION ALL
SELECT 9015,'WF','Wallis e Futuna, Ilhas'
UNION ALL
SELECT 8907,'ZM','Zâmbia'
UNION ALL
SELECT 6653,'ZW','Zimbábue'
