SELECT
    CONCAT(id_invoice, "-", DATE_FORMAT(dt_reference, 'yyyyMMdd')) AS sk_overdue_portfolio_timeline,
    id_contract,
    id_invoice,
    id_proposal,
    contract_status,
    invoice_type,
    payment_status,
    debtor_type,
    delay_contamined_range,
    contract_overdue_invoices,
    due_amount,
    paid_amount,
    recovered_amount,
    contract_debt,
    business_day,
    is_last_business_days,
    dt_invoice_paid,
    dt_invoice_due,
    dt_invoice_due_adjust,
    dt_month_start,
    dt_month_end,
    dt_reference,
    NOW() AS ts_load
FROM datalake_invoice.overdue_portfolio_timeline
