SELECT
  id,
  houseId AS id_house,
  listingBusinessContextId AS id_listing_business_context,
  dynamicPricingParameterId AS id_dynamic_pricing_parameter,
  REV AS rev,
  REVTYPE AS rev_type,
  status,
  operationmode AS operation_mode,
  origin,
  minRent AS min_rent,
  initialRent AS initial_rent,
  priceChangesOccurred AS occurred_price_changes,
  prepublicationrentprobability AS pre_publication_rent_probability,
  enabled AS is_enabled,
  listingBusinessContextId_MOD AS mod_listing_business_context,
  dynamicPricingParameterId_MOD AS mod_dynamic_pricing_parameter,
  status_MOD AS mod_status,
  operationmode_mod AS mod_operation_mode,
  origin_mod AS mod_origin,
  priceChangesOccurred_MOD AS mod_price_changes_occurred,
  prepublicationrentprobability_mod AS mod_pre_publication_rent_probability,
  enabled_MOD AS mod_is_enabled,
  activatedAt_MOD AS mod_dt_activated,
  deactivatedAt_MOD AS mod_dt_deactivated,
  lastPriceUpdate AS dt_last_price_updated,
  activatedAt AS dt_activated,
  deactivatedAt AS dt_deactivated
FROM
    datalake_ebdb_raw.dynamicpricinghouse_aud
