SELECT
    id,
    idempresa AS id_company,
    idcredor AS id_creditor,
    iddevedor AS id_debtor,
    id_correcao_mon AS id_monetary_correction,
    cod_ext AS id_recupera_installment,
    processo AS process,
    negociador AS negotiator,
    status,
    usuario_cancelamento AS cancellation_user,
    juros_porcento AS percent_fee,
    multa_porcento AS percent_fine,
    honorarios_porcento AS percent_honorary,
    mora_porcento AS percent_default,
    desc_capital_porcento AS percent_capital_discount,
    taxa_contrato_porcento AS percent_contract_tax,
    taxa_pd_porcento AS percent_pd_tax,
    tot_capital AS total_capital,
    tot_capital_liq AS total_net_capital,
    tot_protesto AS total_protest,
    tot_taxa AS total_tax,
    tot_juros AS total_fee,
    tot_multa AS total_fine,
    tot_ho AS total__ho,
    tot_sem_mora AS total_without_default,
    tot_com_mora AS total_with_default,
    saldo_capital_liq AS balance_net_capital,
    data_acordo AS dt_agreement,
    data_calc AS dt_calc,
    data_cancelamento AS dt_cancellation,
    last_update AS ts_updated
FROM
    datalake_iaf_raw.vi_319_tb_acordo
