SELECT
    id,
    idempresa AS id_company,
    idboleto AS id_invoice,
    idcampanha AS id_campaign,
    id_correcao_mon AS id_monetary_correction,
    idcontrato AS id_contract,
    idcampanha2 AS id_campaign_2,
    idcampanha2ck AS id_campaign_2_ck,
    idboleto_bloq AS id_invoice_blocked,
    p_codigoid AS id_code,
    codigo AS code,
    razaosocial AS corporate_name,
    fantasia AS fantasy_name,
    cnpj,
    ie,
    endereco AS address,
    end_numero AS address_number,
    end_bairro AS neighborhood,
    end_cep  AS zip_code,
    end_cidade AS city,
    end_uf AS uf,
    fone1 AS first_phone,
    fone2 AS second_phone,
    email1 AS first_email,
    email2 AS second_email,
    obs,
    obs_cob,
    ac_login AS login,
    ac_senha AS password,
    ac_email AS ac_email,
    consultor AS consultant,
    atividade AS activity,
    p_banco AS bank,
    p_agencia AS agency,
    p_conta AS account,
    p_obs AS obs_p,
    p_email AS p_email,
    p_frequencia AS frequency,
    prazo_perm AS term,
    grupo AS group,
    end_compl AS address_complement,
    status,
    ultimo_acesso AS last_access,
    p_envionf AS shipping,
    p_modalidade AS modality,
    param_status_proc,
    param_status_oco,
    consultor2 AS consultant_2,
    contabilizar_comissoes AS account_commissions,
    cod_ext,
    p_modelo AS model,
    districk,
    layout_imp,
    bol_cedente AS assignor,
    bol_cedente_cnpj AS assignor_cnpj,
    a_quebra_acordo AS breaks_deal,
    a_quebra_dias AS breaks_days,
    usuario_cad AS user_cad,
    usuario_alt AS user_alt,
    segmento AS segment,
    bloq_pc AS block_pc,
    qtde_parc AS installment_amount,
    conf_div,
    conf_inov,
    ativa_acordo AS activate_agreement,
    vl_desconto_min AS min_discount_value,
    vl_desconto AS discount_value,
    vl_juros AS fee_value,
    vl_multa AS fine_value,
    vl_honorarios AS honorary_value,
    vl_pd AS pd_value,
    vl_contrato AS contract_value,
    vl_multa_min AS min_fine_value,
    vl_juros_min AS min_fee_value,
    vl_honorarios_min AS min_honorary_value,
    vl_cobranca AS charge_value,
    data_cad AS dt_cad,
    data_alt AS dt_alt,
    last_update AS ts_updated
FROM
    datalake_iaf_raw.vi_319_tb_credor
