SELECT
    id,
    idempresa AS id_company,
    idpc_old AS id_pc_old,
    idcredor AS id_creditor,
    codigo AS code,
    obs,
    nrepasse AS number_pass_through,
    status,
    forma_repasse AS pass_through_type,
    usuario_auditoria AS audit_user,
    localpagto AS payment_local,
    total_taxa_adm AS total_tax_adm,
    conf_status,
    conf_usuario AS conf_user,
    conf_obs,
    retemail AS ret_email,
    usuario_cad AS user_cad,
    usuario_alt AS user_alt,
    total_credito AS total_credit,
    total_taxa_contr AS total_tax_contr,
    total_repasse AS total_pass_through,
    total_outros_debitos AS total_other_debts,
    total_hon AS total_honorary,
    total_pd,
    data_rec AS dt_rec,
    data_cad AS dt_cad,
    data_auditoria AS dt_audit,
    last_update AS ts_updated
FROM
    datalake_iaf_raw.vi_319_tb_prestacao
