SELECT
    id,
    idempresa AS id_company,
    idcredor AS id_creditor,
    iddevedor AS id_debtor,
    idtitulo_old AS id_old_title,
    processo AS process,
    NULLIF(valor, 'NaN') AS value,
    usuario_cad AS user_cad,
    usuario_tipo AS user_type,
    ntitulo AS title_number,
    parcela AS installment,
    especie AS type,
    protesto AS protest,
    status,
    obs,
    codimp AS imp_code,
    status_bkp,
    moeda AS currency,
    NULLIF(valor_old, 'NaN') AS old_value,
    info1 AS info_1,
    info2 AS info_2,
    info3 AS info_3,
    cod_dev_get,
    campo1 AS field_1,
    campo2 AS field_2,
    campo3 AS field_3,
    campo4 AS field_4,
    campo5 AS field_5,
    campo6 AS field_6,
    campo7 AS field_7,
    campo8 AS field_8,
    campo9 AS field_9,
    campo10 AS field_10,
    data_baixa AS dt_write_off,
    data_cad AS dt_cad,
    data_rem AS dt_rem,
    data_doc AS dt_doc,
    data_quit AS dt_quit,
    data_dev AS dt_dev,
    vencimento AS dt_due,
    data_atualiza AS dt_update,
    last_update AS ts_updated
FROM
    datalake_iaf_raw.vi_319_tb_titulos
