SELECT
    id,
    organization_id AS id_organization,
    created_by_id AS id_created_by,
    description,
    label_config,
    expert_instruction,
    model_version,
    title,
    maximum_annotations,
    data_types,
    min_annotations_to_start_training,
    sampling,
    task_data_login,
    task_data_password,
    overlap_cohort_percentage,
    control_weights,
    token,
    result_count,
    color,
    skip_queue,
    parsed_label_config,
    is_published,
    is_draft,
    enable_empty_annotation AS is_empty_annotation_enabled,
    show_instruction AS has_instruction,
    show_annotation_history AS has_annotation_history,
    show_collab_predictions AS has_collab_predictions,
    show_ground_truth_first AS has_ground_truth_first,
    show_overlap_first AS has_overlap_first,
    show_skip_button AS has_skip_button,
    evaluate_predictions_automatically AS has_auto_evaluate_predictions,
    reveal_preannotations_interactively AS has_interactive_reveal_preannotations,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_quinturk_test_raw.project
