SELECT
    id,
    related_document_id AS id_related_document,
    due_amount,
    due_date AS dt_due,
    timestamp(issue_date_time) AS ts_issued,
    company_use,
    our_number,
    one_day_interest,
    fine_due_date AS dt_fine_due,
    fine_amount,
    occurrence_code,
    occurrence_reason,
    payer_name,
    payer_document,
    payer_address,
    payer_neighborhood,
    payer_zipcode,
    payer_city,
    payer_state,
    timestamp(created_at) AS ts_created,
    timestamp(updated_at) AS ts_updated,
    status,
    paid_at AS dt_paid,
    paid_amount,
    requested_by,
    related_document_type,
    original_response,
    interest,
    related_document_status,
    document_number,
    bank_boleto_id AS id_bank_boleto,
    timestamp(credit_date) AS ts_credited
FROM
    datalake_vans_raw.boleto
