select
    id,
    related_document_id as id_related_document,
    due_amount,
    due_date as dt_due, 
    timestamp(issue_date_time) as ts_issued,
    company_use,
    our_number,
    one_day_interest,
    fine_due_date as dt_fine_due,
    fine_amount,
    occurrence_code,
    sha2(payer_name,256) as payer_name, 
    sha2(payer_document,256) as payer_document,
    sha2(payer_address,256) as payer_address,
    sha2(payer_neighborhood,256) as payer_neighborhood,
    sha2(payer_zipcode,256) as payer_zipcode,
    sha2(payer_city,256) as payer_city,
    sha2(payer_state,256) as payer_state,
    timestamp(created_at) as ts_created, 
    timestamp(updated_at) as ts_updated, 
    status,
    paid_at as dt_paid, 
    paid_amount, 
    requested_by, 
    related_document_type,
    original_response,
    interest, 
    related_document_status, 
    document_number, 
    bank_boleto_id as id_bank_boleto, 
    timestamp(credit_date) as ts_credited    
from
    datalake_vans_raw.boleto