SELECT
    id,
    bank_payment_id AS id_bank_payment,
    file_id AS id_file,
    payment_id AS id_payment,
    related_document_id AS id_related_document,
    company_use,
    our_number,
    paid_amount,
    due_amount,
    bank_payment_code,
    occurrence_code,
    payee_bank_code
    payee_account,
    payee_agency,
    payee_document,
    payee_name,
    payee_bank_info_status,
    related_document_type,
    related_document_status,
    requested_by,
    occurrence_reason,
    original_response,
    return_file_number,
    status,
    style,
    type,
    payee_savings_acc AS is_payee_savings_acc,
    TO_DATE(return_file_date, 'yyMMdd') AS dt_return_file,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated,
    TIMESTAMP(created_at_payment) AS ts_payment_created,
    TIMESTAMP(issue_date_time) AS ts_issued,
    TIMESTAMP(due_date) AS ts_due,
    TIMESTAMP(paid_at) AS ts_paid,
    year,
    month,
    day,
    hour
FROM
    datalake_vans_raw.payment_status_log
