SELECT
    id,
    related_document_id AS id_related_document,
    bank_payment_id AS id_bank_payment,
    due_amount,
    due_date AS dt_dued,
    timestamp(issue_date_time) AS ts_issued,
    company_use,
    our_number,
    occurrence_code,
    occurrence_reason,
    payee_name,
    payee_document,
    payee_agency,
    payee_account,
    boolean(payee_savings_acc) AS has_payee_savings_acc,
    payee_bank_code,
    timestamp(created_at) AS ts_created,
    timestamp(updated_at) AS ts_updated,
    status,
    paid_at AS dt_paid,
    requested_by,
    related_document_type,
    original_response,
    related_document_status,
    paid_amount,
    bank_payment_code,
    type
FROM
    datalake_vans_raw.payment
