SELECT
  ler_id AS id_life_event_reason,
  business_group_id AS id_business_group,
  name AS life_event_reason_name,
  typ_cd AS type_code,
  tmlns_eval_cd AS timelines_evaluation_code,
  slctbl_slf_svc_cd AS selectable_self_service_code,
  prod_cd AS product_code,
  created_by AS created_by,
  last_updated_by AS updated_by,
  desc_txt AS description,
  CAST(tmlns_dys_num AS INT) AS days_timeliness,
  CAST(object_version_number AS INT) AS object_version_number,
  ck_rltd_per_elig_flag = 'Y' AS is_check_related_person_eligibility,
  cm_aply_flag = 'Y' AS is_communications_apply,
  ovridg_le_flag = 'Y' AS is_overriding_life_event,
  qualg_evt_flag = 'Y' AS is_qualifying_event,
  global_flag = 'Y' AS is_global,
  self_assigned_event_flag = 'Y' AS is_self_assigned_event,
  TO_DATE(effective_start_date) AS dt_effective_started,
  TO_DATE(effective_end_date) AS dt_effective_ended,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load
FROM
  datalake_pin_benefits_raw.ben_ler_f
