SELECT
  prtt_rt_val_id AS id_participant_rate_value,
  business_group_id AS id_business_group,
  prtt_enrt_rslt_id AS id_participant_enrollment_result,
  acty_base_rt_id AS id_activity_base_rate,
  per_in_ler_id AS id_period_in_life_event_reason,
  ended_per_in_ler_id AS id_ended_period_in_life_event_reason,
  tx_typ_cd AS transaction_type_code,
  acty_typ_cd AS activity_type_code,
  mlt_cd AS multiplier_code,
  acty_ref_perd_cd AS activity_reference_period_code,
  cmcd_ref_perd_cd AS communicated_reference_period_code,
  rate_display_cd AS rate_display_code,
  created_by AS created_by,
  last_updated_by AS updated_by,
  CAST(object_version_number AS INT) AS object_version_number,
  CAST(rt_val AS DECIMAL(10,2)) AS rate_value,
  CAST(ann_rt_val AS DECIMAL(10,2)) AS annual_rate_value,
  CAST(cmcd_rt_val AS DECIMAL(10,2)) AS communicated_rate_value,
  CAST(pp_in_yr_used_num AS INT) AS used_pay_periods_in_year,
  dsply_on_enrt_flag = 'Y' AS is_display_on_enrollment,
  rt_ovridn_flag = 'Y' AS is_rate_overridden,
  TO_DATE(rt_strt_dt) AS dt_rate_started,
  TO_DATE(rt_end_dt) AS dt_rate_ended,
  TO_DATE(ended_rate_thru_dt) AS dt_rate_through_ended,
  TO_DATE(elctns_made_dt) AS dt_elections_made,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_benefits_raw.ben_prtt_rt_val
