SELECT
  elig_per_elctbl_chc_id AS id_eligible_person_electable_choice,
  benefit_relation_id AS id_benefit_relation,
  pl_id AS id_plan,
  oipl_id AS id_option_in_plan,
  pl_typ_id AS id_plan_type,
  per_in_ler_id AS id_period_in_life_event_reason,
  yr_perd_id AS id_year_period,
  pil_elctbl_chc_popl_id AS id_electable_choice_population,
  business_group_id AS id_business_group,
  opt_id AS id_option,
  prtt_enrt_rslt_id AS id_participant_enrollment_result,
  enrt_cvg_strt_dt_cd AS enrollment_coverage_start_date_code,
  comp_lvl_cd AS compensation_level_code,
  inelig_rsn_cd AS ineligible_reason_code,
  admin_category_cd AS admin_category_code,
  ss_category_cd AS self_service_category_code,
  created_by AS created_by,
  last_updated_by AS updated_by,
  CAST(oipl_ordr_num AS INT) AS option_in_plan_order_number,
  CAST(object_version_number AS INT) AS object_version_number,
  roll_crs_flag = 'Y' AS is_roll_across,
  crntly_enrd_flag = 'Y' AS is_currently_enrolled,
  dflt_flag = 'Y' AS is_default,
  elctbl_flag = 'Y' AS is_electable,
  mndtry_flag = 'Y' AS is_mandatory,
  alws_dpnt_dsgn_flag = 'Y' AS is_allows_dependent_designation,
  auto_enrt_flag = 'Y' AS is_auto_enrollment,
  ctfn_rqd_flag = 'Y' AS is_certification_required,
  in_pndg_wkflow_flag = 'Y' AS is_in_pending_workflow,
  elig_flag = 'Y' AS is_eligible,
  svngs_pln_flag = 'Y' AS is_savings_plan,
  misc_pln_flag = 'Y' AS is_miscellaneous_plan,
  interim_flag = 'Y' AS is_interim,
  cvrd_flag = 'Y' AS is_covered,
  TO_DATE(enrt_cvg_strt_dt) AS dt_enrollment_coverage_started,
  TO_DATE(procg_end_dt) AS dt_processing_ended,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  TO_TIMESTAMP(program_update_date) AS ts_program_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_benefits_raw.ben_elig_per_elctbl_chc
