SELECT
  per_in_ler_id AS id_person_in_life_event_reason,
  benefit_relation_id AS id_benefit_relation,
  business_group_id AS id_business_group,
  ler_id AS id_life_event_reason,
  person_id AS id_person,
  ptnl_ler_for_per_id AS id_potential_life_event_reason_for_person,
  legal_entity_id AS id_legal_entity,
  request_id AS id_request,
  per_in_ler_stat_cd AS person_in_life_event_status_code,
  ler_type_cd AS life_event_reason_type_code,
  prod_cd AS product_code,
  job_definition_name,
  job_definition_package,
  created_by,
  last_updated_by AS updated_by,
  CAST(object_version_number AS INT) AS object_version_number,
  TO_DATE(lf_evt_ocrd_dt) AS dt_life_event_occurred,
  TO_DATE(procd_dt) AS dt_processed,
  TO_DATE(strtd_dt) AS dt_started,
  TO_DATE(ntfn_dt) AS dt_notified,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  TO_TIMESTAMP(program_update_date) AS ts_program_updated,
  NOW() AS ts_load
FROM
  datalake_pin_benefits_raw.ben_per_in_ler
