SELECT
  pl_id AS id_plan,
  pl_typ_id AS id_plan_type,
  business_group_id AS id_business_group,
  pl_cd AS plan_code,
  enrt_mthd_cd AS enrollment_method_code,
  enrt_cvg_strt_dt_cd AS enrollment_coverage_start_date_code,
  enrt_cvg_end_dt_cd AS enrollment_coverage_end_date_code,
  nip_dflt_enrt_cd AS not_in_program_default_enrollment_code,
  dpnt_cvg_end_dt_cd AS dependent_coverage_end_date_code,
  dpnt_cvg_strt_dt_cd AS dependent_coverage_start_date_code,
  nip_acty_ref_perd_cd AS not_in_program_activity_reference_period_code,
  nip_enrt_info_rt_freq_cd AS not_in_program_enrollment_information_rate_frequency_code,
  pl_stat_cd AS plan_status_code,
  rt_end_dt_cd AS rate_end_date_code,
  rt_strt_dt_cd AS rate_start_date_code,
  subj_to_imptd_incm_cd AS subject_to_imputed_income_code,
  short_code,
  function_code,
  name AS plan_name,
  short_name,
  created_by AS created_by,
  last_updated_by AS updated_by,
  nip_pl_uom AS not_in_program_plan_unit_of_measure,
  CAST(object_version_number AS INT) AS object_version_number,
  uses_cir = 'Y' AS is_uses_compensation_information_reporting,
  alws_qdro_flag = 'Y' AS is_allows_qualified_domestic_relations_order,
  alws_qmcso_flag = 'Y' AS is_allows_qualified_medical_child_support_order,
  alws_reimbmts_flag = 'Y' AS is_allows_reimbursements,
  asnt_rqd_for_enrt_flag = 'Y' AS is_assent_required_for_enrollment,
  bnf_addl_instn_alwd_flag = 'Y' AS is_beneficiary_additional_instruction_allowed,
  bnf_adrs_rqd_flag = 'Y' AS is_beneficiary_address_required,
  bnf_cntngt_bnfs_alwd_flag = 'Y' AS is_beneficiary_contingent_benefits_allowed,
  bnf_ctfn_rqd_flag = 'Y' AS is_beneficiary_certification_required,
  bnf_dob_rqd_flag = 'Y' AS is_beneficiary_date_of_birth_required,
  bnf_dsge_mnr_ttee_rqd_flag = 'Y' AS is_beneficiary_designee_minor_trustee_required,
  bnf_legv_id_rqd_flag = 'Y' AS is_beneficiary_legislative_id_required,
  bnf_may_dsgt_org_flag = 'Y' AS is_beneficiary_may_designate_organization,
  bnf_qdro_rl_apls_flag = 'Y' AS is_beneficiary_qualified_domestic_relations_order_rule_applies,
  drvbl_fctr_apls_rts_flag = 'Y' AS is_derivable_factor_applies_rates,
  drvbl_fctr_prtn_elig_flag = 'Y' AS is_derivable_factor_participation_eligibility,
  elig_apls_flag = 'Y' AS is_eligibility_applies,
  invk_dcln_prtn_pl_flag = 'Y' AS is_invoke_decline_participation_plan,
  invk_flx_cr_pl_flag = 'Y' AS is_invoke_flexible_credit_plan,
  invk_imptd_incm_pl_flag = 'Y' AS is_invoke_imputed_income_plan,
  drvbl_dpnt_elig_flag = 'Y' AS is_derivable_dependent_eligibility,
  trk_inelig_per_flag = 'Y' AS is_track_ineligible_person,
  dmstc_prtr_rt_trtmt_flag = 'Y' AS is_domestic_partner_rate_treatment,
  dpnt_cvd_by_othr_apls_flag = 'Y' AS is_dependent_covered_by_other_applies,
  frfs_aply_flag = 'Y' AS is_forfeitures_apply,
  hc_pl_subj_hcfa_aprvl_flag = 'Y' AS is_health_care_plan_subject_to_approval,
  hghly_cmpd_rl_apls_flag = 'Y' AS is_highly_compensated_rule_applies,
  mx_wtg_perd_prte_apls_flag = 'Y' AS is_maximum_waiting_period_participation_applies,
  dpnt_leg_id_rqd_flag = 'Y' AS is_dependent_legislative_id_required,
  dpnt_no_ctfn_rqd_flag = 'Y' AS is_dependent_no_certification_required,
  no_mn_opts_num_apls_flag = 'Y' AS is_no_minimum_options_number_applies,
  no_mx_opts_num_apls_flag = 'Y' AS is_no_maximum_options_number_applies,
  prtn_elig_ovrid_alwd_flag = 'Y' AS is_participation_eligibility_override_allowed,
  svgs_pl_flag = 'Y' AS is_savings_plan,
  subj_to_imput_inc_flag = 'Y' AS is_subject_to_imputed_income,
  use_all_asnts_elig_flag = 'Y' AS is_use_all_assignments_eligibility,
  use_all_asnts_for_rt_flag = 'Y' AS is_use_all_assignments_for_rate,
  vstg_apls_flag = 'Y' AS is_vesting_applies,
  wvbl_flag = 'Y' AS is_waiveable,
  enrl_pl_opt_flag = 'Y' AS is_enroll_plan_option,
  may_enrl_pl_n_oipl_flag = 'Y' AS is_may_enroll_plan_and_option_in_plan,
  alws_unrstrctd_enrt_flag = 'Y' AS is_allows_unrestricted_enrollment,
  nip_dflt_flag = 'Y' AS is_not_in_program_default,
  alws_tmpry_id_crd_flag = 'Y' AS is_allows_temporary_id_card,
  post_to_gl_flag = 'Y' AS is_post_to_general_ledger,
  pl_yr_not_applcbl_flag = 'Y' AS is_plan_year_not_applicable,
  susp_if_ctfn_not_prvd_flag = 'Y' AS is_suspend_if_certification_not_provided,
  susp_if_ctfn_not_bnf_flag = 'Y' AS is_suspend_if_certification_not_beneficiary,
  global_flag = 'Y' AS is_global,
  dsgn_self_as_bnf_flag = 'Y' AS is_designate_self_as_beneficiary,
  TO_DATE(effective_start_date) AS dt_effective_started,
  TO_DATE(effective_end_date) AS dt_effective_ended,
  TO_DATE(incptn_dt) AS dt_inception,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_benefits_raw.ben_pl_f