SELECT
    NULLIF(id_csat, '') AS id_csat,
    INT(NULLIF(contractid, '')) AS id_contract,
    INT(NULLIF(id_vistoriador, '')) AS id_inspector,
    NULLIF(email, '') AS email,
    NULLIF(microtag_1, '') AS microtag_1,
    NULLIF(macrotag_1, '') AS macrotag_1,
    NULLIF(microtag_2, '') AS microtag_2,
    NULLIF(macrotag_2, '') AS macrotag_2,
    NULLIF(microtag_3, '') AS microtag_3,
    NULLIF(macrotag_3, '') AS macrotag_3,
    NULLIF(description, '') AS description,
    NULLIF(company, '') AS company,
    NULLIF(internal_observation, '') AS internal_observation,
    NULLIF(app_evaluation, '') AS app_evaluation,
    INT(NULLIF(general_satisfaction_evaluation, '')) AS general_satisfaction_evaluation,
    INT(NULLIF(report_pictures_evaluation, '')) AS report_pictures_evaluation,
    INT(NULLIF(inspection_deadline_evaluation, '')) AS inspection_deadline_evaluation,
    INT(NULLIF(report_deadline_evaluation, '')) AS report_deadline_evaluation,
    INT(NULLIF(inspectors_comments_evaluation, '')) AS inspectors_comments_evaluation,
    BOOLEAN(NULLIF(is_1_positive, '')) AS is_tag_1_positive,
    BOOLEAN(NULLIF(is_2_positive, '')) AS is_tag_2_positive,
    BOOLEAN(NULLIF(is_3_positive, '')) AS is_tag_3_positive,
    BOOLEAN(NULLIF(is_tag_ok, '')) AS is_tag_ok,
    BOOLEAN(NULLIF(is_repair_needed, '')) AS is_repair_needed,
    TIMESTAMP(CONCAT(LEFT(NULLIF(ts_utc_start_date, ''),10),' ', RIGHT(NULLIF(ts_utc_start_date, ''),8)) ) AS ts_utc_started,
    TIMESTAMP(CONCAT(LEFT(NULLIF(ts_utc_submit_date, ''),10),' ', RIGHT(NULLIF(ts_utc_submit_date, ''),8)) ) AS ts_utc_submitted
FROM
    datalake_gsheets_raw.csat_vistoria_saida 