SELECT
    city_group,
    first_listing,
    mkt_channel,
    mkt_origin,
    operacao,
    opportunities,
    prospect,
    qualified,
    available_qualifieds,
    week,
    week_origin,
    year
FROM
    datalake_gsheets_raw.rental_cohort_supply
