SELECT
    id,
    contract_id AS id_contract,
    exit_inspection_id AS id_exit_inspection,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    feedback,
    tenant_keys_location,
    owner_keys_location,
    status,
    internal_status,
    source,
    requested_by,
    responsible_off_manager_email,
    responsible_off_manager_email_mod AS mod_responsible_off_manager_email,
    date AS dt_termination,
    vacancy_date AS dt_vacancy,
    canceled_at AS ts_canceled,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_terminator_raw.termination_aud
