SELECT
    id_task,
    id_hubspot_owner,
    ids_associated_tickets,
    ids_associated_contacts,
    ids_associated_companies,
    ids_associated_deals,
    task_body,
    task_subject,
    task_status,
    task_type,
    task_priority,
    ts_task_due_date,
    ts_created,
    ts_updated,
    year,
    month,
    day
FROM
    datalake_hubspot.task_history
QUALIFY
    ROW_NUMBER() OVER(PARTITION BY id_task ORDER BY ts_updated DESC) = 1
