SELECT
  id_unidade AS id_unit,
  id_idactum,
  bpatri_key AS id_patrimonial_assets, 
  chave_lote AS id_lot,
  NULLIF(NULLIF(TRIM(cartorio), 'nan'), '') AS real_estate_register,
  NULLIF(NULLIF(TRIM(matricula), '<NA>'), '') AS real_estate_registry,
  NULLIF(ano_construcao_ajustado, 0) AS building_year,
  NULLIF(n_pavimentos, -1) AS number_of_floors,
  andar_unidade AS floor,
  banheiros AS bathrooms_count,
  quartos AS bedrooms_count,
  suites AS suites_count,
  vagas AS parking_slots,
  m2_terreno AS lot_area,
  m2_ocupada AS occupied_area,
  m2_testada AS tested_area,
  m2_construido AS built_area,
  m2_construido_ajustado AS built_area_with_parking_slots,
  m2_privativo AS private_area,
  valor_m2_terreno AS assessed_market_value_per_lot_area,
  valor_m2_construido AS assessed_market_value_per_built_area,
  valor_venal AS assessed_market_value,
  valor_venal_ano AS assessed_market_value_year_reference,
  valor_iptu AS iptu_value,
  fracao_ideal AS fractional_share,
  NULLIF(TRIM(cep_original), '') AS zipcode,
  logradouro_original AS source_street,
  NULLIF(TRIM(`número`), '') AS address_number,
  NULLIF(TRIM(complemento), '') AS address_details,
  NULLIF(TRIM(bloco), '') AS address_details_building,
  unidade AS address_details_unit,
  `UF Correios` AS postal_state_code,
  NULLIF(TRIM(`Bairro Correios`), '') AS postal_neighborhood_name,
  NULLIF(TRIM(`Logradouro Correios`), '') AS postal_street_name,
  latitude,
  longitude,
  m2_privativo_estimado AS private_area_estimated,
  zona_censitaria_codigo AS census_tract_code,
  zona_censitaria_situacao AS census_tract_status,
  zona_censitaria_tipo AS census_tract_type,
  zona_censitaria_desc_situacao AS census_tract_status_description,
  zona_censitaria_desc_tipo AS census_tract_type_description,
  `zona_censitária` AS census_tract,
  `zona_censitária_renda_media_responsavel` AS census_tract_income_avg,
  `zona_censitária_renda_media_desvio_padrao` AS census_tract_income_standard_deviation,
  transacao_mais_recente_valor_total AS latest_transaction_value,
  Sgl_zona AS zone_code,
  price_ref_estimate_michel AS idactum_price_estimation,
  perc_abs_deviation_estimate_michel AS idactum_price_estimation_percentage_absolute_deviation,
  valorizacao_media_anual AS average_annual_appreciation,
  estimativa_ipatri_regra AS idactum_market_price_estimation_score,
  estimativa_ipatri AS idactum_market_price_estimation,
  qtd AS quantity,
  iptu_isento AS is_iptu_exempt, 
  NULLIF(TRIM(finalidade), '') AS usage_purpose,
  NULLIF(TRIM(tipo_de_construcao), '') AS building_type,
  NULLIF(TRIM(tipo_de_uso), '') AS usage_type,
  vertical AS is_vertical_property,
  tipologia AS typology,
  transacao_mais_recente_envolve_garagem AS is_parking_slots_in_latest_transaction,
  SIRGAS_SHP_loteamento AS is_house_in_sp_popular_lot_program,
  SIRGAS_SHP_nucleo AS is_informal_housing_nucleus_sp,
  SIRGAS_SHP_favela AS is_house_in_sp_favela,
  SIRGAS_SHP_cortico AS is_house_in_sp_cortico,
  VILA_FAVELA AS is_house_in_bh_favela,
  OCUPACAO_LOTEAMENTO_IRREGULAR AS is_informal_housing_nucleus_bh,
  CONJUNTO_HABITACIONAL AS is_public_housing_bh,
  dt_load,
  CAST(transacao_mais_recente AS TIMESTAMP) AS ts_latest_transaction_date
FROM
  datalake_idactum_registrations_raw.idactum_registrations
