WITH aggregate_metrics AS (
    SELECT
        id_customer,
        id_contract,
        id_operator,
        operator_agency,
        creditor,
        action,
        action_code_type,
        action_description,
        result,
        result_code_type,
        result_description,
        complement,
        complement_code_type,
        complement_description,
        source,
        DATE(ts_occurrence) AS dt_occurrence,
        SUM(IFNULL(esforco,0)) AS total_esforco,
        SUM(IFNULL(alo,0)) AS total_alo,
        SUM(IFNULL(cpc,0)) AS total_cpc,
        SUM(IFNULL(promisse,0)) AS total_promisse,
        SUM(IFNULL(agreement,0)) AS total_agreement,
        SUM(IFNULL(agreement,0)) AS total_failure
    FROM datalake_collections_quintoandar.collection_events
    GROUP BY ALL
)
SELECT
     md5(CONCAT(COALESCE(id_customer,0), COALESCE(id_contract,0), creditor, COALESCE(id_operator, ''),
                COALESCE(action, ''), COALESCE(result, ''), COALESCE(complement, ''), dt_occurrence)) AS sk_collection,
    id_customer AS sk_debtor,
    id_contract AS sk_contract,
    id_operator AS sk_operator,
    operator_agency,
    creditor,
    action,
    action_code_type,
    action_description,
    result,
    result_code_type,
    result_description,
    complement,
    complement_code_type,
    complement_description,
    dt_occurrence,
    total_esforco,
    total_alo,
    total_cpc,
    total_promisse,
    total_agreement,
    total_failure,
    source,
    NOW() AS ts_load,
    YEAR(dt_occurrence) AS year,
    MONTH(dt_occurrence) AS month,
    DAY(dt_occurrence) AS day
FROM aggregate_metrics
