SELECT
    id_sync_sap_job,
    id_feature,
    id_consolidated,
    `hash`,
    idoc,
    response,
    `type`,
    `status`,
    erp_solution,
    sap_payload,
    charge_back_of,
    error,
    retryable,
    num_retry,
    ts_updated_from_webhook,
    ts_synced,
    ts_created,
    ts_updated,
    year,
    month,
    day
FROM
    datalake_sap_gateway_clean.sync_sap_job
QUALIFY
    ROW_NUMBER() OVER (PARTITION BY id_sync_sap_job ORDER BY ts_updated DESC) = 1
