SELECT
    id,
    house_id AS id_house,
    photographer_job_id AS id_photographer_job,
    analyst_queue,
    photographer_comment,
    plaque_condition,
    plaque_code,
    plaque_location,
    plaque_issue,
    lockbox_condition,
    lockbox_comment,
    link_video,
    owner_description_analysis,
    final_classification,
    analyst_comment,
    ai_score,
    images_per_room,
    num_internal_photos,
    num_bathroom_photos,
    illegible_plaque AS has_illegible_plaque,
    has_lockbox,
    has_video,
    fraud_report AS has_fraud_report,
    reason_unpublish,
    criadoEm AS ts_created,
    atualizadoEm AS ts_updated,
    edited_by
FROM
    datalake_ebdb_raw.listingquality
