WITH occurrences_last_version AS (
    SELECT
        ROW_NUMBER() OVER(PARTITION BY id_issue ORDER BY ts_updated DESC) AS ordered_version,
        id_airtable_record,
        id_agent,
        id_issue,
        department,
        description,
        ql_agent_complete_name,
        ql_agent_region,
        ql_agent_segment,
        ql_ocorrency_category,
        ql_occorency_type,
        ql_resolution,
        ql_ticket_from,
        responsible,
        summary,
        who_is_complaining,
        ts_created,
        ts_updated,
        year,
        month,
        day
    FROM
        datalake_airtable_clean.cr_occurrences
)
SELECT
    id_airtable_record,
    id_agent,
    id_issue,
    department,
    description,
    ql_agent_complete_name,
    ql_agent_region,
    ql_agent_segment,
    ql_ocorrency_category,
    ql_occorency_type,
    ql_resolution,
    ql_ticket_from,
    responsible,
    summary,
    who_is_complaining,
    ts_created,
    ts_updated,
    year,
    month,
    day
FROM
    occurrences_last_version
WHERE
    ordered_version = 1
