WITH leads AS (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY id ORDER BY ts_updated DESC) AS rw
    FROM
        datalake_brokers_supply_processor_clean.lead_3p
)
SELECT
    id,
    id_partner,
    id_file,
    id_listing,
    uuid_lead,
    id_real_estate,
    id_by_real_estate,
    NULLIF(GET_JSON_OBJECT(brokers, '$.housePartnerId'), '') AS id_house_partner,
    GET_JSON_OBJECT(location, '$.regionId')::BIGINT AS id_region,
    lead_hash,
    NULLIF(GET_JSON_OBJECT(brokers, '$.block'), '') AS block,
    NULLIF(GET_JSON_OBJECT(brokers, '$.tower'), '') AS tower,
    NULLIF(GET_JSON_OBJECT(brokers, '$.infoKey'), '') AS info_key,
    NULLIF(GET_JSON_OBJECT(brokers, '$.condominium'), '') AS condominium,
    NULLIF(GET_JSON_OBJECT(brokers, '$.houseCategory'), '') AS house_category,
    NULLIF(GET_JSON_OBJECT(blueprint, '$.houseType'), '') AS house_type,
    NULLIF(GET_JSON_OBJECT(brokers, '$.subTypeHouse'), '') AS house_subtype,
    NULLIF(GET_JSON_OBJECT(brokers, '$.constructionYear'), '') AS construction_year,
    NULLIF(GET_JSON_OBJECT(details, '$.frontDoorType'), '') AS front_door_type,
    NULLIF(GET_JSON_OBJECT(details, '$.description'), '') AS house_description,
    NULLIF(GET_JSON_OBJECT(brokers, '$.country'), '') AS country,
    NULLIF(GET_JSON_OBJECT(location, '$.state'), '') AS state,
    NULLIF(GET_JSON_OBJECT(location, '$.city'), '') AS city,
    NULLIF(GET_JSON_OBJECT(location, '$.neighborhood'), '') AS neighborhood,
    NULLIF(GET_JSON_OBJECT(location, '$.regionSlug'), '') AS region_slug,
    NULLIF(GET_JSON_OBJECT(location, '$.zipCode'), '') AS zip_code,
    NULLIF(GET_JSON_OBJECT(location, '$.address'), '') AS address,
    NULLIF(GET_JSON_OBJECT(location, '$.number'), '') AS number,
    NULLIF(GET_JSON_OBJECT(location, '$.floor'), '') AS floor,
    NULLIF(GET_JSON_OBJECT(location, '$.complement'), '') AS complement,
    NULLIF(GET_JSON_OBJECT(location, '$.referencePoint'), '') AS reference_point,
    NULLIF(GET_JSON_OBJECT(owner, '$.email'), '') AS owner_email,
    NULLIF(GET_JSON_OBJECT(owner, '$.name'), '') AS owner_name,
    NULLIF(GET_JSON_OBJECT(owner, '$.phone'), '') AS owner_phone,
    NULLIF(GET_JSON_OBJECT(owner, '$.personType'), '') AS owner_person_type,
    NULLIF(GET_JSON_OBJECT(access, '$.accessType'), '') AS access_type,
    NULLIF(GET_JSON_OBJECT(access, '$.authorizationType'), '') AS authorization_type,
    NULLIF(GET_JSON_OBJECT(access, '$.occupantType'), '') AS occupant_type,
    NULLIF(GET_JSON_OBJECT(access, '$.additionalInfo'), '') AS additional_access_info,
    NULLIF(GET_JSON_OBJECT(access, '$.lockerAddress'), '') AS locker_address,
    NULLIF(GET_JSON_OBJECT(access, '$.password'), '') AS password,
    cnpj,
    status,
    FROM_JSON(NULLIF(GET_JSON_OBJECT(details, '$.installations'), '{{}}'), 'map<string, boolean>') AS installations,
    FROM_JSON(NULLIF(GET_JSON_OBJECT(details, '$.appliances'), '{{}}'), 'map<string, boolean>') AS house_appliances,
    FROM_JSON(NULLIF(GET_JSON_OBJECT(details, '$.accessibilityItems'), '{{}}'), 'map<string, boolean>') AS accessibility_items,
    FROM_JSON(NULLIF(enrichment_reason, '{{}}'), 'map<string, boolean>') AS enrichment_reason,
    FROM_JSON(NULLIF(discard_reason, '{{}}'), 'map<string, boolean>') AS discard_reason,
    FROM_JSON(NULLIF(eligible_reason, '{{}}'), 'map<string, boolean>') AS eligible_reason,
    FROM_JSON(
        NULLIF(GET_JSON_OBJECT(photos, '$.list'), '[]'),
        'array<struct<url: string, description: string>>'
    ) AS photos,
        FROM_JSON(
        NULLIF(GET_JSON_OBJECT(administrators, '$.list'), '[]'),
        'array<struct<name: string, email: string, phone: string, mainId: bigint>>'
    ) AS administrators,
    FROM_JSON(
        NULLIF(GET_JSON_OBJECT(pricing, '$.iptuList'), '[]'), 
        'array<struct<installmentAmount: int, installmentQuantity: int>>'
    ) AS iptu_installment_informations,
    FROM_JSON(
        NULLIF(GET_JSON_OBJECT(pricing, '$.specialConditions'), '[]'),
        'array<string>'
    ) AS special_conditions,
    GET_JSON_OBJECT(blueprint, '$.totalArea')::INT AS total_area,
    GET_JSON_OBJECT(blueprint, '$.bedrooms')::INT AS bedrooms,
    GET_JSON_OBJECT(blueprint, '$.suites')::INT AS suites,
    GET_JSON_OBJECT(blueprint, '$.bathrooms')::INT AS bathrooms,
    GET_JSON_OBJECT(blueprint, '$.garages')::INT AS garages,
    GET_JSON_OBJECT(location, '$.lat')::DECIMAL(11,8) AS latitude,
    GET_JSON_OBJECT(location, '$.lng')::DECIMAL(11,8) AS longitude,
    GET_JSON_OBJECT(pricing, '$.rent')::INT AS rent_price,
    GET_JSON_OBJECT(pricing, '$.salePrice')::INT AS sale_price,
    GET_JSON_OBJECT(pricing, '$.condoPrice')::INT AS condo_price,
    version,
    GET_JSON_OBJECT(access, '$.optedKeysWithAgent')::BOOLEAN AS has_opted_keys_with_agent,
    GET_JSON_OBJECT(access, '$.hasRestriction')::BOOLEAN AS has_access_restriction,
    GET_JSON_OBJECT(details, '$.isFurnished')::BOOLEAN AS is_furnished,
    GET_JSON_OBJECT(details, '$.isPenthouse')::BOOLEAN AS is_penthouse,
    GET_JSON_OBJECT(details, '$.isPetFriendly')::BOOLEAN AS is_pet_friendly,
    GET_JSON_OBJECT(pricing, '$.iptuNotPaid')::BOOLEAN AS is_iptu_not_paid,
    GET_JSON_OBJECT(location, '$.outOfArea')::BOOLEAN AS is_out_of_area,
    GET_JSON_OBJECT(brokers, '$.habitat')::BOOLEAN AS is_habitat,
    GET_JSON_OBJECT(brokers, '$.balcony')::BOOLEAN AS has_balcony,
    GET_JSON_OBJECT(brokers, '$.agencyKey')::BOOLEAN AS has_agency_key,
    GET_JSON_OBJECT(brokers, '$.concierge')::BOOLEAN AS has_concierge,
    is_eligible,
    is_sent_to_bob,
    is_enriched,
    is_discarded,
    GET_JSON_OBJECT(brokers, '$.createdAt')::TIMESTAMP AS ts_house_created,
    GET_JSON_OBJECT(brokers, '$.updatedAt')::TIMESTAMP AS ts_house_updated,
    ts_created,
    ts_updated
FROM
    leads
WHERE
    rw = 1