"""Migration Comparison DAG — compare Twin and EMR metrics, produce verdict.

Auto-generated by emr-migration-v2 skill.
Run ID: 3eda59b6-f7c0-480d-b2d4-b04eabef7d51
Scope: growth/dw_user_affiliate
"""

import sys
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import urlparse

from airflow import DAG, Dataset
from airflow.operators.python import PythonOperator

from bietlejuice.services.configuration_service import ConfigurationService

_PLATFORM_DIR = str(Path(__file__).resolve().parent.parent)
if _PLATFORM_DIR not in sys.path:
    sys.path.insert(0, _PLATFORM_DIR)

DAG_ID = "migration_compare_growth__dw_user_affiliate"
RUN_ID = "3eda59b6-f7c0-480d-b2d4-b04eabef7d51"
DOMAIN = "growth"
DAG_NAME = "dw_user_affiliate"
RUN_PREFIX = "emr-migration/runs/3eda59b6-f7c0-480d-b2d4-b04eabef7d51"
TWIN_DATASET = "migration:twin-growth__dw_user_affiliate-complete"
EMR_DATASET = "migration:emr-growth__dw_user_affiliate-complete"

TABLES = [
    "dim_user_affiliate",
]

_CONFIG = ConfigurationService("dw_user_affiliate")
ARTIFACTS_URI = _CONFIG.get_config("artifacts_bucket")
ARTIFACTS_BUCKET = urlparse(ARTIFACTS_URI).netloc or ARTIFACTS_URI

default_args = {
    "owner": "data-platform",
    "retries": 0,
}

with DAG(
    dag_id=DAG_ID,
    default_args=default_args,
    schedule=[Dataset(TWIN_DATASET), Dataset(EMR_DATASET)],
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["migration", "comparison", "validation"],
    dagrun_timeout=timedelta(hours=4),
) as dag:

    def _get_s3_client():
        import boto3
        from airflow.models import Variable

        role_arn = Variable.get("DATASET_EVENTS_ASSUME_ROLE_ARN", default_var=None)
        if not role_arn:
            return boto3.client("s3")
        sts = boto3.client("sts")
        creds = sts.assume_role(
            RoleArn=role_arn,
            RoleSessionName="migration-s3-compare",
            DurationSeconds=3600,
        )["Credentials"]
        return boto3.Session(
            aws_access_key_id=creds["AccessKeyId"],
            aws_secret_access_key=creds["SecretAccessKey"],
            aws_session_token=creds["SessionToken"],
        ).client("s3")

    def run_comparison(**context):
        """Read metrics from S3, compare, write verdict."""
        from migration_assets.comparison import (
            compare_table,
            list_s3_jsons,
            read_s3_json,
            write_s3_json,
        )

        s3 = _get_s3_client()
        bucket = ARTIFACTS_BUCKET

        twin_prefix = f"{RUN_PREFIX}/twin/{DOMAIN}/{DAG_NAME}/"
        emr_prefix = f"{RUN_PREFIX}/emr/{DOMAIN}/{DAG_NAME}/"
        verdict_prefix = f"{RUN_PREFIX}/verdicts/{DOMAIN}/{DAG_NAME}/"

        twin_keys = list_s3_jsons(bucket, twin_prefix, s3_client=s3)
        emr_keys = list_s3_jsons(bucket, emr_prefix, s3_client=s3)

        twin_by_table = {}
        for key in twin_keys:
            metric = read_s3_json(f"{ARTIFACTS_URI}/{key}", s3_client=s3)
            table_name = metric.get(
                "table_name", key.split("/")[-1].replace(".json", "")
            )
            twin_by_table[table_name] = metric

        emr_by_table = {}
        for key in emr_keys:
            metric = read_s3_json(f"{ARTIFACTS_URI}/{key}", s3_client=s3)
            table_name = metric.get(
                "table_name", key.split("/")[-1].replace(".json", "")
            )
            emr_by_table[table_name] = metric

        all_tables = (
            TABLES
            if TABLES
            else sorted(set(twin_by_table.keys()) | set(emr_by_table.keys()))
        )
        if not all_tables:
            raise RuntimeError("No metric files found for either runtime")

        summary_uri = f"{ARTIFACTS_URI}/{verdict_prefix}summary.json"
        write_s3_json(
            summary_uri,
            {"version": 1, "run_id": RUN_ID, "status": "in_progress"},
            s3_client=s3,
        )

        verdicts = {}
        passed = warned = failed = 0

        for table_name in all_tables:
            twin_m = twin_by_table.get(
                table_name,
                {
                    "table_name": table_name,
                    "error": "Missing twin metric",
                    "run_id": RUN_ID,
                },
            )
            emr_m = emr_by_table.get(
                table_name,
                {
                    "table_name": table_name,
                    "error": "Missing EMR metric",
                    "run_id": RUN_ID,
                },
            )

            for label, metric in [("twin", twin_m), ("emr", emr_m)]:
                metric_run_id = metric.get("run_id", "")
                if metric_run_id and metric_run_id != RUN_ID:
                    metric["error"] = (
                        f"run_id mismatch: expected {RUN_ID}, got {metric_run_id} ({label})"
                    )
            verdict = compare_table(twin_m, emr_m)
            verdict_uri = f"{ARTIFACTS_URI}/{verdict_prefix}{table_name}.json"
            write_s3_json(verdict_uri, verdict, s3_client=s3)

            v = verdict["verdict"]
            verdicts[table_name] = v
            if v == "PASS":
                passed += 1
            elif v == "WARN":
                warned += 1
            else:
                failed += 1

        summary = {
            "version": 1,
            "run_id": RUN_ID,
            "scope_id": f"{DOMAIN}__{DAG_NAME}",
            "total_tables": len(all_tables),
            "passed": passed,
            "warned": warned,
            "failed": failed,
            "tables": verdicts,
            "overall_verdict": "FAIL" if failed else ("WARN" if warned else "PASS"),
            "pr_gate_eligible": failed == 0,
        }
        summary_uri = f"{ARTIFACTS_URI}/{verdict_prefix}summary.json"
        write_s3_json(summary_uri, summary, s3_client=s3)

        context["ti"].xcom_push(key="overall_verdict", value=summary["overall_verdict"])
        context["ti"].xcom_push(
            key="pr_gate_eligible", value=summary["pr_gate_eligible"]
        )

    compare_all = PythonOperator(
        task_id="compare_all",
        python_callable=run_comparison,
    )
