--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.31.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 02/02/2017 21:52:11
-- Server version: 5.6.19-log
-- Client version: 4.1
-- Please backup your database before running this script
--
DROP PROCEDURE IF EXISTS list_property_scheduling;

SET NAMES 'utf8';

USE ebdb;


DELIMITER $$

--
-- Create procedure "list_property_schedule"
--
CREATE DEFINER = 'QuintoAndarMain'@'%'
PROCEDURE list_property_scheduling()
BEGIN

select
  i.id as id_imovel,  
  a.id as id_scheduling,  
  prop.id as id_owner,
  daf.usuario_id as id_user_affiliate,
  dau.id as id_user_agent,
  v.visitante_id as id_user_visitor,
  dav.id as id_user_visit_agent, 
  v.id as id_visit, 
  vo_cr.isApp as visit_created_from_app,
  vo_cr.nome as visit_created_type,
  coalesce(vo_up.isApp, FALSE) as visit_last_updated_from_app,
  coalesce(vo_up.nome, FALSE) as visit_last_updated_type,
  fl.id as id_rental_flow,
  n.id as id_negotiation,
  n.criadoEm as dt_negotiation,
  pp.id as id_pre_proposal,
  coalesce(p.id, p_n.id) as id_proposal,
  c.id as id_contract,
  c.dataRescisao as dt_contract_anullment
  -- count(1)
  -- *
  
from 
  Imovel i

left join
  Usuario prop
  on prop.id = i.usuario_id

-- DADOS AFILIADO
left join 
  DadosAfiliado daf
  on daf.id = i.dadosAfiliado_id

-- AGENDAMENTO
left join
  Agendamento a
  on a.imovel_id = i.id
  and a.tipo = 'Visita'

left join
  Usuario dau
  on dau.dadosAgente_id = a.agente_id

-- VISITA
left join
  Visita v
  on v.id = a.visita_id
left join
  VisitaOrigem vo_cr
  on vo_cr.id = v.origemCriacao_id
left join
  VisitaOrigem vo_up
  on vo_up.id = v.origemUltimaAtualizacao_id
left join
  Usuario dav
  on dav.dadosAgente_id = v.agente_id

-- FLUXOLOCACAO
left join  
  FluxoLocacao fl
  on a.fluxoLocacao_id = fl.id

left join 
  Negociacao n
  on n.imovel_id = fl.imovel_id
  and n.proponente_id = fl.cliente_id

-- PRE-PROPOSTA
left join 
  PreProposta pp
  on pp.imovel_id = i.id
  and pp.usuario_id = fl.cliente_id

-- PROPOSTA
left join 
  Proposta p
  on p.preProposta_id = pp.id
  
left join
  Proposta p_n
  on p_n.negociacao_id = n.id

-- CONTRATO
left join 
  Contrato c
  on c.proposta_id = p.id  
  -- and c.status != 'Cancelado'
;

END
$$

DELIMITER ;