SELECT 
    id,
    logradouro_id AS id_address,
    imobiliaria_id AS id_real_estate_agency, 
    condominio_id AS id_condo, 
    bairro_id AS id_neighborhood,
    tipo_id AS id_type, 
    finalidade AS goal,
    codigo AS code,
    logradouro_original AS address, 
    cep AS zip_code,
    CAST(latitude AS FLOAT) AS lat, 
    CAST(longitude AS FLOAT) as lng, 
    ordem AS house_order,
    CAST(area AS FLOAT) AS total_area,
    CAST(banheiros AS SMALLINT) AS bathrooms, 
    CAST(quartos AS SMALLINT) AS bedrooms,
    CAST(salas AS SMALLINT) AS living_rooms,
    CAST(suites AS SMALLINT) AS suites,
    CAST(vagas AS SMALLINT) AS parking_slots, 
    CAST(valor_condominio AS FLOAT) AS condo_price,
    CAST(valor_iptu AS FLOAT) AS iptu_price, 
    CAST(preco AS FLOAT) AS price, 
    CAST(liquidez AS FLOAT) AS liquidity,
    CAST(duplicado AS BOOLEAN) AS is_duplicated,
    CAST(construido_em AS TIMESTAMP) AS ts_built,
    CAST(criado_em AS TIMESTAMP) AS ts_created,
    CAST(desativado_em AS TIMESTAMP) AS ts_disabled
FROM 
    datalake_casa_mineira_portal_raw.imovel 