SELECT
    id,
    cidade_id AS id_city,
    nome AS real_estate_agency_name,
    nome_completo AS real_estate_agency_full_name,
    slug_completo AS real_estate_agency_full_slug_name,
    uf,
    cidade AS city,
    bairro AS neighborhood,
    logradouro AS address,
    cep AS zip_code,
    CAST(latitude AS FLOAT) AS lat,
    CAST(longitude AS FLOAT) AS lng,
    tipo_pessoa AS person_type,
    website,
    exibir_endereco AS address_shown,
    url_integracao AS integration_url,
    url_integracao_hash AS integration_url_hash,
    formato_integracao AS integration_format,
    tipo_notificacao AS notification_type,
    url_notificacao AS notification_url,
    token_notificacao AS notification_token,
    token,
    CAST(total_imoveis AS INT) AS total_houses,
    CAST(total_imoveis_ativos AS INT) AS total_active_houses,
    CAST(total_imoveis_contratados AS INT) AS total_hired_houses,
    CAST(lance AS BIGINT) AS bid,
    CAST(criado_em AS TIMESTAMP) AS ts_created,
    CAST(desativado_em AS TIMESTAMP) AS ts_disabled
FROM
    datalake_casa_mineira_portal_raw.imobiliaria