SELECT
    CAST(NULLIF(imovel_id, '') AS bigint) AS sk_house,
    CAST(NULLIF(contrato_id, '') AS bigint) AS sk_contract,
    CAST(NULLIF(id_proposta_base, '') AS bigint) AS sk_base_proposal,
    CAST(NULLIF(id_parcela, '') AS bigint) AS sk_installment,
    CAST(NULLIF(produto_id, '') AS bigint) AS sk_product,
    NULLIF(Nome, '') AS owner_full_name,
    NULLIF(cpf_cnpj, '') AS owner_cpf_cnpj,
    NULLIF(cnpj_investidor, '') AS investor_cnpj,
    CAST(NULLIF(numero_parcela, '') AS bigint) AS installment_number,
    NULLIF(status, '') AS installment_status,
    NULLIF(Numero_CCB, '') AS ccb_number,
    NULLIF(Numero_CCCB, '') AS cccb_number,
    NULLIF(status_solicitacao, '') AS request_status,
    CAST(NULLIF(Qtde_Parcelas, '') AS bigint) AS installment_total_count,
    CAST(NULLIF(REPLACE(REPLACE(Soma_Parcelas, '.', ''), ',', '.'), '') AS double) AS installment_total_sum,
    CAST(NULLIF(REPLACE(REPLACE(juros_parcela_contrato, '.', ''), ',', '.'), '') AS double) AS contract_installment_interest,
    CAST(NULLIF(REPLACE(REPLACE(juros_remuneratorios, '.', ''), ',', '.'), '') AS double) AS compensatory_interest,
    CAST(NULLIF(REPLACE(REPLACE(juros_mora, '.', ''), ',', '.'), '') AS double) AS delay_interest,
    CAST(NULLIF(REPLACE(REPLACE(Taxa_Juros, '.', ''), ',', '.'), '') AS double) AS interest_rate,
    CAST(NULLIF(REPLACE(REPLACE(multa, '.', ''), ',', '.'), '') AS double) AS fine_value,
    CAST(NULLIF(REPLACE(REPLACE(principal_parcela_contrato, '.', ''), ',', '.'), '') AS double) AS contract_main_installment_value,
    CAST(NULLIF(REPLACE(REPLACE(Valor_Principal, '.', ''), ',', '.'), '') AS double) AS main_value,
    CAST(NULLIF(REPLACE(REPLACE(Valor_Juros, '.', ''), ',', '.'), '') AS double) AS interest_value,
    CAST(NULLIF(REPLACE(REPLACE(valor_parcela, '.', ''), ',', '.'), '') AS double) AS installment_value,
    CAST(NULLIF(REPLACE(REPLACE(valor_pago, '.', ''), ',', '.'), '') AS double) AS paid_value,
    TO_DATE(NULLIF(data_contrato_gerado, ''), 'd/M/y') AS dt_generated_contract,
    TO_DATE(NULLIF(data_contrato_assinado, ''), 'd/M/y') AS dt_signed_contract,
    TO_DATE(NULLIF(data_vencimento, ''), 'd/M/y') AS dt_expiration,
    TO_DATE(NULLIF(data_pagamento, ''), 'd/M/y') AS dt_payment,
    TO_DATE(NULLIF(Data_Liquidacao, ''), 'd/M/y') AS dt_settle,
    TO_DATE(NULLIF(created_at, ''), 'd/M/y') AS dt_created_at
FROM
    datalake_gsheets_raw.mova_lra_owners;
