SELECT
    id_colaborador AS employee_id,
    matricula AS registration_id,
    id_gestor AS manager_id,
    numero_centro_de_custo AS cost_center_id,
    nome AS name,
    email,
    status,
    banda AS band,
    gestor AS manager_name,
    cargo AS role,
    classe_cargo AS role_class,
    departamento AS department,
    centro_de_custo AS cost_center,
    sub_diretoria AS sub_board,
    diretoria AS board,
    vertical AS line,
    area,
    owner,
    head,
    c_level,
    vice_presidencia AS vice_presidency,
    status_gestor AS manager_status,
    diretos AS direct_employees,
    indiretos AS indirect_employees,
    layer,
    fl_lider AS fl_leader,
    lideranca AS leadership,
    l0,
    l1,
    l2,
    l3,
    l4,
    l5,
    l6,
    l7,
    CAST(ts_load AS DATE) AS dt_last_update
FROM
    datalake_gsheets_raw.base_hierarquia