SELECT
  id,
  external_id AS id_external,
  original_invoice_external_id AS id_original_invoice_external,
  account_id AS id_account,
  contract_id AS id_contract,
  checkout_order_id AS id_checkout_order,
  checkout_charge_id AS id_checkout_charge,
  idempotency_id AS id_idempotency,
  external_negotiation_id AS id_external_negotiation,
  payment_unique_payment_identifier,
  status,
  sub_status AS substatus,
  payment_status,
  CAST(NULL AS STRING) AS negotiation_status,
  paid_via,
  purpose,
  closing_mode,
  reason,
  due_amount,
  paid_amount,
  payment_paid_interest_amount,
  payment_paid_fine_amount,
  accrual_year_month,
  should_request_boleto,
  sispag_file,
  payment_company_use_number,
  payment_bank_code,
  write_off AS is_write_off,
  write_off_at AS ts_write_off,
  TIMESTAMP(paid_date) AS ts_paid,
  TIMESTAMP(payment_confirmation_at) AS ts_payment_confirmation,
  TIMESTAMP(payment_event_at) AS ts_payment_event,
  TIMESTAMP(payment_divergent_fixed_at) AS ts_payment_divergent_fixed,
  TIMESTAMP(payment_processing_at) AS ts_payment_processing,
  TIMESTAMP(payment_credit_date) AS ts_payment_credit,
  TIMESTAMP(payment_chargeback_at) AS ts_payment_chargeback,
  TIMESTAMP(payment_refunded_at) AS ts_payment_refunded,
  TIMESTAMP(canceled_at) AS ts_canceled,
  TIMESTAMP(sent_at) AS ts_sent,
  TIMESTAMP(due_date) AS ts_due,
  TIMESTAMP(created_at) AS ts_created,
  TIMESTAMP(synced_at) AS ts_synced,
  TIMESTAMP(nf_requested_at) AS ts_nf_requested,
  TIMESTAMP(retsuko_created_at) AS ts_retsuko_created,
  TIMESTAMP(retsuko_updated_at) AS ts_retsuko_updated,
  year,
  month,
  day
FROM datalake_retsuko_raw.invoice
