SELECT
    id AS id_assessment,
    inspection_id AS id_inspection,
    previous_assessment_id AS id_previous_assessment,
    key_location,
    key_location_details,
    GET_JSON_OBJECT(key_information, '$.locationChange.locationChangeReason') AS location_change_reason,
    GET_JSON_OBJECT(key_information, '$.locationChange.locationChangeReasonDetails') AS location_change_reason_details,
    source,
    house_supplies,
    scheduling_key_recovery,
    ai_processing_failure_reason,
    repair_request_ai_flow,
    ai_repair_analysis_control_group,
    ai_repair_analysis_wave_name,
    owner_limit_revision_date AS dt_owner_limit_revision,
    tenant_limit_revision_date AS dt_tenant_limit_revision,
    created_at AS ts_created,
    finished_at AS ts_finished,
    started_at AS ts_started,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_inspection_services_raw.assessment
