CREATE TABLE zendesk.ticket_metrics (
	id varchar(30) NOT NULL,
	ticket_id varchar(30) NOT NULL,
	url varchar(100) NULL,
	group_stations int4 NULL,
	assignee_stations int4 NULL,
	reopens int4 NULL,
	replies int4 NULL,
	assignee_updated_at timestamp NULL,
	requester_updated_at timestamp NULL,
	status_updated_at timestamp NULL,
	initially_assigned_at timestamp NULL,
	assigned_at timestamp NULL,
	solved_at timestamp NULL,
	latest_comment_added_at timestamp NULL,
	first_resolution_time_in_minutes_calendar int4 NULL,
	first_resolution_time_in_minutes_business int4 NULL,
	reply_time_in_minutes_calendar int4 NULL,
	reply_time_in_minutes_business int4 NULL,
	full_resolution_time_in_minutes_calendar int4 NULL,
	full_resolution_time_in_minutes_business int4 NULL,
	agent_wait_time_in_minutes_calendar int4 NULL,
	agent_wait_time_in_minutes_business int4 NULL,
	requester_wait_time_in_minutes_calendar int4 NULL,
	requester_wait_time_in_minutes_business int4 NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	on_hold_time_in_minutes_calendar int4 NULL,
	on_hold_time_in_minutes_business int4 NULL,
	CONSTRAINT ticket_metrics_pkey PRIMARY KEY (id)
);
