CREATE TABLE zendesk.ticket (
	id varchar(30) NOT NULL,
	url varchar NULL,
	external_id varchar(30) NULL,
	"type" varchar(30) NULL,
	subject varchar NULL,
	raw_subject varchar NULL,
	description varchar NULL,
	priority varchar(30) NULL,
	status varchar(30) NULL,
	recipient varchar(50) NULL,
	requester_id varchar(30) NULL,
	submitter_id varchar(30) NULL,
	assignee_id varchar(30) NULL,
	organization_id varchar(30) NULL,
	group_id varchar(30) NULL,
	forum_topic_id varchar(30) NULL,
	problem_id varchar(30) NULL,
	has_incidents bool NULL,
	due_at timestamp NULL,
	via_id int4 NULL,
	satisfaction_rating_score varchar(10) NULL,
	satisfaction_rating_comment varchar NULL,
	followup_ids int4[] NULL,
	sharing_agreement_ids int4[] NULL,
	ticket_form_id varchar(30) NULL,
	brand_id varchar(30) NULL,
	allow_channelback bool NULL,
	is_public bool NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	is_whatsapp bool NULL,
	closed_by_merge bool NULL,
	is_automatic bool NULL,
	missed_chat bool NULL,
	offline_msg bool NULL,
	CONSTRAINT ticket_pkey PRIMARY KEY (id)
);