CREATE TABLE zendesk."user" (
	id varchar NOT NULL,
	email varchar NULL,
	"name" varchar NULL,
	active bool NULL,
	alias varchar NULL,
	chat_only bool NULL,
	created_at timestamp NULL,
	custom_role_id int4 NULL,
	details varchar NULL,
	external_id int4 NULL,
	last_login_at timestamp NULL,
	locale varchar NULL,
	locale_id int4 NULL,
	moderator bool NULL,
	notes varchar NULL,
	only_private_comments bool NULL,
	organization_id varchar NULL,
	default_group_id varchar NULL,
	phone varchar NULL,
	photo_id int4 NULL,
	restricted_agent bool NULL,
	"role" varchar NULL,
	shared bool NULL,
	shared_agent bool NULL,
	signature varchar NULL,
	suspended bool NULL,
	ticket_restriction varchar NULL,
	time_zone varchar NULL,
	two_factor_auth_enabled bool NULL,
	updated_at timestamp NULL,
	url varchar NULL,
	verified bool NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id)
);