SELECT
    id,
    third_party_bills_uuid AS uuid_third_party_bills,
    contract_id AS id_contract,
    payment_request_uuid AS uuid_payment_request,
    bar_code,
    beneficiary_name,
    beneficiary_doc,
    beneficiary_doc_type,
    landlord_name,
    landlord_doc,
    landlord_doc_type,
    type,
    status,
    cancellation_reason,
    digitable_line,
    version,
    updated_amount,
    original_amount,
    fine,
    interest,
    discount,
    payment_request_status,
    payment_flow,
    payout_idempotency_key,
    currency,
    due_date AS dt_due,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_rental_management_raw.third_party_bills
