SELECT
    Id AS id,
    Empresa_portal__c AS id_company_portal,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    Oportunidad__c AS id_opportunity,
    Id_pedido_portal__c AS id_order_portal,
    Id_pedido_SAP__c AS id_order_sap,
    Organizacion_de_venta__c AS id_organization_sales,
    OwnerId AS id_owner,
    Propietario_de_empresa_portal__c AS id_owner_company_portal,
    Producto__c AS id_product,
    Solicitante__c AS id_requester,
    Responsable_pago__c AS id_responsible_payment,
    CEBE__c AS cebe,
    Via_de_pago__c AS channel_payment,
    Clase_de_documento__c AS class_document,
    Tipificacion__c AS classification,
    CurrencyIsoCode AS currency_iso_code,
    Divisa_OV__c AS currency_sales_org,
    Documento_Posicion__c AS document_position,
    Frecuencia_de_Facturacion__c AS frequency_billing,
    Linea_de_producto__c AS line_product,
    Name AS name,
    Motivo__c AS reason,
    Referencia__c AS reference,
    Tipo__c AS type_name,
    Monto_en_Divisa_OV__c AS amount_currency_sales_org,
    Monto_en_Divisa_Transaccion__c AS amount_currency_transaction,
    Monto_mensualizado_moneda_OV__c AS amount_monthly_sales_org_currency,
    Monto_en_USD__c AS amount_usd,
    Duracion_en_meses__c AS duration_months,
    Creada_por_ecommerce__c AS is_created_ecommerce,
    IsDeleted AS is_deleted,
    Fecha_documento__c AS dt_document,
    Fecha_de_fin_de_vigencia__c AS dt_end_validity,
    LastActivityDate AS dt_last_activity,
    Fecha_de_inicio_de_vigencia__c AS dt_start_validity,
    CreatedDate AS ts_created,
    LastModifiedDate AS ts_last_modified,
    LastReferencedDate AS ts_last_referenced,
    LastViewedDate AS ts_last_viewed,
    SystemModstamp AS ts_system_mod,
    CAST(LastModifiedDate AS DATE) AS dt_updated,
    YEAR(LastModifiedDate) AS year,
    MONTH(LastModifiedDate) AS month,
    DAY(LastModifiedDate) AS day
FROM
    datalake_salesforce_classifieds_raw.facturacion__c
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
