SELECT
    Id AS id,
    Empresa_portal__c AS id_company_portal,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    Oportunidad__c AS id_opportunity,
    Id_pedido_posicion_SAP__c AS id_order_position_sap,
    Id_pedido_SAP__c AS id_order_sap,
    Organizacion_de_venta__c AS id_organization_sales,
    OwnerId AS id_owner,
    Producto__c AS id_product,
    Solicitante__c AS id_requester,
    Responsable_pago__c AS id_responsible_payment,
    Via_de_pago__c AS channel_payment,
    CurrencyIsoCode AS currency_iso_code,
    Name AS name,
    Numero_de_oportunidad__c AS number_opportunity,
    Numero_de_pedido_portal__c AS number_order_portal,
    Status_factura__c AS status_invoice,
    Monto__c AS amount,
    Bloqueo_posicion__c AS is_block_position,
    Creada_por_ecommerce__c AS is_created_ecommerce,
    IsDeleted AS is_deleted,
    Reasigna_propietario__c AS is_reassigns_owner,
    Fecha_de_cancelacion__c AS dt_cancellation,
    Fecha_fin_liquidacion__c AS dt_end_settlement,
    Fecha_factura__c AS dt_invoice,
    LastActivityDate AS dt_last_activity,
    Fecha_inicio_liquidacion__c AS dt_start_settlement,
    CreatedDate AS ts_created,
    LastModifiedDate AS ts_last_modified,
    LastReferencedDate AS ts_last_referenced,
    LastViewedDate AS ts_last_viewed,
    SystemModstamp AS ts_system_mod,
    CAST(LastModifiedDate AS DATE) AS dt_updated,
    YEAR(LastModifiedDate) AS year,
    MONTH(LastModifiedDate) AS month,
    DAY(LastModifiedDate) AS day
FROM
    datalake_salesforce_classifieds_raw.plan_de_facturacion__c
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
