SELECT
    Id AS id,
    BusinessHoursId AS id_business_hours,
    ChannelDefinitionId AS id_channel_definition,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    RoutingConfigurationId AS id_routing_configuration,
    TargetQueueId AS id_target_queue,
    ChannelAddressIdentifier AS channel_address_identifier,
    ConsentType AS consent_type,
    ConversationEndResponse AS conversation_end_response,
    Description AS description,
    DeveloperName AS developer_name,
    DoubleOptInPrompt AS double_opt_prompt,
    EngagedResponse AS engaged_response,
    InitialResponse AS initial_response,
    IsoCountryCode AS iso_country_code,
    Language AS language_name,
    MasterLabel AS master_label,
    MessageType AS message_type,
    MessagingPlatformKey AS messaging_platform_key,
    OfflineAgentsResponse AS offline_agents_response,
    OptInPrompt AS opt_prompt,
    OutsideBusinessHoursResponse AS outside_business_hours_response,
    PlatformType AS platform_type,
    RoutingType AS routing_type,
    IsActive AS is_active,
    IsDeleted AS is_deleted,
    IsRequireDoubleOptIn AS is_require_double_opt,
    IsRestrictedToBusinessHours AS is_restricted_business_hours,
    CreatedDate AS ts_created,
    LastModifiedDate AS ts_last_modified,
    SystemModstamp AS ts_system_mod,
    CAST(LastModifiedDate AS DATE) AS dt_updated,
    YEAR(LastModifiedDate) AS year,
    MONTH(LastModifiedDate) AS month,
    DAY(LastModifiedDate) AS day
FROM
    datalake_salesforce_classifieds_raw.messagingchannel
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
