SELECT
    Id AS id,
    CaseId AS id_case,
    CreatedById AS id_created_by,
    EndUserAccountId AS id_end_user_account,
    EndUserContactId AS id_end_user_contact,
    LastModifiedById AS id_last_modified_by,
    LeadId AS id_lead,
    MessagingChannelId AS id_messaging_channel,
    MessagingEndUserId AS id_messaging_end_user,
    OpportunityId AS id_opportunity,
    OwnerId AS id_owner,
    TargetUserId AS id_target_user,
    AgentType AS agent_type,
    ChannelEndUserFormula AS channel_end_user_formula,
    ChannelGroup AS channel_group,
    ChannelIntent AS channel_intent,
    ChannelKey AS channel_key,
    ChannelLocale AS channel_locale,
    ChannelName AS channel_name,
    ChannelType AS channel_type,
    CurrencyIsoCode AS currency_iso_code,
    Name AS name,
    Origin AS origin_channel_name,
    PreviewDetails AS preview_details,
    SessionKey AS session_key,
    Status AS status_name,
    AgentMessageCount AS agent_message_count,
    EndUserMessageCount AS end_user_message_count,
    IsDeleted AS is_deleted,
    AcceptTime AS ts_accepted,
    CreatedDate AS ts_created,
    EndTime AS ts_end,
    LastModifiedDate AS ts_last_modified,
    LastReferencedDate AS ts_last_referenced,
    LastViewedDate AS ts_last_viewed,
    StartTime AS ts_start,
    SystemModstamp AS ts_system_mod,
    CAST(LastModifiedDate AS DATE) AS dt_updated,
    YEAR(LastModifiedDate) AS year,
    MONTH(LastModifiedDate) AS month,
    DAY(LastModifiedDate) AS day
FROM
    datalake_salesforce_classifieds_raw.messagingsession
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
