SELECT
    Id AS id,
    Pais_de_activacion__c AS id_country_activation,
    CreatedById AS id_created_by,
    Id_externo__c AS id_external,
    Id_externo_temporal__c AS id_external_temporary,
    Facturar_a__c AS id_invoice,
    LastModifiedById AS id_last_modified_by,
    Nombre_de_presupuesto__c AS id_name_quote,
    Orden_de_servicio__c AS id_order_service,
    Producto__c AS id_product,
    Branch_ID__c AS branch_id,
    Codigo_de_producto__c AS code_product,
    CurrencyIsoCode AS currency_iso_code,
    Descripcion_de_partida__c AS description_line_item,
    Frecuencia_de_Facturacion__c AS frequency_billing,
    Frecuencia_de_facturacion2__c AS billing_frequency_2,
    Name AS name,
    Estado_de_vigencia__c AS status_validity,
    facturacion__c AS billing,
    diferencia_meses__c AS difference_months,
    Descuento__c AS discount,
    Descuento_original__c AS discount_original,
    Duracion__c AS duration,
    Precio_anual__c AS price_annual,
    Precio_de_lista__c AS price_list,
    Precio_mensual2__c AS price_monthly_2,
    Precio_mensual__c AS price_monthly,
    Precio_de_venta__c AS price_sales,
    Precio_de_venta_original__c AS price_sales_original,
    Precio_total2__c AS price_total2,
    Precio_total_original2__c AS price_total_original2,
    Cantidad__c AS quantity,
    Cantidad_original__c AS quantity_original,
    Vigente__c AS is_current,
    IsDeleted AS is_deleted,
    Renovable__c AS is_renewable,
    Fecha_de_fin_de_vigencia__c AS dt_end_validity,
    LastActivityDate AS dt_last_activity,
    Fecha_de_inicio_de_vigencia__c AS dt_start_validity,
    CreatedDate AS ts_created,
    LastModifiedDate AS ts_last_modified,
    LastReferencedDate AS ts_last_referenced,
    LastViewedDate AS ts_last_viewed,
    SystemModstamp AS ts_system_mod,
    CAST(LastModifiedDate AS DATE) AS dt_updated,
    YEAR(LastModifiedDate) AS year,
    MONTH(LastModifiedDate) AS month,
    DAY(LastModifiedDate) AS day
FROM
    datalake_salesforce_classifieds_raw.producto_de_orden_de_servicio__c
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
