SELECT
    Id AS id,
    AccountId AS id_account,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    Organizacion_de_venta__c AS id_organization_sales,
    OwnerId AS id_owner,
    RecurrenceActivityId AS id_recurrence_activity,
    WhatId AS id_what,
    WhoId AS id_who,
    Call_Ani__c AS call_ani,
    CallDisposition AS call_disposition,
    CallObject AS call_object,
    CallType AS call_type,
    Called_Number__c AS called_number,
    Conversation_Id__c AS conversation_id,
    CurrencyIsoCode AS currency_iso_code,
    Description AS description,
    Interaction_Url__c AS interaction_url,
    Gestion_Cross_selling__c AS management_cross_selling,
    Priority AS priority_name,
    Queue_Name__c AS queue_name,
    RecurrenceInstance AS recurrence_instance,
    RecurrenceMonthOfYear AS recurrence_month_year,
    RecurrenceRegeneratedType AS recurrence_regenerated_type,
    RecurrenceTimeZoneSidKey AS recurrence_time_zone_sid_key,
    RecurrenceType AS recurrence_type,
    Resultado_Lead__c AS result_lead,
    Status_Lead__c AS status_lead,
    Status AS status_name,
    Subject AS subject,
    TaskSubtype AS task_subtype,
    Type AS type_name,
    whatslly__Whatslly_Number__c AS whatslly_number,
    CallDurationInSeconds AS call_duration_seconds,
    RecurrenceDayOfMonth AS recurrence_day_month,
    RecurrenceDayOfWeekMask AS recurrence_day_week_mask,
    RecurrenceInterval AS recurrence_interval,
    Total_Acd_Time__c AS total_acd_time,
    Total_Ivr_Time__c AS total_ivr_time,
    WhatCount AS what_count,
    WhoCount AS who_count,
    IsArchived AS is_archived,
    IsClosed AS is_closed,
    whatslly__Created_by_Whatslly__c AS is_created_whatslly,
    IsDeleted AS is_deleted,
    IsHighPriority AS is_high_priority,
    IsRecurrence AS is_recurrence,
    IsReminderSet AS is_reminder_set,
    whatslly__Is_WhatsApp_Task__c AS is_whats_app_task,
    ActivityDate AS dt_activity,
    Fecha_de_finalizacion__c AS dt_completion,
    RecurrenceEndDateOnly AS dt_recurrence_end_date_only,
    RecurrenceStartDateOnly AS dt_recurrence_start_date_only,
    CompletedDateTime AS ts_completed,
    CreatedDate AS ts_created,
    LastModifiedDate AS ts_last_modified,
    ReminderDateTime AS ts_reminder,
    SystemModstamp AS ts_system_mod,
    CAST(LastModifiedDate AS DATE) AS dt_updated,
    YEAR(LastModifiedDate) AS year,
    MONTH(LastModifiedDate) AS month,
    DAY(LastModifiedDate) AS day
FROM
    datalake_salesforce_classifieds_raw.task
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
