"""Migration EMR DAG — run transpiled queries on EMR, capture metrics to S3.

Auto-generated by emr-migration-v2 skill.
Run ID: 03c62042-3e72-4dee-a98b-735452df845f
Scope: planning_and_performance/dw_bpo_performance
"""

import os
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import urlparse

import yaml
from airflow import DAG, Dataset
from airflow.operators.python import PythonOperator

from bietlejuice.base.airflow.job_cluster_engine import (
    attach_emr_job_cluster_finished_work_prerequisites,
    attach_emr_terminate_cluster_work_prerequisites,
    attach_job_cluster_engine_to_context,
    get_job_cluster_completion_sink,
)
from bietlejuice.base.airflow.task_creators.dag_execution_context import (
    DagExecutionContext,
)
from bietlejuice.services.configuration_service import ConfigurationService

DAG_ID = "migration_emr_planning_and_performance__dw_bpo_performance"
RUN_ID = "03c62042-3e72-4dee-a98b-735452df845f"
DOMAIN = "planning_and_performance"
SOURCE_DAG_NAME = "dw_bpo_performance"
DATASET_URI = "migration:emr-planning_and_performance__dw_bpo_performance-complete"
RUN_PREFIX = "emr-migration/runs/03c62042-3e72-4dee-a98b-735452df845f"
RUNTIME = "emr"
SQL_DIR_NAME = "migration"

TABLES = [
    "backlog_metric",
    "backlog_metrics_salesforce",
    "cases_perspective",
    "csat_front",
    "customer_contacts_session",
    "demand_metric",
    "email",
    "fcr_metric",
    "general_metric",
    "listing_quality_sla",
    "listing_quality_tasks",
    "nps_offboarding",
    "recontact",
    "repair_tickets",
    "satisfaction_salesforce",
    "segments_perspective",
    "speech_call",
    "speech_chat",
    "tarefas_salesforce",
    "taxonomy",
    "tickets_contract",
    "tickets_perspective",
    "tickets_transferred",
    "tmr",
    "twilio_chat_aht",
    "twilio_spoc",
]

DAG_DIR = Path(__file__).resolve().parent
ENV = os.environ.get("ENVIRONMENT")
CONFIG_SERVICE = ConfigurationService(SOURCE_DAG_NAME)
BUCKET = CONFIG_SERVICE.get_config("datalake_bucket")
BIETLEJUICE_REPO_PATH = CONFIG_SERVICE.get_config("databricks_bietlejuice_repo_path")
METRIC_CAPTURE_JOB = (
    f"{BIETLEJUICE_REPO_PATH}/spark_jobs/migration_assets/metric_capture_job.py"
)
ARTIFACTS_URI = CONFIG_SERVICE.get_config("artifacts_bucket")
ARTIFACTS_BUCKET = urlparse(ARTIFACTS_URI).netloc or ARTIFACTS_URI

with open(DAG_DIR / f"{DAG_ID}_cluster.yml") as _f:
    CLUSTER_ARGS = yaml.safe_load(_f).get("cluster", {})


def _build_context(dag):
    ctx = DagExecutionContext(
        dag=dag,
        environment=ENV,
        bucket=BUCKET,
        base_spark_jobs_path=f"{BIETLEJUICE_REPO_PATH}/spark_jobs/base/",
        dag_args={},
        workflow_args={},
        cluster_args=CLUSTER_ARGS,
        databricks_conn_id=CLUSTER_ARGS.get("databricks_conn_id", "databricks_new_env"),
    )
    attach_job_cluster_engine_to_context(ctx, CONFIG_SERVICE)
    return ctx


def _get_s3_client():
    import boto3
    from airflow.models import Variable

    role_arn = Variable.get("DATASET_EVENTS_ASSUME_ROLE_ARN", default_var=None)
    if not role_arn:
        return boto3.client("s3")
    sts = boto3.client("sts")
    creds = sts.assume_role(
        RoleArn=role_arn,
        RoleSessionName="migration-s3-upload",
        DurationSeconds=3600,
    )["Credentials"]
    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
    ).client("s3")


def _upload_sql(**context):
    sql_dir = DAG_DIR / "queries" / SQL_DIR_NAME
    s3 = _get_s3_client()
    for table in TABLES:
        local_path = str(sql_dir / f"{table}.sql")
        s3_key = f"{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}.sql"
        s3.upload_file(local_path, ARTIFACTS_BUCKET, s3_key)


with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["migration", "emr", "validation"],
    default_args={"owner": "data-platform", "retries": 0},
    dagrun_timeout=timedelta(hours=4),
) as dag:
    ctx = _build_context(dag)

    upload_sql = PythonOperator(
        task_id="upload_sql",
        python_callable=_upload_sql,
    )

    execute_cluster = ctx.job_cluster_engine.create_execute_cluster_task(
        config_service=CONFIG_SERVICE,
        minimum_cluster_runtime_version=None,
        execute_job_cluster_local_id=None,
    )

    end = PythonOperator(
        task_id="end",
        python_callable=lambda **kw: None,
        outlets=[Dataset(DATASET_URI)],
    )

    capture_tasks = []

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_backlog_metric",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/backlog_metric",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/backlog_metric",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "backlog_metric",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_backlog_metrics_salesforce",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/backlog_metrics_salesforce",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/backlog_metrics_salesforce",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "backlog_metrics_salesforce",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_cases_perspective",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/cases_perspective",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/cases_perspective",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "cases_perspective",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_csat_front",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/csat_front",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/csat_front",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "csat_front",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_customer_contacts_session",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/customer_contacts_session",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/customer_contacts_session",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "customer_contacts_session",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_demand_metric",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/demand_metric",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/demand_metric",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "demand_metric",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_email",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/email",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/email",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "email",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fcr_metric",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fcr_metric",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fcr_metric",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fcr_metric",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_general_metric",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/general_metric",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/general_metric",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "general_metric",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_listing_quality_sla",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/listing_quality_sla",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/listing_quality_sla",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "listing_quality_sla",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_listing_quality_tasks",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/listing_quality_tasks",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/listing_quality_tasks",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "listing_quality_tasks",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_nps_offboarding",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/nps_offboarding",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/nps_offboarding",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "nps_offboarding",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_recontact",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/recontact",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/recontact",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "recontact",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_repair_tickets",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/repair_tickets",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/repair_tickets",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "repair_tickets",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_satisfaction_salesforce",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/satisfaction_salesforce",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/satisfaction_salesforce",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "satisfaction_salesforce",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_segments_perspective",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/segments_perspective",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/segments_perspective",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "segments_perspective",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_speech_call",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/speech_call",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/speech_call",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "speech_call",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_speech_chat",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/speech_chat",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/speech_chat",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "speech_chat",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_tarefas_salesforce",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tarefas_salesforce",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tarefas_salesforce",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "tarefas_salesforce",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_taxonomy",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/taxonomy",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/taxonomy",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "taxonomy",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_tickets_contract",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tickets_contract",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tickets_contract",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "tickets_contract",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_tickets_perspective",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tickets_perspective",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tickets_perspective",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "tickets_perspective",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_tickets_transferred",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tickets_transferred",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tickets_transferred",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "tickets_transferred",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_tmr",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tmr",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/tmr",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "tmr",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_twilio_chat_aht",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/twilio_chat_aht",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/twilio_chat_aht",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "twilio_chat_aht",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_twilio_spoc",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/twilio_spoc",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/twilio_spoc",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "twilio_spoc",
            ],
            execution_timeout_hours=2,
        )
    )

    cluster_completion = get_job_cluster_completion_sink(ctx, execute_cluster, end)
    attach_emr_job_cluster_finished_work_prerequisites(
        ctx, job_cluster_finished_task=end, work_completion_tasks=capture_tasks
    )

    upload_sql >> execute_cluster >> capture_tasks >> cluster_completion
    attach_emr_terminate_cluster_work_prerequisites(
        ctx,
        cluster_completion,
        execute_job_cluster_task=execute_cluster,
        job_cluster_finished_task=end,
    )
