drop table if exists sortinghat.proposal;
create table sortinghat.proposal (
  id bigint not null,
  imovel_id bigint,
  analysis_date timestamp,
  score_5A int,
  score_5A_best_subset int,
  score_cardif int,
  score_cardif_best_subset int,
  status varchar,
  "comment" varchar,
  analyst_name varchar,
  supervisor_name varchar,
  rent_value numeric(14,4),
  condo_value numeric(14,4),
  iptu_value numeric(14,4),
  created_at timestamp,
  updated_at timestamp,
  home_area int,
  home_bathrooms int,
  home_bedrooms int,
  home_city varchar,
  home_garages int,
  home_region varchar,
  home_suites int,
  home_type varchar,
  home_zipcode varchar,
  drive_id varchar,
  rejection_motive varchar,
  home_insurance_value numeric(14,4),
  risk_level varchar,
  risk_level_best_subset varchar,
  process_date timestamp
);
