SELECT
    id,
    inspection_id AS id_inspection,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    previous_assessment_id AS id_previous_assessment,
    key_location,
    key_location_details,
    inspection_mod AS mod_inspection,
    previous_assessment_id_mod AS mod_id_previous_assessment,
    key_location_mod AS mod_key_location,
    key_location_details_mod AS mod_key_location_details,
    limit_revision_date_mod AS mod_dt_revision_limit,
    created_at_mod AS mod_ts_created,
    finished_at_mod AS mod_ts_finished,
    started_at_mod AS mod_ts_started,
    updated_at_mod AS mod_ts_updated,
    limit_revision_date AS dt_revision_limit,
    created_at AS ts_created,
    finished_at AS ts_finished,
    started_at AS ts_started,
    updated_at AS ts_updated
FROM
    datalake_inspections_raw.assessment_aud
