SELECT
    note_id AS id_note,
    enterprise_id AS id_enterprise,
    object_id AS id_object,
    author_id AS id_author_person,
    context_id AS id_context,
    context_id2 AS id_context_2,
    object_type,
    note_visibility_code,
    note_type_code,
    note_code,
    context_type,
    context_type2 AS context_type_2,
    context_name_vo,
    context_name_vo2 AS context_name_vo_2,
    note_text,
    note_text_audit,
    CAST(object_version_number AS INT) AS object_version_number,
    CAST(reference_count AS INT) AS reference_count,
    created_by,
    last_updated_by AS updated_by,
    hidden_flag = 'Y' AS is_hidden,
    CAST(note_creation_date AS TIMESTAMP) AS ts_note_created,
    CAST(note_last_update_date AS TIMESTAMP) AS ts_note_updated,
    CAST(creation_date AS TIMESTAMP) AS ts_created,
    CAST(last_update_date AS TIMESTAMP) AS ts_updated,
    NOW() AS ts_load,
    year,
    month,
    day
FROM
    datalake_pin_talent_raw.hrt_notes
