with actions_prev as (
  select distinct
    score_factor,
    id_rent_flow,
    actions,
    ts_init,
    receiver_name,
    ts_completed,
    "comment",
    id_origin,
    id_assignee,
    score,
    origin,
    ts_visit,
    type,
    receiver_type,
    description,
    phase,
    ts_silenced_until,
    id_house,
    subject,
    tags,
    id_opened_by,
    id_tenant,
    ts_created,
    id_negotiation,
    ts_origin,
    id_manager,
    ts_fup,
    visit_fup,
    metadata,
    v,
    id_owner,
    id_receiver,
    id,
    resolved,
    regexp_extract_all(actions, '{[^}]+[^,]+[^{]+}') as action_array
  from datalake_clean.crm_tasks
  where dt = '__PARTITION_DATE__'
),
actions as (
  select
    ct.*,
    replace(json_format(json_extract(a.action, '$.userName')), '"') as action_user_name,
    json_format(json_extract(a.action, '$.userId')) as id_user_action,
    cast(regexp_extract(json_format(json_extract(a.action, '$.date')), '\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}') as timestamp) as ts_action,
    replace(json_format(json_extract(a.action, '$.type')), '"') as action_type
  from actions_prev ct
  cross join unnest(action_array) as a (action)
)
select
  score_factor,
  id_rent_flow,
  actions,
  ts_init,
  receiver_name,
  ts_completed,
  "comment",
  id_origin,
  id_assignee,
  score,
  origin,
  ts_visit,
  type,
  receiver_type,
  description,
  phase,
  ts_silenced_until,
  id_house,
  subject,
  tags,
  id_opened_by,
  id_tenant,
  ts_created,
  id_negotiation,
  ts_origin,
  id_manager,
  ts_fup,
  visit_fup,
  metadata,
  v,
  id_owner,
  id_receiver,
  id,
  resolved,
  action_user_name,
  id_user_action,
  ts_action,
  action_type,
  lag(ts_action) over (partition by id order by ts_action) as ts_task_user_start,
  ts_action as ts_task_user_end,
  action_type as task_user_type,
  if(action_user_name is null, null,
    round(date_diff('second', lag(ts_action) over (partition by id order by ts_action), ts_action) / 3600.0, 1)) as task_user_resolve_hours
from actions
;
