# Define the dependencies among DAGs here in the following format:
#  dependent_dag_id_A:
#    - dag_dependency_id_B[:task_dependency_id_1]
#    - dag_dependency_id_C[:task_dependency_id_2]
#  dependent_dag_id_B:
#    - dag_dependency_id_D[:task_dependency_id_3]
#
# Place the dependencies sorted alphabetically

bietlejuice.dw_affiliate_costs:
  - bietlejuice.enrich_robin_hood

bietlejuice.dw_banking:
  - bietlejuice.ebdb:create-clean-bank-in-data-lake
  - bietlejuice.ebdb:create-clean-account-in-data-lake
  - bietlejuice.ebdb:create-clean-account-transaction-in-data-lake
  - bietlejuice.ebdb:create-clean-user-in-data-lake

bietlejuice.dw_booking:
  - bietlejuice.enrich_booking
  - bietlejuice.ebdb:create-clean-visit-in-data-lake
  - bietlejuice.enrich_amplitude_visit
  - bietlejuice.gsheets:load-taxonomy-demand-to-clean

bietlejuice.dw_braze_events_user_centric:
  - bietlejuice.enrich_braze_events_user_centric_periodicity:load-user-events-same-week-to-enrich
  - bietlejuice.enrich_braze_events_user_centric_periodicity:load-user-events-1w-before-to-enrich
  - bietlejuice.enrich_braze_events_user_centric_periodicity:load-user-events-2w-before-to-enrich
  - bietlejuice.enrich_braze_events_user_centric_periodicity:load-user-events-3w-before-to-enrich
  - bietlejuice.enrich_braze_events_user_centric_periodicity:load-user-events-all-time-before-to-enrich

bietlejuice.dw_braze_events_user_dispatch:
  - bietlejuice.enrich_braze_events_dispatches_user:load-owners-events-to-enrich
  - bietlejuice.enrich_braze_events_dispatches_user:load-tenants-events-to-enrich

bietlejuice.dw_call:
  - bietlejuice.enrich_bigfone_twilio:load-call-agents-to-enrich
  - bietlejuice.enrich_bigfone_twilio:load-call-flex-events-to-enrich
  - bietlejuice.enrich_bigfone_twilio:load-call-flex-reservations-to-enrich
  - bietlejuice.enrich_bigfone_twilio:load-call-ivr-events-to-enrich
  - bietlejuice.enrich_bigfone_twilio:load-call-ivr-paths-to-enrich
  - bietlejuice.enrich_bigfone_twilio:load-inbound-call-locations-to-enrich

bietlejuice.dw_chattermill:
  - bietlejuice.enrich_chattermill:load-responses-to-enrich

bietlejuice.dw_dim_listing_owner:
  - bietlejuice.ebdb:create-clean-partner-agent-in-data-lake
  - bietlejuice.ebdb:create-clean-user-preferences-in-data-lake
  - bietlejuice.enrich_ebdb_listing:load-enrich-listing-business-context
  - bietlejuice.enrich_ebdb_listing:load-enrich-house
  - bietlejuice.enrich_ebdb_user:load-user-to-enrich

bietlejuice.dw_front_tickets:
  - bietlejuice.enrich_front_tickets:load-call-to-enrich
  - bietlejuice.enrich_front_tickets:load-chat-to-enrich
  - bietlejuice.enrich_front_tickets:load-email-to-enrich
  - bietlejuice.gsheets:load-department-control-to-clean

bietlejuice.dw_house:
  - bietlejuice.enrich_ebdb_listing:load-enrich-house

bietlejuice.dw_invoice_entries:
  - bietlejuice.ebdb:create-clean-affiliate-data-in-data-lake
  - bietlejuice.ebdb:create-clean-contract-in-data-lake
  - bietlejuice.ebdb:create-clean-conversion-lead-in-data-lake
  - bietlejuice.ebdb:create-clean-house-in-data-lake
  - bietlejuice.ebdb:create-clean-lead-in-data-lake
  - bietlejuice.ebdb:create-clean-partner-agent-in-data-lake
  - bietlejuice.ebdb:create-clean-rent-flow-in-data-lake
  - bietlejuice.ebdb:create-clean-user-in-data-lake
  - bietlejuice.retsuko:load-account-to-clean
  - bietlejuice.retsuko:load-contract-to-clean
  - bietlejuice.retsuko:load-entry-to-clean
  - bietlejuice.retsuko:load-invoice-to-clean

bietlejuice.dw_marketing_costs:
  - bietlejuice.enrich_marketing_costs.load-google-keywords-performance-report-to-enrich:load-enrich-google-keywords-performance-report

bietlejuice.dw_marketing_costs_criteo_campaigns:
  - bietlejuice.enrich_marketing_costs_criteo_campaigns

bietlejuice.dw_marketing_costs_facebook_insights:
  - bietlejuice.enrich_marketing_costs_facebook_insights

bietlejuice.dw_marketing_costs_linkedin:
  - bietlejuice.linkedin

bietlejuice.dw_marketing_costs_mitula:
  - bietlejuice.mitula

bietlejuice.dw_marketing_costs_rtb_campaigns:
  - bietlejuice.rtb_campaigns

bietlejuice.dw_marketing_costs_trovit:
  - bietlejuice.trovit

bietlejuice.dw_proposal:
  - bietlejuice.enrich_proposal:load-proposal-to-enrich
  - bietlejuice.enrich_docx:load-credit-evaluation-to-enrich
  - bietlejuice.sorting_hat:load-proposal-to-datalake-clean
  - bietlejuice.sorting_hat:load-proposal-version-to-datalake-clean

bietlejuice.dw_quinto_messenger:
  - bietlejuice.enrich_ebdb_customer_contact_identification
  - bietlejuice.enrich_quinto_messenger

bietlejuice.dw_region:
  - bietlejuice.enrich_region
  - bietlejuice.enrich_booking
  - bietlejuice.enrich_ebdb_listing:load-enrich-house

bietlejuice.dw_rent_fact_listing_owners:
  - bietlejuice.enrich_listing_owners:load-rental-metrics-to-enrich

bietlejuice.dw_reservation:
  - bietlejuice.enrich_kill_queue

bietlejuice.dw_sale_flows:
  - bietlejuice.ebdb:create-clean-visit-in-data-lake
  - bietlejuice.enrich_amplitude_visit:load-amplitude-visit-to-enrich
  - bietlejuice.enrich_amplitude_offer:load-sale-offer-raw-events-to-enrich
  - bietlejuice.enrich_booking:load-booking-to-enrich
  - bietlejuice.enrich_ebdb_listing:load-enrich-listing-business-context
  - bietlejuice.enrich_sale_flows:load-sale-flow-to-enrich
  - bietlejuice.gsheets:load-taxonomy-demand-to-clean

bietlejuice.dw_sale_listings:
  - bietlejuice.ebdb:create-clean-house-in-data-lake
  - bietlejuice.ebdb:create-clean-house-registration-status-in-data-lake
  - bietlejuice.enrich_ebdb_listing:load-enrich-listing-business-context
  - bietlejuice.enrich_sale_listings:load-sale-listing-status-to-enrich
  - bietlejuice.enrich_sale_listings:load-sale-listing-to-enrich

bietlejuice.dw_sale_offers:
  - bietlejuice.ebdb:create-clean-house-in-data-lake
  - bietlejuice.enrich_amplitude_offer:load-sale-offer-raw-events-to-enrich
  - bietlejuice.enrich_offer:load-sale-offer-to-enrich
  - bietlejuice.gsheets:load-taxonomy-demand-to-clean

bietlejuice.dw_sale_visits:
  - bietlejuice.ebdb:create-clean-house-in-data-lake
  - bietlejuice.ebdb:create-clean-real-estate-agent-rating-in-data-lake
  - bietlejuice.enrich_booking:load-booking-to-enrich
  - bietlejuice.enrich_offer:load-sale-offer-to-enrich
  - bietlejuice.insider:load-review-to-datalake-clean

bietlejuice.dw_sauron:
  - bietlejuice.enrich_ebdb_customer_contact_identification
  - bietlejuice.enrich_quinto_messenger:load-channel-to-enrich
  - bietlejuice.enrich_sauron

bietlejuice.dw_smart_price:
  - bietlejuice.enrich_ebdb_smart_price:load-smart-price-versioning-to-enrich
  - bietlejuice.ebdb:create-clean-dynamic-pricing-house-in-data-lake
  - bietlejuice.ebdb:create-clean-dynamic-pricing-parameters-in-data-lake

bietlejuice.dw_tickets:
  - bietlejuice.enrich_zendesk_ticket_funnels
  - bietlejuice.enrich_zendesk_tickets

bietlejuice.dw_tracksale:
  - bietlejuice.enrich_tracksale
  - bietlejuice.enrich_nps_answer_drivers
  - bietlejuice.enrich_ebdb_customer_contact_identification

bietlejuice.dw_user:
  - bietlejuice.ebdb:create-clean-partner-in-data-lake
  - bietlejuice.ebdb:create-clean-partner-agent-in-data-lake
  - bietlejuice.enrich_ebdb_user:load-user-doorman-to-enrich
  - bietlejuice.ebdb:create-clean-visit-in-data-lake
  - bietlejuice.ebdb:create-clean-rent-flow-in-data-lake
  - bietlejuice.ebdb:create-clean-pre-proposal-in-data-lake
  - bietlejuice.ebdb:create-clean-proposal-in-data-lake
  - bietlejuice.ebdb:create-clean-contract-in-data-lake
  - bietlejuice.ebdb:create-clean-state-in-data-lake
  - bietlejuice.ebdb:create-clean-bank-in-data-lake
  - bietlejuice.ebdb:create-clean-photographer-data-in-data-lake
  - bietlejuice.ebdb:create-clean-sales-rep-in-data-lake
  - bietlejuice.enrich_booking:load-booking-to-enrich
  - bietlejuice.enrich_ebdb_user:load-user-to-enrich
  - bietlejuice.enrich_ebdb_user:load-agent-data-to-enrich
  - bietlejuice.enrich_ebdb_user:load-affiliate-data-to-enrich
  - bietlejuice.enrich_amplitude_partner_taxonomy:load-amplitude-partner-taxonomy-to-enrich

bietlejuice.dw_user_affiliate:
  - bietlejuice.enrich_amplitude_user:load-user-affiliate-origin-to-enrich
  - bietlejuice.enrich_ebdb_user:load-affiliate-data-to-enrich
  - bietlejuice.enrich_ebdb_user:load-user-to-enrich
  - bietlejuice.enrich_ebdb_user:load-agent-data-to-enrich
  - bietlejuice.enrich_region:load-enrich-region
  - bietlejuice.gsheets:load-taxonomy-affiliates-to-clean

bietlejuice.dw_user_sales_rep:
  - bietlejuice.enrich_ebdb_user:load-user-sales-rep-to-enrich

bietlejuice.dw_visit:
  - bietlejuice.ebdb:create-clean-visit-in-data-lake

bietlejuice.enrich_amplitude_offer:
  - bietlejuice.amplitude

bietlejuice.enrich_amplitude_page_viewed_events:
  - bietlejuice.amplitude

bietlejuice.enrich_amplitude_partner_taxonomy:
  - bietlejuice.amplitude:events-raw-to-clean

bietlejuice.enrich_amplitude_user:
  - bietlejuice.amplitude:update-clean-events-daily-partition-athena

bietlejuice.enrich_amplitude_visit:
  - bietlejuice.amplitude

bietlejuice.enrich_bigfone_events:
  - bietlejuice.bigfone:load-event-to-clean

bietlejuice.enrich_bigfone_twilio:
  - bietlejuice.enrich_bigfone_events:load-events-to-enrich

bietlejuice.enrich_bob:
  - bietlejuice.bob:load-house-draft-aud-to-clean
  - bietlejuice.bob:load-house-draft-to-clean

bietlejuice.enrich_booking:
  - bietlejuice.ebdb:create-clean-booking-in-data-lake
  - bietlejuice.ebdb:create-clean-booking-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-follow-up-details-in-data-lake
  - bietlejuice.ebdb:create-clean-entrance-in-data-lake
  - bietlejuice.ebdb:create-clean-booking-status-change-in-data-lake
  - bietlejuice.ebdb:create-clean-appointment-change-reason-category-in-data-lake
  - bietlejuice.ebdb:create-clean-user-revision-entity-in-data-lake
  - bietlejuice.ebdb:create-clean-visit-in-data-lake
  - bietlejuice.ebdb:create-clean-visit-origin-in-data-lake
  - bietlejuice.ebdb:create-clean-visitor-in-data-lake
  - bietlejuice.gsheets:load-from-to-cancellation-to-clean

bietlejuice.enrich_braze_events:
  - bietlejuice.braze_events:load-events-tenants-to-clean
  - bietlejuice.braze_events:load-events-owners-to-clean

bietlejuice.enrich_braze_events_dispatches:
  - bietlejuice.enrich_braze_events:load-events-tenants-to-enrich
  - bietlejuice.enrich_braze_events:load-events-owners-to-enrich

bietlejuice.enrich_braze_events_dispatches_user:
  - bietlejuice.enrich_braze_events:load-events-tenants-to-enrich
  - bietlejuice.enrich_braze_events:load-events-owners-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-inapp-tenants-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-sms-tenants-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-email-tenants-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-webhook-tenants-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-push-tenants-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-inapp-owners-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-sms-owners-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-email-owners-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-webhook-owners-to-enrich
  - bietlejuice.enrich_braze_events_dispatches:load-push-owners-to-enrich

bietlejuice.enrich_braze_events_user_centric:
  - bietlejuice.enrich_braze_events:load-events-tenants-to-enrich
  - bietlejuice.enrich_braze_events:load-events-owners-to-enrich

bietlejuice.enrich_braze_events_user_centric_periodicity:
  - bietlejuice.enrich_braze_events_user_centric:load-user-events-daily-to-enrich

bietlejuice.enrich_chattermill:
  - bietlejuice.chattermill:load-responses-to-clean

bietlejuice.enrich_consolidated_marketing_costs:
  - bietlejuice.enrich_marketing_costs
  - bietlejuice.enrich_marketing_costs_criteo_campaigns:load-criteo-campaigns-to-enrich
  - bietlejuice.enrich_marketing_costs_sharing_rules:load-old-sharing-rules-from-redshift-to-datalake
  - bietlejuice.mitula:load-mitula-report-to-clean
  - bietlejuice.rtb_campaigns:load-rtb-campaigns-to-clean
  - bietlejuice.trovit:load-trovit-report-to-clean

bietlejuice.enrich_credit_evers:
  - bietlejuice.enrich_invoice:load-credit-invoice-original-due-date-to-enrich
  - bietlejuice.enrich_invoice:load-credit-invoice-to-enrich

bietlejuice.enrich_crm:
  - bietlejuice.crm

bietlejuice.enrich_crm_tasks_resolution:
  - bietlejuice.enrich_crm:load-tasks-actions-to-enrich
  - bietlejuice.enrich_crm:load-tasks-to-enrich
  - bietlejuice.enrich_crm:load-task-status-histories-to-enrich

bietlejuice.enrich_docx:
  - bietlejuice.docx:load-credit-evaluation-to-clean

bietlejuice.enrich_ebdb_contract:
  - bietlejuice.ebdb:create-clean-contract-in-data-lake
  - bietlejuice.ebdb:create-clean-contract-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-contract-version-in-data-lake
  - bietlejuice.ebdb:create-clean-full-contract-in-data-lake
  - bietlejuice.ebdb:create-clean-rent-flow-in-data-lake
  - bietlejuice.ebdb:create-clean-user-revision-entity-in-data-lake
  - bietlejuice.enrich_ebdb_listing:load-enrich-house
  - bietlejuice.enrich_ebdb_listing:load-enrich-house-listing

bietlejuice.enrich_ebdb_customer_contact_identification:
  - bietlejuice.ebdb:create-clean-user-in-data-lake
  - bietlejuice.ebdb:create-clean-user-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-contract-person-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-proponent-proposal-aud-in-data-lake

bietlejuice.enrich_ebdb_listing:
  - bietlejuice.ebdb:create-clean-portability-in-data-lake
  - bietlejuice.ebdb:create-clean-listing-business-context-in-data-lake
  - bietlejuice.ebdb:create-clean-listing-business-context-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-user-revision-entity-in-data-lake
  - bietlejuice.ebdb:create-clean-house-in-data-lake
  - bietlejuice.ebdb:create-clean-house-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-house-special-condition-in-data-lake
  - bietlejuice.ebdb:create-clean-special-condition-in-data-lake
  - bietlejuice.ebdb:create-clean-special-condition-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-house-visit-information-in-data-lake
  - bietlejuice.ebdb:create-clean-state-in-data-lake
  - bietlejuice.ebdb:create-clean-map-region-in-data-lake
  - bietlejuice.ebdb:create-clean-condo-in-data-lake
  - bietlejuice.ebdb:create-clean-local-in-data-lake
  - bietlejuice.ebdb:create-clean-access-type-in-data-lake
  - bietlejuice.ebdb:create-clean-occupant-type-in-data-lake
  - bietlejuice.ebdb:create-clean-key-type-in-data-lake
  - bietlejuice.ebdb:create-clean-access-authorization-type-in-data-lake
  - bietlejuice.ebdb:create-clean-restriction-type-in-data-lake
  - bietlejuice.ebdb:create-clean-house-registration-status-in-data-lake

bietlejuice.enrich_ebdb_listing_jobs:
  - bietlejuice.ebdb:create-clean-house-registration-status-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-inspection-in-data-lake
  - bietlejuice.ebdb:create-clean-inspection-item-in-data-lake
  - bietlejuice.ebdb:create-clean-photographer-data-in-data-lake
  - bietlejuice.ebdb:create-clean-photographer-job-in-data-lake
  - bietlejuice.ebdb:create-clean-photographer-job-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-user-in-data-lake
  - bietlejuice.enrich_ebdb_user_revision_entity

bietlejuice.enrich_ebdb_proposal:
  - bietlejuice.ebdb:create-clean-pre-proposal-in-data-lake
  - bietlejuice.ebdb:create-clean-pre-proposal-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-user-revision-entity-in-data-lake
  - bietlejuice.ebdb:create-clean-pre-proposal-condition-in-data-lake
  - bietlejuice.ebdb:create-clean-proposal-condition-in-data-lake

bietlejuice.enrich_ebdb_smart_price:
  - bietlejuice.ebdb:create-clean-house-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-dynamic-pricing-house-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-user-revision-entity-in-data-lake

bietlejuice.enrich_ebdb_user:
  - bietlejuice.ebdb:create-clean-affiliate-data-in-data-lake
  - bietlejuice.ebdb:create-clean-agent-data-in-data-lake
  - bietlejuice.ebdb:create-clean-agent-data-business-contexts-served-in-data-lake
  - bietlejuice.ebdb:create-clean-contract-in-data-lake
  - bietlejuice.ebdb:create-clean-device-in-data-lake
  - bietlejuice.ebdb:create-clean-doorman-affiliate-data-in-data-lake
  - bietlejuice.ebdb:create-clean-doorman-affiliate-occupation-in-data-lake
  - bietlejuice.ebdb:create-clean-house-in-data-lake
  - bietlejuice.ebdb:create-clean-proposal-in-data-lake
  - bietlejuice.ebdb:create-clean-proposal-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-sales-rep-in-data-lake
  - bietlejuice.ebdb:create-clean-user-in-data-lake
  - bietlejuice.ebdb:create-clean-user-revision-entity-in-data-lake

bietlejuice.enrich_ebdb_user_revision_entity:
  - bietlejuice.ebdb:create-clean-user-revision-entity-in-data-lake

bietlejuice.enrich_firestore:
  - bietlejuice.firestore:load-monday-to-clean
  - bietlejuice.firestore:load-rent-offer-to-clean
  - bietlejuice.firestore:load-sale-offer-to-clean

bietlejuice.enrich_front_tickets:
  - bietlejuice.chat_fup:load-chats-chat-to-datalake-clean
  - bietlejuice.chat_fup:load-surveys-answer-to-datalake-clean
  - bietlejuice.chat_fup:load-surveys-survey-to-datalake-clean
  - bietlejuice.enrich_bigfone_twilio:load-call-flex-reservations-to-enrich
  - bietlejuice.enrich_bigfone_twilio:load-call-flex-events-to-enrich
  - bietlejuice.enrich_bigfone_twilio:load-call-ivr-events-to-enrich
  - bietlejuice.enrich_bigfone_twilio:load-call-ivr-paths-to-enrich
  - bietlejuice.enrich_quinto_messenger:load-channel-event-to-enrich
  - bietlejuice.enrich_quinto_messenger:load-channel-to-enrich
  - bietlejuice.enrich_quinto_messenger:load-task-to-enrich
  - bietlejuice.enrich_quinto_messenger:load-task-event-to-enrich
  - bietlejuice.enrich_survicate:load-enrich-surveys
  - bietlejuice.enrich_zendesk_ticket_funnels:load-tickets-funnel-metrics-to-enrich
  - bietlejuice.enrich_zendesk_ticket_funnels:load-ticket-funnel-to-enrich
  - bietlejuice.gsheets:load-agents-control-to-clean
  - bietlejuice.gsheets:load-department-control-to-clean

bietlejuice.enrich_invoice:
  - bietlejuice.ebdb:create-clean-contract-in-data-lake
  - bietlejuice.retsuko:load-account-to-clean
  - bietlejuice.retsuko:load-contract-to-clean
  - bietlejuice.retsuko:load-entry-to-clean
  - bietlejuice.retsuko:load-invoice-to-clean

bietlejuice.enrich_kill_queue:
  - bietlejuice.kill_queue:load-house-to-datalake-clean
  - bietlejuice.kill_queue:load-reservation-to-datalake-clean

bietlejuice.enrich_listing_owners:
  - bietlejuice.ebdb:create-clean-proposal-in-data-lake
  - bietlejuice.enrich_booking:load-booking-to-enrich
  - bietlejuice.enrich_ebdb_contract:load-enrich-contract
  - bietlejuice.enrich_ebdb_listing:load-enrich-listing-business-context
  - bietlejuice.enrich_ebdb_listing:load-enrich-house-listing-status
  - bietlejuice.enrich_ebdb_listing:load-enrich-house
  - bietlejuice.enrich_kill_queue:load-reservation-to-enrich
  - bietlejuice.enrich_offer:load-offer-to-enrich

bietlejuice.enrich_marketing_automatic_daily_costs:
  - bietlejuice.enrich_consolidated_marketing_costs:load-consolidated-media-costs-to-enrich

bietlejuice.enrich_marketing_costs:
  - bietlejuice.marketing_hub

bietlejuice.enrich_marketing_costs_criteo_campaigns:
  - bietlejuice.criteo_campaigns:load-criteo-campaigns-to-clean

bietlejuice.enrich_marketing_costs_facebook_insights:
  - bietlejuice.facebook_insights

bietlejuice.enrich_marketing_costs_offline:
  - bietlejuice.marketing_offline_costs

bietlejuice.enrich_marketing_manual_daily_costs:
  - bietlejuice.marketing_manual_daily_costs:load-marketing-costs-name-convention-shared-costs-to-clean
  - bietlejuice.marketing_manual_daily_costs:load-marketing-costs-manual-shared-costs-to-clean

bietlejuice.enrich_nps_answer_drivers:
  - bietlejuice.enrich_tracksale:load-answer-to-enrich
  - bietlejuice.ebdb:create-clean-house-in-data-lake
  - bietlejuice.ebdb:create-clean-booking-in-data-lake
  - bietlejuice.ebdb:create-clean-offer-in-data-lake
  - bietlejuice.ebdb:create-clean-contract-in-data-lake
  - bietlejuice.enrich_ebdb_listing:load-enrich-house-listing

bietlejuice.enrich_offer:
  - bietlejuice.ebdb:create-clean-offer-in-data-lake
  - bietlejuice.ebdb:create-clean-offer-aud-in-data-lake
  - bietlejuice.enrich_booking:load-booking-to-enrich
  - bietlejuice.enrich_ebdb_user_revision_entity:load-enrich-user-revision-entity
  - bietlejuice.enrich_firestore
  - bietlejuice.godfather:load-business-offer

bietlejuice.enrich_owner_fees:
  - bietlejuice.owner_fees:load-contract-to-clean

bietlejuice.enrich_proposal:
  - bietlejuice.ebdb:create-clean-proposal-in-data-lake
  - bietlejuice.ebdb:create-clean-proposal-aud-in-data-lake
  - bietlejuice.enrich_ebdb_user_revision_entity:load-enrich-user-revision-entity
  - bietlejuice.sorting_hat:load-proposal-to-datalake-clean
  - bietlejuice.sorting_hat:load-proposal-version-to-datalake-clean

bietlejuice.enrich_quinto_messenger:
  - bietlejuice.quinto_messenger:load-channel-to-clean
  - bietlejuice.quinto_messenger:load-channel-event-to-clean
  - bietlejuice.quinto_messenger:load-task-to-clean
  - bietlejuice.quinto_messenger:load-task-event-to-clean

bietlejuice.enrich_region:
  - bietlejuice.ebdb:create-clean-region-in-data-lake
  - bietlejuice.gsheets:load-auxiliary-region-to-clean

bietlejuice.enrich_retsuko:
  - bietlejuice.retsuko:load-account-to-clean
  - bietlejuice.retsuko:load-entry-to-clean
  - bietlejuice.retsuko:load-invoice-to-clean

bietlejuice.enrich_robin_hood:
  - bietlejuice.robin_hood:load-accounting-entry-to-datalake-clean
  - bietlejuice.robin_hood:load-payee-to-datalake-clean
  - bietlejuice.robin_hood:load-tax-to-datalake-clean

bietlejuice.enrich_sale_flows:
  - bietlejuice.ebdb:create-clean-house-in-data-lake
  - bietlejuice.enrich_ebdb_listing:load-enrich-listing-business-context
  - bietlejuice.enrich_offer:load-sale-offer-to-enrich

bietlejuice.enrich_sale_listings:
  - bietlejuice.ebdb:create-clean-house-in-data-lake
  - bietlejuice.ebdb:create-clean-house-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-listing-business-context-in-data-lake
  - bietlejuice.ebdb:create-clean-listing-business-context-aud-in-data-lake
  - bietlejuice.ebdb:create-clean-user-revision-entity-in-data-lake
  - bietlejuice.enrich_ebdb_listing:load-enrich-listing-business-context
  - bietlejuice.enrich_ebdb_user_revision_entity:load-enrich-user-revision-entity

bietlejuice.enrich_sauron:
  - bietlejuice.sauron:load-clean-session

bietlejuice.enrich_survicate:
  - bietlejuice.survicate:load-surveys-to-clean

bietlejuice.enrich_terminator:
  - bietlejuice.terminator:load-clean-termination-aud

bietlejuice.enrich_top_of_funnel_demand:
  - bietlejuice.amplitude:update-clean-staging-subpartitioned-tables-spark

bietlejuice.enrich_tracksale:
  - bietlejuice.tracksale:load-dispatch-to-clean
  - bietlejuice.tracksale:load-answer-to-clean

bietlejuice.enrich_zendesk_custom_fields:
  - bietlejuice.zendesk_tickets

bietlejuice.enrich_zendesk_ticket_funnels:
  - bietlejuice.enrich_ebdb_contract:load-enrich-contract-house
  - bietlejuice.enrich_ebdb_customer_contact_identification:load-customer-contact-identification-to-enrich
  - bietlejuice.enrich_zendesk_custom_fields:load-enrich-custom-fields
  - bietlejuice.enrich_zendesk_tickets:load-ticket-measurements-to-enrich
  - bietlejuice.enrich_zendesk_tickets:load-zendesk-users-contact-to-enrich

bietlejuice.enrich_zendesk_tickets:
  - bietlejuice.enrich_zendesk_custom_fields:load-enrich-custom-fields

bietlejuice.regions_polygon:
  - bietlejuice.enrich_region:load-enrich-region
  - bietlejuice.ebdb:create-clean-polygon-region-in-data-lake

bietlejuice.dw_tenant_booking_review:
  - bietlejuice.ebdb:create-clean-visit-in-data-lake
  - bietlejuice.ebdb:create-clean-booking-in-data-lake
  - bietlejuice.insider:load-review-feature-to-datalake-clean
  - bietlejuice.insider:load-review-to-datalake-clean
