"""Migration EMR DAG — run transpiled queries on EMR, capture metrics to S3.

Auto-generated by emr-migration-v2 skill.
Run ID: 03c62042-3e72-4dee-a98b-735452df845f
Scope: platform/enrich_databricks
"""

import os
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import urlparse

import yaml
from airflow import DAG, Dataset
from airflow.operators.python import PythonOperator

from bietlejuice.base.airflow.job_cluster_engine import (
    attach_emr_job_cluster_finished_work_prerequisites,
    attach_emr_terminate_cluster_work_prerequisites,
    attach_job_cluster_engine_to_context,
    get_job_cluster_completion_sink,
)
from bietlejuice.base.airflow.task_creators.dag_execution_context import (
    DagExecutionContext,
)
from bietlejuice.services.configuration_service import ConfigurationService

DAG_ID = "migration_emr_platform__enrich_databricks"
RUN_ID = "03c62042-3e72-4dee-a98b-735452df845f"
DOMAIN = "platform"
SOURCE_DAG_NAME = "enrich_databricks"
DATASET_URI = "migration:emr-platform__enrich_databricks-complete"
RUN_PREFIX = "emr-migration/runs/03c62042-3e72-4dee-a98b-735452df845f"
RUNTIME = "emr"
SQL_DIR_NAME = "migration"

TABLES = [
    "daily_clusters",
    "daily_table_privileges",
    "unique_clusters",
    "unique_groups",
    "unique_service_principals",
    "unique_users",
]

DAG_DIR = Path(__file__).resolve().parent
ENV = os.environ.get("ENVIRONMENT")
CONFIG_SERVICE = ConfigurationService(SOURCE_DAG_NAME)
BUCKET = CONFIG_SERVICE.get_config("datalake_bucket")
BIETLEJUICE_REPO_PATH = CONFIG_SERVICE.get_config("databricks_bietlejuice_repo_path")
METRIC_CAPTURE_JOB = (
    f"{BIETLEJUICE_REPO_PATH}/spark_jobs/migration_assets/metric_capture_job.py"
)
ARTIFACTS_URI = CONFIG_SERVICE.get_config("artifacts_bucket")
ARTIFACTS_BUCKET = urlparse(ARTIFACTS_URI).netloc or ARTIFACTS_URI

with open(DAG_DIR / f"{DAG_ID}_cluster.yml") as _f:
    CLUSTER_ARGS = yaml.safe_load(_f).get("cluster", {})


def _build_context(dag):
    ctx = DagExecutionContext(
        dag=dag,
        environment=ENV,
        bucket=BUCKET,
        base_spark_jobs_path=f"{BIETLEJUICE_REPO_PATH}/spark_jobs/base/",
        dag_args={},
        workflow_args={},
        cluster_args=CLUSTER_ARGS,
        databricks_conn_id=CLUSTER_ARGS.get("databricks_conn_id", "databricks_new_env"),
    )
    attach_job_cluster_engine_to_context(ctx, CONFIG_SERVICE)
    return ctx


def _get_s3_client():
    import boto3
    from airflow.models import Variable

    role_arn = Variable.get("DATASET_EVENTS_ASSUME_ROLE_ARN", default_var=None)
    if not role_arn:
        return boto3.client("s3")
    sts = boto3.client("sts")
    creds = sts.assume_role(
        RoleArn=role_arn,
        RoleSessionName="migration-s3-upload",
        DurationSeconds=3600,
    )["Credentials"]
    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
    ).client("s3")


def _upload_sql(**context):
    sql_dir = DAG_DIR / "queries" / SQL_DIR_NAME
    s3 = _get_s3_client()
    for table in TABLES:
        local_path = str(sql_dir / f"{table}.sql")
        s3_key = f"{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}.sql"
        s3.upload_file(local_path, ARTIFACTS_BUCKET, s3_key)


with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["migration", "emr", "validation"],
    default_args={"owner": "data-platform", "retries": 0},
    dagrun_timeout=timedelta(hours=4),
) as dag:
    ctx = _build_context(dag)

    upload_sql = PythonOperator(
        task_id="upload_sql",
        python_callable=_upload_sql,
    )

    execute_cluster = ctx.job_cluster_engine.create_execute_cluster_task(
        config_service=CONFIG_SERVICE,
        minimum_cluster_runtime_version=None,
        execute_job_cluster_local_id=None,
    )

    end = PythonOperator(
        task_id="end",
        python_callable=lambda **kw: None,
        outlets=[Dataset(DATASET_URI)],
    )

    capture_tasks = []

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_daily_clusters",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/daily_clusters",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/daily_clusters",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "daily_clusters",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_daily_table_privileges",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/daily_table_privileges",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/daily_table_privileges",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "daily_table_privileges",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_unique_clusters",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/unique_clusters",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/unique_clusters",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "unique_clusters",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_unique_groups",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/unique_groups",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/unique_groups",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "unique_groups",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_unique_service_principals",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/unique_service_principals",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/unique_service_principals",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "unique_service_principals",
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_unique_users",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/unique_users",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/unique_users",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "unique_users",
            ],
            execution_timeout_hours=2,
        )
    )

    cluster_completion = get_job_cluster_completion_sink(ctx, execute_cluster, end)
    attach_emr_job_cluster_finished_work_prerequisites(
        ctx, job_cluster_finished_task=end, work_completion_tasks=capture_tasks
    )

    upload_sql >> execute_cluster >> capture_tasks >> cluster_completion
    attach_emr_terminate_cluster_work_prerequisites(
        ctx,
        cluster_completion,
        execute_job_cluster_task=execute_cluster,
        job_cluster_finished_task=end,
    )
