let
    Source = Odbc.DataSource("dsn=DW", [HierarchicalNavigation=true]),
    dw_Database = Source{[Name="dw",Kind="Database"]}[Data],
    public_Schema = dw_Database{[Name="public",Kind="Schema"]}[Data],
    dim_property_Table = public_Schema{[Name="dim_property",Kind="Table"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(dim_property_Table,{"email_sessao_fotos", "tel_contato2", "tel_sessao_fotos", "usuario_id", "codigo_promocao", "followup_proprietario_subir_fotos", "calculo_pagamento_lead_corretor", "nome_imagem_capa", "calculo_pagamento_lead_afiliado", "cartorio", "receber_copia_contrato_padrao", "confirmado_informacoes_visita", "suspenso_ate", "load_timestamp", "ultimo_update_indice"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"elevador", type logical}, {"fotografo_preenche_dados", type logical}, {"mobiliado", type logical}, {"prefere_email_sessao_fotos", type logical}, {"verificado", type logical}, {"cotar_seguro", type logical}, {"notificacao_anuncio_incompleto_proprietario", type logical}, {"notificacao_anuncio_incompleto_admin", type logical}, {"sugerir_reajuste_de_preco", type logical}, {"permite_placa_aluga_se", type logical}, {"prioridade_destaque_classificado", type logical}, {"condominio_incluso", type logical}, {"coordenadas_manuais", type logical}, {"iptu_incluso", type logical}, {"possui_banheiro_servico", type logical}, {"possui_quarto_servico", type logical}, {"flag_verificar_preco_comparando_com_media", type logical}, {"sempre_consultar_proprietario_visita", type logical}, {"email_publicacao_proprietario_enviado", type logical}, {"em_negociacao", type logical}, {"em_negociacao_externa", type logical}, {"job_fotografo_pendente", type logical}, {"requisitou_fotos_profissionais", type logical}}),
    #"Merged Queries" = Table.NestedJoin(#"Changed Type",{"id"},#"Marketing Attribution",{"imovel_id"},"NewColumn",JoinKind.LeftOuter),
    #"Expanded NewColumn" = Table.ExpandTableColumn(#"Merged Queries", "NewColumn", {"uuid", "campaign", "channel", "event_type", "mobile_app", "platform", "subchannel", "adquirido_em"}, {"Marketing Acquisition.uuid", "Marketing Acquisition.campaign", "Marketing Acquisition.channel", "Marketing Acquisition.event_type", "Marketing Acquisition.mobile_app", "Marketing Acquisition.platform", "Marketing Acquisition.subchannel", "Marketing Acquisition.adquirido_em"})
in
    #"Expanded NewColumn"