SELECT
    id AS id_mortgage,
    sales_flow_id AS id_sales_flow,
    status,
    bank,
    credit_model,
    credit_status,
    bank_fee,
    institution_choice_reason,
    credit_letter,
    mortgage_pendency,
    approved_amount,
    approved_value_less_than_requested,    
    entry_amount_paid_finished_by,
    financed_value,
    payment_id AS payment_id,
    installments_quantity,
    is_entry_amount_paid,
    is_itbi_paid,
    itbi_paid_finished_by,
    credit_start_date AS dt_credit_started,
    credit_end_date AS dt_credit_ended,
    bank_start_date AS dt_bank_started,
    start_date AS dt_started,
    end_date AS dt_ended,
    seller_paid_at AS ts_seller_paid,
    entry_amount_paid_at AS ts_entry_amount_paid,
    itbi_paid_at AS ts_itbi_paid,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM 
    datalake_sales_flow_raw.mortgage