SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    sales_flow_id AS id_sales_flow,
    sales_flow_id_mod AS mod_id_sales_flow,
    signed_document_reference AS uuid_signed_document_reference,
    signed_document_reference_mod AS mod_uuid_signed_document_reference,
    unsigned_document_reference AS uuid_unsigned_document_reference,
    unsigned_document_reference_mod AS mod_uuid_unsigned_document_reference,
    status,
    status_mod AS mod_status,
    template_version,
    template_version_mod AS mod_template_version,
    signed_document_origin,
    signed_document_origin_mod AS mod_signed_document_origin,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.tic_aud
