DROP TABLE IF EXISTS quintoandar.dim_house;
CREATE TABLE quintoandar.dim_house (
    sk_house BIGINT PRIMARY KEY,
    id_short_house BIGINT,
    condo INT,
    land_area INT,
    total_area INT,
    iptu INT,
    bathrooms INT,
    bedrooms INT,
    parking_slots INT,
    suites INT,
    lat DECIMAL(10,7),
    lng DECIMAL(10,7),
    number VARCHAR,
    address VARCHAR,
    city VARCHAR,
    complement VARCHAR,
    neighborhood VARCHAR,
    zipcode VARCHAR,
    geo_hash VARCHAR,
    registry VARCHAR,
    built_period VARCHAR,
    condo_type VARCHAR,
    conservation_status VARCHAR,
    doorman_type VARCHAR,
    iptu_type VARCHAR,
    key_location VARCHAR,
    key_type VARCHAR,
    occupant_type VARCHAR,
    parking_slot_type VARCHAR,
    type VARCHAR,
    does_photographer_fill_information BOOLEAN,
    has_elevator BOOLEAN,
    has_service_bathroom BOOLEAN,
    has_service_bedroom BOOLEAN,
    has_visit_restriction BOOLEAN,
    is_furnished BOOLEAN,
    is_iptu_included BOOLEAN,
    is_verified BOOLEAN,
    is_warn_owner_of_visits_needed BOOLEAN,
    ts_first_verified TIMESTAMP,
    ts_created TIMESTAMP,
    ts_updated TIMESTAMP,
    ts_load TIMESTAMP
)
ALTER TABLE quintoandar.dim_house OWNER TO airflow;