SELECT
    n_cadastro_sql AS iptu_sql_registration_number,
    matricula_imovel AS house_registry_number,
    nome_logradouro AS address_street_name,
    numero AS address_number,
    complemento AS address_complement,
    bairro AS address_neighborhood,
    referencia AS address_reference,
    cep AS address_zipcode,
    natureza_transacao AS transaction_nature,
    tipo_financiamento AS financing_type,
    cartorio_registro AS house_registry_office,
    situacao_sql AS iptu_sql_status,
    descricao_uso_iptu AS iptu_use_description,
    descricao_padrao_iptu AS iptu_standard_description,
    valor_transacao_declarado AS declared_transaction_value,
    valor_venal_referencia AS reference_appraisal_value,
    proporcao_transmitida AS transmitted_proportion,
    valor_venal_referencia_proporcional AS proportional_reference_appraisal_value,
    base_calculo_adotada AS adopted_calculation_basis,
    valor_financiado AS financed_value,
    area_terreno_m2 AS land_area_m2,
    testada_m AS portion_public_road_land_m,
    fracao_ideal AS ideal_fraction,
    area_construida_m2 AS built_area_m2,
    uso_iptu AS iptu_use_code,
    padrao_iptu AS iptu_standard_code,
    acc_iptu AS iptu_registration_year,
    source_file,
    source_tab,
    data_transacao AS dt_transaction,
    dt_load,
    year,
    month,
    day
FROM
    datalake_itbi_raw.itbi_sp
WHERE
    dt_load = current_date