SELECT 
  id_house_platform,
  id_house,
  platform,
  country,
  state,
  address_city,
  neighborhood,
  street,
  zip_code,
  listing_name,
  total_area,
  amenities,
  bathrooms,
  bedrooms,
  parking_spaces,
  unit_type,
  unit_subtype,
  advertiser_id,
  advertiser_name,
  advertiser_phone,
  condo_fee,
  iptu,
  rent_price,
  sale_price,
  price_m2_rental,
  price_m2_sale,
  is_for_rent,
  is_for_sale,
  is_hybrid,
  ts_created,
  year,
  month,
  day
FROM 
  datalake_crawler_olx.olx
WHERE
  MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY id_house ORDER BY MAKE_DATE(year, month, day) DESC) = 1