CREATE TABLE IF NOT EXISTS staging.marketing_google_ads_ads (
    id bigint identity(0,1),
    account_id varchar,
    adgroup_id varchar,
    adgroup_name varchar,
    ad_type varchar,
    campaign_id varchar,
    campaign_name varchar,
    clicks varchar,
    click_type varchar,
    cost varchar,
    keyword_id varchar,
    date varchar,
    device varchar,
    ad_id varchar,
    impressions varchar,
    labels varchar,
    image_creative_name varchar,
    account_name varchar,
    description varchar,
    description1 varchar,
    description2 varchar,
    acc varchar,
    dt_created varchar
)