SELECT
    id AS id_credit_analysis_version,
    created_at AS ts_created,
    updated_at AS ts_updated,
    level,
    type,
    should_interview,
    result,
    rejection_motive,
    comment,
    analyst_name,
    analyst_main_id AS id_analyst,
    proposal_id AS id_proposal,
    transaction_id AS id_transaction,
    end_transaction_id AS id_end_transaction,
    operation_type,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    level_mod AS mod_level,
    type_mod AS mod_type,
    should_interview_mod AS mod_should_interview,
    result_mod AS mod_result,
    rejection_motive_mod AS mod_rejection_motive,
    comment_mod AS mod_comment,
    analyst_name_mod AS mod_analyst_name,
    analyst_main_id_mod AS mod_id_analyst,
    proposal_id_mod AS mod_id_proposal
FROM
    datalake_sorting_hat_raw.`creditanalysis_version`