SELECT
    id AS id_credit_analysis_version,
    created_at AS ts_created,
    updated_at AS ts_updated,
    level,
    type,
    should_interview as is_a_potential_interview,
    result,
    reason,
    comment,
    analyst_name,
    analyst_main_id AS id_analyst,
    proposal_id AS id_proposal,
    transaction_id AS id_transaction,
    end_transaction_id AS id_end_transaction,
    operation_type,
    category,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    level_mod AS mod_level,
    type_mod AS mod_type,
    should_interview_mod AS mod_is_a_potential_interview,
    result_mod AS mod_result,
    reason_mod AS mod_reason,
    comment_mod AS mod_comment,
    analyst_name_mod AS mod_analyst_name,
    analyst_main_id_mod AS mod_id_analyst,
    proposal_id_mod AS mod_id_proposal,
    category_mod as mod_category,
    automatic_decision_reason,
    automatic_decision_reason_mod AS mod_automatic_decision_reason,
    bypass,
    bypass_mod AS mod_bypass
FROM
    datalake_sorting_hat_raw.`creditanalysis_version`
