SELECT
  id AS id_proposal,
  drive_id AS id_drive,
  end_transaction_id AS id_end_transaction,
  home_city_id AS id_home_city,
  imovel_id AS id_house,
  transaction_id AS id_transaction,
  analyst_name,
  comment,
  home_city,
  home_region,
  home_state,
  home_type,
  home_zipcode,
  operation_type,
  pre_analysis_reason,
  pre_analysis_result,
  reason,
  status,
  supervisor_name,
  condo_value,
  home_area,
  home_bathrooms,
  home_bedrooms,
  home_garages,
  home_insurance_value,
  home_suites,
  iptu_value,
  rent_value,
  bypass_pre_analysis AS has_bypassed_pre_analysis,
  home_exclusive_5A AS is_home_exclusive_5A,
  drive_id_mod AS mod_id_drive,
  home_city_id_mod AS mod_id_home_city,
  imovel_id_mod AS mod_id_house,
  analyst_name_mod AS mod_analyst_name,
  comment_mod AS mod_comment,
  home_city_mod AS mod_home_city,
  home_region_mod AS mod_home_region,
  home_state_mod AS mod_home_state,
  home_type_mod AS mod_home_type,
  home_zipcode_mod AS mod_home_zipcode,
  pre_analysis_reason_mod AS mod_pre_analysis_reason,
  pre_analysis_result_mod AS mod_pre_analysis_result,
  reason_mod AS mod_reason,
  status_mod AS mod_status,
  supervisor_name_mod AS mod_supervisor_name,
  condo_value_mod AS mod_condo_value,
  home_area_mod AS mod_home_area,
  home_bathrooms_mod AS mod_home_bathrooms,
  home_bedrooms_mod AS mod_home_bedrooms,
  home_garages_mod AS mod_home_garages,
  home_insurance_value_mod AS mod_home_insurance_value,
  home_suites_mod AS mod_home_suites,
  iptu_value_mod AS mod_iptu_value,
  rent_value_mod AS mod_rent_value,
  bypass_pre_analysis_mod AS mod_has_bypassed_pre_analysis,
  home_exclusive_5A_mod AS mod_is_home_exclusive_5A,
  analysis_date_mod AS mod_ts_analyzed,
  created_at_mod AS mod_ts_created,
  home_last_published_at_mod AS mod_ts_home_last_published,
  process_date_mod AS mod_ts_precessed,
  updated_at_mod AS mod_ts_updated,
  analysis_date AS ts_analyzed,
  TIMESTAMP(created_at) as ts_created,
  home_last_published_at AS ts_home_last_published,
  process_date AS ts_precessed,
  TIMESTAMP(updated_at) as ts_updated
FROM 
  datalake_sorting_hat_raw.proposal_version