SELECT
  id,
  end_transaction_id AS id_end_transaction,
  proposal_id AS id_proposal,
  screening_result_id AS id_screening_result,
  transaction_id AS id_transaction,
  address,
  address_number,
  bairro,
  cell_phone,
  city,
  complement,
  cpf,
  documentation_analysis,
  email,
  employer_name,
  employer_phone,
  extra_income_origin,
  gender,
  income_nature,
  location_motive,
  marital_status,
  mother_name,
  name,
  nationality,
  occupation_area,
  operation_type,
  phone,
  profession,
  residence_condition,
  second_doc_issuer,
  second_doc_number,
  second_doc_type,
  state,
  zipcode,
  boavista_score,
  extra_income_value,
  monthly_income,
  residence_time,
  serasa_score,
  admission_date AS dt_admitted,
  birthday AS dt_birthday,
  second_doc_issue_date AS dt_second_doc_issued,
  will_reside AS is_going_to_reside,
  address_mod AS mod_address,
  address_number_mod AS mod_address_number,
  admission_date_mod AS mod_admission_date,
  bairro_mod AS mod_bairro,
  birthday_mod AS mod_birthday,
  boavista_score_mod AS mod_boavista_score,
  cell_phone_mod AS mod_cell_phone,
  city_mod AS mod_city,
  complement_mod AS mod_complement,
  cpf_mod AS mod_cpf,
  documentation_analysis_mod AS mod_documentation_analysis,
  email_mod AS mod_email,
  employer_name_mod AS mod_employer_name,
  employer_phone_mod AS mod_employer_phone,
  extra_income_origin_mod AS mod_extra_income_origin,
  extra_income_value_mod AS mod_extra_income_value,
  gender_mod AS mod_gender,
  income_nature_mod AS mod_income_nature,
  location_motive_mod AS mod_location_motive,
  marital_status_mod AS mod_marital_status,
  monthly_income_mod AS mod_monthly_income,
  mother_name_mod AS mod_mother_name,
  name_mod AS mod_name,
  nationality_mod AS mod_nationality,
  occupation_area_mod AS mod_occupation_area,
  phone_mod AS mod_phone,
  profession_mod AS mod_profession,
  proposal_id_mod AS mod_proposal_id,
  residence_condition_mod AS mod_residence_condition,
  residence_time_mod AS mod_residence_time,
  screening_result_id_mod AS mod_screening_result_id,
  second_doc_issue_date_mod AS mod_second_doc_issue_date,
  second_doc_issuer_mod AS mod_second_doc_issuer,
  second_doc_number_mod AS mod_second_doc_number,
  second_doc_type_mod AS mod_second_doc_type,
  serasa_score_mod AS mod_serasa_score,
  state_mod AS mod_state,
  will_reside_mod AS mod_is_going_to_reside,
  zipcode_mod AS mod_zipcode
FROM 
  datalake_sorting_hat_raw.proponent_version