SELECT
  HISSNUM AS id,
  HIACCT AS id_contract,
  HIACCTG AS contract_group,
  HIQUE AS segmentation_queue,
  HIQUE2 AS commission_queue,
  HIQUE3 AS agreement_queue,
  HIQUE4 AS digital_channel_queue,
  HIQUE5 AS eviction_queue,
  HIQUE6 AS credit_denial_queue,
  HILABEL1 AS olos_dialer_label,
  HILABEL2 AS evictions_reason,
  HILABEL3 AS campaign_label,
  HILABEL4 AS serasa_limpa_nome_label,
  HILABEL5 AS evictions_label,
  HILABEL6 AS label_6,
  HIDAYS AS days_delayed,
  HICURBAL AS outstanding_balance,
  HIAMTDLQ AS total_delayed_amount,
  HIANO AS partition_year,
  HIDLQDT AS dt_due_date,
  DATE(HIQCHGDT) AS dt_segmentation_queue_update,
  DATE(HIQCHGDT2) AS dt_commission_queue_update,
  DATE(HIQCHGDT3) AS dt_agreement_queue_update,
  DATE(HIQCHGDT4) AS dt_digital_channel_queue_update,
  DATE(HIQCHGDT5) AS dt_eviction_queue_update,
  DATE(HIQCHGDT6) AS dt_credit_denial_queue_update,
  DATE(HILCHGDT1) AS dt_olos_dialer_label_update,
  DATE(HILCHGDT2) AS dt_evictions_reason_update,
  DATE(HILCHGDT3) AS dt_campaign_label_update,
  DATE(HILCHGDT4) AS dt_serasa_limpa_nome_label_update,
  DATE(HILCHGDT5) AS dt_evictions_label_update,
  DATE(HILCHGDT6) AS dt_not_collection_label_update,
  HIREGISTRO AS ts_record_insertion,
  year,
  month,
  day,
  NOW() AS ts_load
FROM datalake_cyber_raw.tb_historico_arvore
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
