SELECT
    sk_contract,
    id_contract,
    country_code,
    rent,
    first_rent_charged,
    day_month_due,
    guarantee,
    type,
    status,
    rental_administrator,
    condo_payer,
    condo_responsible,
    iptu_payer,
    iptu_responsible,
    rental_insurance_installments,
    rental_insurance_value,
    home_insurance_installments,
    home_insurance_value,
    first_rental_commission,
    monthly_administration_fee,
    condo,
    iptu,
    CAST(tenant_service_fee AS DECIMAL(5,3)) AS tenant_service_fee,
    agent_brokerage_share,
    signature_type,
    closing_status,
    cancellation_reason,
    version,
    is_b2b,
    is_contract_b2b,
    contract_partner_type,
    b2b_type,
    b2b_prime_type,
    contract_plan,
    administration_split_percentage,
    brokerage_split_percentage,
    is_ongoing_contract,
    is_tenant_service_fee_opt_out,
    is_exit_inspection_opted_out,
    dt_start,
    dt_entrance,
    dt_intended_end,
    dt_annulment,
    ts_created,
    ts_updated,
    ts_expected_termination,
    ts_signature,
    ts_draft_approved,
    ts_canceled,
    ts_tenant_service_fee_opt_out,
    ts_analyst_annulment_input,
    ts_load AS ts_snapshot,
    YEAR(ts_load) AS year,
    MONTH(ts_load) AS month,
    DAY(ts_load) AS day
FROM
    dw_public.dim_contract
WHERE
    ts_load IS NOT NULL
