SELECT
    origin_table,
    sk_propose,
    sk_propose_20,
    sk_transaction,
    sk_key,
    client_cpf_cnpj,
    dt_register,
    dt_due,
    dt_paid,
    dias_atraso,
    due_amount,
    paid_amount,
    open_amount,
    discount_value,
    bill_item,
    provisional_group,
    is_danos_imovel,
    is_contract_active,
    dt_contract_started,
    dt_contract_ended,
    valor_pacote,
    is_delinquency_renovacao,
    is_perdao_divida,
    NOW() AS ts_snapshot,
    YEAR(CURRENT_DATE()) AS year,
    MONTH(CURRENT_DATE()) AS month,
    DAY(CURRENT_DATE()) AS day
FROM
    dw_velo.quintocred_ifrs_recurring_payment
