SELECT 
    id, 
    imobiliaria_id AS id_real_estate_agency, 
    condominio_id AS id_condo, 
    codigo_quintoandar AS id_house_quintoandar, 
    chave_id AS id_key, 
    bairro_id AS id_neighborhood,
    status_id AS id_status, 
    tipo_id AS id_type, 
    logradouro AS address, 
    banco AS bank, 
    cobertura_tipo AS coverage_type,
    galpao_telhado AS hangar_roof,
    galpao_estrutura AS hangar_structure, 
    lote_geometria AS lot_geometry, 
    lote_inclinacao AS lot_inclination, 
    lote_zoneamento AS lot_zoning,
    imobiliaria_indicacao AS partner_indication, 
    loja_posicao AS store_position,
    posicao AS sun_position, 
    video_url AS video_url, 
    visita_forma AS visit_type,  
    cep AS zip_code,
    CAST(banheiros AS SMALLINT) AS bathrooms, 
    CAST(quartos AS SMALLINT) AS bedrooms,
    CAST(comissao AS FLOAT) AS brokerage, 
    CAST(comissao_bonus AS FLOAT) AS brokerage_bonus,
    CAST(numero_andares AS SMALLINT) AS building_floors, 
    CAST(valor_condominio AS FLOAT) AS condo_price,
    CAST(preco_avaliacao AS FLOAT) AS evaluation_price,
    CAST(valor_iptu AS FLOAT) AS iptu_price, 
    CAST(preco_modelo AS FLOAT) AS predicted_price,
    CAST(preco AS FLOAT) AS price, 
    CAST(valor_saldo_devedor AS FLOAT) AS debit_balance_value, 
    CAST(ano_construcao AS SMALLINT) AS construction_year, 
    CAST(vagas_cobertas AS SMALLINT) AS covered_parking_slots, 
    CAST(elevadores AS SMALLINT) AS elevators,
    CAST(andar AS SMALLINT) AS floor, 
    CAST(unidade_andar AS SMALLINT) AS floor_unities,
    CAST(galpao_pe_direito AS FLOAT) AS hangar_ceiling_height,
    CAST(galpao_frente AS FLOAT) AS hangar_front,
    CAST(galpao_lateral AS FLOAT) AS hangar_lateral, 
    CAST(casa_andares AS SMALLINT) AS house_floors, 
    CAST(qualidade_imagens AS FLOAT) AS images_quality,
    CAST(latitude AS FLOAT) AS lat, 
    CAST(longitude AS FLOAT) as lng, 
    CAST(vagas_linha AS SMALLINT) AS line_parking_slots, 
    CAST(liquidez AS FLOAT) AS liquidity,
    CAST(liquidez_inferior AS FLOAT) AS inferior_liquidity,
    CAST(liquidez_superior AS FLOAT) AS superior_liquidity, 
    CAST(salas AS SMALLINT) AS living_rooms, 
    CAST(lote_area AS FLOAT) AS lot_area, 
    CAST(lote_frente AS FLOAT) AS lot_front,  
    CAST(lote_lateral AS FLOAT) AS lot_lateral, 
    CAST(loja_sobreloja_area AS FLOAT) AS mezzanine_store_area, 
    CAST(vagas_livres AS SMALLINT) AS open_parking_slots, 
    CAST(vagas AS SMALLINT) AS parking_slots, 
    CAST(quantidade_area_privativa AS FLOAT) AS private_area,  
    CAST(cobertura_area_construida AS FLOAT) AS roof_building_area,
    CAST(cobertura_area_terraco AS FLOAT) AS roof_terrace_area, 
    CAST(semissuites AS SMALLINT) AS semi_suites, 
    CAST(loja_pe_direito AS FLOAT) AS store_ceiling_height,
    CAST(loja_sobreloja AS SMALLINT) AS store_mezzanine,
    CAST(suites AS SMALLINT) AS suites,  
    CAST(lavabos AS SMALLINT) AS toilets, 
    CAST(area AS FLOAT) AS total_area,
    CAST(cobertura_piscina AS BOOLEAN) AS has_roof_pool, 
    CAST(cobertura_sauna AS BOOLEAN) AS has_roof_sauna, 
    CAST(cobertura_churrasqueira AS BOOLEAN) AS has_roof_grill,
    CAST(cobertura_ducha AS BOOLEAN) AS has_roof_douche,
    CAST(cobertura_ofuro AS BOOLEAN) AS has_roof_ofuro, 
    CAST(cobertura_espaco_gourmet AS BOOLEAN) AS has_roof_gourmet_area, 
    CAST(casa_geminada_entrada AS BOOLEAN) AS is_house_entrance_semi_detached,
    CAST(aceita_permuta AS BOOLEAN) AS is_permute_accepted,
    CAST(publicar_portais AS BOOLEAN) AS is_portal_published,
    CAST(fotos_profissionais AS BOOLEAN) AS is_profissional_photos, 
    CAST(lote_murado AS BOOLEAN) AS is_walled_lot,
    CAST(obra_entregue_em AS TIMESTAMP) AS ts_construction_ended,
    CAST(criado_em AS TIMESTAMP) AS ts_created,
    CAST(deletado_em AS TIMESTAMP) AS ts_deleted,
    CAST(desativado_em AS TIMESTAMP) AS ts_disabled,
    CAST(publicacao_solicitada_em AS TIMESTAMP) AS ts_publication_requested, 
    CAST(publicado_em AS TIMESTAMP) AS ts_published,
    CAST(republicado_em AS TIMESTAMP) AS ts_republished,
    CAST(atualizado_em AS TIMESTAMP) AS ts_updated
FROM 
    datalake_casa_mineira_crm_raw.imovel 