SELECT
    id_agent AS sk_agent,
    id_agent_data AS sk_agent_data,
    id_partner AS sk_partner,
    id_user AS sk_user,
    uuid_company,
    uuid_agent,
    uuid_person,
    creci,
    creci_uf,
    affiliation_type,
    status,
    company_product_name,
    profile,
    is_reactivated,
    is_allow_supply_acquisition,
    is_allow_demand_acquisition,
    is_allow_visit,
    is_allow_demand_sale,
    is_allow_demand_rent,
    is_passive_lead_receiver,
    is_1p_partnership,
    is_3p_partnership,
    days_in_current_status,
    ts_last_status_changed,
    ts_created,
    ts_updated
FROM
    datalake_agent_accreditation.agent
