SELECT
    amplitude_id AS id_amplitude,
    amplitude_attribution_ids AS ids_amplitude_attributed,
    adid,
    amplitude_event_type,
    app AS id_app,
    city,
    timestamp(client_event_time) AS ts_client_event,
    timestamp(client_upload_time) AS ts_client_uploaded,
    country,
    data,
    timestamp(server_received_time) AS ts_server_received,
    device_brand,
    device_carrier,
    device_family,
    device_id AS id_device,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_id AS id_event,
    timestamp(event_time) AS ts_event,
    event_type,
    event_properties,
    boolean(is_attribution_event) AS is_attribution_event,
    idfa,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    boolean(paying) AS is_paying,
    region,
    timestamp(server_upload_time) AS ts_server_uploaded,
    session_id AS id_session,
    start_version,
    timestamp(user_creation_time) AS ts_user_created,
    user_id AS id_user,
    user_properties,
    language,
    uuid,
    version_name,
    schema AS id_schema,
    timestamp(processed_time) AS ts_processed,
    insert_id AS id_inserted,
    sample_rate,
    year,
    month,
    day
FROM
    datalake_amplitude_raw.events
WHERE
    year = {year} and month = {month} and day = {day}
