SELECT
  rev,
  revtstmp,
  DATE(TO_TIMESTAMP(CAST(revtstmp/1000 AS BIGINT))) AS dt,
  CAST(EXTRACT(YEAR FROM DATE(TO_TIMESTAMP(CAST(revtstmp/1000 AS BIGINT)))) AS INT) AS year,
  CAST(EXTRACT(MONTH FROM DATE(TO_TIMESTAMP(CAST(revtstmp/1000 AS BIGINT)))) AS INT) AS month,
  CAST(EXTRACT(DAY FROM DATE(TO_TIMESTAMP(CAST(revtstmp/1000 AS BIGINT)))) AS INT) AS day
FROM
  revinfo
WHERE
  DATE(TO_TIMESTAMP(CAST(revtstmp/1000 AS BIGINT))) >= DATE(DATE('{execution_date}') - INTERVAL '6 day')
  AND DATE(TO_TIMESTAMP(CAST(revtstmp/1000 AS BIGINT))) < DATE(DATE('{execution_date}') + INTERVAL '1 day')
