SELECT
    sk_company,
    id_hubspot,
    COALESCE(name, 'Unknown') AS company_name,
    COALESCE(tag_real_estate_agency, 'Unknown') AS tag,
    COALESCE(extracted_3p_tag, 'Unknown') AS extracted_3p_tag,
    COALESCE(lead_status, 'Unknown') AS lead_status,
    COALESCE(address, 'Unknown') AS address,
    COALESCE(zip_code, 'Unknown') AS zip_code,
    COALESCE(TRIM(UPPER(city)), 'Unknown') AS city,
    COALESCE(state, 'Unknown') AS state,
    COALESCE(country, 'Unknown') AS country,
    COALESCE(domain, 'Unknown') AS domain,
    COALESCE(e_mail, 'Unknown') AS e_mail,
    COALESCE(phone, 'Unknown') AS phone,
    COALESCE(industry, 'Unknown') AS industry,
    COALESCE(life_cycle_stage, 'Unknown') AS life_cycle_stage,
    COALESCE(mkt_campain, 'Unknown') AS mkt_campaign,
    COALESCE(mkt_channel, 'Unknown') AS mkt_channel,
    COALESCE(mkt_content, 'Unknown') AS mkt_content,
    COALESCE(mkt_medium, 'Unknown') AS mkt_medium,
    COALESCE(mkt_origin, 'Unknown') AS mkt_origin,
    COALESCE(mkt_source, 'Unknown') AS mkt_source,
    COALESCE(unified_discard_reasons, 'Unknown') AS discard_reason,
    COALESCE(lead_origin, 'Unknown') AS lead_origin,
    COALESCE(partnership_type, 'Unknown') AS partnership_type,
    COALESCE(first_conversion_event_name, 'Unknown') AS first_conversion_event_name,
    COALESCE(crm, 'Unknown') AS crm,
    COALESCE(real_estate_agency_focus, 'Unknown') AS real_estate_agency_focus,
    COALESCE(cnpj, 'Unknown') AS cnpj,
    COALESCE(creci, 'Unknown') AS creci,
    CASE
        WHEN is_juridical_person THEN 'PJ'
        WHEN is_natural_person THEN 'PF'
        ELSE 'Unknown'
    END AS person_type,
    num_associated_deals,
    num_associated_contacts,
    monthly_average_new_rental_contracts,
    num_managers,
    num_managed_properties,
    num_monthly_leads,
    average_sale_property_ticket,
    average_rent_property_ticket,
    monthly_repayment_volume_in_real,
    monthly_sale_volume_in_real,
    num_real_estate_agents,
    num_properties_for_sale,
    num_properties_for_rent,
    has_property_advertisement_online,
    is_correspondent_bank,
    is_lost,
    has_financing,
    is_for_sale,
    is_for_rent,
    has_partnerships_with_other_agencies,
    ts_first_conversion,
    ts_recent_deal_close,
    ts_hubspot_owner_assigned,
    ts_last_logged_call,
    ts_notes_last_updated,
    ts_created,
    ts_updated,
    NOW() AS ts_load
FROM
    datalake_hubspot.company AS c
JOIN
    datalake_rede_company.company_sks AS cs
        ON c.id_company = cs.id_hubspot