SELECT
    id,
    externalReference AS id_external_reference,
    cpfCnpj AS document,
    name,
    email,
    additionalEmails AS additional_emails,
    company,
    phone,
    mobilePhone AS mobile_phone,
    address,
    addressNumber AS address_number,
    complement AS address_complement,
    province AS address_provice,
    postalCode AS address_postalcode,
    city AS address_city,
    state AS address_state,
    country AS address_country,
    personType AS person_type,
    observations,
    municipalInscription AS municipal_inscription,
    stateInscription AS state_inscription,
    IF(notificationDisabled='True',TRUE, FALSE) AS is_notification_disabled,
    IF(deleted='True',TRUE, FALSE) AS is_deleted,
    IF(canDelete='True',TRUE, FALSE) AS can_delete,
    IF(canEdit='True',TRUE, FALSE) AS can_edit,
    TO_DATE(dateCreated, 'yyyy-MM-dd') AS dt_created
FROM
    datalake_velo_asaas_raw.customers
