SELECT
    id,
    customer AS id_customer,
    subscription AS id_subscription,
    externalReference AS id_external_reference,
    paymentLink AS payment_link,
    description,
    billingType AS billint_type,
    pixTransaction AS pix_transaction,
    status,
    installmentNumber AS installment_number,
    invoiceUrl AS invoice_url,
    invoiceNumber AS invoice_number,
    transactionReceiptUrl AS transaction_receipt_url,
    nossoNumero AS our_number,
    bankSlipUrl AS bank_slip_url,
    discount_type,
    fine_type,
    interest_type,
    custody,
    refunds,
    CAST(discount_value AS DOUBLE) AS discount_value,
    CAST(fine_value AS DOUBLE) AS fine_value,
    CAST(value AS DOUBLE) AS value,
    CAST(netValue AS DOUBLE) AS net_value,
    CAST(originalValue AS DOUBLE) AS original_value,
    CAST(interestValue AS DOUBLE) AS interest_value,
    CAST(discount_dueDateLimitDays AS INTEGER) AS discout_limit_days_dt_due,
    pixQrCodeId AS pix_qrcode,
    creditCard_creditCardBrand AS credit_card_brand,
    IF(canBePaidAfterDueDate='True',TRUE, FALSE) AS can_be_paid_after_due,
    IF(postalService='True',TRUE, FALSE) AS has_postal_service,
    IF(deleted='True',TRUE, FALSE) AS is_deleted,
    IF(anticipated='True',TRUE, FALSE) AS is_anticipated,
    IF(anticipable='True',TRUE, FALSE) AS is_anticiplable,
    TO_DATE(discount_limitDate, 'yyyy-MM-dd') AS dt_discount_limit,
    TO_DATE(confirmedDate, 'yyyy-MM-dd') AS dt_confirmed,
    TO_DATE(dueDate, 'yyyy-MM-dd') AS dt_due,
    TO_DATE(originalDueDate, 'yyyy-MM-dd') AS dt_original_due,
    TO_DATE(paymentDate, 'yyyy-MM-dd') AS dt_payment,
    TO_DATE(clientPaymentDate, 'yyyy-MM-dd') AS dt_client_payment,
    TO_DATE(creditDate, 'yyyy-MM-dd') AS dt_credit,
    TO_DATE(estimatedCreditDate, 'yyyy-MM-dd') AS dt_estimated_credit,
    TO_DATE(dateCreated, 'yyyy-MM-dd') AS dt_created,
    TO_TIMESTAMP(lastInvoiceViewedDate) AS ts_invoice_last_viewed,
    TO_TIMESTAMP(lastBankSlipViewedDate) AS ts_bank_slip_last_viewed
FROM
    datalake_velo_asaas_raw.payments
