CREATE OR REPLACE VIEW datalake_amplitude_clean_prod.visit_intent_clicked_events AS
SELECT
    server_received_time,
    app,
    device_carrier,
    schema,
    city,
    user_id,
    uuid,
    event_time,
    platform,
    os_version,
    amplitude_id,
    processed_time,
    user_creation_time,
    version_name,
    ip_address,
    paying,
    dma,
    client_upload_time,
    insert_id,
    library,
    amplitude_attribution_ids,
    device_type,
    device_manufacturer,
    start_version,
    location_lng,
    server_upload_time,
    event_id,
    location_lat,
    os_name,
    amplitude_event_type,
    device_brand,
    data,
    device_id,
    language,
    device_model,
    country,
    region,
    is_attribution_event,
    adid,
    session_id,
    device_family,
    sample_rate,
    idfa,
    client_event_time,
    year,
    month,
    day,
    event_type,
    json_extract_scalar(user_properties, '$["AB_SCHEDULING_SUGGESTION"]') as user__a_b__s_c_h_e_d_u_l_i_n_g__s_u_g_g_e_s_t_i_o_n,
    json_extract_scalar(user_properties, '$["HouseCardSize"]') as user__house_card_size,
    json_extract_scalar(user_properties, '$["Location_enabled"]') as user__location_enabled,
    json_extract_scalar(user_properties, '$["Total_booked_visits"]') as user__total_booked_visits,
    json_extract_scalar(user_properties, '$["Total_booking_clicks"]') as user__total_booking_clicks,
    json_extract_scalar(user_properties, '$["Total_cancelled_visits"]') as user__total_cancelled_visits,
    json_extract_scalar(user_properties, '$["Total_confirmed_visits"]') as user__total_confirmed_visits,
    json_extract_scalar(user_properties, '$["Total_map_price_flag_clicks"]') as user__total_map_price_flag_clicks,
    json_extract_scalar(user_properties, '$["Total_rescheduled_visits"]') as user__total_rescheduled_visits,
    json_extract_scalar(user_properties, '$["Total_viewed_listings"]') as user__total_viewed_listings,
    json_extract_scalar(user_properties, '$["aa_firstFold_landing"]') as user_aa_first_fold_landing,
    json_extract_scalar(user_properties, '$["aa_hurry_up"]') as user_aa_hurry_up,
    json_extract_scalar(user_properties, '$["aa_landing_page"]') as user_aa_landing_page,
    json_extract_scalar(user_properties, '$["aa_new_card"]') as user_aa_new_card,
    json_extract_scalar(user_properties, '$["aa_new_house_card"]') as user_aa_new_house_card,
    json_extract_scalar(user_properties, '$["ab-originals-all-or-nothing"]') as user_aboriginalsallornothing,
    json_extract_scalar(user_properties, '$["ab_100_test"]') as user_ab_100_test,
    json_extract_scalar(user_properties, '$["ab_30_test"]') as user_ab_30_test,
    json_extract_scalar(user_properties, '$["ab_announce_cta"]') as user_ab_announce_cta,
    json_extract_scalar(user_properties, '$["ab_announce_cta_owners"]') as user_ab_announce_cta_owners,
    json_extract_scalar(user_properties, '$["ab_announce_owners_cta"]') as user_ab_announce_owners_cta,
    json_extract_scalar(user_properties, '$["ab_appbar_color"]') as user_ab_appbar_color,
    json_extract_scalar(user_properties, '$["ab_booked_plus_similar"]') as user_ab_booked_plus_similar,
    json_extract_scalar(user_properties, '$["ab_booking_pressure"]') as user_ab_booking_pressure,
    json_extract_scalar(user_properties, '$["ab_bookinginfo"]') as user_ab_bookinginfo,
    json_extract_scalar(user_properties, '$["ab_card_booking"]') as user_ab_card_booking,
    json_extract_scalar(user_properties, '$["ab_carousel_landing_page"]') as user_ab_carousel_landing_page,
    json_extract_scalar(user_properties, '$["ab_checkin"]') as user_ab_checkin,
    json_extract_scalar(user_properties, '$["ab_confirmation_schedule"]') as user_ab_confirmation_schedule,
    json_extract_scalar(user_properties, '$["ab_contextual_search"]') as user_ab_contextual_search,
    json_extract_scalar(user_properties, '$["ab_cp_pressure"]') as user_ab_cp_pressure,
    json_extract_scalar(user_properties, '$["ab_credit_simulation_box"]') as user_ab_credit_simulation_box,
    json_extract_scalar(user_properties, '$["ab_draft_inversion"]') as user_ab_draft_inversion,
    json_extract_scalar(user_properties, '$["ab_draftinversion"]') as user_ab_draftinversion,
    json_extract_scalar(user_properties, '$["ab_enhanced_mk"]') as user_ab_enhanced_mk,
    json_extract_scalar(user_properties, '$["ab_enhanced_tags"]') as user_ab_enhanced_tags,
    json_extract_scalar(user_properties, '$["ab_exposed_filters"]') as user_ab_exposed_filters,
    json_extract_scalar(user_properties, '$["ab_favorite_carousel_animation"]') as user_ab_favorite_carousel_animation,
    json_extract_scalar(user_properties, '$["ab_favorite_listing_animation"]') as user_ab_favorite_listing_animation,
    json_extract_scalar(user_properties, '$["ab_favorite_listing_button_type"]') as user_ab_favorite_listing_button_type,
    json_extract_scalar(user_properties, '$["ab_favorite_listing_tooltip"]') as user_ab_favorite_listing_tooltip,
    json_extract_scalar(user_properties, '$["ab_featured_filters_price"]') as user_ab_featured_filters_price,
    json_extract_scalar(user_properties, '$["ab_filter_leak"]') as user_ab_filter_leak,
    json_extract_scalar(user_properties, '$["ab_filters_bedroom"]') as user_ab_filters_bedroom,
    json_extract_scalar(user_properties, '$["ab_girafa"]') as user_ab_girafa,
    json_extract_scalar(user_properties, '$["ab_girafa_switch"]') as user_ab_girafa_switch,
    json_extract_scalar(user_properties, '$["ab_homes_carousel"]') as user_ab_homes_carousel,
    json_extract_scalar(user_properties, '$["ab_homes_filter_tooltip"]') as user_ab_homes_filter_tooltip,
    json_extract_scalar(user_properties, '$["ab_homes_labelmobile"]') as user_ab_homes_labelmobile,
    json_extract_scalar(user_properties, '$["ab_homes_text"]') as user_ab_homes_text,
    json_extract_scalar(user_properties, '$["ab_house_card_size"]') as user_ab_house_card_size,
    json_extract_scalar(user_properties, '$["ab_hurry_up"]') as user_ab_hurry_up,
    json_extract_scalar(user_properties, '$["ab_hurryup_schedule"]') as user_ab_hurryup_schedule,
    json_extract_scalar(user_properties, '$["ab_instant_booking"]') as user_ab_instant_booking,
    json_extract_scalar(user_properties, '$["ab_intersection_observer"]') as user_ab_intersection_observer,
    json_extract_scalar(user_properties, '$["ab_intersection_observer_new"]') as user_ab_intersection_observer_new,
    json_extract_scalar(user_properties, '$["ab_intro_second_fold_3"]') as user_ab_intro_second_fold_3,
    json_extract_scalar(user_properties, '$["ab_landing_first_fold"]') as user_ab_landing_first_fold,
    json_extract_scalar(user_properties, '$["ab_landing_form"]') as user_ab_landing_form,
    json_extract_scalar(user_properties, '$["ab_landing_intercom"]') as user_ab_landing_intercom,
    json_extract_scalar(user_properties, '$["ab_landing_lean_form"]') as user_ab_landing_lean_form,
    json_extract_scalar(user_properties, '$["ab_listing_homes"]') as user_ab_listing_homes,
    json_extract_scalar(user_properties, '$["ab_listing_pois"]') as user_ab_listing_pois,
    json_extract_scalar(user_properties, '$["ab_listing_share"]') as user_ab_listing_share,
    json_extract_scalar(user_properties, '$["ab_listing_videodialog"]') as user_ab_listing_videodialog,
    json_extract_scalar(user_properties, '$["ab_listing_videodialog2"]') as user_ab_listing_videodialog2,
    json_extract_scalar(user_properties, '$["ab_login_displaymode"]') as user_ab_login_displaymode,
    json_extract_scalar(user_properties, '$["ab_map_button_title"]') as user_ab_map_button_title,
    json_extract_scalar(user_properties, '$["ab_map_homes_button_animation"]') as user_ab_map_homes_button_animation,
    json_extract_scalar(user_properties, '$["ab_map_list_mode"]') as user_ab_map_list_mode,
    json_extract_scalar(user_properties, '$["ab_mk_layout"]') as user_ab_mk_layout,
    json_extract_scalar(user_properties, '$["ab_mobile_infinite_scroll"]') as user_ab_mobile_infinite_scroll,
    json_extract_scalar(user_properties, '$["ab_new_card"]') as user_ab_new_card,
    json_extract_scalar(user_properties, '$["ab_new_house_card"]') as user_ab_new_house_card,
    json_extract_scalar(user_properties, '$["ab_new_house_card_v2"]') as user_ab_new_house_card_v2,
    json_extract_scalar(user_properties, '$["ab_originals_all_or_nothing"]') as user_ab_originals_all_or_nothing,
    json_extract_scalar(user_properties, '$["ab_originals_cards"]') as user_ab_originals_cards,
    json_extract_scalar(user_properties, '$["ab_originals_filter"]') as user_ab_originals_filter,
    json_extract_scalar(user_properties, '$["ab_originals_landing_carousel"]') as user_ab_originals_landing_carousel,
    json_extract_scalar(user_properties, '$["ab_originals_ready_listing"]') as user_ab_originals_ready_listing,
    json_extract_scalar(user_properties, '$["ab_originals_stories"]') as user_ab_originals_stories,
    json_extract_scalar(user_properties, '$["ab_pclick_online"]') as user_ab_pclick_online,
    json_extract_scalar(user_properties, '$["ab_pclick_v01"]') as user_ab_pclick_v01,
    json_extract_scalar(user_properties, '$["ab_photosphere"]') as user_ab_photosphere,
    json_extract_scalar(user_properties, '$["ab_premature_login"]') as user_ab_premature_login,
    json_extract_scalar(user_properties, '$["ab_prevent_housecard_show_photos"]') as user_ab_prevent_housecard_show_photos,
    json_extract_scalar(user_properties, '$["ab_price_filter_expansion_checkbox"]') as user_ab_price_filter_expansion_checkbox,
    json_extract_scalar(user_properties, '$["ab_publicationdate"]') as user_ab_publicationdate,
    json_extract_scalar(user_properties, '$["ab_relisting"]') as user_ab_relisting,
    json_extract_scalar(user_properties, '$["ab_results_counter"]') as user_ab_results_counter,
    json_extract_scalar(user_properties, '$["ab_save_filters"]') as user_ab_save_filters,
    json_extract_scalar(user_properties, '$["ab_schedule_button"]') as user_ab_schedule_button,
    json_extract_scalar(user_properties, '$["ab_schedule_call"]') as user_ab_schedule_call,
    json_extract_scalar(user_properties, '$["ab_schedule_label"]') as user_ab_schedule_label,
    json_extract_scalar(user_properties, '$["ab_scheduling_suggestion"]') as user_ab_scheduling_suggestion,
    json_extract_scalar(user_properties, '$["ab_search_rank"]') as user_ab_search_rank,
    json_extract_scalar(user_properties, '$["ab_search_ranking"]') as user_ab_search_ranking,
    json_extract_scalar(user_properties, '$["ab_second_step_scheduling"]') as user_ab_second_step_scheduling,
    json_extract_scalar(user_properties, '$["ab_similar_houses"]') as user_ab_similar_houses,
    json_extract_scalar(user_properties, '$["ab_similarity_carousel"]') as user_ab_similarity_carousel,
    json_extract_scalar(user_properties, '$["ab_supported_neighborhoods_form"]') as user_ab_supported_neighborhoods_form,
    json_extract_scalar(user_properties, '$["ab_supported_regions_empty_search"]') as user_ab_supported_regions_empty_search,
    json_extract_scalar(user_properties, '$["ab_test"]') as user_ab_test,
    json_extract_scalar(user_properties, '$["ab_testing_photos"]') as user_ab_testing_photos,
    json_extract_scalar(user_properties, '$["ab_trending_carousel"]') as user_ab_trending_carousel,
    json_extract_scalar(user_properties, '$["ab_two_steps_scheduling"]') as user_ab_two_steps_scheduling,
    json_extract_scalar(user_properties, '$["ab_unbounce_pwa"]') as user_ab_unbounce_pwa,
    json_extract_scalar(user_properties, '$["ab_user_documents_required"]') as user_ab_user_documents_required,
    json_extract_scalar(user_properties, '$["ab_value_proposition"]') as user_ab_value_proposition,
    json_extract_scalar(user_properties, '$["ab_visit_button_color"]') as user_ab_visit_button_color,
    json_extract_scalar(user_properties, '$["ab_wafflemenu_button"]') as user_ab_wafflemenu_button,
    json_extract_scalar(user_properties, '$["abc_100_test"]') as user_abc_100_test,
    json_extract_scalar(user_properties, '$["abc_search_ranking"]') as user_abc_search_ranking,
    json_extract_scalar(user_properties, '$["accessibility_enabled"]') as user_accessibility_enabled,
    json_extract_scalar(user_properties, '$["chat_onboarding"]') as user_chat_onboarding,
    json_extract_scalar(user_properties, '$["email"]') as user_email,
    json_extract_scalar(user_properties, '$["entrance_uri"]') as user_entrance_uri,
    json_extract_scalar(user_properties, '$["favorite_new_layout"]') as user_favorite_new_layout,
    json_extract_scalar(user_properties, '$["gclid"]') as user_gclid,
    json_extract_scalar(user_properties, '$["grandpaUserId"]') as user_grandpa_user_id,
    json_extract_scalar(user_properties, '$["initial_entrance_uri"]') as user_initial_entrance_uri,
    json_extract_scalar(user_properties, '$["initial_gclid"]') as user_initial_gclid,
    json_extract_scalar(user_properties, '$["initial_referrer"]') as user_initial_referrer,
    json_extract_scalar(user_properties, '$["initial_referring_domain"]') as user_initial_referring_domain,
    json_extract_scalar(user_properties, '$["initial_utm_campaign"]') as user_initial_utm_campaign,
    json_extract_scalar(user_properties, '$["initial_utm_content"]') as user_initial_utm_content,
    json_extract_scalar(user_properties, '$["initial_utm_medium"]') as user_initial_utm_medium,
    json_extract_scalar(user_properties, '$["initial_utm_source"]') as user_initial_utm_source,
    json_extract_scalar(user_properties, '$["initial_utm_term"]') as user_initial_utm_term,
    json_extract_scalar(user_properties, '$["inspectiondocs_button_clicked"]') as user_inspectiondocs_button_clicked,
    json_extract_scalar(user_properties, '$["last_utm_campaign"]') as user_last_utm_campaign,
    json_extract_scalar(user_properties, '$["last_utm_content"]') as user_last_utm_content,
    json_extract_scalar(user_properties, '$["last_utm_medium"]') as user_last_utm_medium,
    json_extract_scalar(user_properties, '$["last_utm_source"]') as user_last_utm_source,
    json_extract_scalar(user_properties, '$["last_utm_term"]') as user_last_utm_term,
    json_extract_scalar(user_properties, '$["leadFormOnHomePageExperiment"]') as user_lead_form_on_home_page_experiment,
    json_extract_scalar(user_properties, '$["lead_firestore_id"]') as user_lead_firestore_id,
    json_extract_scalar(user_properties, '$["login_status"]') as user_login_status,
    json_extract_scalar(user_properties, '$["nbr-listings-viewed"]') as user_nbrlistingsviewed,
    json_extract_scalar(user_properties, '$["nbr-searches-concluded"]') as user_nbrsearchesconcluded,
    json_extract_scalar(user_properties, '$["nbr_homes_subscribed"]') as user_nbr_homes_subscribed,
    json_extract_scalar(user_properties, '$["nbr_initial_offers_submitted"]') as user_nbr_initial_offers_submitted,
    json_extract_scalar(user_properties, '$["nbr_listings_favorited"]') as user_nbr_listings_favorited,
    json_extract_scalar(user_properties, '$["nbr_listings_viewed"]') as user_nbr_listings_viewed,
    json_extract_scalar(user_properties, '$["nbr_onboarding_screens_viewed"]') as user_nbr_onboarding_screens_viewed,
    json_extract_scalar(user_properties, '$["nbr_photos_viewed"]') as user_nbr_photos_viewed,
    json_extract_scalar(user_properties, '$["nbr_photospheres_preview_viewed"]') as user_nbr_photospheres_preview_viewed,
    json_extract_scalar(user_properties, '$["nbr_photospheres_viewed"]') as user_nbr_photospheres_viewed,
    json_extract_scalar(user_properties, '$["nbr_searches_concluded"]') as user_nbr_searches_concluded,
    json_extract_scalar(user_properties, '$["nbr_visits_scheduled"]') as user_nbr_visits_scheduled,
    json_extract_scalar(user_properties, '$["originals"]') as user_originals,
    json_extract_scalar(user_properties, '$["phased_rollout_checkin"]') as user_phased_rollout_checkin,
    json_extract_scalar(user_properties, '$["phasedrollout_test"]') as user_phasedrollout_test,
    json_extract_scalar(user_properties, '$["places_token_autocomplete"]') as user_places_token_autocomplete,
    json_extract_scalar(user_properties, '$["platform"]') as user_platform,
    json_extract_scalar(user_properties, '$["property"]') as user_property,
    json_extract_scalar(user_properties, '$["referrer"]') as user_referrer,
    json_extract_scalar(user_properties, '$["referring_domain"]') as user_referring_domain,
    json_extract_scalar(user_properties, '$["reservation"]') as user_reservation,
    json_extract_scalar(user_properties, '$["similar_props_carousel"]') as user_similar_props_carousel,
    json_extract_scalar(user_properties, '$["swizzling"]') as user_swizzling,
    json_extract_scalar(user_properties, '$["task_expansion_clicked"]') as user_task_expansion_clicked,
    json_extract_scalar(user_properties, '$["twabrowserpackage"]') as user_twabrowserpackage,
    json_extract_scalar(user_properties, '$["twabrowserversioncode"]') as user_twabrowserversioncode,
    json_extract_scalar(user_properties, '$["twabrowserversionname"]') as user_twabrowserversionname,
    json_extract_scalar(user_properties, '$["twaversion"]') as user_twaversion,
    json_extract_scalar(user_properties, '$["upload_page_viewed"]') as user_upload_page_viewed,
    json_extract_scalar(user_properties, '$["user_email"]') as user_user_email,
    json_extract_scalar(user_properties, '$["user_id"]') as user_user_id,
    json_extract_scalar(user_properties, '$["utm_campaign"]') as user_utm_campaign,
    json_extract_scalar(user_properties, '$["utm_content"]') as user_utm_content,
    json_extract_scalar(user_properties, '$["utm_medium"]') as user_utm_medium,
    json_extract_scalar(user_properties, '$["utm_source"]') as user_utm_source,
    json_extract_scalar(user_properties, '$["utm_term"]') as user_utm_term,
    json_extract_scalar(user_properties, '$["webPushToken"]') as user_web_push_token,
    json_extract_scalar(user_properties, '$["web_mobile_mode"]') as user_web_mobile_mode,
    json_extract_scalar(event_properties, '$["accepts_pets"]') as event_accepts_pets,
    json_extract_scalar(event_properties, '$["adj_city"]') as event_adj_city,
    json_extract_scalar(event_properties, '$["adj_macro_region"]') as event_adj_macro_region,
    json_extract_scalar(event_properties, '$["adj_sub_region"]') as event_adj_sub_region,
    json_extract_scalar(event_properties, '$["apartment_id"]') as event_apartment_id,
    json_extract_scalar(event_properties, '$["business_context"]') as event_business_context,
    json_extract_scalar(event_properties, '$["city"]') as event_city,
    json_extract_scalar(event_properties, '$["country"]') as event_country,
    json_extract_scalar(event_properties, '$["current_page"]') as event_current_page,
    coalesce(json_extract_scalar(event_properties, '$["dom_performance"]'), json_extract_scalar(event_properties, '$["domPerformance"]')) as event_dom_performance,
    json_extract_scalar(event_properties, '$["element_type"]') as event_element_type,
    json_extract_scalar(event_properties, '$["event_type"]') as event_event_type,
    json_extract_scalar(event_properties, '$["from_similar"]') as event_from_similar,
    json_extract_scalar(event_properties, '$["has_listing_video"]') as event_has_listing_video,
    json_extract_scalar(event_properties, '$["homes_email"]') as event_homes_email,
    coalesce(json_extract_scalar(event_properties, '$["house_id"]'), json_extract_scalar(event_properties, '$["houseId"]')) as event_house_id,
    json_extract_scalar(event_properties, '$["house_tags"]') as event_house_tags,
    json_extract_scalar(event_properties, '$["is_exclusive"]') as event_is_exclusive,
    json_extract_scalar(event_properties, '$["is_furnished"]') as event_is_furnished,
    json_extract_scalar(event_properties, '$["is_prox_metro"]') as event_is_prox_metro,
    json_extract_scalar(event_properties, '$["listing"]') as event_listing,
    json_extract_scalar(event_properties, '$["m2"]') as event_m2,
    json_extract_scalar(event_properties, '$["macro_region"]') as event_macro_region,
    json_extract_scalar(event_properties, '$["macro_region_id"]') as event_macro_region_id,
    json_extract_scalar(event_properties, '$["nbr_bathrooms"]') as event_nbr_bathrooms,
    json_extract_scalar(event_properties, '$["nbr_dorms"]') as event_nbr_dorms,
    json_extract_scalar(event_properties, '$["nbr_parking_slots"]') as event_nbr_parking_slots,
    json_extract_scalar(event_properties, '$["neighborhood"]') as event_neighborhood,
    coalesce(json_extract_scalar(event_properties, '$["network_performance"]'), json_extract_scalar(event_properties, '$["networkPerformance"]')) as event_network_performance,
    json_extract_scalar(event_properties, '$["originals_type"]') as event_originals_type,
    json_extract_scalar(event_properties, '$["price"]') as event_price,
    json_extract_scalar(event_properties, '$["referrer"]') as event_referrer,
    json_extract_scalar(event_properties, '$["search_id"]') as event_search_id,
    json_extract_scalar(event_properties, '$["search_rank"].rank') as event_search_rank_rank,
    json_extract_scalar(event_properties, '$["search_rank"].resultsOrigin') as event_search_rank_results_origin,
    json_extract_scalar(event_properties, '$["search_rank"].searchClient') as event_search_rank_search_client,
    json_extract_scalar(event_properties, '$["search_rank"].searchMode') as event_search_rank_search_mode,
    json_extract_scalar(event_properties, '$["search_rank"].sortMode') as event_search_rank_sort_mode,
    json_extract_scalar(event_properties, '$["state"]') as event_state,
    json_extract_scalar(event_properties, '$["sub_region"]') as event_sub_region,
    json_extract_scalar(event_properties, '$["sub_region_id"]') as event_sub_region_id,
    json_extract_scalar(event_properties, '$["type_property"]') as event_type_property,
    json_extract_scalar(event_properties, '$["uri"]') as event_uri,
    json_extract_scalar(event_properties, '$["valor_aluguel"]') as event_valor_aluguel,
    json_extract_scalar(event_properties, '$["valor_condominio"]') as event_valor_condominio,
    json_extract_scalar(event_properties, '$["valor_total"]') as event_valor_total
FROM
    datalake_amplitude_clean_prod.events
WHERE
    event_type = 'visit_intent_clicked';
