select
  id,
  dadosfotografo_id as id_photographer_data,
  imovel_id as id_house,
  origincreation_id as id_origin_creation,
  reservadopara_id as id_reserved_for,
  originlastupdate_id as id_last_update_origin,
  telefonesessaofotos as photo_session_phone,
  emailsessaofotos as photo_session_email,
  telefonesessaofotossecundario as photo_session_secondary_phone,
  nomecontatosessaofotos as photo_session_contact_name,
  photoSender as photo_sender_user_type,
  status,
  motivoAlteracao as reason_of_change,
  motivocancelamentojob as cancellation_reason,
  textomotivocancelamento as cancellation_reason_text,
  scorecorretude as correctness_score,
  retirarchave as key_pick_up,
  outroschave as key_others,
  problema as problem,
  instrucoesagendamento as booking_instructions,
  revisionimovel as house_revision,
  tipocontrato as contract_type,
  scorecompletude as completeness_score,
  naotentoucontato as has_tried_contact,
  lockbox as has_lockbox,
  autorizacaoporescrito as has_written_authorization,
  semcontatoproprietario as has_no_landlord_contact,
  fixed as is_fixed,
  prefereemailsessaofotos as is_photo_session_email_preferred,
  aprovado as is_approved,
  confirmado as is_confirmed,
  dataaceitofotografo as ts_photographer_accepted,
  datapagamento as ts_payment,
  datainiciosessao as ts_session_started,
  datauploadfotos as ts_photos_uploaded,
  datajobpedido as ts_photo_job_requested,
  dataagendamento as ts_scheduled,
  datacriacao as ts_created,
  atualizadoem as ts_updated
from datalake_ebdb_raw.jobfotografo
