SELECT
    city,
    comission_cs_ciq_full,
    comission_cs_ciq_manager,
    comission_listing,
    comission_listing_fs,
    data,
    impostos,
    month,
    other,
    revshare_cs_ciq_full,
    revshare_cs_ciq_manager,
    total_costs_ciq_full_for_rent,
    total_costs_ciq_full_for_sale,
    week_start,
    year
FROM
    datalake_gsheets_raw.ciq_costs