SELECT
    city_group,
    contract_signed,
    credit_approved,
    credit_evaluation_init,
    credit_evaluation_positive,
    demand_channel,
    document_sent,
    new_tenant_prospect,
    offer_accepted,
    offer_submitted,
    visit_booked,
    visit_completed,
    week_start
FROM
    datalake_gsheets_raw.demand_channel_share
