SELECT
    CAST(NULLIF(contrato,'') AS INT) AS id_contract,
    CAST(NULLIF(fileid,'') AS INT) AS id_file,
    CAST(NULLIF(ticket,'') AS INT) AS id_ticket,
    NULLIF(reason,'') AS reason,
    NULLIF(type,'') AS type,
    NULLIF(account,'') AS account,
    NULLIF(expense,'') AS expense,
    CAST(NULLIF(amount,'') AS FLOAT) AS amount,
    NULLIF(item,'') AS item,
    NULLIF(from,'') AS from_account,
    NULLIF(to,'') AS to_account,
    NULLIF(mes_vencimento,'') AS month_due,
    NULLIF(request,'') AS request,
    NULLIF(ref_month,'') AS ref_month,
    CAST(NULLIF(invoice_amount,'') AS FLOAT) AS invoice_amount,
    CAST(NULLIF(machine_use,'') AS INT) AS machine_use,
    NULLIF(barcode,'') AS barcode,
    CAST(NULLIF(boleto_creation_time,'') AS INT) AS invoice_creation_time,
    NULLIF(time_spent_ticket,'') AS time_spent_ticket,
    CAST(NULLIF(row,'') AS INT) AS row,
    BOOLEAN(NULLIF(protecao5A,'')) As is_protecao5a,
    DATE(NULLIF(due_date,'')) AS dt_due,
    DATE(NULLIF(result,'')) AS dt_result,
    TO_TIMESTAMP(NULLIF(invoice_creation,''),'MM/dd/yyyy HH:mm:ss') AS ts_invoice_creation,
    TO_TIMESTAMP(NULLIF(boleto_created_at,''),'MM/dd/yyyy HH:mm:ss') AS ts_invoice_created,
    TO_TIMESTAMP(NULLIF(sent_at,''),'MM/dd/yyyy HH:mm:ss') AS ts_sent
FROM 
    datalake_gsheets_raw.extra_invoice_expenses