SELECT
    CAST(contract_id AS INTEGER ) AS id_contract,
    CAST(house_listing AS INTEGER) AS id_house_listing,
    agreement_status,
    check_abandonment,
    city,
    condo_internalization_status,
    contract_ended_reason,
    contract_status,
    cs_eviction_code,
    cs_status,
    eviction_code,
    eviction_status,
    general_comments,
    guarantee,
    landlord_emails,
    landlord_names,
    landlord_ticket_number,
    last_communication_subject,
    last_settlement_communication_subject,
    offboarding_status,
    office_judge,
    order_type,
    procedure,
    resident_emails,
    responsible_office,
    settlement_ticket_number,
    tenant_emails,
    tenant_names,
    tenant_ticket_number,
    IF(LOWER(is_fraud) == 'sim', True, False) AS is_fraud,
    IF(LOWER(is_repeat_offender)=='sim',True, False) AS is_repeat_offender,
    TO_DATE(agreement_settlement_date, 'dd/mm/yyyy') AS dt_agreement_settlement,
    TO_DATE(agreement_start_date, 'dd/mm/yyyy') AS dt_agreement_start,
    TO_DATE(broken_agreement_date, 'dd/mm/yyyy') AS dt_broken_agreement,
    TO_DATE(competency_month, 'dd/mm/yyyy') AS dt_competency_month,
    TO_DATE(contract_ended_date, 'dd/mm/yyyy') AS dt_contract_ended,
    TO_DATE(contract_ended_status_change_date, 'dd/mm/yyyy') AS dt_contract_ended_status_change,
    TO_DATE(contract_ending_date, 'dd/mm/yyyy') AS dt_contract_ending,
    TO_DATE(contract_ending_status_change_date, 'dd/mm/yyyy') AS dt_contract_ending_status_change,
    TO_DATE(contract_start_date, 'dd/mm/yyyy') AS dt_contract_start,
    TO_DATE(cs_distribution_date, 'dd/mm/yyyy') AS dt_cs_distribution,
    TO_DATE(cs_verdict_date, 'dd/mm/yyyy') AS dt_cs_verdict,
    TO_DATE(distribution_date, 'dd/mm/yyyy') AS dt_distribution,
    TO_DATE(final_verdict_date, 'dd/mm/yyyy') AS dt_final_verdict,
    TO_DATE(settlement_without_agreement_date, 'dd/mm/yyyy') AS dt_settlement_without_agreement,
    TO_DATE(sheet_insertion_date, 'dd/mm/yyyy') AS dt_sheet_insertion,
    TO_DATE(verdict_date, 'dd/mm/yyyy') AS dt_verdict
FROM
    datalake_gsheets_raw.process_eviction