SELECT
    CAST(contract_id AS INTEGER ) AS id_contract,
    CAST(house_listing AS INTEGER) AS id_house_listing,
    agreement_status,
    check_abandonment,
    city,
    condo_internalization_status,
    contract_ended_reason,
    contract_status,
    cs_eviction_code,
    cs_status,
    eviction_code,
    eviction_status,
    general_comments,
    guarantee,
    landlord_emails,
    landlord_names,
    landlord_ticket_number,
    last_communication_subject,
    last_settlement_communication_subject,
    offboarding_status,
    office_judge,
    order_type,
    procedure,
    resident_emails,
    responsible_office,
    settlement_ticket_number,
    tenant_emails,
    tenant_names,
    tenant_ticket_number,
    IF(LOWER(is_fraud) == 'sim', True, False) AS is_fraud,
    IF(LOWER(is_repeat_offender)=='sim',True, False) AS is_repeat_offender,
    DATE(agreement_settlement_date) AS dt_agreement_settlement,
    DATE(agreement_start_date) AS dt_agreement_start,
    DATE(broken_agreement_date) AS dt_broken_agreement,
    DATE(competency_month) AS dt_competency_month,
    DATE(contract_ended_date) AS dt_contract_ended,
    DATE(contract_ended_status_change_date) AS dt_contract_ended_status_change,
    DATE(contract_ending_date) AS dt_contract_ending,
    DATE(contract_ending_status_change_date) AS dt_contract_ending_status_change,
    DATE(contract_start_date) AS dt_contract_start,
    DATE(cs_distribution_date) AS dt_cs_distribution,
    DATE(cs_verdict_date) AS dt_cs_verdict,
    DATE(distribution_date) AS dt_distribution,
    DATE(final_verdict_date) AS dt_final_verdict,
    DATE(settlement_without_agreement_date) AS dt_settlement_without_agreement,
    DATE(sheet_insertion_date) AS dt_sheet_insertion,
    DATE(verdict_date) AS dt_verdict
FROM
    datalake_gsheets_raw.process_eviction