SELECT
    campaign,
    city_group,
    first_listings,
    mkt_channel,
    mkt_origin,
    mkt_type,
    operacao,
    opportunities,
    prospects,
    qualifieds,
    halfyear,
    quarter,
    week,
    year,
    month,
    date
FROM
    datalake_gsheets_raw.sale_supply_targets
