SELECT
    account_name,
    campaign_origin_aquisition,
    cost_factor,
    fact_cost,
    mkt_category,
    mkt_channel,
    mkt_completion,
    mkt_flow,
    mkt_medium,
    mkt_origin,
    mkt_source,
    origin,
    schema,
    side,
    split_into_cities,
    table_dim
FROM
    datalake_gsheets_raw.full_taxonomy