SELECT
    city_group,
    contract_signed,
    credit_approved,
    credit_evaluation_init,
    credit_evaluation_positive,
    demand_channel_type,
    document_sent,
    funnel_first_touchpoint,
    offer_accepted,
    offer_submitted,
    visit_booked,
    visit_completed,
    weekday_name
FROM
    datalake_gsheets_raw.weekday_demand_share
