"""
VOCS-34 Slice 1 -- raw inference-status collector for vocs-machina.

Hand-rolled DAG: intentionally NOT generated by the DAG Builder / a
*_declaration.yml (unlike dags/for_rent/vocs_machina, which this DAG reads
from but never modifies). A later slice (Slice 3) needs
airflow.timetables.datasets.DatasetOrTimeSchedule combined with
airflow.timetables.trigger.CronTriggerTimetable to express a hybrid
cron+dataset schedule. BaseWorkflow cannot express that: it treats
schedule_interval and dataset_dependencies as mutually exclusive (see
packages/bietlejuice-airflow/src/bietlejuice/base/airflow/dag_builders/main_builder/workflows/base_workflow.py,
around lines 107-132). So this DAG is hand-rolled from the first commit
instead of being upgraded later. Placeholder schedule only in this slice
(schedule_interval=None) -- the hybrid DatasetOrTimeSchedule is explicitly
out of scope here.

What this DAG does:
  1. stage-inference-status-to-s3 (PythonOperator): reads quintoml's prompt
     manifest, works out which (day, prompt_id, prompt_hash) backfill
     partitions should exist, checks whether quintoml has finalized each one
     (_SUCCESS marker present), and stages a done/missing snapshot as JSON to
     this repo's own datalake bucket.
  2. create-cluster -> load-vocs-machina-inference-status-raw ->
     terminate-cluster: a Databricks cluster loads that JSON into
     datalake_vocs_machina_planning_raw.vocs_machina_inference_status.

Style model: dags/fintech/enrich_dai_report/enrich_dai_report.py (manual
DAG()/create-cluster/submit-run/terminate-cluster wiring) and
dags/platform/dag_inventory/dag_inventory.py (PythonOperator + S3Hook
staging a JSON blob to S3 ahead of the Spark job).
"""

import json
import os
import re
from datetime import datetime, timedelta

import pendulum
from airflow.hooks.S3_hook import S3Hook
from airflow.models import DAG
from airflow.operators.python_operator import PythonOperator
from airflow.utils.trigger_rule import TriggerRule
from databricks_plugin import (
    QuintoAndarDatabricksCreateClusterOperator,
    QuintoAndarDatabricksSubmitRunOperator,
    QuintoAndarDatabricksTerminateClusterOperator,
)
from quintoandar_logger import QuintoAndarLogger

from bietlejuice.base.airflow.base_dag import BaseDAG
from bietlejuice.base.airflow.dag_owner_enum import DAGOwnerEnum
from bietlejuice.base.databricks.cluster_permission_enum import ClusterPermissionEnum
from bietlejuice.base.databricks.databricks_group_name_enum import (
    DatabricksGroupNameEnum,
)
from bietlejuice.base.jiraops.jiraops_callback import JiraOpsCallback
from bietlejuice.services.configuration_service import ConfigurationService

LOCAL_TZ = pendulum.timezone("America/Sao_Paulo")
MAIN_START_DATE = datetime(2026, 7, 1, 0, 0, 0, tzinfo=LOCAL_TZ)

SOURCE = "vocs_machina_planning"
DAG_ID = f"bietlejuice.{SOURCE}"
ENV = os.environ.get("ENVIRONMENT")
logger = QuintoAndarLogger(SOURCE)

DATE_FMT = "%Y-%m-%d"

# quintoml's vocs-machina S3 layout (read-only from this DAG; written by
# quintoml's own write_manifest() / classification job, never by us).
DATA_SCIENCE_BUCKET = "data-science.s3.data.quintoandar.com.br"
VOCS_MACHINA_MANIFEST_KEY = (
    "post-contract/vocs-machina/_meta/latest_active_prompts.json"
)
VOCS_MACHINA_RAW_PREFIX = "post-contract/vocs-machina/raw"

# This DAG's own staging output, in bi-etl-ejuice's datalake bucket -- keyed by
# the DAG's load/ingestion date, NOT by the backfill day each staged row is
# about (a single snapshot file covers many backfill days across all active
# prompts).
STAGING_KEY_PREFIX = "raw/vocs_machina_planning/inference_status_snapshot"
STAGING_FILE_NAME = "inference_status_snapshot.json"

RAW_TABLE_NAME = "vocs_machina_inference_status"
RAW_PARTITION_COLS = "['year', 'month', 'day']"


def get_date_param(dag_run, default_date, date_param_name):
    """Read a date override from the DAG run conf, falling back to default_date.

    Identical logic to BaseWorkflow.get_date_param (see
    dag_builders/main_builder/workflows/base_workflow.py), which BaseWorkflow
    registers as a Jinja user_defined_macro for every DAG-Builder DAG. Since
    this DAG is hand-rolled and never goes through BaseWorkflow.dag_instance(),
    that auto-registration never happens here, so the macro is duplicated and
    registered manually below (same reason dags/growth/semrush/semrush.py
    defines its own get_toggle_param instead of relying on the builder).
    """
    date_param = dag_run.conf.get(date_param_name) if dag_run.conf else None
    if date_param and re.match(r"[0-9]{4}-[0-9]{2}-[0-9]{2}", date_param):
        return date_param
    return default_date


def active_prompts(manifest):
    """Return only the prompts flagged active=True in quintoml's manifest.

    Checks identity against True rather than bare truthiness: quintoml's
    write_manifest() always writes a real JSON boolean, but a hand-edited or
    malformed manifest could carry a truthy-but-wrong value (e.g. the string
    "false", itself truthy in Python) that must not be treated as active.
    """
    return [
        prompt for prompt in manifest.get("prompts", []) if prompt.get("active") is True
    ]


def backfill_day_range(today, backfill_days):
    """Inclusive day range [today - backfill_days, today]."""
    if backfill_days < 0:
        raise ValueError(f"backfill_days must be >= 0, got {backfill_days}")
    start = today - timedelta(days=backfill_days)
    return [start + timedelta(days=offset) for offset in range(backfill_days + 1)]


def success_marker_key(prompt_id, prompt_hash, day):
    """Build the _SUCCESS marker key for one (day, prompt_id, prompt_hash) partition.

    Mirrors quintoml's vocs_machina/storage.py build_partition_prefix +
    build_success_marker_uri byte-for-byte (zero-padded month/day), so this
    checks the exact key quintoml's classification job writes. Relative to
    DATA_SCIENCE_BUCKET (no bucket/scheme prefix) -- dag_inventory.py's own
    partition_path (non-zero-padded) is NOT used here on purpose, since that
    would look for the wrong key against quintoml's actual layout.
    """
    return (
        f"{VOCS_MACHINA_RAW_PREFIX}/"
        f"year={day.year}/month={day.month:02d}/day={day.day:02d}/"
        f"prompt_id={prompt_id}/prompt_hash={prompt_hash}/_SUCCESS"
    )


_UNSAFE_PARTITION_COMPONENT_RE = re.compile(r"[/\x00-\x1f]")


def _is_safe_partition_component(value):
    """True if value is safe to embed as a single S3 partition-key segment.

    Rejects a literal "/" (which would inject extra path segments into the
    year=/month=/day=/prompt_id=/prompt_hash=/ structure quintoml's own
    _HASH_KEY_RE parser expects) and control characters, including a null
    byte.
    """
    return isinstance(value, str) and not _UNSAFE_PARTITION_COMPONENT_RE.search(value)


def iter_partition_days(prompts, today):
    """Expand each active prompt into (day, prompt_id, prompt_hash) tuples, one
    per backfill day.

    A prompt missing "prompt_id"/"prompt_hash"/"backfill_days" (KeyError),
    carrying a negative backfill_days (ValueError, see backfill_day_range),
    or carrying a prompt_id/prompt_hash unsafe for an S3 partition key (see
    _is_safe_partition_component) is skipped with a warning rather than
    aborting the whole snapshot: one malformed manifest entry should not stop
    every other active prompt from being staged.

    De-duplicates by (day, prompt_id, prompt_hash): two manifest entries that
    describe the same partition (e.g. a duplicated entry, or two entries
    whose backfill windows overlap) must not produce the same row twice in
    the staged snapshot.
    """
    partition_days = []
    seen = set()
    for prompt in prompts:
        try:
            prompt_id = prompt["prompt_id"]
            prompt_hash = prompt["prompt_hash"]
            days = backfill_day_range(today, prompt["backfill_days"])
        except (KeyError, ValueError) as exc:
            logger.warning(
                f"m=iter_partition_days, prompt_id={prompt.get('prompt_id')}, "
                f"msg=Skipping prompt with missing/invalid required field: {exc}"
            )
            continue
        if not (
            _is_safe_partition_component(prompt_id)
            and _is_safe_partition_component(prompt_hash)
        ):
            logger.warning(
                f"m=iter_partition_days, prompt_id={prompt_id!r}, "
                f"msg=Skipping prompt with a prompt_id/prompt_hash unsafe for "
                f"S3 partition keys"
            )
            continue
        for day in days:
            key = (day, prompt_id, prompt_hash)
            if key in seen:
                continue
            seen.add(key)
            partition_days.append(key)
    return partition_days


def build_snapshot_rows(partition_days, existing_marker_keys):
    """Pure S3-key -> status mapping: "done" if the partition's _SUCCESS marker
    key is present in existing_marker_keys, "missing" otherwise.

    No I/O happens here -- the caller (stage_inference_status_to_s3) is
    responsible for populating existing_marker_keys by calling
    S3Hook.check_for_key once per candidate key and collecting the ones that
    returned True. Keeping this function pure/isolated is what makes it
    trivially unit-testable (see test_vocs_machina_planning.py) without a
    live or mocked S3 connection.
    """
    rows = []
    for day, prompt_id, prompt_hash in partition_days:
        marker_key = success_marker_key(prompt_id, prompt_hash, day)
        status = "done" if marker_key in existing_marker_keys else "missing"
        rows.append(
            {
                "day": day.strftime(DATE_FMT),
                "prompt_id": prompt_id,
                "prompt_hash": prompt_hash,
                "inference_status": status,
            }
        )
    return rows


def existing_marker_keys_for_days(hook, days):
    """Batch-list every _SUCCESS marker that exists for a set of backfill days.

    Every prompt's marker for a given day lives under the same
    year=/month=/day=/ prefix (prompt_id=/prompt_hash= is nested underneath,
    see success_marker_key), so one S3Hook.list_keys call per unique day
    covers every active prompt that shares that day -- instead of one
    check_for_key HeadObject call per (day, prompt_id, prompt_hash) tuple,
    which for prompts with long, overlapping backfill windows can mean
    hundreds of sequential blocking calls to a cross-account bucket on a
    single run.
    """
    existing_keys = set()
    for day in days:
        prefix = (
            f"{VOCS_MACHINA_RAW_PREFIX}/"
            f"year={day.year}/month={day.month:02d}/day={day.day:02d}/"
        )
        keys = hook.list_keys(bucket_name=DATA_SCIENCE_BUCKET, prefix=prefix) or []
        existing_keys.update(key for key in keys if key.endswith("/_SUCCESS"))
    return existing_keys


def stage_inference_status_to_s3(load_start_date: str, **kwargs) -> None:
    """Task A: build today's inference-status snapshot and stage it to S3.

    1. Read quintoml's prompt manifest (read-only).
    2. For each active prompt, expand [today - backfill_days, today] into one
       (day, prompt_id, prompt_hash) tuple per day.
    3. Batch-list which of those partitions quintoml has already finalized
       (_SUCCESS marker present), one S3Hook.list_keys call per unique day
       shared across all active prompts (see existing_marker_keys_for_days).
    4. Stage the resulting rows as a JSON blob to bi-etl-ejuice's own
       datalake_bucket (NOT the data-science bucket), keyed by this DAG's
       own load date.
    """
    hook = S3Hook(aws_conn_id="aws_default")

    manifest_content = hook.read_key(
        key=VOCS_MACHINA_MANIFEST_KEY, bucket_name=DATA_SCIENCE_BUCKET
    )
    manifest = json.loads(manifest_content)

    today = datetime.strptime(load_start_date, DATE_FMT).date()
    partition_days = iter_partition_days(active_prompts(manifest), today)

    unique_days = {day for day, _, _ in partition_days}
    existing_marker_keys = existing_marker_keys_for_days(hook, unique_days)

    rows = build_snapshot_rows(partition_days, existing_marker_keys)

    execution_date = datetime.strptime(load_start_date, DATE_FMT)
    partition_path = (
        f"year={execution_date.year}/month={execution_date.month:02d}/"
        f"day={execution_date.day:02d}"
    )
    hook.load_string(
        string_data=json.dumps(rows),
        key=f"{STAGING_KEY_PREFIX}/{partition_path}/{STAGING_FILE_NAME}",
        bucket_name=datalake_bucket,
        replace=True,
        acl_policy="bucket-owner-full-control",
    )


jiraops_callback = JiraOpsCallback()

config_service = ConfigurationService(SOURCE)
datalake_bucket = config_service.get_config("datalake_bucket")
doc_md_chart_url = config_service.get_config("doc_md_chart_url")
default_libraries = config_service.get_config("default_libraries")
databricks_bietlejuice_repo_path = config_service.get_config(
    "databricks_bietlejuice_repo_path"
)
SPARK_JOBS_PATH = f"{databricks_bietlejuice_repo_path}/spark_jobs/{SOURCE}/"

CLUSTER_DESCRIPTION = config_service.get_config(
    "consolidation_xs_memory_single_node_cluster"
)
CLUSTER_DESCRIPTION["data_security_mode"] = "SINGLE_USER"
CLUSTER_DESCRIPTION["single_user_name"] = "{{ var.value.databricks_single_user_name }}"
CLUSTER_DESCRIPTION["spark_conf"]["spark.databricks.sql.initial.catalog.namespace"] = (
    "quintoandar_{{ var.value.environment }}"
)
DATABRICKS_CLUSTER_ACCESS_CONTROL_LIST = [
    {
        "group_name": DatabricksGroupNameEnum.ANALYTICS_ENGINEERS,
        "permission_level": ClusterPermissionEnum.MANAGE,
    }
]

dag = DAG(
    dag_id=DAG_ID,
    default_args={
        "owner": DAGOwnerEnum.DATA_FOR_RENT,
        "wait_for_downstream": False,
        "depends_on_past": False,
        "on_failure_callback": jiraops_callback.task_failure_alert,
    },
    start_date=MAIN_START_DATE,
    # Placeholder schedule for this slice -- manual/dataset-triggered runs only.
    # Slice 3 replaces this with DatasetOrTimeSchedule + CronTriggerTimetable.
    schedule_interval=None,
    doc_md=BaseDAG.get_dag_doc(SOURCE).format(
        chart_url=doc_md_chart_url, dag_id=DAG_ID
    ),
    user_defined_macros={"get_date_param": get_date_param},
    params=BaseDAG.get_default_trigger_form_params(),
)

stage_inference_status_task = PythonOperator(
    dag=dag,
    task_id="stage-inference-status-to-s3",
    python_callable=stage_inference_status_to_s3,
    op_kwargs={
        "load_start_date": "{{ get_date_param(dag_run, data_interval_start | ds, 'load_start_date') }}",
    },
    provide_context=True,
)

create_cluster_task = QuintoAndarDatabricksCreateClusterOperator(
    databricks_conn_id="databricks_new",
    dag=dag,
    task_id="create-cluster",
    cluster_configuration=CLUSTER_DESCRIPTION,
    access_control_list=DATABRICKS_CLUSTER_ACCESS_CONTROL_LIST,
    libraries=default_libraries,
)

load_inference_status_raw_task = QuintoAndarDatabricksSubmitRunOperator(
    databricks_conn_id="databricks_new",
    task_id="load-vocs-machina-inference-status-raw",
    dag=dag,
    json={
        "spark_python_task": {
            "python_file": f"{SPARK_JOBS_PATH}load_vocs_machina_inference_status_raw.py",
            "parameters": [
                ENV,
                datalake_bucket,
                SOURCE,
                RAW_TABLE_NAME,
                "{{ get_date_param(dag_run, data_interval_start | ds, 'load_start_date') }}",
                RAW_PARTITION_COLS,
            ],
        }
    },
)

terminate_cluster_task = QuintoAndarDatabricksTerminateClusterOperator(
    databricks_conn_id="databricks_new",
    dag=dag,
    task_id="terminate-cluster",
    # NONE_SKIPPED (not the default ALL_SUCCESS): if load-vocs-machina-
    # inference-status-raw fails after create-cluster succeeded, the cluster
    # must still be torn down instead of leaking until its idle timeout.
    # NONE_SKIPPED still leaves the cluster alone when stage-inference-
    # status-to-s3 itself is skipped (Slice 3's selective-propagation path,
    # see should_skip_stage_task) -- create-cluster is skipped too in that
    # case, so there is no cluster to terminate.
    trigger_rule=TriggerRule.NONE_SKIPPED,
)

(
    stage_inference_status_task
    >> create_cluster_task
    >> load_inference_status_raw_task
    >> terminate_cluster_task
)
