"""
VOCS-34 Slice 3 -- planner scheduling, selective propagation and real enrich
execution for vocs-machina (Slice 1 laid down the raw collector; Slice 2 laid
down the enrich SQL as inert text).

Hand-rolled DAG: intentionally NOT generated by the DAG Builder / a
*_declaration.yml (unlike dags/for_rent/vocs_machina, which this DAG reads
from but never modifies). This slice needs
airflow.timetables.datasets.DatasetOrTimeSchedule combined with
airflow.timetables.trigger.CronTriggerTimetable to express a hybrid
cron+dataset schedule. BaseWorkflow cannot express that: it treats
schedule_interval and dataset_dependencies as mutually exclusive (see
packages/bietlejuice-airflow/src/bietlejuice/base/airflow/dag_builders/main_builder/workflows/base_workflow.py,
around lines 107-132). So this DAG is hand-rolled from the first commit
instead of being upgraded later.

What this DAG does:
  1. stage-inference-status-to-s3 (PythonOperator): reads quintoml's prompt
     manifest, works out which (day, prompt_id, prompt_hash) backfill
     partitions should exist, checks whether quintoml has finalized each one
     (_SUCCESS marker present), and computes a hash of the resulting
     done/missing snapshot to decide whether anything changed since the last
     run. Despite the task's name, it writes nothing to S3 -- see
     spark_jobs/load_vocs_machina_inference_status_raw.py's module docstring
     for why. Selective propagation (Slice 3): if this run was triggered only
     by the cron safety net (no upstream dataset fired) and the snapshot is
     unchanged since the last published run, the task raises
     AirflowSkipException, which cascades to skip every downstream task
     (cluster creation, raw load, enrich execution) so we don't wake
     EMR/quintoml for nothing every 6 hours.
  2. execute-job-cluster -> load-vocs-machina-inference-status-raw -> <enrich
     task group> -> terminate-emr-cluster: a single EMR job cluster
     independently re-reads the same manifest (its own instance profile
     reaches quintoml's bucket directly, separately from Task A's) and loads
     the result into
     datalake_vocs_machina_planning_raw.vocs_machina_inference_status, then
     materializes both queries/enrich/*.sql files (Slice 2) as real Delta
     tables via DatalakeTaskGroup.build_task_group_from_sql_files --
     datalake_vocs_machina_planning.vocs_machina_backfill_status and
     .vocs_machina_backfill_status_summary. The summary's load task is the
     cross-repo contract quintoml's Slice 4 subscribes to (see the dataset
     outlet note on that task group below).
  3. Schedule (Slice 3): DatasetOrTimeSchedule ORing 14 upstream sources
     (FONTES, copied verbatim from quintoml's config/prod.yml job.schedule)
     with a 6-hour CronTriggerTimetable safety net, so the DAG also runs even
     if none of the 14 sources fire in a given window.

Compute (VOCS-45): every Spark task runs as a step on one EMR job cluster,
built by the shared job-cluster engine rather than by hand-instantiated
operators. Structural model:
dags/support_and_service/salesforce_api_v2/salesforce_api_v2.py -- build a
DagExecutionContext carrying the cluster_args read from
vocs_machina_planning_cluster.yml, call attach_job_cluster_engine_to_context
to pick the engine, then create every task through
dag_execution_context.job_cluster_engine (including DatalakeTaskGroup's,
which takes the engine as a constructor argument). Diverges from
salesforce_api_v2 in the teardown: this DAG is a single linear chain with no
job-cluster-finished task, so it calls create_emr_terminate_cluster_task
directly instead of going through get_job_cluster_completion_sink /
attach_emr_terminate_cluster_work_prerequisites, which exist for branching
and multi-cluster topologies.

Diverges from dags/platform/dag_inventory/dag_inventory.py's PythonOperator
+ S3Hook staging-to-S3 pattern for the Task-A-to-Spark-job hand-off -- see
spark_jobs/load_vocs_machina_inference_status_raw.py's module docstring for
why (an Airflow-side S3 write grant, then a job-parameter size cap on the
Databricks submit API this DAG used at the time, were both tried and ruled
out).
"""

import hashlib
import json
import os
import re
from datetime import datetime, timedelta
from functools import reduce
from operator import or_

import pendulum
from airflow.datasets import Dataset
from airflow.exceptions import AirflowSkipException
from airflow.hooks.S3_hook import S3Hook
from airflow.models import DAG, Variable
from airflow.operators.python_operator import PythonOperator
from airflow.timetables.datasets import DatasetOrTimeSchedule
from airflow.timetables.trigger import CronTriggerTimetable
from airflow.utils.helpers import chain
from airflow.utils.trigger_rule import TriggerRule
from quintoandar_logger import QuintoAndarLogger

from bietlejuice.base.airflow.base_dag import BaseDAG
from bietlejuice.base.airflow.dag_owner_enum import DAGOwnerEnum
from bietlejuice.base.airflow.helpers import TaskFlowHelper
from bietlejuice.base.airflow.job_cluster_engine import (
    attach_job_cluster_engine_to_context,
)
from bietlejuice.base.airflow.task_creators.dag_execution_context import (
    DagExecutionContext,
)
from bietlejuice.base.airflow.task_groups.datalake_task_group import DatalakeTaskGroup
from bietlejuice.base.jiraops.jiraops_callback import JiraOpsCallback
from bietlejuice.base.pipeline.layer_enum import LayerEnum
from bietlejuice.base.service.dag_packages_path_service import DAGPackagesPathService
from bietlejuice.services.configuration_service import ConfigurationService
from bietlejuice.services.file_service import FileService

LOCAL_TZ = pendulum.timezone("America/Sao_Paulo")
MAIN_START_DATE = datetime(2026, 7, 1, 0, 0, 0, tzinfo=LOCAL_TZ)

SOURCE = "vocs_machina_planning"
DAG_ID = f"bietlejuice.{SOURCE}"
ENV = os.environ.get("ENVIRONMENT")
logger = QuintoAndarLogger(SOURCE)

DATE_FMT = "%Y-%m-%d"

# quintoml's vocs-machina S3 layout (read-only from this DAG; written by
# quintoml's own write_manifest() / classification job, never by us).
DATA_SCIENCE_BUCKET = "data-science.s3.data.quintoandar.com.br"
VOCS_MACHINA_MANIFEST_KEY = (
    "post-contract/vocs-machina/_meta/latest_active_prompts.json"
)
VOCS_MACHINA_RAW_PREFIX = "post-contract/vocs-machina/raw"

RAW_TABLE_NAME = "vocs_machina_inference_status"
RAW_PARTITION_COLS = "['year', 'month', 'day']"

# Slice 2's enrich tables (queries/enrich/*.sql), materialized for real in
# this slice. vocs_machina_backfill_status_summary.sql SELECTs FROM
# datalake_vocs_machina_planning.vocs_machina_backfill_status, so the summary
# table's load task must run strictly after the detail table's -- see the
# DatalakeTaskGroup.set_inner_dag_dependencies wiring below.
BACKFILL_STATUS_TABLE = "vocs_machina_backfill_status"
BACKFILL_STATUS_SUMMARY_TABLE = "vocs_machina_backfill_status_summary"

# Airflow Variable holding the MD5 of the last snapshot this DAG staged to
# S3, used by should_skip_stage_task to decide whether a cron-only run (no
# upstream dataset fired) has anything new to propagate. Follows the same
# Variable-as-ledger convention as DEDUP_VARIABLE_KEY in
# dags/platform/dag_runtime_monitoring/dag_runtime_monitoring.py.
LAST_SNAPSHOT_HASH_VARIABLE_KEY = "vocs_machina_planning_last_snapshot_hash"

# Hybrid schedule (Slice 3): OR of the 14 upstream sources quintoml's
# config/prod.yml currently subscribes to under job.schedule -- copied
# verbatim, do not alter. This DAG cannot go through
# DatasetService.get_dag_datasets()/dependencies.yaml because that pipeline
# is confirmed AND-only (a flat list is wrapped as {"all": ...} by
# DatasetService.get_dataset_as_dict_expression_from_dependencies, and a
# manual dict-shaped override would crash apply_manual_modifications's
# sort_tasks() step, which assumes every value is a list). reduce(or_, ...)
# below produces a Dataset OR condition directly, bypassing that pipeline.
FONTES = [
    Dataset("bietlejuice.reverse_birdie:load-reverse-onboarding:first-run-of-day"),
    Dataset("bietlejuice.reverse_birdie:load-reverse-ongoing:first-run-of-day"),
    Dataset("bietlejuice.reverse_birdie:load-reverse-offboarding:first-run-of-day"),
    Dataset("bietlejuice.reverse_birdie:load-reverse-lost:first-run-of-day"),
    Dataset("bietlejuice.reverse_birdie:load-reverse-pp-multi:first-run-of-day"),
    Dataset("bietlejuice.reverse_birdie:load-reverse-new-surveys:first-run-of-day"),
    Dataset("bietlejuice.reverse_birdie:load-reverse-end-of-process:first-run-of-day"),
    Dataset("bietlejuice.reverse_birdie:load-reverse-dsat-bot:first-run-of-day"),
    Dataset(
        "bietlejuice.reverse_birdie:load-reverse-dsat-customer-relationship:first-run-of-day"
    ),
    Dataset("bietlejuice.reverse_birdie:load-reverse-dsat-visits:first-run-of-day"),
    Dataset("bietlejuice.reverse_birdie:load-reverse-dsat-diligence:first-run-of-day"),
    Dataset("bietlejuice.reverse_birdie:load-reverse-dsat-financing:first-run-of-day"),
    Dataset(
        "bietlejuice.reverse_birdie:load-reverse-dsat-new-surveys:first-run-of-day"
    ),
    Dataset("bietlejuice.reverse_birdie:load-reverse-dsat-sum:first-run-of-day"),
]


def get_date_param(dag_run, default_date, date_param_name):
    """Read a date override from the DAG run conf, falling back to default_date.

    Identical logic to BaseWorkflow.get_date_param (see
    dag_builders/main_builder/workflows/base_workflow.py), which BaseWorkflow
    registers as a Jinja user_defined_macro for every DAG-Builder DAG. Since
    this DAG is hand-rolled and never goes through BaseWorkflow.dag_instance(),
    that auto-registration never happens here, so the macro is duplicated and
    registered manually below (same reason dags/growth/semrush/semrush.py
    defines its own get_toggle_param instead of relying on the builder).
    """
    date_param = dag_run.conf.get(date_param_name) if dag_run.conf else None
    if date_param and re.match(r"[0-9]{4}-[0-9]{2}-[0-9]{2}", date_param):
        return date_param
    return default_date


def active_prompts(manifest):
    """Return only the prompts flagged active=True in quintoml's manifest.

    Checks identity against True rather than bare truthiness: quintoml's
    write_manifest() always writes a real JSON boolean, but a hand-edited or
    malformed manifest could carry a truthy-but-wrong value (e.g. the string
    "false", itself truthy in Python) that must not be treated as active.
    """
    return [
        prompt for prompt in manifest.get("prompts", []) if prompt.get("active") is True
    ]


def backfill_day_range(today, backfill_days):
    """Inclusive day range [today - backfill_days, today]."""
    if backfill_days < 0:
        raise ValueError(f"backfill_days must be >= 0, got {backfill_days}")
    start = today - timedelta(days=backfill_days)
    return [start + timedelta(days=offset) for offset in range(backfill_days + 1)]


def success_marker_key(prompt_id, prompt_hash, day):
    """Build the _SUCCESS marker key for one (day, prompt_id, prompt_hash) partition.

    Mirrors quintoml's vocs_machina/storage.py build_partition_prefix +
    build_success_marker_uri byte-for-byte (zero-padded month/day), so this
    checks the exact key quintoml's classification job writes. Relative to
    DATA_SCIENCE_BUCKET (no bucket/scheme prefix) -- dag_inventory.py's own
    partition_path (non-zero-padded) is NOT used here on purpose, since that
    would look for the wrong key against quintoml's actual layout.
    """
    return (
        f"{VOCS_MACHINA_RAW_PREFIX}/"
        f"year={day.year}/month={day.month:02d}/day={day.day:02d}/"
        f"prompt_id={prompt_id}/prompt_hash={prompt_hash}/_SUCCESS"
    )


_UNSAFE_PARTITION_COMPONENT_RE = re.compile(r"[/\x00-\x1f]")


def _is_safe_partition_component(value):
    """True if value is safe to embed as a single S3 partition-key segment.

    Rejects a literal "/" (which would inject extra path segments into the
    year=/month=/day=/prompt_id=/prompt_hash=/ structure quintoml's own
    _HASH_KEY_RE parser expects) and control characters, including a null
    byte.
    """
    return isinstance(value, str) and not _UNSAFE_PARTITION_COMPONENT_RE.search(value)


def iter_partition_days(prompts, today):
    """Expand each active prompt into (day, prompt_id, prompt_hash) tuples, one
    per backfill day.

    A prompt missing "prompt_id"/"prompt_hash"/"backfill_days" (KeyError),
    carrying a negative backfill_days (ValueError, see backfill_day_range),
    or carrying a prompt_id/prompt_hash unsafe for an S3 partition key (see
    _is_safe_partition_component) is skipped with a warning rather than
    aborting the whole snapshot: one malformed manifest entry should not stop
    every other active prompt from being staged.

    De-duplicates by (day, prompt_id, prompt_hash): two manifest entries that
    describe the same partition (e.g. a duplicated entry, or two entries
    whose backfill windows overlap) must not produce the same row twice in
    the staged snapshot.
    """
    partition_days = []
    seen = set()
    for prompt in prompts:
        try:
            prompt_id = prompt["prompt_id"]
            prompt_hash = prompt["prompt_hash"]
            days = backfill_day_range(today, prompt["backfill_days"])
        except (KeyError, ValueError) as exc:
            logger.warning(
                f"m=iter_partition_days, prompt_id={prompt.get('prompt_id')}, "
                f"msg=Skipping prompt with missing/invalid required field: {exc}"
            )
            continue
        if not (
            _is_safe_partition_component(prompt_id)
            and _is_safe_partition_component(prompt_hash)
        ):
            logger.warning(
                f"m=iter_partition_days, prompt_id={prompt_id!r}, "
                f"msg=Skipping prompt with a prompt_id/prompt_hash unsafe for "
                f"S3 partition keys"
            )
            continue
        for day in days:
            key = (day, prompt_id, prompt_hash)
            if key in seen:
                continue
            seen.add(key)
            partition_days.append(key)
    return partition_days


def build_snapshot_rows(partition_days, existing_marker_keys):
    """Pure S3-key -> status mapping: "done" if the partition's _SUCCESS marker
    key is present in existing_marker_keys, "missing" otherwise.

    No I/O happens here -- the caller (stage_inference_status_to_s3) is
    responsible for populating existing_marker_keys via
    existing_marker_keys_for_days (batched S3Hook.list_keys, one call per
    unique backfill day). Keeping this function pure/isolated is what makes
    it trivially unit-testable (see test_vocs_machina_planning.py) without a
    live or mocked S3 connection.
    """
    rows = []
    for day, prompt_id, prompt_hash in partition_days:
        marker_key = success_marker_key(prompt_id, prompt_hash, day)
        status = "done" if marker_key in existing_marker_keys else "missing"
        rows.append(
            {
                "day": day.strftime(DATE_FMT),
                "prompt_id": prompt_id,
                "prompt_hash": prompt_hash,
                "inference_status": status,
            }
        )
    return rows


def existing_marker_keys_for_days(hook, days):
    """Batch-list every _SUCCESS marker that exists for a set of backfill days.

    Every prompt's marker for a given day lives under the same
    year=/month=/day=/ prefix (prompt_id=/prompt_hash= is nested underneath,
    see success_marker_key), so one S3Hook.list_keys call per unique day
    covers every active prompt that shares that day -- instead of one
    check_for_key HeadObject call per (day, prompt_id, prompt_hash) tuple,
    which for prompts with long, overlapping backfill windows can mean
    hundreds of sequential blocking calls to a cross-account bucket on a
    single run.
    """
    existing_keys = set()
    for day in days:
        prefix = (
            f"{VOCS_MACHINA_RAW_PREFIX}/"
            f"year={day.year}/month={day.month:02d}/day={day.day:02d}/"
        )
        keys = hook.list_keys(bucket_name=DATA_SCIENCE_BUCKET, prefix=prefix) or []
        existing_keys.update(key for key in keys if key.endswith("/_SUCCESS"))
    return existing_keys


def hash_snapshot_rows(rows: list) -> str:
    """MD5 hex digest of the snapshot rows, order-independent.

    Rows are sorted by (day, prompt_id, prompt_hash) before hashing so that
    incidental reordering of quintoml's manifest between two runs (same
    active prompts, same statuses, different JSON key order) does not make
    should_skip_stage_task() see a spurious "changed" snapshot.
    """
    canonical_rows = sorted(
        rows, key=lambda row: (row["day"], row["prompt_id"], row["prompt_hash"])
    )
    canonical_json = json.dumps(canonical_rows, sort_keys=True)
    return hashlib.md5(canonical_json.encode("utf-8")).hexdigest()


def should_skip_stage_task(
    triggering_dataset_events, previous_snapshot_hash, new_snapshot_hash
) -> bool:
    """Pure skip-vs-proceed decision for stage_inference_status_to_s3 (Slice 3).

    - If triggering_dataset_events is non-empty, one of the 14 upstream
      sources in FONTES fired: always proceed. New data from any of those
      sources is inherently actionable, no further comparison needed.
    - If triggering_dataset_events is empty, only the cron safety net fired:
      proceed only if the freshly computed snapshot differs from the last
      one this DAG published (previous_snapshot_hash); otherwise there is
      nothing new to propagate, so skip.

    :param triggering_dataset_events: the "triggering_dataset_events" Airflow
        context entry (a mapping; empty/falsy for a plain cron-triggered run).
    :param previous_snapshot_hash: hash_snapshot_rows() output from the last
        run that actually staged a snapshot (None if there isn't one yet).
    :param new_snapshot_hash: hash_snapshot_rows() output for this run.
    :return: True if the task (and everything downstream of it) should skip.
    """
    if triggering_dataset_events:
        return False
    return previous_snapshot_hash == new_snapshot_hash


def stage_inference_status_to_s3(load_start_date: str, **kwargs) -> None:
    """Task A: decide whether there's a new inference-status snapshot to load.

    1. Read quintoml's prompt manifest (read-only).
    2. For each active prompt, expand [today - backfill_days, today] into one
       (day, prompt_id, prompt_hash) tuple per day.
    3. Batch-list which of those partitions quintoml has already finalized
       (_SUCCESS marker present), one S3Hook.list_keys call per unique day
       shared across all active prompts (see existing_marker_keys_for_days).
    4. Selective propagation (Slice 3): decide via should_skip_stage_task()
       whether this run has anything new to publish; if not, raise
       AirflowSkipException so this task and everything downstream
       (execute-job-cluster, the raw load, and the enrich task group) is
       skipped instead of waking EMR for an unchanged cron tick. Otherwise,
       remember the new hash in LAST_SNAPSHOT_HASH_VARIABLE_KEY for the next
       run's comparison.

    Despite the task's name, this no longer writes anything to S3:
    airflow-prod-role has no write grant on this repo's own datalake bucket,
    and handing these rows over via XCom/job-parameters instead hit the
    10,000-byte parameter cap on Databricks' jobs/runs/submit, the API this
    DAG submitted Spark work through at the time (see bi-etl-ejuice#27353,
    reverted). The actual read + transform + load now happens independently
    in load_vocs_machina_inference_status_raw.py, on the EMR job cluster
    this DAG creates next -- its own instance profile reaches quintoml's
    manifest bucket directly, so it re-derives the same rows rather than
    receiving them from this task. This task's
    only remaining job is computing the same hash that job's output would
    produce, purely to decide skip vs proceed without paying for a cluster
    + Spark job on every unchanged cron tick.
    """
    hook = S3Hook(aws_conn_id="aws_default")

    manifest_content = hook.read_key(
        key=VOCS_MACHINA_MANIFEST_KEY, bucket_name=DATA_SCIENCE_BUCKET
    )
    manifest = json.loads(manifest_content)

    today = datetime.strptime(load_start_date, DATE_FMT).date()
    partition_days = iter_partition_days(active_prompts(manifest), today)

    unique_days = {day for day, _, _ in partition_days}
    existing_marker_keys = existing_marker_keys_for_days(hook, unique_days)

    rows = build_snapshot_rows(partition_days, existing_marker_keys)

    triggering_dataset_events = kwargs.get("triggering_dataset_events") or {}
    new_snapshot_hash = hash_snapshot_rows(rows)
    previous_snapshot_hash = Variable.get(
        LAST_SNAPSHOT_HASH_VARIABLE_KEY, default_var=None
    )
    if should_skip_stage_task(
        triggering_dataset_events, previous_snapshot_hash, new_snapshot_hash
    ):
        raise AirflowSkipException(
            "Cron-only trigger (no upstream dataset fired) and the "
            "inference-status snapshot is unchanged since the last "
            "published run; skipping this task and its downstream tasks."
        )

    Variable.set(LAST_SNAPSHOT_HASH_VARIABLE_KEY, new_snapshot_hash)


jiraops_callback = JiraOpsCallback()

config_service = ConfigurationService(SOURCE)
datalake_bucket = config_service.get_config("datalake_bucket")
doc_md_chart_url = config_service.get_config("doc_md_chart_url")
databricks_bietlejuice_repo_path = config_service.get_config(
    "databricks_bietlejuice_repo_path"
)
SPARK_JOBS_PATH = f"{databricks_bietlejuice_repo_path}/spark_jobs/{SOURCE}/"
# Generic load_table_full.py used by DatalakeTaskGroup for the SQL-driven
# enrich tables -- distinct from SPARK_JOBS_PATH above, which points at this
# DAG's own custom raw-loader job. Same "spark_jobs/base/" path
# dags/fintech/enrich_dai_report/enrich_dai_report.py uses for the same
# purpose.
ENRICH_SPARK_JOBS_PATH = f"{databricks_bietlejuice_repo_path}/spark_jobs/base/"

dag = DAG(
    dag_id=DAG_ID,
    default_args={
        "owner": DAGOwnerEnum.DATA_FOR_RENT,
        "wait_for_downstream": False,
        "depends_on_past": False,
        "on_failure_callback": jiraops_callback.task_failure_alert,
    },
    start_date=MAIN_START_DATE,
    # Hybrid schedule (Slice 3): triggered by any of the 14 FONTES datasets,
    # OR by a 6-hour cron safety net -- whichever comes first. max_active_runs
    # caps concurrency at 1 so a dataset event and a cron tick can't overlap.
    schedule=DatasetOrTimeSchedule(
        timetable=CronTriggerTimetable("0 */6 * * *", timezone=LOCAL_TZ),
        datasets=reduce(or_, FONTES),
    ),
    max_active_runs=1,
    doc_md=BaseDAG.get_dag_doc(SOURCE).format(
        chart_url=doc_md_chart_url, dag_id=DAG_ID
    ),
    user_defined_macros={"get_date_param": get_date_param},
    params=BaseDAG.get_default_trigger_form_params(),
)

# Cluster shape lives in vocs_machina_planning_cluster.yml rather than inline
# here, the same convention the DAG Builder uses for a declaration's
# `cluster:` block -- attach_job_cluster_engine_to_context reads its `type`
# to pick the EMR engine and resolve the cluster template.
_cluster_file_path = DAGPackagesPathService.resolve_artifact_file_path(
    artifact_type="dag_cluster", dag_name=SOURCE
)
CLUSTER_ARGS = FileService.get_dict_from_yaml_file(_cluster_file_path)["cluster"]

dag_execution_context = DagExecutionContext(
    dag=dag,
    environment=ENV,
    bucket=datalake_bucket,
    base_spark_jobs_path=databricks_bietlejuice_repo_path,
    dag_args={},
    workflow_args={},
    cluster_args=CLUSTER_ARGS,
)
attach_job_cluster_engine_to_context(dag_execution_context, config_service)

stage_inference_status_task = PythonOperator(
    dag=dag,
    task_id="stage-inference-status-to-s3",
    python_callable=stage_inference_status_to_s3,
    op_kwargs={
        "load_start_date": "{{ get_date_param(dag_run, data_interval_start | ds, 'load_start_date') }}",
    },
    provide_context=True,
)

# Must be built before any Spark task: creating it is what records the
# cluster's task id on dag_execution_context, which every later
# create_spark_python_task call reads to point its step at this cluster.
execute_job_cluster_task = (
    dag_execution_context.job_cluster_engine.create_execute_cluster_task(
        config_service=config_service,
        minimum_cluster_runtime_version=None,
        execute_job_cluster_local_id=None,
    )
)

load_inference_status_raw_task = dag_execution_context.job_cluster_engine.create_spark_python_task(
    spark_job_path=f"{SPARK_JOBS_PATH}load_vocs_machina_inference_status_raw.py",
    task_id="load-vocs-machina-inference-status-raw",
    job_parameters=[
        ENV,
        datalake_bucket,
        SOURCE,
        RAW_TABLE_NAME,
        "{{ get_date_param(dag_run, data_interval_start | ds, 'load_start_date') }}",
        RAW_PARTITION_COLS,
    ],
    execution_timeout_hours=2,
)

terminate_task = (
    dag_execution_context.job_cluster_engine.create_emr_terminate_cluster_task(
        execute_cluster_task_id=execute_job_cluster_task.task_id,
        terminate_task_local_suffix=None,
    )
)
# NONE_SKIPPED, overriding the all_done create_emr_terminate_cluster_task
# hardcodes: if load-vocs-machina-inference-status-raw fails after
# execute-job-cluster succeeded, the cluster must still be torn down instead
# of leaking until its idle timeout (a failure leaves downstream tasks
# upstream_failed, not skipped, so NONE_SKIPPED still fires). But all_done
# also treats "skipped" as "done", which would run this task on Slice 3's
# selective-propagation path (see should_skip_stage_task) -- there the skip
# of stage-inference-status-to-s3 cascades through execute-job-cluster, so
# there is no cluster to terminate and no job_flow_id in XCom to pull.
#
# Dropping this line does NOT page anyone: every unchanged 6-hourly cron
# tick would just fail silently. This DAG is muted twice over in
# packages/bietlejuice-compiler/scripts/jiraops/jiraops_mute_list.yml --
# once by DAG (`bietlejuice.vocs_machina_planning`, line 45) and again by
# task (`bietlejuice.*:terminate-emr-cluster`, line 55) -- so
# jiraops_callback.task_failure_alert opens no incident. That makes the
# failure mode worse than a noisy one, not better: red task instances would
# accumulate four times a day on the DAG's happiest path with nobody
# finding out, and the first person to notice would be whoever eventually
# wonders why the run history is red. Keep this override.
terminate_task.trigger_rule = TriggerRule.NONE_SKIPPED

datalake_task_group = DatalakeTaskGroup(
    dag=dag,
    env=ENV,
    datalake_bucket=datalake_bucket,
    relative_query_path=SOURCE,
    spark_jobs_path=ENRICH_SPARK_JOBS_PATH,
    job_cluster_engine=dag_execution_context.job_cluster_engine,
)

# Materializes both queries/enrich/*.sql files (Slice 2) as real Delta
# tables. Every load task DatalakeTaskGroup builds for the enrich layer gets
# a dataset outlet attached automatically (DatalakeTaskGroup._build_load_task
# calls DatasetAdder.attach_dataset_to_task unconditionally unless
# is_validation=True, which we don't set here) -- so
# vocs_machina_backfill_status_summary's load task emits the dataset
# quintoml's Slice 4 subscribes to (see task_id below) with NO extra call
# needed. This also means vocs_machina_backfill_status's own load task emits
# an outlet too; that's harmless since nothing subscribes to it.
enrich_task_groups = datalake_task_group.build_task_group_from_sql_files(
    layer=LayerEnum.ENRICH,
    source_database_base_name=SOURCE,
    target_database_base_name=SOURCE,
)

# vocs_machina_backfill_status_summary.sql SELECTs FROM
# datalake_vocs_machina_planning.vocs_machina_backfill_status (Slice 2), so
# the summary table's load task must run strictly after the detail table's
# is fully loaded (and its metadata synced) -- DatalakeTaskGroup gives each
# table its own independent task group with no ordering between them, so
# this inner dependency is wired explicitly, same pattern as
# dags/growth/enrich_growth_costs_sharing_rules/enrich_growth_costs_sharing_rules.py.
(
    enrich_task_groups_without_inner_dependencies,
    enrich_inner_dependencies_boundaries,
) = datalake_task_group.set_inner_dag_dependencies(
    task_flow_helper=TaskFlowHelper(),
    task_groups_boundaries=enrich_task_groups,
    dag_inner_dependencies={BACKFILL_STATUS_SUMMARY_TABLE: [BACKFILL_STATUS_TABLE]},
)

chain(
    stage_inference_status_task,
    execute_job_cluster_task,
    load_inference_status_raw_task,
)

chain(
    load_inference_status_raw_task,
    datalake_task_group.all_first_tasks(enrich_task_groups_without_inner_dependencies)
    + datalake_task_group.first_tasks(enrich_inner_dependencies_boundaries),
)

chain(
    datalake_task_group.all_last_tasks(enrich_task_groups_without_inner_dependencies)
    + datalake_task_group.last_tasks(enrich_inner_dependencies_boundaries),
    terminate_task,
)
