SELECT
    id,
    cpf,
    dataExpedicaoRG AS dt_rg_created,
    dataNascimento AS dt_birth,
    email,
    nome AS name,
    rg,
    sexo AS gender,
    telefone AS phone_number,
    telefoneSecundario AS secondary_phone,
    contrato_id AS id_contract,
    bairro AS neighborhood,
    cep AS zip_code,
    cidade AS city,
    complemento AS complement,
    endereco AS address,
    estadoCivil AS marital_status,
    numero AS number,
    orgaoExpedidor AS issuing_body,
    profissao AS profession,
    estado_id AS state_id,
    tipo AS type,
    nacionalidade AS nationality,
    atualizadoEm AS ts_updated,
    criadoEm AS ts_created,
    usuario_id AS id_user,
    vaiMorar AS will_live,
    legalRepresentative_cpf AS legal_representative_cpf,
    legalRepresentative_email AS legal_representative_email,
    legalRepresentative_nome AS legal_representative_name,
    legalRepresentative_rg AS legal_representative_rg,
    withRepresentative AS is_with_representative
FROM
    datalake_ebdb_raw.contratopessoa