SELECT
    id,
    atualizadoEm AS ts_updated,
    criadoEm AS ts_created,
    currentCondoFee AS current_condo_fee,
    currentIptuTwelth AS current_iptu_twelth,
    currentRent AS current_rent,
    houseAddress_bairro AS house_address_neighborhood,
    houseAddress_cep AS house_address_zipcode,
    houseAddress_cidade AS house_address_city,
    houseAddress_complemento AS house_address_complement,
    houseAddress_logradouro AS house_address_street,
    houseAddress_numero AS house_address_number,
    houseType AS house_type,
    lat,
    lng,
    ownerData_email AS owner_data_email,
    ownerData_gender AS owner_data_gender,
    ownerData_name AS owner_data_name,
    ownerData_phoneNumber AS owner_data_phone_number,
    status,
    tenantData_email AS tenant_data_email,
    tenantData_gender AS tenant_data_gender,
    tenantData_name AS tenant_data_name,
    tenantData_phoneNumber AS tenant_data_phone_number,
    flow_id AS id_flow,
    house_id AS id_house,
    houseAddress_estado_id AS id_state,
    region_id AS id_region,
    tenant_id AS id_tenant,
    contractFinalDate AS dt_contract_ended,
    contractObservations AS contract_observations,
    contractStartDate AS dt_contract_started,
    ownerType AS owner_type
FROM
    datalake_ebdb_raw.Portability
