DROP TABLE IF EXISTS datalake_clean.potential_listings_temp;
CREATE EXTERNAL TABLE IF NOT EXISTS datalake_clean.potential_listings_temp (
 id BIGINT,
 ref_date TIMESTAMP,
 created_date TIMESTAMP,
 updated_date TIMESTAMP,
 attribution_id INT,
 attribution_uuid STRING,
 contact_date TIMESTAMP,
 lead_and_prospect_date TIMESTAMP,
 first_inside_sales_contact_date TIMESTAMP,
 qualified_date TIMESTAMP,
 opportunity_date TIMESTAMP,
 listing_publication_date TIMESTAMP,
 contract_date TIMESTAMP,
 lead_id INT,
 property_id INT,
 contract_id INT,
 renting_value INT,
 current_property_status STRING,
 dados_fotografo_id INT,
 owner_id INT,
 rep_id INT,
 manager_id INT,
 vendedor_id INT,
 tipo_admin STRING,
 imovel_attribution STRING,
 lead_tipo STRING,
 affiliate_listing_value DECIMAL(12,4),
 affiliate_renting_value DECIMAL(12,4),
 cac_affiliate DECIMAL(12,4),
 cac_marketing DECIMAL(12,4),
 cac_photo DECIMAL(12,4),
 cac_inside_sales DECIMAL(12,4),
 contact_to_lead_diff_minutes INT,
 lead_and_prospect_to_qualified_diff_minutes INT,
 qualified_to_opportunity_diff_minutes INT,
 opportunity_to_listing_diff_minutes INT,
 listing_to_1stcontract_diff_minutes INT,
 contact_to_listing_diff_minutes INT,
 contact_to_1stcontract_diff_minutes INT
) ROW FORMAT DELIMITED
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n'
LOCATION 's3://5a-datalake/clean/potential_listings_temp'
;