SELECT
    id,
    acquireId as id_acquire, 
    customerId as id_customer,
    store_id as id_store,
    externalId as id_external,
    acquireTid as id_acquire_transaction,
    businessEntityId as id_business_entity,
    financeEntityId as id_finance_entity,
    creditCardId as id_credit_card,
    acquire,
    chargeStatus AS charge_status,
    chargeHistory AS charge_history,
    code,
    riskEntities AS risk_entities,
    payerName AS payer_name,
    payerDocumentNumber AS payer_document_number,
    acquireChargeStatus AS acquire_charge_status,
    installments,
    acquireAuthCode AS acquire_auth_code,
    acquireNsu AS acquire_nsu,
    invoiceMessage AS invoice_message,
    acquireName AS acquire_name,
    acquireMessage AS acquire_message,
    acquireReturnCode AS acquire_return_code,
    cardBrand AS card_brand,
    firstSixDigitsCard AS first_six_digits_card,
    lastFourDigitsCard AS last_four_digits_cards,
    acquireFeePercentage AS acquire_fee_percentage,
    amount,
    refundAmount AS refund_amount,
    paidAt AS ts_paid,
    lastUpdate AS ts_updated
FROM
    datalake_wall_street_raw.charge
