SELECT
    id,
    acquireId AS id_acquire,
    customerId AS id_customer,
    store_id AS id_store,
    externalId AS id_external,
    acquireTid AS id_acquire_transaction,
    businessEntityId AS id_business_entity,
    financeEntityId AS id_finance_entity,
    creditCardId AS id_credit_card,
    acquire,
    chargeStatus AS charge_status,
    chargeHistory AS charge_history,
    code,
    amount,
    CAST(paidAt AS TIMESTAMP) AS ts_paid,
    riskEntities AS risk_entities,
    payerName AS payer_name,
    payerDocumentNumber AS payer_document_number,
    acquireChargeStatus AS acquire_charge_status,
    installments,
    acquireAuthCode AS acquire_auth_code,
    acquireNsu AS acquire_nsu,
    acquireTid AS acquire_tid,
    invoiceMessage AS invoice_message,
    refundAmount AS refund_amount,
    acquireName AS acquire_name,
    acquireMessage AS acquire_message,
    acquireReturnCode AS acquire_return_code,
    cardBrand AS card_brand,
    firstSixDigitsCard AS first_six_digits_card,
    lastFourDigitsCard AS last_four_digits_cards,
    acquireFeePercentage AS acquire_fee_percentage,
    CAST(lastUpdate AS TIMESTAMP) AS ts_updated
FROM
    datalake_wall_street_raw.charge
