select
    id,
    acquireId as id_acquire, 
    customerId as id_customer,
    store_id as id_store,
    externalId as id_external,
    acquireTid as id_acquire_transaction,
    businessentityid as id_business_entity,
    financeentityid as id_finance_entity,
    creditcardid as id_credit_card,
    code,
    acquireAuthCode as acquire_auth_code,
    acquireNsu as acquire_nsu,
    acquire, 
    acquirename as acquire_name,
    cardbrand as card_brand,
    acquirefeepercentage as acquire_fee_percentage,
    payername as payer_name,
    payerdocumentnumber as payer_document_number,
    chargeStatus as charge_status,
    acquireChargeStatus as acquire_charge_status,
    invoicemessage as invoice_message,
    installments, 
    amount, 
    refundamount as refund_amount,
    paidat as ts_paid,
    lastUpdate as ts_updated
from 
    datalake_wall_street_raw.charge