SELECT
    id,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    propose AS id_propose,
    propose_mod AS mod_id_propose,
    unicid,
    unicid_mod AS mod_unicid,
    version,
    value,
    value_mod AS mod_value,
    net_value,
    net_value_mod AS mod_net_value,
    fine_value,
    fine_value_mod AS mod_fine_value,
    interest_value,
    interest_value_mod AS mod_interest_value,
    billing_type,
    billing_type_mod AS mod_billing_type,
    status,
    status_mod AS mod_status,
    invoice_url,
    invoice_url_mod AS mod_invoice_url,
    payment_link,
    payment_link_mod AS mod_payment_link,
    description,
    description_mod AS mod_description,
    raw_response AS json_raw_response,
    raw_response_mod AS mod_json_raw_response,
    due_date AS dt_due,
    due_date_mod AS mod_dt_due,
    original_due_date AS dt_due_original,
    original_due_date_mod AS mod_dt_due_original,
    client_payment_date AS dt_client_payment,
    client_payment_date_mod AS mod_dt_client_payment,
    confirmed_payment_date AS dt_confirmed_payment,
    confirmed_payment_date_mod AS mod_dt_confirmed_payment,
    created_at AS ts_created,
    year,
    month,
    day
FROM
    datalake_rental_guarantee_platform_raw.agreement_payment_legacy_aud
