SELECT
    id,
    userinsert AS id_user_insert,
    userupdate AS id_user_update,
    propose AS id_propose,
    company_plan AS id_company_plan,
    maintenant AS id_main_tenant,
    realestate AS id_real_estate,
    realtor AS id_realtor,
    status,
    financial_status,
    activator,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    current_payment_method,
    start_billing_after_mod AS mod_start_billing_after,
    realtor_mod AS mod_realtor,
    realestate_mod AS mod_real_estate,
    propose_mod AS mod_propose,
    next_renewal_date_mod AS mod_dt_next_renewal,
    maintenant_mod AS mod_maintenant,
    financial_status_mod AS mod_financial_status,
    done_mod AS mod_done,
    delinquent_mod AS mod_delinquent,
    current_payment_method_mod AS mod_current_payment_method,
    company_plan_mod AS mod_company_plan,
    begin_mod AS mod_begin,
    bad_debt_at_mod AS mod_ts_bad_debt_at,
    active_mod AS mod_active,
    activator_mod AS mod_activator,
    active AS is_active,
    delinquent AS is_delinquent,
    next_renewal_date AS dt_next_renewal,
    start_billing_after AS dt_start_billing_after,
    begin AS ts_began,
    done AS ts_done,
    bad_debt_at AS ts_bad_debt_at,
    dateinsert AS ts_inserted,
    dateupdate AS ts_updated
FROM
    datalake_rental_guarantee_platform_raw.contract_aud
