SELECT
    CAST(id AS BIGINT) AS id,
    CAST(propose AS BIGINT) AS id_propose,
    propose_mod AS mod_id_propose,
    status AS id_status,
    status_mod AS mod_id_status,
    type AS id_type,
    type_mod AS mod_id_type,
    userinsert AS id_user_insert,
    userupdate AS id_user_update,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    subcategory,
    subcategory_mod AS mod_subcategory,
    value,
    value_mod AS mod_value,
    original_value,
    original_value_mod AS mod_original_value,
    amount_paid,
    amount_paid AS mod_amount_paid,
    boleto_value AS bill_value,
    boleto_value_mod AS mod_bill_value,
    active AS is_active,
    active_mod AS mod_is_active,
    valid AS is_valid,
    valid_mod AS mod_is_valid,
    legacy_agreement AS is_legacy_agreement,
    legacy_agreement_mod AS mod_is_legacy_agreement,
    due_date AS dt_due,
    due_date_mod AS mod_dt_due,
    boleto_month AS dt_bill_month,
    boleto_month_mod AS mod_dt_bill_month,
    payment_date AS dt_paid,
    payment_date_mod AS mod_dt_paid,
    schedule_payment_date AS dt_payment_scheduled,
    schedule_payment_date_mod AS mod_dt_payment_scheduled,
    created_at AS ts_created
FROM
    datalake_rental_guarantee_platform_raw.delinquency_aud
