SELECT
    id,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    user_id AS id_user,
    user_id_mod AS mod_id_user,
    external_id AS id_external,
    external_id_mod AS mod_id_external,
    source_id AS id_source,
    source_id_mod AS mod_id_source,
    payment_type,
    payment_type_mod AS mod_payment_type,
    paid_value,
    paid_value_mod AS mod_paid_value,
    payment_request_id AS id_payment_request,
    payment_request_id_mod AS mod_id_payment_request,
    status,
    status_mod AS mod_status,
    raw_request,
    raw_request_mod AS mod_raw_request,
    raw_response,
    raw_response_mod AS mod_raw_response,
    next_attempt_id AS id_next_attempt,
    next_attempt_id_mod AS mod_id_next_attempt,
    propose_id AS id_propose,
    propose_id_mod AS mod_id_propose,
    event_date AS dt_event,
    event_date_mod AS mod_dt_event,
    payment_schedule_date AS dt_payment_scheduled,
    payment_schedule_date_mod AS mod_dt_payment_scheduled,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_rental_guarantee_platform_raw.lannister_payment_register_aud
