SELECT
    id,
    legacy_id           AS id_legacy,
    userinsert          AS id_user_insert,
    userupdate          AS id_user_update,
    type                AS id_type,
    rev,
    revtype             AS rev_type,
    revend              AS rev_end,
    name,
    name_mod            AS mod_name,
    type_mod            AS mod_type,
    pricing_mod         AS mod_pricing,
    coverage_mod        AS mod_coverage,
    damage_mod          AS mod_damage,
    commission_mod      AS mod_commission,
    userinsert_mod      AS mod_user_insert,
    userupdate_mod      AS mod_user_update,
    dateinsert_mod      AS mod_date_insert,
    dateupdate_mod      AS mod_date_update,
    legacy_id_mod       AS mod_legacy_id,
    active_mod          AS mod_active,
    active              AS is_active,
    CAST(pricing AS NUMERIC(7,4))       AS pricing,
    coverage,
    damage,
    CAST(commission AS NUMERIC(7,4))    AS commission,
    created_at          AS ts_created,
    dateinsert          AS ts_inserted,
    dateupdate          AS ts_updated

FROM
    datalake_rental_guarantee_platform_raw.plan_aud
