SELECT
    id,
    userinsert AS id_user_insert,
    userupdate AS id_user_update,
    type AS id_business_type,
    status AS id_propose_status,
    realestate AS id_real_estate,
    company_plan AS id_company_plan,
    tenant_company AS id_tenant_company,
    realtor AS id_realtor,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    activator AS activator_value,
    billing_model,
    `hash`,
    externalref AS external_ref,
    agent_split_fee,
    activator_mod,
    agent_split_fee_mod,
    billing_model_mod,
    externalref_mod AS external_ref_mod,
    hash_mod,
    realestate_mod AS id_real_estate_mod,
    realtor AS id_realtor_mod,
    company_plan_mod AS id_company_plan_mod,
    credit_analysis_entities_mod,
    tenant_company_mod AS id_tenant_company_mod,
    contract_mod AS id_contract_mod,
    annual_value,
    annual_value_mod,
    monthly_value,
    monthly_value_mod,
    total_coverage,
    total_coverage_mod,
    active AS is_active,
    dateinsert AS ts_inserted
FROM
    datalake_rental_guarantee_platform_raw.propose_aud
