SELECT
    id,
    rev,
    revend                          AS rev_end,
    revtype                         AS rev_type,
    version,
    propose,
    price_index,
    price_index_type,
    step,
    cycle,
    previous_monthly_amount,
    updated_monthly_amount,
    previous_monthly_amount_mod     AS mod_previous_monthly_amount,
    updated_monthly_amount_mod      AS mod_updated_monthly_amount,
    due_date_mod                    AS mod_due_date,
    paid_date_mod                   AS mod_paid_date,
    price_index_mod                 AS mod_price_index,
    price_index_type_mod            AS mod_price_index_type,
    cycle_mod                       AS mod_cycle,
    step_mod                        AS mod_step,
    paid_date                       AS dt_paid,
    due_date                        AS dt_due,
    created_at                      AS ts_created,
    year,
    month,
    day
FROM
    datalake_rental_guarantee_platform_raw.renewal_aud
