SELECT
  id,
  related_document_id AS id_related_document,
  payment_boleto_id AS id_payment_boleto,
  file_id AS id_file,
  bank_payment_id AS id_bank_payment,
  company_use,
  our_number,
  bank_payment_code,
  barcode,
  original_response,
  CAST(paid_amount AS DOUBLE) AS paid_amount,
  occurrence_code,
  occurrence_reason,
  payee_name,
  related_document_status,
  related_document_type,
  requested_by,
  status,
  style,
  type,
  TIMESTAMP(created_at) AS ts_created,
  TIMESTAMP(created_at_payment_boleto) AS ts_created_at_payment_boleto,
  DATE(paid_at) AS dt_paid,
  TIMESTAMP(updated_at) AS ts_updated,
  year,
  month,
  day,
  hour
FROM
  datalake_vans_homolog_raw.paymentboleto_status_log
