"""Migration Twin DAG — run original queries on Databricks, capture metrics to S3.

Auto-generated by emr-migration-v2 skill.
Run ID: 03c62042-3e72-4dee-a98b-735452df845f
Scope: house_and_listing/enrich_sale_stranded_listings_status
"""

import os
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import urlparse

import yaml
from airflow import DAG, Dataset
from airflow.operators.python import PythonOperator

from bietlejuice.base.airflow.job_cluster_engine import (
    attach_emr_job_cluster_finished_work_prerequisites,
    attach_emr_terminate_cluster_work_prerequisites,
    attach_job_cluster_engine_to_context,
    get_job_cluster_completion_sink,
)
from bietlejuice.base.airflow.task_creators.dag_execution_context import (
    DagExecutionContext,
)
from bietlejuice.services.configuration_service import ConfigurationService

DAG_ID = "migration_twin_house_and_listing__enrich_sale_stranded_listings_status"
RUN_ID = "03c62042-3e72-4dee-a98b-735452df845f"
DOMAIN = "house_and_listing"
SOURCE_DAG_NAME = "enrich_sale_stranded_listings_status"
DATASET_URI = (
    "migration:twin-house_and_listing__enrich_sale_stranded_listings_status-complete"
)
RUN_PREFIX = "emr-migration/runs/03c62042-3e72-4dee-a98b-735452df845f"
RUNTIME = "twin"
SQL_DIR_NAME = "enrich"

TABLES = [
    "stranded_status",
]

DAG_DIR = Path(__file__).resolve().parent
ENV = os.environ.get("ENVIRONMENT")
CONFIG_SERVICE = ConfigurationService(SOURCE_DAG_NAME)
BUCKET = CONFIG_SERVICE.get_config("datalake_bucket")
BIETLEJUICE_REPO_PATH = CONFIG_SERVICE.get_config("databricks_bietlejuice_repo_path")
METRIC_CAPTURE_JOB = (
    f"{BIETLEJUICE_REPO_PATH}/spark_jobs/migration_assets/metric_capture_job.py"
)
ARTIFACTS_URI = CONFIG_SERVICE.get_config("artifacts_bucket")
ARTIFACTS_BUCKET = urlparse(ARTIFACTS_URI).netloc or ARTIFACTS_URI

with open(DAG_DIR / f"{DAG_ID}_cluster.yml") as _f:
    CLUSTER_ARGS = yaml.safe_load(_f).get("cluster", {})


def _build_context(dag):
    ctx = DagExecutionContext(
        dag=dag,
        environment=ENV,
        bucket=BUCKET,
        base_spark_jobs_path=f"{BIETLEJUICE_REPO_PATH}/spark_jobs/base/",
        dag_args={},
        workflow_args={},
        cluster_args=CLUSTER_ARGS,
        databricks_conn_id=CLUSTER_ARGS.get("databricks_conn_id", "databricks_new_env"),
    )
    attach_job_cluster_engine_to_context(ctx, CONFIG_SERVICE)
    return ctx


def _get_s3_client():
    import boto3
    from airflow.models import Variable

    role_arn = Variable.get("DATASET_EVENTS_ASSUME_ROLE_ARN", default_var=None)
    if not role_arn:
        return boto3.client("s3")
    sts = boto3.client("sts")
    creds = sts.assume_role(
        RoleArn=role_arn,
        RoleSessionName="migration-s3-upload",
        DurationSeconds=3600,
    )["Credentials"]
    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
    ).client("s3")


def _upload_sql(**context):
    sql_dir = DAG_DIR / "queries" / SQL_DIR_NAME
    s3 = _get_s3_client()
    for table in TABLES:
        local_path = str(sql_dir / f"{table}.sql")
        s3_key = f"{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}.sql"
        s3.upload_file(local_path, ARTIFACTS_BUCKET, s3_key)


with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["migration", "twin", "validation"],
    default_args={"owner": "data-platform", "retries": 0},
    dagrun_timeout=timedelta(hours=4),
) as dag:
    ctx = _build_context(dag)

    upload_sql = PythonOperator(
        task_id="upload_sql",
        python_callable=_upload_sql,
    )

    end = PythonOperator(
        task_id="end",
        python_callable=lambda **kw: None,
        outlets=[Dataset(DATASET_URI)],
    )

    MAX_TASKS_PER_CLUSTER = 100
    batches = [
        TABLES[i : i + MAX_TASKS_PER_CLUSTER]
        for i in range(0, len(TABLES), MAX_TASKS_PER_CLUSTER)
    ]

    for batch_idx, batch_tables in enumerate(batches):
        local_id = None if batch_idx == 0 else batch_idx + 1

        batch_execute = ctx.job_cluster_engine.create_execute_cluster_task(
            config_service=CONFIG_SERVICE,
            minimum_cluster_runtime_version=None,
            execute_job_cluster_local_id=local_id,
        )

        batch_captures = []
        for table in batch_tables:
            batch_captures.append(
                ctx.job_cluster_engine.create_spark_python_task(
                    spark_job_path=METRIC_CAPTURE_JOB,
                    task_id=f"capture_{table}",
                    job_parameters=[
                        "--sql-s3-uri",
                        f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}",
                        "--result-s3-uri",
                        f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}",
                        "--run-id",
                        RUN_ID,
                        "--runtime",
                        "databricks",
                        "--domain",
                        DOMAIN,
                        "--dag-name",
                        SOURCE_DAG_NAME,
                        "--table-name",
                        table,
                    ],
                    execution_timeout_hours=2,
                )
            )

        batch_completion = get_job_cluster_completion_sink(
            ctx, batch_execute, end, local_id
        )
        attach_emr_job_cluster_finished_work_prerequisites(
            ctx, job_cluster_finished_task=end, work_completion_tasks=batch_captures
        )

        upload_sql >> batch_execute >> batch_captures >> batch_completion
        attach_emr_terminate_cluster_work_prerequisites(
            ctx,
            batch_completion,
            execute_job_cluster_task=batch_execute,
            job_cluster_finished_task=end,
        )
