SELECT
    id_listing_owner AS sk_listing_owner,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_first_listing_registered, 1, 10),'-','') AS INTEGER), -1) AS sk_first_listing_registered_date,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_first_booking, 1, 10),'-','') AS INTEGER), -1) AS sk_first_booking_date,
    COALESCE(CAST(REPLACE(SUBSTRING(dt_first_visited, 1, 10),'-','') AS INTEGER), -1) AS sk_first_visit_date,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_first_offer_received, 1, 10),'-','') AS INTEGER), -1) AS sk_first_offer_received_date,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_first_offer_accepted, 1, 10),'-','') AS INTEGER), -1) AS sk_first_offer_accepted_date,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_first_contract_signed, 1, 10),'-','') AS INTEGER), -1) AS sk_first_contract_signed_date,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_last_listing_registered, 1, 10),'-','') AS INTEGER), -1) AS sk_last_listing_registered_date,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_last_booking, 1, 10),'-','') AS INTEGER), -1) AS sk_last_booking_date,
    COALESCE(CAST(REPLACE(SUBSTRING(dt_last_visited, 1, 10),'-','') AS INTEGER), -1) AS sk_last_visit_date,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_last_offer_received, 1, 10),'-','') AS INTEGER), -1) AS sk_last_offer_received_date,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_last_offer_accepted, 1, 10),'-','') AS INTEGER), -1) AS sk_last_offer_accepted_date,
    COALESCE(CAST(REPLACE(SUBSTRING(ts_last_contract_signed, 1, 10),'-','') AS INTEGER), -1) AS sk_last_contract_signed_date,
    properties_registered,
    listings_published,
    visits_booked,
    visits_received,
    visits_expected_to_happen,
    visits_cancelled,
    offers_received,
    offers_rejected,
    offers_negotiating,
    offers_accepted,
    proposals_rejected,
    proposals_approved,
    reservations_received,
    contracts_cancelled,
    contracts_to_be_signed,
    contracts_signed,
    contracts_annuled,
    ongoing_listings,
    ongoing_contracts,
    NOW() AS ts_load
FROM
    datalake_listing_owners.rental_metrics
