SELECT
    id_amplitude,
    id_app,
    id_device,
    id_event,
    id_session,
    id_user,
    id_inserted,
    city,
    country,
    data,
    device_family,
    device_type,
    event_type,
    event_properties,
    GET_JSON_OBJECT(event_properties, '$.product') AS product,
    GET_JSON_OBJECT(event_properties, '$.characteristics_count') AS characteristics_count,
    GET_JSON_OBJECT(event_properties, '$.city') AS city_search,
    GET_JSON_OBJECT(event_properties, '$.matchType') AS match_type,
    GET_JSON_OBJECT(event_properties, '$.latitude') AS latitude,
    GET_JSON_OBJECT(event_properties, '$.longitude') AS longitude,
    GET_JSON_OBJECT(event_properties, '$.business_context') AS business_context,
    GET_JSON_OBJECT(event_properties, '$.complement') AS complement,
    GET_JSON_OBJECT(event_properties, '$.neighborhood') AS neighborhood,
    GET_JSON_OBJECT(event_properties, '$.dejavuid_count') AS dejavuid_count,
    GET_JSON_OBJECT(event_properties, '$.street') AS street,
    GET_JSON_OBJECT(event_properties, '$.complement_type') AS complement_type,
    GET_JSON_OBJECT(event_properties, '$.dejavuid_list') AS dejavuid_list,
    GET_JSON_OBJECT(event_properties, '$.number') AS number,
    GET_JSON_OBJECT(event_properties, '$.dejavuid_match') AS dejavuid_match,
    GET_JSON_OBJECT(event_properties, '$.lead_id') AS lead_id,
    GET_JSON_OBJECT(event_properties, '$.login_status') AS login_status,
    ip_address,
    os_name,
    os_version,
    platform,
    library,
    region,
    start_version,
    user_properties,
    language,
    uuid,
    version_name,
    ts_event,
    ts_server_received,
    ts_server_uploaded,
    ts_processed,
    ts_client_event,
    ts_client_uploaded,
    year,
    month,
    day
FROM
    datalake_amplitude_clean.events
WHERE
    id_app = '183047' AND event_type = 'atlas_db_address_search'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'