SELECT
    id_payment AS sk_payment,
    id_propose AS sk_propose,
    COALESCE(id_propose_values, -1) AS sk_propose_values,
    COALESCE(id_billing_type, -1) AS sk_billing_type,
    COALESCE(id_payment_type, -1) AS sk_payment_type,
    COALESCE(id_status, -1) AS sk_status,
    COALESCE(id_payment_gateway, -1) AS sk_payment_gateway,
    id_customer,
    id_unicid,
    id_subscription,
    invoice_url,
    description,
    due_amount,
    net_amount,
    takerate_amount,
    is_paid_late,
    is_due_modified,
    is_occurrence,
    dt_created,
    dt_due,
    dt_due_original,
    dt_paid,
    dt_payment_confirmed,
    ts_updated,
    NOW() AS ts_load
FROM
    datalake_velo.payment
