SELECT
    id_propose AS sk_propose,
    id_propose_values AS sk_propose_values,
    id_broker AS sk_broker,
    id_house AS sk_house,
    id_propose_company AS sk_propose_company,
    id_agent AS sk_agent,
    id_contract AS sk_contract,
    id_primary_person AS sk_primary_person,
    id_origin AS sk_origin,
    id_propose_status AS sk_propose_status,
    id_guarantee_status AS sk_guarantee_status,
    id_propose_type AS sk_propose_type,
    count_persons_included,
    percentage_income_from_primary_person,
    avg_serasa_score,
    avg_risk_score,
    avg_declared_income,
    is_contract,
    dt_contract_started,
    dt_ended,
    dt_propose_started,
    dt_waiting_new_docs,
    dt_evaluation_started,
    dt_rejected,
    dt_sign_started,
    dt_paid,
    dt_activation,
    dt_secured,
    dt_activation_analysis,
    dt_secure_pending,
    NOW() AS ts_load
FROM
    datalake_velo.propose
