SELECT
    id_propose AS sk_propose,
    COALESCE(CAST(id_propose_values AS BIGINT), -1) AS sk_propose_values,
    COALESCE(id_broker, -1) AS sk_broker,
    COALESCE(id_house, -1) AS sk_house,
    COALESCE(id_propose_company, -1) AS sk_propose_company,
    COALESCE(id_agent, -1) AS sk_agent,
    COALESCE(id_primary_person, -1) AS sk_primary_person,
    COALESCE(id_origin, -1) AS sk_origin,
    COALESCE(id_propose_status, -1) AS sk_propose_status,
    COALESCE(id_guarantee_status, -1) AS sk_guarantee_status,
    COALESCE(id_propose_type, -1) AS sk_propose_type,
    count_persons_included,
    percentage_income_from_primary_person,
    avg_serasa_score,
    avg_risk_score,
    avg_declared_income,
    total_declared_income,
    dti,
    total_paid_amount,
    total_expected_amount,
    total_due_amount,
    -- lmi,
    total_occurrences_due_amount,
    total_occurrences_paid_amount,
    total_payments,
    total_payments_paid,
    total_payments_expired,
    total_occurrences,
    occurrences_solved,
    risk_category_neurotech,
    max_hspn,
    min_hspn,
    last_analysis_result,
    is_contract,
    is_direct_billing,
    is_grace_period_cancelled,
    is_legacy,
    is_3p,
    dt_last_payment,
    dt_contract_started,
    dt_ended,
    dt_next_renewal,
    dt_analyst_annulment_input,
    dt_ended_official,
    ts_propose_started,
    ts_waiting_new_docs,
    ts_evaluation_started,
    ts_rejected,
    ts_sign_started,
    ts_signed,
    ts_paid,
    ts_activation,
    ts_secured,
    ts_activation_analysis,
    ts_secure_pending,
    NOW() AS ts_load
FROM
    datalake_velo.propose

UNION ALL

SELECT
    id_propose AS sk_propose,
    COALESCE(CAST(id_propose_values AS BIGINT), -1) AS sk_propose_values,
    COALESCE(id_broker, -1) AS sk_broker,
    COALESCE(id_house, -1) AS sk_house,
    COALESCE(id_propose_company, -1) AS sk_propose_company,
    COALESCE(id_agent, -1) AS sk_agent,
    COALESCE(id_primary_person, -1) AS sk_primary_person,
    COALESCE(id_origin, -1) AS sk_origin,
    COALESCE(id_propose_status, -1) AS sk_propose_status,
    COALESCE(id_guarantee_status, -1) AS sk_guarantee_status,
    COALESCE(id_propose_type, -1) AS sk_propose_type,
    count_persons_included,
    percentage_income_from_primary_person,
    avg_serasa_score,
    avg_risk_score,
    avg_declared_income,
    total_declared_income,
    dti,
    total_paid_amount,
    total_expected_amount,
    total_due_amount,
    -- lmi,
    total_occurrences_due_amount,
    total_occurrences_paid_amount,
    total_payments,
    total_payments_paid,
    total_payments_expired,
    total_occurrences,
    occurrences_solved,
    risk_category_neurotech,
    max_hspn,
    min_hspn,
    last_analysis_result,
    is_contract,
    is_direct_billing,
    is_grace_period_cancelled,
    is_legacy,
    is_3p,
    dt_last_payment,
    dt_contract_started,
    dt_ended,
    NULL AS dt_next_renewal,
    dt_analyst_annulment_input,
    dt_ended_official,
    ts_propose_started,
    ts_waiting_new_docs,
    ts_evaluation_started,
    ts_rejected,
    ts_sign_started,
    ts_signed,
    ts_paid,
    ts_activation,
    ts_secured,
    ts_activation_analysis,
    ts_secure_pending,
    NOW() AS ts_load
FROM
    datalake_velo.propose_legacy
