SELECT
    id_propose AS sk_propose,
    id_propose_values AS sk_propose_values,
    id_broker AS sk_broker,
    id_house AS sk_house,
    id_propose_company AS sk_propose_company,
    id_agent AS sk_agent,
    id_contract AS sk_contract,
    id_primary_person AS sk_primary_person,
    id_origin AS sk_origin,
    id_propose_status AS sk_propose_status,
    id_guarantee_status AS sk_guarantee_status,
    id_propose_type AS sk_propose_type,
    count_persons_included,
    percentage_income_from_primary_person,
    avg_serasa_score,
    avg_risk_score,
    avg_declared_income,
    total_declared_income,
    dti,
    is_contract,
    is_grace_period_cancelled,
    dt_contract_started,
    dt_ended,
    ts_propose_started,
    ts_waiting_new_docs,
    ts_evaluation_started,
    ts_rejected,
    ts_sign_started,
    ts_paid,
    ts_activation,
    ts_secured,
    ts_activation_analysis,
    ts_secure_pending,
    NOW() AS ts_load
FROM
    datalake_velo.propose
