SELECT
    id_occurrence AS sk_occurrence,
    id_propose AS sk_propose,
    COALESCE(id_client, -1) AS sk_client,
    COALESCE(id_occurrence_type, -1) AS sk_occurrence_type,
    COALESCE(id_occurrence_status, -1) AS sk_occurrence_status,
    id_unicid,
    ids_accounting_entry,
    description,
    invoice_url,
    due_amount,
    due_amount_original,
    paid_amount,
    discount_amount,
    is_valid,
    dt_due,
    dt_due_legacy,
    dt_bill_month,
    dt_payment_scheduled,
    ts_paid,
    ts_created,
    is_legacy,
    NOW() AS ts_load
FROM
    datalake_velo.occurrence
