SELECT
    id AS id_qa_listing,
    houseId AS id_house_api,
    detailViewUrl AS detail_view_url,
    houseType AS house_type,
    houseFinality AS house_finality,
    condominiumName AS condominium_name,
    locationAddress AS location_address,
    locationNumber AS location_number,
    locationComplement AS location_complement,
    locationNeighborhood AS location_neighborhood,
    locationCity AS location_city,
    locationStateName AS location_state_name,
    locationStateAcronym AS location_state_acronym,
    locationZipCode AS location_zip_code,
    locationLat AS location_lat,
    locationLng AS location_lng,
    locationCountryName AS location_country_name,
    locationCountryCode AS location_country_code,
    locationFloorMin AS location_floor_min,
    locationFloorMax AS location_floor_max,
    title,
    description,
    features,
    videourl AS video_url,
    salePrice AS sale_price,
    rentPrice AS rent_price,
    bedrooms,
    suites,
    bathrooms,
    garages,
    utilArea AS util_area,
    totalArea AS total_area,
    condominiumPrice AS condominium_price,
    iptuPrice AS iptu_price,
    zone,
    businessContextSale AS is_business_context_sale,
    businessContextRent AS is_business_context_rent,
    isCondominium AS is_condominium,
    activeDb AS is_active_db,
    createDate AS dt_created,
    updateDate AS dt_updated,
    createDateDb AS ts_created_db,
    updateDateDb AS ts_updated_db,
    activeDbDate AS ts_active_db
FROM
    datalake_union_cdc_raw.qa_listing
