"""Migration Twin DAG — run original queries on Databricks, capture metrics to S3.

Auto-generated by emr-migration-v2 skill.
Run ID: c6dc6f1c-78a5-4da1-85a5-85e189c08704
Scope: fintech/enrich_velo
"""

import os
from datetime import datetime
from pathlib import Path

import yaml
from airflow import DAG, Dataset
from airflow.models import Variable
from airflow.operators.python import PythonOperator

from bietlejuice.base.airflow.job_cluster_engine import (
    attach_emr_job_cluster_finished_work_prerequisites,
    attach_emr_terminate_cluster_work_prerequisites,
    attach_job_cluster_engine_to_context,
    get_job_cluster_completion_sink,
)
from bietlejuice.base.airflow.task_creators.dag_execution_context import (
    DagExecutionContext,
)
from bietlejuice.services.configuration_service import ConfigurationService

DAG_ID = "migration_twin_fintech__enrich_velo"
RUN_ID = "c6dc6f1c-78a5-4da1-85a5-85e189c08704"
DOMAIN = "fintech"
SOURCE_DAG_NAME = "enrich_velo"
DATASET_URI = "migration:twin-fintech__enrich_velo-complete"
RUN_PREFIX = "emr-migration/runs/c6dc6f1c-78a5-4da1-85a5-85e189c08704"
RUNTIME = "twin"
SQL_DIR_NAME = "enrich"

TABLES = [
    "broker",
    "house",
    "house_legacy",
    "junk",
    "neurotech_rating",
    "occurrence",
    "omie_bank_account",
    "omie_client",
    "payment",
    "payment_contracts",
    "payment_legacy",
    "propose",
    "propose_company",
    "propose_legacy",
    "propose_person",
    "propose_person_legacy",
    "propose_values",
    "propose_values_legacy",
    "transaction_category",
    "transaction_entries",
    "user",
    
]

DAG_DIR = Path(__file__).resolve().parent
ENV = os.environ.get("ENVIRONMENT")
CONFIG_SERVICE = ConfigurationService(SOURCE_DAG_NAME)
BUCKET = CONFIG_SERVICE.get_config("datalake_bucket")
BIETLEJUICE_REPO_PATH = CONFIG_SERVICE.get_config(
    "databricks_bietlejuice_repo_path"
)
METRIC_CAPTURE_JOB = (
    f"{BIETLEJUICE_REPO_PATH}/packages/bietlejuice-runtime"
    f"/src/bietlejuice/migration/metric_capture_job.py"
)

with open(DAG_DIR / f"{DAG_ID}_cluster.yml") as _f:
    CLUSTER_ARGS = yaml.safe_load(_f).get("cluster", {})


def _build_context(dag):
    ctx = DagExecutionContext(
        dag=dag,
        environment=ENV,
        bucket=BUCKET,
        base_spark_jobs_path=f"{BIETLEJUICE_REPO_PATH}/spark_jobs/base/",
        dag_args={},
        workflow_args={},
        cluster_args=CLUSTER_ARGS,
        databricks_conn_id=CLUSTER_ARGS.get(
            "databricks_conn_id", "databricks_new_env"
        ),
    )
    attach_job_cluster_engine_to_context(ctx, CONFIG_SERVICE)
    return ctx


def _upload_sql(**context):
    import boto3

    artifacts_uri = Variable.get("artifacts_bucket")
    artifacts_bucket = artifacts_uri.replace("s3://", "").strip("/")
    sql_dir = DAG_DIR / "queries" / SQL_DIR_NAME
    s3 = boto3.client("s3")
    for table in TABLES:
        local_path = str(sql_dir / f"{table}.sql")
        s3_key = (
            f"{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}"
            f"/{SOURCE_DAG_NAME}/{table}.sql"
        )
        s3.upload_file(local_path, artifacts_bucket, s3_key)


with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["migration", "twin", "validation"],
    default_args={"owner": "data-platform", "retries": 1},
) as dag:
    ctx = _build_context(dag)

    upload_sql = PythonOperator(
        task_id="upload_sql",
        python_callable=_upload_sql,
    )

    execute_cluster = ctx.job_cluster_engine.create_execute_cluster_task(
        config_service=CONFIG_SERVICE,
        minimum_cluster_runtime_version=None,
        execute_job_cluster_local_id=None,
    )

    end = PythonOperator(
        task_id="end",
        python_callable=lambda **kw: None,
        outlets=[Dataset(DATASET_URI)],
    )

    artifacts_uri = Variable.get("artifacts_bucket")
    artifacts_bucket = artifacts_uri.replace("s3://", "").strip("/")
    capture_tasks = []
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_broker",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/broker.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/broker.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "broker",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_house",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/house.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/house.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "house",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_house_legacy",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/house_legacy.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/house_legacy.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "house_legacy",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_junk",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/junk.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/junk.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "junk",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_neurotech_rating",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/neurotech_rating.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/neurotech_rating.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "neurotech_rating",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_occurrence",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/occurrence.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/occurrence.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "occurrence",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_omie_bank_account",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/omie_bank_account.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/omie_bank_account.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "omie_bank_account",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_omie_client",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/omie_client.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/omie_client.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "omie_client",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_payment",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/payment.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/payment.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "payment",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_payment_contracts",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/payment_contracts.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/payment_contracts.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "payment_contracts",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_payment_legacy",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/payment_legacy.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/payment_legacy.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "payment_legacy",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_propose",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "propose",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_propose_company",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_company.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_company.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "propose_company",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_propose_legacy",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_legacy.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_legacy.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "propose_legacy",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_propose_person",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_person.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_person.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "propose_person",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_propose_person_legacy",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_person_legacy.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_person_legacy.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "propose_person_legacy",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_propose_values",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_values.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_values.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "propose_values",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_propose_values_legacy",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_values_legacy.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/propose_values_legacy.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "propose_values_legacy",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_transaction_category",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/transaction_category.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/transaction_category.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "transaction_category",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_transaction_entries",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/transaction_entries.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/transaction_entries.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "transaction_entries",
            ],
            execution_timeout_hours=2,
        )
    )
    
    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_user",
            job_parameters=[
                "--sql-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/user.sql",
                "--result-s3-uri",
                f"s3://{artifacts_bucket}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/user.json",
                "--run-id", RUN_ID,
                "--runtime", "databricks",
                "--domain", DOMAIN,
                "--dag-name", SOURCE_DAG_NAME,
                "--table-name", "user",
            ],
            execution_timeout_hours=2,
        )
    )
    

    cluster_completion = get_job_cluster_completion_sink(
        ctx, execute_cluster, end
    )
    attach_emr_job_cluster_finished_work_prerequisites(
        ctx, job_cluster_finished_task=end, work_completion_tasks=capture_tasks
    )

    upload_sql >> execute_cluster >> capture_tasks >> cluster_completion
    attach_emr_terminate_cluster_work_prerequisites(
        ctx,
        cluster_completion,
        execute_job_cluster_task=execute_cluster,
        job_cluster_finished_task=end,
    )
