WITH parsed AS (
    SELECT
        lf.uuid_company,
        lf.id_listing_original,
        lf.id_synthetic_house,
        lf.status,
        CAST(GET_JSON_OBJECT(lf.text2filter_prediction, '$.hasElevator') AS BOOLEAN) AS has_elevator,
        CAST(GET_JSON_OBJECT(lf.text2filter_prediction, '$.hasAllDayDoorman') AS BOOLEAN) AS has_doorman_24h,
        CAST(GET_JSON_OBJECT(lf.text2filter_prediction, '$.isFurnished') AS BOOLEAN) AS is_furnished,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'PISCINA') AS has_swimming_pool,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'SALAO_DE_FESTAS') AS has_party_hall,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'ACADEMIA') AS has_gym,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'PLAYGROUND') AS has_playground,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'CHURRASQUEIRA_NO_PREDIO') AS has_building_bbq,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'QUADRA_ESPORTIVA') AS has_sports_court,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'SALAO_DE_JOGOS') AS has_game_room,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'PORTARIA_24H') AS has_24h_front_desk,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'AREA_VERDE') AS has_green_area,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'BRINQUEDOTECA') AS has_playroom,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'SAUNA') AS has_sauna,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'ELEVADOR') AS has_building_elevator,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'LAVANDERIA_NO_PREDIO') AS has_building_laundry,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'RAMPAS_DE_ACESSO') AS has_access_ramps,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'CORRIMAO') AS has_handrails,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.installations'), 'ARRAY<STRING>'), 'PISO_TATIL') AS has_tactile_paving,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'VARANDA') AS has_balcony,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'AREA_DE_SERVICO') AS has_service_area,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'ARMARIOS_NA_COZINHA') AS has_kitchen_cabinets,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'CHURRASQUEIRA_NO_IMOVEL') AS has_unit_bbq,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'AR_CONDICIONADO') AS has_air_conditioning,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'ARMARIOS_EMBUTIDOS_NO_QUARTO') AS has_bedroom_wardrobes,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'QUINTAL') AS has_backyard,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'NOVOS_OU_REFORMADOS') AS has_new_or_renovated,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'CLOSET') AS has_closet,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'VISTA_LIVRE') AS has_unobstructed_view,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'JARDIM') AS has_garden,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'PISCINA_PRIVATIVA') AS has_private_swimming_pool,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'APARTAMENTO_COBERTURA') AS has_penthouse,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'COZINHA_AMERICANA') AS has_open_kitchen,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'HOME_OFFICE') AS has_home_office,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'RUA_SILENCIOSA') AS has_quiet_street,
        array_contains(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), 'ARMARIOS_NOS_BANHEIROS') AS has_bathroom_cabinets,
        array_join(from_json(GET_JSON_OBJECT(lf.text2filter_prediction, '$.amenities'), 'ARRAY<STRING>'), '|') AS amenities_other,
        CAST(GET_JSON_OBJECT(lf.cached_location, '$.lat') AS DOUBLE) AS lat,
        CAST(GET_JSON_OBJECT(lf.cached_location, '$.lon') AS DOUBLE) AS lon,
        lf.ts_last_update,
        lf.ts_created,
        lf.ts_updated,
        lf.year,
        lf.month,
        lf.day
    FROM
        datalake_alias_clean.listing_fingerprint AS lf
    WHERE
        lf.ts_updated >= TIMESTAMP('{load_start_date}')
        AND lf.ts_updated < TIMESTAMP('{load_end_date}')
)
SELECT
    p.id_synthetic_house AS sk_listing,
    COALESCE(cb.sk_broker, -1) AS sk_broker,
    p.id_listing_original,
    p.status,
    p.has_elevator,
    p.has_doorman_24h,
    p.is_furnished,
    p.has_swimming_pool,
    p.has_party_hall,
    p.has_gym,
    p.has_playground,
    p.has_building_bbq,
    p.has_sports_court,
    p.has_game_room,
    p.has_24h_front_desk,
    p.has_green_area,
    p.has_playroom,
    p.has_sauna,
    p.has_building_elevator,
    p.has_building_laundry,
    p.has_access_ramps,
    p.has_handrails,
    p.has_tactile_paving,
    p.has_balcony,
    p.has_service_area,
    p.has_kitchen_cabinets,
    p.has_unit_bbq,
    p.has_air_conditioning,
    p.has_bedroom_wardrobes,
    p.has_backyard,
    p.has_new_or_renovated,
    p.has_closet,
    p.has_unobstructed_view,
    p.has_garden,
    p.has_private_swimming_pool,
    p.has_penthouse,
    p.has_open_kitchen,
    p.has_home_office,
    p.has_quiet_street,
    p.has_bathroom_cabinets,
    p.amenities_other,
    p.lat,
    p.lon,
    p.ts_last_update,
    p.ts_created,
    p.ts_updated,
    CURRENT_TIMESTAMP() AS ts_load,
    p.year,
    p.month,
    p.day
FROM
    parsed AS p
LEFT JOIN
    core_brokers.brokers AS cb
        ON p.uuid_company = cb.uuid_company