SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    external_domain_id AS id_external_domain,
    earning_source_uuid AS uuid_earning_source,
    external_cart_uuid AS uuid_external_cart,
    external_domain_type,
    currency,
    status,
    failure_reason,
    incentive_systems_calculated,
    base_amount,
    revenue_share_total_amount,
    earning_source_uuid_mod AS mod_uuid_earning_source,
    external_cart_uuid_mod AS mod_uuid_external_cart,
    external_domain_type_mod AS mod_external_domain_type,
    external_domain_id_mod AS mod_id_external_domain,
    currency_mod AS mod_currency,
    status_mod AS mod_status,
    failure_reason_mod AS mod_failure_reason,
    incentive_systems_calculated_mod AS mod_incentive_systems_calculated,
    base_amount_mod AS mod_base_amount,
    revenue_share_total_amount_mod AS mod_revenue_share_total_amount,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated,
    year,
    month,
    day
FROM
    datalake_big_agent_raw.earning_sources_aud