SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    external_condition_id AS id_external_condition,
    external_condition_type,
    incentive_system,
    status,
    external_condition_id_mod AS mod_id_external_condition,
    external_condition_type_mod AS mod_external_condition_type,
    incentive_system_mod AS mod_incentive_system,
    status_mod AS mod_status,
    classification_start_at_mod AS mod_dt_classification_started,
    classification_end_at_mod AS mod_dt_classification_ended,
    partner_tier_validity_start_at_mod AS mod_dt_partner_tier_validity_started,
    partner_tier_validity_end_at_mod AS mod_dt_partner_tier_validity_ended,
    DATE(classification_start_at) AS dt_classification_started,
    DATE(classification_end_at) AS dt_classification_ended,
    DATE(partner_tier_validity_start_at) AS dt_partner_tier_validity_started,
    DATE(partner_tier_validity_end_at) AS dt_partner_tier_validity_ended,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated,
    year,
    month,
    day
FROM
    datalake_big_agent_raw.incentive_engine_aud