SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    earning_source_id AS id_earning_source,
    revenue_share_id AS id_revenue_share,
    external_receiver_id AS id_external_receiver,
    earning_uuid AS uuid_earning,
    incentive_system,
    external_receiver_type,
    calculated_from,
    currency,
    status,
    reason,
    author,
    revenue_amount,
    revenue_percentage,
    earning_uuid_mod AS mod_uuid_earning,
    incentive_system_mod AS mod_incentive_system,
    earning_source_id_mod AS mod_id_earning_source,
    revenue_share_id_mod AS mod_id_revenue_share,
    external_receiver_id_mod AS mod_id_external_receiver,
    external_receiver_type_mod AS mod_external_receiver_type,
    calculated_from_mod AS mod_calculated_from,
    currency_mod AS mod_currency,
    status_mod AS mod_status,
    reason_mod AS mod_reason,
    author_mod AS mod_author,
    revenue_amount_mod AS mod_revenue_amount,
    revenue_percentage_mod AS mod_revenue_percentage,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated,
    year,
    month,
    day
FROM
    datalake_big_agent_raw.new_earnings_aud