SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    partner_external_id AS id_partner_external,
    tier_id AS id_tier,
    overwritten_by AS id_overwritten_by,
    partner_external_type,
    incentive_system,
    overwritten_reason,
    partner_external_id_mod AS mod_id_partner_external,
    tier_id_mod AS mod_id_tier,
    overwritten_by_mod AS mod_id_overwritten_by,
    partner_external_type_mod AS mod_partner_external_type,
    incentive_system_mod AS mod_incentive_system,
    overwritten_reason_mod AS mod_overwritten_reason,
    validity_start_at_mod AS mod_dt_validity_started,
    validity_end_at_mod AS mod_dt_validity_ended,
    DATE(validity_start_at) AS dt_validity_started,
    DATE(validity_end_at) AS dt_validity_ended,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated,
    year,
    month,
    day    
FROM
    datalake_big_agent_raw.partner_tier_aud