SELECT
    discount_uuid AS uuid_discount,
    contract_id AS id_contract,
    inspection_uuid AS uuid_inspection,
    checkpoint_id AS id_checkpoint,
    discount_type,
    inspection_cost,
    disputed_inspection_cost,
    discount_value,
    discount_hash,
    discount_value_type,
    tenant_approval AS has_tenant_approval,
    landlord_approval AS has_landlord_approval,
    landlord_repair_request AS has_landlord_repair_request,
    is_eviction,
    is_spoc,
    discount_accepted AS is_discount_accepted,
    discount_reviewed_value,
    discount_acceptance_by,
    tenant_cost,
    company_cost,
    landlord_cost,
    unassigned_cost,
    landlord_receivables,
    exempted_cost,
    discount_accepted_at AS dt_discount_accepted,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_inspection_services_raw.invoice_discount

