SELECT
    id AS id_item_type,
    item_group_type_id AS id_item_group_type,
    display_type,
    media_type,
    type,
    rev,
    revtype,
    revend,
    order AS number_order,
    allow_comments AS is_allow_comments,
    allow_media AS is_allow_media,
    deleted AS is_deleted,
    show_label AS is_show_label,
    item_group_type_mod AS mod_item_group_type,
    display_type_mod AS mod_display_type,
    media_type_mod AS mod_media_type,
    type_mod AS mod_type,
    order_mod AS mod_number_order,
    deleted_mod AS mod_is_deleted,
    issue_types_mod AS mod_issue_types,
    allow_comments_mod AS mod_is_allow_comments,
    allow_media_mod AS mod_is_allow_media,
    show_label_mod AS mod_is_show_label,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_inspection_services_raw.item_type_aud
