SELECT
  id AS id_offer,
  REV,
  REVTYPE AS rev_type,
  client_id AS id_client,
  house_id AS id_house,
  rentFlow_id AS id_rent_flow,
  firestoreId AS id_firestore,
  godfatherId AS id_godfather,
  originalCondo AS original_condo,
  originalHomeInsurance AS original_home_insurance,
  originalIptu AS original_iptu,
  originalRent AS original_rent,
  rent,
  status,
  turn,
  expirationDate AS ts_expiration,
  iteration,
  rejectionReason AS rejection_reason,
  status_MOD AS MOD_status,
  turn_MOD AS MOD_turn,
  type,
  godfatherUpdatedAt AS ts_godfather_updated,
  residentName AS resident_name
FROM
  datalake_ebdb_raw.Offer_AUD
