WITH flattened AS (
    SELECT
        CAST(GET_JSON_OBJECT(payload, '$.assigned_seat_count') AS BIGINT) AS count_assigned_seats,
        CAST(GET_JSON_OBJECT(payload, '$.pending_invite_count') AS BIGINT) AS count_pending_invites,
        CAST(GET_JSON_OBJECT(payload, '$.daily_active_user_count') AS BIGINT) AS count_daily_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.weekly_active_user_count') AS BIGINT) AS count_weekly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.monthly_active_user_count') AS BIGINT) AS count_monthly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.daily_adoption_rate') AS DOUBLE) AS pct_daily_adoption,
        CAST(GET_JSON_OBJECT(payload, '$.weekly_adoption_rate') AS DOUBLE) AS pct_weekly_adoption,
        CAST(GET_JSON_OBJECT(payload, '$.monthly_adoption_rate') AS DOUBLE) AS pct_monthly_adoption,
        CAST(GET_JSON_OBJECT(payload, '$.chat_daily_active_user_count') AS BIGINT) AS count_chat_daily_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.chat_weekly_active_user_count') AS BIGINT) AS count_chat_weekly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.chat_monthly_active_user_count') AS BIGINT) AS count_chat_monthly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.claude_code_daily_active_user_count') AS BIGINT) AS count_claude_code_daily_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.claude_code_weekly_active_user_count') AS BIGINT) AS count_claude_code_weekly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.claude_code_monthly_active_user_count') AS BIGINT) AS count_claude_code_monthly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.claude_design_daily_active_user_count') AS BIGINT) AS count_claude_design_daily_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.claude_design_weekly_active_user_count') AS BIGINT) AS count_claude_design_weekly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.claude_design_monthly_active_user_count') AS BIGINT) AS count_claude_design_monthly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.cowork_daily_active_user_count') AS BIGINT) AS count_cowork_daily_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.cowork_weekly_active_user_count') AS BIGINT) AS count_cowork_weekly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.cowork_monthly_active_user_count') AS BIGINT) AS count_cowork_monthly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.office_agent_daily_active_user_count') AS BIGINT) AS count_office_agent_daily_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.office_agent_weekly_active_user_count') AS BIGINT) AS count_office_agent_weekly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.office_agent_monthly_active_user_count') AS BIGINT) AS count_office_agent_monthly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.science_daily_active_user_count') AS BIGINT) AS count_science_daily_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.science_weekly_active_user_count') AS BIGINT) AS count_science_weekly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.science_monthly_active_user_count') AS BIGINT) AS count_science_monthly_active_users,
        CAST(GET_JSON_OBJECT(payload, '$.science_entitled_user_count') AS BIGINT) AS count_science_entitled_users,
        CAST(GET_JSON_OBJECT(payload, '$.starting_at') AS DATE) AS dt_starting,
        CAST(GET_JSON_OBJECT(payload, '$.ending_at') AS DATE) AS dt_ending,
        ts_load,
        year,
        month,
        day
    FROM
        datalake_claude_usage_raw.summaries
),
ranked AS (
    SELECT
        count_assigned_seats,
        count_pending_invites,
        count_daily_active_users,
        count_weekly_active_users,
        count_monthly_active_users,
        pct_daily_adoption,
        pct_weekly_adoption,
        pct_monthly_adoption,
        count_chat_daily_active_users,
        count_chat_weekly_active_users,
        count_chat_monthly_active_users,
        count_claude_code_daily_active_users,
        count_claude_code_weekly_active_users,
        count_claude_code_monthly_active_users,
        count_claude_design_daily_active_users,
        count_claude_design_weekly_active_users,
        count_claude_design_monthly_active_users,
        count_cowork_daily_active_users,
        count_cowork_weekly_active_users,
        count_cowork_monthly_active_users,
        count_office_agent_daily_active_users,
        count_office_agent_weekly_active_users,
        count_office_agent_monthly_active_users,
        count_science_daily_active_users,
        count_science_weekly_active_users,
        count_science_monthly_active_users,
        count_science_entitled_users,
        dt_starting,
        dt_ending,
        ts_load,
        year,
        month,
        day,
        ROW_NUMBER() OVER (
            PARTITION BY
                dt_starting,
                dt_ending
            ORDER BY
                ts_load DESC
        ) AS rn
    FROM
        flattened
)
SELECT
    count_assigned_seats,
    count_pending_invites,
    count_daily_active_users,
    count_weekly_active_users,
    count_monthly_active_users,
    pct_daily_adoption,
    pct_weekly_adoption,
    pct_monthly_adoption,
    count_chat_daily_active_users,
    count_chat_weekly_active_users,
    count_chat_monthly_active_users,
    count_claude_code_daily_active_users,
    count_claude_code_weekly_active_users,
    count_claude_code_monthly_active_users,
    count_claude_design_daily_active_users,
    count_claude_design_weekly_active_users,
    count_claude_design_monthly_active_users,
    count_cowork_daily_active_users,
    count_cowork_weekly_active_users,
    count_cowork_monthly_active_users,
    count_office_agent_daily_active_users,
    count_office_agent_weekly_active_users,
    count_office_agent_monthly_active_users,
    count_science_daily_active_users,
    count_science_weekly_active_users,
    count_science_monthly_active_users,
    count_science_entitled_users,
    dt_starting,
    dt_ending,
    ts_load,
    year,
    month,
    day
FROM
    ranked
WHERE
    rn = 1
