SELECT
    raw.id_event,
    raw.id_person,
    raw.id_user,
    raw.id_domain_user,
    raw.id_anonymous,
    raw.event_name,
    raw.application,
    raw.platform,
    raw.country,
    raw.city,
    raw.region,
    raw.app_type,
    raw.device_info,
    raw.ip_address,
    raw.latitude,
    raw.longitude,
    raw.egw_initial_gclid,
    raw.egw_initial_fbclid,
    raw.egw_initial_gbraid,
    raw.egw_initial_wbraid,
    raw.egw_gclid,
    raw.egw_fbclid,
    raw.egw_gbraid,
    raw.egw_wbraid,
    raw.egw_rdt_cid,
    raw.egw_initial_rdt_cid,
    raw.egw_msclkid,
    raw.egw_initial_msclkid,
    raw.egw_apps_flyer_id,
    raw.egw_initial_utm_campaign,
    raw.egw_initial_utm_content,
    raw.egw_initial_utm_medium,
    raw.egw_initial_utm_source,
    raw.egw_initial_utm_term,
    raw.egw_utm_campaign,
    raw.egw_utm_content,
    raw.egw_utm_medium,
    raw.egw_utm_source,
    raw.egw_utm_term,
    raw.egw_initial_attribution_time,
    raw.egw_last_attribution_time,
    raw.egw_linked_devices,
    raw.event_properties,
    raw.user_properties,
    raw.ts_event,
    raw.ts_egw,
    raw.ts_egw_updated_at,
    raw.ts_ingested_at,
    CURRENT_TIMESTAMP() AS ts_load,
    DATE_FORMAT(raw.ts_event, 'yyyy-MM-dd') AS event_date
FROM
    datalake_cdp_raw.user_tracking_events AS raw
WHERE
    raw.ingestion_date >= DATE_FORMAT(TIMESTAMP('{load_start_date}'), 'yyyy-MM-dd-HH')
    AND raw.ingestion_date <= DATE_FORMAT(TIMESTAMP('{load_end_date}'), 'yyyy-MM-dd-HH')
