drop table if exists zendesk.fact_ticket_metrics;

create table if not exists zendesk.fact_ticket_metrics(
    sk_ticket integer,
    sk_house_listing bigint,
    sk_contract integer,
    sk_client integer,
    sk_owner integer,
    sk_zendesk_requester_user bigint,
    sk_zendesk_submitter_user bigint,
    sk_zendesk_assignee_user bigint,
    sk_created_date integer,
    sk_solved_date integer,
    sk_extraction_date integer,
    sk_chat_started_date integer,
    sk_chat_started_time varchar,
    minutes_first_reply_time_calendar integer,
	minutes_first_reply_time_business integer,
	minutes_first_resolution_time_calendar integer,
	minutes_first_resolution_time_business integer,
	minutes_requester_wait_time_calendar integer,
	minutes_requester_wait_time_business integer,
	minutes_agent_wait_time_calendar integer,
	minutes_agent_wait_time_business integer,
	minutes_on_hold_time_calendar integer,
	minutes_on_hold_time_business integer,
	minutes_full_resolution_time_calendar integer,
	minutes_full_resolution_time_business integer,
    reopens varchar,
    replies varchar,
    has_public_comments varchar,
    status varchar,
    ts_load varchar
);