SELECT
    id AS id_contestation,
    reviewer_id AS id_reviewer,
    repair_request_id AS id_repair_request,
    uuid,
    comment,
    reason,
    origin,
    type,
    cost,
    rev,
    revtype,
    revend,
    reviewer_id_mod AS mod_id_reviewer,
    repair_request_id_mod AS mod_id_repair_request,
    uuid_mod AS mod_uuid,
    comment_mod AS mod_comment,
    reason_mod AS mod_reason,
    origin_mod AS mod_origin,
    type_mod AS mod_type,
    cost_mod AS mod_cost,
    reviewer_mod AS mod_reviewer,
    repair_request_mod AS mod_repair_request,
    contestation_medias_mod AS mod_contestation_medias,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_inspection_services_raw.contestation_aud
