SELECT
    id,
    item_group_type_id AS id_item_group_type,
    repair_suggestion_id AS id_repair_suggestion,
    previous_item_type_id AS id_previous_item_type,
    current_item_type_id AS id_current_item_type,
    previous_item_issue_type_id AS id_previous_item_issue_type,
    current_item_issue_type_id AS id_current_item_issue_type,
    item_group_status,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    item_group_type_id_mod AS mod_id_item_group_type,
    repair_suggestion_id_mod AS mod_id_repair_suggestion,
    previous_item_type_id_mod AS mod_id_previous_item_type,
    current_item_type_id_mod AS mod_id_current_item_type,
    previous_item_issue_type_id_mod AS mod_id_previous_item_issue_type,
    current_item_issue_type_id_mod AS mod_id_current_item_issue_type,
    item_group_status_mod AS mod_item_group_status,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_inspections_raw.item_group_state_aud
