SELECT
    id AS id_item_group_type,
    room_type_id AS id_room_type,
    review_instruction,
    type,
    rev,
    revtype,
    revend,
    deleted AS is_deleted,
    deletable AS is_deletable,
    review_instruction_mod AS mod_review_instruction,
    type_mod AS mod_type,
    item_types_mod AS mod_item_types,
    room_type_mod AS mod_room_type,
    deleted_mod AS mod_deleted,
    deletable_mod AS mod_deletable,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_inspection_services_raw.item_group_type_aud
