SELECT
    id AS id_reviewer,
    user_id AS id_user,
    user_id_mod AS mod_id_user,
    assessment_id AS id_assessment,
    assessment_id_mod AS mod_id_assessment,
    uuid,
    uuid_mod AS mod_uuid,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    reviewer_type,
    reviewer_type_mod AS mod_reviewer_type,
    assessment_mod AS mod_assessment,
    approval_type,
    approval_type_mod AS mod_approval_type,
    approval_reason,
    approval_reason_mod AS mod_approval_reason,
    approval_comment,
    approval_comment_mod AS mod_approval_comment,
    approved AS is_approved,
    approved_mod AS mod_is_approved,
    approved_at AS ts_approved,
    approved_at_mod AS mod_ts_approved,
    created_at AS ts_created,
    created_at_mod AS mod_ts_created,
    updated_at AS ts_updated,
    updated_at_mod AS mod_ts_updated,
    year,
    month,
    day
FROM
    datalake_inspection_services_raw.reviewer_aud
