SELECT
    PersonId AS id_person,
    PersonNumber AS person_number,
    CorrespondenceLanguage AS correspondence_language,
    CorrLanguageMeaning AS correspondence_language_meaning,
    BloodType AS blood_type,
    BloodTypeMeaning AS blood_type_meaning,
    CountryOfBirth AS birth_country,
    CountryOfBirthName AS birth_country_name,
    RegionOfBirth AS birth_region,
    TownOfBirth AS birth_town,
    CreatedBy AS created_by,
    LastUpdatedBy AS last_update_by,
    addresses,
    citizenships,
    contactRelationships AS contact_relationships,
    contactsDFF AS contacts_dff,
    driverLicenses AS driver_licenses,
    emails,
    ethnicities,
    legislativeInfo AS legislative_info,
    names,
    nationalIdentifiers AS national_identifiers,
    otherCommunicationAccounts AS other_communication_accounts,
    passports,
    phones,
    religions,
    visasPermits AS visas_permits,
    to_date(DateOfBirth, 'yyyy-MM-dd') AS dt_birth,
    to_date(DateOfDeath, 'yyyy-MM-dd') AS dt_death,
    to_timestamp(substr(replace(CreationDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_created,
    to_timestamp(substr(replace(LastUpdateDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_last_update,
    ts_load,
    year,
    month,
    day
FROM datalake_hr_system_raw.hcm_contacts