SELECT
    PersonId AS id_person,
    ProfileId AS id_profile,
    PersonNumber AS person_number,
    ProfileCode AS profile_code,
    DisplayName AS display_name,
    accomplishmentSections AS accomplishment,
    attachments,
    careerPreferenceSections AS career_preference,
    certificationSections AS certifications,
    competencySections AS competency,
    educationSections AS education,
    educationLvlSections AS education_level,
    areasOfExpertise AS expertise_areas,
    favoriteLinks AS favorite_links,
    highestEducationLvlSections AS highest_education_level,
    honorSections AS honors,
    areasOfInterest AS interest_areas,
    careersOfInterest AS interest_careers,
    languageSections AS languages,
    membershipSections AS membership,
    publicSkills AS public_skills,
    skillSections AS skills,
    specialProjectSections AS special_projects,
    StatusCode AS status_code,
    areaOfStudySections AS study_area,
    Summary AS summary,
    tags AS tags,
    technicalPostDetailsSections AS technical_post_details,
    workHistorySections AS work_history,
    workPreferenceSections AS work_preference,
    CreatedBy AS created_by,
    LastUpdatedBy AS last_updated_by,
    to_timestamp(substr(replace(CreationDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_created,
    to_timestamp(substr(replace(LastUpdateDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_last_update,
    ts_load,
    year AS year,
    month AS month,
    day AS day
FROM datalake_hr_system_raw.talent_person_profiles