/*  Although there are created_at and update_at columns,
this query is running as FULL, because, currently,
these columns are mostly empty. */
SELECT 
    id, 
    guarantee_id AS id_guarantee, 
    rev,
    revend AS rev_end, 
    revtype AS rev_type, 
    cancellation_reason,
    card_token, 
    emv, 
    installments,
    pix_link, 
    qr_code, 
    status AS charge_status,
    type AS charge_type,
    refund_amount,
    guarantee_id_mod AS mod_id_guarantee,
    cancellation_reason_mod AS mod_cancellation_reason,
    card_token_mod AS mod_card_token, 
    emv_mod AS mod_emv, 
    installments_mod AS mod_installments, 
    pix_link_mod AS mod_pix_link, 
    qr_code_mod AS mod_qr_code, 
    status_mod AS mod_charge_status, 
    type_mod AS mod_charge_type,
    refund_amount_mod AS mod_refund_amount,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM 
    datalake_rental_guarantee_raw.charge_aud
