SELECT
    id AS id_listing_business_context,
    imovelId AS id_house,
    rev,
    revtype AS rev_type,
    businessContext AS business_context,
    businessContext_mod AS mod_business_context,
    shortUrl AS short_url,
    shortUrl_mod AS mod_short_url,
    status,
    status_mod AS mod_status,
    closingStatus AS status_closing,
    closingStatus_mod AS mod_status_closing,
    selectedAction AS selected_action,
    selectedAction_mod AS mod_selected_action,
    statusReason AS status_reason,
    statusReason_mod AS mod_status_reason,
    ownership,
    ownership_mod AS mod_ownership,
    calculatorPrice AS calculator_price,
    calculatorPrice_mod AS mod_calculator_price,
    version,
    version_MOD AS mod_version,
    suspensionReason AS suspension_reason,
    suspensionReason_MOD AS mod_suspension_reason,
    suspendedUntil AS ts_suspended_until,
    suspendedUntil_MOD AS mod_suspended_until,
    firstPublicationDate AS ts_first_publication,
    firstPublicationDate_mod AS mod_ts_first_publication,
    lastPublicationDate AS ts_last_publication,
    lastPublicationDate_mod AS mod_ts_last_publication,
    lastStatusChangedAt AS ts_last_status_changed,
    lastStatusChangedAt_MOD AS mod_ts_last_status_changed,
    atualizadoEm AS ts_updated,
    criadoEm AS ts_created,
    op_cdc,
    ts_cdc_transaction,
    ts_database_transaction
FROM
    datalake_ebdb_raw.ListingBusinessContext_AUD
