SELECT
    id AS id_observation,
    parentObservationId AS id_parent_observation,
    traceId AS id_trace,
    modelId AS id_model,
    projectId AS id_project,
    promptId AS id_prompt,
    input,
    output,
    environment,
    model,
    modelParameters AS model_parameters,
    name,
    promptName AS prompt_name,
    promptTokens AS prompt_tokens,
    promptVersion AS prompt_version,
    type,
    unit,
    usage,
    usageDetails AS usage_details,
    latency,
    level,
    inputPrice AS input_price,
    outputPrice AS output_price,
    completionTokens AS completion_tokens,
    calculatedInputCost AS calculated_input_cost,
    calculatedOutputCost AS calculated_output_cost,
    calculatedTotalCost AS calculated_total_cost,
    costDetails AS cost_details,
    CAST(createdAt AS TIMESTAMP) AS ts_created,
    CAST(updatedAt AS TIMESTAMP) AS ts_updated,
    year,
    month,
    day,
    hour
FROM
    datalake_langfuse_raw.observations
WHERE
    MAKE_TIMESTAMP(year, month, day, hour, 0, 0) >= TIMESTAMP('{load_start_date}')