SELECT 
    YEAR(dt_month_started) AS base_year,
    dt_month_started AS month_start,
    country_code AS country_name,
    city_group,
    supply_mkt_origin, 
    supply_mkt_origin_detailed,
    mexico_channel,
    leads,
    leads_ub_i24,
    leads_ub_human_crawlers,
    leads_ub_owner_mx AS leads_ub_owner_mex,
    prospects,
    qualifieds,
    opportunities,
    first_listings,
    prospects_targets,
    qualifieds_targets,
    opportunities_targets,
    first_listings_targets,
    p2q,
    q2fl,
    ongoing_listings,
    budget_total_target,
    budget_comission_target,
    budget_target,
    actual_cost,
    actual_cost_comission,
    cost
FROM 
    datalake_mexico_rent_supply_funnel.monthly_supply_flow_metrics