    SELECT
    id_entry,
    id_invoice,
    sk_invoice_reversed_entry,
    sk_contract,
    version,
    locale,
    localidade,
    guarantee,
    rental_administrator,
    bill_item,
    description,
    purpose,
    invoice_account_type,
    from_account_type,
    to_account_type,
    account_type,
    account_classification,
    status,
    closing_mode,
    entry_sort_ascend,
    entry_by_accrual_sort_ascend,
    due_amount,
    invoice_due_amount,
    is_cap,
    is_contract_b2b,
    is_rental_paid_in_advance,
    has_negotiation,
    has_installments,
    pp_pays,
    ended_before_started,
    accrual_year_month,
    entry_accrual_year_month,
    entry_creation_accrual_year_month,
    entry_created_date,
    invoice_created_date,
    invoice_due_date,
    invoice_paid_date,
    invoice_paid_date_next_business_day,
    invoice_canceled_date,
    contract_start,
    contract_annulment,
    ts_load AS ts_snapshot,
    YEAR(ts_load) AS year,
    MONTH(ts_load) AS month,
    DAY(ts_load) AS day
FROM
    datalake_accounting_funnel.accounts_payable
