SELECT
  bp.id_buyer AS sk_buyer,
  bp.id_first_region AS sk_first_region,
  bp.id_last_region AS sk_last_region,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.ts_first_sale_flow,1, 10),'-','') AS BIGINT), -1) AS sk_first_sale_flow_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.ts_first_booking_created,1, 10),'-','') AS BIGINT), -1) AS sk_first_booking_created_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.ts_first_visit_completed,1, 10),'-','') AS BIGINT), -1) AS sk_first_visit_completed_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.ts_first_offer_submitted,1, 10),'-','') AS BIGINT), -1) AS sk_first_offer_submitted_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.dt_first_offer_accepted,1, 10),'-','') AS BIGINT), -1) AS sk_first_offer_accepted_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.dt_first_sale_agreement_signed,1, 10),'-','') AS BIGINT), -1) AS sk_first_sale_agreement_signed_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.ts_last_sale_flow,1, 10),'-','') AS BIGINT), -1) AS sk_last_sale_flow_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.ts_last_booking_created,1, 10),'-','') AS BIGINT), -1) AS sk_last_booking_created_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.ts_last_visit_completed,1, 10),'-','') AS BIGINT), -1) AS sk_last_visit_completed_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.ts_last_offer_submitted,1, 10),'-','') AS BIGINT), -1) AS sk_last_offer_submitted_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.dt_last_offer_accepted,1, 10),'-','') AS BIGINT), -1) AS sk_last_offer_accepted_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.dt_last_sale_agreement_signed,1, 10),'-','') AS BIGINT), -1) AS sk_last_sale_agreement_signed_date,
  COALESCE(CAST(REPLACE(SUBSTRING(bp.ts_last_event,1, 10),'-','') AS BIGINT), -1) AS sk_last_event_date,
  bp.first_event,
  bp.last_event,
  bp.further_funnel_step,
  bp.first_buyer_intention,
  bp.is_tenant,
  bp.is_current_tenant,
  bp.is_contract_owner,
  bp.is_tenant_prospect,
  bp.sale_flows,
  bp.regions_with_sale_flows,
  bp.weeks_with_sale_flows,
  bp.bookings_created,
  bp.bookings_created_by_agent,
  bp.bookings_canceled,
  bp.visits_completed,
  bp.offers_submitted,
  bp.offers_accepted,
  bp.offers_dismissed,
  bp.sale_agreements_signed,
  bp.avg_sale_price,
  bp.avg_offer_price,
  bp.avg_offer_discount,
  bp.houses_owned,
  bp.listings_for_sale,
  bp.listings_for_rent,
  bp.days_first_sale_flow_to_first_booking_created,
  bp.days_first_sale_flow_to_first_visit_completed,
  bp.days_first_sale_flow_to_first_offer_submitted,
  bp.days_first_sale_flow_to_first_offer_accepted,
  bp.days_first_sale_flow_to_first_sale_agreement_signed,
  bp.days_first_booking_created_to_first_visit_completed,
  bp.days_first_booking_created_to_first_offer_submitted,
  bp.days_first_booking_created_to_first_offer_accepted,
  bp.days_first_booking_created_to_first_sale_agreement_signed,
  bp.days_first_visit_completed_to_first_offer_submitted,
  bp.days_first_visit_completed_to_first_offer_accepted,
  bp.days_first_visit_completed_to_first_sale_agreement_signed,
  bp.days_first_offer_submitted_to_first_offer_accepted,
  bp.days_first_offer_submitted_to_first_sale_agreement_signed,
  bp.days_first_offer_accepted_to_first_sale_agreement_signed,
  bp.days_first_sale_flow_to_last_sale_flow,
  bp.days_first_sale_flow_to_last_booking_created,
  bp.days_first_sale_flow_to_last_visit_completed,
  bp.days_first_sale_flow_to_last_offer_submitted,
  bp.days_first_sale_flow_to_last_offer_accepted,
  bp.days_first_sale_flow_to_last_sale_agreement_signed,
  bp.days_first_sale_flow_to_last_event,
  bp.days_first_booking_created_to_last_booking_created,
  bp.days_first_booking_created_to_last_visit_completed,
  bp.days_first_booking_created_to_last_offer_submitted,
  bp.days_first_booking_created_to_last_offer_accepted,
  bp.days_first_booking_created_to_last_sale_agreement_signed,
  bp.days_first_visit_completed_to_last_visit_completed,
  bp.days_first_visit_completed_to_last_offer_submitted,
  bp.days_first_visit_completed_to_last_offer_accepted,
  bp.days_first_visit_completed_to_last_sale_agreement_signed,
  bp.days_first_offer_submitted_to_last_offer_submitted,
  bp.days_first_offer_submitted_to_last_offer_accepted,
  bp.days_first_offer_submitted_to_last_sale_agreement_signed,
  bp.days_first_offer_accepted_to_last_offer_accepted,
  bp.days_first_offer_accepted_to_last_sale_agreement_signed,
  bp.days_first_sale_agreement_signed_to_last_sale_agreement_signed,
  current_timestamp AS ts_load
FROM
  datalake_buyer_prospect.buyer_prospect bp