SELECT
    id,
    task_id AS id_task,
    channel_id AS id_channel,
    GET_JSON_OBJECT(task_attributes,'$.chat_id') AS id_chat,
    GET_JSON_OBJECT(assigned_to,'$.worker_sid') AS id_worker,
    task_status,
    GET_JSON_OBJECT(task_attributes,'$.conversations.outcome') AS task_outcome,
    GET_JSON_OBJECT(task_attributes,'$.customers') AS customer_metadata,
    GET_JSON_OBJECT(task_attributes,'$.from') AS customer_contact_info,
    GET_JSON_OBJECT(task_attributes,'$.email') AS customer_email,
    GET_JSON_OBJECT(task_attributes,'$.twilioNumber') AS twilio_phone_number,
    GET_JSON_OBJECT(assigned_to,'$.worker_name') AS worker_email,
    GET_JSON_OBJECT(task_attributes,'$.channelType') AS channel_type,
    GET_JSON_OBJECT(task_resource, '$.reason') AS completion_reason,
    GET_JSON_OBJECT(task_attributes,'$.status') AS channel_status,
    GET_JSON_OBJECT(task_attributes,'$.target') AS department,
    GET_JSON_OBJECT(task_attributes,'$.BPO') AS bpo_name,
    GET_JSON_OBJECT(task_attributes,'$.tagsByType') AS tags,
    GET_JSON_OBJECT(task_attributes,'$.conversations') AS conversation_attributes,
    task_attributes,
    task_resource,
    assigned_to,
    seconds_to_first_response,
    CAST(GET_JSON_OBJECT(task_attributes,'$.forwarding') AS BOOLEAN) AS is_forwarded,
    CAST(GET_JSON_OBJECT(task_attributes,'$.conversations.conversation_attribute_2') AS BOOLEAN) AS is_per_team_task,
    COALESCE(CAST(GET_JSON_OBJECT(task_attributes,'$.is_spoc') AS BOOLEAN), FALSE) AS is_spoc_task,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_quinto_messenger_test_raw.task
