SELECT
  CAST(id AS BIGINT) AS id_machine_state,
  CAST(input_source_id AS BIGINT) AS id_input_source,
  CAST(context_external_id AS BIGINT) AS id_context_external,
  CAST(group_id AS BIGINT) AS id_group,
  CAST(scope_id AS INT) AS id_scope,
  CAST(get_json_object(properties,'$.analysisRequestId') AS BIGINT) AS id_analysis_request,
  CAST(get_json_object(properties,'$.creditEvaluationId') AS BIGINT) AS id_credit_evaluation,
  CAST(get_json_object(properties,'$.houseId') AS BIGINT) AS id_house,
  CAST(get_json_object(properties,'$.cityId') AS INT) AS id_city,
  get_json_object(properties,'$.reason') AS reason,
  get_json_object(properties,'$.result') AS result,
  get_json_object(properties,'$.guaranteeType') as guarantee_type,
  CAST(get_json_object(properties,'$.informedLimit') AS DECIMAL(10,2)) AS informed_limit,
  CAST(get_json_object(properties,'$.preApprovedLimit') AS DECIMAL(10,2)) AS pre_approved_limit,
  properties,
  status,
  type,
  input_source_type,
  input_description,
  version,
  scope_type,
  active AS is_active,
  expires_at AS ts_expires,
  created_at AS ts_created,
  updated_at AS ts_updated
FROM
  datalake_docx_raw.machine_state
