SELECT
  CAST(id AS BIGINT) AS id_machine_state,
  CAST(input_source_id AS BIGINT) AS id_input_source,
  CAST(context_external_id AS BIGINT) AS id_context_external,
  CAST(group_id AS BIGINT) AS id_group,
  CAST(scope_id AS BIGINT) AS id_scope,
  CAST(GET_JSON_OBJECT(properties,'$.analysisRequestId') AS BIGINT) AS id_analysis_request,
  CAST(GET_JSON_OBJECT(properties,'$.creditEvaluationId') AS BIGINT) AS id_credit_evaluation,
  CAST(GET_JSON_OBJECT(properties,'$.houseId') AS BIGINT) AS id_house,
  CAST(GET_JSON_OBJECT(properties,'$.cityId') AS BIGINT) AS id_city,
  rev,
  revtype AS rev_type,
  revend AS rev_end,
  GET_JSON_OBJECT(properties,'$.reason') AS reason,
  GET_JSON_OBJECT(properties,'$.result') AS result,
  GET_JSON_OBJECT(properties,'$.guaranteeType') AS guarantee_type,
  CAST(GET_JSON_OBJECT(properties,'$.informedLimit') AS DECIMAL(10,2)) AS informed_limit,
  CAST(GET_JSON_OBJECT(properties,'$.preApprovedLimit') AS DECIMAL(10,2)) AS pre_approved_limit,
  properties,
  status,
  type,
  input_source_type,
  input_description,
  version,
  scope_type,
  active AS is_active,
  expires_at AS ts_expired
FROM
  datalake_docx_raw.machine_state_aud
