SELECT
    lpe.id_listing_duplicity AS sk_listing_duplicity,
    lpe.id_listing_purchase AS sk_listing_purchase,
    lpe.id_house AS sk_house,
    lpe.id_ciq_user AS sk_ciq_user,
    lpe.id_owner AS sk_owner,
    lpe.id_contract AS sk_contract,
    lpe.id_atlas_duplicity AS sk_atlas_duplicity,
    lpe.id_address_parsed_duplicity AS sk_address_parsed_duplicity,
    lpe.id_similar_listing_purchase AS sk_similar_listing_purchase,
    lpe.id_similar_house AS sk_similar_house,
    lpe.id_similar_house_ciq_user AS sk_similar_house_ciq_user,
    lpe.id_similar_house_owner AS sk_similar_house_owner,
    lpe.id_similar_contract AS sk_similar_contract,
    lpe.similar_house_listing_status,
    lpe.similar_house_consultant_type,
    lpe.similar_house_business_context,
    lpe.atlas_duplicity_action,
    lpe.atlas_duplicity_reason,
    lpe.total_days_since_house_inactived,
    lpe.is_similiar_house_inactive,
    lpe.is_similiar_house_paid,
    lpe.is_same_ciq,
    lpe.is_same_owner,
    lpe.is_address_parsed_duplicity,
    lpe.is_atlas_atlas_duplicity,
    lpe.is_publication_blocked_by_atlas,
    lpe.has_similiar_house_republication,
    lpe.dt_similiar_house_paid,
    lpe.dt_similiar_house_contract_termination,
    lpe.ts_similiar_house_contract_signed,
    lpe.ts_similiar_house_inactived,
    lpe.ts_house_registration,
    lpe.ts_similiar_house_registration,
    NOW() AS ts_load
FROM
    datalake_ciq.listing_purchase_duplicity AS lpe