SELECT
  id,
  owner_id as id_owner,
  main_id as id_main,
  version,
  `status`,
  `type`,
  suspension_reason,
  neighbourhood,
  home_insurance,
  city,
  url_main_image,
  rent,
  iptu_included as is_iptu_included,
  total_cost,
  `number`,
  condo,
  iptu_type,
  condo_type,
  iptu,
  complement,
  state,
  address,
  main_created_at as ts_main_created,
  main_updated_at as ts_main_updated,
  created_at as ts_created,
  updated_at as ts_updated
FROM
  datalake_godfather_raw.house
