SELECT
  id,
  resident_info_id as id_resident_info,
  firestore_id as id_firestore,
  rent_flow_id as id_rent_flow,
  version,
  `status`,
  rejection_reason_description,
  `type`,
  rejection_reason,
  original_rent,
  iteration,
  visualized as is_visualized,
  rent,
  original_home_insurance,
  original_iptu,
  turn,
  original_condo,
  code,
  offer_status,
  raw_document,
  expiration_date as ts_expiration,
  created_firestore_at as ts_created_firestore,
  visualized_at as ts_visualized,
  first_sent_at as ts_first_sent,
  last_sent_at as ts_last_sent,
  created_at as ts_created,
  updated_at as ts_updated
FROM datalake_godfather_raw.offer
