SELECT
  id,
  rent_flow_id as id_rent_flow,
  resident_info_id as id_resident_info,
  firestore_id as id_firestore,
  firestore_id_mod as mod_id_firestore,
  rev,
  revtype as rev_type,
  code,
  visualized as is_visualized,
  cast(original_rent as double) original_rent,
  cast(original_condo as double) as original_condo ,
  cast(original_home_insurance as double) as original_home_insurance ,
  cast(original_iptu as double) as original_iptu ,
  `type` ,
  `status`,
  status_mod as mod_status,
  rejection_reason,
  rejection_reason_mod as mod_rejection_reason,
  rejection_reason_description,
  rejection_reason_description_mod as mod_rejection_reason_description,
  cast(rent as double) as rent ,
  rent_mod as mod_rent,
  turn,
  turn_mod as mod_turn,
  iteration,
  iteration_mod as mod_iteration,
  visualized_at as ts_visualized,
  visualized_at_mod as mod_ts_visualized_mod,
  first_sent_at as ts_first_sent,
  last_sent_at as ts_last_sent,
  last_sent_at_mod as mod_ts_last_sent,
  created_firestore_at as ts_created_firestore,
  created_firestore_at_mod as mod_ts_created_firestore,
  expiration_date as ts_expiration,
  expiration_date_mod as mod_ts_expiration
FROM
  datalake_godfather_raw.offer_aud
