SELECT
    city_group,
    lead_processing_operation,
    supply_mkt_origin_detailed,
    planning_taxonomy,
    planning_conversion,
    planning_operation,
    planning_cluster,
    company_report_origin,
    weeks_conversion,
    op2q,
    q2opp,
    opp2fl,
    fl,
    q2avq,
    avq2opp,
    TO_DATE(week_start, 'yyyy-MM-dd') AS dt_week_started
FROM
    datalake_gsheets_raw.sale_supply_targets_cohort_2024
