SELECT
    email_address AS email,
    CAST(score AS STRING) AS score,
    qual_a_sua_relacao_com_este_condominio AS condo_affiliation_type,
    qual_o_nome_do_condominio AS condo_name,
    CAST(cnpj_base AS STRING) AS condo_cnpj,
    tipo_de_logradouro AS address_type,
    nome_do_logradouro AS address,
    CAST(numero AS BIGINT) AS number,
    CAST(cep AS STRING) AS zipcode,
    alguma_outra_informacao_importante_para_identificar_o_endereco_do_seu_condominio_descreva_abaixo AS complement,
    bairro AS neighborhood,
    cidade AS city,
    estado AS state,
    alguma_outra_informacao_relevante_sobre_este_condominio AS user_condo_comments,
    o_condominio_possui_as_amenidades_abaixo_garagem AS has_garage,
    o_condominio_possui_as_amenidades_abaixo_piscina AS has_swim_pool,
    o_condominio_possui_as_amenidades_abaixo_academia AS has_gym,
    o_condominio_possui_as_amenidades_abaixo_salao_de_festas AS has_party_hall,
    o_condominio_possui_as_amenidades_abaixo_churrasqueira AS has_grill_area,
    o_condominio_possui_as_amenidades_abaixo_quadra_poliesportiva AS has_sports_court,
    o_condominio_possui_as_amenidades_abaixo_playground AS has_playground,
    o_condominio_possui_as_amenidades_abaixo_brinquedoteca AS has_toy_library,
    o_condominio_possui_as_amenidades_abaixo_elevador AS has_elevator,
    o_condominio_possui_as_amenidades_abaixo_portaria_24h AS has_entrance_hall,
    o_condominio_possui_as_amenidades_abaixo_sauna AS has_sauna,
    o_condominio_possui_as_amenidades_abaixo_lavanderia_no_predio AS has_laundry,
    o_condominio_possui_as_amenidades_abaixo_gas_encanado AS has_piped_gas,
    o_condominio_possui_as_amenidades_abaixo_area_gourmet AS has_gourmet_area,
    o_condominio_possui_as_amenidades_abaixo_e_proximo_ao_metro_ou_trem AS has_metro_or_train_close,
    CAST(timestamp AS TIMESTAMP) AS dt_created
FROM
    datalake_gsheets_raw.vespucio_condo_golden_set