SELECT
  os.id_offer,
  os.id_user_consultant,
  os.id_consultant,
  os.id_user_team_lead,
  os.id_team_lead,
  os.id_user_pre_specialist,
  os.id_pre_specialist,
  os.id_user_post_specialist,
  os.id_post_specialist,
  os.id_user_credit_specialist,
  os.id_credit_specialist,
  os.id_user_start_financing_specialist,
  os.id_start_financing_specialist,
  os.id_user_follow_up_financing_specialist,
  os.id_follow_up_financing_specialist,
  os.id_user_end_financing_specialist,
  os.id_end_financing_specialist,
  os.id_user_notes_registry_specialist,
  os.id_notes_registry_specialist,
  os.id_user_real_estate_register_specialist,
  os.id_real_estate_register_specialist,
  os.id_user_legal_risk_analyst,
  os.id_legal_risk_analyst,
  os.id_user_agent,
  os.id_agent,
  os.id_user_post_dd_specialist,
  os.id_post_dd_specialist,
  os.consultant_name,
  os.consultant_email,
  os.team_lead_name,
  os.team_lead_email,
  os.pre_specialist_name,
  os.pre_specialist_email,
  os.post_specialist_name,
  os.post_specialist_email,
  os.credit_specialist_name,
  os.credit_specialist_email,
  os.start_financing_specialist_name,
  os.start_financing_specialist_email,
  os.follow_up_financing_specialist_name,
  os.follow_up_financing_specialist_email,
  os.end_financing_specialist_name,
  os.end_financing_specialist_email,
  os.notes_registry_specialist_name,
  os.notes_registry_specialist_email,
  os.real_estate_register_specialist_name,
  os.real_estate_register_specialist_email,
  os.legal_risk_analyst_name,
  os.legal_risk_analyst_email,
  os.agent_name,
  os.agent_email,
  os.post_dd_specialist_name,
  os.post_dd_specialist_email,
  CASE WHEN os.pre_specialist_email = cah_pre.email THEN cah_pre.managers END AS TL_pre,
  CASE WHEN os.post_specialist_email = cah_pos.email THEN cah_pos.managers END AS TL_post
FROM datalake_sale_offer_flows.offer_specialists AS os
LEFT JOIN datalake_gsheets_clean.closing_analysts_hierarchy AS cah_pre
  ON os.pre_specialist_email = cah_pre.email
LEFT JOIN datalake_gsheets_clean.closing_analysts_hierarchy AS cah_pos
  ON os.post_specialist_email = cah_pos.email