SELECT
    id_pre_proposal,
    pp.id_house,
    pp.id_user,
    id_when_will_schedule,
    id_who_will_live,
    id_animals,
    ch.country_code,
    rev,
    rev_type,
    rent,
    edition,
    status,
    original_rent,
    original_condo,
    original_iptu,
    original_home_insurance,
    rejection_reason,
    code,
    mod_house,
    mod_when_will_schedule,
    mod_who_will_live,
    mod_user,
    mod_animals,
    mod_rent,
    mod_edition,
    mod_status,
    mod_conditions,
    mod_ts_visualized,
    mod_has_rental_accepted,
    mod_has_income_proof_accepted,
    mod_has_charge_accepted,
    has_rental_accepted,
    has_income_proof_accepted,
    has_charge_accepted,
    is_owner_accept_condition,
    (edition = 'EdicaoInquilino') AS is_tenant_edition,
    (edition = 'EdicaoProprietario') AS is_landlord_edition,
    ts_approved,
    ts_expired,
    ts_visualized
FROM
    datalake_ebdb_clean.pre_proposal_aud AS pp
JOIN
    datalake_ebdb_country.house AS ch
        ON ch.id_house = pp.id_house