SELECT
    id,
    cpf,
    dataExpedicaoRG as dt_rg_created,
    dataNascimento as dt_birth,
    email,
    nome as name,
    rg,
    sexo as gender,
    telefone as phone_number,
    telefoneSecundario as secondary_phone,
    contrato_id as id_contract,
    bairro as neighborhood,
    cep as zip_code,
    cidade as city,
    complemento as complement,
    endereco as address,
    estadoCivil as marital_status,
    numero as number,
    orgaoExpedidor as issuing_body,
    profissao as profession,
    estado_id as state_id,
    tipo as type,
    nacionalidade as nationality,
    atualizadoEm as ts_updated,
    criadoEm as ts_created,
    usuario_id as id_user,
    vaiMorar as will_live,
    legalRepresentative_cpf as legal_representative_cpf,
    legalRepresentative_email as legal_representative_email,
    legalRepresentative_nome as legal_representative_name,
    legalRepresentative_rg as legal_representative_rg,
    withRepresentative as is_with_representative
FROM datalake_ebdb_raw.contratopessoa