SELECT
    dataCalculoComissaoCorretor AS ts_agent_comission_calculated,
    diaMesPagarProprietario AS owner_pay_day_of_month,
    parcelaSeguroFianca AS rental_guarantee_installment,
    id,
    fimDesconto AS dt_discount_ended,
    inicioDesconto AS dt_discount_started,
    valorDesconto AS discount,
    responsavelIptu AS responsible_for_iptu,
    pagtoIptu_parcelas AS iptu_installment,
    pagtoIptu_valor AS iptu,
    pagtoSeguroFianca_parcelas AS rental_pay_guarantee_installment, -- force to memory: column name repeated
    pagtoSeguroFianca_valor AS rental_guarantee,
    taxaAdministracaoMensal AS monthly_administration_fee,
    agenciaBanco AS bank_agency,
    comissao AS commission,
    contaBanco AS bank_account,
    dataEntrada AS dt_entered,
    dataFim AS dt_ended,
    dataInicio AS dt_started,
    nomeBanco AS bank_name,
    paganteIptu AS paying_iptu,
    valorCondominio AS condo_price,
    valorIptu AS value_iptu, -- force to memory: column name repeated
    priceindextype AS price_index_type,
    enviadoAvisoDeIGPMEm AS ts_igpm_notice_sent,
    autoIgpm AS is_auto_igpm,
    admFeeChargeType AS adm_fee_charge_type,
    promotionalAdmFee AS promotional_adm_fee,
    promotionalPeriod AS promotional_period,
    homeInsuranceType AS home_insurance_type,
    ownerBenefit_parcelas AS owner_benefit_installment,
    ownerBenefit_valor AS owner_benefit,
    lastIGPMAdjustment_id AS id_last_IGPM_adjustment,
    vacancyDate AS dt_vacancy,
    reservationValue AS reservation_price
FROM
    datalake_ebdb_raw.`contratofull`
