SELECT
    id as id_inspection,
    contrato_id as id_contract,
    imovel_id as id_house,
    bigint(ref_id) as id_ref,
    vistoriador_id as id_user_inspector,
    finalReportPdfId as id_final_report_pdf,
    schedule_id as id_booking,
    partialReportPdfId as id_partial_report_pdf,
    REV as rev,
    rEVTYPE as rev_type,
    aprovadoInquilino as is_tenant_approved,
    aprovadoInquilino_MOD as mod_is_tenant_approved,
    aprovadoProprietario as is_owner_approved,
    aprovadoProprietario_MOD as mod_is_owner_approved,
    browserAprovacaoInquilino as browser_tenant_approval,
    browserAprovacaoProprietario as browser_owner_approval,
    comentarioInquilino as tenant_comment,
    comentarioProprietario as owner_comment,
    hash,
    ipAprovacaoInquilino as ip_tenant_approval,
    ipAprovacaoProprietario as ip_owner_approval,
    shortRevisarInq as short_review_tenant,
    shortRevisarProp as short_review_owner,
    soAprovacaoInquilino as os_tenant_approval,
    soAprovacaoProprietario as os_owner_approval,
    status,
    status_MOD as mod_status,
    tipo as type,
    comentarioInquilino_MOD as mod_tenant_comment,
    comentarioProprietario_MOD as mod_owner_comment,
    itenCommented as is_item_commented,
    finalReportCreated as is_final_report_created,
    reportSentStatus as report_sent_status,
    reportSentStatus_MOD as mod_report_sent_status,
    lastReportSent as last_report_sent,
    lastReportSent_MOD as mod_last_report_sent,
    expiraEm_MOD as mod_ts_expired,
    reportFinished as is_report_finished,
    reportFinished_MOD as mod_is_report_finished,
    keyLocation as key_location,
    keyLocation_MOD as mod_key_location,
    keyLocationDetails as key_location_details,
    inspectorGotAllInfo as has_inspector_got_all_info,
    version,
    version_MOD as mod_version,
    schedule_MOD as mod_id_booking,
    scheduleObservations as schedule_observations,
    scheduleObservations_MOD as mod_schedule_observations,
    reportRevised as report_revised,
    reportRevised_MOD as mod_report_revised,
    scheduleDoubleChecked as is_schedule_double_checked,
    scheduleDoubleChecked_MOD as mod_is_schedule_double_checked,
    lastSynced_MOD as mod_ts_last_synced,
    mode,
    mode_MOD as mod_mode,
    dataAprovacaoInquilino as ts_tenant_approved,
    dataAprovacaoProprietario as ts_owner_approved,
    expiraEm as ts_expired,
    partialOwnerReportSentAt as ts_partial_owner_report_sent,
    partialTenantReportSentAt as ts_partial_tenant_report_sent,
    lastSynced as ts_last_synced,
    dataVistoria as dt_inspected,
    finalReportSentAt as dt_final_report_sent
FROM
    datalake_ebdb_raw.vistoria_aud
