SELECT
  id as id_offer,
  REV,
  REVTYPE as rev_type,
  client_id as id_client,
  house_id as id_house,
  rentFlow_id as id_rent_flow,
  firestoreId as id_firestore,
  godfatherId as id_godfather,
  originalCondo as original_condo,
  originalHomeInsurance as original_home_insurance,
  originalIptu as original_iptu,
  originalRent as original_rent,
  rent,
  status,
  turn,
  expirationDate as ts_expiration,
  iteration,
  rejectionReason as rejection_reason,
  status_MOD as MOD_status,
  turn_MOD as MOD_turn,
  type,
  godfatherUpdatedAt as ts_godfather_updated,
  residentName as resident_name
FROM datalake_ebdb_raw.Offer_AUD
