SELECT
  id,
  firestoreId as id_firestore,
  godfatherId as id_godfather,
  client_id as id_client,
  house_id as id_house,
  rentFlow_id as id_rent_flow,
  originalCondo as original_condo,
  originalHomeInsurance as original_home_insurance,
  originalIptu as original_iptu,
  originalRent as original_rent,
  rent,
  status,
  turn,
  rejectionReason as rejection_reason,
  criadoEm as ts_created,
  atualizadoEm as ts_updated,
  iteration,  
  expirationDate as ts_expired,
  type,
  godfatherUpdatedAt as ts_updated_godfather,
  residentName as resident_name,
  firestoreId_unique as is_id_firestore_unique
FROM datalake_ebdb_raw.offer
