SELECT
    id AS id_pre_proposal,
    REV AS rev,
    rEVTYPE AS rev_type,
    aceitoAluguel AS has_rental_accepted,
    aceitoAluguel_MOD AS mod_has_rental_accepted,
    aceitoComprovarRenda AS has_income_proof_accepted,
    aceitoComprovarRenda_MOD AS mod_has_income_proof_accepted,
    aceitoEncargos AS has_charge_accepted,
    aceitoEncargos_MOD AS mod_has_charge_accepted,
    aluguel AS rent,
    aluguel_MOD AS mod_rent,
    dataAprovacao AS ts_approved,
    edicao AS edition,
    edicao_MOD AS mod_edition,
    proprietarioAceitouCondicoes5A AS is_owner_accept_condition,
    status,
    status_MOD AS mod_status,
    animais_id AS id_animals,
    animais_MOD AS mod_animals,
    condicoes_MOD AS mod_conditions,
    imovel_id AS id_house,
    imovel_MOD AS mod_house,
    quandoVaiMudar_id AS id_when_will_schedule,
    quandoVaiMudar_MOD AS mod_when_will_schedule,
    quemVaiMorar_id AS id_who_will_live,
    quemVaiMorar_MOD AS mod_who_will_live,
    usuario_id AS id_user,
    usuario_MOD AS mod_user,
    aluguelOriginal AS original_rent,
    condominioOriginal AS original_condo,
    iptuOriginal AS original_iptu,
    homeOwnerInsuranceOriginalValue AS original_home_insurance,
    expirationDate AS ts_expired,
    rejectionReason AS rejection_reason,
    code,
    visualizedDate AS ts_visualized,
    visualizedDate_MOD AS mod_ts_visualized
FROM
    datalake_ebdb_raw.preproposta_aud
