SELECT
    id,
    REV as rev,
    rEVTYPE as rev_type,
    bairro as neighborhood,
    cep as zip_code,
    cidade as city,
    complemento as complement,
    contribuiNoImovelAtual as has_contributed_to_current_house,
    cpf,
    dataAdmissao as dt_admission_date,
    dataExpedicaoRG as dt_rg_created,
    dataNascimento as dt_birth,
    dataValidadeDocumento as ts_document_validity,
    email,
    empVinculo as company_link,
    empresa as company,
    endereco as address,
    estadoCivil as marital_status,
    motivoLocacao as rental_reason,
    nacionalidade as nationality,
    nome as name,
    nomeImobiliariaOuProprietario as name_of_real_estate_company_or_owner,
    nomeMae as mothers_name,
    numero as number,
    numeroDependentes as number_of_dependents,
    orgaoExpedidor as issuing_body,
    paisOrigem as country_of_origin,
    pastaDriveId as id_drive_folder,
    profissao as profession,
    ramal as branch,
    refNome as name_reference,
    refTelefone as phone_number_reference,
    refVinculo as link_reference,
    rendaMensal as monthly_salary,
    rg,
    sexo as gender,
    situacaoAtual as current_situation,
    telefone as phone_number,
    telefoneEmpresa as company_phone_number,
    telefoneImobiliariaOuProprietario as phone_number_of_real_estate_company_or_owner,
    telefoneResidencial as residential_phone_number,
    tempoDeResidenciaAnos as years_lived_in_residence,
    tipo as type,
    tipoPessoa as person_type,
    vaiMorar as will_live,
    proposta_id as id_proposal,
    origemRenda as source_of_income,
    rendimentoAdicional as additional_income,
    documentationExtraComment as documentation_extra_comment,
    documentationExtraComment_MOD as mod_documentation_extra_comment,
    estado_id as id_state,
    estado_MOD as mod_state,
    flagRepresentante as flag_agent,
    nomeProprietario as owner_name,
    cpfProprietario as owner_cpf,
    docxFolderId as id_docx_folder
FROM
    datalake_ebdb_raw.propostaproponente_aud