CREATE EXTERNAL TABLE datalake_clean.zendesk_ticket (
  id string,
  url string,
  external_id string,
  type string,
  subject string,
  raw_subject string,
  description string,
  priority string,
  status string,
  recipient string,
  requester_id string,
  submitter_id string,
  assignee_id string,
  organization_id string,
  group_id string,
  forum_topic_id string,
  problem_id string,
  has_incidents boolean,
  due_at string,
  via_id int,
  satisfaction_rating_score string,
  satisfaction_rating_comment string,
  followup_ids string,
  sharing_agreement_ids string,
  ticket_form_id string,
  brand_id string,
  allow_channelback boolean,
  is_public boolean,
  created_at string,
  updated_a string
)
STORED AS PARQUET
LOCATION 's3://5a-datalake/clean/zendesk/ticket/'
tblproperties ("parquet.compress"="SNAPPY");