drop table if exists dim_offer;
create table dim_offer (
  sk_offer integer,
  id_offer integer,
  id_godfather integer,
  last_offered_rent integer,
  original_rent integer,
  original_condo integer,
  dt_analysis timestamp,
  editing varchar,
  status varchar,
  id_user integer,
  id_property integer,
  dt_created timestamp,
  dt_updated timestamp,
  dt_timestamp timestamp,
  offer_submitted boolean,
  ultimo_update_edicao integer,
  dt_first_sent timestamp,
  last_updated_date timestamp,
  expiration_date timestamp,
  last_rent_offered_by_tenant decimal(18,4),
  last_rent_offered_by_owner decimal(18,4),
  rejection_reason varchar(255),
  animais_condition integer,
  quando_vai_mudar_condition integer,
  quem_vai_morar_condition integer,
  special_conditions_count integer,
  remove_conditions integer,
  include_conditions integer,
  maintenance_or_repair_conditions integer,
  replace_or_modify_conditions integer,
  price_conditions integer,
  other_conditions integer,
  type varchar(255)
);