DROP TABLE IF EXISTS public.dim_offer;
CREATE TABLE public.dim_offer (
  sk_offer INTEGER PRIMARY KEY,
  id_offer INTEGER,
  id_godfather INTEGER,
  id_firestore VARCHAR(255),
  id_user INTEGER,
  id_property INTEGER,
  country_code VARCHAR,
  editing VARCHAR,
  status VARCHAR,
  rejection_reason VARCHAR(255),
  type VARCHAR(255),
  app_type VARCHAR(255),
  utm_source VARCHAR(255),
  utm_medium VARCHAR(2000),
  utm_campaign VARCHAR(2000),
  utm_content VARCHAR(255),
  utm_term VARCHAR(255),
  mkt_category VARCHAR(255),
  mkt_flow VARCHAR(255),
  mkt_completion VARCHAR(255),
  mkt_origin VARCHAR(255),
  mkt_channel VARCHAR(255),
  mkt_medium VARCHAR(255),
  mkt_source VARCHAR(255),
  mkt_platform VARCHAR(255),
  last_offered_rent INTEGER,
  original_rent INTEGER,
  original_condo INTEGER,
  is_instant_offer BOOLEAN,
  flg_branded BOOLEAN,
  offer_submitted BOOLEAN,
  first_rent_offered_by_tenant DECIMAL(18,4),
  first_rent_offered_by_owner DECIMAL(18,4),
  last_rent_offered_by_tenant DECIMAL(18,4),
  last_rent_offered_by_owner DECIMAL(18,4),
  number_of_tenants INT2,
  number_of_kids INT2,
  rental_reason VARCHAR(255),
  rental_urgency VARCHAR(255),
  tenant_description VARCHAR(5000),
  tenant_pets_info VARCHAR(255),
  tenant_type VARCHAR(255),
  has_pets BOOLEAN,
  ts_email_sent_to_owner TIMESTAMP,
  last_updated_date TIMESTAMP,
  expiration_date TIMESTAMP,
  dt_analysis TIMESTAMP,
  dt_first_sent TIMESTAMP,
  dt_created TIMESTAMP,
  dt_updated TIMESTAMP,
  dt_timestamp TIMESTAMP
);

ALTER TABLE public.dim_offer OWNER TO databricks;
