drop table if exists dim_lead;
create table if not exists dim_lead (
  sk_lead bigint primary key,
  id bigint,
  area_total integer,
  bairro varchar(200),
  captado_em date,
  cep varchar(9),
  cidade varchar(200),
  complemento varchar(200),
  endereco varchar(200),
  nome_anunciante varchar(255),
  numero varchar(200),
  numero_banheiros integer,
  numero_quartos integer,
  numero_suites integer,
  url_anuncio varchar(255),
  telefone_anunciante varchar(100),
  tipo varchar(255),
  email varchar(250),
  email_captador varchar(250),
  telefone_captador varchar(250),
  dentro_area_atuacao integer,
  lat numeric(10,7),
  lng numeric(10,7),
  condominio integer,
  iptu integer,
  ub_page_variant varchar(255),
  reason varchar(255),
  reason_detail varchar(255),
  status varchar(255),
  processado smallint,
  origem varchar(255),
  external_id varchar(255),
  mencionar integer,
  automatically_discarded integer,
  proprietario_nome varchar(255),
  proprietario_email varchar(255),
  affiliate_type varchar,
  dados_afiliado_inicio_atuacao timestamp without time zone,
  dados_afiliado_cidade_atuacao varchar(100),
  region_id integer,
  atualizado_em timestamp without time zone,
  criado_em timestamp without time zone,
  utm_source varchar(255),
  utm_medium varchar(255),
  utm_campaign varchar(255),
  utm_content varchar(255),
  utm_term varchar(255),
  tracking_platform varchar(255),
  tracking_region varchar(255),
  tracking_city varchar(255),
  network varchar(255),
  usuario_que_indicou_id varchar(255),
  score_factor bigint,
  is_b2b boolean,
  b2b_type varchar,
  sales_company varchar(255),
  ts_sales_company_sent timestamp,
  sale_price bigint,
  is_for_rent boolean,
  is_for_sale boolean,
  load_timestamp timestamp without time zone
) ;