drop table if exists dim_user;

CREATE TABLE dim_user (
  sk_user bigint not null primary key,
  id bigint,
  nome varchar(255) DEFAULT NULL,
  bairro varchar(255) DEFAULT NULL,
  cep varchar(255) DEFAULT NULL,
  cidade varchar(255) DEFAULT NULL,
  complemento varchar(255) DEFAULT NULL,
  cpf varchar(255) DEFAULT NULL,
  data_nascimento timestamp DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  email_alternativo varchar(255) DEFAULT NULL,
  endereco varchar(255) DEFAULT NULL,
  numero varchar(255) DEFAULT NULL,
  facebook_id varchar(255) DEFAULT NULL,
  linkedin_id varchar(255) DEFAULT NULL,
  sexo varchar(255) DEFAULT NULL,
  telefone_principal varchar(255) DEFAULT NULL,
  estado_abreviacao varchar(200) DEFAULT NULL,
  estado_nome varchar(200) DEFAULT NULL,
  contadorlogin bigint DEFAULT NULL,
  nao_me_prgunte_telefone integer DEFAULT NULL,
  bloqueado integer DEFAULT NULL,
  rg varchar(30) DEFAULT NULL,
  detalhes_lead_busca_guiada varchar(2000),
  recebeu_busca_guiada integer DEFAULT NULL,
  dadosagente_email_coordinator varchar(255) DEFAULT NULL,
  dadosagente_cidade varchar(255) DEFAULT NULL,
  dadosagente_atuacao varchar(100) DEFAULT NULL,
  dadosagente_perfil varchar(255) DEFAULT NULL,
  dadosagente_numero_creci varchar(255) DEFAULT NULL,
  dadosagente_ativo integer DEFAULT NULL,
  aceita_sms integer DEFAULT NULL,
  preferencia_contato varchar(255) DEFAULT NULL,
  prefere_contato varchar(255) DEFAULT NULL,
  data_clickanuncie timestamp DEFAULT NULL,
  dadosbancarios_banco_codigo varchar(255) DEFAULT NULL,
  dadosbancarios_banco varchar(255) DEFAULT NULL,
  dadosbancarios_agencia varchar(255) DEFAULT NULL,
  dadosbancarios_conta_corrente varchar(255) DEFAULT NULL,
  dadosbancarios_cpf_cnpj varchar(255) DEFAULT NULL,
  dadosbancarios_nome varchar(255) DEFAULT NULL,
  dadosbancarios_outro_titular integer DEFAULT NULL,
  dadosbancarios_tipo_conta varchar(255) DEFAULT NULL,
  nao_enviar_aviso_mensal_procura integer NULL,
  cod_ativacao_sms varchar(6) DEFAULT NULL,
  data_geracao_cod_sms date DEFAULT NULL,
  tipo_admin varchar(255) DEFAULT NULL,
  last_update_oportunidade timestamp DEFAULT NULL,
  data_avisado_condicoes_cardiff timestamp DEFAULT NULL,
  data_captadora_enviou_email timestamp DEFAULT NULL,
  data_enviado_app_e_cardiff timestamp DEFAULT NULL,
  google_id varchar(255) DEFAULT NULL,
  account_kit_id varchar(255) DEFAULT NULL,
  dadosfotografo_inicio_contrato timestamp,
  dadosfotografo_tipo_contrato varchar(255) DEFAULT NULL,
  dadosfotografo_preferencia_pagamento varchar(255) DEFAULT NULL,
  dadosfotografo_ativo integer DEFAULT NULL,
  dadosvendedor_inicio_contrato timestamp,
  dadosvendedor_nome_gerente varchar(255) DEFAULT NULL,
  dadosafiliado_indicacao_shorturl varchar(100) DEFAULT NULL,
  dadosafiliado_inicio_atuacao timestamp,
  dadosafiliado_ultim_calculo_comissao_indicado timestamp DEFAULT NULL,
  dadosafiliado_verificado integer DEFAULT NULL,
  dadosafiliado_tipo varchar(255) DEFAULT NULL,
  dadosafiliado_cidade_atuacao varchar(100) DEFAULT NULL,
  dadosafiliado_principais_bairros_atuacao varchar(2000),
  dadosafiliado_preferencia_pagamento varchar(255) DEFAULT NULL,
  dadosafiliado_numero_creci varchar(255) DEFAULT NULL,
  dadosafiliado_semana_ultima_comunicacao_balanco integer DEFAULT NULL,
  dadosafiliado_id_planilha_gdocs varchar(200) DEFAULT NULL,
  dadosafiliado_ativo integer DEFAULT NULL,
  dadosafiliado_custo_aquisicao NUMERIC(18,4),
  dadosgerenteContas_inicio_contrato timestamp,
  dadosgerenteContas_nome varchar(255) DEFAULT NULL,
  active integer DEFAULT NULL,
  dados_agente_id integer,
  dados_fotografo_id integer,
  dados_vendedor_id integer,
  dados_afiliado_id integer,
  flg_doorman_affiliate integer,
  sk_doorman_joined_date bigint,
  tem_imovel varchar(10),
  tem_app_inquilino varchar(10),
  tem_contrato_ativo varchar(10),
  inquilino varchar(10),
  first_booking_date timestamp,
  first_booking_confirmed_date timestamp,
  first_visit_date timestamp,
  first_visit_confirmed_date timestamp,
  first_pre_proposal_date timestamp,
  first_proposal_accepted_date timestamp,
  first_contract_date timestamp,
  first_signed_contract timestamp,
  first_dt_document_sent timestamp DEFAULT NULL,
  last_dt_document_sent timestamp DEFAULT NULL,
  first_dt_sent_to_insurance timestamp DEFAULT NULL,
  criado_em timestamp ,
  atualizado_em timestamp DEFAULT NULL,
  load_timestamp TIMESTAMP WITHOUT TIME ZONE,
  network varchar(255) DEFAULT NULL,
  visits_booked integer,
  visits_realized integer,
  visits_expected_to_happen integer
) ;