CREATE TABLE public.dim_date (
	sk_date int8 NOT NULL,
	"date" date NULL,
	"year" int4 NULL,
	"month" int4 NULL,
	month_name varchar(15) NULL,
	"day" int4 NULL,
	day_of_year int4 NULL,
	week_day int4 NULL,
	weekday_name varchar(15) NULL,
	calendar_week int4 NULL,
	brz_date varchar(10) NULL,
	usa_date varchar(10) NULL,
	universal_date varchar(10) NULL,
	quarter varchar(2) NULL,
	year_quarter varchar(10) NULL,
	year_month varchar(10) NULL,
	year_calendar_week varchar(10) NULL,
	weekend varchar(10) NULL,
	is_brz_holiday varchar(10) NULL,
	brz_season varchar(10) NULL,
	week_start date NULL,
	week_end date NULL,
	month_start date NULL,
	month_end date NULL,
	last_day date NULL,
	last_week date NULL,
	last_2_weeks date NULL,
	last_4_weeks date NULL,
	last_month date NULL,
	last_quarter date NULL,
	last_year date NULL
);