drop table if exists dim_contract;
create table dim_contract (
  sk_contract bigint primary key,
  id_contract bigint,
  rent numeric(14,2),
  day_month_due smallint,
  guarantee varchar,
  type varchar,
  status varchar,
  dt_start date,
  ts_signature timestamp,
  ts_draft_approved timestamp,
  dt_entrance date,
  dt_intended_end date,
  dt_annulment date,
  condo_payer varchar,
  condo_responsible varchar,
  iptu_payer varchar,
  iptu_responsible varchar,
  rental_insurance_installments smallint,
  rental_insurance_value numeric(14,2),
  home_insurance_installments smallint,
  home_insurance_value numeric(14,2),
  first_rental_commission numeric(14,2),
  monthly_administration_fee numeric(5,4),
  condo numeric(14,2),
  iptu numeric(14,2),
  tenant_service_fee numeric(5,2),
  signature_type varchar,
  closing_status varchar,
  ts_created timestamp,
  ts_updated timestamp,
  ts_canceled timestamp,
  cancellation_reason varchar,
  is_b2b boolean,
  b2b_type varchar,
  b2b_prime_type varchar,
  ts_analyst_annulment_input timestamp,
  version varchar,
  is_ongoing_contract boolean,
  ts_load timestamp
)
;
