drop table if exists dim_lead;
create table if not exists dim_lead (
  sk_lead bigint primary key,
  id bigint,
  anuncio_criado_em date,
  area_total integer,
  bairro varchar(200),
  captado_em date,
  cep varchar(9),
  cidade varchar(200),
  complemento varchar(200),
  endereco varchar(200),
  endereco_captado text,
  nome_anunciante varchar(255),
  numero varchar(200),
  numero_banheiros integer,
  numero_quartos integer,
  numero_suites integer,
  url_anuncio varchar(255),
  valor integer,
  telefone_anunciante varchar(100),
  valor_por_metro_quad numeric(18,4),
  valor_por_quartos numeric(18,4),
  tipo varchar(255),
  email varchar(250),
  email_captador varchar(250),
  telefone_captador varchar(250),
  hot integer,
  proximo_followup timestamp without time zone,
  gerado_a_partir_de_deduplicacao integer,
  dentro_area_atuacao integer,
  sistema_enviou_email_via_classificado integer,
  lat numeric(10,7),
  lng numeric(10,7),
  condominio integer,
  iptu integer,
  reason varchar(255),
  reason_detail varchar(255),
  status varchar(255),
  envio_email_apresentacao_pos timestamp without time zone,
  envio_email_apresentacao_pre timestamp without time zone,
  processado smallint,
  origem varchar(255),
  external_id varchar(255),
  mencionar integer,
  referencia varchar(255),
  automatically_discarded integer,
  estado_nome varchar(255),
  estado_abrev varchar(255),
  lead_imobiliaria varchar(255),
  proprietario_nome varchar(255),
  proprietario_email varchar(255),
  dados_corretor_tipo_afiliado varchar(200),
  dados_corretor_nome varchar(250),
  dados_corretor_email varchar(250),
  dados_gerente_contas_nome varchar(250),
  dados_gerente_contas_email varchar(250),
  dados_afiliado_inicio_atuacao timestamp without time zone,
  dados_afiliado_cidade_atuacao varchar(100),
  region_id integer,
  atualizado_em timestamp without time zone,
  criado_em timestamp without time zone,
  url_source varchar(255),
  utm_source varchar(255),
  utm_medium varchar(255),
  utm_campaign varchar(255),
  utm_content varchar(255),
  utm_term varchar(255),
  tracking_platform varchar(255),
  tracking_region varchar(255),
  tracking_city varchar(255),
  network varchar(255),
  usuario_que_indicou_id varchar(255),
  flg_city_served boolean,
  flg_latlng_served boolean,
  flg_location_served boolean,
  score_factor bigint,
  is_b2b boolean,
  b2b_type varchar,
  load_timestamp timestamp without time zone
) ;