drop table if exists dim_pre_proposal;
create table dim_pre_proposal (
  sk_pre_proposal integer,
  id_pre_proposal integer,
  code varchar,
  renting_value integer,
  renting_original_value integer,
  condo_original_value integer,
  dt_approved timestamp,
  editing varchar,
  status varchar,
  owner_accepted_5a_conditions integer,
  id_user integer,
  id_property integer,
  dt_created timestamp,
  dt_updated timestamp,
  dt_timestamp timestamp without time zone,
  offer_submitted boolean,
  ultimo_update_edicao integer,
  dt_first_sent timestamp,
  last_updated_date timestamp,
  expiration_date timestamp,
  last_rent_value_tenant decimal(18,4),
  last_rent_value_landlord decimal(18,4),
  total_rent_value decimal(18,4),
  rejection_reason varchar,
  animais_condition integer,
  quando_vai_mudar_condition integer,
  quem_vai_morar_condition integer,
  special_conditions_count integer,
  remove_conditions integer,
  include_conditions integer,
  maintenance_or_repair_conditions integer,
  replace_or_modify_conditions integer,
  other_conditions integer
);