drop table public.fact_house_listing_flows;

create table public.fact_house_listing_flows (
	sk_house_listing_flow bigint NOT NULL,
	sk_condo bigint,
	sk_lead integer,
	sk_lead_conversion integer,
	sk_first_photo_job integer,
	sk_house_listing bigint,
	sk_user_house_registrant integer,
	sk_user_sales_rep integer,
	sk_user_lead_affiliate integer,
	sk_user_task_assignee integer,
	sk_region integer,
	sk_city integer,
	sk_lead_date integer,
	sk_prospect_date integer,
	sk_task_created_date integer,
	sk_task_closed_date integer,
	sk_first_inside_sales_contact_date integer,
	sk_conversion_date integer,
	sk_qualified_date integer,
	sk_opportunity_date integer,
	sk_first_listing_date integer,
	sk_discard_date integer,
	funnel_step varchar(255),
	funnel_drop_reason varchar(255),
	hours_lead_to_prospect decimal(10,1),
	hours_prospect_to_qualified decimal(10,1),
	hours_lead_to_first_inside_sales_contact decimal(10,1),
	hours_prospect_to_first_inside_sales_contact decimal(10,1),
	hours_qualified_to_opportunity decimal(10,1),
	hours_opportunity_to_listing decimal(10,1),
	hours_lead_to_listing decimal(10,1),
	days_lead_to_prospect decimal(10,1),
	days_prospect_to_qualified decimal(10,1),
	days_lead_to_first_inside_sales_contact decimal(10,1),
	days_prospect_to_first_inside_sales_contact decimal(10,1),
	days_qualified_to_opportunity decimal(10,1),
	days_opportunity_to_listing decimal(10,1),
	days_lead_to_listing decimal(10,1),
	days_lead_to_processing decimal(10,1),
	is_exclusive smallint,
	first_isales_intervention varchar(50),
	lead_type varchar(255),
	lead_origin varchar(255),
	lead_utm_source varchar(255),
	lead_utm_medium varchar(255),
	is_branded boolean,
	is_b2b boolean,
	is_doorman boolean,
	is_isales_direct_register boolean,
	is_cx_direct_register boolean,
	has_isales_intervention boolean,
	is_call_center boolean,
	is_lead_reprocessed boolean,
	mkt_branded varchar(255),
	mkt_category varchar(255),
	mkt_flow varchar(255),
	mkt_completion varchar(255),
	mkt_channel varchar(255),
	mkt_platform varchar(255),
	mkt_medium varchar(255),
	mkt_source varchar(255),
	ts_load timestamp default getdate()
)