drop table if exists fact_house_listing_flows;
create table if not exists fact_house_listing_flows
(
 sk_house_listing_flow bigint not null  encode lzo,
 sk_condo bigint   encode lzo,
 sk_lead integer   encode lzo,
 sk_lead_conversion integer   encode lzo,
 sk_first_photo_job integer   encode lzo,
 sk_house_listing bigint   encode lzo,
 sk_user_house_registrant integer   encode lzo,
 sk_user_sales_rep integer   encode lzo,
 sk_user_lead_affiliate integer   encode lzo,
 sk_user_first_task_assignee integer   encode lzo,
 sk_user_last_task_assignee integer   encode lzo,
 sk_region integer   encode lzo,
 sk_city integer   encode lzo,
 sk_partner integer   encode lzo,
 sk_autonomous_agent integer   encode lzo,
 sk_lead_date integer   encode lzo,
 sk_sales_company_lead_sent_date integer   encode lzo,
 sk_prospect_date integer   encode lzo,
 sk_first_task_created_date integer   encode lzo,
 sk_first_task_closed_date integer   encode lzo,
 sk_last_task_created_date integer   encode lzo,
 sk_last_task_closed_date integer   encode lzo,
 sk_first_contact_date integer   encode lzo,
 sk_conversion_date integer   encode lzo,
 sk_qualified_date integer   encode lzo,
 sk_opportunity_date integer   encode lzo,
 sk_first_listing_date integer   encode lzo,
 sk_discard_date integer   encode lzo,
 sk_user_lead_first_discarder integer   encode lzo,
 sk_user_lead_last_discarder integer   encode lzo,
 funnel_step varchar(255)   encode lzo,
 funnel_drop_reason varchar(255)   encode lzo,
 hours_lead_to_prospect numeric(10,1)   encode lzo,
 hours_prospect_to_qualified numeric(10,1)   encode lzo,
 hours_lead_to_first_contact numeric(10,1)   encode lzo,
 hours_prospect_to_first_contact numeric(10,1)   encode lzo,
 hours_qualified_to_opportunity numeric(10,1)   encode lzo,
 hours_opportunity_to_listing numeric(10,1)   encode lzo,
 hours_lead_to_listing numeric(10,1)   encode lzo,
 days_lead_to_prospect numeric(10,1)   encode lzo,
 days_prospect_to_qualified numeric(10,1)   encode lzo,
 days_lead_to_first_contact numeric(10,1)   encode lzo,
 days_prospect_to_first_contact numeric(10,1)   encode lzo,
 days_qualified_to_opportunity numeric(10,1)   encode lzo,
 days_opportunity_to_listing numeric(10,1)   encode lzo,
 days_lead_to_listing numeric(10,1)   encode lzo,
 days_lead_to_processing numeric(10,1)   encode lzo,
 is_exclusive smallint   encode lzo,
 first_isales_intervention varchar(50)   encode lzo,
 lead_type varchar(255)   encode lzo,
 lead_origin varchar(255)   encode lzo,
 lead_tracking_source varchar(255)   encode lzo,
 lead_tracking_medium varchar(255)   encode lzo,
 lead_tracking_platform varchar(255)   encode lzo,
 is_branded boolean,
 is_b2b boolean,
 is_autonomous_agent boolean,
 is_doorman boolean,
 is_isales_direct_register boolean,
 is_cx_direct_register boolean,
 is_ops_direct_register boolean,
 has_isales_intervention boolean,
 has_fup_photo_task boolean,
 is_call_center boolean,
 is_lead_reprocessed boolean,
 affiliate_type varchar(512)   encode lzo,
 is_agent_referral boolean,
 lead_referring_domain varchar(512)   encode lzo,
 lead_referring_category varchar(512)   encode lzo,
 subscription_source varchar(512)   encode lzo,
 mkt_branded varchar(255)   encode lzo,
 mkt_category varchar(255)   encode lzo,
 mkt_flow varchar(255)   encode lzo,
 mkt_completion varchar(255)   encode lzo,
 mkt_origin varchar(255)   encode lzo,
 mkt_channel varchar(255)   encode lzo,
 mkt_platform varchar(255)   encode lzo,
 mkt_medium varchar(255)   encode lzo,
 mkt_source varchar(255)   encode lzo,
 lead_context_origin varchar(255)   encode lzo,
 listing_sale_status varchar(255)   encode lzo,
 ts_opted_out_rent timestamp   encode lzo,
 ts_load timestamp without time zone  default getdate() encode lzo
)
diststyle key
distkey (sk_lead)
;

ALTER TABLE public.fact_house_listing_flows OWNER TO airflow;