drop table public.fact_photo_job;

create table public.fact_photo_job(
  id_photo_job int8,
  sk_house_listing int8,
  sk_region int8,
  sk_user_cancel int8,
  sk_user_photographer int8,
  sk_user_rep int8,
  job_status varchar(255),
  creation_origin varchar(255),
  photo_shoot_contact_name varchar(255),
  photo_shoot_email varchar(255),
  photo_shoot_phone varchar(255),
  photo_shoot_second_phone varchar(255),
  key_withdraw varchar(255),
  key_comments varchar(255),
  photographer_contract_type varchar(255),
  photographer_problem_reason varchar(255),
  cancel_reason varchar(255),
  user_cancel_type varchar(255),
  flexible_schedule int8,
  is_same_day_upload boolean,
  is_anticipated boolean,
  flg_job_on_time boolean,
  approved int8,
  confirmed int8,
  lockbox int8,
  rescheduled boolean,
  sk_date_photographer_accepted int8,
  sk_date_job_created int8,
  sk_date_job_issued int8,
  sk_date_shoot_started int8,
  sk_date_job_scheduled int8,
  sk_date_photos_uploaded int8,
  sk_date_updated int8,
  sk_date_photographer_start int8,
  sk_date_user_cancel int8,
  sk_date_problem_reported int8,
  creation_to_scheduling_diff_minutes decimal(10,1),
  creation_to_scheduling_diff_hours decimal(10,1),
  creation_to_scheduling_diff_days decimal(10,1)
)

ALTER TABLE public.fact_photo_job OWNER TO databricks;