SELECT
    ccv,
    os2ccv,
    cidade,
    deal_quali,
    offer_accepted,
    offer_sent,
    origem,
    operacao,
    visit_booked,
    visit_completed,
    week,
    week_origin
FROM
    datalake_gsheets_raw.target_sale_cohort_demand
