SELECT
    sk_overdue_portfolio_timeline,
    sk_contract,
    id_invoice,
    id_proposal,
    contract_status,
    invoice_type,
    payment_status,
    is_ssn,
    type_ssn,
    recovery_method,
    debtor_type,
    delay_contamined_at_closure,
    delay_contamined_range,
    delay_contract_range,
    contract_overdue_invoices,
    due_amount,
    paid_amount,
    recovered_amount,
    contract_debt,
    business_day,
    is_last_business_days,
    advisory,
    distributor,
    partner,
    is_most_recent_record_month,
    dt_invoice_paid,
    dt_invoice_due,
    dt_invoice_due_adjust,
    dt_month_start,
    dt_month_end,
    dt_reference,
    ts_load,
    NOW() AS ts_snapshot,
    YEAR(NOW()) AS year,
    MONTH(NOW()) AS month,
    DAY(NOW()) AS day
FROM
   dw_collection_recovery_quintoandar.fact_overdue_portfolio_timeline
WHERE DATE_TRUNC("MONTH", dt_month_end) = DATE_TRUNC("MONTH",DATEADD(MONTH, -1, '{load_start_date}'))
