SELECT
    sk_overdue_portfolio_timeline,
    sk_region,
    sk_contract,
    sk_negotiation,
    sk_origin_negotiation,
    id_invoice,
    id_proposal,
    negotiation_installment_number,
    contract_status,
    invoice_type,
    payment_status,
    reason,
    paid_via,
    is_ssn,
    CAST(NULL AS STRING) AS type_ssn,
    CAST(NULL AS STRING) AS recovery_method,
    debtor_type,
    delay_contamined_at_closure,
    delay_contamined_range,
    delay_contract_range,
    contract_overdue_invoices,
    due_amount,
    paid_amount,
    recovered_amount,
    net_recovered_amount,
    contract_debt,
    business_day,
    is_last_business_days,
    is_write_off,
    is_contract_write_off,
    segmentation_queue,
    advisory,
    is_most_recent_record_month,
    dt_invoice_paid,
    dt_invoice_due,
    dt_invoice_due_adjust,
    dt_write_off,
    dt_month_start,
    dt_month_end,
    dt_reference,
    ts_load,
    NOW() AS ts_snapshot,
    YEAR(NOW()) AS year,
    MONTH(NOW()) AS month,
    DAY(NOW()) AS day,
    CAST(NULL AS STRING) AS segmentation_queue_timeline,
    CAST(NULL AS STRING) AS segmentation_queue_description_timeline,
    CAST(NULL AS STRING) AS agreement_queue_timeline,
    CAST(NULL AS STRING) AS agreement_queue_description_timeline,
    CAST(NULL AS STRING) AS eviction_queue_timeline,
    CAST(NULL AS STRING) AS eviction_queue_description_timeline,
    delay_invoice_at_reference,
    delay_first_payment_default,
    is_first_payment_default,
    segmentation_queue_description,
    agreement_queue,
    agreement_queue_description,
    eviction_queue,
    eviction_queue_description,
    sk_agency,
    recovery_channel,
    has_app_action_event,
    CAST(NULL AS BOOLEAN) AS has_matthew_interaction
FROM
   dw_collection_recovery_quintoandar.fact_overdue_portfolio_timeline
WHERE DATE_TRUNC("MONTH", dt_month_end) = DATE_TRUNC("MONTH",DATEADD(MONTH, -1, '{load_start_date}'))
