CREATE TABLE IF NOT EXISTS staging.fact_facebook_ads_daily_ads_insights (
	sk_ad BIGINT,
    ad_id BIGINT,
    sk_date INTEGER,
    account_id BIGINT,
    campaign_id BIGINT,
    adset_id BIGINT,
    android_smartphone_impressions DOUBLE PRECISION,
    android_smartphone_reach INTEGER,
    android_smartphone_total_clicks INTEGER,
    android_tablet_impressions DOUBLE PRECISION,
    android_tablet_reach INTEGER,
    android_tablet_total_clicks INTEGER,
    desktop_impressions DOUBLE PRECISION,
    desktop_reach INTEGER,
    desktop_total_clicks INTEGER,
    iphone_impressions DOUBLE PRECISION,
    iphone_reach INTEGER,
    iphone_total_clicks INTEGER,
    ipad_impressions DOUBLE PRECISION,
    ipad_reach INTEGER,
    ipad_total_clicks INTEGER,
    ipod_impressions DOUBLE PRECISION,
    ipod_reach INTEGER,
    ipod_total_clicks INTEGER,
    other_impressions DOUBLE PRECISION,
    other_reach INTEGER,
    other_total_clicks INTEGER,
    total_reach INTEGER,
    total_impressions DOUBLE PRECISION,
    total_clicks INTEGER,
    total_spend DOUBLE PRECISION,
    dt_created VARCHAR
);