SELECT
    CECASENO AS id_case,
    CEDOSSIERID AS id_dossier,
    CESSNUM AS id_client,
    REGEXP_REPLACE(CESSNUM, '[^0-9]', '') AS id_client_clean,
    CECRTID AS id_court,
    CEEXTLWYR AS id_external_attorney,
    CERESPLWYR AS id_responsible_attorney,
    CESUPVLWYR AS id_supervisor_attorney,
    CELWYRAGENCY AS id_attorney_agency,
    CESTATLWYR AS id_status_attorney,
    CEBRANCH AS id_branch,
    CELWYRPRVAGN AS id_previous_attorney_agency,
    CEPRVAGN AS id_previous_agency,
    CEACTOR AS plaintiff_name,
    CENAME AS debtor_name,
    CENAME2 AS debtor_name_2,
    CEADDR1 AS address_line_1,
    CEADDR2 AS address_line_2,
    CECITY AS city,
    CESTATE AS state,
    CEZIP AS zip_code,
    CEPHONE AS home_phone,
    CEBNAME AS business_name,
    CEBADDR1 AS business_address_line_1,
    CEBADDR2 AS business_address_line_2,
    CEBCITY AS business_city,
    CEBSTATE AS business_state,
    CEBZIP AS business_zip_code,
    CEBPHONE AS business_phone,
    CEBPEXT AS business_phone_extension,
    CEPRVNAM AS previous_name,
    CEPRVNM2 AS previous_name_2,
    CEPRVAD1 AS previous_address_line_1,
    CEPRVAD2 AS previous_address_line_2,
    CEPRVCTY AS previous_city,
    CEPRVSTA AS previous_state,
    CEPRVZIP AS previous_zip_code,
    CETYPE AS process_type,
    CESUBTYPE AS case_subtype,
    CEPROD AS product_type,
    CECOMM AS case_comment,
    CECLOSECOMM AS close_comment,
    CECURRENCY AS currency_code,
    CEREASON AS closure_reason,
    CERESULT AS closure_result,
    CETHDACT AS third_party_name,
    CESALCD AS greeting_code,
    CEACAC1 AS action_code_class_1,
    CEACAC2 AS action_code_class_2,
    CEACAC3 AS action_code_class_3,
    CEACLC1 AS letter_code_class_1,
    CEACLC2 AS letter_code_class_2,
    CEACLC3 AS letter_code_class_3,
    CEACRC1 AS result_code_class_1,
    CEACRC2 AS result_code_class_2,
    CEACRC3 AS result_code_class_3,
    CELASTAC AS last_action_code,
    CELASTLC AS last_letter_code,
    CELASTRC AS last_result_code,
    CASE
        WHEN CESTATUS = 'N' THEN 'New'
        WHEN CESTATUS = 'A' THEN 'Active'
        WHEN CESTATUS = 'F' THEN 'Finalized'
        WHEN CESTATUS = 'P' THEN 'Pending'
        WHEN CESTATUS = 'C' THEN 'Completed'
        WHEN CESTATUS = 'S' THEN 'Suspended'
        ELSE CESTATUS
    END AS case_status,
    CEACSC1 AS action_score_class_1,
    CEACSC2 AS action_score_class_2,
    CEACSC3 AS action_score_class_3,
    CEASSTAWRD AS adjudicated_assets_amount,
    CEURCAMT AS unrecoverable_amount,
    CELWSTAMT AS lawsuit_amount,
    CELWYPRVAMT AS previous_attorney_amount,
    CELWYAGNAMT AS attorney_agency_amount,
    CEEXPACC AS accessory_expenses_amount,
    CEEXPFEE AS expense_fees_amount,
    CEEXPOTH AS other_expenses_amount,
    CEDISCOUNT AS discount_amount,
    CERCAMT AS cash_recovered_amount,
    CERCFCAMT AS recovery_forecast_percentage,
    CEFORECAST AS win_probability_percentage,
    CEACCEPTDT AS dt_case_accepted,
    CEASGNDT AS dt_case_assigned,
    CEACDT1 AS dt_activity_class_1,
    CEACDT2 AS dt_activity_class_2,
    CEACDT3 AS dt_activity_class_3,
    CELCLUPD AS dt_last_collector_update,
    CELSTACT AS dt_last_activity,
    CELSTCON AS dt_last_contact,
    CENXTCON AS dt_next_contact,
    CEURCDT AS dt_unrecoverable_declaration,
    CELWSTDT AS dt_lawsuit_filed,
    CESTATDT AS dt_status_changed,
    CELWYPRVREF AS dt_previous_attorney_assigned,
    CELWYAGNREF AS dt_attorney_agency_assigned,
    CEDTUPD AS ts_updated,
    NOW() AS ts_load
FROM datalake_cyber_legal_homolog_raw.case
