WITH ranked AS (
    SELECT
        CECASENO AS id_case,
        CEDOSSIERID AS id_dossier,
        CESSNUM AS id_client,
        REGEXP_REPLACE(CESSNUM, '[^0-9]', '') AS id_client_clean,
        CECRTID AS id_court,
        CEEXTLWYR AS id_external_attorney,
        CERESPLWYR AS id_responsible_attorney,
        CESUPVLWYR AS id_supervisor_attorney,
        CELWYRAGENCY AS id_attorney_agency,
        CESTATLWYR AS id_status_attorney,
        CEBRANCH AS id_branch,
        CELWYRPRVAGN AS id_previous_attorney_agency,
        CEPRVAGN AS id_previous_agency,
        CEACTOR AS plaintiff_name,
        CENAME AS debtor_name,
        CENAME2 AS debtor_name_2,
        CEADDR1 AS address_line_1,
        CEADDR2 AS address_line_2,
        CECITY AS city,
        CESTATE AS state,
        CEZIP AS zip_code,
        CEPHONE AS home_phone,
        CEBNAME AS business_name,
        CEBADDR1 AS business_address_line_1,
        CEBADDR2 AS business_address_line_2,
        CEBCITY AS business_city,
        CEBSTATE AS business_state,
        CEBZIP AS business_zip_code,
        CEBPHONE AS business_phone,
        CEBPEXT AS business_phone_extension,
        CEPRVNAM AS previous_name,
        CEPRVNM2 AS previous_name_2,
        CEPRVAD1 AS previous_address_line_1,
        CEPRVAD2 AS previous_address_line_2,
        CEPRVCTY AS previous_city,
        CEPRVSTA AS previous_state,
        CEPRVZIP AS previous_zip_code,
        CETYPE AS process_type,
        CESUBTYPE AS case_subtype,
        CEPROD AS product_type,
        CECOMM AS case_comment,
        CECLOSECOMM AS close_comment,
        CECURRENCY AS currency_code,
        CEREASON AS closure_reason,
        CERESULT AS closure_result,
        CETHDACT AS third_party_name,
        CESALCD AS greeting_code,
        CEACAC1 AS action_code_class_1,
        CEACAC2 AS action_code_class_2,
        CEACAC3 AS action_code_class_3,
        CEACLC1 AS letter_code_class_1,
        CEACLC2 AS letter_code_class_2,
        CEACLC3 AS letter_code_class_3,
        CEACRC1 AS result_code_class_1,
        CEACRC2 AS result_code_class_2,
        CEACRC3 AS result_code_class_3,
        CELASTAC AS last_action_code,
        CELASTLC AS last_letter_code,
        CELASTRC AS last_result_code,
        CASE
            WHEN CESTATUS = 'N' THEN 'New'
            WHEN CESTATUS = 'A' THEN 'Active'
            WHEN CESTATUS = 'F' THEN 'Finalized'
            WHEN CESTATUS = 'P' THEN 'Pending'
            WHEN CESTATUS = 'C' THEN 'Completed'
            WHEN CESTATUS = 'S' THEN 'Suspended'
            ELSE CESTATUS
        END AS case_status,
        CEACSC1 AS action_score_class_1,
        CEACSC2 AS action_score_class_2,
        CEACSC3 AS action_score_class_3,
        CEASSTAWRD AS adjudicated_assets_amount,
        CEURCAMT AS unrecoverable_amount,
        CELWSTAMT AS lawsuit_amount,
        CELWYPRVAMT AS previous_attorney_amount,
        CELWYAGNAMT AS attorney_agency_amount,
        CEEXPACC AS accessory_expenses_amount,
        CEEXPFEE AS expense_fees_amount,
        CEEXPOTH AS other_expenses_amount,
        CEDISCOUNT AS discount_amount,
        CERCAMT AS cash_recovered_amount,
        CERCFCAMT AS recovery_forecast_percentage,
        CEFORECAST AS win_probability_percentage,
        CEACCEPTDT AS dt_case_accepted,
        CEASGNDT AS dt_case_assigned,
        CEACDT1 AS dt_activity_class_1,
        CEACDT2 AS dt_activity_class_2,
        CEACDT3 AS dt_activity_class_3,
        CELCLUPD AS dt_last_collector_update,
        CELSTACT AS dt_last_activity,
        CELSTCON AS dt_last_contact,
        CENXTCON AS dt_next_contact,
        CEURCDT AS dt_unrecoverable_declaration,
        CELWSTDT AS dt_lawsuit_filed,
        CESTATDT AS dt_status_changed,
        CELWYPRVREF AS dt_previous_attorney_assigned,
        CELWYAGNREF AS dt_attorney_agency_assigned,
        CEDTUPD AS ts_updated,
        year,
        month,
        day,
        NOW() AS ts_load,
        ROW_NUMBER() OVER(PARTITION BY CECASENO ORDER BY MAKE_DATE(year,month,day) DESC) AS rn
    FROM datalake_cyber_legal_raw.case
    WHERE
        MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
)
SELECT
    id_case,
    id_dossier,
    id_client,
    id_client_clean,
    id_court,
    id_external_attorney,
    id_responsible_attorney,
    id_supervisor_attorney,
    id_attorney_agency,
    id_status_attorney,
    id_branch,
    id_previous_attorney_agency,
    id_previous_agency,
    plaintiff_name,
    debtor_name,
    debtor_name_2,
    address_line_1,
    address_line_2,
    city,
    state,
    zip_code,
    home_phone,
    business_name,
    business_address_line_1,
    business_address_line_2,
    business_city,
    business_state,
    business_zip_code,
    business_phone,
    business_phone_extension,
    previous_name,
    previous_name_2,
    previous_address_line_1,
    previous_address_line_2,
    previous_city,
    previous_state,
    previous_zip_code,
    process_type,
    case_subtype,
    product_type,
    case_comment,
    close_comment,
    currency_code,
    closure_reason,
    closure_result,
    third_party_name,
    greeting_code,
    action_code_class_1,
    action_code_class_2,
    action_code_class_3,
    letter_code_class_1,
    letter_code_class_2,
    letter_code_class_3,
    result_code_class_1,
    result_code_class_2,
    result_code_class_3,
    last_action_code,
    last_letter_code,
    last_result_code,
    case_status,
    action_score_class_1,
    action_score_class_2,
    action_score_class_3,
    adjudicated_assets_amount,
    unrecoverable_amount,
    lawsuit_amount,
    previous_attorney_amount,
    attorney_agency_amount,
    accessory_expenses_amount,
    expense_fees_amount,
    other_expenses_amount,
    discount_amount,
    cash_recovered_amount,
    recovery_forecast_percentage,
    win_probability_percentage,
    dt_case_accepted,
    dt_case_assigned,
    dt_activity_class_1,
    dt_activity_class_2,
    dt_activity_class_3,
    dt_last_collector_update,
    dt_last_activity,
    dt_last_contact,
    dt_next_contact,
    dt_unrecoverable_declaration,
    dt_lawsuit_filed,
    dt_status_changed,
    dt_previous_attorney_assigned,
    dt_attorney_agency_assigned,
    ts_updated,
    year,
    month,
    day,
    ts_load
FROM
    ranked
WHERE
    rn = 1
