SELECT
    EXCASENO AS id_case,
    EXID AS id_expense,
    EXCOLLID AS id_attorney,
    EXCOLSUP AS id_supervisor_attorney,
    EXAGENCY AS id_agency,
    EXSTGID AS id_stage,
    EXLOTE AS id_lot,
    EXINVOICE AS id_invoice,
    EXCSTYPE AS case_type,
    EXCSSUBTYPE AS case_subtype,
    EXTYPE AS expense_type,
    EXSTYPE AS expense_subtype,
    EXDESC AS expense_description,
    EXIDESC AS invoice_description,
    EXSUPPLIER AS supplier_name,
    IF(EXAUTFLG = 'Y', TRUE, FALSE) AS is_authorized,
    IF(EXPAYEXP = 'Y', TRUE, FALSE) AS is_payment_made,
    IF(EXSTATUS = '1', TRUE, FALSE) AS is_recovered,
    IF(EXSTATUSAGN = '1', TRUE, FALSE) AS is_reimbursed,
    EXAMT AS expense_amount,
    EXAUTDT AS dt_authorized,
    EXDT AS dt_captured,
    EXINVOICEDT AS dt_invoice,
    EXDTRELCLI AS dt_recovered,
    EXDTRELAGN AS dt_reimbursed,
    EXDTUPD AS ts_updated,
    year,
    month,
    day,
    NOW() AS ts_load
FROM datalake_cyber_legal_homolog_raw.caexpns
