SELECT
    LLCODIGO AS id_legal_batch,
	LLTIPO AS batch_type,
    LLSTATUS AS batch_status,
    LLESCRITORIO AS office,
    LLORIGEM AS origin,
    LLQTD AS quantity,
    LLVALOR AS value,
    LLNOTAFISCAL AS invoice_number,
    LLPROGRAMACAOCONPAG AS conpag_programming,
	LLBANCON AS bank,
	LLCODVW AS code_vw,
	LLUSUARIOC AS user_created,
	LLUSUARIOF AS user_closed,
	LLUSUARIOI AS user_printed,
	LLUSUARIOAP AS user_approved,
	LLUSUARIOR AS user_rejected,
    LLDATACRIACAO AS dt_creation,
    LLDATAFECHAMENTO AS dt_closed,
    LLDATAIMPRESSAO AS dt_print,
    LLDATAAPROVACAO AS dt_approval,
    LLDATAPAGAMENTO AS dt_payment,
    LLDATACANCELAMENTO AS dt_canceled,
    LLDATAREJEICAO AS dt_rejected,
    LLDATAEMISSAO AS dt_issued
FROM
    datalake_cyber_legal_raw.tb_lote_legal
