SELECT
  id,
  id_unidade AS id_municipal_house,
  id_idactum AS id_idactum,
  bpatri_key AS id_patrimonial_assets,
  uf AS state,
  municipio AS city,
  NULLIF(TRIM(bairro), '') AS neighborhood,
  NULLIF(TRIM(logradouro_correios), '') AS street,
  numero AS address_number,
  NULLIF(TRIM(cep), '') AS zipcode,
  NULLIF(TRIM(complemento), '') AS address_details,
  NULLIF(TRIM(unidade), '') AS address_details_unit,
  bloco_id AS address_details_building,
  NULLIF(NULLIF(TRIM(cartorio), 'nan'), '') AS real_estate_register,
  NULLIF(NULLIF(TRIM(matricula), '<NA>'), '') AS real_estate_registry,
  ano_construcao AS building_year,
  m2_terreno AS lot_area,
  m2_construido AS building_area,
  m2_privativo AS private_area,
  estimativa_ipatri AS idactum_price_estimation,
  NULLIF(TRIM(assertividade_estimativa_ipatri), '') AS idactum_price_estimation_quality,
  valorizacao_anual_media AS avg_annual_appreciation_idactum_estimation,
  giro_anual_estimado AS estimated_annual_revenue,
  condominio_estimado AS condominium_estimation,
  valor_venal_iptu AS assessed_iptu_value,
  valor_venal_itbi AS assessed_itbi_value,
  latitude,
  longitude,
  tipo AS kind,
  finalidade AS usage_purpose,
  tipo_utilizacao AS usage_type,
  isento_iptu AS is_iptu_exempt,
  ativo AS is_active,
  dt_load
FROM 
  datalake_idactum_houses_raw.idactum_houses
