SELECT
    id,
    attributes.alias_uid AS id_alias,
    attributes.full_name AS full_name,
    attributes.first_name AS first_name,
    attributes.last_name AS last_name,
    attributes.personal_email AS personal_email,
    attributes.organization_email AS organization_email,
    attributes.bio,
    attributes.location,
    attributes.permission_role AS permission_role,
    attributes.profile_visibility AS profile_visibility,
    attributes.job_role AS job_role,
    attributes.preferred_language AS preferred_language,
    attributes.display_language AS display_language,
    attributes.profile_image_url AS url_profile_image,
    relationships,
    CAST(attributes.total_points AS FLOAT) AS total_points,
    CAST(attributes.daily_logins AS INT) AS daily_logins,
    CAST(attributes.is_active_learner AS BOOLEAN) AS is_active_learner,
    CAST(attributes.daily_digest_email AS BOOLEAN) AS is_daily_digest_email,
    CAST(attributes.weekly_digest_email AS BOOLEAN) AS is_weekly_digest_email,
    CAST(attributes.is_managed AS BOOLEAN) AS is_managed,
    CAST(attributes.restricted AS BOOLEAN) AS is_restricted,
    CAST(attributes.real_time_email_notification AS BOOLEAN) AS is_real_time_email_notification,
    CAST(attributes.login_disabled AS BOOLEAN) AS is_login_disabled,
    TO_TIMESTAMP(attributes.created_at) AS ts_created,
    TO_TIMESTAMP(attributes.first_login_at) AS ts_first_login,
    TO_TIMESTAMP(attributes.last_login_at) AS ts_last_login,
    NOW() AS ts_load
FROM 
    datalake_degreed_raw.users