SELECT
    lsk.sk_lead_3p,
    l.id AS id_lead_3p, 
    COALESCE(lsc.status, 'Unknown') AS status, 
    COALESCE(lsc.growth_status, 'Unknown') AS growth_status,
    COALESCE(c.name, 'Unknown') AS company_name,
    COALESCE(c.tag_real_estate_agency, 'Unknown') AS company_tag,
    COALESCE(l.house_category, 'Unknown') AS house_category,
    COALESCE(l.house_type, 'Unknown') AS house_type, 
    COALESCE(l.house_subtype, 'Unknown') AS house_subtype, 
    COALESCE(l.front_door_type, 'Unknown') AS front_door_type, 
    COALESCE(l.house_description, 'Unknown') AS house_description, 
    COALESCE(l.country, 'Unknown') AS country, 
    COALESCE(l.state, 'Unknown') AS state, 
    COALESCE(l.city, 'Unknown') AS city, 
    COALESCE(l.neighborhood, 'Unknown') AS neighborhood, 
    COALESCE(l.region_slug, 'Unknown') AS region_slug, 
    COALESCE(l.zip_code, 'Unknown') AS zip_code, 
    COALESCE(l.address, 'Unknown') AS address,
    COALESCE(l.number, 'Unknown') AS number,
    COALESCE(l.block, 'Unknown') AS block,
    COALESCE(l.tower, 'Unknown') AS tower,
    COALESCE(l.floor, 'Unknown') AS floor,
    COALESCE(l.complement, 'Unknown') AS complement,
    COALESCE(l.reference_point, 'Unknown') AS reference_point,
    COALESCE(l.condominium, 'Unknown') AS condominium,
    COALESCE(l.owner_email, 'Unknown') AS owner_email,
    COALESCE(l.owner_phone, 'Unknown') AS owner_phone,
    COALESCE(l.owner_person_type, 'Unknown') AS owner_person_type,
    COALESCE(l.access_type, 'Unknown') AS access_type,
    COALESCE(l.authorization_type, 'Unknown') AS authorization_type,
    COALESCE(l.occupant_type, 'Unknown') AS occupant_type,
    COALESCE(l.additional_access_info, 'Unknown') AS additional_access_info,
    COALESCE(l.locker_address, 'Unknown') AS locker_address,
    COALESCE(l.password, 'Unknown') AS password,
    COALESCE(l.cnpj, 'Unknown') AS cnpj,
    l.iptu_installment_informations[0]['installmentAmount'] AS iptu_installment_amount,
    l.iptu_installment_informations[0]['installmentQuantity'] AS iptu_installment_quantity,
    l.latitude,
    l.longitude,
    l.rent_price,
    l.sale_price,
    l.total_area, 
    l.bedrooms, 
    l.suites, 
    l.bathrooms, 
    l.garages,
    l.has_opted_keys_with_agent,
    l.has_access_restriction,
    l.is_furnished,
    l.is_penthouse,
    l.is_pet_friendly,
    l.is_iptu_not_paid,
    l.is_out_of_area,
    l.is_habitat,
    l.has_balcony,
    l.has_agency_key,
    l.has_concierge,
    lsc.is_waiting_for_enrichment,
    lsc.is_ineligible,
    lsc.is_discarded,
    l.is_sent_to_main,
    l.ts_house_created,
    l.ts_house_updated,
    l.ts_created,
    l.ts_updated,
    NOW() AS ts_load
FROM
    datalake_brokers_supply_processor.lead_3p AS l
JOIN
    datalake_rede_supply.lead_3p_sks AS lsk
        ON l.id = lsk.id_lead_3p
JOIN
    datalake_rede_supply.lead_3p_status_changes AS lsc
        ON lsc.id_lead_3p = l.id
        AND lsc.ts_status_ended IS NULL
LEFT JOIN
    datalake_hubspot.company AS c
        ON c.id_company = lsc.id_company_hubspot
