drop view if exists vw_dim_photo_job;
create or replace view vw_dim_photo_job
as
select
	id as sk_photo_job,
	id,
	imovel_id,
	job_status,
	creation_origin,
	flexible_schedule,
	dt_photographer_accepted,
	dt_job_created,
	dt_job_issued,
	dt_shoot_started,
	dt_job_scheduled,
	dt_photos_uploaded,
	dt_updated,
	scheduling_instructions::varchar(100) as scheduling_instructions,
	photo_shoot_contact_name,
	photo_shoot_email,
	photo_shoot_phone,
	photo_shoot_second_phone,
	approved,
	confirmed,
	lockbox,
	key_withdraw,
	key_comments::varchar(100) as key_comments,
	photographer_id,
	photographer_name,
	photographer_email,
	dt_photographer_start,
	photographer_contract_type,
	job_problem_reason,
	cancel_reason::varchar(100) as cancel_reason,
	user_cancel_dt,
	user_cancel_id,
	user_cancel_name,
	user_cancel_email
from public.photo_job;