WITH extracted_payload AS (
    SELECT
    id_debtor_external AS id_contract,
    id_collector_external AS id_negotiation,
    GET_JSON_OBJECT(payload, "$.contrato") AS id_contract_cyber,
    GET_JSON_OBJECT(payload, "$.cpfCnpj") AS id_client,
    GET_JSON_OBJECT(payload, "$.grupo") AS contract_group,
    status,
    status_reason,
    GET_JSON_OBJECT(payload, '$.tipoContato') AS contact_type,
    GET_JSON_OBJECT(payload, '$.cdAssessoria') AS agency,
    GET_JSON_OBJECT(payload, '$.periodicidade') AS frequency,
    GET_JSON_OBJECT(payload, '$.diasCarencia') AS grace_period_days,
    GET_JSON_OBJECT(payload, '$.formaPagamento') AS payment_method,
    GET_JSON_OBJECT(payload, '$.flgCampanhaBoletagem') AS is_boletagem,
    GET_JSON_OBJECT(payload, '$.cdTipoAcordo') AS agreement_type,
    GET_JSON_OBJECT(payload, "$.taxaMulta") AS fine_rate,
    GET_JSON_OBJECT(payload, "$.vlrEntrada") AS down_payment,
    GET_JSON_OBJECT(payload, '$.qtdParcelas') AS total_installments,
    GET_JSON_OBJECT(payload, '$.vlrNegociado') AS negotiated_amount,
    GET_JSON_OBJECT(payload, '$.vlrHonorariosParc') AS installment_honorarium_amount,
    GET_JSON_OBJECT(payload, '$.dataValidadeBoletagem') AS ts_due_boletagem,
    from_json(GET_JSON_OBJECT(payload, '$.parcelas'),
        'array<struct<grupo:string, contrato:string, idParcela:string, vlrPrincipal:double, vlrMultaResidual:double, vlrJurosResiduais:double, vlrCustasResiduais:double, vlrHonorariosResiduais:double>>') AS parcelas_json,
    from_json(GET_JSON_OBJECT(payload, '$.parcelasAgr'),
        'array<struct<vlrJuros:double, vlrSaldo:double, dtInicial:string, taxaMulta:double, vlrParcela:double, dtVencimento:string, numeroParcela:int, vlrAmortizacao:double, taxaCartaoCredito:double>>') AS parcelas_agr_json,
    from_json(GET_JSON_OBJECT(payload, '$.camposDesconto'),
        'array<struct<campo:string, idAcordo:int, operador:string, vlrComDesconto:double, vlrSemDesconto:double, percentualDesconto:double>>') AS discounts_json,
    ts_created AS ts_creation
    FROM datalake_trato_feito_clean.billing
),
exploded AS (
    SELECT
        ep.*,
        invoice.idParcela AS id_invoice,
        invoice.vlrPrincipal AS invoice_main_amount,
        invoice.vlrMultaResidual AS invoice_residual_fine_amount,
        invoice.vlrJurosResiduais AS invoice_residual_interest_amount,
        invoice.vlrCustasResiduais AS invoice_residual_costs_amount,
        invoice.vlrHonorariosResiduais AS invoice_residual_honorarium_amount,
        installment.vlrJuros AS installment_fine_amount,
        installment.vlrSaldo AS installment_balance_amount,
        installment.dtInicial AS dt_installment_start,
        installment.taxaMulta AS installment_fine_rate,
        installment.vlrParcela AS installment_amount,
        installment.dtVencimento AS dt_due_installment,
        installment.numeroParcela AS installment_number,
        installment.vlrAmortizacao AS installment_amortization_amount,
        installment.taxaCartaoCredito AS installment_credit_card_fee,
        UPPER(discount.campo) AS discount_field,
        discount.vlrComDesconto AS amount_with_discount,
        discount.vlrSemDesconto AS amount_without_discount
    FROM extracted_payload ep
    LATERAL VIEW EXPLODE(parcelas_json) AS invoice
    LATERAL VIEW EXPLODE(parcelas_agr_json) AS installment
    LATERAL VIEW EXPLODE(discounts_json) AS discount
)
SELECT
    id_contract,
    id_negotiation,
    id_contract_cyber,
    id_client,
    id_invoice,
    contract_group,
    status,
    status_reason,
    contact_type,
    agency,
    frequency,
    grace_period_days,
    payment_method,
    is_boletagem,
    agreement_type,
    fine_rate,
    down_payment,
    total_installments,
    negotiated_amount,
    installment_honorarium_amount,
    invoice_main_amount,
    invoice_residual_fine_amount,
    invoice_residual_interest_amount,
    invoice_residual_costs_amount,
    invoice_residual_honorarium_amount,
    installment_fine_amount,
    installment_balance_amount,
    installment_fine_rate,
    installment_amount,
    installment_number,
    installment_amortization_amount,
    installment_credit_card_fee,
    MAX(CASE WHEN discount_field = 'U1VLRPRCAG' THEN amount_with_discount END) AS overdue_amount_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRPRCAG' THEN amount_without_discount END) AS overdue_amount_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLRPRCAVAG' THEN amount_with_discount END) AS to_due_amount_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRPRCAVAG' THEN amount_without_discount END) AS to_due_amount_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLRPRMUAGR' THEN amount_with_discount END) AS installment_fine_amount_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRPRMUAGR' THEN amount_without_discount END) AS installment_fine_amount_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLRMUREAG' THEN amount_with_discount END) AS residual_fine_amount_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRMUREAG' THEN amount_without_discount END) AS residual_fine_amount_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLRMUAG' THEN amount_with_discount END) AS agreement_fine_amount_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRMUAG' THEN amount_without_discount END) AS agreement_fine_amountwithout_discount,
    MAX(CASE WHEN discount_field = 'U1VLRPRJUAG' THEN amount_with_discount END) AS interest_installments_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRPRJUAG' THEN amount_without_discount END) AS interest_installments_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLRJUREAG' THEN amount_with_discount END) AS residual_interest_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRJUREAG' THEN amount_without_discount END) AS residual_interest_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLRJUAG' THEN amount_with_discount END) AS agreement_interest_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRJUAG' THEN amount_without_discount END) AS agreement_interest_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLCUSREAG' THEN amount_with_discount END) AS residual_costs_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLCUSREAG' THEN amount_without_discount END) AS residual_costs_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLCUSTASAG' THEN amount_with_discount END) AS agreement_costs_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLCUSTASAG' THEN amount_without_discount END) AS agreement_costs_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLRHOREAG' THEN amount_with_discount END) AS residual_fees_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRHOREAG' THEN amount_without_discount END) AS residual_fees_without_discount,
    MAX(CASE WHEN discount_field = 'U1VLRDESPJUD' THEN amount_with_discount END) AS judicial_expenses_with_discount,
    MAX(CASE WHEN discount_field = 'U1VLRDESPJUD' THEN amount_without_discount END) AS judicial_expenses_without_discount,
    dt_installment_start,
    dt_due_installment,
    ts_creation,
    ts_due_boletagem
FROM exploded
GROUP BY ALL
