DROP VIEW IF EXISTS vw_contract_costs CASCADE;
CREATE VIEW vw_contract_costs AS
  SELECT
    contract_id                                                                  AS sk_contract,
    imovel_id                                                                    AS sk_property,
    dense_rank()
    OVER (
      PARTITION BY contract_id, imovel_id
      ORDER BY date_range )                                                      AS contract_length,
    date_range                                                                   AS dt_cash_flow,
    rent_value,
    -sum(value_onboarding)                                                       AS vl_onboarding,
    sum(flg_incurred_onboarding) :: INT :: BOOLEAN                               AS flg_incurred_onboarding,
    sum(flg_projected_onboarding) :: INT :: BOOLEAN                              AS flg_projected_onboarding,
    -sum(value_payments)                                                         AS vl_payments,
    sum(flg_incurred_payments) :: INT :: BOOLEAN                                 AS flg_incurred_payments,
    sum(flg_projected_payments) :: INT :: BOOLEAN                                AS flg_projected_payments,
    -sum(value_inspections)                                                      AS vl_inspections,
    sum(flg_incurred_inspections) :: INT :: BOOLEAN                              AS flg_incurred_inspections,
    sum(flg_projected_inspections) :: INT :: BOOLEAN                             AS flg_projected_inspections,
    -sum(value_collections)                                                      AS vl_collections,
    sum(flg_incurred_collections) :: INT :: BOOLEAN                              AS flg_incurred_collections,
    sum(flg_projected_collections) :: INT :: BOOLEAN                             AS flg_projected_collections,
    -sum(value_offboarding)                                                      AS vl_offboarding,
    -sum(
        value_ongoing_support_and_conflict_resolution)                           AS vl_ongoing_support_and_conflict_resolution,
    sum(
        flg_incurred_ongoing_support_and_conflict_resolution) :: INT :: BOOLEAN  AS flg_incurred_ongoing_support_and_conflict_resolution,
    sum(
        flg_projected_ongoing_support_and_conflict_resolution) :: INT :: BOOLEAN AS flg_projected_ongoing_support_and_conflict_resolution,
    sum(value_mgmt)                                                              AS vl_mgmt,
    sum(value_brokerage)                                                         AS vl_brokerage,
    sum(flg_incurred_brokerage) :: INT :: BOOLEAN                                AS flg_incurred_brokerage,
    sum(flg_projected_brokerage) :: INT :: BOOLEAN                               AS flg_projected_brokerage,
    sum(value_delay)                                                             AS vl_delay,
    sum(value_termination)                                                       AS vl_termination
  FROM
    (
      SELECT
        contract_id,
        imovel_id,
        date_trunc('month', date_range) :: DATE AS date_range,
        rent_value                              AS rent_value,
        gap_fill                                AS value_onboarding,
        flg_incurred :: INTEGER                 AS flg_incurred_onboarding,
        flg_projected :: INTEGER                AS flg_projected_onboarding,
        0                                       AS value_payments,
        0                                       AS flg_incurred_payments,
        0                                       AS flg_projected_payments,
        0                                       AS value_inspections,
        0                                       AS flg_incurred_inspections,
        0                                       AS flg_projected_inspections,
        0                                       AS value_collections,
        0                                       AS flg_incurred_collections,
        0                                       AS flg_projected_collections,
        0                                       AS value_offboarding,
        0                                       AS value_ongoing_support_and_conflict_resolution,
        0                                       AS flg_incurred_ongoing_support_and_conflict_resolution,
        0                                       AS flg_projected_ongoing_support_and_conflict_resolution,
        0                                       AS value_mgmt,
        0                                       AS value_brokerage,
        0                                       AS flg_incurred_brokerage,
        0                                       AS flg_projected_brokerage,
        0                                       AS value_delay,
        0                                       AS value_termination
      FROM vw_rental_mgmt_onboarding_costs
      UNION ALL
      SELECT
        contract_id,
        imovel_id,
        date_trunc('month', date_range) :: DATE AS date_range,
        rent_value,
        0,
        0,
        0,
        gap_fill                                AS value_payments,
        flg_incurred :: INTEGER                 AS flg_incurred_payments,
        flg_projected :: INTEGER                AS flg_projected_payments,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      FROM vw_rental_mgmt_payments_costs
      UNION ALL
      SELECT
        contract_id,
        imovel_id,
        date_trunc('month', date_range) :: DATE AS date_range,
        rent_value,
        0,
        0,
        0,
        0,
        0,
        0,
        cost                                    AS value_inspections,
        flg_incurred :: INTEGER                 AS flg_incurred_inspections,
        flg_projected :: INTEGER                AS flg_projected_inspections,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      FROM vw_rental_mgmt_inspections_costs
      UNION ALL
      SELECT
        contract_id,
        imovel_id,
        date_trunc('month', date_range) :: DATE AS date_range,
        rent_value,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        gap_fill                                AS value_collections,
        flg_incurred :: INTEGER                 AS flg_incurred_collections,
        flg_projected :: INTEGER                AS flg_projected_collections,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      FROM vw_rental_mgmt_collections_costs
      UNION ALL
      SELECT DISTINCT
        contract_id,
        imovel_id,
        date_trunc('month', date_range) :: DATE AS date_range,
        rent_value,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        total_offboarding_avg                   AS value_offboarding,
        gap_fill                                AS value_ongoing_support_and_conflict_resolution,
        flg_incurred :: INTEGER                 AS flg_incurred_ongoing_support_and_conflict_resolution,
        flg_projected :: INTEGER                AS flg_projected_ongoing_support_and_conflict_resolution,
        0,
        0,
        0,
        0,
        0,
        0
      FROM vw_rental_mgmt_ongoing_and_offboarding_costs
      UNION ALL
      SELECT
        contract_id,
        imovel_id,
        date_trunc('month', expense_date) :: DATE AS date_range,
        rent_value,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        expense_value                             AS value_mgmt,
        0,
        0,
        0,
        0,
        0
      FROM vw_net_revenue_mgmt_fee
      UNION ALL
      SELECT
        contract_id,
        imovel_id,
        date_trunc('month', date_range) :: DATE AS date_range,
        rent_value,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        brokerage_fee                           AS value_brokerage,
        flg_incurred :: INTEGER                 AS flg_incurred_brokerage,
        flg_projected :: INTEGER                AS flg_projected_brokerage,
        0,
        0
      FROM vw_net_revenue_brokerage_fee
      UNION ALL
      SELECT
        contract_id,
        imovel_id,
        date_trunc('month', date_range) :: DATE AS date_range,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        cost                                    AS value_delay,
        0
      FROM vw_net_revenue_fine_for_delay_in_payment
      UNION ALL
      SELECT
        contract_id,
        imovel_id,
        date_trunc('month', date_range) :: DATE AS date_range,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        cost                                    AS value_termination
      FROM vw_net_revenue_mgmt_fee_over_termination_fine
    ) x
  GROUP BY contract_id, imovel_id, date_range, rent_value;

