SELECT
    id,
    project_id AS id_project,
    notary_id AS id_notary,
    matricula_id AS id_matricula,
    place_id AS id_place,
    operation_id AS id_operation,
    google_docs_id AS id_google_docs,
    google_drive_folder_id AS id_google_drive_folder,
    google_spreedsheets_id AS id_google_spreedsheets,
    google_docs_id_backup AS id_google_docs_backup,
    google_docs_id_backup_partial AS id_google_docs_backup_partial,
    google_docs_id_partial AS id_google_docs_partial,
    favorite,
    disable,
    report_status,
    type,
    approved,
    queue,
    report_google_docs_status,
    complement,
    formatted_address,
    geometry,
    name,
    obs,
    address_components,
    notary_office,
    folders,
    slug,
    contributor,
    delivered_at AS ts_delivered,
    created_at AS ts_created
FROM
    datalake_legaut_test_raw.meuSite_unit
