SELECT
    id,
    project_id AS id_project,
    google_docs_ccv_id AS id_google_docs_ccv,
    notary_id AS id_notary,
    place_id AS id_place,
    created_by_id AS id_created_by,
    house_id AS id_house,
    offer_id AS id_offer,
    salesflow_id AS id_sales_flow,
    financing_type AS id_financing_type,
    status AS id_status,
    name,
    financing_bank,
    formatted_address,
    cep,
    banco_alienacao AS disposal_bank,
    payment_obs,
    geometry,
    address_components,
    fgts_amount,
    signal_down_payment,
    down_payment,
    financing_amount,
    total_amount,
    valor_alienacao AS disposal_amount,
    num_banheiros_sem_emp AS bathrooms,
    num_quartos AS bedrooms,
    num_vagas_garagem_escritura AS parking_slots_deed,
    pos_pavimento AS floor,
    complement,
    disable AS is_disabled,
    favorite AS is_favorite,
    is_closing AS is_closing,
    fgts AS is_fgts,
    financing AS is_financed,
    area_lazer AS has_leasure_area,
    banheiro_emp AS has_maid_bathroom,
    elevador AS has_elevator,
    imovel_foreiro AS is_foreiro,
    quarto_emp AS has_maid_bedroom,
    varanda AS has_balcony,
    alienacao_fiduciaria AS has_fiduciary_alienation,
    credit_approved AS is_credit_approved,
    created_at AS ts_created
FROM
    datalake_legaut_test_raw.meuSite_operation
