SELECT
    absenceCaseId AS id_absence_case,
    absenceTypeId AS id_absence_type,
    absenceTypeReasonId AS id_absence_type_reason,
    agreementId AS id_agreement,
    assignmentId AS id_assignment,
    bandDtlId AS id_band_dtl,
    dataSecurityPersonId AS id_data_security_person,
    initialReportById AS id_initial_report_by,
    legalEntityId AS id_legal_entity,
    legislativeDataGroupId AS id_legislative_data_group,
    periodOfServiceId AS id_period_of_service,
    personId AS id_person,
    personAbsenceEntryId AS id_person_absence_entry,
    projectId AS id_project,
    absenceAttachments AS absence_attachments,
    absenceEntitlements AS abscente_entitlements,
    absenceMaternity AS absence_maternity,
    absencePatternCd AS absence_pattern_cd,
    absenceRecordingDFF AS absence_recording,
    absenceRecordingsDDF AS absence_recordings,
    absenceStatusCd AS absence_status_cd,
    absenceType AS absence_type,  
    absenceReason AS absence_reason,
    absenceDispStatus AS absence_disp_status,
    absenceDispStatusMeaning AS absence_disp_status_meaning,
    AbsenceAgreementBandDtlsVA AS absence_agreement_band_dtls_VA,
    AbsenceDisplayStatusVA AS absence_display_status_VA,
    AbsenceStatusVA AS absence_status_VA,
    AbsenceTypeAgreementsVA AS absence_type_agreement_VA,
    AbsenceTypeReasonsVA AS absence_type_reasons_VA,
    AbsenceTypeVA AS absence_type_VA,
    agreementName AS agreement_name,
    approvalStatusCd AS approval_status_cd,
    ApprovalStatusVA AS approval_status_VA,
    assignmentName AS assignment_name,
    assignmentNumber AS assignment_number,
    AssignmentVA AS assignment_VA,
    blockedLeaveCandidate AS blocked_leave_candidate,
    BlockedLeaveCandidateVA AS blocked_leave_candidate_VA,
    certificationAuthFlag AS certification_auth_flag,
    childEventTypeCd AS child_event_type_cd,
    ChildEventTypeVA AS child_event_type_VA,
    comments,
    consumedByAgreement AS consumed_by_agreement,
    createdBy AS created_by,
    diseaseCode AS disease_code,
    duration,
    employer,
    formattedDuration AS formatted_duration,
    frequency,
    allowAssignmentSelectionFlag AS has_allow_assignment_selection,
    absenceEntryBasicFlag as is_absence_entry_basic,
    absenceUpdatableFlag AS is_absence_updatable,
    employeeShiftFlag AS is_employee_shift,
    initialTimelyNotifyFlag as is_initial_timely_notify,
    lateNotifyFlag AS is_late_notify,
    openEndedFlag AS is_open_ended,
    periodOfIncapToWorkFlag AS is_period_of_incap_to_work,
    singleDayFlag AS is_single_day,
    lastUpdateLogin AS last_update_login,
    lastUpdatedBy AS last_updated_by,
    legislationCode AS legislation_code,
    ObjectVersionNumber AS object_version_number,
    overridden,
    paymentDetail AS payment_detail,
    personNumber AS person_number,
    PersonVA AS person_VA,
    processingStatus AS processing_status,
    source,
    splCondition AS spl_condition,
    SplConditionVA AS spl_condition_VA,
    unitOfMeasure AS unit_of_measure,
    unitOfMeasureMeaning AS unit_of_measure_meaning,
    UomMeaningVA AS uom_meaning_VA,
    userMode AS user_mode,
    authStatusUpdateDate AS dt_auth_status_update,
    conditionStartDate AS dt_condition_start,
    notificationDate AS dt_notification,
    effectiveStartDate AS dt_effective_start,
    plannedEndDate AS dt_planned_end,
    effectiveEndDate AS dt_effective_end,
    submittedDate AS dt_submitted,
    timelinessOverrideDate AS dt_timeliness_override,
    confirmedDate AS dt_confirmed,
    creationDate AS dt_creation,
    establishmentDate AS dt_establishment,
    lastUpdateDate AS dt_last_update,
    ApprovalDatetime AS ts_approval,
    startDateTime AS ts_start_date,
    endDateTime AS ts_end_date,
    ts_load,
    year,
    month,
    day
FROM 
    datalake_hr_system_raw.absences
