SELECT 
    EnrollmentResultId AS id_enrollment_result,
    OptionId AS id_option,
    PersonId AS id_person,
    PlanTypeId AS id_plan_type,
    PlanId AS id_plan,
    ProgramId AS id_program,
    costs AS costs,
    CoverageAmount AS coverage_amount,
    CreatedBy AS created_by,
    CurrencyCode AS currency_code,
    dependents AS dependents,
    InterimFlag AS interim_flag,
    LastUpdatedBy AS last_updated_by,
    NonMonetaryUnit AS non_monetary_unit,
    ObjectVersionNumber AS object_version_number,
    OptionName AS option_name,
    PersonName AS person_name,
    PlanName AS plan_name,
    PlanTypeName AS plan_type_name,
    ProgramName AS program_name,
    providers AS providers,
    SuspendFlag AS suspend_flag,
    to_date(EnrollmentCoverageEndDate, 'yyyy-mm-dd') AS dt_enrollment_coverage_end,
    to_date(EnrollmentCoverageStartDate, 'yyyy-mm-dd') AS dt_enrollment_coverage_start,
    to_date(OriginalCoverageStartDate, 'yyyy-mm-dd') AS dt_original_coverage_start,
    to_timestamp(substr(replace(CreationDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_created,
    to_timestamp(substr(replace(LastUpdateDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_last_update,
    year,
    month,
    day
FROM datalake_hr_system_raw.benefit_enrollments