SELECT 
    OrganizationId AS id_organization,
    LocationIdLOV AS id_location_lov,
    LocationId AS id_location,
    name,
    title,
    OrganizationCode AS organization_code,
    status,
    OrgCode AS org_code,
    OrgClassificationVA AS organization_classification_va,
    StatusLOV AS status_lov,
    ClassificationCode AS classification_code,
    InternalAddressLine AS internal_address_line,
    OrganizationDFF AS organization_dff,
    extraInformation AS extra_information,
    to_date(EffectiveStartDate, 'yyyy-MM-dd') AS dt_effective_start,
    to_date(EffectiveEndDate, 'yyyy-MM-dd') AS dt_effective_end,
    to_timestamp(substr(replace(CreationDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_created,
    to_timestamp(substr(replace(LastUpdateDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_last_update,
    ts_load,
    year,
    month,
    day
FROM datalake_hr_system_raw.organizations