SELECT 
    EvaluationId AS id_evaluation,
    PersonId AS id_person,
    PersonNumber AS person_number,
    AssignmentId AS id_assignment,
    ManagerId AS id_manager,
    ManagerAssignmentId AS id_manager_assignment,
    ReviewPeriodId AS id_review_period,
    TmplPeriodId AS id_template_period,
    TemplateDefnId AS id_template_defn,
    PerformanceDocumentName AS performance_document_name,
    name,
    StatusCode AS status_code,
    TemplateTypeCode AS template_type_code,
    EvalStatus AS evaluation_status,
    roles,
    to_date(StartDate) AS dt_start,
    to_date(EndDate) AS dt_end,
    ts_load
FROM datalake_hr_system_raw.performance_evaluations