SELECT
    SalaryId AS id_salary,
    AssignmentId AS id_assignment,
    SalaryBasisId AS id_salary_basis,
    AssignmentNumber AS assignment_number,
    ActionId AS id_action,
    ActionReasonId AS id_action_reason,
    GradeId AS id_grade,
    LegislativeDataGroupId AS id_legislative_data_group,
    SalaryFrequencyCode AS salary_frequency_code,
    SalaryBasisType AS salary_basis_type,
    CurrencyCode AS currency_code,
    quartile,
    quintile,
    FrequencyName AS frequency_name,
    DisplayName AS display_name,
    ActionCode AS action_code,
    ActionReasonCode AS action_reason_code,
    ActionReason AS action_reason,
    ActionName AS action_name,
    code AS salary_basis_code,
    LegalEmployerName AS legal_employer_name,
    GradeLadderName AS grade_ladder_name,
    GradeName AS grade_name,
    GradeStepName AS grade_step_name,
    GeographyName AS geography_name,
    GeographyTypeName AS geography_type_name,
    LastUpdatedBy AS last_update_by,
    CreatedBy AS created_by,
    AssignmentType AS assignment_type,
    SalaryBasisName AS salary_basis_name,
    AmountRoundingCode AS amount_rounding_code,
    AnnualRoundingCode AS annaul_rounding_code,
    RangeRoundingCode AS range_rounding_code,
    WorkAtHome AS work_at_home,
    QuartileMeaning AS quartile_meaning,
    QuintileMeaning AS quintile_meaning,
    ComponentUsage AS component_usage,
    PendingTransactionExists AS pending_transaction_exists,
    RangeErrorWarning AS range_error_warning,
    PayrollFactor AS payroll_factor,
    SalaryFactor AS salary_factor,
    PayrollFrequencyCode AS payroll_frequency_code,
    salaryComponents AS salary_components,
    salaryPayRateComponents AS salary_pay_rate_components,
    salarySimpleComponents AS salary_simple_components,
    FLOAT(SalaryAmount) AS salary_amount,
    FLOAT(AdjustmentAmount) AS adjustment_amount,
    FLOAT(AdjustmentPercentage) AS adjustment_percentage,
    FLOAT(AnnualSalary) AS annual_salary,
    FLOAT(AnnualFullTimeSalary) AS annual_full_time_salary,
    FLOAT(CompaRatio) AS compa_ratio,
    FLOAT(RangePosition) AS range_position,
    FLOAT(SalaryRangeMinimum) AS salary_range_minimum,
    FLOAT(SalaryRangeMidPoint) AS salary_range_mid_point,
    FLOAT(SalaryRangeMaximum) AS salary_range_maximum,
    INT(FTEValue) AS fte_value,
    INT(AmountDecimalPrecision) AS amount_decimal_precision,
    INT(SalaryAmountScale) AS salary_amount_scale,
    CASE
        WHEN hasFutureSalary = 'Y' THEN TRUE
        ELSE FALSE
    END AS has_future_salary,
    CASE
        WHEN MultipleComponents = 'Y' THEN TRUE
        ELSE FALSE
    END AS has_multiple_components,
    TO_DATE(DateFrom, 'yyyy-MM-dd') AS dt_from,
    TO_DATE(DateTo, 'yyyy-MM-dd') AS dt_to,
    TO_DATE(SearchDate, 'yyyy-MM-dd') AS dt_search,
    TO_DATE(NextSalReviewDate, 'yyyy-MM-dd') AS dt_next_salary_review,
    TO_TIMESTAMP(SUBSTR(REPLACE(CreationDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_created,
    TO_TIMESTAMP(SUBSTR(REPLACE(LastUpdateDate, 'T', ' '), 0, 19), 'yyyy-MM-dd HH:mm:ss') AS ts_last_update,
    ts_load,
    year AS year,
    month AS month,
    day AS day
FROM
    datalake_hr_system_raw.salaries
WHERE
    MAKE_DATE(YEAR, MONTH, DAY) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')