SELECT
    person_id AS id_person,
    assignment_id AS id_assignment,
    salary_id AS id_salary,
    job_id AS id_job,
    grade_id AS id_grade,
    legal_entity_id AS id_legal_entity,
    business_unit_id AS id_business_unit,
    action_id AS id_action,
    action_occurrence_id AS id_action_occurrence,
    action_reason_id AS id_action_reason,
    salary_basis_id AS id_salary_basis,
    element_entry_id AS id_element_entry,
    element_type_id AS id_element_type,
    input_value_id AS id_input_value,
    legislative_data_group_id AS id_legislative_data_group,
    business_group_id AS id_business_group,
    assig_grade_ladder_id AS id_assignment_grade_ladder,
    rate_id AS id_rate,
    currency_code,
    salary_basis_code,
    salary_basis_type,
    assignment_type,
    element_usage_level,
    component_usage,
    quartile,
    quintile,
    multiple_components,
    salary_transaction_status,
    created_by,
    last_updated_by AS updated_by,
    CAST(object_version_number AS INT) AS object_version_number,
    CAST(salary_amount AS DECIMAL(18, 2)) AS salary_amount,
    CAST(annual_salary AS DECIMAL(18, 2)) AS annual_salary,
    CAST(adjustment_amount AS DECIMAL(18, 2)) AS adjustment_amount,
    CAST(adjustment_percent AS DECIMAL(10, 2)) AS adjustment_percent,
    CAST(adjustment_amount_scale AS INT) AS adjustment_amount_scale,
    CAST(adjustment_percent_scale AS INT) AS adjustment_percent_scale,
    CAST(annual_ft_salary AS DECIMAL(18, 2)) AS annual_ft_salary,
    CAST(compa_ratio_scale AS INT) AS compa_ratio_scale,
    CAST(fte_value AS DECIMAL(10, 4)) AS fte_value,
    CAST(payroll_factor AS DECIMAL(10, 4)) AS payroll_factor,
    CAST(range_position_scale AS INT) AS range_position_scale,
    CAST(salary_amount_scale AS INT) AS salary_amount_scale,
    CAST(salary_factor AS DECIMAL(10, 4)) AS salary_factor,
    CAST(salary_range_scale AS INT) AS salary_range_scale,
    CAST(compa_ratio AS DECIMAL(10, 2)) AS compa_ratio,
    CAST(range_position AS DECIMAL(10, 2)) AS range_position,
    CAST(rate_default_amount AS DECIMAL(18, 2)) AS rate_default_amount,
    CAST(rate_factor AS DECIMAL(10, 4)) AS rate_factor,
    CAST(rate_max_amount AS DECIMAL(18, 2)) AS rate_max_amount,
    CAST(rate_mid_amount AS DECIMAL(18, 2)) AS rate_mid_amount,
    CAST(rate_min_amount AS DECIMAL(18, 2)) AS rate_min_amount,
    CAST(adjusted_fte_value AS DECIMAL(10, 4)) AS adjusted_fte_value,
    COALESCE(adjusted_fte_flag = 'Y', FALSE) AS is_adjusted_fte,
    COALESCE(salary_approved = 'Y', FALSE) AS is_salary_approved,
    COALESCE(work_at_home = 'Y', FALSE) AS is_working_at_home,
    TO_DATE(attribute_date15) AS dt_salary_proposal,
    TO_DATE(date_from) AS dt_started,
    TO_DATE(date_to) AS dt_ended,
    TO_TIMESTAMP(creation_date) AS ts_created,
    TO_TIMESTAMP(last_update_date) AS ts_updated,
    NOW() AS ts_load,
    year,
    month,
    day
FROM
    datalake_pin_compensation_raw.cmp_salary
