SELECT
    Id AS id_agent_work,
    OwnerId AS id_owner,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    UserId AS id_user,
    WorkItemId AS id_work_item,
    ServiceChannelId AS id_service_channel,
    OriginalQueueId AS id_original_queue,
    PendingServiceRoutingId AS id_pending_service_routing,
    PreferredUserId AS id_preferred_user,
    OriginalGroupId AS id_original_group,
    Name AS agent_work_name,
    Status AS agent_work_status,
    DeclineReason AS decline_reason,
    RoutingType AS routing_type,
    RoutingModel AS routing_model,
    CapacityModel AS capacity_model,
    CAST(CapacityWeight AS DOUBLE) AS capacity_weight,
    CAST(CapacityPercentage AS DOUBLE) AS capacity_percentage,
    CAST(SpeedToAnswer AS INT) AS speed_to_answer,
    CAST(AgentCapacityWhenDeclined AS DOUBLE) AS agent_capacity_when_declined,
    CAST(PushTimeout AS INT) AS push_timeout,
    CAST(HandleTime AS INT) AS handle_time,
    CAST(ActiveTime AS INT) AS active_time,
    CAST(RoutingPriority AS INT) AS routing_priority,
    CAST(SecondaryRoutingPriority AS INT) AS secondary_routing_priority,
    CAST(AfterConversationActualTime AS INT) AS after_conversation_actual_time,
    CAST(IsDeleted AS BOOLEAN) AS is_deleted,
    CAST(ShouldSkipCapacityCheck AS BOOLEAN) AS is_should_skip_capacity_check,
    CAST(IsStatusChangeInitiated AS BOOLEAN) AS is_status_change_initiated,
    CAST(IsOwnerChangeInitiated AS BOOLEAN) AS is_owner_change_initiated,
    CAST(IsPreferredUserRequired AS BOOLEAN) AS is_preferred_user_required,
    CAST(RequestDateTime AS TIMESTAMP) AS ts_request,
    CAST(AcceptDateTime AS TIMESTAMP) AS ts_accept,
    CAST(DeclineDateTime AS TIMESTAMP) AS ts_decline,
    CAST(CloseDateTime AS TIMESTAMP) AS ts_close,
    CAST(PushTimeoutDateTime AS TIMESTAMP) AS ts_push_timeout,
    CAST(CancelDateTime AS TIMESTAMP) AS ts_cancel,
    CAST(AssignedDateTime AS TIMESTAMP) AS ts_assigned,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.agent_work
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
