SELECT
    Id AS id_case,
    MasterRecordId AS id_master_record,
    CAST(CaseNumber AS INT) AS case_number,
    ContactId AS id_contact,
    AccountId AS id_account,
    AssetId AS id_asset,
    ProductId AS id_product,
    EntitlementId AS id_entitlement,
    SourceId AS id_source,
    BusinessHoursId AS id_business_hours,
    ParentId AS id_parent,
    RecordTypeId AS id_record_type,
    OwnerId AS id_owner,
    CAST(ContractId__c AS INT) AS id_contract,
    CAST(ExternalId__c AS INT) AS id_external,
    RepairId__c AS id_repair,
    Termination__c AS id_termination,
    ServiceContractId AS id_service_contract,
    ZendeskId__c AS id_zendesk,
    LastModifiedById AS id_last_modified_by,
    customerId__c AS id_customer,
    PurchaseSaleContract__c AS id_purchase_sale_contract,
    SuppliedName AS supplied_name,
    SuppliedEmail AS supplied_email,
    SuppliedPhone AS supplied_phone,
    SuppliedCompany AS supplied_company,
    Type AS case_type,
    Status AS case_status,
    Reason AS case_reason,
    Origin AS case_origin,
    Language AS case_language,
    Subject AS case_subject,
    Priority AS case_priority,
    Description AS case_description,
    MilestoneStatus AS milestone_status,
    ZendeskUrl__c AS zendesk_url,
    ContactPhone AS contact_phone,
    ContactMobile AS contact_mobile,
    ContactEmail AS contact_email,
    ContactFax AS contact_fax,
    Comments AS comments,
    AgentRepublishedWithPP__c AS agent_republished_with_pp,
    InformationCollected__c AS information_collected,
    LandlordInformedServiceProvider__c AS pp_informed_service_provider,
    LLServiceConcluded__c AS ll_service_concluded,
    PPacceptedDoingRepair__c AS pp_accepted_doing_repair,
    criticality__c AS criticality,
    ContactSuccess__c AS contact_success,
    followUpDescription__c AS follow_up_description,
    followUpStatus__c AS follow_up_status,
    serviceProviderJourney__c AS service_provider_journey,
    serviceProviderName__c AS service_provider_name,
    serviceProviderPhone__c AS service_provider_phone,
    serviceProviderType__c AS service_provider_type,
    ContestationResponsabilityValid__c AS contestation_reponsability_valid,
    AccountName__c AS account_name,
    BYCurrentOnboardingContact__c AS buyer_current_onboarding_contact,
    CRNStatus__c AS notary_office_status,
    FlowSubType__c AS flow_sub_type,
    ForSaleFlow__c AS for_sale_flow,
    FS_CRI_HaveDemandNote__c AS fs_cri_have_demand_note,
    FS_CRIStatus__c AS fs_cri_status,
    FS_StatusCRI__c AS fs_status_cri,
    FS_SubscriptionModelBuyer__c AS fs_subscription_model_buyer,
    FS_SubscriptionModelSeller__c AS fs_subscription_model_seller,
    PublicationOccurredOnProperty__c AS publication_occurred_on_property,
    SLCurrentOnboardingContact__c AS seller_current_onboarding_contact,
    UnlistingReason__c AS unlisting_reason,
    UnassignedReason__c AS unassigned_reason,
    ContractIdOddOrEven__c AS contract_id_odd_even,
    CAST(IsABTest__c AS BOOLEAN) AS is_ab_test,
    CAST(PastDueDateSimulation__c AS BOOLEAN) AS is_past_due_date_simulation,
    CAST(SimulationTenantBudgetTimeLimit__c AS BOOLEAN) AS is_simulation_iq_budget_time_limit,
    CAST(IsDeleted AS BOOLEAN) AS is_deleted,
    CAST(IsClosed AS BOOLEAN) AS is_closed,
    CAST(IsEscalated AS BOOLEAN) AS is_escalated,
    CAST(IsClosedOnCreate AS BOOLEAN) AS is_closed_on_create,
    CAST(IsStopped AS BOOLEAN) AS is_stopped,
    CAST(isContest__c AS BOOLEAN) AS is_contest,
    CAST(MS_TT_Close_BudgetReviewIQ__c AS BOOLEAN) AS is_ms_tt_close_budget_review_iq,
    CAST(MS_TT_Close_BudgetReviewPP__c AS BOOLEAN) AS is_ms_tt_close_budget_review_pp,
    CAST(MS_TT_Close_ReportReviewIQ__c AS BOOLEAN) AS is_ms_tt_close_report_review_iq,
    CAST(MS_TT_Close_ReportReviewPP__c AS BOOLEAN) AS is_ms_tt_close_report_review_pp,
    CAST(MS_TT_Open_BudgetReviewIQ__c AS BOOLEAN) AS is_ms_tt_open_budget_review_iq,
    CAST(MS_TT_Open_BudgetReviewPP__c AS BOOLEAN) AS is_ms_tt_open_budget_review_pp,
    CAST(MS_TT_Open_ReportReviewIQ__c AS BOOLEAN) AS is_ms_tt_open_report_review_iq,
    CAST(MS_TT_Open_ReportReviewPP__c AS BOOLEAN) AS is_ms_tt_open_report_review_pp,
    CAST(AlreadyAskedForApproval__c AS BOOLEAN) AS is_already_asked_for_approval,
    CAST(AlreadyContested__c AS BOOLEAN) AS is_already_contested,
    CAST(CaseCreationStartMilestoneClosed__c AS BOOLEAN) AS is_case_creation_start_milestone_closed,
    CAST(CaseCreationStartMilestone__c AS BOOLEAN) AS is_case_creation_start_milestone,
    CAST(RequestedHelpTimeLimit__c AS BOOLEAN) AS is_requested_help_time_limit,
    CAST(LLBudgetApprovalTimeLimit__c AS BOOLEAN) AS is_ll_budget_approval_time_limit,
    CAST(BYContactSuccess__c AS BOOLEAN) AS is_buyer_contact_success,
    CASE
        WHEN FS_BalancePaymentMade__c = 'Sim' THEN TRUE
        WHEN FS_BalancePaymentMade__c = 'Não' THEN FALSE
    END AS is_fs_balance_payment_made,
    CASE
        WHEN FS_KeysReceived__c = 'Sim' THEN TRUE
        WHEN FS_KeysReceived__c = 'Não' THEN FALSE
    END AS is_fs_keys_received,
    CASE
        WHEN FS_MilestoneFinish__c = 'Sim' THEN TRUE
        WHEN FS_MilestoneFinish__c = 'Não' THEN FALSE
    END AS is_fs_milestone_finish,
    CASE
        WHEN SLContactSuccess__c = 'Sim' THEN TRUE
        WHEN SLContactSuccess__c = 'Não' THEN FALSE
    END AS is_sl_contact_success,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    CAST(followUpExpectedResolutionDate__c AS TIMESTAMP) AS ts_follow_up_expected_resolution,
    CAST(followUpReassignDate__c AS TIMESTAMP) AS ts_follow_up_reassign,
    CAST(SlaStartDate AS TIMESTAMP) AS ts_sla_start,
    CAST(SlaExitDate AS TIMESTAMP) AS ts_sla_exit,
    CAST(StopStartDate AS TIMESTAMP) AS ts_stop_start,
    CAST(ClosedDate AS TIMESTAMP) AS ts_closed,
    CAST(LastViewedDate AS TIMESTAMP) AS ts_last_viewed,
    CAST(LastReferencedDate AS TIMESTAMP) AS ts_last_referenced,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(FS_BY_KeyDeliveryDate__c AS DATE) AS dt_fs_buyer_key_delivery,
    CAST(FS_BYNextContactDate__c AS DATE) AS dt_fs_buyer_next_contact,
    CAST(FS_CCVSigned__c AS TIMESTAMP) AS ts_fs_ccv_signed,
    CAST(FS_DDAcceptedDate__c AS DATE) AS dt_fs_dd_accepted_date,
    CAST(FS_PDSL_SubscriptionSchedulingDate__c AS DATE) AS dt_fs_pds_subscription_scheduling,
    CAST(FS_ReturnDate__c AS DATE) AS dt_fs_return_date,
    CAST(FS_SL_KeyDeliveryDate__c AS DATE) AS dt_fs_seller_key_delivery,
    CAST(FS_SLNextContactDate__c AS DATE) AS dt_fs_seller_next_contact,
    CAST(KeyDeliveryDate__c AS DATE) AS dt_key_delivery,
    CAST(MS_TT_Date_BudgetReviewIQCreatedDateTD__c AS TIMESTAMP) AS ts_ms_tt_budget_review_iq_created_td,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.cases
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
