SELECT
    Id AS id_case,
    MasterRecordId AS id_master_record,
    CAST(CaseNumber AS INT) AS case_number,
    ContactId AS id_contact,
    AccountId AS id_account,
    AssetId AS id_asset,
    ProductId AS id_product,
    EntitlementId AS id_entitlement,
    SourceId AS id_source,
    BusinessHoursId AS id_business_hours,
    ParentId AS id_parent,
    RecordTypeId AS id_record_type,
    OwnerId AS id_owner,
    ContractId__c AS id_contract,
    ExternalId__c AS id_external,
    RepairId__c AS id_repair,
    Termination__c AS id_termination,
    ServiceContractId AS id_service_contract,
    ZendeskId__c AS id_zendesk,
    LastModifiedById AS id_last_modified_by,
    customerId__c AS id_customer,
    PurchaseSaleContract__c AS id_purchase_sale_contract,
    SuppliedName AS supplied_name,
    SuppliedEmail AS supplied_email,
    SuppliedPhone AS supplied_phone,
    SuppliedCompany AS supplied_company,
    Type AS case_type,
    Status AS case_status,
    Reason AS case_reason,
    Origin AS case_origin,
    Language AS case_language,
    Subject AS case_subject,
    Priority AS case_priority,
    Description AS case_description,
    MilestoneStatus AS milestone_status,
    ZendeskUrl__c AS zendesk_url,
    ContactPhone AS contact_phone,
    ContactMobile AS contact_mobile,
    ContactEmail AS contact_email,
    ContactFax AS contact_fax,
    Comments AS comments,
    AgentRepublishedWithPP__c AS agent_republished_with_pp,
    InformationCollected__c AS information_collected,
    LandlordInformedServiceProvider__c AS pp_informed_service_provider,
    criticality__c AS criticality,
    ContactSuccess__c AS contact_success,
    followUpDescription__c AS follow_up_description,
    followUpStatus__c AS follow_up_status,
    serviceProviderJourney__c AS service_provider_journey,
    serviceProviderName__c AS service_provider_name,
    serviceProviderPhone__c AS service_provider_phone,
    serviceProviderType__c AS service_provider_type,
    ContestationResponsabilityValid__c AS contestation_reponsability_valid,
    AccountName__c AS account_name,
    BYCurrentOnboardingContact__c AS buyer_current_onboarding_contact,
    CRNStatus__c AS notary_office_status,
    FlowSubType__c AS flow_sub_type,
    ForSaleFlow__c AS for_sale_flow,
    FS_CRI_HaveDemandNote__c AS fs_cri_have_demand_note,
    FS_CRIStatus__c AS fs_cri_status,
    FS_StatusCRI__c AS fs_status_cri,
    FS_SubscriptionModelBuyer__c AS fs_subscription_model_buyer,
    FS_SubscriptionModelSeller__c AS fs_subscription_model_seller,
    PublicationOccurredOnProperty__c AS publication_occurred_on_property,
    SLCurrentOnboardingContact__c AS seller_current_onboarding_contact,
    UnlistingReason__c AS unlisting_reason,
    UnassignedReason__c AS unassigned_reason,
    TypeApproval__c AS case_type_approval,
    CommentsApproval__c AS case_comments_approval,
    ContractIdOddOrEven__c AS contract_id_odd_even,
    OmniChannelQueue__c AS omni_channel_queue,
    CAST(IsABTest__c AS BOOLEAN) AS is_ab_test,
    CAST(PastDueDateSimulation__c AS BOOLEAN) AS is_past_due_date_simulation,
    CAST(SimulationTenantBudgetTimeLimit__c AS BOOLEAN) AS is_simulation_iq_budget_time_limit,
    CAST(IsDeleted AS BOOLEAN) AS is_deleted,
    CAST(IsClosed AS BOOLEAN) AS is_closed,
    CAST(IsEscalated AS BOOLEAN) AS is_escalated,
    CAST(IsClosedOnCreate AS BOOLEAN) AS is_closed_on_create,
    CAST(IsStopped AS BOOLEAN) AS is_stopped,
    CAST(isContest__c AS BOOLEAN) AS is_contest,
    CAST(MS_TT_Close_BudgetReviewIQ__c AS BOOLEAN) AS is_ms_tt_close_budget_review_iq,
    CAST(MS_TT_Close_BudgetReviewPP__c AS BOOLEAN) AS is_ms_tt_close_budget_review_pp,
    CAST(MS_TT_Close_ReportReviewIQ__c AS BOOLEAN) AS is_ms_tt_close_report_review_iq,
    CAST(MS_TT_Close_ReportReviewPP__c AS BOOLEAN) AS is_ms_tt_close_report_review_pp,
    CAST(MS_TT_Open_BudgetReviewIQ__c AS BOOLEAN) AS is_ms_tt_open_budget_review_iq,
    CAST(MS_TT_Open_BudgetReviewPP__c AS BOOLEAN) AS is_ms_tt_open_budget_review_pp,
    CAST(MS_TT_Open_ReportReviewIQ__c AS BOOLEAN) AS is_ms_tt_open_report_review_iq,
    CAST(MS_TT_Open_ReportReviewPP__c AS BOOLEAN) AS is_ms_tt_open_report_review_pp,
    CAST(AlreadyAskedForApproval__c AS BOOLEAN) AS is_already_asked_for_approval,
    CAST(AlreadyContested__c AS BOOLEAN) AS is_already_contested,
    CAST(CaseCreationStartMilestoneClosed__c AS BOOLEAN) AS is_case_creation_start_milestone_closed,
    CAST(CaseCreationStartMilestone__c AS BOOLEAN) AS is_case_creation_start_milestone,
    CAST(RequestedHelpTimeLimit__c AS BOOLEAN) AS is_requested_help_time_limit,
    CAST(LLBudgetApprovalTimeLimit__c AS BOOLEAN) AS is_ll_budget_approval_time_limit,
    CAST(BYContactSuccess__c AS BOOLEAN) AS is_buyer_contact_success,
    CASE
        WHEN FS_BalancePaymentMade__c = 'Sim' THEN TRUE
        WHEN FS_BalancePaymentMade__c = 'Não' THEN FALSE
    END AS is_fs_balance_payment_made,
    CASE
        WHEN FS_KeysReceived__c = 'Sim' THEN TRUE
        WHEN FS_KeysReceived__c = 'Não' THEN FALSE
    END AS is_fs_keys_received,
    CASE
        WHEN FS_MilestoneFinish__c = 'Sim' THEN TRUE
        WHEN FS_MilestoneFinish__c = 'Não' THEN FALSE
    END AS is_fs_milestone_finish,
    CASE
        WHEN SLContactSuccess__c = 'Sim' THEN TRUE
        WHEN SLContactSuccess__c = 'Não' THEN FALSE
    END AS is_sl_contact_success,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    CAST(followUpExpectedResolutionDate__c AS TIMESTAMP) AS ts_follow_up_expected_resolution,
    CAST(followUpReassignDate__c AS TIMESTAMP) AS ts_follow_up_reassign,
    CAST(LastAgentInteraction__c AS TIMESTAMP) AS ts_last_agent_interaction,
    CAST(LastCustomerInteraction__c AS TIMESTAMP) AS ts_last_customer_interaction,
    CAST(SlaStartDate AS TIMESTAMP) AS ts_sla_start,
    CAST(SlaExitDate AS TIMESTAMP) AS ts_sla_exit,
    CAST(StopStartDate AS TIMESTAMP) AS ts_stop_start,
    CAST(ClosedDate AS TIMESTAMP) AS ts_closed,
    CAST(LastViewedDate AS TIMESTAMP) AS ts_last_viewed,
    CAST(LastReferencedDate AS TIMESTAMP) AS ts_last_referenced,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(FS_BY_KeyDeliveryDate__c AS DATE) AS dt_fs_buyer_key_delivery,
    CAST(FS_BYNextContactDate__c AS DATE) AS dt_fs_buyer_next_contact,
    CAST(FS_CCVSigned__c AS TIMESTAMP) AS ts_fs_ccv_signed,
    CAST(FS_DDAcceptedDate__c AS DATE) AS dt_fs_dd_accepted_date,
    CAST(FS_PDSL_SubscriptionSchedulingDate__c AS DATE) AS dt_fs_pds_subscription_scheduling,
    CAST(FS_ReturnDate__c AS DATE) AS dt_fs_return_date,
    CAST(FS_SL_KeyDeliveryDate__c AS DATE) AS dt_fs_seller_key_delivery,
    CAST(FS_SLNextContactDate__c AS DATE) AS dt_fs_seller_next_contact,
    CAST(KeyDeliveryDate__c AS DATE) AS dt_key_delivery,
    CAST(MS_TT_Date_BudgetReviewIQCreatedDateTD__c AS TIMESTAMP) AS ts_ms_tt_budget_review_iq_created_td,
    CreatedById AS id_created_by_id,
    LandlordInformedTTServiceProvider__c AS landlord_informed_tt_service_provider,
    TTsolicitedHelp__c AS t_tsolicited_help,
    LandlordProviderNoHelpMilestoneClosed__c AS landlord_provider_no_help_milestone_closed,
    LandlordProviderNoHelpMilestone__c AS landlord_provider_no_help_milestone,
    TenantProviderOwnerApprovalClosed__c AS tenant_provider_owner_approval_closed,
    TenantProviderOwnerApprovalMilestone__c AS tenant_provider_owner_approval_milestone,
    TenantServiceProviderMilestoneClosed__c AS tenant_service_provider_milestone_closed,
    TenantServiceProviderMilestone__c AS tenant_service_provider_milestone,
    ReasonForRetry__c AS reason_for_retry,
    FS_CRI_Have_Demand_Note__c AS fs_cri_have_demand_note_2,
    FS_ContinueWithPartnerRegistry__c AS fs_continue_with_partner_registry,
    FS_CRI_Password__c AS fs_cri_password,
    FS_CRI_Protocol__c AS fs_cri_protocol,
    FS_CRI_RequestDate__c AS dt_fs_cri_request_date,
    FS_CRI_Request_Date__c AS dt_fs_cri_request_date_2,
    FS_CreatedDate__c AS dt_fs_created_date,
    FS_CreatedSequence__c AS fs_created_sequence,
    TT_UnlistingApproval__c AS tt_unlisting_approval,
    StatusReadOnly__c AS status_read_only,
    BookkeepingDoneDate__c AS dt_bookkeeping_done_date,
    CRIDoneDate__c AS dt_cri_done_date,
    CRIPRENOTEDDate__c AS dt_criprenoted_date,
    CaseShareCommunityPortal__c AS case_share_community_portal,
    Escrivao__c AS escrivao,
    FS_AVE_Password__c AS fs_ave_password,
    FS_AVE_Protocol__c AS fs_ave_protocol,
    FS_AVE_RequestDate__c AS dt_fs_ave_request_date,
    FS_CRIName__c AS fs_cri_name,
    FS_CRNPartnerName__c AS fs_crn_partner_name,
    FS_CRNPartner__c AS fs_crn_partner,
    FS_ConcomitantRegistration__c AS fs_concomitant_registration,
    FS_EndorsementStatus__c AS fs_endorsement_status,
    FS_FID_AlienationStatus__c AS fs_fid_alienation_status,
    FS_FID_DischargeTermReceived__c AS fs_fid_discharge_term_received,
    FS_FirstNotification__c AS fs_first_notification,
    FS_HouseOccupant__c AS fs_house_occupant,
    FS_IDCartorio__c AS fs_id_cartorio,
    FS_NomeComprador__c AS fs_nome_comprador,
    FS_PreemptiveRight__c AS fs_preemptive_right,
    FS_ReasonNonConversion__c AS fs_reason_non_conversion,
    FS_CancelledNotFollowingCRN__c AS fs_cancelled_not_following_crn,
    FS_CanceledReason__c AS fs_canceled_reason,
    FS_ResponsibleAssistant__c AS fs_responsible_assistant,
    ITBIStatus__c AS itbi_status,
    CaseListViewUser__c AS case_list_view_user,
    LeadTime__c AS lead_time,
    LTBookkeepingDone__c AS lt_bookkeeping_done,
    LTCRI__c AS ltcri,
    FS_BookkeepingCompletionDate__c AS dt_fs_bookkeeping_completion_date,
    FS_AVE_HaveDemandNote__c AS fs_ave_have_demand_note,
    FS_ProofPaymentReceived__c AS fs_proof_payment_received,
    FS_ReasonsLTOverrunRegister__c AS fs_reasons_lt_overrun_register,
    FS_ReasonsLTOverrun__c AS fs_reasons_lt_overrun,
    EntryAccess__c AS entry_access,
    Inspection__c AS inspection,
    Analyst__c AS analyst,
    CollectionAddress__Street__s AS collection_addresstreet,
    CollectionAddress__City__s AS collection_address_city,
    CollectionAddress__PostalCode__s AS collection_address_postal_code,
    CollectionAddress__StateCode__s AS collection_addresstate_code,
    CollectionAddress__CountryCode__s AS collection_address_country_code,
    CollectionAddress__Latitude__s AS collection_address_latitude,
    CollectionAddress__Longitude__s AS collection_address_longitude,
    CollectionAddress__GeocodeAccuracy__s AS collection_address_geocode_accuracy,
    CollectionAddress__c AS collection_address,
    CollectionAvailableDate__c AS dt_collection_available_date,
    CollectionAvailablePeriod__c AS collection_available_period,
    CollectionAvailableTime__c AS collection_available_time,
    CollectionReferencePoint__c AS collection_reference_point,
    CollectionResponsibleName__c AS collection_responsible_name,
    CollectionResponsiblePhone__c AS collection_responsible_phone,
    CollectionResponsibleRole__c AS collection_responsible_role,
    ContactDateTime__c AS dt_contact_date_time,
    ContactReplyIQ__c AS contact_reply_iq,
    ContactReplyPP__c AS contact_reply_pp,
    ContactReplyVT__c AS contact_reply_vt,
    CriticalitySla__c AS criticality_sla,
    DeliveryAddress__Street__s AS delivery_addresstreet,
    DeliveryAddress__City__s AS delivery_address_city,
    DeliveryAddress__PostalCode__s AS delivery_address_postal_code,
    DeliveryAddress__StateCode__s AS delivery_addresstate_code,
    DeliveryAddress__CountryCode__s AS delivery_address_country_code,
    DeliveryAddress__Latitude__s AS delivery_address_latitude,
    DeliveryAddress__Longitude__s AS delivery_address_longitude,
    DeliveryAddress__GeocodeAccuracy__s AS delivery_address_geocode_accuracy,
    DeliveryAddress__c AS delivery_address,
    DeliveryAvailableDate__c AS dt_delivery_available_date,
    DeliveryAvailablePeriod__c AS delivery_available_period,
    DeliveryReferencePoint__c AS delivery_reference_point,
    DeliveryResponsibleName__c AS delivery_responsible_name,
    DeliveryResponsiblePhone__c AS delivery_responsible_phone,
    DeliveryResponsibleRole__c AS delivery_responsible_role,
    DepartureInspectionDate__c AS dt_departure_inspection_date,
    KeyLocation__c AS key_location,
    LeadershipApprovedException__c AS leadership_approved_exception,
    ParentCaseAnalyst__c AS parent_case_analyst,
    ParentCaseOwner__c AS parent_case_owner,
    PriorityLighthouse__c AS priority_lighthouse,
    Property__c AS property,
    RelatedContract__c AS related_contract,
    RideDistance__c AS ride_distance,
    SLALighthouse__c AS sla_lighthouse,
    SkillPriority__c AS skill_priority,
    Source__c AS source,
    Stage__c AS stage,
    StartServiceDate__c AS dt_start_service_date,
    ContractMagicLink__c AS contract_magic_link,
    ContractStartDate__c AS dt_contract_start_date,
    IsAbove50Km__c AS is_above50_km,
    KeyOffboardingLeadTime__c AS key_offboarding_lead_time,
    PropertyMagicLink__c AS property_magic_link,
    PropertyNumber__c AS property_number,
    RelatedContractLink__c AS related_contract_link,
    CAST(SLA__c AS FLOAT) AS sla,
    PriorityByFlow__c AS priority_by_flow,
    DeliveryNotesDropoff__c AS delivery_notes_dropoff,
    ActiveUser__c AS active_user,
    CollectionAddressComplement__c AS collection_address_complement,
    DeliveryAddressComplement__c AS delivery_address_complement,
    CreatedDate__c AS dt_created_date,
    TaskNotes__c AS task_notes,
    DeliveryNotesPickup__c AS delivery_notes_pickup,
    NeedRun__c AS need_run,
    NoRideReason__c AS no_ride_reason,
    CollectionAvailableTimeMax__c AS collection_available_time_max,
    KeyProcess__c AS key_process,
    PPReplied__c AS pp_replied,
    Urgency__c AS urgency,
    VTReplied__c AS vt_replied,
    CorrelationId__c AS id_correlation_id,
    Mediacao__c AS mediacao,
    InspectionRecordOwnerReview__c AS inspection_record_owner_review,
    InspectionRecordTenantReviewFormula__c AS inspection_record_tenant_review_formula,
    RelatedContractId__c AS id_related_contract_id,
    RequesterAccount__c AS requester_account,
    SKSession__c AS sk_session,
    IsSpoc__c AS is_spoc,
    MediationCase__c AS mediation_case,
    Mediation__c AS mediation,
    CSATSurveySent__c AS csat_survey_sent,
    DoNotTriggerCSAT__c AS do_not_trigger_csat,
    OwnerRecipientId__c AS id_owner_recipient_id,
    PrimaryOwneroftheCustomerService__c AS primary_ownerofthe_customer_service,
    PrimaryTenantoftheCustomerService__c AS primary_tenantofthe_customer_service,
    TenantRecipientId__c AS id_tenant_recipient_id,
    Despejo__c AS despejo,
    HighValue__c AS high_value,
    PpMulti__c AS pp_multi,
    CPF__c AS cpf,
    CaseDescription__c AS case_description_2,
    ClientName__c AS client_name,
    ClientPhone__c AS client_phone,
    PreferredContactChannel__c AS preferred_contact_channel,
    PropertyAddress__c AS property_address,
    PropertyID__c AS property_id,
    ServiceAccountIssue__c AS service_account_issue,
    Accessory_Property_DD__c AS accessory_property_dd,
    Diligence_Link_DD__c AS diligence_link_dd,
    Identified_Fails_DD__c AS identified_fails_dd,
    Link_Legaut_DD__c AS link_legaut_dd,
    Risk_Level_DD__c AS risk_level_dd,
    ItemToBeRemoved__c AS item_to_be_removed,
    DistributionModel__c AS distribution_model,
    HefestoContextId__c AS id_hefesto_context_id,
    Manual_Closing__c AS manual_closing,
    CX_For_Rent__c AS cx_for_rent,
    NewEffectiveDate__c AS dt_new_effective_date,
    isEviction__c AS is_eviction,
    isHighValue__c AS is_high_value,
    isPPMulti__c AS is_pp_multi,
    Addendum_Reason_DD__c AS addendum_reason_dd,
    IsKirk__c AS is_kirk,
    FR_CaseNumberMagicLink__c AS fr_case_number_magic_link,
    FR_Case_Reopen_Count__c AS fr_case_reopen_count,
    Address_Cognito__c AS address_cognito,
    Amount__c AS amount,
    AnalystRemarks__c AS analyst_remarks,
    Bank_Branch_Cognito__c AS bank_branch_cognito,
    Bank_Cognito__c AS bank_cognito,
    BookingDate__c AS dt_booking_date,
    BookingTime__c AS booking_time,
    Checking_Account_Cognito__c AS checking_account_cognito,
    City_State_Cognito__c AS city_state_cognito,
    Email_Cognito__c AS email_cognito,
    IAm__c AS i_am,
    Member_real_estate_name__c AS member_real_estate_name,
    Name_Cognito__c AS name_cognito,
    Other_sector__c AS other_sector,
    PartnerRealtyAgency__c AS partner_realty_agency,
    Partner_Realty_Agency_Others__c AS partner_realty_agency_others,
    Phone_Cognito__c AS phone_cognito,
    PropertyNumberCognito__c AS property_number_cognito,
    Quantity__c AS quantity,
    SubjectCorrespondsRequestReason__c AS subject_corresponds_request_reason,
    Sector__c AS sector,
    HefestoContextGroupId__c AS id_hefesto_context_group_id,
    OriginalQueueDeveloperName__c AS original_queue_developer_name,
    ContestationCase__c AS contestation_case,
    RepairAnalysisId__c AS id_repair_analysis_id,
    ApplicantType__c AS applicant_type,
    CCs__c AS c_cs,
    ClientType__c AS client_type,
    ContactTicket__c AS contact_ticket,
    DemandType__c AS demand_type,
    JustifiedRequest__c AS justified_request,
    OpenComunicationToOtherPart__c AS open_comunication_to_other_part,
    RequestReason__c AS request_reason,
    RequestType__c AS request_type,
    SendToCounterpart__c AS send_to_counterpart,
    SendToLandlord__c AS send_to_landlord,
    SendToRequester__c AS send_to_requester,
    SendToTenant__c AS send_to_tenant,
    CaseInspectionId__c AS id_case_inspection_id,
    CustomerType__c AS customer_type,
    DiscardReason__c AS discard_reason,
    InternalTeam__c AS internal_team,
    IsCollaborator__c AS is_collaborator,
    OriginCognito__c AS origin_cognito,
    PropertyIDLink__c AS property_id_link,
    Requestor__c AS requestor,
    ReschedulePrioritization__c AS reschedule_prioritization,
    ServiceRequestChannel__c AS service_request_channel,
    SolicitationType__c AS solicitation_type,
    SpecificPhotographer__c AS specific_photographer,
    TaskOrigin__c AS task_origin,
    TaskRequestedCorrectly__c AS task_requested_correctly,
    TicketType__c AS ticket_type,
    TypeOfProvider__c AS type_of_provider,
    Justification__c AS justification,
    VerificationKeysLocal__c AS verification_keys_local,
    WhatShouldBeVerified__c AS what_should_be_verified,
    Department__c AS department,
    Extension__c AS extension,
    MagicLinkHouseURL__c AS magic_link_house_url,
    PropertyClassification__c AS property_classification,
    CasePlatesLockboxRelated__c AS case_plates_lockbox_related,
    CaseLegalOps__c AS case_legal_ops,
    ContractExternalId__c AS id_contract_external_id,
    SLADueDays__c AS sla_due_days,
    Approved__c AS approved,
    PhotographerId__c AS id_photographer_id,
    ReportReason__c AS report_reason,
    SessionId__c AS id_session_id,
    CurrentJourney__c AS current_journey,
    InspectionExternalId__c AS id_inspection_external_id,
    Offer_ID__c AS offer_id,
    Valor_do_caso__c AS valor_do_caso,
    HefestoError__c AS hefesto_error,
    CustomerSegmentation__c AS customer_segmentation,
    CustomerUpset__c AS customer_upset,
    Data_Saida_Imovel__c AS data_saida_imovel,
    ReasonNotRescindViaApp__c AS reason_not_rescind_via_app,
    RescissionQuestions__c AS rescission_questions,
    CaseEndOfProcess__c AS case_end_of_process,
    RecordTypeDeveloperName__c AS record_type_developer_name,
    AmountAceptedByPP__c AS amount_acepted_by_pp,
    DeadlineAlredyPassed__c AS deadline_alredy_passed,
    IQLikePayInstallments__c AS iq_like_pay_installments,
    NumberInstallments__c AS number_installments,
    PPAcceptNegotiation__c AS pp_accept_negotiation,
    PartnerProtocol__c AS partner_protocol,
    ContractCreationDate__c AS dt_contract_creation_date,
    ContractStatus__c AS contract_status,
    CostResponsible__c AS cost_responsible,
    EffectiveDate__c AS dt_effective_date,
    ExecutionDeadline__c AS execution_deadline,
    HasNegotiation__c AS has_negotiation,
    ProposalText__c AS proposal_text,
    RequestedBy__c AS requested_by,
    WhoEnters__c AS who_enters,
    WhoLeaves__c AS who_leaves,
    WhoRemains__c AS who_remains,
    MagiclinkAnalystEmail__c AS magiclink_analyst_email,
    AdvanceProduct__c AS advance_product,
    Demandant__c AS demandant,
    ExpenseName__c AS expense_name,
    InvoiceMonth__c AS invoice_month,
    NewAmount__c AS new_amount,
    PreviousAmount__c AS previous_amount,
    PreviouslyRequestedInApp__c AS previously_requested_in_app,
    RecurringExpense__c AS recurring_expense,
    RelatedContractStatus__c AS related_contract_status,
    RelatedProposalId__c AS id_related_proposal_id,
    SolvedHour__c AS solved_hour,
    UpdatedListingValue__c AS updated_listing_value,
    RAModerationReason__c AS ra_moderation_reason,
    Associated_Executive__c AS associated_executive,
    SolicitationReason__c AS solicitation_reason,
    BankDetails__c AS bank_details,
    ExecutiveEmail__c AS executive_email,
    Action__c AS action,
    CollectionWave__c AS collection_wave,
    Credit__c AS credit,
    DayOverdue__c AS day_overdue,
    Debit__c AS debit,
    HasApprovedBandAid__c AS has_approved_band_aid,
    HasOpenInvoices__c AS has_open_invoices,
    InvoiceDate__c AS dt_invoice_date,
    InvoiceId__c AS id_invoice_id,
    InvoiceQuantity__c AS invoice_quantity,
    IsContractInLawFirm__c AS is_contract_in_law_firm,
    IsContractLinkedToAdvisory__c AS is_contract_linked_to_advisory,
    IsCustomerNegativelyListed__c AS is_customer_negatively_listed,
    PaymentDate__c AS dt_payment_date,
    PaymentMethod__c AS payment_method,
    ResponsibleAdvisory__c AS responsible_advisory,
    DisposalCost__c AS disposal_cost,
    InterestedPartyKeepsItem__c AS interested_party_keeps_item,
    InterestedPartyPaymentAmount__c AS interested_party_payment_amount,
    ItemPhotosSent__c AS item_photos_sent,
    ItemPickupDateTime__c AS dt_item_pickup_date_time,
    ItemPickupKeyLocation__c AS item_pickup_key_location,
    PriorItemNegotiation__c AS prior_item_negotiation,
    AdditionalContacts__c AS additional_contacts,
    BillingResponsible__c AS billing_responsible,
    BillingStartDate__c AS dt_billing_start_date,
    BuyerEmail__c AS buyer_email,
    BuyerId__c AS id_buyer_id,
    BuyerPhone__c AS buyer_phone,
    Buyer__c AS buyer,
    Classification__c AS classification,
    ConditionPrecedentDate__c AS dt_condition_precedent_date,
    ConditionPrecedent__c AS condition_precedent,
    EntryDate__c AS dt_entry_date,
    ExtrajudicialNotificationDate__c AS dt_extrajudicial_notification_date,
    ExtrajudicialNotification__c AS extrajudicial_notification,
    FirstContactDate__c AS dt_first_contact_date,
    IDOfferFR__c AS id_offer_fr,
    RegistryCheck__c AS registry_check,
    ResponsibleAnalyst__c AS responsible_analyst,
    ReturnDate__c AS dt_return_date,
    SellerEmail__c AS seller_email,
    SellerId__c AS id_seller_id,
    SellerPhone__c AS seller_phone,
    Seller__c AS seller,
    HefestoPortfolioStatus__c AS hefesto_portfolio_status,
    AccountType__c AS account_type,
    AccountValue__c AS account_value,
    IsItMoreThanOneBill__c AS is_it_more_than_one_bill,
    WhoIssuesTheBill__c AS who_issues_the_bill,
    PPMultiPicklist__c AS pp_multi_picklist,
    RepairBudgetApproved__c AS repair_budget_approved,
    RepairBudgetsSent__c AS repair_budgets_sent,
    RepairCaseNumber__c AS repair_case_number,
    RepairContestationChangeMade__c AS repair_contestation_change_made,
    RepairContestationChangeReason__c AS repair_contestation_change_reason,
    RepairContestationClientFriction__c AS repair_contestation_client_friction,
    RepairContestationCriticalityApproved__c AS repair_contestation_criticality_approved,
    RepairContestationResponsibilityApproved__c AS repair_contestation_responsibility_approved,
    RepairContestationType__c AS repair_contestation_type,
    RepairExecutionDate__c AS dt_repair_execution_date,
    RepairIsExecuted__c AS repair_is_executed,
    RepairSchedulingDate__c AS dt_repair_scheduling_date,
    RepairSchedulingPeriod__c AS repair_scheduling_period,
    RepairServiceProviderComments__c AS repair_service_provider_comments,
    RepairServiceProviderIsAware__c AS repair_service_provider_is_aware,
    RepairServiceProviderIsCompulsory__c AS repair_service_provider_is_compulsory,
    RepairServiceProviderName__c AS repair_service_provider_name,
    RepairServiceProviderPhone__c AS repair_service_provider_phone,
    RepairServiceProviderType__c AS repair_service_provider_type,
    RepairTerminationNoticeIssued__c AS repair_termination_notice_issued,
    RentPeriod__c AS rent_period,
    AmountMoney__c AS amount_money,
    AmountReceived__c AS amount_received,
    BandAidNumber__c AS band_aid_number,
    Disappearancetime__c AS disappearancetime,
    ExpectedValue__c AS expected_value,
    FlowDecision__c AS flow_decision,
    JiraLink__c AS jira_link,
    LastKeyLocation__c AS last_key_location,
    PartnerId__c AS id_partner_id,
    Period__c AS period,
    Platform__c AS platform,
    PropertyCategory__c AS property_category,
    PropertyType__c AS property_type,
    ReferenceMonth__c AS reference_month,
    RequiresInternalHandling__c AS requires_internal_handling,
    ThereWasANeedToOpenJira__c AS there_was_a_need_to_open_jira,
    TypeOfOperationalProperty__c AS type_of_operational_property,
    UserIssueonthePlatform__c AS user_issueonthe_platform,
    WhatWasTheMethodOfResolution__c AS what_was_the_method_of_resolution,
    WhereToPickUpAndReturnTheKeys__c AS where_to_pick_up_and_return_the_keys,
    BalanceToReceive__c AS balance_to_receive,
    BillingReason__c AS billing_reason,
    CCVSignedDate__c AS dt_ccv_signed_date,
    EarliestDueDate__c AS dt_earliest_due_date,
    Invoice__c AS invoice,
    OutstandingAmount__c AS outstanding_amount,
    Product__c AS product,
    ReceivedBalance__c AS received_balance,
    ServiceClassification__c AS service_classification,
    SwappedContractId__c AS id_swapped_contract_id,
    TotalBrokerageAmount__c AS total_brokerage_amount,
    CaseRepairItem__c AS case_repair_item,
    CaseRepairRequest__c AS case_repair_request,
    RepairServiceProviderDate__c AS dt_repair_service_provider_date,
    CustomerFavorable__c AS customer_favorable,
    EntryChannel__c AS entry_channel,
    FraudAnalysis__c AS fraud_analysis,
    LegalAction__c AS legal_action,
    ProcessOffender__c AS process_offender,
    Product5A__c AS product5_a,
    RelatedEmployee__c AS related_employee,
    NewRelatedContractStatus__c AS new_related_contract_status,
    CreditAnalysisApprovedByTheTeam__c AS credit_analysis_approved_by_the_team,
    HefestoPortfolioStatusLabel__c AS hefesto_portfolio_status_label,
    BuyerDocument__c AS buyer_document,
    BuyerName__c AS buyer_name,
    BypassType__c AS bypass_type,
    CRINumber__c AS cri_number,
    IDIdactum__c AS id_idactum,
    InvestigationSource__c AS investigation_source,
    LandlordDocument__c AS landlord_document,
    LandlordName__c AS landlord_name,
    PropertyNegotiationValue__c AS property_negotiation_value,
    RegistrationNumber__c AS registration_number,
    TransactionDate__c AS dt_transaction_date,
    VisitId__c AS id_visit_id,
    ClosedByAutomation__c AS closed_by_automation,
    journey__c AS journey,
    CaseToBeHandled__c AS case_to_be_handled,
    Microtaxonomy__c AS microtaxonomy,
    RA_Active__c AS ra_active,
    RA_AttachmentsCount__c AS ra_attachments_count,
    RA_BackDoingBusiness__c AS ra_back_doing_business,
    RA_BlockPublicReply__c AS ra_block_public_reply,
    RA_BlockPublicUntil__c AS ra_block_public_until,
    RA_Categories__c AS ra_categories,
    RA_ClientQuintoAndar__c AS ra_client_quinto_andar,
    RA_ClosedByInactivity__c AS ra_closed_by_inactivity,
    RA_CompanyId__c AS id_ra_company_id,
    RA_CompanyName__c AS ra_company_name,
    RA_ContractSituation__c AS ra_contract_situation,
    RA_CreationDate__c AS dt_ra_creation_date,
    RA_CustomerCNPJ__c AS ra_customer_cnpj,
    RA_CustomerCity__c AS ra_customer_city,
    RA_CustomerCpf__c AS ra_customer_cpf,
    RA_CustomerEmail__c AS ra_customer_email,
    RA_CustomerInteractionsCount__c AS ra_customer_interactions_count,
    RA_CustomerName__c AS ra_customer_name,
    RA_CustomerPhone__c AS ra_customer_phone,
    RA_CustomerState__c AS ra_customer_state,
    RA_ExternalId__c AS id_ra_external_id,
    RA_Feeling__c AS ra_feeling,
    RA_HugMeStatus__c AS ra_hug_me_status,
    RA_InteractionsCount__c AS ra_interactions_count,
    RA_LastModificationDate__c AS dt_ra_last_modification_date,
    RA_LastPollDate__c AS dt_ra_last_poll_date,
    RA_ModerationDescription__c AS ra_moderation_description,
    RA_ModerationEndDate__c AS dt_ra_moderation_end_date,
    RA_ModerationPending__c AS ra_moderation_pending,
    RA_ModerationResult__c AS ra_moderation_result,
    RA_ModerationStartDate__c AS dt_ra_moderation_start_date,
    RA_PreferredContactMethod__c AS ra_preferred_contact_method,
    RA_PrivateSessionOpen__c AS ra_private_session_open,
    RA_PrivateTreatmentTime__c AS ra_private_treatment_time,
    RA_PublicResponseContent__c AS ra_public_response_content,
    RA_PublicResponseDate__c AS dt_ra_public_response_date,
    RA_PublicTreatmentTime__c AS ra_public_treatment_time,
    RA_RaFoneStatus__c AS ra_ra_fone_status,
    RA_RatingDate__c AS dt_ra_rating_date,
    RA_RatingExplanation__c AS ra_rating_explanation,
    RA_Rating__c AS ra_rating,
    RA_ReasonContact__c AS ra_reason_contact,
    RA_Reason__c AS ra_reason,
    RA_ReopenReason__c AS ra_reopen_reason,
    RA_RequestEvaluation__c AS ra_request_evaluation,
    RA_RequestModeration__c AS ra_request_moderation,
    RA_ResolvedIssue__c AS ra_resolved_issue,
    RA_Source__c AS ra_source,
    RA_StatusId__c AS id_ra_status_id,
    RA_Status__c AS ra_status,
    RA_TicketId__c AS id_ra_ticket_id,
    RA_TicketModerationsCount__c AS ra_ticket_moderations_count,
    RA_TicketUrl__c AS ra_ticket_url,
    SoniaContract__c AS sonia_contract,
    CaseRequireFollowUp__c AS case_require_follow_up,
    FavorableReview__c AS favorable_review,
    AgreementChannelBetweenPPAndIQ__c AS agreement_channel_between_pp_and_iq,
    AuthorizedByOwner__c AS authorized_by_owner,
    CrmTaskId__c AS id_crm_task_id,
    InstallmentPlan__c AS installment_plan,
    RepairValue__c AS repair_value,
    RA_TicketLink__c AS ra_ticket_link,
    DateAwaitingRA__c AS dt_date_awaiting_ra,
    DidFrontSendCompleteData__c AS did_front_send_complete_data,
    ShouldBeFCR__c AS should_be_fcr,
    CheckClosureFields__c AS check_closure_fields,
    DiscountPercentage__c AS discount_percentage,
    InvoiceType__c AS invoice_type,
    PenaltyAmount__c AS penalty_amount,
    TerminationReason__c AS termination_reason,
    Billingtype__c AS billingtype,
    CaseID__c AS case_id,
    InspectionRealized__c AS inspection_realized,
    SendToBroker__c AS send_to_broker,
    SendToBuyer__c AS send_to_buyer,
    SendToCollaborator__c AS send_to_collaborator,
    SendToInspector__c AS send_to_inspector,
    SendToPhotographer__c AS send_to_photographer,
    SendToSeller__c AS send_to_seller,
    ReplyCaseOwner__c AS reply_case_owner,
    EmailAddressEscalations__c AS email_address_escalations,
    MagicLinkCode__c AS magic_link_code,
    FinalClaimant__c AS final_claimant,
    PublicationLink__c AS publication_link,
    SocialNetwork__c AS social_network,
    PrivacyAnalysis__c AS privacy_analysis,
    CheckCollectionsCaseClosure__c AS check_collections_case_closure,
    Opportunity__c AS opportunity,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.cases
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
