SELECT
    Id AS id_dynamic_form,
    OwnerId AS id_owner,
    RecordTypeId AS id_record_type,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    ExternalId__c AS id_external,
    ParentForm__c AS id_parent_form,
    ParentRecordId__c AS id_parent_record,
    RelatedQuestion__c AS id_related_question,
    Name AS form_name,
    FormFilterValue__c AS form_filter_value,
    FormFilter__c AS form_filter,
    FormObject__c AS form_object,
    TaskManagement__c AS task_management,
    TaskType__c AS task_type,
    AnswerOptions__c AS answer_options,
    Answer__c AS answer,
    ConditionField__c AS condition_field,
    ConditionObject__c AS condition_object,
    ConditionValue__c AS condition_value,
    DataType__c AS data_type,
    FieldToValue__c AS field_to_value,
    ObjectToValue__c AS object_to_value,
    Object__c AS object_name,
    Operator__c AS operator,
    Question__c AS question,
    Section__c AS section,
    TargetField__c AS target_field,
    TargetObject__c AS target_object,
    CAST(QuestionOrder__c AS INT) AS question_order,
    CAST(IsDeleted AS BOOLEAN) AS is_deleted,
    CAST(IsActive__c AS BOOLEAN) AS is_active,
    CAST(IsConcatenation__c AS BOOLEAN) AS is_concatenation,
    CAST(IsRequired__c AS BOOLEAN) AS is_required,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(LastViewedDate AS TIMESTAMP) AS ts_last_viewed,
    CAST(LastReferencedDate AS TIMESTAMP) AS ts_last_referenced,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.dynamic_forms
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
