SELECT
    Id AS id_email_message,
    ParentId AS id_parent,
    ActivityId AS id_activity,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    ReplyToEmailMessageId AS id_reply_to_email_message,
    EmailTemplateId AS id_email_template,
    RelatedToId AS id_related_to,
    TextBody AS text_body,
    HtmlBody AS html_body,
    Headers AS headers,
    Subject AS subject,
    FromName AS from_name,
    FromAddress AS from_address,
    ValidatedFromAddress AS validated_from_address,
    ToAddress AS to_address,
    CcAddress AS cc_address,
    BccAddress AS bcc_address,
    Status AS email_status,
    MessageIdentifier AS message_identifier,
    ThreadIdentifier AS thread_identifier,
    CAST(Incoming AS BOOLEAN) AS is_incoming,
    CAST(HasAttachment AS BOOLEAN) AS has_attachment,
    CAST(IsDeleted AS BOOLEAN) AS is_deleted,
    CAST(IsPrivateDraft AS BOOLEAN) AS is_private_draft,
    CAST(IsExternallyVisible AS BOOLEAN) AS is_externally_visible,
    CAST(IsClientManaged AS BOOLEAN) AS is_client_managed,
    CAST(IsTracked AS BOOLEAN) AS is_tracked,
    CAST(IsOpened AS BOOLEAN) AS is_opened,
    CAST(IsBounced AS BOOLEAN) AS is_bounced,
    CAST(MessageDate AS TIMESTAMP) AS ts_message,
    CAST(FirstOpenedDate AS TIMESTAMP) AS ts_first_opened,
    CAST(LastOpenedDate AS TIMESTAMP) AS ts_last_opened,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.email_message
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
