SELECT
    Id AS id_opportunity,
    AccountId AS id_account,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    OwnerId AS id_owner,
    RecordTypeId AS id_record_type,
    PartnerAccountId AS id_partner_account,
    Pricebook2Id AS id_pricebook,
    CampaignId AS id_campaign,
    SyncedQuoteId AS id_synced_quote,
    ContractId AS id_contract,
    Agent__c AS id_agent,
    OfferId__c AS id_offer,
    Seller__c AS id_seller,
    FS_ChosenMortgageApplication__c AS id_fs_chosen_mortgage_application,
    FS_mortgageIntentionUuid__c AS fs_mortgage_intention_uuid,
    Name AS opportunity_name,
    Type AS opportunity_type,
    StageName AS stage_name,
    LeadSource AS lead_source,
    ForecastCategoryName AS forecast_category_name,
    FS_BankChosen__c AS fs_bank_chosen,
    FS_paymentMethod__c AS fs_payment_method,
    NextStep AS next_step,
    FS_AccountName__c AS fs_account_name,
    FS_SellerName__c AS fs_seller_name,
    FS_CreditFormLink__c AS fs_credit_form_link,
    iSolveLink__c AS isolve_link,
    Loss_Reason__c AS loss_reason,
    FS_SourceEvent__c AS fs_source_event,
    FS_CreditProposal__c AS fs_credit_proposal,
    FS_ClientResponse__c AS fs_client_response,
    FS_AgentEmail__c AS fs_agent_email,
    FS_SellerEmail__c AS fs_seller_email,
    FS_AccountPersonEmail__c AS fs_account_person_email,
    FS_AccountPhone__c AS fs_account_phone,
    FS_SellerPhone__c AS fs_seller_phone,
    Description AS description,
    CAST(Amount AS DOUBLE) AS amount,
    CAST(ExpectedRevenue AS DOUBLE) AS expected_revenue,
    CAST(Probability AS DOUBLE) AS probability,
    CAST(FS_downPaymentAmount__c AS DOUBLE) AS fs_down_payment_amount,
    CAST(Budget_Confirmed__c AS BOOLEAN) AS is_budget_confirmed,
    CAST(FS_ProceedWithQuintoAndar__c AS BOOLEAN) AS is_fs_proceed_with_quintoandar,
    CAST(Discovery_Completed__c AS BOOLEAN) AS is_discovery_completed,
    CAST(FS_isCreditFormFilled__c AS BOOLEAN) AS is_fs_credit_form_filled,
    CAST(Processo_Ativo__c AS BOOLEAN) AS is_processo_ativo,
    CAST(ROI_Analysis_Completed__c AS BOOLEAN) AS is_roi_analysis_completed,
    CAST(FS_CanUseFGTS__c AS BOOLEAN) AS is_fs_can_use_fgts,
    CAST(FS_WillUseSavings__c AS BOOLEAN) AS is_fs_will_use_savings,
    CAST(FS_HasUpdatedAmounts__c AS BOOLEAN) AS is_fs_has_updated_amounts,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(FS_CCVSigned__c AS TIMESTAMP) AS ts_fs_ccv_signed,
    CAST(FS_CCVTerminationCreatedAt__c AS TIMESTAMP) AS ts_fs_ccv_termination_created_at,
    CAST(FS_AcceptedAt__c AS TIMESTAMP) AS ts_fs_accepted_at,
    CAST(CloseDate AS DATE) AS dt_close,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.opportunity
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')