SELECT
    Id AS id_task,
    WhoId AS id_who,
    WhatId AS id_what,
    OwnerId AS id_owner,
    AccountId AS id_account,
    RecurrenceActivityId AS id_recurrence_activity,
    CAST(ContractId__c AS INT) AS id_contract,
    LastModifiedById AS id_last_modified_by,
    CallId__c AS id_call,
    EntityId__c AS id_entity,
    FS_OfferId__c AS id_fs_offer,
    FS_PurchaseSaleContract__c AS id_fs_purchase_sale_contract,
    RecordTypeId AS id_record_type,
    SourceTask__c AS id_source_task,
    CAST(WhoCount AS INT) AS who_count,
    CAST(WhatCount AS INT) AS what_count,
    CAST(RecurrenceInterval AS INT) AS recurrence_interval,
    CAST(RecurrenceDayOfWeekMask AS INT) AS recurrence_day_of_week_mask,
    CAST(RecurrenceDayOfMonth AS INT) AS recurrence_day_of_month,
    CAST(CallDurationInSeconds AS INT) AS call_duration_in_seconds,
    Subject AS subject,
    Status AS status,
    Priority AS priority,
    Type__c AS type,
    CallType AS call_type,
    CallDisposition AS call_disposition,
    CallObject AS call_object,
    TaskSubtype AS task_subtype,
    RecurrenceType AS recurrence_type,
    RecurrenceInstance AS recurrence_instance,
    RecurrenceMonthOfYear AS recurrence_month_of_year,
    RecurrenceRegeneratedType AS recurrence_regenerated_type,
    TaskName__c AS task_name,
    TaskInteractionType__c AS task_interaction_type,
    CaseCriticality__c AS case_criticality,
    CaseAccount__c AS case_account,
    Observation__c AS observation,
    DelayMessage__c AS delay_message,
    ResponsabilityContestingIsGood__c AS responsability_contesting_is_good,
    CognitoLink__c AS cognito_link,
    FS_ReasonDelay__c AS fs_reason_delay,
    FS_Seller__c AS fs_seller,
    SchedulingManagement__c AS scheduling_management,
    Source__c AS source,
    TaskAction__c AS task_action,
    TaskManagement__c AS task_management,
    ExperimentGroup__c AS experiment_group,
    UnlistingReason__c AS unlisting_reason,
    ContractIdOddOrEven__c AS contract_id_odd_even,
    CommunicationTask__c AS communication_task,
    SourceTask__c AS source_task,
    CommunicationStatus__c AS communication_status,
    CAST(SLA__c AS FLOAT) AS sla,
    CAST(HSMSent__c AS BOOLEAN) AS is_hsm_sent,
    CAST(EmailSent__c AS BOOLEAN) AS is_email_sent,
    CAST(Answer__c AS BOOLEAN) AS is_answer,
    CAST(IsHighPriority AS BOOLEAN) AS is_high_priority,
    CAST(IsDeleted AS BOOLEAN) AS is_deleted,
    CAST(IsClosed AS BOOLEAN) AS is_closed,
    CAST(IsArchived AS BOOLEAN) AS is_archived,
    CAST(IsReminderSet AS BOOLEAN) AS is_reminder_set,
    CAST(IsRecurrence AS BOOLEAN) AS is_recurrence,
    CAST(IsABTest__c AS BOOLEAN) AS is_ab_test,
    CASE
        WHEN FS_KeysReceived__c = 'Sim' THEN TRUE
        WHEN FS_KeysReceived__c = 'Não' THEN FALSE
    END AS is_fs_keys_received,
    CASE
        WHEN GetResponse__c = 'Sim' THEN TRUE
        WHEN GetResponse__c = 'Não' THEN FALSE
    END AS has_got_response,
    CASE
        WHEN PaidViaTed__c = 'Sim' THEN TRUE
        WHEN PaidViaTed__c = 'Não' THEN FALSE
    END AS has_paid_via_ted,
    CAST(QuestionResolvedInformedCustomer__c AS BOOLEAN) AS is_question_resolved,
    CASE
        WHEN WasDisagreement__c = 'Sim' THEN TRUE
        WHEN WasDisagreement__c = 'Não' THEN FALSE
    END AS has_disagreement,
    CAST(CompletedDateTime AS TIMESTAMP) AS ts_completed,
    CAST(ReminderDateTime AS TIMESTAMP) AS ts_reminder,
    CAST(ActivityDate AS TIMESTAMP) AS ts_activity,
    CAST(PassDueDate__c AS TIMESTAMP) AS ts_pass_due,
    CAST(FirstInteractionDate__c AS TIMESTAMP) AS ts_first_interaction,
    CAST(RecurrenceStartDateOnly AS TIMESTAMP) AS ts_recurrence_start,
    CAST(RecurrenceEndDateOnly AS TIMESTAMP) AS ts_recurrence_end,
    CAST(TaskCreatedDate__c AS TIMESTAMP) AS ts_task_created,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    CAST(KeyDeliveryDate__c AS TIMESTAMP) AS ts_key_delivery,
    CAST(ReturnDateCustomer__c AS TIMESTAMP) AS ts_return_date_customer,
    CAST(SchedulingDate__c AS TIMESTAMP) AS ts_scheduling,
    CAST(TaskDueDateFormula__c AS TIMESTAMP) AS ts_task_due_date_formula,
    Description AS description,
    Type AS type_2,
    CreatedById AS id_created_by_id,
    IsVisibleInSelfService AS is_visible_in_self_service,
    RecurrenceTimeZoneSidKey AS recurrence_time_zone_sid_key,
    FeedItemId__c AS id_feed_item_id,
    Flow__c AS flow,
    FS_CRI_HaveDemandNote__c AS fs_cri_have_demand_note,
    FS_CRI_Have_Demand_Note__c AS fs_cri_have_demand_note_2,
    FS_CRI_RegistrationCompleted__c AS fs_cri_registration_completed,
    FS_CRI_Registration_Completed__c AS fs_cri_registration_completed_2,
    FS_ClientRequestTime__c AS fs_client_request_time,
    FS_Buyer__c AS fs_buyer,
    FS_ContactReturnDate__c AS dt_fs_contact_return_date,
    FS_CaseSubject__c AS fs_case_subject,
    FS_MadeByWhere__c AS fs_made_by_where,
    CloseSource__c AS close_source,
    FS_AVE_PasswordTask__c AS fs_ave_password_task,
    FS_AVE_ProtocolTask__c AS fs_ave_protocol_task,
    FS_AVE_RequestDateTask__c AS dt_fs_ave_request_date_task,
    FS_ApprovalRequested__c AS fs_approval_requested,
    FS_RegistrationCompleted__c AS fs_registration_completed,
    FS_AddendumReceived__c AS fs_addendum_received,
    FS_DoesBuyerWantLeaseTermination__c AS fs_does_buyer_want_lease_termination,
    FS_LeaseTerminationSent__c AS fs_lease_termination_sent,
    FS_PPTransferAddendumSent__c AS fs_pp_transfer_addendum_sent,
    Case__c AS id_case,
    Team__c AS team,
    IntegrationJob__c AS integration_job,
    FS_CRIDoneDateTask__c AS dt_fs_cri_done_date_task,
    FS_RegistrationReceived__c AS fs_registration_received,
    FS_CancelledNotFollowingCRN__c AS fs_cancelled_not_following_crn,
    FS_DraftReceivedBuyers__c AS fs_draft_received_buyers,
    FS_DraftReceivedSellers__c AS fs_draft_received_sellers,
    FS_CanceledReason__c AS fs_canceled_reason,
    Complexity__c AS complexity,
    ContractLink__c AS contract_link,
    DueDateFutureStatus__c AS dt_due_date_future_status,
    DueDateIn2Days__c AS dt_due_date_in2_days,
    DueDateStatus__c AS dt_due_date_status,
    ManualRepair__c AS manual_repair,
    Relisting__c AS relisting,
    TRDate__c AS dt_tr_date,
    TdDate__c AS dt_td_date,
    Termination__c AS termination,
    TfDate__c AS dt_tf_date,
    LDTOff__c AS ldt_off,
    LeadTime__c AS lead_time,
    Ruler__c AS ruler,
    TdToToday__c AS td_to_today,
    TaskStage__c AS task_stage,
    FS_TaskCreatedDate__c AS dt_fs_task_created_date,
    HSMStatus__c AS hsm_status,
    Supervisor__c AS supervisor,
    Contract__c AS contract,
    CaseClosedDate__c AS dt_case_closed_date,
    CaseType__c AS case_type,
    ContractName__c AS contract_name,
    DistanceBetweenPointsKm__c AS distance_between_points_km,
    OpenDays__c AS open_days,
    ActiveUser__c AS active_user,
    RecipientPerson__c AS recipient_person,
    Bypass_Validation__c AS bypass_validation,
    FS_AdditionalInformation__c AS fs_additional_information,
    FS_AdvantagesPresented__c AS fs_advantages_presented,
    FS_BY_Document_List__c AS fs_by_document_list,
    FS_BY_Reason_for_Request__c AS fs_by_reason_for_request,
    FS_BankChosenByClient__c AS fs_bank_chosen_by_client,
    FS_BanksNotDesiredForFinancing__c AS fs_banks_not_desired_for_financing,
    FS_BuyerWithdrawnFromPurchaseProcess__c AS fs_buyer_withdrawn_from_purchase_process,
    FS_CanUseFGTS__c AS fs_can_use_fgts,
    FS_ClientResponse__c AS fs_client_response,
    FS_CommentsOrRecommendationsToClient__c AS fs_comments_or_recommendations_to_client,
    FS_CommercialContactMade__c AS fs_commercial_contact_made,
    FS_CreditFormLinkSent__c AS fs_credit_form_link_sent,
    FS_DigitalFlowAccepted__c AS fs_digital_flow_accepted,
    FS_DigitalFlowEligibility__c AS fs_digital_flow_eligibility,
    FS_DisputeUpheld__c AS fs_dispute_upheld,
    FS_Dispute_upheld__c AS fs_dispute_upheld_2,
    FS_DocumentsSentToBank__c AS fs_documents_sent_to_bank,
    FS_FormCompletionRequested__c AS fs_form_completion_requested,
    FS_FormsForSignatureList__c AS fs_forms_for_signature_list,
    FS_InspectionDataCompletedInISolve__c AS fs_inspection_data_completed_in_i_solve,
    FS_OnboardingChannel__c AS fs_onboarding_channel,
    FS_OpenBackOfficeFollowUp__c AS fs_open_back_office_follow_up,
    FS_PreProposalClientGuidance__c AS fs_pre_proposal_client_guidance,
    FS_ProceedWithQuintoAndar__c AS fs_proceed_with_quinto_andar,
    FS_ProposalReadyToSendToClient__c AS fs_proposal_ready_to_send_to_client,
    FS_ProposalsReadyToSendToClient__c AS fs_proposals_ready_to_send_to_client,
    FS_ProposalsRequiringDispute__c AS fs_proposals_requiring_dispute,
    FS_Reason__c AS fs_reason,
    FS_Reasons__c AS fs_reasons,
    FS_RelationshipBanks__c AS fs_relationship_banks,
    FS_RequestJustification__c AS fs_request_justification,
    FS_RequiredAdditionalDocuments__c AS fs_required_additional_documents,
    FS_SL_Document_List__c AS fs_sl_document_list,
    FS_SL_Reason_for_Request__c AS fs_sl_reason_for_request,
    FS_SendAssessmentToService__c AS fs_send_assessment_to_service,
    FS_WasOnboardingCompleted__c AS fs_was_onboarding_completed,
    FS_isCreditFormFilled__c AS fs_is_credit_form_filled,
    Status_Documenta_o__c AS status_documenta_o,
    CCVPaymentMethod__c AS ccv_payment_method,
    FS_AdviseCustomersConsumption__c AS fs_advise_customers_consumption,
    FS_ForSaleTeam__c AS fs_for_sale_team,
    AllocatedCompany__c AS allocated_company,
    DateAndTimeOfTheAppointment__c AS dt_date_and_time_of_the_appointment,
    EstimatedDistance__c AS estimated_distance,
    ExpectedCost__c AS expected_cost,
    FinalPriceOfTheRace__c AS final_price_of_the_race,
    RaceCancelled__c AS race_cancelled,
    RaceFinished__c AS race_finished,
    ReasonForCancellation__c AS reason_for_cancellation,
    WasTheAppointmentKept__c AS was_the_appointment_kept,
    IsSpoc__c AS is_spoc,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.task
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
