SELECT
    Id AS id_task,
    WhoId AS id_who,
    WhatId AS id_what,
    OwnerId AS id_owner,
    AccountId AS id_account,
    RecurrenceActivityId AS id_recurrence_activity,
    CAST(ContractId__c AS INT) AS id_contract,
    LastModifiedById AS id_last_modified_by,
    CallId__c AS id_call,
    EntityId__c AS id_entity,
    FS_OfferId__c AS id_fs_offer,
    FS_PurchaseSaleContract__c AS id_fs_purchase_sale_contract,
    RecordTypeId AS id_record_type,
    CAST(WhoCount AS INT) AS who_count,
    CAST(WhatCount AS INT) AS what_count,
    CAST(RecurrenceInterval AS INT) AS recurrence_interval,
    CAST(RecurrenceDayOfWeekMask AS INT) AS recurrence_day_of_week_mask,
    CAST(RecurrenceDayOfMonth AS INT) AS recurrence_day_of_month,
    CAST(CallDurationInSeconds AS INT) AS call_duration_in_seconds,
    Subject AS subject,
    Status AS status,
    Priority AS priority,
    Type__c AS type,
    CallType AS call_type,
    CallDisposition AS call_disposition,
    CallObject AS call_object,
    TaskSubtype AS task_subtype,
    RecurrenceType AS recurrence_type,
    RecurrenceInstance AS recurrence_instance,
    RecurrenceMonthOfYear AS recurrence_month_of_year,
    RecurrenceRegeneratedType AS recurrence_regenerated_type,
    TaskName__c AS task_name,
    TaskInteractionType__c AS task_interaction_type,
    CaseCriticality__c AS case_criticality,
    CaseAccount__c AS case_account,
    Observation__c AS observation,
    DelayMessage__c AS delay_message,
    ResponsabilityContestingIsGood__c AS responsability_contesting_is_good,
    CognitoLink__c AS cognito_link,
    FS_ReasonDelay__c AS fs_reason_delay,
    FS_Seller__c AS fs_seller,
    SchedulingManagement__c AS scheduling_management,
    Source__c AS source,
    TaskAction__c AS task_action,
    TaskManagement__c AS task_management,
    ExperimentGroup__c AS experiment_group,
    UnlistingReason__c AS unlisting_reason,
    ContractIdOddOrEven__c AS contract_id_odd_even,
    CAST(SLA__c AS FLOAT) AS sla,
    CAST(Answer__c AS BOOLEAN) AS is_answer,
    CAST(IsHighPriority AS BOOLEAN) AS is_high_priority,
    CAST(IsDeleted AS BOOLEAN) AS is_deleted,
    CAST(IsClosed AS BOOLEAN) AS is_closed,
    CAST(IsArchived AS BOOLEAN) AS is_archived,
    CAST(IsReminderSet AS BOOLEAN) AS is_reminder_set,
    CAST(IsRecurrence AS BOOLEAN) AS is_recurrence,
    CAST(IsABTest__c AS BOOLEAN) AS is_ab_test,
    CASE
        WHEN FS_KeysReceived__c = 'Sim' THEN TRUE
        WHEN FS_KeysReceived__c = 'Não' THEN FALSE
    END AS is_fs_keys_received,
    CASE
        WHEN GetResponse__c = 'Sim' THEN TRUE
        WHEN GetResponse__c = 'Não' THEN FALSE
    END AS has_got_response,
    CASE
        WHEN PaidViaTed__c = 'Sim' THEN TRUE
        WHEN PaidViaTed__c = 'Não' THEN FALSE
    END AS has_paid_via_ted,
    CAST(QuestionResolvedInformedCustomer__c AS BOOLEAN) AS is_question_resolved,
    CASE
        WHEN WasDisagreement__c = 'Sim' THEN TRUE
        WHEN WasDisagreement__c = 'Não' THEN FALSE
    END AS has_disagreement,
    CAST(CompletedDateTime AS TIMESTAMP) AS ts_completed,
    CAST(ReminderDateTime AS TIMESTAMP) AS ts_reminder,
    CAST(ActivityDate AS TIMESTAMP) AS ts_activity,
    CAST(PassDueDate__c AS TIMESTAMP) AS ts_pass_due,
    CAST(FirstInteractionDate__c AS TIMESTAMP) AS ts_first_interaction,
    CAST(RecurrenceStartDateOnly AS TIMESTAMP) AS ts_recurrence_start,
    CAST(RecurrenceEndDateOnly AS TIMESTAMP) AS ts_recurrence_end,
    CAST(TaskCreatedDate__c AS TIMESTAMP) AS ts_task_created,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    CAST(KeyDeliveryDate__c AS TIMESTAMP) AS ts_key_delivery,
    CAST(ReturnDateCustomer__c AS TIMESTAMP) AS ts_return_date_customer,
    CAST(SchedulingDate__c AS TIMESTAMP) AS ts_scheduling,
    CAST(TaskDueDateFormula__c AS TIMESTAMP) AS ts_task_due_date_formula,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.task
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
