SELECT
    Id AS id_task,
    WhoId AS id_who,
    WhatId AS id_what,
    OwnerId AS id_owner,
    AccountId AS id_account,
    RecurrenceActivityId AS id_recurrence_activity,
    CAST(ContractId__c AS INT) AS id_contract,
    LastModifiedById AS id_last_modified_by,
    CAST(WhoCount AS INT) AS who_count,
    CAST(WhatCount AS INT) AS what_count,
    CAST(RecurrenceInterval AS INT) AS recurrence_interval,
    CAST(RecurrenceDayOfWeekMask AS INT) AS recurrence_day_of_week_mask,
    CAST(RecurrenceDayOfMonth AS INT) AS recurrence_day_of_month,
    CAST(CallDurationInSeconds AS INT) AS call_duration_in_seconds,
    Subject AS subject,
    Status AS status,
    Priority AS priority,
    Type__c AS type,
    CallType AS call_type,
    CallDisposition AS call_disposition,
    CallObject AS call_object,
    TaskSubtype AS task_subtype,
    RecurrenceType AS recurrence_type,
    RecurrenceInstance AS recurrence_instance,
    RecurrenceMonthOfYear AS recurrence_month_of_year,
    RecurrenceRegeneratedType AS recurrence_regenerated_type,
    TaskName__c AS task_name,
    TaskInteractionType__c AS task_interaction_type,
    CaseCriticality__c AS case_criticality,
    CaseAccount__c AS case_account,
    Observation__c AS observation,
    DelayMessage__c AS delay_message,
    ResponsabilityContestingIsGood__c AS responsability_contesting_is_good,
    CAST(Answer__c AS BOOLEAN) AS is_answer,
    CAST(IsHighPriority AS BOOLEAN) AS is_high_priority,
    CAST(IsDeleted AS BOOLEAN) AS is_deleted,
    CAST(IsClosed AS BOOLEAN) AS is_closed,
    CAST(IsArchived AS BOOLEAN) AS is_archived,
    CAST(IsReminderSet AS BOOLEAN) AS is_reminder_set,
    CAST(IsRecurrence AS BOOLEAN) AS is_recurrence,
    CAST(CompletedDateTime AS TIMESTAMP) AS ts_completed,
    CAST(ReminderDateTime AS TIMESTAMP) AS ts_reminder,
    CAST(ActivityDate AS TIMESTAMP) AS ts_activity,
    CAST(PassDueDate__c AS TIMESTAMP) AS ts_pass_due,
    CAST(FirstInteractionDate__c AS TIMESTAMP) AS ts_first_interaction,
    CAST(RecurrenceStartDateOnly AS TIMESTAMP) AS ts_recurrence_start,
    CAST(RecurrenceEndDateOnly AS TIMESTAMP) AS ts_recurrence_end,
    CAST(TaskCreatedDate__c AS TIMESTAMP) AS ts_task_created,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.task
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
