SELECT
    Id AS id_termination,
    OwnerId AS id_owner,
    CAST(ContractId__c AS INT) AS id_contract,
    CAST(PropertyId__c AS INT) AS id_house,
    CAST(ExternalId__c AS INT) AS id_external,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    Case__c AS case,
    Contract__c AS contract,
    Name AS termination_number,
    TerminationStatus__c AS termination_status,
    ResponsibleOffManager__c AS responsible_off_manager,
    TerminationUrl__c AS termination_url,
    RequestedBy__c AS requested_by,
    BudgetApprovalResponsePP__c AS budget_approval_pp_response,
    BudgetApprovalResponseIQ__c AS budget_approval_iq_response,
    DescriptionAgreementAndImprovements__c AS description_agreement_and_improvements,
    FeedItemComment__c AS feed_item_comment,
    CAST(AdminTermination__c AS BOOLEAN) AS admin_termination,
    CAST(AllRepairsExemptedByOwner__c AS BOOLEAN) AS all_repairs_exempted_by_owner,
    CAST(BeforeRental__c AS BOOLEAN) AS before_rental,
    CAST(AgreementAndImprovements__c AS BOOLEAN) AS agreement_and_improvements,
    CAST(Eviction__c AS BOOLEAN) AS eviction,
    CAST(ConsumptionProofSubmissionIQ__c AS BOOLEAN) AS consumption_proof_submission_iq,
    CAST(HighValueContract__c AS BOOLEAN) AS high_value_contract,
    CAST(InspectionOptedOut__c AS BOOLEAN) AS inspection_opted_out,
    CAST(InspectionRequired__c AS BOOLEAN) AS inspection_required,
    CAST(IntermediationRequired__c AS BOOLEAN) AS intermediation_required,
    CAST(InternalAdministration__c AS BOOLEAN) AS internal_administration,
    CAST(JobTransfer__c AS BOOLEAN) AS job_transfer,
    CAST(LandlordSelling__c AS BOOLEAN) AS land_lord_selling,
    CAST(NoticeDue__c AS BOOLEAN) AS notice_due,
    CAST(ProOwner__c AS BOOLEAN) AS pro_owner,
    CAST(RepairsChargedARorPP__c AS BOOLEAN) AS repairs_charged_ar_or_pp,
    CAST(RepairsChargedPP__c AS BOOLEAN) AS repairs_charged_pp,
    CAST(RepairsChargedToTenant__c AS BOOLEAN) AS repairs_charged_to_tenant,
    CAST(RepairsContestedByTenant__c AS BOOLEAN) AS repairs_contested_by_tenant,
    CAST(RepairsDetectedByOwner__c AS BOOLEAN) AS repairs_detected_by_owner,
    CAST(RepairsDetectedInternally__c AS BOOLEAN) AS repairs_detected_internally,
    CAST(SuccesContactIQ__c AS BOOLEAN) AS success_contact_iq,
    CAST(SuccesContactPP__c AS BOOLEAN) AS success_contact_pp,
    CAST(TenantCondominiumPayer__c AS BOOLEAN) AS tenant_condominium_payer,
    CAST(TerminationInFirstYear__c AS BOOLEAN) AS termination_in_first_year,
    CAST(TerminationWithPenalty__c AS BOOLEAN) AS termination_with_penalty,
    CAST(RelistingEnabled__c AS BOOLEAN) AS relisting_enable,
    CAST(OwnerAnsweredBudgetApprovalReview__c AS BOOLEAN) AS owner_answered_budget_approval_review,
    CAST(OwnerAgreedBudgetApprovalReview__c AS BOOLEAN) AS owner_agreed_budget_approval_review,
    CAST(TenantAnsweredBudgetApprovalReview__c AS BOOLEAN) AS tenant_answered_budget_approval_review,
    CAST(TenantAgreedBudgetApprovalReview__c AS BOOLEAN) AS tenant_agreed_budget_approval_review,
    CAST(HasBudgetApproval__c AS BOOLEAN) AS has_budget_approval,
    CAST(IsValidLetter__c AS BOOLEAN) AS is_valid_letter,
    CAST(IsDeleted AS BOOLEAN) AS is_deleted,
    CAST(TRTerminationCreatedDate__c AS DATE) AS dt_tr_termination_created,
    CAST(VacancyDate__c AS DATE) AS dt_vacancy,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    CAST(LastActivityDate AS TIMESTAMP) AS ts_last_activity,
    CAST(LastViewedDate AS TIMESTAMP) AS ts_last_viewed,
    CAST(LastReferencedDate AS TIMESTAMP) AS ts_last_referenced,
    dt_updated,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.terminations
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
