SELECT
    Id AS id_termination,
    OwnerId AS id_owner,
    ContractId__c AS id_contract,
    PropertyId__c AS id_house,
    ExternalId__c AS id_external,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    Name AS termination_number,
    TerminationStatus__c AS termination_status,
    BudgetApprovalResponseIQ__c AS budget_approval_iq_response,
    ResponsibleOffManager__c AS responsible_off_manager,
    TerminationUrl__c AS termination_url,
    RequestedBy__c AS requested_by,
    BudgetApprovalResponsePP__c AS budget_approval_pp_response,
    AdminTermination__c AS admin_termination,
    AllRepairsExemptedByOwner__c AS all_repairs_exempted_by_owner,
    BeforeRental__c AS before_rental,
    AgreementAndImprovements__c AS agreement_and_improvements,
    Eviction__c AS eviction,
    ConsumptionProofSubmissionIQ__c AS consumption_proof_submission_iq,
    HighValueContract__c AS high_value_contract,
    InspectionOptedOut__c AS inspection_opted_out,
    InspectionRequired__c AS inspection_required,
    IntermediationRequired__c AS intermediation_required,
    InternalAdministration__c AS internal_administration,
    JobTransfer__c AS job_transfer,
    LandlordSelling__c AS land_lord_selling,
    NoticeDue__c AS notice_due,
    ProOwner__c AS pro_owner,
    RepairsChargedARorPP__c AS repairs_charged_ar_or_pp,
    RepairsChargedPP__c AS repairs_charged_pp,
    RepairsChargedToTenant__c AS repairs_charged_to_tenant,
    RepairsContestedByTenant__c AS repairs_contested_by_tenant,
    RepairsDetectedByOwner__c AS repairs_detected_by_owner,
    RepairsDetectedInternally__c AS repairs_detected_internally,
    SuccesContactIQ__c AS success_contract_iq,
    SuccesContactPP__c AS success_contract_pp,
    TenantCondominiumPayer__c AS tenant_condominium_payer,
    TerminationInFirstYear__c AS termination_in_first_year,
    TerminationWithPenalty__c AS termination_with_penalty,
    Case__c AS case,
    Contract__c AS contract,
    RelistingEnabled__c AS relisting_enable,
    DescriptionAgreementAndImprovements__c AS description_agreement_and_improvements,
    OwnerAnsweredBudgetApprovalReview__c AS owner_answered_budget_approval_review,
    OwnerAgreedBudgetApprovalReview__c AS owner_agreed_budget_approval_review,
    TenantAnsweredBudgetApprovalReview__c AS tenant_answered_budget_approval_review,
    TenantAgreedBudgetApprovalReview__c AS tenant_agreed_budget_approval_review,
    FeedItemComment__c AS feed_item_comment,
    HasBudgetApproval__c AS has_budget_approval,
    IsValidLetter__c AS is_valid_letter,
    IsDeleted AS is_deleted,
    TRTerminationCreatedDate__c AS ts_tr_termination_created,
    VacancyDate__c AS ts_vacancy,
    CreatedDate AS ts_created,
    LastModifiedDate AS ts_last_modified,
    SystemModstamp AS system_mod_stamp,
    LastActivityDate AS ts_last_activity,
    LastViewedDate AS ts_last_viewed,
    LastReferencedDate AS ts_last_referenced,
    dt_updated,
    year,
    month,
    day
FROM
    datalake_salesforce_raw.terminations
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
