SELECT
    Id AS id_user_salesforce,
    UserRoleId AS id_user_role,
    ProfileId AS id_profile,
    DelegatedApproverId AS id_delegated_approver,
    ManagerId AS id_manager,
    IndividualId AS id_individual,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    Username AS username,
    LastName AS last_name,
    FirstName AS first_name,
    MiddleName AS middle_name,
    Suffix AS suffix,
    Name AS name,
    CompanyName AS company_name,
    Division AS division,
    Department AS department,
    Title AS title,
    Street AS street,
    City AS city,
    State AS state,
    PostalCode AS postal_code,
    Country AS country,
    Latitude AS latitude,
    Longitude AS longitude,
    GeocodeAccuracy AS geocode_accuracy,
    Address AS address,
    Email AS email,
    EmailPreferencesAutoBcc AS email_preferences_auto_bcc,
    EmailPreferencesAutoBccStayInTouch AS email_preferences_auto_bcc_stay_in_touch,
    EmailPreferencesStayInTouchReminder AS email_preferences_stay_in_touch_reminder,
    SenderEmail AS sender_email,
    SenderName AS sender_name,
    Signature AS signature,
    StayInTouchSubject AS stay_in_touch_subject,
    StayInTouchSignature AS stay_in_touch_signature,
    StayInTouchNote AS stay_in_touch_note,
    Phone AS phone,
    Fax AS fax,
    MobilePhone AS mobile_phone,
    Alias AS alias,
    CommunityNickname AS community_nickname,
    BadgeText AS badge_text,
    TimeZoneSidKey AS time_zone_sid_key,
    LocaleSidKey AS locale_sid_key,
    ReceivesInfoEmails AS receives_info_emails,
    ReceivesAdminInfoEmails AS receives_admin_info_emails,
    EmailEncodingKey AS email_encoding_key,
    UserType AS user_type,
    StartDay AS start_day,
    EndDay AS end_day,
    LanguageLocaleKey AS language_locale_key,
    EmployeeNumber AS employee_number,
    CAST(NumberOfFailedLogins AS INT) AS failed_logins,
    BPO__c AS bpo,
    CAST(IsActive AS BOOLEAN) AS is_active,
    CAST(LastLoginDate AS TIMESTAMP) AS ts_last_login,
    CAST(LastPasswordChangeDate AS TIMESTAMP) AS ts_last_password_change,
    CAST(CreatedDate AS TIMESTAMP) AS ts_created,
    CAST(LastModifiedDate AS TIMESTAMP) AS ts_last_modified,
    CAST(SystemModstamp AS TIMESTAMP) AS ts_system_mod,
    CAST(PasswordExpirationDate AS TIMESTAMP) AS ts_password_expiration,
    CAST(SuAccessExpirationDate AS TIMESTAMP) AS ts_su_access_expiration,
    CAST(OfflineTrialExpirationDate AS TIMESTAMP) AS ts_offline_trial_expiration,
    dt_updated,
    year,
    month,
    day,
    NOW() AS ts_load
FROM
    datalake_salesforce_raw.users
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
