SELECT
    idusuarioempresa AS id_company_user,
    idportal AS id_portal,
    idempresa AS id_company,
    idcuenta AS id_account,
    idtipodeusuario AS id_user_type,
    idEstadoCivil AS id_marital_status,
    idPais AS id_country,
    idProvincia AS id_state,
    idCiudad AS id_city,
    idFacebook AS id_facebook,
    idIdioma AS id_language,
    idGeolocalizacion AS id_geolocation,
    idZona AS id_zone,
    nombre AS first_name,
    apellido AS last_name,
    username AS username,
    email AS email,
    prefijo AS phone_prefix,
    telefono AS phone_number,
    cargo AS job_title,
    area AS department,
    celPrefijo AS mobile_prefix,
    celNumero AS mobile_number,
    mailusername AS email_username,
    sexo AS gender_code,
    bloqueado AS is_blocked,
    permisoenviomailinterno AS has_internal_email_permission,
    emailusuariovalido AS is_email_valid,
    fbaja AS dt_deactivated,
    falta AS ts_missing,
    ultimavezqueselogueo AS ts_last_logged_in,
    fechaalta AS ts_created
FROM
    datalake_imovelweb_raw.usuariosempresas
