select
	id,
	campaign_code as id_campaign,
	campaign_name, 
	name,
	identification,
	email,
	alternative_email,
	phone,
	alternative_phone, 
	priority,
	type,
	status,
	cast(nps_answer as smallint),
	cast(last_nps_answer as smallint),
	nps_comment,
	justifications,
	lot_code,
	assignee,
	tags,
	categories,
	elapsed_time as seconds_spent_answering,
	cast(deadline as timestamp) as ts_deadline,
	cast(reminder_time as timestamp) as ts_reminder,
	cast(dispatch_time as timestamp) as ts_dispatch,
	cast(time as timestamp) as ts_answer_sent,
	year,
	month,
	day
from datalake_tracksale_raw.answer
where year={year} and month={month} and day={day}