SELECT
    id_colaborador AS id_employee,
    id_gestor AS id_manager,
    matricula AS employee_registration,
    empresa AS company,
    email AS employee_email,
    email_navent AS employee_email_navent,
    nome AS employee_name,
    status AS employee_status,
    cargo AS employee_position,
    classe_cargo AS employee_position_class,
    gestor AS employee_manager,
    nacionalidade AS employee_nationality,
    tenure,
    motivo_desligamento AS employee_dismissal_reason,
    sexo AS employee_gender,
    departamento AS employee_department,
    centro_de_custo AS employee_cost_center,
    sub_diretoria AS employee_sub_board,
    diretoria AS employee_board,
    vertical AS employee_vertical,
    marca_produto_dedicado AS employee_product_brand,
    business_navent AS employee_business_navent,
    pais AS employee_country,
    hrbp AS employee_hrbp,
    banda AS employee_band,
    naturalidade_cidade AS employee_city_birth,
    restricciones_alimentarias AS employee_food_restrictions,
    residencia_pais AS employee_country_residence,
    origen_etnico AS employee_ethnic_origin,
    identidade_genero AS employee_gender_identity,
    orientacao_sexual AS employee_genderual_orientation,
    tipo_deficiencia AS employee_deficiency_type,
    neurodiversidade AS employee_neurodiversity,
    estado_civil AS employee_marital_status,
    religiosidade AS employee_reliosity,
    tipo_de_vivienda AS housing_type,
    situacion_en_el_pais AS situation_in_the_country,
    potencial AS potential,
    criticidade AS criticality,
    status_gestor AS manager_status,
    email_gestor AS manager_email,
    salario_moeda_local AS employee_salary_local_currency,
    faixa_etaria AS employee_age_group,
    FLOAT(salario) AS employee_salary,
    CASE
        WHEN fl_lider = 1
            THEN TRUE
        ELSE FALSE
    END  AS is_leader,
    to_date(dt_inicio) AS dt_employee_admission,
    to_date(dt_desligamento) AS dt_employee_dismissal,
    to_date(dt_desligamento) AS dt_employee_birth,
    ts_load AS ts_load
FROM datalake_gsheets_raw.navent_convenia_like