SELECT
    employees_name,
    email,
    to_date(admission, 'MM/dd/yyyy') as admission,
    manager,
    department,
    cost_center,
    subdirectorate,
    IF(fl_lider = 'L', True, False) as is_leader,
    direct_headcount,
    squad_1_primary,
    squad_2,
    squad_3,
    squad_4,
    squad_5,
    squad_6,
    squad_7,
    squad_8,
    squad_9,
    squad_10,
    tribe_1_primary,
    tribe_2,
    tribe_3,
    tribe_4,
    tribe_5,
    tribe_6,
    tribe_7,
    tribe_8,
    tribe_9,
    tribe_10,
    line_type,
    line,
    internal_job,
    equivalencia_cargos as position_equivalency,
    tribe_or_squad_leader,
    api_squad_1_primary,
    api_squad_2,
    api_squad_3,
    api_squad_4,
    api_squad_5,
    api_squad_6,
    api_squad_7,
    api_squad_8,
    api_squad_9,
    api_squad_10
FROM datalake_gsheets_raw.team_formation_tech_active