SELECT
    nome as name,
    email as email,
    banda as band,
    gestor as manager,
    cargo as position,
    departamento as department,
    centro_de_custo as cost_center,
    sub_diretoria as sub_directorate,
    IF(fl_lider = 'L', True, False) as is_leader,
    hc_direto as direct_headcount,
    squad_1_primaria as squad_1_primaria,
    squad_2,
    squad_3,
    squad_4,
    squad_5,
    squad_6,
    tribo_time_1_primaria as tribe_1_primary,
    tribo_time_2 as tribe_2,
    tribo_time_3 as tribe_3,
    tribo_time_4 as tribe_4,
    tribo_time_5 as tribe_5,
    tribo_time_6 as tribe_6,
    tipo_de_linha as line_type,
    linha as line,
    internal_job,
    equivalencia_cargos as position_equivalency,
    squad_or_tribe_leader
FROM datalake_gsheets_raw.team_formation_tech_dismissed