drop table if exists public.dim_lead;
create table if not exists public.dim_lead
(
 sk_lead bigint,
 id bigint,
 external_id varchar(255),
 region_id integer,
 area_total integer,
 bairro varchar(200),
 cep varchar(9),
 cidade varchar(200),
 complemento varchar(500),
 endereco varchar(300),
 numero varchar(200),
 nome_anunciante varchar(255),
 numero_banheiros integer,
 numero_quartos integer,
 numero_suites integer,
 url_anuncio varchar(255),
 telefone_anunciante varchar(100),
 tipo varchar(255),
 email varchar(250),
 email_captador varchar(250),
 telefone_captador varchar(250),
 lat numeric(10,7),
 lng numeric(10,7),
 condominio integer,
 iptu integer,
 ub_page_variant varchar(255),
 ub_page_name varchar(255),
 reason varchar(255),
 reason_detail varchar(255),
 deadline_of_new_contact varchar(255),
 status varchar(255),
 origem varchar(255),
 proprietario_nome varchar(255),
 proprietario_email varchar(255),
 affiliate_type varchar(256),
 dados_afiliado_cidade_atuacao varchar(100),
 utm_source varchar(255),
 utm_medium varchar(255),
 utm_campaign varchar(255),
 utm_content varchar(255),
 utm_term varchar(255),
 tracking_platform varchar(255),
 tracking_region varchar(255),
 tracking_city varchar(255),
 network varchar(255),
 usuario_que_indicou_id varchar(255),
 score_factor bigint,
 b2b_type varchar(256),
 sales_company varchar(255),
 sale_price bigint,
 automatically_discarded integer,
 processado smallint,
 is_b2b boolean,
 is_for_rent boolean,
 is_for_sale boolean,
 dentro_area_atuacao integer,
 is_enriched_data boolean,
 mencionar integer,
 captado_em date,
 dados_afiliado_inicio_atuacao timestamp without time zone,
 ts_sales_company_sent timestamp without time zone,
 criado_em timestamp without time zone,
 atualizado_em timestamp without time zone,
 load_timestamp timestamp without time zone
);

ALTER TABLE public.dim_lead OWNER TO databricks;