drop table if exists public.dim_booking;
create table if not exists public.dim_booking
( 
  sk_booking integer not null encode az64,
  sk_rent_flow_taxonomy bigint encode az64,
  id_booking integer encode az64,
  id_visitor bigint encode az64,
  id_visit bigint encode az64,
  id_property bigint encode az64,
  id_agent bigint encode az64,
  id_attendant bigint encode az64,
  id_rental_flow bigint encode az64,
  rescheduled_from_id integer encode az64,
  visit_intent varchar(100) encode lzo,
  buyer_intention varchar(100)   encode lzo,
  type varchar(255) encode lzo,
  confirmed varchar(100),
  performed varchar(100),
  closed varchar(100),
  is_rescheduled boolean,
  flg_via_reschedule boolean,
  is_first_booking_auto boolean,
  flg_branded boolean,
  visitor_arrived varchar(255),
  agent_arrived varchar(255),
  owner_arrived varchar(255),
  successful_entrance varchar(255),
  is_visit_created_from_app boolean,
  is_visit_last_updated_from_app boolean,
  visit_follow_up varchar(255) encode lzo,
  status varchar(255) encode lzo,
  slot_dia integer encode az64,
  reason varchar(255) encode lzo,
  cancellation_reason varchar(255) encode lzo,
  cancellation_reason_category varchar(255) encode lzo,
  reason_category varchar(255) encode lzo,
  responsible varchar(255) encode lzo,
  last_update_source varchar(255) encode lzo,
  first_update_source varchar(255) encode lzo,
  visitor_missing_reason varchar(255) encode lzo,
  agent_missing_reason varchar(255) encode lzo,
  owner_missing_reason varchar(255) encode lzo,
  troublesome_entrance varchar(255) encode lzo,
  checkin_status varchar(255) encode lzo,
  user_sale_booking_creator varchar(255) encode lzo,
  partner_3p_supply varchar(255) encode lzo,
  partner_3p_demand varchar(255) encode lzo,
  app_type varchar(255) encode lzo,
  media_source varchar(255) encode lzo,
  adjust_network varchar(255) encode lzo,
  utm_source varchar(255) encode lzo,
  utm_medium varchar(1024) encode lzo,
  utm_campaign varchar(2000) encode lzo,
  utm_content varchar(255) encode lzo,
  utm_term varchar(255) encode lzo,
  mkt_category varchar(255) encode lzo,
  mkt_flow varchar(255) encode lzo,
  mkt_completion varchar(255) encode lzo,
  mkt_origin varchar(255) encode lzo,
  mkt_channel varchar(255) encode lzo,
  mkt_medium varchar(255) encode lzo,
  mkt_source varchar(255) encode lzo,
  mkt_platform varchar(255) encode lzo,
  is_3p_supply boolean,
  is_3p_demand boolean,
  dt_visit_follow_up timestamp without time zone encode az64,
  ts_visit_follow_up_local timestamp without time zone encode az64,
  dt_scheduling timestamp without time zone encode az64,
  ts_scheduling_local timestamp without time zone encode az64,
  dt_cancel timestamp without time zone encode az64,
  ts_cancel_local timestamp without time zone encode az64,
  dt_created timestamp without time zone encode az64,
  ts_created_local timestamp without time zone encode az64,
  dt_updated timestamp without time zone encode az64,
  ts_load timestamp without time zone encode az64,
  primary key (sk_booking)
)
diststyle key
distkey (sk_booking)
;

ALTER TABLE public.dim_booking OWNER TO databricks;