from bietlejuice.jobs.etl.crm.tasks.closing import CRMTasksClosing
from bietlejuice.jobs.etl.crm.tasks.credit import CRMTasksCredit
from bietlejuice.jobs.etl.crm.tasks.crm_tasks_table_enum import CRMTasksTableEnum
from bietlejuice.jobs.etl.crm.tasks.factory import CRMTasksFactory
from bietlejuice.jobs.etl.crm.tasks.inspection import CRMTasksInspection
from bietlejuice.jobs.etl.crm.tasks.lead import CRMTasksLead
from bietlejuice.jobs.etl.crm.tasks.offboarding import CRMTasksOffboarding
from bietlejuice.jobs.etl.crm.tasks.onboarding_tenant import CRMTasksOnboardingTenant
from bietlejuice.jobs.etl.crm.tasks.payment import CRMTasksPayment
from bietlejuice.jobs.etl.crm.tasks.photo_job import CRMTasksPhotoJob
from bietlejuice.jobs.etl.crm.tasks.repair import CRMTasksRepair
from bietlejuice.jobs.etl.crm.tasks.tasks import CRMTasks
from bietlejuice.jobs.etl.crm.tasks.ungrouped_manual import CRMTasksUngroupedManual
from bietlejuice.jobs.etl.crm.tasks.visit import CRMTasksVisit
