SELECT
  h.id AS sk_house,
  h.id_region AS sk_region,
  h.id % 892700000 AS id_short_house,
  h.condo,
  h.land_area,
  h.total_area,
  h.iptu,
  h.bathrooms,
  h.bedrooms,
  h.parking_slots,
  h.suites,
  h.lat,
  h.lng,
  h.number,
  h.address,
  h.city,
  h.complement,
  h.neighborhood,
  h.zipcode,
  h.geo_hash,
  h.registry,
  h.dt_built AS built_period,
  h.condo_type,
  h.conservation_status,
  h.doorman_type,
  h.iptu_type,
  h.key_location,
  h.key_type,
  h.occupant_type,
  h.parking_slot_type,
  h.type,
  h.does_photographer_fill_information,
  h.has_elevator,
  h.has_service_bathroom,
  h.has_service_bedroom,
  h.has_visit_restriction,
  h.is_furnished,
  h.is_iptu_included,
  h.is_verified,
  h.is_warn_owner_of_visits_needed,
  h.ts_first_verified,
  TIMESTAMP(h.dt_creation) AS ts_created,
  h.ts_updated,
  NOW() AS ts_load
FROM
  datalake_ebdb_listing.house AS h
