/*  Although there are created_at and update_at columns,
this query is running as FULL, because, currently,
these columns are mostly empty. */
SELECT 
    id, 
    contract_ebdb_id AS id_contract_ebdb,
    documentation_ebdb_id AS id_documentation_ebdb,
    house_ebdb_id AS id_house_ebdb, 
    tenant_ebdb_id AS id_tenant_ebdb,
    rev, 
    revend AS rev_end, 
    revtype AS rev_type, 
    accepted_terms_and_conditions,
    cancellation_reason,
    score,
    source AS guarantee_source, 
    status AS guarantee_status,
    base_value,
    final_value,
    contract_ebdb_id_mod AS mod_id_contract_ebdb,
    documentation_ebdb_id_mod AS mod_id_documentation_ebdb,
    house_ebdb_id_mod AS mod_id_house_ebdb,
    tenant_ebdb_id_mod AS mod_id_tenant_ebdb,
    accepted_terms_and_conditions_mod AS mod_accepted_terms_and_conditions,
    cancellation_reason_mod AS mod_cancellation_reason,
    score_mod AS mod_score,
    source_mod AS mod_guarantee_source,
    status_mod AS mod_guarantee_status,
    base_value_mod AS mod_base_value, 
    final_value_mod AS mod_final_value, 
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    cancellation_requested_at_mod AS mod_ts_cancellation_requested,
    expires_at_mod AS mod_ts_expired,
    paid_at_mod AS mod_ts_paid,
    payment_expires_at_mod AS mod_ts_payment_expired,
    created_at AS ts_created,
    updated_at AS ts_updated,
    cancellation_requested_at AS ts_cancellation_requested,
    expires_at AS ts_expired,
    paid_at AS ts_paid,
    payment_expires_at AS ts_payment_expired
FROM 
    datalake_rental_guarantee_raw.guarantee_aud
