SELECT
    id,
    street,
    number,
    complement,
    neighborhood,
    city,
    state,
    zip_code,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    street_mod AS mod_street,
    number_mod AS mod_number,
    complement_mod AS mod_complement,
    neighborhood_mod AS mod_neighborhood,
    city_mod AS mod_city,
    state_mod AS mod_state,
    zip_code_mod AS mod_zip_code,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.address_data_aud
