SELECT
    id AS id_buyer,
    sales_flow_id AS id_sales_flow,
    docx_folder_id AS id_docx_folder,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    name,
    email,
    holding_value,
    ccv_role,
    signer_status,
    triage_status,
    sales_flow_id_mod AS mod_id_sales_flow,
    triage_status_mod AS mod_triage_status,
    signer_status_mod AS mod_signer_status,
    ccv_role_mod AS mod_ccv_role,
    docx_folder_id_mod AS mod_id_docx_folder,
    name_mod AS mod_name,
    email_mod AS mod_email,
    holding_value_mod AS mod_holding_value,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.buyer_data_aud
