SELECT
    id,
    house_id AS id_house,
    rev,
    revtype as rev_type,
    revend as rev_end,
    register_number,
    rating,
    status,
    filepath_s3 AS file_path_s3,
    message,
    found_data,
    bypass_confirmation AS is_bypass,
    status_mod AS mod_status,
    register_number_mod AS mod_register_number,
    rating_mod AS mod_rating,
    processing_date_mod AS mod_processing_date,
    message_mod AS mod_message,
    house_id_mod AS mod_id_house,
    found_data_mod AS mod_found_data,
    filepath_s3_mod AS mod_file_path_s3,
    bypass_confirmation_mod AS mod_is_bypass,
    processing_date AS dt_processing,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.bypass_aud

