SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    sales_flow_id AS id_sales_flow,
    sales_flow_id_mod AS mod_id_sales_flow,
    condition,
    condition_mod AS mod_condition,
    reason,
    reason_mod AS mod_reason,
    document_token,
    document_token_mod AS mod_document_token,
    payer_type,
    payer_type_mod AS mod_payer_type,
    payment_value,
    payment_value_mod AS mod_payment_value,
    approval_email,
    approval_email_mod AS mod_approval_email,
    zendesk_link,
    zendesk_link_mod AS mod_zendesk_link,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.ccv_termination_aud
