SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    sales_flow_id AS id_sales_flow,
    sales_flow_id_mod AS mod_id_sales_flow,
    external_proposal_id as id_external_proposal,
    external_proposal_id_mod AS mod_external_proposal_id,
    bank,
    bank_mod AS mod_bank,
    macro_status,
    macro_status_mod AS mod_macro_status,
    micro_status,
    micro_status_mod AS mod_micro_status,
    is_chosen,
    is_chosen_mod AS mod_is_chosen,
    last_macro_status_updated_at AS ts_last_macro_status_updated,
    last_macro_status_updated_at_mod AS mod_ts_last_macro_status_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.credit_proposal_aud
