SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    name,
    name_mod AS mod_name,
    mobile_phone,
    mobile_phone_mod AS mod_mobile_phone,
    phone,
    phone_mod AS mod_phone,
    email,
    email_mod AS mod_email,
    address,
    address_mod AS mod_address,
    city,
    city_mod AS mod_city,
    state,
    state_mod AS mod_state,
    hubs_id,
    hubs_id_mod AS mod_hubs_id,
    label,
    label_mod AS mod_label,
    type,
    type_mod AS mod_type,
    latitude,
    latitude_mod AS mod_latitude,
    longitude,
    longitude_mod AS mod_longitude,
    created_at AS ts_created,
    created_at_mod AS mod_ts_created,
    updated_at AS ts_updated,
    updated_at_mod AS mod_ts_updated,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.notary_office_aud
