SELECT
    id AS id_notary,
    sales_flow_id AS id_sales_flow,
    specialist_id AS id_specialist,
    notary_office_id AS id_notary_office,
    label,
    status,
    protocol,
    password,
    available_costs,
    paid_costs,
    seller_payment_status,
    customer_follow_up,
    deed_emission_finished_by,
    deed_signature_finished_by,
    crn_finished_by,
    key_delivery_finished_by,
    cri_finished_by,
    started_at AS ts_started,
    ended_at AS ts_ended,
    end_prevision_at AS ts_prevision_ended,
    buyer_received_keys_at AS ts_buyer_received_keys,
    kit_sent_at AS ts_kit_sent,
    created_at AS ts_created,
    updated_at AS ts_updated,
    deed_emission_finished_at AS ts_deed_emission_finished,
    deed_signature_finished_at AS ts_deed_signature_finished,
    crn_finished_at AS ts_crn_finished,
    key_delivery_finished_at AS ts_key_delivery_finished,
    cri_finished_at AS ts_cri_finished,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.notary
