SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    payment_id AS id_payment,
    payment_id_mod AS mod_id_payment,
    has_down_payment_extension,
    has_down_payment_extension_mod AS mod_has_down_payment_extension,
    down_payment_term,
    down_payment_term_mod AS mod_down_payment_term,
    has_cash_value_installment,
    has_cash_value_installment_mod AS mod_has_cash_value_installment,
    cash_first_installment_value,
    cash_first_installment_value_mod AS mod_cash_first_installment_value,
    cash_first_installment_term,
    cash_first_installment_term_mod AS mod_cash_first_installment_term,
    cash_first_installment_day_count_type,
    cash_first_installment_day_count_type_mod AS mod_cash_first_installment_day_count_type,
    cash_second_installment_value,
    cash_second_installment_value_mod AS mod_cash_second_installment_value,
    cash_second_installment_condition,
    cash_second_installment_condition_mod AS mod_cash_second_installment_condition,
    cash_second_installment_term,
    cash_second_installment_term_mod AS mod_cash_second_installment_term,
    cash_second_installment_day_count_type,
    cash_second_installment_day_count_type_mod AS mod_cash_second_installment_day_count_type,
    has_cash_value_payment_extension,
    has_cash_value_payment_extension_mod AS mod_has_cash_value_payment_extension,
    cash_value_payment_extension_markdown,
    cash_value_payment_extension_markdown_mod AS mod_cash_value_payment_extension_markdown,
    cash_value_payment_extension_term,
    cash_value_payment_extension_term_mod AS mod_cash_value_payment_extension_term,
    has_entry_amount_installment,
    has_entry_amount_installment_mod AS mod_has_entry_amount_installment,
    entry_amount_first_installment_value,
    entry_amount_first_installment_value_mod AS mod_entry_amount_first_installment_value,
    entry_amount_first_installment_term,
    entry_amount_first_installment_term_mod AS mod_entry_amount_first_installment_term,
    entry_amount_first_installment_day_count_type,
    entry_amount_first_installment_day_count_type_mod AS mod_entry_amount_first_installment_day_count_type,
    entry_amount_second_installment_value,
    entry_amount_second_installment_value_mod AS mod_entry_amount_second_installment_value,
    entry_amount_second_installment_condition,
    entry_amount_second_installment_condition_mod AS mod_entry_amount_second_installment_condition,
    entry_amount_second_installment_term,
    entry_amount_second_installment_term_mod AS mod_entry_amount_second_installment_term,
    entry_amount_second_installment_day_count_type,
    entry_amount_second_installment_day_count_type_mod AS mod_entry_amount_second_installment_day_count_type,
    has_entry_amount_payment_extension,
    has_entry_amount_payment_extension_mod AS mod_has_entry_amount_payment_extension,
    entry_amount_payment_extension_markdown,
    entry_amount_payment_extension_markdown_mod AS mod_entry_amount_payment_extension_markdown,
    entry_amount_payment_extension_term,
    entry_amount_payment_extension_term_mod AS mod_entry_amount_payment_extension_term,
    entry_amount_payment_extension_day_count_type,
    entry_amount_payment_extension_day_count_type_mod AS mod_entry_amount_payment_extension_day_count_type,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.payment_rules_aud
