SELECT
    id AS id_seller,
    sales_flow_id AS id_sales_flow,
    docx_folder_id AS id_docx_folder,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    name,
    email,
    share_percentage,
    holding_value,
    party_kind,
    on_register AS is_on_register,
    active AS is_active,
    is_ccv_signer,
    is_pj,
    sales_flow_id_mod AS mod_id_sales_flow,
    is_ccv_signer_mod AS mod_is_ccv_signer,
    party_kind_mod AS mod_party_kind,
    on_register_mod AS mod_is_on_register,
    docx_folder_id_mod AS mod_id_docx_folder,
    share_percentage_mod AS mod_share_percentage,
    name_mod AS mod_name,
    email_mod AS mod_email,
    is_pj_mod AS mod_is_pj,
    active_mod AS mod_active,
    holding_value_mod AS mod_holding_value,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.seller_data_aud

