SELECT
    id,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    subtask_id AS id_subtask,
    subtask_id_mod AS mod_id_subtask,
    main_user_id AS id_main_user,
    main_user_id_mod AS mod_id_main_user,
    sales_flow_id AS id_sales_flow,
    sales_flow_id_mod AS mod_id_sales_flow,
    status,
    status_mod AS mod_status,
    released_at AS ts_released,
    released_at_mod AS mod_ts_released,
    concluded_at AS ts_concluded,
    concluded_at_mod AS mod_ts_concluded,
    attributes,
    attributes_mod AS mod_attributes,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_sales_flow_raw.task_association_aud
