/*  Although there are created_at and update_at columns,
this query is running as FULL, because, currently,
these columns are mostly empty. */
SELECT
    id,
    guarantee_id AS id_guarantee,
    checkout_order_id AS id_checkout_order,
    subscription_id AS id_subscription,
    invoice_id AS id_invoice,
    external_id AS id_external,
    renewal_id AS id_renewal,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    cancellation_reason,
    card_token,
    emv,
    installments,
    pix_link,
    qr_code,
    status AS charge_status,
    type AS charge_type,
    refund_amount,
    checkout_order_hash,
    external_source,
    value,
    fee,
    external_info,
    invoice_charge_code,
    guarantee_id_mod AS mod_id_guarantee,
    cancellation_reason_mod AS mod_cancellation_reason,
    card_token_mod AS mod_card_token,
    emv_mod AS mod_emv,
    installments_mod AS mod_installments,
    pix_link_mod AS mod_pix_link,
    qr_code_mod AS mod_qr_code,
    status_mod AS mod_charge_status,
    type_mod AS mod_charge_type,
    refund_amount_mod AS mod_refund_amount,
    checkout_order_hash_mod AS mod_checkout_order_hash,
    checkout_order_id_mod AS mod_id_checkout_order,
    value_mod AS mod_value,
    fee_mod AS mod_fee,
    external_source_mod AS mod_external_source,
    external_info_mod AS mod_external_info,
    invoice_charge_code_mod AS mod_invoice_charge_code,
    external_info_mod AS mod_external_info,
    invoice_charge_code_mod AS mod_invoice_charge_code,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_rental_guarantee_raw.charge_aud
