SELECT
    id,
    contract_ebdb_id AS id_contract_ebdb,
    documentation_ebdb_id AS id_documentation_ebdb,
    house_ebdb_id AS id_house_ebdb,
    tenant_ebdb_id AS id_tenant_ebdb,
    accepted_terms_and_conditions,
    cancellation_reason,
    score,
    source AS guarantee_source,
    status AS guarantee_status,
    CAST(base_value/100.00 AS DECIMAL(12,2)) AS base_value,
    CAST(final_value/100.00 AS DECIMAL(12,2)) AS final_value,
    type AS guarantee_type,
    payment_recurrence,
    created_at AS ts_created,
    updated_at AS ts_updated,
    billed_at AS ts_billed,
    cancellation_requested_at AS ts_cancellation_requested,
    expires_at AS ts_expired,
    paid_at AS ts_paid,
    payment_expires_at AS ts_payment_expired,
    begins_at AS ts_started,
    year,
    month,
    day
FROM
    datalake_rental_guarantee_raw.guarantee
