SELECT
    id AS id_airtable_record,
    CAST(inscricao AS BIGINT) AS id_inscription,
    CAST(ticket_da_indicacao_novo_forms_sale AS BIGINT) AS id_broker_referral_ticket,
    CAST(id_admin AS BIGINT) AS id_admin,
    CAST(cpf AS BIGINT) AS cpf,
    nome_completo AS full_name,
    preferencia_de_atuacao AS performance_preference,
    2_opcao AS second_option,
    etapa_processo AS stage_process,
    depara_regiao AS region_from_to,
    estado_de_atuacao AS state_operation,
    situacao_cadastro AS registration_status,
    status_parceiro AS partner_status,
    aprovado_inscricao AS registration_approved,
    aprovado_batepapo AS chat_approved,
    motivo_reprovacao AS disapproval_reason,
    classificacao_entrevista AS interview_classification,
    tipo_do_cadastro AS registration_type,
    funcao AS function,
    mgm_flag, 
    regiao_de_atuacao AS region_operation,
    executivo_de_negociacao AS negotiation_executive_name,
    executivo_associado AS associate_executive_name,
    etapa_processo_ativacao AS stage_process_activation,
    batepapo_finalizado AS chat_ended,
    CAST(score_formulario_de_inscricao AS INTEGER) AS score_inscription_form,
    CAST(score_entrevista AS INTEGER) AS score_interview,
    CAST(score_ocupacao AS INTEGER) AS score_occupation,
    CAST(score_autonomo AS INTEGER) AS score_autonomous,
    CAST(score_experiencia AS INTEGER) AS score_experience,
    CAST(score_captacao AS INTEGER) AS score_capture,
    CAST(score_disponibilidade_semana AS INTEGER) AS score_availability_week,
    CAST(score_disponibilidade_final_de_semana AS INTEGER) AS score_availability_end_of_week,
    CAST(score_pre_visita AS INTEGER) AS score_before_visit,
    CAST(score_visita AS INTEGER) AS score_visit,
    CAST(score_pos_visita AS INTEGER) AS score_after_visit,
    CAST(score_locomocao AS INTEGER) AS score_locomotion,
    CAST(puxar_para_agendar_entrevista_time AS BOOLEAN) AS has_schedule_interview,
    CAST(enviado_para_entrevista_eaen AS BOOLEAN) AS is_sent_interview_with_ea_en,
    DATE(atualizacao_creci) AS dt_creci_update,
    DATE(data_de_finalizacao_entrevista) AS dt_interview_ended,
    DATE(data_de_envio_de_contrato) AS dt_contract_sent,
    DATE(data_de_assinatura_de_contrato) AS dt_contract_signed,
    DATE(data_de_cadastro_admin) AS dt_admin_registered,
    DATE(data_de_vinculo_teams) AS dt_teams_link_created,
    DATE(data_envio_de_onboarding) AS dt_onboarding_sent,
    DATE(data_de_ativacao_novo_fluxo) AS dt_activated,
    DATE(data_finalizacao_de_onboarding) AS dt_onboarding_completed,
    DATE(abertura_de_agenda) AS dt_agenda_opened,
    DATE(data_de_nascimento) AS dt_birth,
    DATE(data_de_inscricao) AS dt_registration,
    TIMESTAMP(puxar_para_entrevista) AS ts_interview_scheduled,
    TIMESTAMP(createdTime) AS ts_airtable_record_created,
    MAKE_DATE(year, month, day) AS dt_load,
    year,
    month,
    day
FROM
    datalake_airtable_test_raw.brokers_accreditation
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}