SELECT
    id_airtable_record,
    CAST(bd_indicante_id_admin AS BIGINT) AS id_admin_recommender,
    CAST(id_indicacao AS BIGINT) AS id_indication,
    CAST(ticket_inscricao AS BIGINT) AS id_registration_ticket,
    CAST(REPLACE(REPLACE(bd_indicado_pos_indicacao_id_admin, "]"), "[") AS BIGINT) AS id_admin_indicated_after_indication,
    nome_de_quem_esta_realizando_a_indicacao AS recommender_name,
    email_de_quem_esta_indicando AS recommender_email,
    cpf_indicante_formato AS recommender_cpf,
    voce_e_um_corretor_parceiro_quintoandar AS recommender_quintoandar_partner_broker,
    nome_completo_do_indicado AS indicated_broker_name,
    email_do_corretor_indicado AS indicated_broker_email,
    cpf_indicado_formato_ AS indicated_broker_cpf,
    telefone_do_corretor_indicado AS indicated_broker_phone_number,
    praca_de_interesse_do_indicado AS indicated_broker_square_interest,
    CAST(sla_inscricao_indicado AS INTEGER) AS indicated_sla_inscription,
    regiao_escolhida AS chosen_region,
    hub_escolhido AS chosen_hub,
    status_fup,
    cr_tem_inscricao_na_lp_com_ticket AS cr_has_registration_in_lp_with_ticket,
    motivo_de_invalidade AS reason_for_invalidity,
    verificacao_geral_da_indicacao_dash AS indication_general_check,
    consolidado_check_indicacao_duplicada AS duplicate_indication_check,
    consolidado_check_descredenciamento_forcado AS forced_deaccreditation_check,
    consolidado_check_tempo_de_descredenciamento AS deaccreditation_time_check,
    consolidado_check_ativo AS active_check,
    consolidado_check_tempo_de_inscricao_e_lead_trabalhado AS registration_time_and_lead_worked_check,
    verificacao_geral_da_indicacao_completo_all_checks AS indication_general_all_checks,
    REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_motivo_de_reprovacao, "]"), "["), "'") AS indicated_after_indication_reason_for_disapproval,
    REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_etapa_processo, "]"), "["), "'") AS indicated_after_indication_process_stage,
    SPLIT(REPLACE(REPLACE(REPLACE(bd_indicado_inscricao_verificacao_atual, "]"), "["), "'"), ",") AS indicated_registration_current_verification, 
    SPLIT(REPLACE(REPLACE(REPLACE(bd_indicante_regiao_de_atuacao, "]"), "["), "'"), ",") AS indicated_region_of_operation, 
    REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_1opcao, "]"), "["), "'") AS indicated_after_indication_first_option,
    REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_2opcao, "]"), "["), "'") AS indicated_after_indication_second_option,
    REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_regiao_validada, "]"), "["), "'") AS indicated_after_indication_validated_region,
    DATE(REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_atualizacao_creci, "]"), "["), "'")) AS dt_indicated_after_indication_creci_updated,
    DATE(REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_data_de_envio_de_contrato, "]"), "["), "'")) AS dt_indicated_after_indication_contract_sent,
    DATE(REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_data_de_assinatura_de_contrato, "]"), "["), "'")) AS dt_indicated_after_indication_contract_signed,
    DATE(REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_data_de_envio_de_onboarding, "]"), "["), "'")) AS dt_indicated_after_indication_onboarding_sent,
    DATE(REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_data_de_finalizacao_de_onboarding, "]"), "["), "'")) AS dt_indicated_after_indication_onboarding_ended,
    DATE(REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_abertura_de_agenda, "]"), "["), "'")) AS dt_indicated_after_indication_agenda_opened,
    DATE(REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_atualizacao_entrevista, "]"), "["), "'")) AS dt_indicated_after_indication_interview_updated,
    TIMESTAMP(REPLACE(REPLACE(REPLACE(bd_indicado_pos_indicacao_puxar_entrevista, "]"), "["), "'")) AS ts_indicated_after_indication_interview_scheduled,
    TIMESTAMP(data_da_indicacao) AS ts_recommendation,
    MAKE_DATE(year, month, day) AS dt_load,
    year,
    month,
    day
FROM
    datalake_airtable_test_raw.brokers_indication
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}


