SELECT
    id AS id_airtable_record,
    CAST(inscricao AS BIGINT) AS id_lead,
    CAST(id_admin AS BIGINT) AS id_admin,
    CAST(credenciamentos AS INT) AS accreditations,
    ativacao AS activation,
    modalidade_de_atuacao AS actuation_model,
    preferencia_de_atuacao AS actuation_preference,
    estado_de_atuacao AS actuation_state,
    cpf_ajustado AS adjusted_cpf,
    CAST(creci AS BIGINT) AS agent_creci,
    status_aprovacao AS approved_status,
    checado_por AS checked_by,
    regiao_escolhida AS chosen_region,
    situacao_creci AS creci_situation,
    status_creci AS creci_status,
    nota AS grade,
    como_conheceu_o_5a AS how_met_5a,
    email AS lead_email,
    nome_completo AS lead_name,
    telefone AS lead_phone_number,
    descred_permanente AS permanent_deaccreditation,
    qual_imobiliaria AS real_estate,
    1_opcao AS region_first_option,
    2_opcao AS region_second_option,
    1_opcao_completa AS region_first_option_complete,
    2_opcao_completa AS region_second_option_complete,
    status_rental AS rental_status,
    ativos_rental AS rental_activated,
    desistencia_treinamento AS training_giving_up,
    duplicado AS is_duplicated,
    TO_DATE(data_da_resposta, 'yyyy-MM-dd') AS dt_answer,
    TO_DATE(auto_data_creci, 'yyyy-MM-dd') AS dt_auto_data_creci,
    TO_DATE(data_de_nascimento, 'yyyy-MM-dd') AS dt_birth,
    TO_DATE(envio_contrato, 'yyyy-MM-dd') AS dt_contract_sent,
    TO_DATE(fup_ligacao, 'yyyy-MM-dd') AS dt_fup_call,
    TO_DATE(fup_email, 'yyyy-MM-dd') AS dt_fup_email_sent,
    TO_DATE(fup_sms, 'yyyy-MM-dd') AS dt_fup_sms_sent,
    TO_DATE(fup_whatsapp,'yyyy-MM-dd') AS dt_fup_whatsapp_sent,
    TO_DATE(criacao_de_id, 'yyyy-MM-dd') AS dt_id_created,
    TO_DATE(envio_reforco, 'yyyy-MM-dd') AS dt_reforce_sent,
    TO_DATE(assinatura, 'yyyy-MM-dd') AS dt_signed,
    TO_DATE(data_de_inscricao, 'yyyy-MM-dd') AS dt_subscripted,
    TO_DATE(data_desistencia_treinamento, 'yyyy-MM-dd') AS dt_training_giving_up,
    TO_DATE(envio_treinamento, 'yyyy-MM-dd') AS dt_training_sent,
    TO_TIMESTAMP(ultima_atualizacao) AS ts_updated,
    year,
    month,
    day
FROM
    datalake_airtable_test_raw.leads
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}