SELECT
  id_idactum AS id_idactum,
  id_unidade AS id_unit,
  NULLIF(TRIM(id_unidade_original), '')  AS id_original_unit,
  NULLIF(TRIM(chave_lote), '') AS id_lot,
  NULLIF(TRIM(bpatri_key), '') AS id_patrimonial_assets,
  NULLIF(TRIM(id_condominio), '') AS id_condominium,
  preco_declarado AS reported_price,
  valor_venal AS assessed_value,
  valor_venal_de_referencia AS assessed_value_reference,
  proporcao_transmitida AS transfered_percentage,
  base_de_calculo_adotada AS calculus_base_used,
  valor_financiado AS funding_price,
  NULLIF(TRIM(cartorio), '') AS real_estate_register,
  NULLIF(TRIM(matricula), '') AS real_estate_registry,
  NULLIF(TRIM(situacao), '') AS building_type,
  NULLIF(TRIM(UPPER(padrao)), '') AS usage_category,
  NULLIF(TRIM(descricao), '') AS property_description,
  acc AS building_year,
  area_terreno AS lot_area,
  area_construida AS building_area,
  area_privativa AS private_area,
  NULLIF(TRIM(area), '') AS area,
  NULLIF(TRIM(uf), '') AS state,
  NULLIF(TRIM(cidade), '') AS city,
  NULLIF(TRIM(bairro), '') AS neighborhood,
  NULLIF(TRIM(logradouro), '') AS street,
  NULLIF(NULLIF(TRIM(numero), ''), 'None') AS number,
  NULLIF(TRIM(complemento), '') AS address_details,
  NULLIF(TRIM(unidade), '') AS unit,
  NULLIF(TRIM(bloco), '') AS building,
  bloco_id AS building_number,
  cep AS zipcode,
  NULLIF(TRIM(`Logradouro Correios`), '') AS postal_street_name,
  sgl_zona AS zone_code,
  CASE
    WHEN TRIM(setor_quadra) IN ('', '00None', '000nan', 'None') THEN null
    ELSE TRIM(setor_quadra)
  END AS block_number,
  NULLIF(TRIM(`zona_censitária`), '') AS census_tract,
  NULLIF(TRIM(natureza_transacao), '') AS transaction_type,
  NULLIF(TRIM(tipo_de_financiamento), '') AS funding_method,
  NULLIF(TRIM(finalidade), '') AS property_usage_purpose,
  limbo AS is_in_limbo,
  vertical AS is_vertical_property,
  tipologia AS typology,
  CAST(data_transacao AS TIMESTAMP) AS ts_transaction_date,
  CAST(data_declaracao_transacao AS TIMESTAMP) AS ts_transaction_declaration_date,
  dt_load
FROM datalake_idactum_transactions_raw.idactum_transactions
