SELECT
    run_id AS uuid_run,
    environment,
    mode,
    execution_backend,
    model,
    forward_tasks,
    backfill_tasks,
    s3_key,
    metrics.planned_calls AS planned_calls,
    metrics.completed_calls AS completed_calls,
    metrics.failed_calls AS failed_calls,
    metrics.calls_per_second AS calls_per_second,
    metrics.duration_seconds AS duration_seconds,
    metrics.classification_duration_seconds AS classification_duration_seconds,
    metrics.prompt_tokens AS prompt_tokens,
    metrics.completion_tokens AS completion_tokens,
    metrics.cached_tokens AS cached_tokens,
    metrics.cache_hit_rate AS cache_hit_rate,
    metrics.response_cost_usd AS cost_usd,
    metrics.partitions_complete AS partitions_complete,
    metrics.partitions_incomplete AS partitions_incomplete,
    metrics.backfill_deferred_partitions AS backfill_deferred_partitions,
    backfill_breaker.n_prompts AS breaker_n_prompts,
    backfill_breaker.n_partitions AS breaker_n_partitions,
    backfill_breaker.estimated_calls AS breaker_estimated_calls,
    backfill_escalation_attribution.forward_tasks AS escalation_forward_tasks,
    backfill_escalation_attribution.backfill_tasks AS escalation_backfill_tasks,
    backfill_escalation_attribution.forward_plan_and_fetch_seconds AS escalation_forward_plan_and_fetch_seconds,
    backfill_escalation_attribution.backfill_plan_and_fetch_seconds AS escalation_backfill_plan_and_fetch_seconds,
    backfill_escalation_attribution.forward_classification_seconds_estimated AS escalation_forward_classification_seconds_estimated,
    backfill_escalation_attribution.backfill_classification_seconds_estimated AS escalation_backfill_classification_seconds_estimated,
    backfill_escalation_attribution.forward_cost_usd_estimated AS escalation_forward_cost_usd_estimated,
    backfill_escalation_attribution.backfill_cost_usd_estimated AS escalation_backfill_cost_usd_estimated,
    backfill_breaker.tripped AS is_breaker_tripped,
    backfill_breaker.approved AS is_breaker_approved,
    backfill_breaker.refused AS is_breaker_refused,
    backfill_escalation_attribution.escalated_to_backfill AS is_escalated_to_backfill,
    backfill_escalation_attribution.backfill_share_estimated AS is_escalation_backfill_share_estimated,
    CAST(`window`.`start` AS TIMESTAMP) AS ts_window_start,
    CAST(`window`.`end` AS TIMESTAMP) AS ts_window_end,
    ts_load,
    failed_sources,
    prompts_backfilling,
    metrics,
    throughput_calibration,
    backfill_breaker,
    backfill_escalation_attribution,
    year,
    month,
    day
FROM
    datalake_vocs_machina_meta_raw.run_summaries
