SELECT
    id as id_deal, 
    pipeline_id as id_pipeline, 
    stage_id as id_stage,
    next_activity_id as id_next_activity,
    last_activity_id as id_last_activity,
    group_id as id_group,    
    title,    
    formatted_value as value_formatted,
    formatted_weighted_value as value_formatted_weighted,
    weighted_value_currency as value_currency_weighted,
    currency,
    label,
    status,
    probability,
    lost_reason,
    visible_to,
    renewal_type,
    plano as plan,
    person_id as person,
    person_name,
    creator_user_id as creator_user,
    user_id as user,
    org_id as organization,
    org_name as organization_name,
    group_name,
    owner_name,
    consultor_que_fez_a_ligacao as consultant_made_call,
    cc_email as email,
    xml_imoveis as realty_xml,
    numero_imoveis_extenso as total_properties_text,
    next_activity_subject,
    next_activity_type,
    next_activity_duration,
    next_activity_note,
    canal_de_origem as source_channel,
    status_termo as term_status,
    sistema_de_integracao as integration_system,
    status_de_publicacao as publication_status,
    dia_de_cobranca as billing_day,
    bonificacao as bonus,
    supervisor,
    campanha as campaign,
    value,
    weighted_value as value_weighted,
    products_count as total_products,
    files_count as total_files,
    notes_count as total_notes,
    followers_count as total_followers,
    email_messages_count as total_email_messages,
    activities_count as total_activities,
    done_activities_count as total_done_activities,
    undone_activities_count as total_undone_activities,
    participants_count as total_participants,
    numero_imoveis as total_properties,
    stage_order_nr as stage_order_number,
    valor_do_lead as lead_value,
    active as is_active,
    deleted as is_deleted,
    org_hidden as is_organization_hidden, 
    person_hidden as is_person_hidden,
    data_da_ligacao as dt_call,
    inicio_da_cobranca as dt_start_billing,
    envio_de_email_de_boas_vindas as dt_welcome_email,
    data_assinatura_termo as dt_signature_term,
    next_activity_date as dt_next_activity,
    last_activity_date as dt_last_activity, 
    expected_close_date as dt_expected_close, 
    update_time as ts_updated,
    close_time as ts_closed,
    add_time as ts_added,
    stage_change_time as ts_stage_changed,
    next_activity_time as ts_next_activity,
    won_time as ts_won,
    first_won_time as ts_first_won,
    lost_time as ts_lost,
    last_incoming_mail_time as ts_last_incoming_mail,
    last_outgoing_mail_time as ts_last_outgoing_mail,
    rotten_time as ts_rotten,
    year,
    month,
    day
FROM 
    datalake_portal_casa_mineira_pipedrive_raw.deals
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}