select
	"id",
	criadoEm as ts_created,
	dataVistoria as dt_inspected,
	imovel_id as id_house,
	vistoriador_id as id_user_inspector,
	status,
	comentario as "comment",
	contrato_id as id_contract,
	"hash",
	aprovadoInquilino+0 as is_tenant_approved,
	aprovadoProprietario+0 as is_owner_approved,
	browserAprovacaoInquilino as browser_tenant_approval,
	browserAprovacaoProprietario as browser_owner_approval,
	comentarioInquilino as tenant_comment,
	comentarioProprietario as owner_comment,
	dataAprovacaoInquilino as ts_tenant_approved,
	dataAprovacaoProprietario as ts_owner_approved,
	ipAprovacaoInquilino as ip_tenant_approval,
	ipAprovacaoProprietario as ip_owner_approval,
	soAprovacaoInquilino as os_tenant_approval,
	soAprovacaoProprietario as os_owner_approval,
	atualizadoEm as ts_updated,
	expiraEm as ts_expired,
	ref_id as id_ref,
	tipo as "type",
	shortRevisarInq as short_review_tenant,
	shortRevisarProp as short_review_owner,
	finalReportPdfId as id_final_report_pdf,
	finalReportSentAt as dt_final_report_sent,
	itenCommented+0 as is_item_commented,
	finalReportCreated+0 as is_final_report_created,
	lastReportSent as last_report_sent,
	reportFinished+0 as is_report_finished,
	keyLocation as key_location,
	keyLocationDetails as key_location_details,
	inspectorGotAllInfo+0 as has_inspector_got_all_info,
	partialTenantReportSentAt as ts_partial_tenant_report_sent,
	partialOwnerReportSentAt as ts_partial_owner_report_sent,
	"version",
	schedule_id as id_booking,
	scheduleObservations as schedule_observations,
	reportRevised as report_revised,
	scheduleDoubleChecked+0 as is_schedule_double_checked
from Vistoria
;