select
    id,
    house_id as id_house,
    flow_id as id_flow,
    houseAddress_estado_id as id_house_address_estado,
    region_id as id_region,
    tenant_id as is_tenant,
    ownerType as owner_type,
    criadoEm as ts_created,
    atualizadoEm as ts_updated,
    contractStartDate as ts_contract_started,
    contractFinalDate as ts_contract_ended,
    currentCondoFee as current_condo_fee,
    currentIptuTwelth as current_iptu_twelth,
    currentRent as current_rent,
    houseAddress_bairro as house_address_neighboor,
    houseAddress_cep as house_address_cep,
    houseAddress_cidade as house_address_city,
    houseAddress_complemento as house_address_complement,
    houseAddress_logradouro as house_address_street,
    houseAddress_numero as house_address_number,
    houseType as house_type,
    lat,
    lng,
    ownerData_email as owner_data_email,
    ownerData_gender as owner_data_gender,
    ownerData_name as owner_data_name,
    ownerData_phoneNumber as owner_data_phone_number,
    status,
    tenantData_email as tenant_data_email,
    tenantData_gender as tenant_data_gender,
    tenantData_name as tenant_data_name,
    tenantData_phoneNumber as tenant_data_phone_number,
    contractObservations as contract_observations
  from
    Portability
where date(coalesce(criadoEm, '1900-01-01 00:00:00')) <= DATE('{}')