DROP TABLE IF EXISTS datalake_clean.contract;
CREATE TABLE IF NOT EXISTS datalake_clean.contract (
 id INT,
 emailFatura STRING,
 emailProprietario STRING,
 valorAluguel DOUBLE PRECISION,
 numImovel INT,
 diaMesCobranca INT,
 garantia STRING,
 tipo STRING,
 status STRING,
 dataCalculoComissaoAfiliado TIMESTAMP,
 dataCalculoComissaoCorretor TIMESTAMP,
 dataInicio DATE,
 dataAssinado TIMESTAMP,
 dataMinutaAprovada TIMESTAMP,
 dataEntrada DATE,
 dataFimContratoPrevisto DATE,
 dataRescisao DATE,
 nomeBanco STRING,
 paganteCondominio STRING,
 paganteIptu STRING,
 responsavelCondominio STRING,
 responsavelIptu STRING,
 seguroFianca_parcelas INT,
 seguroFianca_valor DOUBLE PRECISION,
 seguroResidencial_parcelas INT,
 seguroResidencial_valor DOUBLE PRECISION,
 taxaComissaoPrimeiroAluguel DOUBLE,
 valorCondominio DOUBLE PRECISION,
 valorIptu DOUBLE PRECISION,
 tipoAssinatura STRING,
 dataContratoEletronicoEnviado TIMESTAMP,
 statusClosing STRING,
 contratoAssinado STRING,
 googleDriveId STRING,
 tokenESignatureLocacao STRING,
 tokenESignatureAdm STRING,
 contratoAdministracaoAssinado STRING,
 contratoAutorizacaoEntradaAssinado STRING,
 contratoLocacaoAssinado STRING,
 dataTrocaTitularidade STRING,
 proposta_id INT,
 imovel_id INT,
 criadoEm TIMESTAMP,
 atualizadoEm TIMESTAMP
  ) ROW FORMAT DELIMITED
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n'
LOCATION 's3://5a-datalake/clean/contract'
;