DROP TABLE IF EXISTS datalake_clean.contacts_and_prospects;
CREATE EXTERNAL TABLE IF NOT EXISTS datalake_clean.contacts_and_prospects (
 cap_id BIGINT,
 lead_id BIGINT,
 imovel_id BIGINT,
 anuncio_criado_em DATE,
 area_total INT,
 bairro STRING,
 cep STRING,
 cidade STRING,
 complemento STRING,
 endereco STRING,
 numero STRING,
 numero_banheiros INT,
 numero_quartos INT,
 numero_suites INT,
 url_anuncio STRING,
 valor INT,
 telefone_anunciante STRING,
 tipo STRING,
 email STRING,
 lat DECIMAL(10,7),
 lng DECIMAL(10,7),
 condominio INT,
 iptu INT,
 reason STRING,
 status STRING,
 envio_email_apresentacao_pos TIMESTAMP,
 envio_email_apresentacao_pre TIMESTAMP,
 processado SMALLINT,
 origem STRING,
 external_id STRING,
 mencionar INT,
 automatically_discarded INT,
 estado_nome STRING,
 estado_abrev STRING,
 dados_afiliado_tipo_afiliado STRING,
 dados_afiliado_inicio_atuacao TIMESTAMP,
 dados_afiliado_cidade_atuacao STRING,
 region_id INT,
 atualizado_em TIMESTAMP,
 url_source STRING,
 utm_medium STRING,
 utm_campaign STRING,
 utm_source STRING,
 usuario_que_indicou_id INT,
 usuario_que_cadastrou_id INT,
 self_service INT,
 attribution_type STRING
  ) ROW FORMAT DELIMITED
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY '\n'
LOCATION 's3://5a-datalake/clean/contacts_and_prospects'
;