SELECT
    template_defn_id AS id_template_definition,
    business_group_id AS id_business_group,
    doc_type_id AS id_document_type,
    process_flow_id AS id_process_flow,
    ess_request_id AS id_ess_request,
    status_code,
    template_type_code,
    created_by,
    last_updated_by AS updated_by,
    CAST(object_version_number AS INT) AS object_version_number,
    CAST(total_min_participants AS INT) AS min_total_participants,
    CAST(total_max_participants AS INT) AS max_total_participants,
    use_calc_ratings_flag = 'Y' AS is_calculated_ratings_used,
    calculate_ratings_flag = 'Y' AS is_ratings_calculation_enabled,
    select_mgr_allowed_flag = 'Y' AS is_manager_selection_allowed,
    wrk_see_mgr_pcpn_flag = 'Y' AS is_worker_allowed_to_see_manager_participants,
    show_pcpn_calc_rating_flag = 'Y' AS is_participant_allowed_to_see_calculated_rating,
    show_mm_calc_rating_flag = 'Y' AS is_matrix_manager_allowed_to_see_calculated_rating,
    CAST(date_from AS DATE) AS dt_started,
    CAST(date_to AS DATE) AS dt_ended,
    CAST(creation_date AS TIMESTAMP) AS ts_created,
    CAST(last_update_date AS TIMESTAMP) AS ts_updated,
    NOW() AS ts_load,
    year,
    month,
    day
FROM
    datalake_pin_performance_raw.hra_tmpl_defns_b
