SELECT
    section_id AS id_section,
    section_rating_model_id AS id_section_rating_model,
    content_type_id AS id_content_type,
    perf_rating_model_id AS id_performance_rating_model,
    reference_section_id AS id_reference_section,
    section_def_id AS id_section_definition,
    section_type_code AS section_type,
    description,
    calculation_rule_code AS calculation_rule,
    rating_type_code AS rating_type,
    item_calculation_code AS item_calculation,
    mapping_method_code AS mapping_method,
    calc_mapping_code AS calculation_mapping_code,
    rounding_rule_code AS rounding_rule,
    created_by,
    last_updated_by AS updated_by,
    rate_section_flag = 'Y' AS is_section_rated,
    weight_section_flag = 'Y' AS is_section_weighted,
    enable_items_flag = 'Y' AS is_items_enabled,
    content_profile_flag = 'Y' AS is_content_profile,
    show_target_perf_rtg = 'Y' AS is_target_performance_rating_shown,
    show_target_prof_level = 'Y' AS is_target_proficiency_level_shown,
    show_mandatory = 'Y' AS is_mandatory_shown,
    show_measurement = 'Y' AS is_measurement_shown,
    show_reminder_date = 'Y' AS is_reminder_date_shown,
    show_status = 'Y' AS is_status_shown,
    enable_mgr_reason_flag = 'Y' AS is_manager_reason_required,
    CAST(object_version_number AS INT) AS object_version_number,
    CAST(creation_date AS TIMESTAMP) AS ts_created,
    CAST(last_update_date AS TIMESTAMP) AS ts_updated,
    NOW() AS ts_load,
    year,
    month,
    day
FROM
    datalake_pin_performance_raw.hra_tmpl_sections
