SELECT
	CAST(id AS BIGINT) AS id,
	CAST(COALESCE(userid, user_id) AS BIGINT) AS id_user,
	CAST(eventId AS BIGINT) AS id_event,
	COALESCE(referenceId, entity_id) AS id_entity,
	CAST(campaign_id AS BIGINT) AS id_campaign,
	COALESCE(referenceName, entity_name) AS entity_name,
	action,
	status,
	state,
	channel,
	profile,
	tags,
	destination,
	sender,
	payload,
	COALESCE(templateName, GET_JSON_OBJECT(payload, '$.bodyTemplate')) AS template,
	lower(metaCategory) as template_meta_category,
	GET_JSON_OBJECT(payload, '$.country') AS country_code,
	GET_JSON_OBJECT(payload, '$.metadata') AS metadata,
	ccost AS cost_center,
	scope,
	notificationCenterAcknowledge AS notification_center_acknowledge,
	errorInfo AS error_info,
	errorCode AS error_code,
	CAST(COALESCE(sentAt, sent_at) AS TIMESTAMP) AS ts_sent,
	CAST(COALESCE(createdAt, created_at) AS TIMESTAMP) AS ts_created,
	CAST(COALESCE(updatedAt, updated_at) AS TIMESTAMP) AS ts_updated,
	year,
	month,
	day
FROM
	datalake_jaiminho_raw.user_notifications
