select
    _id, 
    boolean(active) as is_active,
    business_context,
    cloudsearch_criteria,
    created_at,
    date,
    days,
    device_id as id_device,
    filters,
    grandpa_user_id as id_grandpa_user,
    house_id as id_house,
    house_ids as ids_house,
    houses_ids as ids_houses,
    houses_sent, 
    boolean(is_auto_scheduling_possible) as is_auto_scheduling_possible,
    timestamp(lastActivation) as ts_last_activation,
    timestamp(last_day_sent) as ts_last_day_sent,
    last_email_run,
    lead_id as id_lead,
    name,
    notifications_sent_agent,
    profile_id as id_profile,
    push_user_id as id_push_user,
    quintoandar_id as id_quintoandar,
    results, 
    source,
    type,
    updated_at,
    user_id as id_user,
    visit_code,
    timestamp(visit_day_time) as ts_visited_day_time
from
    datalake_cidade_alerta_raw.alert