select
    _id, 
    aluguel as rental,
    aluguel_condominio as condo_rental,
    amenidades as amenities,
    andar as floor,
    area,
    bairro as neighborhood,
    banheiros as bathrooms,
    cidade as city,
    condominio as condo_price, 
    condominio_id as id_condo,
    custo as cost,
    descricao as description,
    endereco as address,
    first_publication,
    foto_capa as cover_photo,
    garantias as guarantees,
    home_insurance,
    house_id as id_house,
    id,
    instalacoes as facilities,
    iptu,
    listing_tags,
    local,
    nome_condominio as condo_name, 
    photo_titles,
    photos,
    quartos as bedrooms,
    regiao as region,
    regiao_nome as region_name,
    relevance_score,
    relevance_score_vnext,
    short_id as id_short,
    special_conditions,
    suites,
    tipo as type,
    ultima_publicacao as last_publication,
    vagas as vacancies,
    verificado as verified,
    visit_status    
from
    datalake_cidade_alerta_raw.house
    