select
    _id, 
    boolean(acceptSms) as has_accept_sms, 
    boolean(acceptWhatsapp) as has_accept_whatsapp,
    agentId as id_agent,
    alternativeEmail as alternative_email,
    birthDate as birth_date,
    businessContext as business_context,
    cpf,
    email,
    firstName as first_name,
    boolean(hasDocument) as has_document,
    hashId as id_hash,
    house_alerts,
    houses_sent,
    id, 
    boolean(isInstantLogin) as is_instant_login,
    boolean(isPartner) as is_partner,
    boolean(is_pwa) as is_pwa,
    last_email_run,
    name,
    boolean(new_houses_alert_subscription) as has_new_houses_alert_subscription,
    phone,
    phoneNumber as phone_number,
    phoneNumberSecondary as phone_number_secondary,
    phoneNumberSecondaryView as phone_number_secondary_view,
    phoneNumberView as phone_number_view,
    push_user_id as id_push_user,
    quintoandar_id as id_quintoandar,
    similar_houses_blacklist as similar_houses_blocklist,
    unsubscribed_notifications,
    visit_time_alert,
    visit_time_alert_subscription    
from
    datalake_cidade_alerta_raw.profile