SELECT
    id,
    parent_id AS id_parente,
    location_reference_id AS id_location_reference,
    internal_reference_id AS id_internal_reference,
    visitant_reference_id AS id_visitant_reference,
    version,
    type,
    dated_at,
    slot_of_day,
    duration_in_slots,
    status,
    check_in_status,
    last_app_origin,
    code,
    business_context,
    location_reference_name,
    internal_reference_name,
    visitant_date_time,
    visitant_reference_name,
    business_metadata,
    datetime,
    timezone,
    confirmed AS is_confirmed,
    fixed_agent AS is_fixed_agent,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_schedules_test_raw.appointment
