SELECT    
    id,
    feature_id AS id_feature,
    consolidated_id AS id_consolidated,
    person_id AS id_person,
    business_entity_id AS id_business_entity,
    finance_entity_id AS id_finance_entity,
    external_payment_id AS id_external_payment,
    finance_entity_entry_id AS id_finance_entity_entry,
    amount,
    user_type,
    source_client,
    status,
    city_state,
    city,
    accounting_rule,
    accounting_type,
    person_card_code,
    person_document,
    person_document_type,
    sequence_code,
    description,
    cost_center,
    business_place,
    account_code,
    account_cfop_code,
    account_managerial_center,
    person_address,
    person_address_block,
    person_address_complement,
    person_address_number,
    person_address_street_suffix,
    person_address_zip_code,
    person_city,
    person_email,
    person_name,
    person_phone,
    person_state,
    reference_year_month,
    reversed AS is_reversed,
    DATE(event_date) AS dt_event,
    DATE(due_date) AS dt_due,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated
FROM 
    datalake_sap_gateway_homolog_raw.invoice