select
  home_area int,
  home_bathrooms int,
  home_bedrooms int,
  home_city varchar,
  home_garages int,
  home_region varchar,
  home_suites int,
  home_type varchar,
  home_zipcode varchar,
  drive_id varchar,
  rejection_motive varchar,
  home_insurance_value numeric(14,4),
  risk_level varchar,
  risk_level_best_subset varchar,
  process_date timestamp

	id,
  proposal_id,
  imovel_id,
  analysis_date,
  "score_5A",
  "score_5A_best_subset",
  score_cardif,
  score_cardif_best_subset,
  status,
  replace("comment", '\n', ' ') as "comment",
  analyst_name,
  supervisor_name,
  rent_value,
  condo_value,
  iptu_value,
  created_at,
  updated_at,
  versioned_at,
  home_area,
  home_bathrooms,
  home_bedrooms,
  home_city,
  home_garages,
  home_region,
  home_suites,
  home_type,
  home_zipcode,
  drive_id,
  rejection_motive,
  home_insurance_value,
  risk_level,
  risk_level_best_subset,
  process_date
from "ProposalVersion"
;