SELECT
    id,
    gateway_id AS id_gateway,
    source_id AS id_source,
    operation_id AS id_operation,
    external_contract_id AS id_external_contract,
    gateway,
    source,
    product,
    status,
    status_reason,
    gateway_status,
    ccb_url,
    ccb_code,
    investment_source,
    partner_commission_amount,
    iof_amount,
    installment_amount,
    total_loan_cost_amount,
    requested_loan_amount,
    credit_accrual_year_month,
    first_installment_date AS ts_first_installment,
    signed_at AS ts_signed,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_fastforward_homolog_raw.gateway_loan
