SELECT
    id,
    contract_id AS id_contract,
    installment_option_id AS id_installment_option,
    installment_option_mod AS mod_id_installment_option,
    quota_id AS id_quota,
    operation_id AS id_operation,
    rev,
    revtype AS rev_type,
    investment_source,
    investment_source_mod AS mod_investment_source,
    status,
    status_mod AS mod_status,
    months_anticipated_number AS months_anticipated,
    months_anticipated_number_mod AS mod_months_anticipated,
    installment_value,
    installment_value_mod AS mod_installment_value,
    partner_commission,
    partner_commission_mod AS mod_partner_commission,
    total_amount,
    total_amount_mod AS mod_total_amount,
    total_rent,
    total_rent_mod AS mod_total_rent,
    ccb_code,
    ccb_url,
    iof_amount,
    iof_amount_mod AS mod_iof_amount,
    paid_at_mod AS mod_ts_paid,
    first_installment_date_mod AS mod_dt_first_installment,
    paid_at AS ts_paid,
    signed_at AS ts_signed,
    first_installment_date AS dt_first_installment
FROM
    datalake_fastforward_homolog_raw.long_term_anticipation_aud
