SELECT
    GET_JSON_OBJECT(REPLACE(_id, '$', ''), '$.oid') AS id,
    id AS id_profile,
    agentId AS id_agent,
    hashId AS id_hash,
    push_user_id AS id_push_user,
    quintoandar_id AS id_quintoandar,
    REGEXP_EXTRACT(businessContext, '(\\w+)', 0) AS business_context,
    name,
    firstName AS first_name,
    birthDate AS birth_date,
    cpf,
    email,
    alternativeEmail AS alternative_email,
    phone,
    phoneNumber AS phone_number,
    phoneNumberSecondary AS phone_number_secondary,
    phoneNumberSecondaryView AS phone_number_secondary_view,
    phoneNumberView AS phone_number_view,
    house_alerts,
    houses_sent,
    similar_houses_blacklist AS similar_houses_blocklist,
    unsubscribed_notifications,
    visit_time_alert,
    BOOLEAN(hasDocument) AS has_document,
    BOOLEAN(acceptSms) AS has_accept_sms, 
    BOOLEAN(acceptWhatsapp) AS has_accept_whatsapp,
    BOOLEAN(visit_time_alert_subscription) AS has_visit_time_alert_subscription,
    BOOLEAN(new_houses_alert_subscription) AS has_new_houses_alert_subscription,
    BOOLEAN(isPartner) AS is_partner,
    BOOLEAN(is_pwa) AS is_pwa,
    BOOLEAN(isInstantLogin) AS is_instant_login,
    TIMESTAMP(last_email_run) AS ts_last_email_run  
FROM
    datalake_cidade_alerta_raw.profile
