select
    id,
    name,
    cpf,
    income_nature,
    occupation_area,
    marital_status,
    gender,
    admission_date as dt_admitted,
    cell_phone,
    phone,
    email,
    monthly_income,
    will_reside as is_going_to_reside,
    location_motive,
    second_doc_type,
    second_doc_number,
    second_doc_issuer,
    second_doc_issue_date as dt_second_doc_issued,
    nationality,
    birthday as dt_birthday,
    mother_name,
    zipcode,
    address,
    address_number,
    complement,
    bairro as neighborhood,
    city,
    state,
    residence_condition,
    residence_time,
    profession,
    employer_name,
    employer_phone,
    extra_income_origin,
    extra_income_value,
    proposal_id as id_proposal,
    boavista_score,
    serasa_score,
    screening_result_id as id_screening_result
from datalake_sorting_hat_raw.proponent
