SELECT
    ID                          AS id_pre_analysis_itau,
    IDUsuario                   AS id_registration_user,
    id_usuarioRetorno           AS id_return_user,
    IDParceiro                  AS id_partner,
    IDFranquia                  AS id_franchise,
    IDSolicitacao               AS id_request,
    id_segmento                 AS id_segment,
    CPF                         AS client_cpf,
    CPF2                        AS client_cpf_secondary,
    cpf_mascara                 AS client_cpf_masked,
    EMAIL_SOLICITANTE           AS requester_email,
    produtoSacPlus              AS product_sac_plus,
    UF                          AS `state`,
    TpImovel                    AS house_type,
    tipo_operacao               AS operation_type,
    R_NOME                      AS r_name,
    R_SCORE                     AS r_score,
    R_SCORE2                    AS r_score2,
    R_SCORE3                    AS r_score3,
    R_ORIGEM                    AS r_origin,
    R_IDADE                     AS r_age,
    R_BHV                       AS r_bhv,
    R_BHV2                      AS r_bhv2,
    R_BHV3                      AS r_bhv3,
    ERRO                        AS error,
    `STATUS`                    AS pre_analysis_status,
    PRAZO                       AS deadline,
    vl_ltv                      AS ltv_value,
    vl_taxa                     AS fee_value,
    VlrImovel                   AS house_value,
    VlrEntrada                  AS down_payment_value,
    VlrFinanciado               AS financing_value,
    R_VLR_APROVADO              AS r_approved_value,
    S_PRIPARC                   AS s_first_installment_value,
    S_ULTPARC                   AS s_last_installment_value,
    S_VLRIBTI                   AS s_ribti_value,
    S_VLRTARIFA                 AS s_tax_value,
    S_VLRIOF                    AS s_iof_value,
    S_VLRRENDAMIN               AS s_min_income_value,
    S_TAXA                      AS s_fee_value,
    LIDO                        AS is_read,
    DATA_RETORNO                AS ts_returned,
    DATA_SOLICITACAO            AS ts_registration

FROM
    datalake_atta_test_raw.consulta_score_itau
