SELECT
    ID                          AS id_pre_analysis_bradesco,
    ID_USUARIO                  AS id_registration_user,
    IDParceiro                  AS id_partner,
    IDFranquia                  AS id_franchise,
    IDSolicitacao               AS id_request,
    id_usuarioRetorno           AS id_return_user,
    id_segmento                 AS id_segment,
    IDUsuarioAutorizacao        AS id_approval_user,
    IDUSUARIO_APTIDAO           AS id_qualification_user,
    CPF                         AS client_cpf,
    CPF2                        AS client_cpf_secondary,
    NomeProp1                   AS owner_name,
    tipo_operacao               AS operation_type,
    TipoParcela                 AS installment_type,
    TipoProduto                 AS product_type,
    R_SCORE                     AS r_score,
    Versao                      AS version_number,
    ERRO                        AS error,
    STATUS_APTIDAO              AS qualification_status,
    STATUS_SOLICITACAO          AS request_status,
    STATUS_INDICACAO            AS recommendation_status,
    STATUS_ANEXO                AS attachment_status,
    vl_ltv                      AS ltv_value,
    vl_taxa                     AS fee_value,
    VlrImovel                   AS house_value,
    VlrEntrada                  AS down_payment_value,
    VlrFinanciado               AS financing_value,
    DATA_RETORNO_SOLICITACAO    AS ts_registration_returned,
    DATA_INDICACAO              AS ts_recommendation,
    DATA_RETORNO_INDICACAO      AS ts_recommendation_returned,
    DATA_APTIDAO                AS ts_qualification,
    DATA_ANEXO                  AS ts_attachment,
    DATA_SOLICITACAO            AS ts_registration
FROM
    datalake_atta_test_raw.consulta_score_bradesco
