SELECT
    id,
    external_id AS id_external,
    contract_external_id AS id_contract_external,
    from_account_external_id AS id_from_account_external,
    to_account_external_id AS id_to_account_external,
    request_source_id AS id_request_source,
    idempotency_id AS id_idempotency,
    description,
    starts_when,
    number_of_times,
    contract_end_action,
    bill_item,
    amount,
    request_source_name,
    request_as,
    source,
    normality_control,
    status,
    canceled_when,
    timestamp(canceled_at) AS ts_canceled,
    timestamp(created_at) AS ts_created,
    timestamp(published_at) AS ts_published,
    timestamp(retsuko_created_at) AS ts_retsuko_created,
    timestamp(retsuko_updated_at) AS ts_retsuko_updated
FROM
    datalake_retsuko_raw.discount
