select
    id,
    external_id as id_external,
    account_id as id_account,
    contract_id as id_contract,
    status,
    sub_status as substatus,
    CAST(NULL AS STRING) AS negotiation_status,
    paid_via,
    purpose,
    closing_mode,
    reason,
    due_amount,
    paid_amount,
    accrual_year_month,
    sispag_file,
    timestamp(paid_date) as ts_paid,
    timestamp(canceled_at) as ts_canceled,
    timestamp(sent_at) as ts_sent,
    timestamp(due_date) as ts_due,
    timestamp(created_at) as ts_created,
    retsuko_created_at AS ts_retsuko_created,
    retsuko_updated_at AS ts_retsuko_updated
from
    datalake_retsuko_raw.invoice
