SELECT
    id,
    external_id AS id_external,
    original_invoice_external_id AS id_original_invoice_external,
    account_id AS id_account,
    contract_id AS id_contract,
    checkout_order_id AS id_checkout_order,
    checkout_charge_id AS id_checkout_charge,
    idempotency_id AS id_idempotency,
    status,
    sub_status AS substatus,
    payment_status,
    CAST(NULL AS STRING) AS negotiation_status,
    paid_via,
    purpose,
    closing_mode,
    reason,
    due_amount,
    paid_amount,
    payment_paid_interest_amount,
    payment_paid_fine_amount,
    accrual_year_month,
    should_request_boleto,
    sispag_file,
    payment_company_use_number,
    payment_bank_code,
    write_off AS is_write_off,
    write_off_at AS ts_write_off,
    timestamp(paid_date) AS ts_paid,
    timestamp(payment_confirmation_at) AS ts_payment_confirmation,
    timestamp(payment_event_at) AS ts_payment_event,
    timestamp(payment_divergent_fixed_at) AS ts_payment_divergent_fixed,
    timestamp(payment_processing_at) AS ts_payment_processing,
    timestamp(payment_credit_date) AS ts_payment_credit,
    timestamp(payment_chargeback_at) AS ts_payment_chargeback,
    timestamp(payment_refunded_at) AS ts_payment_refunded,
    timestamp(canceled_at) AS ts_canceled,
    timestamp(sent_at) AS ts_sent,
    timestamp(due_date) AS ts_due,
    timestamp(created_at) AS ts_created,
    timestamp(synced_at) AS ts_synced,
    timestamp(nf_requested_at) as ts_nf_requested,
    timestamp(retsuko_created_at) AS ts_retsuko_created,
    timestamp(retsuko_updated_at) AS ts_retsuko_updated,
    year,
    month,
    day
FROM
    datalake_retsuko_raw.invoice
