SELECT
    id,
    external_id AS id_external,
    business_entity_id AS id_business_entity,
    finance_entity_id AS id_finance_entity,
    requester_id AS id_requester,
    charge_id AS id_charge,
    payer_email,
    card_brand,
    requester_name,
    token,
    interest_type,
    payer_zipcode,
    fine_type,
    canceled_by_email,
    payer_name,
    first_six_digits,
    acquire_name,
    acquire_nsu,
    payer_neighborhood,
    acquire_tid,
    fixed_cost_of_transaction,
    block_entity,
    status,
    acquire_auth_code,
    payer_state,
    payer_street_address,
    cancellation_reason,
    payer_city,
    payer_identifiable_document,
    payer_person_type,
    convenience_fee_amount,
    fine_amount_percentage,
    refund_amount,
    acquire_fee_amount,
    paid_amount,
    fine_paid_amount,
    max_installments,
    min_installments,
    installments,
    interest_amount,
    interest_amount_percentage,
    interest_paid_amount,
    installment_fee_amount,
    due_amount,
    fine_amount,
    last_four_digits,
    code,
    last_date_to_pay AS dt_last_date_to_pay,
    due_date AS dt_due,
    created_at AS ts_created,
    fine_start_at AS ts_fine_start,
    updated_at AS ts_updated,
    interest_start_at AS ts_interest_start,
    paid_at AS ts_paid,
    canceled_at AS ts_canceled
FROM
    datalake_checkout_homolog_raw.credit_card
