SELECT
    pt.id AS id_agent_tier,
    IF(pt.partner_external_type = 'PERSON', pt.id_partner_external, NULL) AS uuid_person,
    pt.id_tier,
    tr.id_business_unit,
    pt.partner_external_type,
    pt.incentive_system,
    pt.status,
    tr.tier_name,
    tr.tier_priority,
    tr.classifier_min_score,
    tr.classifier_resume,
    tr.qualifier_min_score,
    tr.qualifier_resume,
    tr.classifier_max_points_cs,
    tr.classifier_max_points_fl_rent,
    tr.classifier_max_points_ccv,
    tr.classifier_max_points_fl_sale,
    tr.classifier_max_points_tqc,
    tr.classifier_min_points_cs,
    tr.classifier_min_points_fl_rent,
    tr.classifier_min_points_ccv,
    tr.classifier_min_points_sale,
    tr.classifier_min_points_tqc,
    tr.classifier_multiplier_cs,
    tr.classifier_multiplier_fl_rent,
    tr.classifier_multiplier_ccv,
    tr.classifier_multiplier_fl_sale,
    tr.classifier_multiplier_tqc,
    tr.qualifier_max_points_cs,
    tr.qualifier_max_points_fl_rent,
    tr.qualifier_max_points_ccv,
    tr.qualifier_max_points_fl_sale,
    tr.qualifier_max_points_tqc,
    tr.qualifier_min_points_cs,
    tr.qualifier_min_points_fl_rent,
    tr.qualifier_min_points_ccv,
    tr.qualifier_min_points_sale,
    tr.qualifier_min_points_tqc,
    tr.qualifier_multiplier_cs,
    tr.qualifier_multiplier_fl_rent,
    tr.qualifier_multiplier_ccv,
    tr.qualifier_multiplier_fl_sale,
    tr.qualifier_multiplier_tqc,
    pt.dt_validity_started,
    pt.dt_validity_ended,
    pt.ts_created,
    pt.ts_updated
  FROM
    datalake_big_agent_clean.partner_tier AS pt
  JOIN
    datalake_big_agent.tier_rule AS tr
      ON pt.id_tier = tr.id_tier
  WHERE
    DATE(pt.ts_updated) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
