SELECT
    id,
    partner_id AS id_partner,
    file_id AS id_file,
    listing_id AS id_listing,
    lead_id AS id_lead,
    real_estate_id AS id_real_estate,
    id_by_real_estate,
    brokers,
    location,
    pricing,
    owner,
    blueprint,
    details,
    access,
    administrators,
    photos,
    lead_hash,
    enrichment_reason,
    discard_reason,
    eligible_reason,
    cnpj,
    version,
    sent_to_bob AS is_sent_to_bob,
    eligible AS is_eligible,
    enriched AS is_enriched,
    discard AS is_discarded,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    partner_id_mod AS mod_id_partner,
    file_id_mod AS mod_id_file,
    listing_id_mod AS mod_id_listing,
    lead_id_mod AS mod_id_lead,
    real_estate_id_mod AS mod_id_real_estate,
    id_by_real_estate_mod AS mod_id_by_real_estate,
    brokers_mod AS mod_brokers,
    location_mod AS mod_location,
    pricing_mod AS mod_pricing,
    owner_mod AS mod_owner,
    blueprint_mod AS mod_blueprint,
    details_mod AS mod_details,
    access_mod AS mod_access,
    administrators_mod AS mod_administrators,
    photos_mod AS mod_photos,
    lead_hash_mod AS mod_lead_hash,
    enrichment_reason_mod AS mod_enrichment_reason,
    discard_reason_mod AS mod_discard_reason,
    eligible_reason_mod AS mod_eligible_reason,
    cnpj_mod AS mod_cnpj,
    sent_to_bob_mod AS mod_is_sent_to_bob,
    enriched_mod AS mod_is_enriched,
    eligible_mod AS mod_is_eligible,
    discard_mod AS mod_is_discarded,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_brokers_supply_processor_raw.lead3p_aud
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}