drop table if exists datalake_clean.ods_dim_booking;
create external table if not exists datalake_clean.ods_dim_booking (
  sk_booking string,
  id_booking string,
  is_rescheduled string,
  dt_scheduling string,
  visit_intent string,
  buyer_intention string,
  type string,
  confirmed string,
  performed string,
  closed string,
  visit_follow_up string,
  dt_visit_follow_up string,
  rescheduled_from_id string,
  id_visitor string,
  id_visit string,
  id_property string,
  id_agent string,
  id_attendant string,
  id_rental_flow string,
  status string,
  slot_dia string,
  reason string,
  cancellation_reason string,
  cancellation_reason_category string,
  reason_category string,
  responsible string,
  app_type string,
  media_source string,
  adjust_network string,
  utm_source string,
  utm_medium string,
  utm_campaign string,
  utm_content string,
  utm_term string,
  dt_cancel string,
  dt_created string,
  dt_updated string,
  last_update_source string,
  first_update_source string,
  visitor_arrived string,
  visitor_missing_reason string,
  agent_arrived string,
  agent_missing_reason string,
  owner_arrived string,
  owner_missing_reason string,
  successful_entrance string,
  troublesome_entrance string,
  checkin_status string,
  ts_scheduling_local string,
  ts_cancel_local string,
  ts_created_local string,
  ts_visit_follow_up_local string,
  is_first_booking_auto string,
  is_visit_created_from_app string,
  is_visit_last_updated_from_app string,
  flg_branded string,
  flg_via_reschedule string,
  sk_rent_flow_taxonomy string,
  mkt_category string,
  mkt_flow string,
  mkt_completion string,
  mkt_origin string,
  mkt_channel string,
  mkt_medium string,
  mkt_source string,
  mkt_platform string,
  ts_load string
)
row format serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
with serdeproperties (
  'separatorChar' = ',',
  'quoteChar' = '\"'
)
location 's3://5a-datalake/clean/ods/booking'
tblproperties (
  'skip.header.line.count' = '1'
)
;