drop table if exists datalake_clean.ods_dim_lead;

create external table if not exists datalake_clean.ods_dim_lead (
  sk_lead string,
  id string,
  area_total string,
  bairro string,
  captado_em string,
  cep string,
  cidade string,
  complemento string,
  endereco string,
  nome_anunciante string,
  numero string,
  numero_banheiros string,
  numero_quartos string,
  numero_suites string,
  url_anuncio string,
  telefone_anunciante string,
  tipo string,
  email string,
  email_captador string,
  telefone_captador string,
  dentro_area_atuacao string,
  lat string,
  lng string,
  condominio string,
  iptu string,
  ub_page_variant string,
  ub_page_name string,
  reason string,
  reason_detail string,
  deadline_of_new_contact string,
  status string,
  processado string,
  origem string,
  is_enriched_data string,
  external_id string,
  mencionar string,
  automatically_discarded string,
  proprietario_nome string,
  proprietario_email string,
  affiliate_type string,
  dados_afiliado_inicio_atuacao string,
  dados_afiliado_cidade_atuacao string,
  region_id string,
  atualizado_em string,
  criado_em string,
  utm_source string,
  utm_medium string,
  utm_campaign string,
  utm_content string,
  utm_term string,
  tracking_platform string,
  tracking_region string,
  tracking_city string,
  network string,
  usuario_que_indicou_id string,
  score_factor string,
  is_b2b string,
  b2b_type string,
  sales_company string,
  ts_sales_company_sent string,
  sale_price string,
  is_for_rent string,
  is_for_sale string,
  load_timestamp string
)
row format serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
with serdeproperties (
  'separatorChar' = ',',
  'quoteChar' = '\"'
)
location 's3://5a-datalake/clean/ods/lead'
tblproperties (
  'skip.header.line.count' = '1'
)
;