drop table if exists datalake_clean.ods_dim_lead;

create external table if not exists datalake_clean.ods_dim_lead (
  sk_lead string,
  id string,
  anuncio_criado_em string,
  area_total string,
  bairro string,
  captado_em string,
  cep string,
  cidade string,
  complemento string,
  endereco string,
  endereco_captado string,
  nome_anunciante string,
  numero string,
  numero_banheiros string,
  numero_quartos string,
  numero_suites string,
  url_anuncio string,
  valor string,
  telefone_anunciante string,
  valor_por_metro_quad string,
  valor_por_quartos string,
  tipo string,
  email string,
  email_captador string,
  telefone_captador string,
  hot string,
  proximo_followup string,
  gerado_a_partir_de_deduplicacao string,
  dentro_area_atuacao string,
  sistema_enviou_email_via_classificado string,
  lat string,
  lng string,
  condominio string,
  iptu string,
  reason string,
  reason_detail string,
  status string,
  envio_email_apresentacao_pos string,
  envio_email_apresentacao_pre string,
  processado string,
  origem string,
  external_id string,
  mencionar string,
  referencia string,
  automatically_discarded string,
  estado_nome string,
  estado_abrev string,
  lead_imobiliaria string,
  proprietario_nome string,
  proprietario_email string,
  dados_corretor_tipo_afiliado string,
  dados_corretor_nome string,
  dados_corretor_email string,
  dados_gerente_contas_nome string,
  dados_gerente_contas_email string,
  dados_afiliado_tipo_afiliado string,
  dados_afiliado_inicio_atuacao string,
  dados_afiliado_cidade_atuacao string,
  region_id string,
  atualizado_em string,
  criado_em string,
  url_source string,
  utm_source string,
  utm_medium string,
  utm_campaign string,
  network string,
  usuario_que_indicou_id string,
  flg_city_served string,
  flg_latlng_served string,
  flg_location_served string,
  score_factor string,
  load_timestamp string
)
row format serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
with serdeproperties (
  'separatorChar' = ',',
  'quoteChar' = '\"'
)
location 's3://5a-datalake/clean/ods/lead'
tblproperties (
  'skip.header.line.count' = '1'
)
;