DROP TABLE datalake_clean.ods_dim_user;

CREATE EXTERNAL TABLE datalake_clean.ods_dim_user (
  `sk_user` string,
  `id` string,
  `nome` string,
  `bairro` string,
  `cep` string,
  `cidade` string,
  `complemento` string,
  `cpf` string,
  `data_nascimento` string,
  `email` string,
  `email_alternativo` string,
  `endereco` string,
  `numero` string,
  `facebook_id` string,
  `linkedin_id` string,
  `sexo` string,
  `telefone_principal` string,
  `estado_abreviacao` string,
  `estado_nome` string,
  `bloqueado` string,
  `rg` string,
  `dadosagente_perfil` string,
  `dadosagente_numero_creci` string,
  `dadosagente_ativo` string,
  `aceita_sms` string,
  `data_clickanuncie` string,
  `dadosbancarios_banco_codigo` string,
  `dadosbancarios_banco` string,
  `dadosbancarios_agencia` string,
  `dadosbancarios_conta_corrente` string,
  `dadosbancarios_cpf_cnpj` string,
  `dadosbancarios_nome` string,
  `dadosbancarios_outro_titular` string,
  `dadosbancarios_tipo_conta` string,
  `tipo_admin` string,
  `google_id` string,
  `account_kit_id` string,
  `dadosfotografo_inicio_contrato` string,
  `dadosfotografo_tipo_contrato` string,
  `dadosfotografo_ativo` string,
  `dadosvendedor_inicio_contrato` string,
  `dadosafiliado_inicio_atuacao` string,
  `dadosafiliado_cidade_atuacao` string,
  `dadosafiliado_preferencia_pagamento` string,
  `dadosafiliado_numero_creci` string,
  `dadosafiliado_semana_ultima_comunicacao_balanco` string,
  `dadosafiliado_ativo` string,
  `active` string,
  `dados_agente_id` string,
  `dados_fotografo_id` string,
  `dados_vendedor_id` string,
  `dados_afiliado_id` string,
  `flg_doorman_affiliate` string,
  `sk_doorman_joined_date` string,
  `tem_imovel` string,
  `tem_app_inquilino` string,
  `tem_contrato_ativo` string,
  `inquilino` string,
  `first_booking_date` string,
  `first_booking_confirmed_date` string,
  `first_visit_date` string,
  `first_visit_confirmed_date` string,
  `first_pre_proposal_date` string,
  `first_proposal_accepted_date` string,
  `first_contract_date` string,
  `first_signed_contract` string,
  `first_dt_document_sent` string,
  `last_dt_document_sent` string,
  `first_dt_sent_to_insurance` string,
  `criado_em` string,
  `atualizado_em` string,
  `load_timestamp` string,
  `network` string,
  `visits_booked` string,
  `visits_realized` string,
  `visits_expected_to_happen` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
WITH SERDEPROPERTIES ( 
  'separatorChar'=',') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://5a-datalake/clean/ods/user'
TBLPROPERTIES (
  'quoteChar'='\"', 
  'serialization.null.format'='', 
  'skip.header.line.count'='1')