DROP TABLE datalake_clean.ods_dim_user;

CREATE EXTERNAL TABLE datalake_clean.ods_dim_user (
    sk_user bigint,
    sk_doorman_joined_date bigint,
    id bigint,
    dados_agente_id int,
    dados_fotografo_id int,
    dados_vendedor_id int,
    dados_afiliado_id int,
    facebook_id varchar(255),
    linkedin_id varchar(255),
    google_id varchar(255),
    active int,
    bloqueado int,
    dadosafiliado_ativo int,
    dadosagente_ativo int,
    dadosfotografo_ativo int,
    flg_doorman_affiliate int,
    inquilino varchar(10),
    is_sale_agent boolean,
    is_rent_agent boolean,
    dadosbancarios_outro_titular int,
    tem_imovel varchar(10),
    tem_app_inquilino varchar(10),
    tem_contrato_ativo varchar(10),
    aceita_sms int,
    nome varchar(255),
    cpf varchar(255),
    rg varchar(30),
    sexo varchar(255),
    email varchar(255),
    email_alternativo varchar(255),
    telefone_principal varchar(255),
    endereco varchar(255),
    numero varchar(255),
    complemento varchar(255),
    bairro varchar(255),
    cep varchar(255),
    cidade varchar(255),
    estado_nome varchar(200),
    estado_abreviacao varchar(200),
    tipo_admin varchar(255),
    dadosbancarios_banco_codigo varchar(255),
    dadosbancarios_banco varchar(255),
    dadosbancarios_agencia varchar(255),
    dadosbancarios_conta_corrente varchar(255),
    dadosbancarios_cpf_cnpj varchar(255),
    dadosbancarios_nome varchar(255),
    dadosbancarios_tipo_conta varchar(255),
    dadosagente_perfil varchar(255),
    dadosagente_numero_creci varchar(255),
    dadosfotografo_tipo_contrato varchar(255),
    dadosafiliado_cidade_atuacao varchar(100),
    dadosafiliado_preferencia_pagamento varchar(255),
    dadosafiliado_numero_creci varchar(255),
    dadosafiliado_semana_ultima_comunicacao_balanco int,
    visits_booked int,
    visits_realized int,
    visits_expected_to_happen int,
    data_nascimento date,
    first_visit_date timestamp,
    first_visit_confirmed_date timestamp,
    data_clickanuncie timestamp,
    dadosfotografo_inicio_contrato timestamp,
    dadosvendedor_inicio_contrato timestamp,
    dadosafiliado_inicio_atuacao timestamp,
    first_booking_date timestamp,
    first_booking_confirmed_date timestamp,
    first_pre_proposal_date timestamp,
    first_proposal_accepted_date timestamp,
    first_contract_date timestamp,
    first_signed_contract timestamp,
    first_dt_document_sent timestamp,
    last_dt_document_sent timestamp,
    first_dt_sent_to_insurance timestamp,
    criado_em timestamp,
    atualizado_em timestamp,
    network varchar(255),
    load_timestamp timestamp
)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://dw.s3.data.quintoandar.com.br/public/dim_user'
TBLPROPERTIES (
  'parquet.compress'='SNAPPY')