drop table if exists datalake_clean.ods_dim_booking;
create external table if not exists datalake_clean.ods_dim_booking (
  sk_booking int,
  sk_rent_flow_taxonomy bigint,
  id_booking int,
  id_visitor bigint,
  id_visit bigint,
  id_property bigint,
  id_agent bigint,
  id_attendant bigint,
  id_rental_flow bigint,
  rescheduled_from_id int,
  visit_intent varchar(100),
  buyer_intention varchar(100),
  type varchar(255),
  confirmed varchar(100),
  performed varchar(100),
  closed varchar(100),
  is_rescheduled boolean,
  flg_via_reschedule boolean,
  is_first_booking_auto boolean,
  flg_branded boolean,
  visitor_arrived varchar(255),
  agent_arrived varchar(255),
  owner_arrived varchar(255),
  successful_entrance varchar(255),
  is_visit_created_from_app boolean,
  is_visit_last_updated_from_app boolean,
  visit_follow_up varchar(255),
  status varchar(255),
  slot_dia int,
  reason varchar(255),
  cancellation_reason varchar(255),
  cancellation_reason_category varchar(255),
  reason_category varchar(255),
  responsible varchar(255),
  last_update_source varchar(255),
  first_update_source varchar(255),
  visitor_missing_reason varchar(255),
  agent_missing_reason varchar(255),
  owner_missing_reason varchar(255),
  troublesome_entrance varchar(255),
  checkin_status varchar(255),
  app_type varchar(255),
  media_source varchar(255),
  adjust_network varchar(255),
  utm_source varchar(255),
  utm_medium varchar(255),
  utm_campaign varchar(2000),
  utm_content varchar(255),
  utm_term varchar(255),
  mkt_category varchar(255),
  mkt_flow varchar(255),
  mkt_completion varchar(255),
  mkt_origin varchar(255),
  mkt_channel varchar(255),
  mkt_medium varchar(255),
  mkt_source varchar(255),
  mkt_platform varchar(255),
  dt_visit_follow_up timestamp,
  ts_visit_follow_up_local timestamp,
  dt_scheduling timestamp,
  ts_scheduling_local timestamp,
  dt_cancel timestamp,
  ts_cancel_local timestamp,
  dt_created timestamp,
  ts_created_local timestamp,
  dt_updated timestamp,
  ts_load timestamp  
)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://dw.s3.data.quintoandar.com.br/public/dim_booking'
TBLPROPERTIES (
  'parquet.compress'='SNAPPY')
;