drop table if exists datalake_clean.ods_fact_listing_rent_flows;
create external table datalake_clean.ods_fact_listing_rent_flows (
    ods_id BIGINT,
    sk_house_listing BIGINT,
    sk_region BIGINT,
    sk_condo BIGINT,
    sk_rent_flow BIGINT,
    sk_booking BIGINT,
    sk_tenant_booking_review BIGINT,
    sk_owner BIGINT,
    sk_user_agent BIGINT,
    sk_client BIGINT,
    sk_visit BIGINT,
    sk_offer BIGINT,
    sk_reservation BIGINT,
    sk_proposal BIGINT,
    sk_contract BIGINT,
    sk_rent_flow_taxonomy BIGINT,
    sk_house_first_listing_date BIGINT,
    sk_house_listing_date BIGINT,
    sk_house_listing_de_publication_date BIGINT,
    sk_house_listing_first_offer_submitted_date BIGINT,
    sk_booking_created_date BIGINT,
    sk_visit_date BIGINT,
    sk_agent_sign_up_date BIGINT,
    sk_client_sign_up_date BIGINT,
    sk_offer_submitted_date BIGINT,
    sk_min_offer_submitted_date BIGINT,
    sk_offer_approved_date BIGINT,
    sk_reservation_created_date BIGINT,
    sk_proposal_approved_date BIGINT,
    sk_proposal_processed_date BIGINT,
    sk_tenant_first_doc_sent_date BIGINT,
    sk_tenant_manual_first_doc_sent_date BIGINT,
    sk_tenant_auto_first_doc_sent_date BIGINT,
    sk_tenant_first_doc_complete_date BIGINT,
    sk_tenant_last_doc_complete_date BIGINT,
    sk_tenant_doc_complete_date BIGINT,
    sk_contract_created_date BIGINT,
    sk_contract_signed_date BIGINT,
    sk_contract_annulment_date BIGINT,
    sk_contract_canceled_date BIGINT,
    sk_credit_analysis_first_init_date BIGINT,
    sk_credit_analysis_last_init_date BIGINT,
    sk_credit_analysis_init_date BIGINT,
    sk_credit_analysis_first_end_date BIGINT,
    sk_credit_analysis_last_end_date BIGINT,
    sk_credit_analysis_end_date BIGINT,
    sk_credit_analysis_approved_date BIGINT,
    sk_first_credit_evaluation_init BIGINT,
    sk_last_credit_evaluation_init BIGINT,
    sk_first_credit_evaluation_positive BIGINT,
    sk_last_credit_evaluation_positive BIGINT,
    sk_first_credit_evaluation_negative BIGINT,
    sk_last_credit_evaluation_negative BIGINT,
    sk_guarantee_date BIGINT,
    sk_first_doc_analysis_approved BIGINT,
    sk_last_doc_analysis_approved BIGINT,
    sk_first_doc_analysis_rejected BIGINT,
    sk_last_doc_analysis_rejected BIGINT,
    sk_guarantee_paid_date BIGINT,
    sk_agent_review_rating_date BIGINT,
    visit_created_type VARCHAR(256),
    booking_utm_campaign VARCHAR(2000),
    booking_utm_content VARCHAR(256),
    booking_utm_term VARCHAR(256),
    funnel_step VARCHAR(255),
    funnel_step_drop_reason VARCHAR(255),
    flg_visit_completed BOOLEAN,
    flg_visit_performed BOOLEAN,
    flg_visit_created_from_app BOOLEAN,
    flg_visit_last_updated_from_app BOOLEAN,
    reservation_attempts SMALLINT,
    days_booking_created_to_visit DECIMAL(14,2),
    days_user_created_to_visit DECIMAL(14,2),
    days_offer_submitted_to_internal_analysis DECIMAL(14,2),
    days_offer_approved_to_doc_first_sent DECIMAL(14,2),
    days_offer_approved_to_owner_doc_sent DECIMAL(14,2),
    days_first_doc_sent_to_credit_processed DECIMAL(14,2),
    days_first_doc_sent_to_doc_completed DECIMAL(14,2),
    days_doc_completed_to_credit_processed DECIMAL(14,2),
    days_credit_approved_to_contract_created DECIMAL(14,2),
    days_credit_approved_to_contract_signed DECIMAL(14,2),
    days_contract_created_to_contract_signed DECIMAL(14,2),
    days_booking_created_to_contract_signed DECIMAL(14,2),
    days_visit_to_contract_signed DECIMAL(14,2),
    days_visit_to_offer_submitted DECIMAL(14,2),
    days_booking_created_to_offer_submitted DECIMAL(14,2),
    days_tenant_first_doc_sent_to_insurance_approved DECIMAL(14,2),
    days_insurance_approved_to_contract_signed DECIMAL(14,2),
    days_offer_approved_to_tenant_first_doc_sent DECIMAL(14,2),
    days_offer_submitted_to_offer_approved DECIMAL(14,2),
    days_offer_approved_to_credit_init DECIMAL(14,2),
    days_offer_submitted_to_contract_signed DECIMAL(14,2),
    days_offer_approved_to_contract_signed DECIMAL(14,2),
    days_tenant_doc_completed_to_credit_approved DECIMAL(14,2),
    days_tenant_first_doc_sent_to_doc_completed DECIMAL(14,2),
    days_house_listing_to_contract_signed DECIMAL(14,2),
    days_house_listing_to_visit DECIMAL(14,2),
    days_credit_approved_to_closing_processed DECIMAL(14,2),
    days_offer_approved_to_doc_contact DECIMAL(14,2),
    ts_load TIMESTAMP  
)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://dw.s3.data.quintoandar.com.br/public/fact_listing_rent_flows'
TBLPROPERTIES (
  'parquet.compress'='SNAPPY');
