drop table if exists datalake_clean.fact_supply;

create external table datalake_clean.fact_supply (
	ods_id string,
	sk_lead string,
	sk_conversion string,
	sk_photo_job string,
	sk_property string,
	sk_user_rep string,
	sk_user_sales_rep string,
	sk_user_affiliate string,
	sk_user_task_assignee string,
	sk_user_owner string,
	sk_user_photographer string,
	sk_region string,
	sk_lead_date string,
	sk_prospect_date string,
	sk_task_created_date string,
	sk_task_closed_date string,
	sk_first_inside_sales_contact_date string,
	sk_conversion_date string,
	sk_qualified_date string,
	sk_opportunity_date string,
	sk_first_listing_date string,
	sk_discard_date string,
	flow string,
	acquisition_method string,
	acquisition_channel string,
	acquisition_source string,
	funnel_step string,
	funnel_drop_reason string,
	lead_to_prospect_diff_minutes string,
	prospect_to_qualified_diff_minutes string,
	lead_to_first_inside_sales_contact_diff_minutes string,
	prospect_to_first_inside_sales_contact_diff_minutes string,
	qualified_to_opportunity_diff_minutes string,
	opportunity_to_listing_diff_minutes string,
	lead_to_listing_diff_minutes string,
	lead_to_prospect_diff_hours string,
	prospect_to_qualified_diff_hours string,
	lead_to_first_inside_sales_contact_diff_hours string,
	prospect_to_first_inside_sales_contact_diff_hours string,
	qualified_to_opportunity_diff_hours string,
	opportunity_to_listing_diff_hours string,
	lead_to_listing_diff_hours string,
	lead_to_prospect_diff_days string,
	prospect_to_qualified_diff_days string,
	lead_to_first_inside_sales_contact_diff_days string,
	prospect_to_first_inside_sales_contact_diff_days string,
	qualified_to_opportunity_diff_days string,
	opportunity_to_listing_diff_days string,
	lead_to_listing_diff_days string,
	lead_to_processing_diff_days string,
	exclusivity string,
	lead_type string,
	lead_origin string,
	lead_utm_source string,
	lead_utm_medium string,
	flg_branded string,
	flg_b2b string,
	flg_doorman string,
	flg_isales_direct_register string,
	flg_cx_direct_register string,
	flg_isales_intervention string,
	flg_callcenter string,
	mkt_branded string,
	mkt_category string,
	mkt_flow string,
	mkt_completion string,
	mkt_channel string,
	mkt_platform string,
	mkt_medium string,
	mkt_source string,
	dt_timestamp string
)
row format serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
with serdeproperties (
  'separatorChar' = ',',
  'quoteChar' = '\"'
)
location 's3://5a-datalake/clean/ods/supply'
tblproperties (
  'skip.header.line.count' = '1'
)
;