drop table if exists datalake_clean.ods_fact_demand;
create external table datalake_clean.ods_fact_demand (
  ods_id string,
	sk_house string,
	sk_house_first_listing_date string,
	sk_house_listing_date string,
	sk_house_de_publication_date string,
	sk_house_first_offer_submitted_date string,
	sk_region string,
	sk_rent_flow string,
	sk_booking string,
	sk_booking_created_date string,
	sk_visit_date string,
	sk_owner string,
	sk_user_agent string,
	sk_agent_sign_up_date string,
	sk_client string,
	sk_client_sign_up_date string,
	sk_visit string,
	sk_offer string,
	sk_offer_submitted_date string,
	sk_min_offer_submitted_date string,
	sk_offer_approved_date string,
	sk_proposal string,
	sk_proposal_approved_date string,
	sk_tenant_first_document_sent_date string,
	sk_tenant_auto_first_doc_sent_date string,
	sk_contract string,
	sk_contract_created_date string,
	sk_contract_signed_date string,
	sk_contract_annulment_date string,
	sk_credit_analysis_init_date string,
	sk_credit_analysis_end_date string,
	sk_credit_analysis_approved_date string,
	flg_visit_completed string,
	flg_visit_performed string,
	flg_visit_created_from_app string,
	visit_created_type string,
	flg_visit_last_updated_from_app string,
	visit_last_updated_type string,
    booking_to_visit string,
    offer_submitted_to_internal_analyis string,
    offer_approved_to_doc_first_sent string,
    doc_first_sent_to_credit_processed string,
    doc_first_sent_to_doc_completed string,
    doc_completed_to_credit_processed string,
    credit_approved_to_contract_created string,
    credit_approved_to_contract_signed string,
    contract_created_to_contract_signed string,
    days_booking_to_contract_signed string,
	days_booking_to_visit string,
	days_user_creation_to_visit string,
	days_visit_to_contract_signed string,
	days_visit_to_offer_submitted string,
	days_booking_created_to_offer_submitted string,
	days_tenant_doc_sent_to_insurance_approval string,
	days_insurance_approval_to_contract_signed string,
	days_offer_approved_to_tenant_doc_sent string,
	days_offer_submitted_to_offer_approved string,
	days_offer_approved_to_credit_init string,
	days_offer_submitted_to_contract_signed string,
	days_tenant_doc_completed_to_credit_approved string,
	days_tenant_doc_sent_to_doc_completed string,
	days_credit_approved_to_contract_created string,
	days_credit_approved_to_contract_signed string,
	days_contract_created_to_contract_signed string,
	days_house_listing_to_contract_signed string,
	days_house_listing_to_visit string,
	sk_agent_review_rating_date string,
    dt_timestamp string
)
row format serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
with serdeproperties (
  'separatorChar' = ',',
  'quoteChar' = '\"'
)
location 's3://5a-datalake/clean/ods/demand'
tblproperties (
  'skip.header.line.count' = '1'
)
;