drop table if exists datalake_clean.ods_sale_fact_listing_flows;

create external table datalake_clean.ods_sale_fact_listing_flows (
    sk_house_listing_flow bigint,
    sk_condo bigint,
    sk_lead bigint,
    sk_lead_conversion bigint,
    sk_first_photo_job bigint,
    sk_house_listing bigint,
    sk_user_house_registrant bigint,
    sk_user_sales_rep bigint,
    sk_user_lead_affiliate bigint,
    sk_user_first_task_assignee bigint,
    sk_user_last_task_assignee bigint,
    sk_region bigint,
    sk_city bigint,
    sk_partner bigint,
    sk_lead_date bigint,
    sk_sales_company_lead_sent_date bigint,
    sk_prospect_date bigint,
    sk_first_task_created_date bigint,
    sk_first_task_closed_date bigint,
    sk_last_task_created_date bigint,
    sk_last_task_closed_date bigint,
    sk_first_contact_date bigint,
    sk_conversion_date bigint,
    sk_qualified_date bigint,
    sk_opportunity_date bigint,
    sk_first_listing_date bigint,
    sk_discard_date bigint,
    sk_user_lead_first_discarder int,
    sk_user_lead_last_discarder int,
    funnel_step varchar(255),
    funnel_drop_reason varchar(255),
    hours_lead_to_prospect decimal(10,1),
    hours_prospect_to_qualified decimal(10,1),
    hours_lead_to_first_contact decimal(10,1),
    hours_prospect_to_first_contact decimal(10,1),
    hours_qualified_to_opportunity decimal(10,1),
    hours_opportunity_to_listing decimal(10,1),
    hours_lead_to_listing decimal(10,1),
    days_lead_to_prospect decimal(10,1),
    days_prospect_to_qualified decimal(10,1),
    days_lead_to_first_contact decimal(10,1),
    days_prospect_to_first_contact decimal(10,1),
    days_qualified_to_opportunity decimal(10,1),
    days_opportunity_to_listing decimal(10,1),
    days_lead_to_listing decimal(10,1),
    days_lead_to_processing decimal(10,1),
    is_exclusive SMALLINT,
    first_isales_intervention varchar(50),
    lead_type varchar(255),
    lead_origin varchar(255),
    lead_tracking_source varchar(255),
    lead_tracking_medium varchar(255),
    lead_tracking_platform varchar(255),
    is_branded boolean,
    is_b2b boolean,
    is_doorman boolean,
    is_isales_direct_register boolean,
    is_cx_direct_register boolean,
    is_ops_direct_register boolean,
    has_isales_intervention boolean,
    has_fup_photo_task boolean,
    is_call_center boolean,
    is_lead_reprocessed boolean,
    affiliate_type varchar(512),
    is_agent_referral boolean,
    lead_referring_domain varchar(512),
    lead_referring_category varchar(512),
    subscription_source varchar(512),
    mkt_branded varchar(255),
    mkt_category varchar(255),
    mkt_flow varchar(255),
    mkt_completion varchar(255),
    mkt_origin varchar(255),
    mkt_channel varchar(255),
    mkt_platform varchar(255),
    mkt_medium varchar(255),
    mkt_source varchar(255),
    lead_context_origin varchar(255),
    listing_rent_status varchar(255),
    ts_opt_out_sale timestamp,
    ts_load timestamp
)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://dw.s3.data.quintoandar.com.br/sale/fact_listing_flows'
TBLPROPERTIES (
  'parquet.compress'='SNAPPY')
;
