drop table if exists datalake_clean.ods_fact_house_listing_flows;

create external table datalake_clean.ods_fact_house_listing_flows (
	sk_house_listing_flow BIGINT,
	sk_condo BIGINT,
	sk_lead INT,
	sk_lead_conversion INT,
	sk_first_photo_job INT,
	sk_house_listing BIGINT,
	sk_user_house_registrant INT,
	sk_user_sales_rep INT,
	sk_user_lead_affiliate INT,
	sk_user_first_task_assignee INT,
	sk_user_last_task_assignee INT,
	sk_region INT,
	sk_city INT,
	sk_partner INT,
	sk_autonomous_agent INT,
	sk_lead_date INT,
	sk_sales_company_lead_sent_date INT,
	sk_prospect_date INT,
	sk_first_task_created_date INT,
	sk_first_task_closed_date INT,
	sk_last_task_created_date INT,
	sk_last_task_closed_date INT,
	sk_first_contact_date INT,
	sk_conversion_date INT,
	sk_qualified_date INT,
	sk_opportunity_date INT,
	sk_first_listing_date INT,
	sk_discard_date INT,
	sk_user_lead_first_discarder INT,
	sk_user_lead_last_discarder INT,
	funnel_step VARCHAR(255),
	funnel_drop_reason VARCHAR(255),
	hours_lead_to_prospect DECIMAL(10,1),
	hours_prospect_to_qualified DECIMAL(10,1),
	hours_lead_to_first_contact DECIMAL(10,1),
	hours_prospect_to_first_contact DECIMAL(10,1),
	hours_qualified_to_opportunity DECIMAL(10,1),
	hours_opportunity_to_listing DECIMAL(10,1),
	hours_lead_to_listing DECIMAL(10,1),
	days_lead_to_prospect DECIMAL(10,1),
	days_prospect_to_qualified DECIMAL(10,1),
	days_lead_to_first_contact DECIMAL(10,1),
	days_prospect_to_first_contact DECIMAL(10,1),
	days_qualified_to_opportunity DECIMAL(10,1),
	days_opportunity_to_listing DECIMAL(10,1),
	days_lead_to_listing DECIMAL(10,1),
	days_lead_to_processing DECIMAL(10,1),
	is_exclusive SMALLINT,
	first_isales_intervention VARCHAR(50),
	lead_type VARCHAR(255),
	lead_origin VARCHAR(255),
	lead_tracking_source VARCHAR(255),
	lead_tracking_medium VARCHAR(255),
	lead_tracking_platform VARCHAR(255),
	is_branded BOOLEAN,
	is_b2b BOOLEAN,
	is_autonomous_agent BOOLEAN,
	is_doorman BOOLEAN,
	is_isales_direct_register BOOLEAN,
	is_cx_direct_register BOOLEAN,
	is_ops_direct_register BOOLEAN,
	has_isales_intervention BOOLEAN,
	has_fup_photo_task BOOLEAN,
	is_call_center BOOLEAN,
	is_lead_reprocessed BOOLEAN,
	affiliate_type VARCHAR(512),
	is_agent_referral BOOLEAN,
	lead_referring_domain VARCHAR(512),
	lead_referring_category VARCHAR(512),
	subscription_source VARCHAR(512),
	mkt_branded VARCHAR(255),
	mkt_category VARCHAR(255),
	mkt_flow VARCHAR(255),
	mkt_completion VARCHAR(255),
	mkt_origin VARCHAR(255),
	mkt_channel VARCHAR(255),
	mkt_platform VARCHAR(255),
	mkt_medium VARCHAR(255),
	mkt_source VARCHAR(255),
	lead_context_origin VARCHAR(255),
	listing_sale_status VARCHAR(255),
	ts_opted_out_rent TIMESTAMP,
	ts_load TIMESTAMP
)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://dw.s3.data.quintoandar.com.br/public/fact_house_listing_flows'
TBLPROPERTIES (
  'parquet.compress'='SNAPPY')
;
