SELECT
  e.id_expense AS sk_expense,
  e.id_case AS sk_case,
  e.id_invoice,
  e.id_agency,
  e.id_contract,
  e.id_process,
  e.id_stage,
  e.id_attorney,
  e.id_supervisor_attorney,
  e.invoice_description,
  e.stage_description,
  e.action,
  e.expense_type,
  e.expense_subtype,
  e.expense_type_description,
  e.agency_name,
  e.debtor_name,
  e.case_type,
  e.expense_amount,
  e.expense_description,
  e.is_authorized,
  e.is_payment_made,
  e.is_reimbursed,
  e.dt_lauch,
  e.dt_expense_real,
  e.dt_authorized,
  e.dt_reimbursed,
  e.dt_recovered,
  NOW() AS ts_load
FROM
    datalake_cyber_legal.expenses AS e
