SELECT
  eso.id_offer AS sk_offer,
  eso.sale_agreement_status,
  eso.sale_agreement_cancellation_reason,
  eso.sale_price_agreed,
  eso.brokerage_fee,
  eso.fgts_value,
  eso.financing_bank,
  eso.financing_value,
  eso.earnest_value,
  eso.current_payment_method AS payment_method,
  eso.credit_model,
  eso.closing_status,
  eso.house_dilligence_status,
  eso.seller_dilligence_status,
  eso.report_dilligence_status,
  eso.bank_analysis_status,
  eso.payment_status,
  eso.credit_status,
  eso.notary_office_status,
  eso.real_estate_register_office_status,
  eso.has_used_fgts_in_payment,
  eso.has_seller_debt_payments,
  eso.is_ccv_canceled,
  CAST(eso.dt_sale_agreement_signed AS TIMESTAMP) AS ts_sale_agreement_signed,
  CAST(eso.dt_sale_agreement_cancelled AS TIMESTAMP) AS ts_sale_agreement_cancelled,
  CAST(eso.dt_house_registry_started AS TIMESTAMP) AS ts_house_registry_started,
  CAST(eso.dt_house_registry_ended AS TIMESTAMP) AS ts_house_registry_ended,
  CAST(eso.dt_sale_transacton_paid AS TIMESTAMP) AS ts_sale_transaction_paid,
  NOW() AS ts_load
FROM datalake_offer.sale_offer eso
WHERE eso.dt_sale_agreement_signed IS NOT NULL