SELECT
	eso.id_offer AS sk_offer,
	eso.id_sale_flow AS sk_sale_flow,
	eso.id_house AS sk_house,
  	eso.id_buyer AS sk_buyer,
  	eso.id_owner AS sk_owner,
	COALESCE(h.id_region,-1) AS sk_region,
  	COALESCE(eso.id_booking,-1) AS sk_booking,
  	COALESCE(eso.id_agent,-1) AS sk_agent,
  	COALESCE(eso.id_consultant, -1) AS sk_consultant,
  	COALESCE(eso.id_closing_specialist, -1) AS sk_closing_specialist,
	COALESCE(CAST(REPLACE(substring(eso.ts_offer_submitted,1, 10),'-','') AS BIGINT), -1) AS sk_offer_submitted_date,
	COALESCE(CAST(REPLACE(substring(eso.dt_offer_accepted,1, 10),'-','') AS BIGINT), -1) AS sk_offer_accepted_date,
	COALESCE(CAST(REPLACE(substring(eso.dt_offer_dismissed,1, 10),'-','') AS BIGINT), -1) AS sk_offer_dismissed_date,
	COALESCE(CAST(REPLACE(substring(eso.dt_sale_agreement_created,1, 10),'-','') AS BIGINT), -1) AS sk_sale_agreement_created_date,
	COALESCE(CAST(REPLACE(substring(eso.dt_sale_agreement_signed,1, 10),'-','') AS BIGINT), -1) AS sk_sale_agreement_signed_date,
	eso.is_buyer_first_offer,
	eso.is_house_first_offer,
	eso.flg_visit_completed_before_offer AS has_completed_visit_before_offer,
	eso.flg_booking_before_offer AS has_booking_before_offer,
	eso.first_price_offered_by_buyer,
	eso.last_price_offered_by_buyer,
	eso.first_discount_proposed,
	eso.last_discount_proposed,
	eso.days_offer_submitted_to_offer_accepted,
	eso.days_offer_submitted_to_offer_dismissed,
	eso.days_offer_submitted_to_sale_agreement_created,
	eso.days_offer_submitted_to_sale_agreement_signed,
	eso.days_offer_accepted_to_offer_dismissed,
	eso.days_offer_accepted_to_sale_agreement_created,
	eso.days_offer_accepted_to_sale_agreement_signed,
	eso.days_sale_agreement_created_to_sale_agreement_signed,
	eso.hours_booking_to_offer,
	eso.hours_visit_to_offer AS hours_visit_completed_to_offer,
	now() AS ts_load
FROM datalake_offer.sale_offer eso
LEFT JOIN datalake_ebdb_clean.house h
	ON eso.id_house = h.id