SELECT
    13o AS bonus_salary,
    13o1 AS bonus_salary_second_instance,
    acordao AS judgment,
    acordao1 AS judgment_second_instance,
    acordo_em AS agreement_in,
    acordo_sem_vinculo AS no_strings_attached_agreement,
    adicional_de_periculosidade AS hazard_pay,
    adicional_de_periculosidade1 AS hazard_pay_second_instance,
    adicional_noturno AS night_surcharge,
    adicional_noturno1 AS night_surcharge_second_instance,
    aviso_previo AS advance_notice,
    aviso_previo1 AS advance_notice_second_instance,
    cargo_exercido AS position_held,
    comarca AS county,
    desembargador_relator AS judge_rapporteur,
    desvio_de_funcao AS function_desviation,
    desvio_de_funcao1 AS function_desviation_second_instance,
    diferenca_em_comissoes AS commissions_difference,
    diferenca_em_comissoes1 AS commissions_difference_second_instance, 
    duracao_processual AS procedural_duration,
    duracao_processual_ate_sentenca AS procedural_duration_until_sentencing,
    ferias_13 AS vacations,
    ferias_131 AS vacations_second_instance,
    gratificacao_cct AS cct_gratification,
    gratificacao_cct1 AS cct_gratification_second_instance,
    honorarios_sucumbencia AS succumbence_fees,
    honorarios_sucumbencia1 AS succumbence_fees_second_instance,
    hora_extra_8a44a AS overtime_8_44,
    hora_extra_8a44a1 AS overtime_8_44_second_instance,
    hora_extra_intrajornada AS working_hours_overtime,
    hora_extra_intrajornada1 AS working_hours_overtime_second_instance,
    hora_extra_noturna_reduzida AS reduced_nighttime_overtime,
    hora_extra_noturna_reduzida1 AS reduced_nighttime_overtime_second_instance,
    CASE 
        WHEN houve_reversao_da_sentenca = 'Sim' THEN True
        ELSE False
    END AS is_sentence_reverted,
    CASE 
        WHEN houve_reversao_da_sentenca1 = 'Sim' THEN True
        ELSE False
    END AS is_sentence_reverted_second_instance,
    indenizacao_dano_material AS compensation_material_damage,
    indenizacao_dano_material1 AS compensation_material_damage_second_instance,
    indenizacao_dano_moral AS compensation_moral_damage,
    indenizacao_dano_moral1 AS compensation_moral_damage_second_instance,
    indenizacao_estabilidade_gestante AS compensation_pregnant_stability,
    indenizacao_estabilidade_gestante1 AS compensation_pregnant_stability_second_instance,
    juiz AS judge,
    labor_domingos_e_feriados_100 AS sunday_holiday_labor,
    labor_domingos_e_feriados_1001 AS sunday_holiday_labor_second_instance,
    multa_467_clt AS fine_467_clt,
    multa_467_clt1 AS fine_467_clt_second_instance,
    multa_477_clt AS fine_477_clt,
    multa_477_clt1 AS fine_477_clt_second_instance,
    multa_cct AS fine_cct,
    multa_cct1 AS fine_cct_second_instance,
    processo AS judicial_process,
    reconhecimento_de_vinculo_empregaticio AS employment_relationship_recognition,
    reconhecimento_de_vinculo_empregaticio1 AS employment_relationship_recognition_second_instance,
    repeticao_descontos_indevidos AS repeat_undue_discounts,
    repeticao_descontos_indevidos1 AS repeat_undue_discounts_second_instance,
    responsabilidade_deferido_ou_deferido AS joint_or_subsidiary_liability,
    responsabilidade_deferido_ou_deferido1 AS joint_or_subsidiary_liability_second_instance,
    retificacao_ctps AS ctps_retification,
    retificacao_ctps1 AS ctps_retification_second_instance,
    rsr AS rsr,
    rsr1 AS rsr_second_instance,
    salario_minimo_nos_meses_que_nao_houve_pagamento_de_comissoes AS minimum_wage_in_month_without_commissions_payment,
    salario_minimo_nos_meses_que_nao_houve_pagamento_de_comissoes1 AS minimum_wage_in_month_without_commissions_payment_second_instance,
    status,
    segmento AS segment,
    sentenca AS verdict,
    tempo_entre_a_demissao_e_a_distribuicao AS time_between_dismissal_and_distribution,
    tempo_entre_a_demissao_e_a_distribuicao_agrupado AS grouped_time_between_dismissal_and_distribution,
    trt,
    treinamento_obrigatorio_pelo_empregador AS employer_mandatory_training,
    treinamento_obrigatorio_pelo_empregador1 AS employer_mandatory_training_second_instance,
    ranqueamento_de_vendedorescorretores AS seller_broker_ranking,
    ranqueamento_de_vendedorescorretores1 AS seller_broker_ranking_second_instance,
    avaliacoes_pelo_contratante AS appraisals_by_the_contractor,
    avaliacoes_pelo_contratante1 AS appraisals_by_the_contractor_second_instance,
    imposicao_de_metas_de_vendas AS imposing_sales_targets,
    imposicao_de_metas_de_vendas1 AS imposing_sales_targets_second_instance,
    liberdade_para_negociar_comissoes AS freedom_to_negotiate_commissions,
    liberdade_para_negociar_comissoes1 AS freedom_to_negotiate_commissions_second_instance,
    ha_gerenciasupervisao_da_empresa_sobre_o_reclamante AS company_management_over_the_complainant,
    ha_gerenciasupervisao_da_empresa_sobre_o_reclamante1 AS company_management_over_the_complainant_second_instance,
    ha_penalidades_por_faltas_perda_comissao AS penalties_for_fouls,
    ha_penalidades_por_faltas_perda_comissao1 AS penalties_for_fouls_second_instance,
    uso_de_uniformecracha AS wearing_uniform_badge,
    uso_de_uniformecracha1 AS wearing_uniform_badge_second_instance,
    liberdade_de_agenda AS schedule_freedom,
    liberdade_de_agenda1 AS schedule_freedom_second_instance,
    obrigacao_de_comparecimento_em_estande_de_vendas AS obligation_to_attend_the_sales_booth,
    obrigacao_de_comparecimento_em_estande_de_vendas1 AS obligation_to_attend_the_sales_booth_second_instance,
    comissao_paga_em_caso_de_inadimplencia_do_comprador AS commission_paid_in_case_of_buyer_default,
    comissao_paga_em_caso_de_inadimplencia_do_comprador1 AS commission_paid_in_case_of_buyer_default_second_instance,
    creci_depois_do_contrato_de_prestacao_de_servico AS creci_after_the_service_provision,
    creci_depois_do_contrato_de_prestacao_de_servico1 AS creci_after_the_service_provision_second_instance,
    ha_cobranca_de_relatorios_de_vendas AS charge_for_sales_reports,
    ha_cobranca_de_relatorios_de_vendas1 AS charge_for_sales_reports_second_instance,
    registro_do_contrato_de_prestacao_de_servico_no_sindicato AS service_provision_contract_in_the_union,
    registro_do_contrato_de_prestacao_de_servico_no_sindicato1 AS service_provision_contract_in_the_union_second_instance,
    ha_processo_seletivo_de_vendedorescorretores AS selection_process_for_seller_broker,
    ha_processo_seletivo_de_vendedorescorretores1 AS selection_process_for_seller_broker_second_instance,
    ha_aplicacao_de_regras_de_rescisao_trabalhista_no_contrato AS employment_termination_rules_application_in_the_contract,
    ha_aplicacao_de_regras_de_rescisao_trabalhista_no_contrato1 AS employment_termination_rules_application_in_the_contract_second_instance,
    garantia_de_valor_minimo_mensal AS minimum_monthly_guarantee_value,
    garantia_de_valor_minimo_mensal1 AS minimum_monthly_guarantee_value_second_instance,
    segmentos_reclamada AS defendant_segment,
    TO_DATE(SUBSTRING(admissao FROM 0 FOR 11), 'dd MMM yyyy') AS dt_admission,
    TO_DATE(SUBSTRING(demissao FROM 0 FOR 11), 'dd MMM yyyy') AS dt_resignation,
    TO_DATE(SUBSTRING(distribuicao FROM 0 FOR 11), 'dd MMM yyyy') AS dt_distribuition,
    CASE
        WHEN usuario_ativo_na_plataforma = 'Sim' THEN True
        ELSE False
    END AS is_active_platform_user,
    CAST(REPLACE(REPLACE(valor_acao, 'R$', ''), ',', '') AS NUMERIC(10,2)) AS lawsuit_value,
    CAST(valor_condenacao_acordao AS NUMERIC(10,2)) AS condemnation_judgment_value,
    CAST(REPLACE(REPLACE(valor_final_execucao, 'R$', ''), ',', '') AS NUMERIC(10,2)) AS final_execution,
    CAST(valor_sentenca AS NUMERIC(10,2)) AS verdict_value
FROM
    datalake_gsheets_raw.dados_docato