SELECT
    id,
    earning_source_id AS id_earning_source,
    revenue_share_id AS id_revenue_share,
    external_receiver_id AS id_external_receiver,
    GET_JSON_OBJECT(author, "$.id") AS id_author,
    earning_uuid AS uuid_earning,
    external_receiver_type,
    incentive_system,
    calculated_from,
    currency,
    status,
    reason,
    author,
    GET_JSON_OBJECT(author, "$.role") AS author_role,
    GET_JSON_OBJECT(author, "$.channel") AS author_channel,
    GET_JSON_OBJECT(author, "$.on_behalf_of_role") AS author_on_behalf_of_role,
    CAST(revenue_amount AS DOUBLE) AS revenue_amount,
    CAST(revenue_percentage AS DOUBLE) AS revenue_percentage,
    payment_due_date AS dt_payment_due,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated,
    year,
    month,
    day
FROM
    datalake_big_agent_raw.new_earnings