SELECT 
    id_lead AS sk_lead,
    id_user AS sk_user,
    id_visitor_hub_service AS sk_visitor_hub_service,    
    id_classified_lead AS sk_classified_lead,
    id_secretariat_client AS sk_secretariat_client,
    id_region_classified AS sk_region_classified,
    id_region_contact_prospect AS sk_region_contact_prospect,
    id_region_booking_cm AS sk_region_booking_cm,
    id_region_booking_5a AS sk_region_booking_5a, 
    id_region_visit_intent AS sk_region_visit_intent,
    id_first_region AS sk_first_region, 
    id_first_house AS sk_first_house, 
    id_first_house_sale_agreement AS sk_first_house_sale_agreement,
    UPPER(first_touch) AS first_touch,
    first_classified_partner,
    UPPER(first_business_unit_region_intent_lead) AS first_business_unit_region_intent_lead,
    UPPER(last_business_unit_region_intent_lead) AS last_business_unit_region_intent_lead,
    UPPER(first_business_unit_region_new_buyer_prospect) AS first_business_unit_region_new_buyer_prospect,
    UPPER(first_city_booking_cm) AS first_city_booking_cm,
    UPPER(first_city_contact_prospect) AS first_city_contact_prospect,
    UPPER(first_contact_prospect_origin) AS first_contact_prospect_origin,
    UPPER(last_contact_prospect_origin) AS last_contact_prospect_origin,
    UPPER(first_contact_prospect_media) AS first_contact_prospect_media,
    UPPER(last_contact_prospect_media) AS last_contact_prospect_media,
    first_offer_flow,
    first_ccv_flow,
    first_offer_business_unit,
    first_ccv_business_unit,
    UPPER(first_booking_creator_5a) AS first_booking_creator_5a,
    UPPER(further_funnel_step) AS further_funnel_step,
    has_first_booking,
    has_secretariat_contact_created,
    has_booking_before_secretariat_contact,
    has_tenant_rental_contract,
    is_ongoing_tenant_rental_contract,
    has_owner_rental_contract,
    has_rental_visit_intent,
    total_bookings_created_by_secretariat,
    total_bookings_created,
    total_bookings_canceled,
    total_visits_completed_by_secretariat,
    total_visits_completed,
    total_offer_submitted,
    total_sale_agreement_signed,
    days_first_visit_intent_to_first_contact_prospect,
    days_first_visit_intent_to_new_buyer_prospect,
    days_first_visit_intent_to_first_booking_created,
    days_first_visit_intent_to_first_visit_completed,
    days_first_booking_created_to_first_visit_completed,
    days_first_booking_created_to_first_offer_submitted,
    days_first_booking_created_to_first_offer_accepted,
    days_first_booking_created_to_first_sale_agreement_signed,
    days_first_visit_completed_to_first_offer_submitted,
    days_first_visit_completed_to_first_offer_accepted,
    days_first_visit_completed_to_first_sale_agreement_signed,
    days_first_offer_submitted_to_first_offer_accepted,
    days_first_offer_submitted_to_first_sale_agreement_signed,
    days_first_offer_accepted_to_first_sale_agreement_signed,
    ts_first_talk_to_secretariat,
    ts_last_talk_to_secretariat,
    ts_first_visit_lead_intent,
    ts_last_visit_lead_intent,
    ts_first_contact_prospect,
    ts_last_contact_prospect,
    ts_first_classified_intent,
    ts_last_classified_intent,
    ts_first_visit_scheduling_event,
    ts_last_visit_scheduling_event,
    ts_first_tta_message_sent,
    ts_last_tta_message_sent,
    ts_first_booking_created_5a,
    ts_last_booking_created_5a,
    ts_first_visit_completed_5a,
    ts_last_visit_completed_5a,
    ts_first_booking_created_cm,
    ts_last_booking_created_cm,
    ts_first_visit_completed_cm,
    ts_last_visit_completed_cm,
    ts_new_buyer_prospect,
    ts_first_booking_created,
    ts_last_booking_created,
    ts_first_visit_completed,
    ts_last_visit_completed,
    ts_first_offer_submitted,
    ts_last_offer_submitted,
    ts_first_offer_accepted,
    ts_last_offer_accepted,
    ts_first_sale_agreement_signed,
    ts_last_sale_agreement_signed,
    ts_first_combo_event_contact_prospect,
    ts_last_combo_event_contact_prospect
FROM 
    datalake_sale_lead_flows_prod.lead_flow