SELECT
  id,
  external_id AS id_external,
  property_id AS id_property,
  trace_id AS id_trace,
  request_state,
  request_city,
  request_neighborhood,
  request_cep_prefix,
  vespucio_total_hits,
  production_filter_mode,
  hits_with_neighborhood_filter,
  hits_without_neighborhood_filter,
  hit_ids_with_neighborhood,
  hit_ids_without_neighborhood,
  cep_filtered_diverged,
  action_with_neighborhood,
  action_without_neighborhood,
  actions_match,
  async_evaluated,
  async_completed_at AS ts_async_completed,
  ts_decision,
  created_at AS ts_created,
  updated_at AS ts_updated,
  year,
  month,
  day
FROM
  datalake_property_dedup_raw.dedup_contextual_cep_neighborhood_shadow_audit
