SELECT
  id,
  external_id AS id_external,
  property_id AS id_property,
  trace_id AS id_trace,
  complement_raw,
  mode_requested,
  strategy_used,
  fallback_reason,
  legacy_unit,
  legacy_building,
  legacy_empty,
  atlas_unit,
  atlas_building,
  atlas_empty,
  atlas_error,
  components_match,
  primary_total_hits,
  shadow_total_hits,
  search_diverged,
  primary_hit_ids_pre_cep,
  shadow_hit_ids_pre_cep,
  primary_hit_ids_post_cep,
  shadow_hit_ids_post_cep,
  cep_filtered_diverged,
  action_primary,
  action_shadow,
  actions_match,
  async_evaluated,
  async_completed_at AS ts_async_completed,
  ts_decision,
  created_at AS ts_created,
  updated_at AS ts_updated,
  year,
  month,
  day
FROM
  datalake_property_dedup_raw.dedup_complement_parse_audit
