drop table if exists janus.dim_house_listing;
create table if not exists janus.dim_house_listing
(
 sk_house_listing bigint not null,
 sk_autonomous_agent bigint,
 id_house bigint,
 short_id_house bigint,
 version smallint,
 status varchar(256),
 rent numeric(14,2),
 house_rent numeric(14,2),
 house_neighborhood varchar(256),
 house_zipcode varchar(256),
 house_city varchar(256),
 house_complement varchar(256),
 house_condo numeric(14,2),
 house_elevator smallint,
 house_address varchar(256),
 house_iptu numeric(14,2),
 house_lat numeric(14,7),
 house_lng numeric(14,7),
 house_number varchar(256),
 house_bathrooms smallint,
 house_bedrooms smallint,
 house_suites smallint,
 house_garages smallint,
 house_status varchar(256),
 house_type varchar(256),
 house_entrance varchar(256),
 house_garage_type varchar(256),
 house_total_value numeric(14,2),
 house_total_area numeric(14,2),
 house_construction_area numeric(14,2),
 house_condo_type varchar(256),
 house_iptu_type varchar(256),
 registration_abandoned_reason varchar(256),
 house_unpublished_reason varchar(256),
 listing_category_start varchar(256),
 who_is_living varchar(256),
 key_type varchar(256),
 key_location varchar(256),
 house_predicted_price numeric(14,2),
 b2b_type varchar(256),
 b2b_prime_type varchar(256),
 last_originals_type varchar(256),
 last_iorent_type varchar(256),
 sale_price bigint,
 has_visit_restriction boolean,
 has_instant_offer_enabled boolean,
 is_house_furnished boolean,
 is_house_registration_verified boolean,
 is_last_version boolean,
 is_exclusive boolean,
 is_b2b boolean,
 is_autonomous_agent boolean,
 is_originals_active boolean,
 is_iorent_active boolean,
 is_for_rent boolean,
 is_for_sale boolean,
 dt_last_exclusive_opted_in date,
 dt_last_exclusive_opted_out date,
 dt_last_originals_opted_in date,
 dt_last_originals_opted_out date,
 dt_last_iorent_opted_in date,
 dt_last_iorent_opted_out date,
 ts_listing_version_start timestamp,
 ts_listing_version_end timestamp,
 ts_publication timestamp,
 ts_house_first_publication timestamp,
 ts_house_last_publication timestamp,
 ts_last_de_publication timestamp,
 ts_house_create timestamp,
 ts_house_update timestamp,
 ts_load timestamp
);

ALTER TABLE janus.dim_house_listing OWNER TO airflow;
