drop table if exists janus.dim_proposal;
create table janus.dim_proposal (
  sk_proposal integer primary key,
  id_proposal integer,
  guarantee varchar(50),
  status varchar(50),
  tenant_documentation_status varchar(50),
  owner_documentation_status varchar(50),
  rejection_reason varchar(255),
  result_last_credit_evaluation varchar(50),
  sorting_hat_proposal_status varchar(50),
  renting_proposal_value double precision,
  tenant_documentation_sent_count integer,
  credit_evaluation_count integer,
  has_tenant_sent_documentation boolean,
  has_tenant_accepted_contract boolean,
  has_owner_accepted_contract boolean,
  has_owner_sent_documentation boolean,
  is_doc_reused boolean,
  ts_proposal timestamp,
  ts_approved timestamp,
  ts_processed timestamp,
  ts_created timestamp,
  ts_updated timestamp,
  ts_tenant_documentation_sent timestamp,
  ts_owner_documentation_sent timestamp,
  ts_tenant_first_doc_sent timestamp,
  ts_tenant_auto_first_doc_sent timestamp,
  ts_credit_analysis_first_init timestamp,
  ts_credit_analysis_last_init timestamp,
  ts_credit_analysis_first_end timestamp,
  ts_credit_analysis_last_end timestamp,
  ts_credit_approved_last timestamp,
  ts_tenant_first_doc_complete timestamp,
  ts_tenant_last_doc_complete timestamp,
  ts_credit_evaluation_first_init timestamp,
  ts_credit_evaluation_last_init timestamp,
  ts_credit_evaluation_first_negative timestamp,
  ts_credit_evaluation_last_negative timestamp,
  ts_doc_analysis_first_approved timestamp,
  ts_doc_analysis_last_approved timestamp,
  ts_doc_analysis_first_rejected timestamp,
  ts_doc_analysis_last_rejected timestamp,
  ts_proposal_first_credit_evaluation_positive timestamp,
  ts_proposal_last_credit_evaluation_positive timestamp,
  ts_load timestamp
);