DROP TABLE IF EXISTS janus.dim_photo_job;

CREATE TABLE janus.dim_photo_job (
    sk_photo_job bigint primary key,
    id bigint,
    imovel_id bigint,
    rep_id bigint,
    photographer_id bigint,
    user_cancel_id bigint,
    job_status varchar(255),
    creation_origin varchar(20),
    scheduling_instructions varchar,
    photo_shoot_contact_name varchar(255),
    photo_shoot_email varchar(255),
    photo_shoot_phone varchar(20),
    photo_shoot_second_phone varchar(20),
    key_withdraw varchar(255),
    key_comments varchar(255),
    photographer_name varchar(255),
    photographer_email varchar(255),
    photographer_contract_type varchar(255),
    photographer_problem_reason varchar(255),
    user_sender_type varchar(255),
    cancel_reason varchar(255),
    cancel_reason_detailed varchar(512),
    user_cancel_name varchar(255),
    user_cancel_email varchar(255),
    user_cancel_type varchar(255),
    flexible_schedule int,
    approved int,
    confirmed int,
    lockbox int,
    rescheduled boolean,
    is_same_day_upload boolean,
    is_anticipated boolean,
    dt_photographer_accepted datetime,
    dt_job_created datetime,
    dt_job_issued datetime,
    dt_shoot_started datetime,
    dt_job_scheduled datetime,
    dt_photos_uploaded datetime,
    dt_updated datetime,
    dt_problem_reported datetime,
    dt_photographer_start datetime,
    user_cancel_dt datetime,
    creation_to_scheduling_diff_minutes decimal(10,1),
    creation_to_scheduling_diff_hours decimal(10,1),
    creation_to_scheduling_diff_days decimal(10,1)
)

ALTER TABLE janus.dim_photo_job OWNER TO airflow;