drop table if exists janus.dim_offer;
create table janus.dim_offer (
  sk_offer integer primary key,
  id_offer integer,
  id_godfather integer,
  id_firestore varchar(255),
  id_user integer,
  id_property integer,
  editing varchar,
  status varchar,
  rejection_reason varchar(255),
  type varchar(255),
  app_type varchar(255),
  utm_source varchar(255),
  utm_medium varchar(255),
  utm_campaign varchar(2000),
  utm_content varchar(255),
  utm_term varchar(255),
  mkt_category varchar(255),
  mkt_flow varchar(255),
  mkt_completion varchar(255),
  mkt_origin varchar(255),
  mkt_channel varchar(255),
  mkt_medium varchar(255),
  mkt_source varchar(255),
  mkt_platform varchar(255),
  last_offered_rent integer,
  original_rent integer,
  original_condo integer,
  is_instant_offer boolean,
  flg_branded boolean,
  offer_submitted boolean,
  first_rent_offered_by_tenant decimal(18,4),
  first_rent_offered_by_owner decimal(18,4),
  last_rent_offered_by_tenant decimal(18,4),
  last_rent_offered_by_owner decimal(18,4),
  last_updated_date timestamp,
  expiration_date timestamp,
  dt_analysis timestamp,
  dt_first_sent timestamp,
  dt_created timestamp,
  dt_updated timestamp,
  dt_timestamp timestamp
);

ALTER TABLE janus.dim_offer OWNER TO airflow;