drop table if exists janus.dim_region;
create table if not exists janus.dim_region (
  sk_region integer primary key,
  id integer,
  macro_id integer,
  city_id integer,
  level varchar,
  name varchar,
  macro_name varchar,
  city_name varchar,
  city_group varchar,
  city_ddd varchar(2),
  region_code varchar,
  region_code_deprecated varchar,
  region_code_inspector varchar(10),
  short_region_name varchar,
  greater_region varchar,
  regional varchar,
  regional_deprecated varchar,
  regional_inspection varchar,
  tier integer,
  dt_first_booking timestamp,
  dt_first_property_created timestamp,
  dt_created timestamp without time zone,
  dt_updated timestamp without time zone,
  dt_timestamp timestamp without time zone
);