drop table if exists janus.dim_booking;
create table if not exists janus.dim_booking
( 
  sk_booking bigint not null encode az64,
  sk_rent_flow_taxonomy bigint encode az64,
  id_booking bigint encode az64,
  id_visitor bigint encode az64,
  id_visit bigint encode az64,
  id_house bigint encode az64,
  id_agent bigint encode az64,
  id_attendant bigint encode az64,
  id_rent_flow bigint encode az64,
  id_rescheduled_booking bigint encode az64,
  visit_intent varchar(100) encode lzo,
  buyer_intention varchar(100)   encode lzo,
  type varchar(255) encode lzo,
  is_visit_completed boolean,
  is_visit_performed boolean,
  is_closed boolean,
  has_reschedule boolean,
  is_via_reschedule boolean,
  is_branded boolean,
  has_tenant_attended boolean,
  has_agent_attended boolean,
  has_owner_arrived boolean,
  is_entrance_successful boolean,
  is_visit_created_from_app boolean,
  is_visit_last_updated_from_app boolean,
  visit_fup varchar(255) encode lzo,
  status varchar(255) encode lzo,
  slot_day integer encode az64,
  last_status_change_reason varchar(255) encode lzo,
  cancellation_reason varchar(255) encode lzo,
  cancellation_reason_category varchar(255) encode lzo,
  reason_category varchar(255) encode lzo,
  responsible varchar(255) encode lzo,
  last_update_source varchar(255) encode lzo,
  first_update_source varchar(255) encode lzo,
  tenant_absence_reason varchar(255) encode lzo,
  agent_absence_reason varchar(255) encode lzo,
  owner_missing_reason varchar(255) encode lzo,
  troublesome_entrance_problem varchar(255) encode lzo,
  checkin_status varchar(255) encode lzo,
  app_type varchar(255) encode lzo,
  media_source varchar(255) encode lzo,
  adjust_network varchar(255) encode lzo,
  utm_source varchar(255) encode lzo,
  utm_medium varchar(255) encode lzo,
  utm_campaign varchar(2000) encode lzo,
  utm_content varchar(255) encode lzo,
  utm_term varchar(255) encode lzo,
  mkt_category varchar(255) encode lzo,
  mkt_flow varchar(255) encode lzo,
  mkt_completion varchar(255) encode lzo,
  mkt_origin varchar(255) encode lzo,
  mkt_channel varchar(255) encode lzo,
  mkt_medium varchar(255) encode lzo,
  mkt_source varchar(255) encode lzo,
  mkt_platform varchar(255) encode lzo,
  ts_visit_fup timestamp without time zone encode az64,
  ts_visit_follow_up_local_tz timestamp without time zone encode az64,
  ts_booking_utc timestamp without time zone encode az64,
  ts_booking_local_tz timestamp without time zone encode az64,
  ts_first_canceled timestamp without time zone encode az64,
  ts_first_canceled_local_tz timestamp without time zone encode az64,
  ts_created timestamp without time zone encode az64,
  ts_created_local_tz timestamp without time zone encode az64,
  ts_updated timestamp without time zone encode az64,
  ts_load timestamp without time zone encode az64,
  primary key (sk_booking)
)
diststyle key
distkey (sk_booking)
;