DROP TABLE IF EXISTS janus.fact_listing_rent_flows;

CREATE TABLE IF NOT EXISTS janus.fact_listing_rent_flows
(
    ods_id BIGINT ENCODE AZ64,
    sk_house_listing BIGINT ENCODE AZ64,
    sk_region BIGINT ENCODE AZ64,
    sk_condo BIGINT ENCODE AZ64,
    sk_rent_flow BIGINT ENCODE AZ64,
    sk_booking BIGINT ENCODE AZ64,
    sk_tenant_booking_review BIGINT ENCODE AZ64,
    sk_owner BIGINT ENCODE AZ64,
    sk_user_agent BIGINT ENCODE AZ64,
    sk_client BIGINT ENCODE AZ64,
    sk_visit BIGINT ENCODE AZ64,
    sk_offer BIGINT ENCODE AZ64,
    sk_reservation BIGINT ENCODE AZ64,
    sk_proposal BIGINT ENCODE AZ64,
    sk_contract BIGINT ENCODE AZ64,
    sk_rent_flow_taxonomy BIGINT ENCODE AZ64,
    sk_house_first_listing_date BIGINT ENCODE AZ64,
    sk_house_listing_date BIGINT ENCODE AZ64,
    sk_house_listing_de_publication_date BIGINT ENCODE AZ64,
    sk_house_listing_first_offer_submitted_date BIGINT ENCODE AZ64,
    sk_booking_created_date BIGINT ENCODE AZ64,
    sk_visit_date BIGINT ENCODE AZ64,
    sk_agent_sign_up_date BIGINT ENCODE AZ64,
    sk_client_sign_up_date BIGINT ENCODE AZ64,
    sk_offer_submitted_date BIGINT ENCODE AZ64,
    sk_min_offer_submitted_date BIGINT ENCODE AZ64,
    sk_offer_approved_date BIGINT ENCODE AZ64,
    sk_reservation_created_date BIGINT ENCODE AZ64,
    sk_proposal_approved_date BIGINT ENCODE AZ64,
    sk_proposal_processed_date BIGINT ENCODE AZ64,
    sk_tenant_first_doc_sent_date BIGINT ENCODE AZ64,
    sk_tenant_manual_first_doc_sent_date BIGINT ENCODE AZ64,
    sk_tenant_auto_first_doc_sent_date BIGINT ENCODE AZ64,
    sk_tenant_first_doc_complete_date BIGINT ENCODE AZ64,
    sk_tenant_last_doc_complete_date BIGINT ENCODE AZ64,
    sk_tenant_doc_complete_date BIGINT ENCODE AZ64,
    sk_contract_created_date BIGINT ENCODE AZ64,
    sk_contract_signed_date BIGINT ENCODE AZ64,
    sk_contract_annulment_date BIGINT ENCODE AZ64,
    sk_contract_canceled_date BIGINT ENCODE AZ64,
    sk_credit_analysis_first_init_date BIGINT ENCODE AZ64,
    sk_credit_analysis_last_init_date BIGINT ENCODE AZ64,
    sk_credit_analysis_init_date BIGINT ENCODE AZ64,
    sk_credit_analysis_first_end_date BIGINT ENCODE AZ64,
    sk_credit_analysis_last_end_date BIGINT ENCODE AZ64,
    sk_credit_analysis_end_date BIGINT ENCODE AZ64,
    sk_credit_analysis_approved_date BIGINT ENCODE AZ64,
    sk_first_credit_evaluation_init BIGINT ENCODE AZ64,
    sk_last_credit_evaluation_init BIGINT ENCODE AZ64,
    sk_first_credit_evaluation_positive BIGINT ENCODE AZ64,
    sk_last_credit_evaluation_positive BIGINT ENCODE AZ64,
    sk_first_credit_evaluation_negative BIGINT ENCODE AZ64,
    sk_last_credit_evaluation_negative BIGINT ENCODE AZ64,
    sk_guarantee_date BIGINT ENCODE AZ64,
    sk_first_doc_analysis_approved BIGINT ENCODE AZ64,
    sk_last_doc_analysis_approved BIGINT ENCODE AZ64,
    sk_first_doc_analysis_rejected BIGINT ENCODE AZ64,
    sk_last_doc_analysis_rejected BIGINT ENCODE AZ64,
    sk_guarantee_paid_date BIGINT ENCODE AZ64,
    sk_agent_review_rating_date BIGINT ENCODE AZ64,
    visit_created_type VARCHAR(256) ENCODE LZO,
    booking_utm_campaign VARCHAR(2000) ENCODE LZO,
    booking_utm_content VARCHAR(256) ENCODE LZO,
    booking_utm_term VARCHAR(256) ENCODE LZO,
    funnel_step VARCHAR(255) ENCODE LZO,
    funnel_step_drop_reason VARCHAR(255) ENCODE LZO,
    flg_visit_completed BOOLEAN,
    flg_visit_performed BOOLEAN,
    flg_visit_created_from_app BOOLEAN,
    flg_visit_last_updated_from_app BOOLEAN,
    reservation_attempts SMALLINT ENCODE AZ64,
    days_booking_created_to_visit NUMERIC(14,2) ENCODE AZ64,
    days_user_created_to_visit NUMERIC(14,2) ENCODE AZ64,
    days_offer_submitted_to_internal_analysis NUMERIC(14,2) ENCODE AZ64,
    days_offer_approved_to_doc_first_sent NUMERIC(14,2) ENCODE AZ64,
    days_offer_approved_to_owner_doc_sent NUMERIC(14,2) ENCODE AZ64,
    days_first_doc_sent_to_credit_processed NUMERIC(14,2) ENCODE AZ64,
    days_first_doc_sent_to_doc_completed NUMERIC(14,2) ENCODE AZ64,
    days_doc_completed_to_credit_processed NUMERIC(14,2) ENCODE AZ64,
    days_credit_approved_to_contract_created NUMERIC(14,2) ENCODE AZ64,
    days_credit_approved_to_contract_signed NUMERIC(14,2) ENCODE AZ64,
    days_contract_created_to_contract_signed NUMERIC(14,2) ENCODE AZ64,
    days_booking_created_to_contract_signed NUMERIC(14,2) ENCODE AZ64,
    days_visit_to_contract_signed NUMERIC(14,2) ENCODE AZ64,
    days_visit_to_offer_submitted NUMERIC(14,2) ENCODE AZ64,
    days_booking_created_to_offer_submitted NUMERIC(14,2) ENCODE AZ64,
    days_tenant_first_doc_sent_to_insurance_approved NUMERIC(14,2) ENCODE AZ64,
    days_insurance_approved_to_contract_signed NUMERIC(14,2) ENCODE AZ64,
    days_offer_approved_to_tenant_first_doc_sent NUMERIC(14,2) ENCODE AZ64,
    days_offer_submitted_to_offer_approved NUMERIC(14,2) ENCODE AZ64,
    days_offer_approved_to_credit_init NUMERIC(14,2) ENCODE AZ64,
    days_offer_submitted_to_contract_signed NUMERIC(14,2) ENCODE AZ64,
    days_offer_approved_to_contract_signed NUMERIC(14,2) ENCODE AZ64,
    days_tenant_doc_completed_to_credit_approved NUMERIC(14,2) ENCODE AZ64,
    days_tenant_first_doc_sent_to_doc_completed NUMERIC(14,2) ENCODE AZ64,
    days_house_listing_to_contract_signed NUMERIC(14,2) ENCODE AZ64,
    days_house_listing_to_visit NUMERIC(14,2) ENCODE AZ64,
    days_credit_approved_to_closing_processed NUMERIC(14,2) ENCODE AZ64,
    days_offer_approved_to_doc_contact NUMERIC(14,2) ENCODE AZ64,
    ts_load TIMESTAMP ENCODE AZ64
)
DISTSTYLE key
DISTKEY (sk_booking)
;

ALTER TABLE janus.fact_listing_rent_flows OWNER TO databricks;