WITH ranked AS (
    SELECT
        sk_contract,
        sk_invoice,
        user_id,
        sk_pd_rule,
        sk_ead_lgd_rule,
        run_id,
        dt_closing,
        invoice_account_type,
        guarantee_group,
        delay_contamined_range,
        estagio_inicial,
        closing_month_status,
        delay_contaminated_range_rule_e,
        pd_model_name,
        pd_model_version,
        ead_lgd_model_version,
        commit_sha,
        boavista_score_p6__avg,
        loss_given_default,
        probability_of_default,
        sum_due_amount,
        provision_balance_ecl,
        is_early_bird,
        is_guarantee_paid,
        is_ongoing_contract,
        is_automated_run,
        timestamp,
        loaded_at,
        raw_input,
        model_input,
        raw_outputs,
        metadata,
        year,
        month,
        day,
        ROW_NUMBER() OVER (
            PARTITION BY sk_invoice, sk_contract, DATE(dt_closing)
            ORDER BY loaded_at DESC
        ) AS rn
    FROM
        datalake_ifrs_raw.ecl_asset_runs
)
SELECT
    sk_contract AS id_contract,
    sk_invoice AS id_invoice,
    user_id AS id_user,
    sk_pd_rule AS id_pd_rule,
    sk_ead_lgd_rule AS id_ead_lgd_rule,
    run_id AS id_run,
    invoice_account_type,
    guarantee_group,
    delay_contamined_range AS delay_contaminated_range,
    estagio_inicial AS initial_stage,
    closing_month_status,
    delay_contaminated_range_rule_e,
    pd_model_name,
    pd_model_version,
    ead_lgd_model_version,
    commit_sha,
    boavista_score_p6__avg,
    loss_given_default,
    probability_of_default,
    sum_due_amount,
    provision_balance_ecl,
    is_early_bird,
    is_guarantee_paid,
    is_ongoing_contract,
    is_automated_run,
    DATE(dt_closing) AS dt_closing,
    timestamp AS ts_inference,
    loaded_at AS ts_loaded,
    raw_input,
    model_input,
    raw_outputs,
    metadata,
    year,
    month,
    day
FROM
    ranked
WHERE
    rn = 1
