SELECT
    id,
    status_from,
    status_to,
    substatus_from,
    substatus_to,
    reason_category,
    reason,
    additional_context,
  op_cdc,
  ts_cdc_transaction,
  ts_database_transaction
FROM
    datalake_ebdb_raw.HouseListingStatusLog
