select
  links,
  score_factor,
  cast(cast(fluxo_locacao_id as double) as bigint) as fluxo_locacao_id,
  actions,
  data_inicio,
  nome_destinatario,
  realizada_em,
  comentario,
  cast(cast(origem_id as double) as bigint) as origem_id,
  cast(cast(assignee_id as double) as bigint) as assignee_id,
  score,
  origem,
  data_visita,
  type,
  tipo_destinatario,
  descricao,
  fase,
  silenciada_ate,
  cast(cast(imovel_id as double) as bigint) as imovel_id,
  assunto,
  tags,
  cast(cast(opened_by_id as double) as bigint) as opened_by_id,
  cast(cast(inquilino_id as double) as bigint) as inquilino_id,
  data_criacao,
  cast(cast(negociacao_id as double) as bigint) as negociacao_id,
  origem_data,
  cast(cast(gerente_id as double) as bigint) as gerente_id,
  data_fup,
  follow_up_visita,
  metadata,
  cast(cast(v as double) as integer) as v,
  cast(cast(proprietario_id as double) as bigint) as proprietario_id,
  cast(cast(destinatario_id as double) as bigint) as destinatario_id,
  id,
  cast(resolvida as boolean) as resolvida
from datalake_raw.crm_tasks
where dt = '__PARTITION_DATE__'
;