select
  links,
  score_factor,
  cast(fluxo_locacao_id as bigint) as fluxo_locacao_id,
  actions,
  data_inicio,
  nome_destinatario,
  realizada_em,
  comentario,
  cast(origem_id as bigint) as origem_id,
  cast(assignee_id  as bigint) as assignee_id,
  score,
  origem,
  data_visita,
  type,
  tipo_destinatario,
  descricao,
  fase,
  silenciada_ate,
  cast(imovel_id as bigint) as imovel_id,
  assunto,
  tags,
  cast(opened_by_id as bigint) as opened_by_id,
  cast(inquilino_id as bigint) as inquilino_id,
  data_criacao,
  cast(negociacao_id as bigint) as negociacao_id,
  origem_data,
  cast(gerente_id as bigint) as gerente_id,
  data_fup,
  follow_up_visita,
  metadata,
  cast(v as integer) as v,
  cast(proprietario_id as bigint) as proprietario_id,
  cast(destinatario_id as bigint) as destinatario_id,
  id,
  cast(resolvida as boolean) as resolvida
from datalake_raw.crm_tasks
where dt = '__PARTITION_DATE__'
;