DROP TABLE IF EXISTS dim_proposal;
CREATE TABLE dim_proposal (
  sk_proposal INTEGER,
  id_proposal INTEGER,
  dt_proposal TIMESTAMP,
  guarantee VARCHAR(50),
  renting_proposal_value DOUBLE PRECISION,
  status VARCHAR(50),
  dt_proposal_approved TIMESTAMP,
  tenant_document_sent INTEGER,
  dt_tenant_document_sent TIMESTAMP,
  owner_document_sent INTEGER,
  dt_owner_document_sent TIMESTAMP WITHOUT TIME ZONE,
  tenant_contract_accepted INTEGER,
  owner_contract_accepted INTEGER,
  status_doc_tenant VARCHAR(50),
  status_doc_owner VARCHAR(50),
  id_pre_proposal INTEGER,
  tenant_document_sent_count integer,
  dt_created TIMESTAMP,
  dt_updated TIMESTAMP,
  dt_timestamp TIMESTAMP WITHOUT TIME ZONE,
  dt_tenant_first_document_sent TIMESTAMP,
  dt_credit_analysis_init TIMESTAMP,
  dt_credit_analysis_end TIMESTAMP,
  CONSTRAINT dim_proposal_pkey PRIMARY KEY(sk_proposal)
) ;