DROP TABLE IF EXISTS public.dim_contract;
CREATE TABLE public.dim_contract (
  sk_contract INTEGER,
  id_contract INTEGER,
  email_invoice VARCHAR(100),
  renting_value DOUBLE PRECISION,
  property_number INTEGER,
  day_month_due INTEGER,
  guarantee VARCHAR(50),
  contract_type VARCHAR(20),
  contract_status VARCHAR(20),
  dt_calc_affiliate_comission TIMESTAMPTZ,
  dt_calc_agent_comission TIMESTAMPTZ,
  dt_contract_start DATE,
  dt_signature TIMESTAMPTZ,
  dt_draft_approved TIMESTAMPTZ,
  dt_entrance DATE,
  dt_contract_intended_end DATE,
  dt_contract_annulment DATE,
  bank_name VARCHAR(50),
  condo_payer VARCHAR(100),
  iptu_payer VARCHAR(100),
  condo_responsible VARCHAR(100),
  iptu_responsible VARCHAR(100),
  rental_insurance_installments INTEGER,
  rental_insurance_value DOUBLE PRECISION,
  home_insurance_installments INTEGER,
  home_insurance_value DOUBLE PRECISION,
  first_rental_comission DOUBLE PRECISION,
  condo_value DOUBLE PRECISION,
  iptu_value DOUBLE PRECISION,
  signature_type VARCHAR(50),
  dt_send_eletronic_contract TIMESTAMPTZ,
  closing_status VARCHAR(50),
  contract_signed VARCHAR(50),
  contract_administration_signed VARCHAR(50),
  contract_authorization_signed VARCHAR(50),
  contract_renting_signed VARCHAR(50),
  dt_ownership_changed VARCHAR(50),
  dt_created TIMESTAMPTZ,
  dt_updated TIMESTAMPTZ,
  dt_timestamp TIMESTAMPTZ,
  CONSTRAINT dim_contract_pkey PRIMARY KEY(sk_contract)
) ;
