drop table if exists public.dim_external_property;
create table public.dim_external_property (
  sk_external_property bigint not null,
  id bigint not null,
  source varchar(50) not null default 'outro',
  business varchar(200),
  type varchar(50),
  primary_phone_number varchar(20),
  secondary_phone_number varchar(20),
  price decimal(14,2),
  rent decimal(14,2),
  condominium decimal(14,2),
  iptu decimal(16,2),
  total_area decimal(14,2),
  useful_area decimal(14,2),
  bedrooms smallint,
  suites smallint,
  toilets smallint,
  garages smallint,
  year_building smallint,
  cep varchar(20),
  lat decimal(18,7),
  lng decimal(18,7),
  street varchar(200),
  neighborhood varchar(200),
  city varchar(200),
  state varchar(10),
  start_date date,
  end_date date,
  constraint dim_external_property_pkey primary key(sk_external_property, id, source)
);
