drop table if exists public.fact_property_economics;
create table if not exists public.fact_property_economics (
    sk_property bigint not null,
    property_id bigint not null,
    sk_contract bigint not null,
    sk_cash_flow_date bigint not null,
    vl_owner_campaigns double precision,
    vl_affiliate_campaigns double precision,
    vl_inside_sales double precision,
    vl_photos double precision,
    vl_affiliate_bonus double precision,
    vl_lockbox double precision,
    vl_tenant_campaigns double precision,
    vl_cs_pre_sale double precision,
    vl_field_ops double precision,
    vl_bo_pre_sale double precision,
    vl_agent_hours double precision,
    vl_st_pis_cofins double precision,
    vl_st_iss double precision,
    vl_affiliate_commission double precision,
    vl_agent_commission double precision,
    vl_delay_fine double precision,
    vl_termination_fine double precision,
    vl_brokerage_fee double precision,
    vl_management_fee double precision,
    vl_cs_post_sale double precision,
    vl_collection double precision,
    vl_bo_onboarding double precision,
    vl_bo_ongoing double precision,
    vl_bo_offboarding double precision,
    vl_insurance_fee double precision
);
