drop table if exists fact_liquidity_property_scheduling;
create table fact_liquidity_property_scheduling (
  ods_id bigint,
  sk_property bigint,
  sk_region bigint,
  listing_number integer,
  sk_booking integer,
  sk_owner integer,
  sk_user_affiliate integer,
  sk_user_agent integer,
  sk_user_visitor integer,
  sk_user_visit_agent integer,
  sk_visit integer,
  sk_negotiation integer,
  sk_offer integer,
  sk_proposal integer,
  sk_contract integer,
  id_rental_flow integer,
  sk_first_listing_date integer,
  sk_listing_date integer,
  sk_booking_created_date integer,
  sk_visit_date integer,
  sk_visitor_user_signup_date integer,
  sk_offer_created_date integer,
  sk_contract_signed_date integer,
  sk_user_agent_date integer,
  dt_contract_anullment date,
  visit_created_from_app integer,
  visit_created_type varchar(14),
  visit_last_updated_from_app integer,
  visit_last_updated_type varchar(14),
  initial_source varchar(100),
  initial_medium varchar(100),
  initial_campaign varchar(200),
  initial_referring_domain varchar(200),
  source varchar(100),
  medium varchar(100),
  campaign varchar(200),
  referring_domain varchar(200),
  vl_cost_marketing_campaigns numeric(14,4),
  vl_cost_marketing_ads numeric(14,4),
  vl_cost_marketing_sms numeric(14,4),
  vl_cost_agents_comission numeric(14,4),
  vl_cost_agents_slot numeric(14,4),
  vl_cost_visit_support numeric(14,4),
  vl_cost_closing_support numeric(14,4),
  vl_cost_classifieds numeric(14,4),
  dt_timestamp timestamp without time zone,
  booking_to_visit numeric(14,4),
  offer_to_internal_analyis numeric(14,4),
  offer_to_credit_analysis_init_date numeric(14,4),
  credit_analysis_init_to_end numeric(14,4),
  credit_analysis_to_contract numeric(14,4)
) with oids
;
