SELECT
    CAST(codigo_proposta AS BIGINT) AS id_proposal,
    CAST(codigo_operacao AS BIGINT) AS id_operation,
    CAST(log_id_proposta AS BIGINT) AS id_proposal_log,
    prop_dom_alcada_usuario AS prop_dom_competence_user,
    calc_status AS calc_status,
    calc_tipo_pessoa AS calc_person_type,
    prop_ffp_campo12 AS proposal_type,
    ret_rf_rua AS ret_rf_street,
    log_resultado AS log_result,
    nome_politica AS policy_name,
    CAST(prop_business_unit_uid AS DECIMAL(15,1)) AS proposal_business_unit_uid,
    calc_valor_aprovado AS status_approved_value,
    reflect('java.net.URLDecoder','decode', calc_motivos , 'utf-8') AS status_motives,
    prop_ffp_campo11 AS proposal_rating,
    calc_status_decisao AS status_decision,
    calc_erro AS status_error,
    calc_id_operacao AS status_id_operation,
    calc_rfpj_municipio AS status_rfpj_state,
    vi_upload_usuario AS vi_upload_user,
    versao_politica AS policy_version,
    calc_motivo AS status_motive,
    calc_exception_callback AS status_exception_callback,
    calc_tipo_processo AS status_process_type,
    calc_mesa_fila AS status_credit_team_queue,
    calc_note AS status_note,
    log_usuario AS log_user,
    calc_doc_aprov AS status_doc_approval,
    calc_comp_pend AS status_comp_pending,
    calc_observacao AS status_observation,
    prop_cod_operacao AS cod_operation,
    CAST(prop_ffp_campo6 AS BIGINT) AS proposal_number,
    calc_stat AS status,
    calc_request_test AS status_request_test,
    prop_tipo_documento AS proposal_document_type,
    calc_doc_reprov AS calc_doc_reproof,
    prop_ffp_campo13 AS proposal_realestate,
    prop_ffp_nome AS proposal_name,
    calc_motivo_comprov_negado AS status_motive_receipt_denied,
    prop_ffp_tipo_contribuinte AS proposal_contributor_type,
    flx_principal AS flx_principal,
    politica AS policy,
    prop_fma_parecer_documento AS proposal_fma_decision_document,
    prop_fma_motivos AS proposal_fma_motives,
    case_alcada_decisao AS case_competence_decision,
    calc_docs AS status_docs,
    CAST(REPLACE(calc_dti_maximo, '%') AS INT)/100 AS status_dti_max_percentage,
    CAST(IF(prop_resubmissao="S", TRUE, FALSE) AS BOOLEAN) AS is_resubmission,
    TO_TIMESTAMP(REPLACE(prop_ffp_dh_cadastro, '.000', ''), 'dd/MM/yyyy HH:mm:ss z') AS ts_proposal_dh_registration,
    TO_TIMESTAMP(log_dh_inicio, 'yyyy-MM-dd HH:mm:ss') AS ts_dh_start,
    TO_TIMESTAMP(log_dh_processamento, 'yyyy-MM-dd HH:mm:ss') AS ts_dh_processing,
    TO_TIMESTAMP(log_dh_fim, 'yyyy-MM-dd HH:mm:ss') AS ts_dh_end,
    TO_TIMESTAMP(REPLACE(instante, '.000', ''), 'yyyy-MM-dd HH:mm:ss') AS ts_operation,
    year AS year,
    month AS month,
    day AS day
FROM
    datalake_velo_neurotech_homolog_raw.logs_scoping_policy
