SELECT
    BIGINT(ID_Lead) AS id_lead,
    BIGINT(McxCampaignId) AS id_campaign,
    Link AS link,
    Origem AS origin,
    bairro AS neighbourhood,
    cep AS zipcode,
    cidade AS city,
    endereco AS address,
    nomeAnunciante AS advertiser_name,
    telefone1 AS phone1,
    telefone2 AS phone2,
    telefone3 AS phone3,
    telefoneAnunciante AS advertiser_phone,
    telefoneformated AS phone_formatted,
    Canal AS channel,
    tablename AS table_name,
    Categoria AS category,
    Coringa_1 AS joker_1,
    Coringa_2 AS joker_2,
    Coringa_3 AS joker_3,
    Coringa_4 AS joker_4,
    Coringa_5 AS joker_5,
    Coringa_6 AS joker_6,
    Coringa_7 AS joker_7,
    Coringa_8 AS joker_8,
    Coringa_9 AS joker_9,
    Coringa_10 AS joker_10,
    Coringa_11 AS joker_11,
    Coringa_12 AS joker_12,
    Coringa_13 AS joker_13,
    Coringa_14 AS joker_14,
    Coringa_15 AS joker_15,
    Coringa_16 AS joker_16,
    Coringa_17 AS joker_17,
    Coringa_18 AS joker_18,
    Coringa_19 AS joker_19,
    Coringa_20 AS joker_20,
    Coringa_21 AS joker_21,
    Coringa_22 AS joker_22,
    Coringa_23 AS joker_23,
    Coringa_24 AS joker_24,
    Coringa_25 AS joker_25,
    Coringa_26 AS joker_26,
    Coringa_27 AS joker_27,
    Coringa_28 AS joker_28,
    Coringa_29 AS joker_29,
    Coringa_30 AS joker_30,
    Coringa_31 AS joker_31,
    Coringa_32 AS joker_32,
    Coringa_33 AS joker_33,
    Coringa_34 AS joker_34,
    Coringa_35 AS joker_35,
    Coringa_36 AS joker_36,
    Coringa_37 AS joker_37,
    Coringa_38R AS joker_38r,
    Coringa_39 AS joker_39,
    Coringa_40 AS joker_40,
    TIMESTAMP(DataCriacao) AS ts_created,
    TIMESTAMP(DateImport) AS ts_imported,
    year,
    month,
    day
FROM datalake_olos_dialer_test_raw.OPS_Mailing_LayoutId_4
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')