SELECT
    id,
    rev,
    revtype,
    negotiation_id AS id_negotiation,
    finance_entity_id AS id_finance_entity,
    channel,
    domain,
    total_amount,
    principal_amount,
    fine_amount,
    interest_amount,
    reversed_discount_amounts,
    residual_amounts,
    additional_charges_amounts,
    due_date AS dt_due,
    negotiation_id_mod AS mod_id_negotiation,
    finance_entity_id_mod AS mod_id_finance_entity,
    channel_mod AS mod_channel,
    domain_mod AS mod_domain,
    total_amount_mod AS mod_total_amount,
    principal_amount_mod AS mod_principal_amount,
    fine_amount_mod AS mod_fine_amount,
    interest_amount_mod AS mod_interest_amount,
    reversed_discount_amounts_mod AS mod_reversed_discount_amounts,
    residual_amounts_mod AS mod_residual_amounts,
    additional_charges_amounts_mod AS mod_additional_charges_amounts,
    due_date_mod AS mod_dt_due,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_negotiation_raw.break_bill_aud
