SELECT
    id,
    negotiation_id AS id_negotiation,
    finance_entity_id AS id_finance_entity,
    uuid AS uuid_installment,
    rev,
    revtype,
    installment_number,
    status,
    grace_period_days,
    total_amount,
    principal_amount,
    fine_amount,
    interest_amount,
    discount_amounts,
    residual_amounts,
    additional_charges_amounts,
    due_date AS dt_due,
    uuid_mod AS mod_uuid_installment,
    negotiation_id_mod AS mod_id_negotiation,
    finance_entity_id_mod AS mod_id_finance_entity,
    installment_number_mod AS mod_installment_number,
    status_mod AS mod_status,
    grace_period_days_mod AS mod_grace_period_days,
    total_amount_mod AS mod_total_amount,
    principal_amount_mod AS mod_principal_amount,
    fine_amount_mod AS mod_fine_amount,
    interest_amount_mod AS mod_interest_amount,
    discount_amounts_mod AS mod_discount_amounts,
    residual_amounts_mod AS mod_residual_amounts,
    additional_charges_amounts_mod AS mod_additional_charges_amounts,
    due_date_mod AS mod_dt_due,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_negotiation_raw.installment_aud
