SELECT
    id,
    negotiation_id AS id_negotiation,
    rev,
    revtype,
    source_key,
    source_type,
    installment_interval,
    number_of_installments,
    down_payment_percentage,
    down_payment,
    total_amount,
    principal_amount,
    discount_amount,
    discount_on_interest_percentage,
    discount_on_fine_percentage,
    discount_on_principal_amount_percentage,
    discount_on_additional_charges_percentage,
    fine_amount,
    interest_amount,
    residual_amount,
    additional_charges_amount,
    negotiation_id_mod AS mod_id_negotiation,
    source_key_mod AS mod_source_key,
    source_type_mod AS mod_source_type,
    installment_interval_mod AS mod_installment_interval,
    number_of_installments_mod AS mod_number_of_installments,
    down_payment_percentage_mod AS mod_down_payment_percentage,
    down_payment_mod AS mod_down_payment,
    total_amount_mod AS mod_total_amount,
    principal_amount_mod AS mod_principal_amount,
    discount_amount_mod AS mod_discount_amount,
    discount_on_interest_percentage_mod AS mod_discount_on_interest_percentage,
    discount_on_fine_percentage_mod AS mod_discount_on_fine_percentage,
    discount_on_principal_amount_percentage_mod AS mod_discount_on_principal_amount_percentage,
    discount_on_additional_charges_percentage_mod AS mod_discount_on_additional_charges_percentage,
    fine_amount_mod AS mod_fine_amount,
    interest_amount_mod AS mod_interest_amount,
    residual_amount_mod AS mod_residual_amount,
    additional_charges_amount_mod AS mod_additional_charges_amount,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_negotiation_raw.negotiation_condition_aud
