SELECT
    INT(id) AS id_post_wordpress,
    INT(author) AS id_author,
    guid,
    slug,
    title,
    wps_subtitle,
    categories,
    tags,
    acf,
    acf:funil AS acf_funnel,
    acf:tipo_de_usuario AS acf_user_type,
    acf:leia_tambem_title AS acf_read_also_title,
    acf:leia_tambem_filter_tag AS acf_read_also_filter_tag,
    acf:custom_author AS acf_custom_author,
    tax_additional,
    status,
    type,
    link,
    author_meta,
    coauthors,
    featured_media,
    comment_status,
    ping_status,
    sticky,
    template,
    format,
    meta,
    featured_img,
    featured_img_caption,
    comment_count,
    slug_history,
    _links AS other_links,
    content,
    DATE(date) AS dt_post_created,
    DATE(date_gmt) AS dt_gmt_post_created,
    DATE(modified) AS dt_post_modified,
    DATE(modified_gmt) AS dt_gmt_post_modified,
    year,
    month,
    day
FROM
    datalake_wordpress_baroes_raw.meulugar_data
WHERE
    DATE(modified) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')