SELECT
  response.numero_guia AS guide_number,
  response.numero_protocolo AS protocol_number,
  response.numero_certidao AS certificate_number,
  response.numero_autenticacao AS authentication_number,
  response.inscricao_imobiliaria AS municipal_registration,
  response.inscricao_imobiliaria AS id_municipal_house,
  'RJ' AS state,
  'Rio de Janeiro' AS city,
  TRIM(REGEXP_EXTRACT(response.endereco_imovel, '^([^,]+)', 1)) AS street,
  TRIM(REGEXP_EXTRACT(response.endereco_imovel, ',\\s*([^/\\-]+)', 1)) AS address_number,
  TRIM(REGEXP_EXTRACT(response.endereco_imovel, '/\\s*([^\\-]+)', 1)) AS address_details,
  TRIM(REGEXP_EXTRACT(response.endereco_imovel, '-\\s*(.+)$', 1)) AS neighborhood,
  response.natureza_transacao AS transaction_nature,
  response.endereco_imovel AS property_address,
  response.parte_transferida AS transferred_share,
  response.parcela AS installment,
  CAST(response.valor_declarado AS DOUBLE) AS declared_value,
  CAST(response.valor_declarado AS DOUBLE) AS assessed_itbi_value,
  CAST(response.base_calculo AS DOUBLE) AS calculation_base,
  CAST(response.valor_total_devido AS DOUBLE) AS total_amount_due,
  CAST(response.valor_total_pago AS DOUBLE) AS total_amount_paid,
  response.data_vencimento AS due_date,
  response.data_pagamento AS payment_date,
  response.adquirente AS buyer_name,
  response.transmitente AS seller_name,
  response.folha_suplementar AS supplementary_page,
  response.observacao AS observation,
  metadata.source AS feed_source,
  metadata.url AS feed_url,
  metadata.accessed_at AS ts_accessed,
  metadata.referer_url AS referer_url,
  crawler_name,
  dt_load,
  year,
  month,
  day
FROM
  datalake_crawled_idactum_houses_raw.rj_itbi_main
