SELECT
  COALESCE(response.inscricao_cadastral, response.cdc) AS id_municipal_house,
  response.inscricao_cadastral AS municipal_inscription,
  response.cdc AS cdc,
  'SP' AS state,
  'Osasco' AS city,
  CAST(NULL AS STRING) AS real_estate_register,
  CAST(response.valor_pago AS DOUBLE) AS assessed_itbi_value,
  CAST(NULL AS DOUBLE) AS assessed_iptu_value,
  CAST(NULL AS DOUBLE) AS building_assessed_value,
  CAST(NULL AS STRING) AS transaction_nature,
  CAST(NULL AS STRING) AS owner_name,
  response.adquirente AS buyer_name,
  response.situacao AS payment_status,
  metadata.source AS feed_source,
  metadata.url AS feed_url,
  metadata.accessed_at AS ts_accessed,
  metadata.referer_url AS referer_url,
  crawler_name,
  dt_load,
  year,
  month,
  day
FROM
  datalake_crawled_idactum_houses_raw.sp_osasco_itbi
