DROP TABLE IF EXISTS sale.dim_sale_agreement;
CREATE TABLE sale.dim_sale_agreement (
    sk_offer VARCHAR PRIMARY KEY,
    pendency VARCHAR,
    pendency_type VARCHAR,
    opportunities_of_the_week VARCHAR,
    sale_agreement_status VARCHAR,
    offer_flow VARCHAR,
    business_unit VARCHAR,
    sale_agreement_cancellation_reason VARCHAR,
    sale_price_agreed FLOAT,
    brokerage_fee FLOAT,
    fgts_value BIGINT,
    financing_bank VARCHAR,
    financing_value BIGINT,
    earnest_value BIGINT,
    down_payment_amount BIGINT,
    payment_method VARCHAR,
    payment_model VARCHAR,
    credit_model VARCHAR,
    early_keys_status VARCHAR,
    closing_status VARCHAR,
    house_dilligence_status VARCHAR,
    seller_dilligence_status VARCHAR,
    report_dilligence_status VARCHAR,
    diligence_appointment_reason VARCHAR(500),
    bank_analysis_status VARCHAR,
    payment_status VARCHAR,
    credit_status VARCHAR,
    notary_office_status VARCHAR,
    real_estate_register_office_status VARCHAR,
    tags_from_salesflow VARCHAR,
    has_used_fgts_in_payment BOOLEAN,
    has_seller_debt_payments BOOLEAN,
    is_ccv_canceled BOOLEAN,
    ts_sale_agreement_signed TIMESTAMP,
    ts_sale_agreement_cancelled TIMESTAMP,
    ts_house_registry_started TIMESTAMP,
    ts_house_registry_ended TIMESTAMP,
    ts_sale_transaction_paid TIMESTAMP,
    ts_last_updated_pendency TIMESTAMP,
    ts_load TIMESTAMP
);
ALTER TABLE sale.dim_sale_agreement OWNER TO airflow;
