DROP TABLE IF EXISTS sale.dim_offer;
CREATE TABLE sale.dim_offer (
	sk_offer VARCHAR PRIMARY KEY,
	monday_status VARCHAR,
	offer_status VARCHAR,
	drop_reason VARCHAR,
	drop_reason_responsible VARCHAR,
	payment_method VARCHAR,
	business_unit VARCHAR,
	offer_platform VARCHAR,
	offer_flow VARCHAR,
	agent_work_contract VARCHAR,
	team_lead_name VARCHAR,
	deal_maker_name VARCHAR,
	agent_name VARCHAR,
	sale_price BIGINT,
	registry_price BIGINT,
	itbi_price BIGINT,
	payment_entry_amount BIGINT,
	app_type VARCHAR,
	utm_source VARCHAR,
	utm_medium VARCHAR,
	utm_campaign VARCHAR,
	mkt_category VARCHAR,
	mkt_flow VARCHAR,
	mkt_completion VARCHAR,
	mkt_origin VARCHAR,
	mkt_channel VARCHAR,
	mkt_medium VARCHAR,
	mkt_source VARCHAR,
	mkt_platform VARCHAR,
	is_branded BOOLEAN,
	has_used_fgts_in_payment BOOLEAN,
	has_used_negotiation_chat BOOLEAN,
	ts_offer_submitted TIMESTAMP,
	ts_updated TIMESTAMP,
	ts_load TIMESTAMP
);
ALTER TABLE sale.dim_offer OWNER TO airflow;