DROP TABLE IF EXISTS sale.fact_sale_flows;
CREATE TABLE sale.fact_sale_flows (
  sk_sale_flow VARCHAR PRIMARY KEY,
  sk_buyer BIGINT,
  sk_house BIGINT,
  sk_seller BIGINT,
  sk_region BIGINT,
  --
  sk_first_listing_date BIGINT,
  sk_first_event_date BIGINT,
  sk_first_tta_message_sent_date BIGINT,
  sk_first_booking_created_date BIGINT,
  sk_first_visit_completed_date BIGINT,
  sk_first_offer_submitted_date BIGINT,
  sk_first_offer_accepted_date BIGINT,
  sk_first_offer_dismissed_date BIGINT,
  sk_sale_agreement_created_date BIGINT,
  sk_sale_agreement_signed_date BIGINT,
  sk_sale_agreement_cancelled_date BIGINT,
  sk_house_registry_ended_date BIGINT,
  --
  first_event VARCHAR,
  higher_intent_before_offer VARCHAR,
  higher_intent_after_offer VARCHAR,
  rank_buyer_sale_flow INTEGER,
  rank_house_sale_flow INTEGER,
  is_buyer_first_sale_flow BOOLEAN,
  is_house_first_sale_flow BOOLEAN,
  flow_type VARCHAR,
  max_discount_proposed FLOAT,
  --
  bookings BIGINT,
  visits_completed BIGINT,
  offers_submitted BIGINT,
  tta_messages_sent BIGINT,
  --
  days_first_publication_to_first_event INTEGER,
  days_first_publication_to_first_booking_created INTEGER,
  days_first_publication_to_first_visit_completed INTEGER,
  days_first_publication_to_first_offer_submitted INTEGER,
  days_first_publication_to_first_offer_accepted INTEGER,
  days_first_publication_to_sale_agreement_signed INTEGER,
  days_first_publication_to_house_registry_ended INTEGER,
  days_first_event_to_first_visit_completed INTEGER,
  days_first_event_to_first_offer_submitted INTEGER,
  days_first_event_to_first_offer_accepted INTEGER,
  days_first_event_to_sale_agreement_signed INTEGER,
  days_first_event_to_house_registry_ended INTEGER,
  days_first_booking_created_to_first_visit_completed INTEGER,
  days_first_booking_created_to_first_offer_submitted INTEGER,
  days_first_booking_created_to_first_offer_accepted INTEGER,
  days_first_booking_created_to_sale_agreement_signed INTEGER,
  days_first_booking_created_to_house_registry_ended INTEGER,
  days_first_visit_completed_to_first_offer_submitted INTEGER,
  days_first_visit_completed_to_first_offer_accepted INTEGER,
  days_first_visit_completed_to_sale_agreement_signed INTEGER,
  days_first_visit_completed_to_house_registry_ended INTEGER,
  days_first_offer_submitted_to_first_offer_accepted INTEGER,
  days_first_offer_submitted_to_sale_agreement_signed INTEGER,
  days_first_offer_accepted_to_sale_agreement_signed INTEGER,
  days_first_offer_submitted_to_house_registry_ended INTEGER,
  --
  app_type VARCHAR,
  utm_source VARCHAR,
  utm_medium VARCHAR,
  utm_campaign VARCHAR,
  is_branded BOOLEAN,
  mkt_category VARCHAR,
  mkt_flow VARCHAR,
  mkt_completion VARCHAR,
  mkt_origin VARCHAR,
  mkt_channel VARCHAR,
  mkt_medium VARCHAR,
  mkt_source VARCHAR,
  mkt_platform VARCHAR,
  ts_load TIMESTAMP
  )
;

ALTER TABLE sale.fact_sale_flows OWNER TO airflow;
