DROP TABLE IF EXISTS sale.fact_closing_flows;
CREATE TABLE sale.fact_closing_flows (
  sk_offer VARCHAR PRIMARY KEY,
  sk_buyer BIGINT,
  sk_owner BIGINT,
  sk_house BIGINT,
  sk_sale_agreement_signed_date BIGINT,
  sk_onboarding_ended_date BIGINT,
  sk_sale_agreement_cancelled_date BIGINT,
  sk_legal_analysis_ended_date BIGINT,
  sk_legaut_analysis_started_date BIGINT,
  sk_legaut_analysis_ended_date BIGINT,
  sk_legal_risk_started_date BIGINT,
  sk_legal_risk_ended_date BIGINT,
  sk_bank_legal_analysis_started BIGINT,
  sk_credit_analysis_started_date BIGINT,
  sk_credit_analysis_ended_date BIGINT,
  sk_financing_started_date BIGINT,
  sk_financing_ended_date BIGINT,
  sk_notes_registry_started_date BIGINT,
  sk_notes_registry_ended_date BIGINT,
  sk_house_registry_started_date BIGINT,
  sk_house_registry_ended_date BIGINT,
  sk_sale_key_delivered_date BIGINT,
  sk_sale_transaction_paid_date BIGINT,
  --
  id_closing_specialist VARCHAR,
  id_legal_risk_analyst VARCHAR,
  id_pre_specialist VARCHAR,
  id_post_specialist VARCHAR,
  id_start_financing_specialist VARCHAR,
  id_follow_up_financing_specialist VARCHAR,
  id_end_financing_specialist VARCHAR,
  id_credit_specialist VARCHAR,
  id_notes_registry_specialist VARCHAR,
  id_real_estate_register_specialist VARCHAR,
  --
  days_sale_agreement_signed_to_house_registry_started INTEGER,
  days_sale_agreement_signed_to_house_registry_ended INTEGER,
  days_sale_agreement_signed_to_sale_agreement_cancelled INTEGER,
  days_sale_agreement_signed_to_onboarding_ended INTEGER,
  days_sale_agreement_signed_to_credit_analysis_started INTEGER,
  days_sale_agreement_signed_to_credit_analysis_ended INTEGER,
  days_sale_agreement_signed_to_financing_started INTEGER,
  days_sale_agreement_signed_to_notes_registry_started INTEGER,
  days_sale_agreement_signed_to_notes_registry_ended INTEGER,
  days_sale_agreement_signed_to_legaut_analysis_started INTEGER,
  days_sale_agreement_signed_to_legaut_analysis_ended INTEGER,
  days_sale_agreement_signed_to_legal_risk_ended INTEGER,
  days_sale_agreement_signed_to_bank_legal_analysis_started INTEGER,
  days_legal_risk_started_to_legal_risk_ended INTEGER,
  days_legal_risk_ended_to_legal_analysis_ended INTEGER,
  days_legaut_analysis_started_to_legaut_analysis_ended INTEGER,
  days_legaut_analysis_ended_to_legal_risk_ended INTEGER,
  days_legal_analysis_ended_notes_registry_ended INTEGER,
  days_legal_analysis_ended_to_bank_legal_analysis_started INTEGER,
  days_bank_legal_analysis_started_to_financing_ended INTEGER,
  days_bank_legal_analysis_started_to_house_registry_started INTEGER,
  days_credit_analysis_started_to_credit_analysis_ended INTEGER,
  days_credit_analysis_ended_to_bank_legal_analysis_started INTEGER,
  days_financing_started_to_financing_ended INTEGER,
  days_financing_ended_to_house_registry_ended INTEGER,
  days_financing_ended_to_house_registry_started INTEGER,
  days_notes_registry_started_to_notes_registry_ended INTEGER,
  days_house_registry_started_to_house_registry_ended INTEGER,
  days_notes_registry_ended_to_house_registry_started INTEGER,
  days_notes_registry_ended_to_house_registry_ended INTEGER,
  days_house_registry_ended_to_sale_key_delivered INTEGER,
  days_house_registry_ended_to_sale_transaction_paid INTEGER,
  --
  ts_updated TIMESTAMP,
  ts_monday_load TIMESTAMP,
  ts_load TIMESTAMP
  );

ALTER TABLE sale.fact_closing_flows OWNER TO airflow;
