DROP TABLE IF EXISTS sale.fact_visits;
CREATE TABLE sale.fact_visits (
    sk_booking BIGINT PRIMARY KEY,
    sk_sale_flow VARCHAR,
    sk_house BIGINT,
    sk_region BIGINT,
    sk_agent BIGINT,
    sk_user_agent BIGINT,
    sk_fixed_agent BIGINT,
    sk_buyer BIGINT,
    sk_seller BIGINT,
    sk_user_creation BIGINT,
    sk_user_cancelation BIGINT,
    sk_visit BIGINT,
    sk_visit_code VARCHAR,
    sk_offer VARCHAR,
    sk_agent_booking_review BIGINT,
    sk_buyer_booking_review BIGINT,
    sk_booking_created_date BIGINT,
    sk_visit_date BIGINT,
    sk_visit_canceled_date BIGINT,
    sk_visit_completed_date BIGINT,
    sk_visit_follow_up_date BIGINT,
    sk_agent_review_rating_date BIGINT,
    sk_buyer_review_rating_date BIGINT,
    is_hub_flow BOOLEAN,
    is_house_rented BOOLEAN,
    is_virtual_visit BOOLEAN,
    days_visit_booked_to_visit_cancelled INTEGER,
    days_visit_cancelled_to_visit INTEGER,
    days_visit_booked_to_visit INTEGER,
    days_visit_booked_to_visit_completed INTEGER,
    hours_booking_to_offer FLOAT,
    hours_visit_to_offer FLOAT,
    ts_load TIMESTAMP
);
ALTER TABLE sale.fact_visits OWNER TO airflow;
