DROP TABLE IF EXISTS sale.fact_offers;
CREATE TABLE sale.fact_offers (
	sk_offer VARCHAR PRIMARY KEY,
	sk_sale_flow VARCHAR,
	sk_house BIGINT,
	sk_buyer BIGINT,
	sk_owner BIGINT,
	sk_region BIGINT,
	sk_booking BIGINT,
	sk_agent BIGINT,
	sk_consultant VARCHAR,
	sk_closing_specialist BIGINT,
	sk_offer_submitted_date BIGINT,
	sk_offer_accepted_date BIGINT,
	sk_offer_dismissed_date BIGINT,
	sk_sale_agreement_created_date BIGINT,
	sk_sale_agreement_signed_date BIGINT,
	is_buyer_first_offer BOOLEAN,
	is_house_first_offer BOOLEAN,
	has_completed_visit_before_offer BOOLEAN,
	has_booking_before_offer BOOLEAN,
	first_price_offered_by_buyer BIGINT,
	last_price_offered_by_buyer BIGINT,
	first_discount_proposed FLOAT,
	last_discount_proposed FLOAT,
	days_offer_submitted_to_offer_accepted INTEGER,
	days_offer_submitted_to_offer_dismissed INTEGER,
	days_offer_submitted_to_sale_agreement_created INTEGER,
	days_offer_submitted_to_sale_agreement_signed INTEGER,
	days_offer_accepted_to_offer_dismissed INTEGER,
	days_offer_accepted_to_sale_agreement_created INTEGER,
	days_offer_accepted_to_sale_agreement_signed INTEGER,
	days_sale_agreement_created_to_sale_agreement_signed INTEGER,
	hours_booking_to_offer FLOAT,
	hours_visit_completed_to_offer FLOAT,
	ts_load TIMESTAMP
);
ALTER TABLE sale.fact_offers OWNER TO airflow;