DROP TABLE IF EXISTS sale.fact_listings;
CREATE TABLE sale.fact_listings (
	sk_sale_listing BIGINT PRIMARY KEY,
	sk_house BIGINT,
	sk_owner BIGINT,
	sk_region BIGINT,
	price BIGINT,
	price_m2 FLOAT,
	sk_first_publication_date BIGINT,
	sk_last_publication_date BIGINT,
	sk_first_depublication_date BIGINT,
	sk_last_depublication_date BIGINT,
	sk_first_visit_completed BIGINT,
	sk_first_offer_submitted_date BIGINT,
	sk_first_offer_accepted BIGINT,
	days_last_publication_to_depublication BIGINT,
	days_first_publication_to_first_depublication BIGINT,
	days_first_publication_to_last_depublication BIGINT,
	days_first_publication_to_first_sale_flow BIGINT,
	days_first_publication_to_first_booking BIGINT,
	days_first_publication_to_visit_completed BIGINT,
	days_first_publication_to_first_offer_accepted BIGINT,
	days_first_publication_to_first_sale_agreement_signed BIGINT,
	days_first_publication_to_house_registry_ended BIGINT,
	days_first_publication_to_first_offer_submitted BIGINT,
	total_depublications BIGINT,
	total_listings_visit_completed BIGINT,
	total_listings_offer_submited BIGINT,
	total_listings_offer_accepted BIGINT,
	days_as_published BIGINT,
	ts_load TIMESTAMP
);
ALTER TABLE sale.fact_listings OWNER TO airflow;
