select 
    lat,
    lng,
    city_name,
    neighborhood,
    region_code,
    iptu_quantity_of_apartments,
    cast(qa_ongoing_contracts as int)/cast(iptu_quantity_of_apartments as float)*100 as quintoandar_market_share,
    condo_name,
    telephone,
    email,
    google_formatted_address,
    condo_construction_year,
    cnpj,
    qa_ongoing_contracts,
    qa_ongoing_listing ,
    qa_avg_total_value,
    qa_unpublished,
    qa_min_bedrooms,
    qa_max_bedrooms,
    qa_max_area,
    qa_min_area,
    qa_elevator,
    qa_entrance,
    qa_key_location,
    qa_leads_last_120_days,
    qa_converted_leads_last_120_days,
    qa_doormen,
    qa_doormen_name,
    qa_doormen_telephone,
    qa_doormen_email,
    competitors_advertiser,
    competitors_listings,
    competitors_avg_total_value,
    competitors_listing_last_date
from datamarts.external_condos
where (qa_ongoing_contracts is not null or qa_ongoing_listing is not null) and quintoandar_market_share < 100
and cast(iptu_quantity_of_apartments as float) >= 20
