SELECT
    event_id AS id_event,
    amplitude_id AS id_amplitude,
    app AS id_app,
    user_id AS id_user,
    schema AS id_schema,
    insert_id AS id_inserted,
    device_id AS id_device,
    session_id AS id_session,
    amplitude_attribution_ids AS ids_amplitude_attributed,
    uuid,
    adid,
    ip_address,
    amplitude_event_type,
    event_type,
    event_properties,
    user_properties,
    data,
    city,
    country,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    idfa,
    language,
    library,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    region,
    sample_rate,
    start_version,
    version_name,
    is_attribution_event,
    BOOLEAN(paying) AS is_paying,
    TIMESTAMP(event_time) AS ts_event,
    TIMESTAMP(client_event_time) AS ts_client_event,
    TIMESTAMP(client_upload_time) AS ts_client_uploaded,
    TIMESTAMP(processed_time) AS ts_processed,
    TIMESTAMP(server_received_time) AS ts_server_received,
    TIMESTAMP(server_upload_time) AS ts_server_uploaded,
    TIMESTAMP(user_creation_time) AS ts_user_created,
    year,
    month,
    day
FROM
    datalake_casa_mineira_amplitude_raw.events
WHERE
    app = 329001
    AND year = {year}
    AND month = {month}
    AND day = {day}