SELECT
    id AS id_user,
    locale_id AS id_locale,
    custom_role_id AS id_custom_role,
    default_group_id AS id_default_group,
    external_id AS id_external,
    alias,
    details,
    name,
    email,
    phone,
    notes,
    locale,
    role,
    role_type,
    signature,
    tags,
    ticket_restriction,
    time_zone,
    user_fields,
    active AS is_active,
    shared AS is_shared,
    shared_agent AS is_shared_agent,
    chat_only AS is_chat_only,
    moderator AS is_moderator,
    only_private_comments AS is_only_private_comments,
    organization_id AS id_organization,
    permanently_deleted AS is_permanently_deleted,
    report_csv AS is_report_csv,
    restricted_agent AS is_restricted_agent,
    shared_phone_number AS is_shared_phone_number,
    verified AS is_verified,
    two_factor_auth_enabled AS is_two_factor_auth_enabled,
    suspended AS is_suspended,
    dt AS dt_extracted,
    last_login_at AS ts_last_login,
    created_at AS ts_created,
    updated_at AS ts_updated,
    NOW() AS ts_load,
    YEAR(dt) AS year,
    MONTH(dt) AS month,
    DAY(dt) AS day
FROM
    datalake_zendesk_raw.users
WHERE
    dt IN (CAST('{year}-{month}-{day}' AS DATE), CAST('{year}-{month}-{day}' AS DATE) + INTERVAL 1 DAY)
