select
    id,
    related_document_id as id_related_document,
    due_amount,
    due_date as dt_dued, 
    timestamp(issue_date_time) as ts_issued,
    company_use,
    our_number,
    occurrence_code,
    sha2(payee_name,256) as payee_name, 
    sha2(payee_document,256) as payee_document,
    sha2(payee_agency,256) as payee_agency,
    sha2(payee_account,256) as payee_account,
    boolean(payee_savings_acc) as has_payee_savings_acc,
    payee_bank_code, 
    timestamp(created_at) as ts_created,
    timestamp(updated_at) as ts_updated,
    status,
    paid_at as dt_paid,
    requested_by,
    related_document_type,
    original_response,
    related_document_status,
    paid_amount,
    bank_payment_code,
    type,
    style,
    bank_payment_id as id_bank_payment    
from
    datalake_vans_raw.payment