select
  id,
  atualizadoEm as ts_updated,
  criadoEm as ts_created,
  dataVigencia as ts_validity,
  status,
  contrato_id as id_contrato,
  fluxoLocacao_id as id_rent_flow,
  dataEnvioApolice as ts_policy_sent,
  dataEnvioEmailVigenciaLongaInquilino as ts_long_form_policy_sent_via_email_tenant,
  dataEnvioEmailVigenciaLongaProprietario as ts_long_form_policy_sent_via_email_landlord,
  dataSolicitacaoApolice as ts_policy_solicited,
  googleDriveId as id_google_drive,
  termoEntregaItens as terms_of_item_delivery,
  boletoCondominioTransferencia as has_transfered_payment_slip_condominium,
  dataConfirmaDadosMudanca  as ts_confirmed_data_change,
  numeroBoletosAbertos as number_of_open_payments,
  valorBoletoAberto as value_of_open_payment,
  openEnergyBill as open_energy_bill,
  openGasBill as open_gas_bill,
  openWaterBill as open_water_bill,
  shortTermSent as ts_short_term_sent,
  keyLocation as key_location,
  keyLocationDetails as key_location_details,
  missingFinanceData as is_missing_financial_data,
  shortTermTenantSent as ts_short_term_tenant_sent,
  shortTermLandlordSent as ts_short_term_landlord_sent,
  version
from datalake_ebdb_raw.onboarding
