SELECT
    id AS id_portability,
    REV AS rev,
    REVTYPE AS rev_type,
    contractFinalDate AS dt_final_contract,
    contractFinalDate_MOD AS mod_dt_final_contract,
    contractObservations AS contract_observations,
    contractObservations_MOD AS mod_contract_observations,
    contractStartDate AS dt_start_contract,
    contractStartDate_MOD AS mod_dt_start_contract,
    currentCondoFee AS current_condo_fee,
    currentCondoFee_MOD AS mod_current_condo_fee,
    currentIptuTwelth AS current_iptu_twelth,
    currentIptuTwelth_MOD AS mod_current_iptu_twelth,
    currentRent AS current_rent,
    currentRent_MOD AS mod_current_rent,
    houseAddress_bairro AS house_address_neighborhood,
    houseAddress_cep AS house_address_zipcode,
    houseAddress_cidade AS house_address_city,
    houseAddress_complemento AS house_address_complement,
    houseAddress_logradouro AS house_address_street,
    houseAddress_numero AS house_address_number,
    houseAddress_MOD AS mod_house_address,
    houseType AS house_type,
    houseType_MOD AS mod_house_type,
    lat,
    lat_MOD AS mod_lat,
    lng,
    lng_MOD AS mod_lng,
    ownerData_email AS owner_data_email,
    ownerData_gender AS owner_data_gender,
    ownerData_name AS owner_data_name,
    ownerData_phoneNumber AS owner_data_phone_number,
    ownerData_MOD AS mod_owner_data,
    status,
    status_MOD AS mod_status,
    tenantData_email AS tenant_data_email,
    tenantData_gender AS tenant_data_gender,
    tenantData_name AS tenant_data_name,
    tenantData_phoneNumber AS tenant_data_phone_number,
    tenantData_MOD AS mod_tenant_data,
    flow_id AS id_flow,
    flow_MOD AS mod_id_flow,
    house_id AS id_house,
    house_MOD AS mod_house,
    region_id AS id_region,
    region_MOD AS mod_id_region,
    tenant_id AS id_tenant,
    tenant_MOD AS mod_tenant,
    ownerType AS owner_type,
    ownerType_MOD AS mod_owner_type
FROM
    datalake_ebdb_raw.Portability_AUD
