SELECT
    evaluation_id AS id_evaluation,
    business_group_id AS id_business_group,
    template_defn_id AS id_template_definition,
    tmpl_period_id AS id_template_period,
    worker_id AS id_worker,
    manager_id AS id_manager,
    assignment_id AS id_assignment,
    locked_by_user_id AS id_locked_by_user,
    default_matrix_pcpn_role_id AS id_default_matrix_participant_role,
    manager_assignment_id AS id_manager_assignment,
    review_period_id AS id_review_period,
    cmp_plan_id AS id_compensation_plan,
    cmp_plan_period_id AS id_compensation_plan_period,
    template_type_code,
    name AS evaluation_name,
    language_code,
    status_code,
    prev_status_code AS previous_status_code,
    mapping_method_code,
    manager_comments,
    worker_comments,
    created_by,
    last_updated_by,
    action_code,
    action_reason,
    action_performed_by,
    calibration_status,
    calibration_performed_by,
    use_calc_ratings_flag AS is_calculated_ratings_used,
    select_manager_allowed_flag AS is_select_manager_allowed,
    calculation_ratings_flag AS is_calculation_ratings_enabled,
    star_rating_enabled_flag AS is_star_rating_enabled,
    kudos_region_flag AS is_kudos_region_enabled,
    digital_signature_flag AS is_digital_signature_enabled,
    set_role_minimums_flag AS is_role_minimums_set,
    set_role_maximums_flag AS is_role_maximums_set,
    total_min_participants AS min_total_participants,
    total_max_participants AS max_total_participants,
    enforce_min_pcpns_flag AS is_min_participants_enforced,
    wrk_see_mgr_pcpn_flag AS is_worker_allowed_see_manager_participants,
    use_wrk_connections_flag AS is_worker_connections_used,
    pcpn_feedback_req_flag AS is_feedback_required_for_participants,
    pcpn_decline_option_flag AS is_decline_option_available,
    auto_populate_mm_flag AS is_auto_populate_mm_enabled,
    send_request_to_mm_flag AS is_request_to_mm_sent,
    object_version_number,
    show_wkr_calc_rating_flag AS is_worker_calculated_rating_shown,
    show_mgr_calc_rating_flag AS is_manager_calculated_rating_shown,
    show_mm_calc_rating_flag AS is_mm_calculated_rating_shown,
    show_pcpn_calc_rating_flag AS is_participant_calculated_rating_shown,
    enable_sync_flag AS is_sync_enabled,
    start_date AS dt_started,
    end_date AS dt_ended,
    evaluation_date AS dt_evaluated,
    meeting_held_date AS dt_meeting_held,
    creation_date AS dt_created,
    last_update_date AS dt_updated,
    action_performed_date AS dt_action_performed,
    calibration_performed_date AS dt_calibration_performed,
    NOW () AS ts_load
FROM
    datalake_gsheets_people_raw.hra_evaluations
