SELECT
    template_defn_id AS id_template_definition,
    business_group_id AS id_business_group,
    set_id AS id_set,
    doc_type_id AS id_document_type,
    process_flow_id AS id_process_flow,
    default_matrix_pcpn_role_id AS id_default_matrix_participant_role,
    module_id AS id_module,
    ess_request_id AS id_ess_request,
    status_code,
    template_type_code,
    mapping_method_code AS mapping_method,
    created_by,
    last_updated_by AS updated_by,
    ess_request_status AS status_ess_request,
    mm_manager_types AS mm_manager_types_list,
    use_calc_ratings_flag AS is_calculated_ratings_used,
    calculate_ratings_flag AS is_ratings_calculation_enabled,
    rounding_rule_code AS rounding_rule,
    decimal_places AS decimal_places_num,
    show_participant_names AS is_name_participants_showed,
    select_mgr_allowed_flag AS is_manager_selection_allowed,
    star_rating_enabled_flag AS is_star_rating_enabled,
    set_role_minimums_flag AS is_role_minimums_set,
    set_role_maximums_flag AS is_role_maximums_set,
    total_min_participants AS total_minimum_participants,
    total_max_participants AS total_maximum_participants,
    enforce_min_pcpns_flag AS is_min_participants_enforced,
    use_wrk_connections_flag AS is_worker_connections_used,
    wrk_see_mgr_pcpn_flag AS is_worker_allowed_see_manager_participants,
    pcpn_feedback_req_flag AS is_feedback_required_for_participants,
    pcpn_decline_option_flag AS is_decline_option_allowed,
    auto_populate_mm_flag AS is_auto_populate_mm_enabled,
    send_request_to_mm_flag AS is_request_to_mm_sent,
    object_version_number,
    digital_signature_flag AS is_digital_signature_enabled,
    kudos_region_flag AS is_kudos_region_enabled,
    show_wkr_calc_rating_flag AS is_worker_calculated_rating_shown,
    show_mgr_calc_rating_flag AS is_manager_calculated_rating_shown,
    show_mm_calc_rating_flag AS is_mm_calculated_rating_shown,
    show_pcpn_calc_rating_flag AS is_participant_calculated_rating_shown,
    show_check_in_region_flag AS is_check_in_region_shown,
    show_feedback_req_region_flag AS is_feedback_request_region_shown,
    enable_sync_flag AS is_sync_enabled,
    allow_wkr_select_mm_role_flag AS is_worker_mm_role_selection_allowed,
    allow_mgr_select_mm_role_flag AS is_manager_mm_role_selection_allowed,
    all_mm_mgr_type_flag AS is_all_mm_manager_types_allowed,
    min_length_comments AS min_comments_length,
    max_length_comments AS max_comments_length,
    date_from AS dt_started,
    date_to AS dt_ended,
    creation_date AS dt_created,
    last_update_date AS dt_updated,
    NOW () AS ts_load
FROM
    datalake_gsheets_people_raw.hra_tmpl_defns_b
