SELECT
    person_name_id AS id_person_name,
    person_id AS id_person,
    business_group_id AS id_business_group,
    legislation_code AS code_legislation,
    name_type AS type_name,
    last_name AS last_name,
    first_name AS first_name,
    middle_names AS middle_names,
    title AS title,
    pre_name_adjunct AS adjunct_pre_name,
    suffix AS suffix,
    known_as AS known_as,
    previous_last_name AS previous_last_name,
    honors AS honors,
    military_rank AS rank_military,
    display_name AS display_name,
    full_name AS full_name,
    list_name AS list_name,
    order_name AS name_order,
    created_by,
    last_updated_by AS updated_by,
    char_set_context AS context_char_set,
    object_version_number AS version_number,
    effective_start_date AS dt_effective_start,
    effective_end_date AS dt_effective_end,
    creation_date AS dt_created,
    last_update_date AS dt_last_updated,
    NOW () AS ts_load
FROM
    datalake_gsheets_people_raw.per_person_names_f
