WITH last_sk_values AS (
    SELECT
        COALESCE(MAX(sk_house_amenities_version), 0) AS max_sk_house_amenities_version
    FROM
        dw_house.dim_house_amenities_version
)
SELECT
    COALESCE(
        dhav.sk_house_amenities_version,
        last_sk_values.max_sk_house_amenities_version + MONOTONICALLY_INCREASING_ID() + 1
    ) AS sk_house_amenities_version,
    pa.id_house,
    pa.has_bathtub,
    pa.has_shower_enclosure,
    pa.has_balcony,
    pa.has_stove_and_refrigerator,
    pa.has_private_pool,
    pa.has_bedroom_closets,
    pa.has_bathroom_cabinets,
    pa.has_kitchen_cabinets,
    pa.has_air_conditioning,
    pa.has_gas_shower,
    pa.has_pets_allowed,
    pa.has_maid_room,
    pa.has_maid_bathroom,
    pa.has_assigned_parking_space,
    pa.has_gourmet_balcony,
    pa.is_penthouse_apartment,
    pa.has_reversible_extra_room,
    pa.has_stove,
    pa.has_refrigerator,
    pa.has_morning_sun,
    pa.has_afternoon_sun,
    pa.has_blackout_curtains,
    pa.has_sheer_curtain,
    pa.has_soundproof_window,
    pa.has_ceiling_fan,
    pa.has_large_windows,
    pa.has_unobstructed_view,
    pa.has_quiet_street,
    pa.has_electric_shower,
    pa.has_microwave,
    pa.has_sofa,
    pa.has_washing_machine,
    pa.has_dryer,
    pa.has_washer_dryer_combo,
    pa.has_laundry_sink,
    pa.has_window_screens,
    pa.has_clothesline,
    pa.has_three_pin_outlets,
    pa.has_television,
    pa.has_dining_tables_and_chairs,
    pa.has_coffee_maker,
    pa.has_barbecue,
    pa.has_step_free_access,
    pa.has_cooktop,
    pa.has_kitchen_utensils,
    pa.has_double_bed,
    pa.has_single_bed,
    pa.has_bathroom_mirror,
    pa.has_electronic_lock,
    pa.has_electricity_included,
    pa.has_adapted_bathroom,
    pa.has_walk_in_closet,
    pa.has_open_kitchen,
    pa.has_office_tables_and_chairs,
    pa.has_garden,
    pa.has_spacious_rooms_and_corridors_doors,
    pa.has_backyard,
    pa.has_single_house_on_the_property,
    pa.has_laundry_area,
    pa.has_private_garden_area,
    pa.has_elevator,
    pa.has_playground,
    pa.has_condo_pool,
    pa.has_condo_grill_area,
    pa.has_sports_court,
    pa.has_gym,
    pa.has_party_hall,
    pa.has_sauna,
    pa.has_condo_laundry,
    pa.has_piped_gas,
    pa.has_automatic_gate,
    pa.has_gourmet_area,
    pa.is_near_metro_or_train,
    pa.has_playroom,
    pa.has_handrail,
    pa.has_tactile_floor,
    pa.has_access_ramps,
    pa.has_game_room,
    pa.has_accessible_parking_space,
    pa.has_green_area,
    pa.version,
    pa.is_current_version,
    pa.is_last_status_of_day,
    pa.ts_version_started,
    pa.ts_version_ended,
    NOW() AS ts_load
FROM
    datalake_ebdb_amenities.pivotted_amenities AS pa,
    last_sk_values
LEFT JOIN
    dw_house.dim_house_amenities_version AS dhav
        ON pa.id_house = dhav.id_house
        AND pa.version = dhav.version