SELECT
    external_id AS 123i_condo_id,
    title AS condo,
    bedrooms,
    garages,
    sizes AS house_sizes,
    construction_year,
    description,
    location.street AS address,
    location.number,
    location.neighborhood,
    location.city,
    location.state,
    location.zipcode AS zip_code,
    location.latitude AS lat,
    location.longitude AS lng,
    TRANSFORM(blocks, block -> block.name) AS blocks_name,
    metadata.source AS source,
    url,
    blocks,
    metadata,
    amenities AS amenities_list,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Salão de Festa') THEN TRUE END AS has_party_hall,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Churrasqueira') THEN TRUE END AS has_grill_area,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Piscina') THEN TRUE END AS has_swim_pool,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Quadra Poliesportiva') THEN TRUE END AS has_sports_court,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Sala de Ginástica') THEN TRUE END AS has_gym,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Sauna') THEN TRUE END AS has_sauna,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Espaço Gourmet') THEN TRUE END AS has_gourmet_area,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Playground') THEN TRUE END AS has_toy_library,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Aquecimento Central') THEN TRUE END AS has_piped_gas,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Lavanderia Coletiva') THEN TRUE END AS has_laundry,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Children Care') THEN TRUE END AS has_children_care,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Espaço Zen') THEN TRUE END AS has_spa,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Garagem para visitas') THEN TRUE END AS has_guest_garage,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Gerador') THEN TRUE END AS has_power_generator,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Hidromassagem') THEN TRUE END AS has_jacuzzi,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Home Cinema') THEN TRUE END AS has_movie_room,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Forno de Pizza') THEN TRUE END AS has_pizza_oven,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Jardim') THEN TRUE END AS has_garden,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Piscina Aquecida') THEN TRUE END AS has_heated_pool,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Piscina Infantil') THEN TRUE END AS has_kids_pool,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Pista Cooper') THEN TRUE END AS has_cooper_track,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Quadra Squash') THEN TRUE END AS has_squash_court,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Redário') THEN TRUE END AS has_hammock_area,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Salão de Jogos') THEN TRUE END AS has_game_room,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Vestiário') THEN TRUE END AS has_locker_room,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Frente Para o Mar') THEN TRUE END AS is_seafront,
    CASE WHEN ARRAY_CONTAINS(amenities, 'Esquina') THEN TRUE END AS is_corner_property,
    metadata.accessed_at AS ts_accessed,
    year,
    month,
    day
FROM 
    datalake_aragog_raw.123i_condominium
QUALIFY
    ROW_NUMBER() OVER(PARTITION BY external_id ORDER BY ts_accessed DESC) = 1