SELECT
    id,
    contribuiNoImovelAtual as has_contributed_to_current_house,
    cpf,
    dataAdmissao as dt_admission_date,
    donoDoAtual as current_owner,
    email,
    empVinculo as emp_link,
    empresa as company,
    estadoCivil as marital_status,
    nome as name,
    profissao as profession,
    refNome as name_reference,
    refTelefone as phone_number_reference,
    refVinculo as link_referencce,
    rendaMensal as monthly_salary,
    rg,
    sexo as gender,
    situacaoAtual as current_situation,
    telefone as phone_number,
    tempoDeResidenciaAnos as time_lived_in_residence,
    proposta_id as id_proposal,
    numeroDependentes as number_of_dependents,
    bairro as neighborhood,
    cep,
    cidade as city,
    complemento as complement,
    endereco as address,
    numero as number,
    estado_id as id_estado,
    dataExpedicaoRG as dt_rg_created,
    dataNascimento as dt_birth,
    fiador as has_guarantor,
    orgaoExpedidor as issuing_body,
    atualizadoEm as ts_updated,
    criadoEm as ts_created,
    tipo as type,
    motivoLocacao as rental_motive,
    vaiMorar as will_live,
    nacionalidade as nationality,
    nomeImobiliariaOuProprietario as name_of_real_estate_company_or_landlord,
    nomeMae as mothers_name,
    paisOrigem as country_of_origin,
    pastaDriveId as id_drive_folder,
    ramal as branch,
    telefoneEmpresa as company_phone_number,
    telefoneImobiliariaOuProprietario as phone_number_of_real_estate_company_or_landlord,
    dadosbancarios_agencia as agency_number,
    dadosBancarios_contaCorrente as account_number,
    dadosBancarios_cpfOuCnpj as account_cpf_or_cnpj,
    dadosbancarios_nome as account_name,
    dadosBancarios_outroTitular as has_secondary_account_holder,
    dadosBancarios_tipoConta as account_type,
    tipoPessoa as person_type,
    dadosBancarios_banco_id as id_bank_account,
    dataValidadeDocumento as ts_document_validity,
    telefoneResidencial as residential_phone_number,
    origemRenda as source_of_income,
    rendimentoAdicional as additional_income,
    documentationExtraComment as documentation_extra_comment,
    rgHasCPF as has_cpf_on_rg,
    rneHasCpf as has_cpf_on_rne,
    chosenDocumentationFlow as chosen_documentation_flow
FROM
    datalake_ebdb_raw.propostaproponente