---
custom_cluster:
  driver_node_type_id: m5a.xlarge
  node_type_id: m5a.xlarge
  num_workers: 2
  spark_version: 13.3.x-scala2.12
tables:
  - table_name: Contract
    extraction_type: full
    date_filter_column: created_on
    clean_table_name: contract
  - table_name: ContractPerson
    extraction_type: incremental
    date_filter_column: updated_on
    clean_table_name: contract_person
  - table_name: Onboarding
    extraction_type: incremental
    date_filter_column: updated_on
    clean_table_name: onboarding
  - table_name: OnboardingAction
    extraction_type: incremental
    date_filter_column: updated_on
    clean_table_name: onboarding_action
  - table_name: OnboardingBill
    extraction_type: incremental
    date_filter_column: updated_on
    clean_table_name: onboarding_bill
  - table_name: OnboardingTask
    extraction_type: incremental
    date_filter_column: updated_on
    clean_table_name: onboarding_task
  - table_name: OnboardingTaskTypes
    extraction_type: incremental
    date_filter_column: updated_on
    clean_table_name: onboarding_task_types
  - table_name: User
    extraction_type: incremental
    date_filter_column: updated_on
    clean_table_name: user
partition_cols: ["year", "month", "day"]
lineage_product_database_name: missioncontrol
