SELECT
    chave AS key,
    contrato AS id_contract,
    id_imovel AS id_house,
    id_analise_jira AS id_jira_analysis,
    valor AS value,
    status,
    tipo AS type,
    departamento AS department,
    solicitante AS requester,
    email_solicitante AS requester_email,
    email_cliente AS client_email,
    beneficiario AS beneficiary,
    resumo_do_caso AS case_summary,
    responsavel_jira AS jira_responsible,
    aprovador AS approver,
    tipo_solicitacao AS request_type,
    categoria AS category,
    classificacao AS classification,
    motivo AS reason,
    comentario AS comment,
    tag_acao_especifica AS specific_action_tag,
    email_analista_erro AS error_analyst_email,
    bpo,
    motivo_reprovacao AS rejection_reason,
    nome_do_processo_sistema AS system_process_name,
    data_analise_jira AS jira_analysis_date,
    criado AS created_at,
    atualizadoa AS updated_at,
    ts_load
FROM
    datalake_gsheets_raw.bandaid
