SELECT
  id_schedule AS sk_schedule,
  schedule_origin,
  channel_creation,
  application_source_creation,
  source_creation_unified,
  user_role_creation AS schedule_requested_user_role,
  first_confirmed_channel AS schedule_first_confirmed_channel,
  first_confirmed_user_role AS schedule_first_confirmed_user_role,
  last_confirm_answer_supply,
  last_confirm_answer_demand,
  last_confirm_answer_agent,
  last_confirm_answer_tenant_living,
  channel_confirmed_supply,
  channel_confirmed_demand,
  channel_confirmed_agent,
  channel_confirmed_tenant_living,
  is_confirmed_by_supply AS is_schedule_confirmed_by_supply,
  is_confirmed_by_demand AS is_schedule_confirmed_by_demand,
  is_confirmed_by_agent AS is_schedule_confirmed_by_agent,
  is_confirmed_by_tenant_living AS is_schedule_confirmed_by_tenant_living,
  IF(id_succeed_schedule IS NULL, TRUE, FALSE) AS is_last_schedule,
  IF(schedule_origin = "REQUEST", TRUE, FALSE) AS is_first_schedule,
  is_confirmed AS is_schedule_confirmed,
  is_completed AS is_schedule_completed,
  is_rescheduled AS is_schedule_rescheduled,
  is_canceled AS is_schedule_canceled,
  is_unsuccessful AS is_schedule_unsuccessful,
  ts_schedule_created,
  ts_next_schedule_created,
  ts_schedule_requested,
  ts_schedule_rescheduled,
  ts_schedule_confirmed,
  ts_schedule_completed,
  ts_schedule_unsuccessful,
  ts_schedule_canceled,
  ts_schedule_visit
FROM
  datalake_visit.visit_schedules
