SELECT -- [ODS] This table was migrated from ODS flow and needs a future refactoring to remove castings and renaming
  v.id_visit AS sk_visit,
  v.id_visit AS id_visit,
  v.code AS cd_visit,
  sv.business_unit,
  v.dt_visit AS day_visit,
  v.slot,
  v.slot_count,
  v.type,
  v.status,
  v.computed_status,
  v.behavior,
  v.booking_type,
  v.business_context,
  v.business_model,
  v.business_model_supply,
  v.business_model_demand,
  v.cancellation_reason,
  v.cancellation_on_behalf_of,
  v.cancellation_channel,
  v.cancellation_type,
  v.cancellation_author_role,
  v.unsuccessful_reason,
  v.visit_model,
  v.visit_schedule_type,
  v.visit_request_channel,
  v.visit_request_on_behalf_of,
  v.visit_request_user_role,
  v.first_supply_answer,
  v.first_supply_answer_channel,
  v.first_tenant_living_answer,
  v.first_tenant_living_answer_channel,
  v.visit_first_confirmed_channel,
  v.visit_first_confirmed_user_role,
  v.is_fixed_agent AS is_visit_with_fixed_agent,
  v.is_confirmed AS is_visit_confirmed,
  v.is_completed AS is_visit_completed,
  v.is_canceled AS is_visit_canceled,
  v.is_unsuccessful AS is_visit_unsuccessful,
  v.is_reschedule AS is_visit_reschedule,
  v.is_cancelled_by_expiration AS is_visit_cancelled_by_expiration,
  v.is_stalled AS is_visit_stalled,
  v.has_tenant_living AS has_visit_tenant_living,
  v.has_fup_collected AS has_visit_fup_collected,
  v.has_finisher_status AS has_visit_finisher_status,
  v.has_more_one_agent AS has_visit_more_one_agent,
  v.has_unsuccessful_demand_attended,
  v.has_unsuccessful_agent_attended,
  v.has_unsuccessful_supply_attended,
  v.ts_created AS dt_created,
  v.ts_updated AS dt_updated,
  v.ts_visit,
  v.ts_visit_requested,
  v.ts_visit_first_confirmed,
  v.ts_visit_supply_answer,
  v.ts_visit_demand_answer,
  v.ts_visit_agent_answer,
  v.ts_visit_tenant_answer,
  v.ts_visit_last_confirmed,
  v.ts_visit_first_rescheduled,
  v.ts_visit_rescheduled AS ts_visit_last_rescheduled,
  v.ts_visit_canceled,
  v.ts_visit_unsuccessful,
  v.ts_visit_done,
  v.ts_visit_fup_collected,
  v.ts_visit_stalled,
  v.ts_first_visit,
  NOW() AS ts_load
FROM
  datalake_visit.visits AS v
LEFT JOIN
  datalake_sale_visit_hubs.sale_visit_hubs AS sv
    ON sv.id_booking = v.id_visit
