---
custom_cluster:
  driver_node_type_id: r5d.12xlarge
  node_type_id: r5d.12xlarge
  runtime_engine: PHOTON
  autoscale:
    min_workers: 2
    max_workers: 6
  aws_attributes:
    ebs_volume_size: 500
  spark_conf:
    spark.sql.mapKeyDedupPolicy: "LAST_WIN"
    spark.executor.memory: "240g"
    spark.executor.memoryOverhead: "23g"
