SELECT
    Id AS id_account,
    OwnerId AS id_owner,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    MasterRecordId AS id_master_record,
    RecordTypeId AS id_record_type,
    ParentId AS id_parent,
    JigsawCompanyId AS jigsaw_company_id,
    CustomerId__c AS id_customer,
    ExternalId__c AS id_external,
    Name AS account_name,
    Type AS account_type,
    BillingStreet AS billing_street,
    BillingCity AS billing_city,
    BillingState AS billing_state,
    BillingPostalCode AS billing_postal_code,
    BillingCountry AS billing_country,
    BillingLatitude AS billing_latitude,
    BillingLongitude AS billing_longitude,
    BillingGeocodeAccuracy AS billing_geocode_accuracy,
    BillingAddress AS billing_address,
    ShippingStreet AS shipping_street,
    ShippingCity AS shipping_city,
    ShippingState AS shipping_state,
    ShippingPostalCode AS shipping_postal_code,
    ShippingCountry AS shipping_country,
    ShippingLatitude AS shipping_latitude,
    ShippingLongitude AS shipping_longitude,
    ShippingGeocodeAccuracy AS shipping_geocode_accuracy,
    ShippingAddress AS shipping_address,
    Phone AS phone,
    Fax AS fax,
    AccountNumber AS account_number,
    Website AS website,
    PhotoUrl AS photo_url,
    Sic AS sic,
    Industry AS industry,
    AnnualRevenue AS annual_revenue,
    NumberOfEmployees AS number_of_employees,
    Ownership AS ownership,
    TickerSymbol AS ticker_symbol,
    Description AS description,
    Rating AS rating,
    Site AS site,
    SystemModstamp AS system_mod_stamp,
    SourceSystemIdentifier AS source_system_identifier,
    Jigsaw AS jigsaw,
    AccountSource AS account_source,
    SicDesc AS sic_desc,
    Email__c AS email,
    IsDeleted AS is_deleted,
    CreatedDate AS ts_created,
    LastModifiedDate AS ts_last_modified,
    LastActivityDate AS ts_last_activity,
    LastViewedDate AS ts_last_viewed,
    LastReferencedDate AS ts_last_referenced,
    year,
    month,
    day
FROM
    datalake_sales_force_raw.account
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
