SELECT
    Id AS id_task,
    WhoId AS id_who,
    WhatId AS id_what,
    OwnerId AS id_owner,
    AccountId AS id_account,
    RecurrenceActivityId AS id_recurrence_activity,
    ContractId__c AS id_contract,
    LastModifiedById AS id_last_modified_by,
    WhoCount AS who_count,
    WhatCount AS what_count,
    Subject AS subject,
    Status AS status,
    Priority AS priority,
    Type__c AS type,
    CallDurationInSeconds AS call_duration_in_seconds,
    CallType AS call_type,
    CallDisposition AS call_disposition,
    CallObject AS call_object,
    TaskSubtype AS task_subtype,
    RecurrenceType AS recurrence_type,
    RecurrenceInterval AS recurrence_interval,
    RecurrenceDayOfWeekMask AS recurrence_day_of_week_mask,
    RecurrenceDayOfMonth AS recurrence_day_of_month,
    RecurrenceInstance AS recurrence_instance,
    RecurrenceMonthOfYear AS recurrence_month_of_year,
    RecurrenceRegeneratedType AS recurrence_regenerated_type,
    TaskName__c AS task_name,
    TaskInteractionType__c AS task_interaction_type,
    CaseCriticality__c AS case_criticality,
    CaseAccount__c AS case_account,
    Answer__c AS answer,
    Observation__c AS observation,
    DelayMessage__c AS delay_message,
    IsHighPriority AS is_high_priority,
    IsDeleted AS is_deleted,
    IsClosed AS is_closed,
    IsArchived AS is_archived,
    IsReminderSet AS is_reminder_set,
    IsRecurrence AS is_recurrence,
    ResponsabilityContestingIsGood__c AS responsability_contesting_is_good,
    CompletedDateTime AS ts_completed,
    ReminderDateTime AS ts_reminder,
    ActivityDate AS ts_activity,
    PassDueDate__c AS ts_pass_due,
    FirstInteractionDate__c AS ts_first_interaction,
    RecurrenceStartDateOnly AS ts_recurrence_start,
    RecurrenceEndDateOnly AS ts_recurrence_end,
    TaskCreatedDate__c AS ts_task_created,
    CreatedDate AS ts_created,
    LastModifiedDate AS ts_last_modified,
    SystemModstamp AS system_mod_stamp,
    LastViewedDate AS ts_last_viewed,
    LastReferencedDate AS ts_last_referenced,
    year,
    month,
    day
FROM
    datalake_sales_force_raw.task
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
