-- This DDL is not meant for Redshift, but for Spark itself.
-- This is because the query for this table is self-referential in order to create the Surrogate Keys.
-- Therefore, we need to have the empty table created manually before the query runs.
CREATE TABLE dw_visit.dim_behavior (
    sk_behavior_type BIGINT GENERATED BY DEFAULT AS IDENTITY,
    behavior_type STRING,
    ts_load TIMESTAMP
) USING DELTA LOCATION 's3://5a-dw-prod/visit/dim_behavior'
