-- removing duplicates rows due to CASE difference in the taxonomy
WITH taxonomy_demand AS (
    WITH taxonomy_min_ids AS (
        SELECT
            MIN(CAST(id AS BIGINT)) AS id
        FROM
            datalake_gsheets_clean.taxonomy_demand
        GROUP BY
            LOWER(app_type),
            LOWER(utm_source),
            LOWER(utm_medium),
            LOWER(branded),
            LOWER(first_update_source),
            flg_via_reschedule
    )
    SELECT
        CAST(td.id AS BIGINT) AS id,
        td.app_type,
        td.utm_source,
        td.utm_medium,
        td.branded,
        td.first_update_source,
        CAST(td.flg_via_reschedule AS BOOLEAN) AS flg_via_reschedule,
        td.category AS mkt_category,
        td.flow AS mkt_flow,
        td.completion AS mkt_completion,
        td.channel AS mkt_channel,
        td.medium AS mkt_medium,
        td.origin AS mkt_origin,
        td.source AS mkt_source,
        td.platform AS mkt_platform
    FROM
        datalake_gsheets_clean.taxonomy_demand AS td
    JOIN taxonomy_min_ids AS td_min
        ON td.id = td_min.id
),
booking AS (
    SELECT-- [ODS] This table was migrated from ODS flow and needs a future refactoring to remove castings and renamings
        CAST(b.id AS INT) AS sk_booking,
        CAST(b.id AS INT) AS id_booking,
        b.id_visitor,
        b.id_visit,
        b.id_house AS id_property,
        b.id_agent,
        b.id_attendant,
        b.id_rent_flow AS id_rental_flow,
        bc.id_user_cancellation,
        CAST(b.id_rescheduled_booking AS INT) AS rescheduled_from_id,
        b.country_code,
        b.visit_intent,
        b.buyer_intention,
        b.type,
        COALESCE(b.is_visit_completed, FALSE) AS is_visit_completed,
        CAST(b.is_visit_performed AS VARCHAR(100)) AS performed,
        CAST(b.is_closed AS VARCHAR(100)) AS closed,
        b.has_reschedule AS is_rescheduled,
        b.is_via_reschedule AS flg_via_reschedule,
        b.is_first_booking_auto,
        CAST(CAST(b.has_tenant_attended AS INT) AS VARCHAR(255)) AS visitor_arrived,
        CAST(CAST(b.has_agent_attended AS INT) AS VARCHAR(255)) AS agent_arrived,
        -- TODO [ODS] review this rule
        CAST(COALESCE(b.has_owner_arrived, true) AS VARCHAR(255)) AS owner_arrived,
        CAST(CAST(b.is_entrance_successful AS INT) AS VARCHAR(255)) AS successful_entrance,
        b.is_visit_created_from_app,
        b.is_visit_last_updated_from_app,
        b.visit_fup AS visit_follow_up,
        b.status,
        b.slot_day AS slot_dia,
        SUBSTRING(b.last_status_change_reason, 1, 200) AS reason,
        bc.cancelled_by,
        b.cancellation_reason,
        b.cancellation_reason_category,
        b.reason_category,
        b.responsible,
        b.checkin_code,
        b.visit_checkin_status,
        b.checkin_fail_reason,
        b.checkin_fail_commentary,
        b.last_update_source,
        b.first_update_source,
        b.first_cancelation_source,
        b.tenant_absence_reason AS visitor_missing_reason,
        b.agent_absence_reason AS agent_missing_reason,
        b.owner_missing_reason,
        b.troublesome_entrance_problem AS troublesome_entrance,
        b.checkin_status,
        b.user_sale_booking_creator,
        b.partner_3p_supply,
        b.partner_3p_demand,
        b.app_type,
        b.media_source,
        b.utm_source,
        b.utm_medium,
        b.utm_campaign,
        b.utm_content,
        b.utm_term,
        b.branded,
        b.final_attribution_origin,
        b.is_3p_supply,
        b.is_3p_supply_5a,
        b.is_3p_supply_bh,
        b.is_3p_demand,
        b.ts_visit_fup AS dt_visit_follow_up,
        b.ts_visit_follow_up_local_tz AS ts_visit_follow_up_local,
        b.ts_booking_utc AS dt_scheduling,
        b.ts_booking_local_tz AS ts_scheduling_local,
        b.ts_first_canceled AS dt_cancel,
        b.ts_first_canceled_local_tz AS ts_cancel_local,
        b.ts_created AS dt_created,
        b.ts_created_local_tz AS ts_created_local,
        b.ts_updated AS dt_updated
    FROM
        datalake_booking.booking AS b
            LEFT JOIN datalake_booking.booking_cancellation AS bc
                ON b.id = bc.id_booking
)
SELECT
    b.sk_booking,
    COALESCE(td.id,-1) AS sk_rent_flow_taxonomy,
    b.id_booking,
    b.id_visitor,
    b.id_visit,
    b.id_property,
    b.id_agent,
    b.id_attendant,
    b.id_rental_flow,
    b.id_user_cancellation,
    b.rescheduled_from_id,
    b.country_code,
    b.visit_intent,
    b.buyer_intention,
    b.type,
    b.performed,
    b.closed,
    b.visitor_arrived,
    b.agent_arrived,
    b.owner_arrived,
    b.successful_entrance,
    b.visit_follow_up,
    b.status,
    b.slot_dia,
    b.reason,
    b.cancelled_by,
    b.cancellation_reason,
    b.cancellation_reason_category,
    b.reason_category,
    b.responsible,
    b.last_update_source,
    b.first_update_source,
    b.first_cancelation_source,
    b.visitor_missing_reason,
    b.agent_missing_reason,
    b.owner_missing_reason,
    b.troublesome_entrance,
    b.checkin_status,
    b.checkin_code,
    b.visit_checkin_status,
    b.checkin_fail_reason,
    b.checkin_fail_commentary,
    b.user_sale_booking_creator,
    b.partner_3p_supply,
    b.partner_3p_demand,
    b.app_type,
    b.media_source,
    b.utm_source,
    b.utm_medium,
    b.utm_campaign,
    b.utm_content,
    b.utm_term,
    b.final_attribution_origin,
    CASE WHEN td.id IS NULL THEN 'Not Mapped' ELSE td.mkt_category END AS mkt_category,
    CASE WHEN td.id IS NULL THEN 'Not Mapped' ELSE td.mkt_flow END AS mkt_flow,
    CASE WHEN td.id IS NULL THEN 'Not Mapped' ELSE td.mkt_completion END AS mkt_completion,
    CASE WHEN td.id IS NULL THEN 'Not Mapped' ELSE td.mkt_origin END AS mkt_origin,
    CASE WHEN td.id IS NULL THEN 'Not Mapped' ELSE td.mkt_channel END AS mkt_channel,
    CASE WHEN td.id IS NULL THEN 'Not Mapped' ELSE td.mkt_medium END AS mkt_medium,
    CASE WHEN td.id IS NULL THEN 'Not Mapped' ELSE td.mkt_source END AS mkt_source,
    CASE WHEN td.id IS NULL THEN 'Not Mapped' ELSE td.mkt_platform END AS mkt_platform,
    b.flg_via_reschedule,
    b.branded = 'Branded' AS flg_branded,
    b.is_visit_completed,
    b.is_rescheduled,
    b.is_first_booking_auto,
    b.is_visit_created_from_app,
    b.is_visit_last_updated_from_app,
    b.is_3p_supply,
    b.is_3p_supply_5a,
    b.is_3p_supply_bh,
    b.is_3p_demand,
    b.dt_visit_follow_up,
    b.ts_visit_follow_up_local,
    b.dt_scheduling,
    b.ts_scheduling_local,
    b.dt_cancel,
    b.ts_cancel_local,
    b.dt_created,
    b.ts_created_local,
    b.dt_updated,
    NOW() AS ts_load
FROM
    booking b
    LEFT JOIN taxonomy_demand td
        ON LOWER(COALESCE(td.app_type, '')) = LOWER(COALESCE(b.app_type, ''))
        AND LOWER(COALESCE(td.utm_source, '')) = LOWER(COALESCE(b.utm_source, ''))
        AND LOWER(COALESCE(td.utm_medium, '')) = LOWER(COALESCE(b.utm_medium, ''))
        -- TODO [ODS] use flag is_branded FROM datalake_amplitude_visit.amplitude_visit
        AND LOWER(COALESCE(td.branded, '')) = LOWER(COALESCE(b.branded,''))
        AND LOWER(COALESCE(td.first_update_source, '')) = LOWER(COALESCE(b.first_update_source, ''))
        AND COALESCE(td.flg_via_reschedule, FALSE) = COALESCE(b.flg_via_reschedule, FALSE)
