SELECT
    id,
    id_external,
    id_invoice,
    id_checkout_boleto,
    identifier,
    status,
    due_amount,
    our_number,
    our_number_digit,
    wallet_number,
    barcode,
    inputtable_line,
    external_source,
    ts_due,
    ts_issued,
    ts_created,
    ts_retsuko_created,
    ts_retsuko_updated
FROM
    datalake_retsuko_clean.boleto
