SELECT
    id,
    id_external,
    id_account,
    id_contract,
    status,
    substatus,
    negotiation_status,
    paid_via,
    purpose,
    closing_mode,
    due_amount,
    paid_amount,
    accrual_year_month,
    ts_paid,
    ts_canceled,
    ts_sent,
    ts_due,
    ts_created,
    ts_retsuko_updated
FROM
    datalake_retsuko_clean.invoice
QUALIFY
    ROW_NUMBER() OVER (PARTITION BY id ORDER BY ts_retsuko_updated DESC) = 1
