class APIEnum:
    """
    Mapping of secret keys for the API connections parameters stored in
    the Databricks secrets.
    """

    BRAZE_INDICA_AI = "BRAZE_INDICA_AI_API"
    BRAZE_OWNERS = "BRAZE_OWNERS_API"
    BRAZE_TENANTS = "BRAZE_TENANTS_API"
    CHATTERMILL = "CHATTERMILL_API"
    CRITEO = "CRITEO_API"
    CRITEO_CASA_MINEIRA = "CRITEO_API_CASA_MINEIRA"
    FACEBOOK = "FACEBOOK_API"
    FACEBOOK_CASA_MINEIRA = "FACEBOOK_API_CASA_MINEIRA"
    GSHEETS_CREDENTIALS = "GOOGLE_SERVICE_ACCOUNT_CREDENTIALS"
    JIRA = "JIRA_API"
    LINKEDIN = "LINKEDIN_API"
    RTB = "RTB_API"
    SIRENA = "SIRENA_API"
    SURVICATE = "SURVICATE_API"
    TRACKSALE = "TRACKSALE_API"
    TWITTER = "TWITTER_API"
    TWILIO_FLEX_INSIGHTS = "TWILIO_FLEX_INSIGHTS_API"
