SELECT
  id_house_listing,
  id_house,
  version,
  status,
  cast(rent as decimal(12,2)) as rent,
  listing_category,
  last_originals_type,
  last_iorent_type,
  is_last_version,
  is_exclusive,
  is_originals_active,
  is_iorent_active,
  ts_listing_version_start,
  ts_listing_version_end,
  ts_last_unpublished,
  dt_last_exclusive_opted_in,
  dt_last_exclusive_opted_out,
  dt_last_originals_opted_in,
  dt_last_originals_opted_out,
  dt_last_iorent_opted_in,
  dt_last_iorent_opted_out
 FROM datalake_ebdb_listing_prod.house_listing