drop table if exists datalake_clean.crawler_listings;

create external table datalake_clean.crawler_listings (
	id string,
	website string,
	street string,
	street_number string,
	neighborhood string,
	city string,
	state string,
	lat string,
	lng string,
	latlng string,
	full_address string,
	location_type string,
	location_precision string,
	gcep string,
	glat string,
	glng string,
	gstreet string,
	gaddress_flg string,
	dt_address string,
	gstreet_number string,
	gneighborhood string,
	gcity string,
	gstate string,
	street_flg string,
	street_number_flg string,
	neighborhood_flg string,
	cep_flg string,
	city_flg string,
	latlng_flg string,
	full_address_flg string,
	primary_phone_number string,
	secondary_phone_number string,
	price string,
	rent string,
	condominium string,
	iptu string,
	total_area string,
	useful_area string,
	bedrooms string,
	suites string,
	toilets string,
	garages string,
	year_building string,
	cep string,
	sk_date_last_run string,
	sk_date_first_seen string,
	sk_date_last_seen string,
	active string,
	days_seen string,
	days_unseen string,
	runs_unseen string,
	rental_flg string,
	sale_flg string,
	listing_type string,
	advertiser_type string,
	big_advertiser string,
	advertiser_name string
)
row format serde 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
with serdeproperties (
  'separatorChar' = ',',
  'quoteChar' = '\"'
)
location 's3://5a-datalake/clean/crawler_listings/'
tblproperties (
  'skip.header.line.count' = '1'
);
