SELECT
  business_group_id AS id_business_group,
  dashboard_tmpl_id AS id_dashboard_template,
  set_id AS id_set,
  created_by,
  last_updated_by AS updated_by,
  CAST(object_version_number AS INT) AS object_version_number,
  display_age = 'Y' AS is_age_overlay_visible,
  display_comments = 'Y' AS is_detail_comments_visible,
  display_ethnicity = 'Y' AS is_ethnicity_visible,
  display_gender = 'Y' AS is_gender_visible,
  display_impact_of_loss = 'Y' AS is_impact_of_loss_visible,
  display_mobility = 'Y' AS is_mobility_visible,
  display_religious_affltn = 'Y' AS is_religious_affiliation_overlay_visible,
  display_risk_of_loss = 'Y' AS is_risk_of_loss_visible,
  filter_businessunit = 'Y' AS is_business_unit_filter_visible,
  filter_competency = 'Y' AS is_competency_filter_enabled,
  filter_department = 'Y' AS is_department_filter_enabled,
  filter_jobgrade = 'Y' AS is_job_grade_filter_enabled,
  filter_jobrole_assgn = 'Y' AS is_job_role_assignment_filter_enabled,
  filter_job_family = 'Y' AS is_job_family_filter_enabled,
  filter_job_function = 'Y' AS is_job_function_filter_enabled,
  filter_level = 'Y' AS is_level_filter_enabled,
  filter_location = 'Y' AS is_location_filter_enabled,
  filter_mgmt_level = 'Y' AS is_management_level_filter_enabled,
  filter_org_hierarchy = 'Y' AS is_organization_hierarchy_filter_enabled,
  filter_proficiency = 'Y' AS is_proficiency_filter_enabled,
  filter_revwr_partcpnt = 'Y' AS is_reviewer_participant_filter_enabled,
  filter_succession_plan = 'Y' AS is_succession_plan_filter_enabled,
  filter_talent_pool = 'Y' AS is_talent_pool_filter_enabled,
  color_jobrole_assgn = 'Y' AS is_job_role_assignment_color_enabled,
  color_location = 'Y' AS is_location_color_enabled,
  color_org_hierarchy = 'Y' AS is_organization_hierarchy_color_enabled,
  max_markers_allowed = 'Y' AS is_max_marker_allowed,
  use_compare_flag = 'Y' AS is_comparison_used,
  create_goals_flag = 'Y' AS is_goal_creation_enabled,
  use_holding_area_flag = 'Y' AS is_holding_area_used,
  use_notes_flag = 'Y' AS is_notes_used,
  use_orgchart_flag = 'Y' AS is_org_chart_used,
  use_pot_assess_flag = 'Y' AS is_potential_assessment_used,
  use_tasks_flag = 'Y' AS is_task_usage_enabled,
  include_matrix_mgmt = 'Y' AS is_matrix_management_included,
  include_succession_plans = 'Y' AS is_succession_plan_inclusion_enabled,
  include_talent_pools = 'Y' AS is_talent_pool_inclusion_enabled,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_hr_review_raw.hrr_dashboard_tmpls_b
