SELECT
    id,
    idempresa AS id_company,
    idcredor AS id_creditor,
    codigo AS code,
    razaosocial AS corporate_name,
    fantasia AS fantasy_name,
    cnpj,
    ie,
    endereco AS address,
    end_numero AS address_number,
    end_bairro AS neighborhood,
    end_cep  AS zip_code,
    end_cidade AS city,
    end_uf AS uf,
    email1 AS first_email,
    email2 AS second_email,
    obs,
    processo AS process,
    contatos AS contacts,
    campo1 AS field_1,
    campo2 AS field_2,
    campo3 AS field_3,
    campo4 AS field_4,
    campo5 AS field_5,
    end_compl AS address_complement,
    usuario_cad AS user_cad,
    usuario_alt AS user_alt,
    cod_ext,
    data_cad AS dt_cad,
    data_alt AS dt_alt,
    last_update AS ts_updated
FROM
    datalake_iaf_raw.vi_319_tb_devedor
