SELECT
    id,
    idempresa AS id_company,
    idgrupo AS id_group,
    codigo AS code,
    nome AS name,
    cpf,
    rg,
    endereco AS address,
    end_numero AS address_number,
    end_bairro AS neighborhood,
    end_cep  AS zip_code,
    end_cidade AS city,
    end_uf AS uf,
    fone1 AS first_phone,
    fone2 AS second_phone,
    email1 AS first_email,
    email2 AS second_email,
    obs,
    ac_login AS login,
    ac_senha AS password,
    ac_email AS email,
    comissao AS commission,
    taxa_contrato AS contract_tax,
    status,
    fase AS phase,
    p_banco AS bank,
    p_agencia AS agency,
    p_conta AS account,
    p_obs AS obs_p,
    end_compl AS address_complement,
    perfil AS profile,
    ultimo_acesso AS last_access,
    taxa_pd AS pd_tax,
    ac_nivel_acesso AS access_level,
    pausa_status AS status_pause,
    pausa_motivo AS reason_pause,
    ramal AS extension,
    permgestor AS manager,
    funcao_com AS com_function,
    funcao_lider AS leader_function,
    funcao_neg AS neg_function,
    ger_comercial AS commercial_manager,
    tp_comissao AS commision_type,
    ipfixo AS is_fix_ip,
    data_adm AS dt_adm,
    data_dem AS dt_dem,
    last_update AS ts_updated
FROM
    datalake_iaf_raw.vi_319_tb_colaborador
