SELECT
    id,
    idbaixa_old AS id_write_off_old,
    idempresa AS id_company,
    idcredor AS id_creditor,
    iddevedor AS id_debtor,
    idrecebimento AS id_receipt,
    idtitulo AS id_title,
    processo AS process,
    usuario_cad AS cad_user,
    usuario_alt_neg AS alt_neg_user,
    negociador AS negotiator,
    obs,
    capitalpago AS paid_capital,
    protestopago AS paid_protest,
    jurospago AS paid_fee,
    multapago AS paid_fine,
    honorariospago AS paid_honorary,
    descontopago AS paid_discount,
    totalpago AS total_paid,
    taxapago AS paid_tax,
    pdpago AS paid_pd,
    comi_hon_paga AS paid_comi_hon,
    taxaadmpago AS paid_adm_tax,
    taxaoutpago AS paid_out_tax,
    jurosretpago AS paid_ret_fee,
    quitacaotot AS total_discharge,
    fase AS phase,
    origem AS origin,
    databaixa AS dt_write_off,
    last_update AS ts_updated
FROM
    datalake_iaf_raw.vi_319_tb_baixas
