DROP TABLE IF EXISTS public.dim_pre_proposal;
CREATE TABLE public.dim_pre_proposal (
  sk_pre_proposal INTEGER,
  id_pre_proposal INTEGER,
  code varchar(10),
  renting_value INTEGER,
  renting_original_value INTEGER,
  condo_original_value INTEGER,
  dt_approved TIMESTAMP,
  editing VARCHAR(50),
  status VARCHAR(50),
  owner_accepted_5a_conditions INTEGER,
  id_user INTEGER,
  id_property INTEGER,
  dt_created TIMESTAMP,
  dt_updated TIMESTAMP,
  dt_timestamp TIMESTAMP WITHOUT TIME ZONE,
  offer_submitted BOOLEAN,
  ultimo_update_edicao integer,
  dt_first_sent timestamp,
  last_updated_date timestamp,
  expiration_date timestamp,
  last_rent_value_tenant decimal(18,4),
  last_rent_value_landlord decimal(18,4),
  total_rent_value decimal(18,4),
  animais_condition INTEGER,
  quando_vai_mudar_condition INTEGER,
  quem_vai_morar_condition INTEGER,
  special_conditions_count INTEGER,
  remove_conditions INTEGER,
  include_conditions INTEGER,
  maintenance_or_repair_conditions INTEGER,
  replace_or_modify_conditions INTEGER,
  other_conditions INTEGER,
  CONSTRAINT dim_pre_proposal_pkey PRIMARY KEY(sk_pre_proposal)
) ;