DROP TABLE IF EXISTS dim_external_property;
CREATE TABLE dim_external_property (
  sk_external_property   BIGINT      NOT NULL,
  id                     BIGINT      NOT NULL,
  common_id              BIGINT      NOT NULL DEFAULT -1,
  source                 VARCHAR(50) NOT NULL DEFAULT 'outro',
  business               VARCHAR(200),
  type                   VARCHAR(50),
  primary_phone_number   VARCHAR(20),
  secondary_phone_number VARCHAR(20),
  price                  NUMERIC(14, 2),
  rent                   NUMERIC(14, 2),
  condominium            NUMERIC(14, 2),
  iptu                   NUMERIC(14, 2),
  total_area             NUMERIC(14, 2),
  useful_area            NUMERIC(14, 2),
  bedrooms               SMALLINT,
  suites                 SMALLINT,
  toilets                SMALLINT,
  garages                SMALLINT,
  year_building          SMALLINT,
  cep                    VARCHAR(20),
  lat                    NUMERIC(18, 7),
  lng                    NUMERIC(18, 7),
  street                 VARCHAR(200),
  neighborhood           VARCHAR(200),
  city                   VARCHAR(200),
  state                  VARCHAR(10),
  start_date             DATE,
  end_date               DATE,
  PRIMARY KEY (sk_external_property, id, source)
)