SELECT
  id,
  id_house,
  id_flow,
  id_tenant,
  id_state as id_house_state,
  id_region as id_house_region,
  owner_type,
  dt_contract_started,
  dt_contract_ended,
  current_condo_fee,
  current_iptu_twelth,
  current_rent,
  house_address_neighborhood,
  house_address_zipcode,
  house_address_city,
  house_address_complement,
  house_address_street,
  house_address_number,
  house_type,
  lat,
  lng,
  owner_data_email,
  owner_data_gender,
  owner_data_name,
  owner_data_phone_number,
  status,
  tenant_data_email,
  tenant_data_gender,
  tenant_data_name,
  tenant_data_phone_number,
  contract_observations,
  coalesce(owner_type = 'B2B', false) as is_owner_b2b,
  ts_created,
  ts_updated
from
  datalake_ebdb_clean.portability