SELECT
   id,
   authorization_id AS id_authorization,
   imovel_id AS id_house,
   occupant_id AS id_occupant,
   restriction_id AS id_restriction,
   type_id AS id_type,
   rev,
   revtype AS rev_type, 
   additionalinfo AS additional_info,
   description,
   lockeraddress AS locker_address,
   password,
   CAST(optedkeyswithagent AS BOOLEAN) AS has_opted_keys_with_agent,
   imovel_mod AS mod_id_house,
   additionalinfo_mod AS mod_additional_info,
   authorization_mod AS mod_authorization,
   description_mod AS mod_description,
   lockeraddress_mod AS mod_locker_address,
   occupant_mod AS mod_occupant,
   password_mod AS mod_password,   
   restriction_mod AS mod_restriction,
   type_mod AS mod_type,
   optedkeyswithagent_mod AS mod_has_opted_keys_with_agent,
   vacanton_mod AS mod_dt_vacated,
   CAST(vacanton AS DATE) AS dt_vacated
FROM
   datalake_ebdb_raw.accesstype_aud