SELECT
  c.id,
  c.condoManager_id AS id_condo_manager,
  c.nome AS name,
  c.endereco AS address,
  c.numero AS number,
  c.bairro AS neighborhood,
  c.cidade AS city,
  c.cep AS zipcode,
  c.lat,
  c.lng,
  c.latlng,
  c.rules,
  c.referenciaExterna AS external_reference,
  c.entryAuthorization AS entry_authorization,
  c.entryAuthorizationInfo AS entry_authorization_info,
  c.hasCondominiumPage AS has_condo_page,
  c.expirationDay AS dt_expiration,
  c.weekendEndMovingSchedule AS ts_weekend_moving_schedule_ended,
  c.weekendStartMovingSchedule AS ts_weekend_moving_schedule_started,
  c.workDaysEndMovingSchedule AS ts_workdays_moving_schedule_ended,
  c.workDaysStartMovingSchedule AS ts_workdays_moving_schedule_started,
  c.criadoEm AS ts_created,
  c.atualizadoEm AS ts_updated
FROM datalake_ebdb_raw.Condominio c
