SELECT
  id AS id_listing_business_context,
  rev,
  revtype AS rev_type,
  lastPublicationDate AS ts_last_publication,
  lastPublicationDate_mod AS mod_ts_last_publication,
  businessContext AS business_context,
  businessContext_mod AS mod_business_context,
  shortUrl AS short_url,
  shortUrl_mod AS mod_short_url,
  status,
  status_mod AS mod_status,
  closingStatus AS status_closing,
  closingStatus_mod AS mod_status_closing,
  imovelId AS id_house,
  selectedAction AS selected_action,
  selectedAction_mod AS mod_selected_action,
  statusReason AS status_reason,
  statusReason_mod AS mod_status_reason,
  ownership,
  ownership_mod AS mod_ownership,
  calculatorPrice AS calculator_price,
  calculatorPrice_mod AS mod_calculator_price,
  firstPublicationDate AS ts_first_publication,
  firstPublicationDate_mod AS mod_ts_first_publication,
  atualizadoEm AS ts_updated,
  criadoEm AS ts_created
FROM
  datalake_ebdb_raw.ListingBusinessContext_AUD
