SELECT
    id,
    dataParaMudanca AS ts_to_scheduling,
    dataProposta AS ts_proposal,
    garantia AS guarantee,
    garantiaPagaEm as ts_guarantee_paid,
    motivacao AS motivation,
    propostaAluguel AS rent_proposal,
    status,
    imovel_id AS id_house,
    proponente_id AS id_proponent,
    explicacao AS explanation,
    ticketID AS id_ticket,
    descricaoGarantia AS guarantee_description,
    atualizadoEm AS ts_updated,
    criadoEm AS ts_created,
    dataAprovacao AS ts_approved,
    dataDocumentosEnviados AS ts_documentation_sent,
    negociacao_id AS id_negotiation,
    dataDocumentosProprietarioEnviados AS ts_owner_documentation_sent,
    proprietarioEnviouDocumentos AS has_owner_sent_documentation,
    inquilinoEnviouDocumentos AS has_tenant_sent_documentation,
    proprietarioAceitouContrato AS has_owner_accepted_contract,
    inquilinoAceitouContrato AS has_tenant_accepted_contract,
    inquilinoPastaGDrive AS tenant_gdrive_folder,
    proprietarioPastaGDrive AS owner_gdrive_folder,
    statusDocumentacaoInq AS tenant_documentation_status,
    statusDocumentacaoProp AS owner_documentation_status,
    preProposta_id AS id_pre_proposal,
    fazerTermoAditivo AS has_additive_term,
    visualizedDateOwner AS ts_owner_visualized,
    visualizedDateTenant AS ts_tenant_visualized,
    offer_id AS id_offer,
    expiresAt AS ts_expired,
    portability_id AS id_portability,
    rejectionReason AS rejection_reason,
    isTenantAutomaticSubmission AS is_tenant_auto_submission,
    bypassPreAnalysis AS is_pre_analyze,
    dataVigencia AS ts_entrance
FROM
    datalake_ebdb_raw.proposta
