SELECT
    id as id_rent_flow,
    cliente_id as id_client,
    gerente_id as id_manager,
    imovel_id as id_house,
    currentOffer_id as id_current_offer,
    currentContrato_id as id_current_contract,
    currentProposta_id as id_current_proposal,
    REV as rev,
    rEVTYPE as rev_type,
    ignorarAntesDe_MOD as mod_ts_ignore_before,
    status,
    status_MOD as mod_status,
    agentes_MOD as mod_agents,
    cliente_MOD as mod_id_client,
    gerente_MOD as mod_id_manager,
    imovel_MOD as mod_id_house,
    etapaRejeitada as is_step_rejected,
    etapaRejeitada_MOD as mod_is_step_rejected,
    withoutIptu as has_no_iptu,
    withoutIptu_MOD as mod_has_no_iptu,
    currentOfferId_MOD as mod_id_current_offer,
    currentContratoId_MOD as mod_id_current_contract,
    currentPropostaId_MOD as mod_id_current_proposal,
    ignorarAntesDe as ts_ignore_before
FROM
    datalake_ebdb_raw.fluxolocacao_aud
