SELECT
  ae.id,
  ae.id_tracking,
  ae.uuid_event,
  ae.uuid_lead,
  ae.event_type,
  GET_JSON_OBJECT(ae.event_properties, '$.user') AS event_properties_user,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.payloadToPricingReport.pricing.rentPrice') AS pricing_rent_price,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.percentilesRent.10') AS pricing_percentiles_rent_10,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.percentilesRent.20') AS pricing_percentiles_rent_20,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.percentilesRent.30') AS pricing_percentiles_rent_30,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.percentilesRent.40') AS pricing_percentiles_rent_40,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.percentilesRent.50') AS pricing_percentiles_rent_50,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.percentilesRent.60') AS pricing_percentiles_rent_60,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.percentilesRent.70') AS pricing_percentiles_rent_70,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.percentilesRent.80') AS pricing_percentiles_rent_80,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.percentilesRent.90') AS pricing_percentiles_rent_90,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.payloadToPricingReport.details.description') AS pricing_details_description,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.payloadToPricingReport.location.city') AS pricing_city,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.payloadToPricingReport.location.address') AS pricing_address,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.payloadToPricingReport.location.zipCode') AS pricing_zipcode,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.pricing.payloadToPricingReport.blueprint.bedrooms') AS pricing_bedrooms,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.enrichment.enrichmentResponse.features') AS enrichment_features,
  GET_JSON_OBJECT(ae.event_properties, '$.properties.completeness.completenessScore') AS completeness_score,
  ae.ts_event,
  ae.ts_created,
  ae.ts_updated,
  ae.year,
  ae.month,
  ae.day
FROM 
  datalake_brokers_supply_processor_clean.analytic_event AS ae