SELECT
    id_company::BIGINT,
    GET_JSON_OBJECT(properties, '$.hubspot_owner_id')::BIGINT AS id_hubspot_owner,
    GET_JSON_OBJECT(properties, '$.hubspot_team_id')::BIGINT AS id_hubspot_team,
    SPLIT(NULLIF(GET_JSON_OBJECT(properties, '$.atuacao_da_imobiliaria'), ''), ';') AS fields_of_business,
    NULLIF(GET_JSON_OBJECT(properties, '$.address'), '') AS address,
    NULLIF(GET_JSON_OBJECT(properties, '$.zip'), '') AS zip_code,
    NULLIF(GET_JSON_OBJECT(properties, '$.city'), '') AS city,
    COALESCE(
        NULLIF(GET_JSON_OBJECT(properties, '$.estado'), ''),
        NULLIF(GET_JSON_OBJECT(properties, '$.state'), '')
    ) AS state,
    NULLIF(GET_JSON_OBJECT(properties, '$.country'), '') AS country,
    NULLIF(GET_JSON_OBJECT(properties, '$.domain'), '') AS domain,
    NULLIF(GET_JSON_OBJECT(properties, '$.e_mail'), '') AS e_mail,
    NULLIF(GET_JSON_OBJECT(properties, '$.hs_analytics_source'), '') AS hs_analytics_source,
    NULLIF(GET_JSON_OBJECT(properties, '$.hs_analytics_source_data_1'), '') AS hs_analytics_source_data_1,
    NULLIF(GET_JSON_OBJECT(properties, '$.hs_analytics_source_data_2'), '') AS hs_analytics_source_data_2,
    NULLIF(GET_JSON_OBJECT(properties, '$.industry'), '') AS industry,
    NULLIF(GET_JSON_OBJECT(properties, '$.inside_sales'), '') AS inside_sales,
    NULLIF(GET_JSON_OBJECT(properties, '$.lifecyclestage'), '') AS life_cycle_stage,
    NULLIF(GET_JSON_OBJECT(properties, '$.mkt_campain'), '') AS mkt_campain,
    NULLIF(GET_JSON_OBJECT(properties, '$.mkt_channel'), '') AS mkt_channel,
    NULLIF(GET_JSON_OBJECT(properties, '$.mkt_content'), '') AS mkt_content,
    NULLIF(GET_JSON_OBJECT(properties, '$.mkt_medium'), '') AS mkt_medium,
    NULLIF(GET_JSON_OBJECT(properties, '$.mkt_origin'), '') AS mkt_origin,
    NULLIF(GET_JSON_OBJECT(properties, '$.mkt_source'), '') AS mkt_source,
    NULLIF(GET_JSON_OBJECT(properties, '$.motivo_de_descarte'), '') AS discard_reason,
    NULLIF(GET_JSON_OBJECT(properties, '$.motivos_de_descarte_unificados'), '') AS unified_discard_reasons,
    NULLIF(GET_JSON_OBJECT(properties, '$.name'), '') AS name,
    NULLIF(GET_JSON_OBJECT(properties, '$.origem_do_lead'), '') AS lead_origin,
    NULLIF(GET_JSON_OBJECT(properties, '$.phone'), '') AS phone,
    NULLIF(GET_JSON_OBJECT(properties, '$.tipo_de_parceria'), '') AS partnership_type,
    NULLIF(GET_JSON_OBJECT(properties, '$.first_conversion_event_name'), '') AS first_conversion_event_name,
    NULLIF(GET_JSON_OBJECT(properties, '$.hs_analytics_first_touch_converting_campaign'), '') AS hs_analytics_first_touch_converting_campaign,
    NULLIF(GET_JSON_OBJECT(properties, '$.qual_'), '') AS crm,
    SPLIT(NULLIF(GET_JSON_OBJECT(properties, '$.com_quais_imobiliarias_tem_parceria_'), ''), ';') AS partner_agencies,
    SPLIT(NULLIF(GET_JSON_OBJECT(properties, '$.em_quais_portais_anuncia_'), ''), ';') AS advertising_portals,
    SPLIT(NULLIF(GET_JSON_OBJECT(properties, '$.qual_a_solucao_empresa_de_garantia_locaticia_oferece_para_os_clientes_de_locacao_'), ''), ';') AS rental_guarantee_solutions,
    NULLIF(GET_JSON_OBJECT(properties, '$.qual_o_foco_da_imobiliaria_'), '') AS real_estate_agency_focus,
    SPLIT(NULLIF(GET_JSON_OBJECT(properties, '$.trabalha_com_financiamento__se_sim__quais_bancos_'), ''), ';') AS financing_banks,
    NULLIF(GET_JSON_OBJECT(properties, '$.cnpj'), '') AS cnpj,
    NULLIF(GET_JSON_OBJECT(properties, '$.creci'), '') AS creci,
    SPLIT(NULLIF(GET_JSON_OBJECT(properties, '$.produto_de_interesse'), ''), ';') AS products_of_interest,
    NULLIF(GET_JSON_OBJECT(properties, '$.hs_lead_status'), '') AS lead_status,
    FROM_JSON(
        GET_JSON_OBJECT(properties_with_history, '$.hs_lead_status'),
        'array<struct<
            value:string,
            timestamp:timestamp,
            source_type:string,
            source_id:string,
            source_label:string,
            updated_by_user_id:string
        >>'
    ) AS lead_status_history,
    COALESCE(GET_JSON_OBJECT(properties, '$.num_associated_deals')::INT, 0) AS num_associated_deals,
    COALESCE(GET_JSON_OBJECT(properties, '$.num_associated_contacts')::INT, 0) AS num_associated_contacts,
    GET_JSON_OBJECT(properties, '$.qual_a_media_de_novos_contratos_de_locacao_mes_')::INT AS monthly_average_new_rental_contracts,
    GET_JSON_OBJECT(properties, '$.quantidade_de_gerentes')::INT AS num_managers,
    GET_JSON_OBJECT(properties, '$.qual_a_quantidade_de_imoveis_administrados_')::INT AS num_managed_properties,
    GET_JSON_OBJECT(properties, '$.quantos_leads_recebem_por_mes')::INT AS num_monthly_leads,
    GET_JSON_OBJECT(properties, '$.ticket_medio_de_imoveis_de_venda')::INT AS average_sale_property_ticket,
    GET_JSON_OBJECT(properties, '$.ticket_medio_de_imoveis_para_locacao')::INT AS average_rent_property_ticket,
    GET_JSON_OBJECT(properties, '$.volume_de_repasse_mensal__vgv_r__')::INT AS monthly_repayment_volume_in_real,
    GET_JSON_OBJECT(properties, '$.volume_de_vendas__vgv_r__')::INT AS monthly_sale_volume_in_real,
    GET_JSON_OBJECT(properties, '$.quantidade_de_corretores')::INT AS num_real_estate_agents,
    GET_JSON_OBJECT(properties, '$.quantidade_de_imoveis_a_venda')::INT AS num_properties_for_sale,
    GET_JSON_OBJECT(properties, '$.quantidade_de_imoveis_para_locacao')::INT AS num_properties_for_rent,
    NULLIF(GET_JSON_OBJECT(properties, '$.utiliza_algum_crm_'), '') = 'Sim' AS has_crm,
    NULLIF(GET_JSON_OBJECT(properties, '$.anuncia_os_imoveis_online_'), '') = 'Sim' AS has_property_advertisement_online,
    NULLIF(GET_JSON_OBJECT(properties, '$.atua_como_correspondente_bancario_'), '') = 'Sim' AS is_correspondent_bank,
    NULLIF(GET_JSON_OBJECT(properties, '$.situacao_da_empresa'), '') = 'Sim' AS is_lost,
    NULLIF(GET_JSON_OBJECT(properties, '$.trabalha_com_financiamento_'), '') = 'Sim' AS has_financing,
    NULLIF(GET_JSON_OBJECT(properties, '$.trabalha_com_venda_e_locacao_'), '') LIKE '%Venda%' AS is_for_sale,
    NULLIF(GET_JSON_OBJECT(properties, '$.trabalha_com_venda_e_locacao_'), '') LIKE '%Locação%' AS is_for_rent,
    NULLIF(GET_JSON_OBJECT(properties, '$.trabalha_em_parceria_com_outras_imobiliarias_'), '') = 'Sim' AS has_partnerships_with_other_agencies,
    NULLIF(GET_JSON_OBJECT(properties, '$.digito_creci'), '') = 'PF' AS is_natural_person,
    NULLIF(GET_JSON_OBJECT(properties, '$.digito_creci'), '') = 'PJ' AS is_juridical_person,
    is_archived,
    GET_JSON_OBJECT(properties, '$.first_conversion_date')::TIMESTAMP AS ts_first_conversion,
    GET_JSON_OBJECT(properties, '$.recent_deal_close_date')::TIMESTAMP AS ts_recent_deal_close,
    GET_JSON_OBJECT(properties, '$.hubspot_owner_assigneddate')::TIMESTAMP AS ts_hubspot_owner_assigned,
    GET_JSON_OBJECT(properties, '$.hs_last_logged_call_date')::TIMESTAMP AS ts_last_logged_call,
    GET_JSON_OBJECT(properties, '$.notes_last_updated')::TIMESTAMP AS ts_notes_last_updated,
    ts_archived,
    ts_created,
    ts_updated,
    year,
    month,
    day
FROM
    datalake_hubspot_clean.company
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}