SELECT 
    regexp_replace(service_version, "[^0-9a-zA-Z_\-]+", "_") as service_version,
    id_service, 
    year, 
    month, 
    day,
    s_inputs.model_features.last_hsm_type,
    s_inputs.model_features.last_hsm_ts_diff,
    s_inputs.model_features.last_taxonomies,
    s_inputs.model_features.last_taxonomies_ts_diff,
    s_inputs.model_features.agent_is_active,
    s_inputs.model_features.owner_house_status_rented__sum,
    s_inputs.model_features.owner_house_status_edition__sum,
    s_inputs.model_features.owner_house_status_published__sum,
    s_inputs.model_features.owner_house_status_suspended__sum,
    s_inputs.model_features.owner_rent_flow_contract_sent__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_rent_flow_documentations__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_rent_flow_closed_deals__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_rent_flow_negotiations__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_rent_flow_prospects__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_offer_status_negotiation__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_offer_status_approved__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_offer_status_rejected__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_proposal_new__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_proposal_analysis__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_proposal_approved__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_proposal_rejected__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_documentation_under_analysis__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_documentation_approved__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_documentation_not_sent__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_contract_active__sum,
    s_inputs.model_features.owner_contract_pre_signature__sum,
    s_inputs.model_features.owner_contract_finalized__sum,
    s_inputs.model_features.owner_contract_canceled__sum,
    s_inputs.model_features.owner_contract_draft__sum,
    s_inputs.model_features.owner_contract_closing_signed__sum,
    s_inputs.model_features.owner_contract_closing_sent__sum,
    s_inputs.model_features.owner_inspection_status_commented__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.owner_contract_signed__count_over_40_days_rolling_windows,
    s_inputs.model_features.tenant_rent_flow_documentations__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_rent_flow_closed_deals__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_rent_flow_negotiations__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_contract_canceled__sum,
    s_inputs.model_features.tenant_contract_finalized__sum,
    s_inputs.model_features.tenant_contract_active__sum,
    s_inputs.model_features.tenant_contract_pre_signature__sum,
    s_inputs.model_features.tenant_contract_draft__sum,
    s_inputs.model_features.tenant_contract_closing_signed__sum,
    s_inputs.model_features.tenant_offer_status_negotiation__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_offer_status_approved__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_offer_status_rejected__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_offer_rejection_reason_rented_for_another_tenant_5a__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_offer_rejection_reason_tenant_does_not_agree_with_conditions__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_proposal_new__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_proposal_under_analysis__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_proposal_approved__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_proposal_rejected__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_documentation_under_analysis__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_documentation_approved__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_documentation_refused__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_documentation_not_sent__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_documentation_resend__sum_over_4_weeks_rolling_windows,
    s_inputs.model_features.tenant_log_diff_ts_proposal_expired_at,
    s_inputs.model_features.tenant_log_diff_ts_proposal_status_change,
    s_inputs.model_features.tenant_log_diff_ts_contract_started,
    s_inputs.model_features.tenant_log_diff_ts_contract_status_change,
    s_inputs.model_features.tenant_proposal_status,
    s_inputs.model_features.tenant_proposal_tenant_documentation_status,
    s_inputs.model_features.tenant_proposal_rejection_reason,
    s_inputs.model_features.tenant_contract_status,
    s_inputs.model_features.tenant_contract_previous_status,
    s_inputs.model_features.initial_text
FROM (
    SELECT 
        from_json(inputs, "Struct<
                                model_features: Struct<
                                    last_hsm_type: STRING,
                                    last_hsm_ts_diff: DOUBLE,
                                    last_taxonomies: STRING,
                                    last_taxonomies_ts_diff: DOUBLE,
                                    agent_is_active: BOOLEAN,
                                    owner_house_status_rented__sum: DOUBLE,
                                    owner_house_status_edition__sum: DOUBLE,
                                    owner_house_status_published__sum: DOUBLE,
                                    owner_house_status_suspended__sum: DOUBLE,
                                    owner_rent_flow_contract_sent__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_rent_flow_documentations__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_rent_flow_closed_deals__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_rent_flow_negotiations__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_rent_flow_prospects__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_offer_status_negotiation__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_offer_status_approved__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_offer_status_rejected__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_proposal_new__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_proposal_analysis__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_proposal_approved__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_proposal_rejected__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_documentation_under_analysis__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_documentation_approved__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_documentation_not_sent__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_contract_active__sum: DOUBLE,
                                    owner_contract_pre_signature__sum: DOUBLE,
                                    owner_contract_finalized__sum: DOUBLE,
                                    owner_contract_canceled__sum: DOUBLE,
                                    owner_contract_draft__sum: DOUBLE,
                                    owner_contract_closing_signed__sum: DOUBLE,
                                    owner_contract_closing_sent__sum: DOUBLE,
                                    owner_inspection_status_commented__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    owner_contract_signed__count_over_40_days_rolling_windows: DOUBLE,
                                    tenant_rent_flow_documentations__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_rent_flow_closed_deals__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_rent_flow_negotiations__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_contract_canceled__sum: DOUBLE,
                                    tenant_contract_finalized__sum: DOUBLE,
                                    tenant_contract_active__sum: DOUBLE,
                                    tenant_contract_pre_signature__sum: DOUBLE,
                                    tenant_contract_draft__sum: DOUBLE,
                                    tenant_contract_closing_signed__sum: DOUBLE,
                                    tenant_offer_status_negotiation__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_offer_status_approved__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_offer_status_rejected__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_offer_rejection_reason_rented_for_another_tenant_5a__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_offer_rejection_reason_tenant_does_not_agree_with_conditions__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_proposal_new__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_proposal_under_analysis__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_proposal_approved__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_proposal_rejected__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_documentation_under_analysis__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_documentation_approved__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_documentation_refused__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_documentation_not_sent__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_documentation_resend__sum_over_4_weeks_rolling_windows: DOUBLE,
                                    tenant_log_diff_ts_proposal_expired_at: TIMESTAMP,
                                    tenant_log_diff_ts_proposal_status_change: TIMESTAMP,
                                    tenant_log_diff_ts_contract_started: TIMESTAMP,
                                    tenant_log_diff_ts_contract_status_change: TIMESTAMP,
                                    tenant_proposal_status: STRING,
                                    tenant_proposal_tenant_documentation_status: STRING,
                                    tenant_proposal_rejection_reason: STRING,
                                    tenant_contract_status: STRING,
                                    tenant_contract_previous_status: STRING,
                                    initial_text: STRING
                                >
                            >") as s_inputs, 
        service_version, 
        id_service, 
        year, 
        month, 
        day
    FROM 
        datalake_emlio_clean.emlio_logs 
    WHERE 
        year = {year} 
        AND month = {month} 
        AND day = {day}
        AND id_service = 'citadel'
)