SELECT
    service_version,
    id_service,
    year,
    month,
    day,
    s_inputs.street,
    s_inputs.latitude,
    s_inputs.longitude,
    s_inputs.condominium_per_month,
    s_inputs.bathroom_count,
    s_inputs.bedroom_count,
    s_inputs.suite_count,
    s_inputs.total_area,
    s_inputs.parking_slots_count,
    s_inputs.has_fridge,
    s_inputs.has_bedroom_cabinets,
    s_inputs.has_pool,
    s_inputs.is_furnished,
    s_inputs.iptu_per_month,
    s_inputs.iptu_type,
    s_inputs.type,
    s_inputs.city,
    s_inputs.is_penthouse,
    s_inputs.has_chair_and_table,
    s_inputs.has_sofa,
    s_inputs.condominium_type,
    s_inputs.has_gym,
    s_inputs.has_glass_shower_stall,
    s_inputs.maintenance_condition,
    s_inputs.has_common_laundry,
    s_inputs.floor,
    s_inputs.has_ceiling_fan,
    s_inputs.has_gourmet_balcony,
    s_inputs.has_sports_court,
    s_inputs.has_party_saloon,
    s_inputs.has_air_conditioning,
    s_inputs.has_gas_heated_shower,
    s_inputs.has_kitchen_cabinets,
    s_inputs.has_barbecue_grill,
    s_inputs.has_sauna,
    s_inputs.has_elevator,
    s_inputs.h3_resolution_7__listing_sale_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__listing_sale_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__listing_sale_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__listing_sale_price_m2__max_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__listing__count_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__rented_rental_price_m2__p10_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__rented_rental_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__rented_rental_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__rented_rental_price_m2__max_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__rented_rental_price_m2__min_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__published_rental_price_m2__p10_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__published_rental_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__published_rental_price_m2__stddev_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__published_rental_price_m2__p90_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__rented__count_over_730_days_rolling_windows,
    s_inputs.h3_resolution_7__published__count_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__listing_sale_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__listing_sale_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__listing_sale_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__listing_sale_price_m2__stddev_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__listing_sale_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__listing__count_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__rented_rental_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__rented_rental_price_m2__max_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__published_rental_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__published_rental_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__published_rental_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__published_rental_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_8__published__count_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__listing_sale_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__listing_sale_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__listing_sale_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__listing_sale_price_m2__stddev_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__listing_sale_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__listing_sale_price_m2__max_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__rented_rental_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__rented_rental_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__rented_rental_price_m2__stddev_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__rented_rental_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__rented_rental_price_m2__max_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__rented_rental_price_m2__p90_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__published_rental_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__published_rental_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__published_rental_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_9__published_rental_price_m2__p90_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__listing_sale_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__listing_sale_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__listing_sale_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__listing_sale_price_m2__stddev_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__listing_sale_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__listing_sale_price_m2__max_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__listing_sale_price_m2__min_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__listing__count_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__rented_rental_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__rented_rental_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__rented_rental_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__rented_rental_price_m2__stddev_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__rented_rental_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__rented_rental_price_m2__p90_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__published_rental_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__published_rental_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__published_rental_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__published_rental_price_m2__stddev_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__published_rental_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__published_rental_price_m2__p90_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__rented__count_over_730_days_rolling_windows,
    s_inputs.h3_resolution_10__published__count_over_730_days_rolling_windows,
    s_inputs.h3_resolution_11__listing_sale_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_11__listing_sale_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_11__listing_sale_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_11__listing_sale_price_m2__stddev_over_730_days_rolling_windows,
    s_inputs.h3_resolution_11__listing_sale_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_11__listing_sale_price_m2__max_over_730_days_rolling_windows,
    s_inputs.h3_resolution_11__listing_sale_price_m2__min_over_730_days_rolling_windows,
    s_inputs.h3_resolution_11__listing__count_over_730_days_rolling_windows,
    s_inputs.h3_resolution_12__listing_sale_price_m2__q1_over_730_days_rolling_windows,
    s_inputs.h3_resolution_12__listing_sale_price_m2__avg_over_730_days_rolling_windows,
    s_inputs.h3_resolution_12__listing_sale_price_m2__median_over_730_days_rolling_windows,
    s_inputs.h3_resolution_12__listing_sale_price_m2__stddev_over_730_days_rolling_windows,
    s_inputs.h3_resolution_12__listing_sale_price_m2__q3_over_730_days_rolling_windows,
    s_inputs.h3_resolution_12__listing_sale_price_m2__max_over_730_days_rolling_windows,
    s_inputs.h3_resolution_12__listing_sale_price_m2__min_over_730_days_rolling_windows,
    s_inputs.h3_resolution_12__listing__count_over_730_days_rolling_windows,
    s_keys.house_id,
    s_keys.prediction_id,
    s_keys.x_original_requester,
    s_keys.x_request_via,
    s_keys.request_method,
    s_outputs.result.quantile_10,
    s_outputs.result.quantile_20,
    s_outputs.result.quantile_30,
    s_outputs.result.quantile_40,
    s_outputs.result.quantile_50,
    s_outputs.result.quantile_60,
    s_outputs.result.quantile_70,
    s_outputs.result.quantile_80,
    s_outputs.result.quantile_90,
    s_outputs.result.certainty
FROM (
    SELECT
        from_json(inputs, "Struct<
                                street: STRING,
                                latitude: DOUBLE,
                                longitude: DOUBLE,
                                condominium_per_month: DOUBLE,
                                bathroom_count: INTEGER,
                                bedroom_count: INTEGER,
                                suite_count: INTEGER,
                                total_area: INTEGER,
                                parking_slots_count: INTEGER,
                                has_fridge: INTEGER,
                                has_bedroom_cabinets: BOOLEAN,
                                has_pool: BOOLEAN,
                                is_furnished: BOOLEAN,
                                iptu_per_month: DOUBLE,
                                iptu_type: STRING,
                                type: STRING,
                                city: STRING,
                                is_penthouse: BOOLEAN,
                                has_chair_and_table: INTEGER,
                                has_sofa: INTEGER,
                                condominium_type: STRING,
                                has_gym: BOOLEAN,
                                has_glass_shower_stall: BOOLEAN,
                                maintenance_condition: STRING,
                                has_common_laundry: BOOLEAN,
                                floor: INTEGER,
                                has_ceiling_fan: BOOLEAN,
                                has_gourmet_balcony: BOOLEAN,
                                has_sports_court: BOOLEAN,
                                has_party_saloon: BOOLEAN,
                                has_air_conditioning: BOOLEAN,
                                has_gas_heated_shower: BOOLEAN,
                                has_kitchen_cabinets: BOOLEAN,
                                has_barbecue_grill: BOOLEAN,
                                has_sauna: BOOLEAN,
                                has_elevator: BOOLEAN,
                                h3_resolution_7__listing_sale_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__listing_sale_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__listing_sale_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__listing_sale_price_m2__max_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__listing__count_over_730_days_rolling_windows: INTEGER,
                                h3_resolution_7__rented_rental_price_m2__p10_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__rented_rental_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__rented_rental_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__rented_rental_price_m2__max_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__rented_rental_price_m2__min_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__published_rental_price_m2__p10_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__published_rental_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__published_rental_price_m2__stddev_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__published_rental_price_m2__p90_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_7__rented__count_over_730_days_rolling_windows: INTEGER,
                                h3_resolution_7__published__count_over_730_days_rolling_windows: INTEGER,
                                h3_resolution_8__listing_sale_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__listing_sale_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__listing_sale_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__listing_sale_price_m2__stddev_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__listing_sale_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__listing__count_over_730_days_rolling_windows: INTEGER,
                                h3_resolution_8__rented_rental_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__rented_rental_price_m2__max_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__published_rental_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__published_rental_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__published_rental_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__published_rental_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_8__published__count_over_730_days_rolling_windows: INTEGER,
                                h3_resolution_9__listing_sale_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__listing_sale_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__listing_sale_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__listing_sale_price_m2__stddev_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__listing_sale_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__listing_sale_price_m2__max_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__rented_rental_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__rented_rental_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__rented_rental_price_m2__stddev_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__rented_rental_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__rented_rental_price_m2__max_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__rented_rental_price_m2__p90_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__published_rental_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__published_rental_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__published_rental_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_9__published_rental_price_m2__p90_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__listing_sale_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__listing_sale_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__listing_sale_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__listing_sale_price_m2__stddev_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__listing_sale_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__listing_sale_price_m2__max_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__listing_sale_price_m2__min_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__listing__count_over_730_days_rolling_windows: INTEGER,
                                h3_resolution_10__rented_rental_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__rented_rental_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__rented_rental_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__rented_rental_price_m2__stddev_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__rented_rental_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__rented_rental_price_m2__p90_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__published_rental_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__published_rental_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__published_rental_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__published_rental_price_m2__stddev_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__published_rental_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__published_rental_price_m2__p90_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_10__rented__count_over_730_days_rolling_windows: INTEGER,
                                h3_resolution_10__published__count_over_730_days_rolling_windows: INTEGER,
                                h3_resolution_11__listing_sale_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_11__listing_sale_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_11__listing_sale_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_11__listing_sale_price_m2__stddev_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_11__listing_sale_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_11__listing_sale_price_m2__max_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_11__listing_sale_price_m2__min_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_11__listing__count_over_730_days_rolling_windows: INTEGER,
                                h3_resolution_12__listing_sale_price_m2__q1_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_12__listing_sale_price_m2__avg_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_12__listing_sale_price_m2__median_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_12__listing_sale_price_m2__stddev_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_12__listing_sale_price_m2__q3_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_12__listing_sale_price_m2__max_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_12__listing_sale_price_m2__min_over_730_days_rolling_windows: DOUBLE,
                                h3_resolution_12__listing__count_over_730_days_rolling_windows: INTEGER
        >") as s_inputs,
        FROM_JSON(outputs, "Struct<result: Struct<quantile_10: DOUBLE,
                                                  quantile_20: DOUBLE,
                                                  quantile_30: DOUBLE,
                                                  quantile_40: DOUBLE,
                                                  quantile_50: DOUBLE,
                                                  quantile_60: DOUBLE,
                                                  quantile_70: DOUBLE,
                                                  quantile_80: DOUBLE,
                                                  quantile_90: DOUBLE,
                                                  certainty: STRING>>") as s_outputs,
        FROM_JSON(service_keys, "Struct<house_id: STRING,
                                        prediction_id: STRING,
                                        x_original_requester: STRING,
                                        x_request_via: STRING,
                                        request_method: STRING>") as s_keys,
        service_version,
        id_service,
        year,
        month,
        day
    FROM
        datalake_emlio_clean.emlio_logs
    WHERE
        year = {year}
        AND month = {month}
        AND day = {day}
        AND id_service = 'girafales'
)
