SELECT 
    service_version, 
    id_service, 
    year, 
    month, 
    day,
    s_inputs.user__filter_value_price_type,
    s_inputs.user__filter_value_price_min,
    s_inputs.user__filter_value_price_max,
    s_inputs.user__filter_value_price_max_changed,
    s_inputs.user__filter_sale_value_valor_min,
    s_inputs.user__filter_sale_value_valor_max,
    s_inputs.user__filter_sale_value_valor_min_changed,
    s_inputs.user__filter_sale_value_valor_max_changed,
    s_inputs.user__filter_value_area_min,
    s_inputs.user__filter_value_area_max,
    s_inputs.user__map_borders_lat_center,
    s_inputs.user__map_borders_lng_center,
    s_inputs.user__map_borders_lat_ne,
    s_inputs.user__map_borders_lat_sw,
    s_inputs.user__map_borders_lng_ne,
    s_inputs.user__map_borders_lng_sw,
    s_inputs.user__hour_day,
    s_inputs.user__day_of_week,
    s_inputs.user__dropdown_address_type,
    s_inputs.address,
    s_inputs.user__search_location_context,
    s_inputs.user__listing_page_viewed_total_area__stddev_pop_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_bathroom_count__stddev_pop_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_condominium_per_month__avg_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_rent_over_area__stddev_pop_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_rent_over_area__avg_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_rent_over_area__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_floor__avg_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_condominium_per_month__stddev_pop_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_bathroom_count__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_has_elevator__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_bedroom_count__stddev_pop_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_floor__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_bedroom_count__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_total_area__stddev_pop_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_floor__stddev_pop_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_floor__stddev_pop_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_total_area__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_rent_over_area__stddev_pop_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_iptu_per_month__stddev_pop_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_total_area__avg_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_rent_per_month__stddev_pop_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_has_kitchen_cabinets__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_has_oven__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_has_pool__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_iptu_per_month__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_has_air_conditioning__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_has_bedroom_cabinets__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_condominium_per_month__stddev_pop_over_5_events_row_windows,
    s_inputs.user__user_platform,
    s_inputs.user__listing_page_viewed_rent_per_month__stddev_pop_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_iptu_per_month__avg_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_iptu_per_month__stddev_pop_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_suite_count__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_condominium_per_month__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_rent_per_month__avg_over_5_events_row_windows,
    s_inputs.user__listing_page_viewed_rent_per_month__avg_over_15_events_row_windows,
    s_inputs.user__listing_page_viewed_is_furnished__avg_over_15_events_row_windows,
    s_inputs.user__id,
    s_inputs.house__condominium_per_month,
    s_inputs.house__bathrooms_over_area,
    s_inputs.house__bedrooms_over_area,
    s_inputs.house__parking_slots_count,
    s_inputs.house__latitude,
    s_inputs.house__rent_over_area,
    s_inputs.house__bedroom_count,
    s_inputs.house__bathroom_count,
    s_inputs.house__type,
    s_inputs.house__sale_ts_last_publication,
    s_inputs.house__street,
    s_inputs.house__is_furnished,
    s_inputs.house__rent_ts_last_publication,
    s_inputs.house__rent_per_month,
    s_inputs.house__has_elevator,
    s_inputs.house__longitude,
    s_inputs.house__city,
    s_inputs.house__total_area,
    s_inputs.searched_house__haversine_distance,
    s_inputs.searched_house__estimated_difference_price_min,
    s_inputs.searched_house__estimated_difference_price_max,
    s_inputs.searched_house__estimated_difference_area_min,
    s_inputs.searched_house__estimated_difference_area_max,
    s_inputs.user_house_diff__rent_per_month__avg,
    s_inputs.user_house_diff__condominium__avg,
    s_inputs.user_house_diff__total_price__avg,
    s_inputs.user_house_diff__total_area__avg,
    s_inputs.user_house_diff__bedroom_count__avg,
    s_inputs.user_house_diff__bathroom_count__avg,
    s_inputs.user_house_diff__furnished__avg,
    s_inputs.house__listing_age,
    s_inputs.searched_house__street_match,
    s_inputs.user_id,
    s_inputs.house_id
FROM (
    SELECT 
        from_json(inputs, "Struct<user__filter_value_price_type: DOUBLE,
                                user__filter_value_price_min: DOUBLE,
                                user__filter_value_price_max: DOUBLE,
                                user__filter_value_price_max_changed: DOUBLE,
                                user__filter_sale_value_valor_min: DOUBLE,
                                user__filter_sale_value_valor_max: DOUBLE,
                                user__filter_sale_value_valor_min_changed: BOOLEAN,
                                user__filter_sale_value_valor_max_changed: BOOLEAN,
                                user__filter_value_area_min: DOUBLE,
                                user__filter_value_area_max: DOUBLE,
                                user__map_borders_lat_center: DOUBLE,
                                user__map_borders_lng_center: DOUBLE,
                                user__map_borders_lat_ne: DOUBLE,
                                user__map_borders_lat_sw: DOUBLE,
                                user__map_borders_lng_ne: DOUBLE,
                                user__map_borders_lng_sw: DOUBLE,
                                user__hour_day: DOUBLE,
                                user__day_of_week: INTEGER,
                                user__dropdown_address_type: STRING,
                                address: STRING,
                                user__search_location_context: DOUBLE,
                                user__listing_page_viewed_total_area__stddev_pop_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_bathroom_count__stddev_pop_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_condominium_per_month__avg_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_rent_over_area__stddev_pop_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_rent_over_area__avg_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_rent_over_area__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_floor__avg_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_condominium_per_month__stddev_pop_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_bathroom_count__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_has_elevator__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_bedroom_count__stddev_pop_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_floor__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_bedroom_count__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_total_area__stddev_pop_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_floor__stddev_pop_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_floor__stddev_pop_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_total_area__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_rent_over_area__stddev_pop_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_iptu_per_month__stddev_pop_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_total_area__avg_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_rent_per_month__stddev_pop_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_has_kitchen_cabinets__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_has_oven__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_has_pool__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_iptu_per_month__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_has_air_conditioning__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_has_bedroom_cabinets__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_condominium_per_month__stddev_pop_over_5_events_row_windows: DOUBLE,
                                user__user_platform: DOUBLE,
                                user__listing_page_viewed_rent_per_month__stddev_pop_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_iptu_per_month__avg_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_iptu_per_month__stddev_pop_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_suite_count__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_condominium_per_month__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_rent_per_month__avg_over_5_events_row_windows: DOUBLE,
                                user__listing_page_viewed_rent_per_month__avg_over_15_events_row_windows: DOUBLE,
                                user__listing_page_viewed_is_furnished__avg_over_15_events_row_windows: DOUBLE,
                                user__id: INTEGER,
                                house__condominium_per_month: DOUBLE,
                                house__bathrooms_over_area: DOUBLE,
                                house__bedrooms_over_area: DOUBLE,
                                house__parking_slots_count: DOUBLE,
                                house__latitude: DOUBLE,
                                house__rent_over_area: DOUBLE,
                                house__bedroom_count: DOUBLE,
                                house__bathroom_count: DOUBLE,
                                house__type: DOUBLE,
                                house__sale_ts_last_publication: TIMESTAMP,
                                house__street: STRING,
                                house__is_furnished: DOUBLE,
                                house__rent_ts_last_publication: TIMESTAMP,
                                house__rent_per_month: DOUBLE,
                                house__has_elevator: DOUBLE,
                                house__longitude: DOUBLE,
                                house__city: DOUBLE,
                                house__total_area: DOUBLE,
                                searched_house__haversine_distance: DOUBLE,
                                searched_house__estimated_difference_price_min: DOUBLE,
                                searched_house__estimated_difference_price_max: DOUBLE,
                                searched_house__estimated_difference_area_min: DOUBLE,
                                searched_house__estimated_difference_area_max: DOUBLE,
                                user_house_diff__rent_per_month__avg: DOUBLE,
                                user_house_diff__condominium__avg: DOUBLE,
                                user_house_diff__total_price__avg: DOUBLE,
                                user_house_diff__total_area__avg: DOUBLE,
                                user_house_diff__bedroom_count__avg: DOUBLE,
                                user_house_diff__bathroom_count__avg: DOUBLE,
                                user_house_diff__furnished__avg: DOUBLE,
                                house__listing_age: INTEGER,
                                searched_house__street_match: BOOLEAN,
                                user_id: INTEGER,
                                house_id: INTEGER>") as s_inputs, 
        service_version, 
        id_service, 
        year, 
        month, 
        day
    FROM 
        datalake_emlio_clean.emlio_logs 
    WHERE 
        year = {year} 
        AND month = {month} 
        AND day = {day}
        AND id_service = 'p-click'
)