SELECT
    id,
    propose AS id_propose,
    billingtype AS id_billing_type,
    status AS id_status,
    gateway AS id_gateway,
    userinsert AS id_user_insert,
    userupdate AS id_user_update,
    unicid,
    customer,
    subscription,
    paymentlink AS payment_link,
    invoiceurl AS invoice_url,
    description,
    value,
    netvalue,
    BOOLEAN(active) AS is_active,
    duedate AS dt_due,
    originalduedate AS dt_original_due,
    datecreated AS dt_created,
    clientPaymentDate AS dt_client_payment,
    confirmedDate AS dt_confirmed,
    creditDate AS dt_credit,
    dateinsert AS ts_inserted,
    dateupdate AS ts_updated
FROM
    datalake_velo_raw.fiancavelo_payment
