from enum import Enum


class TaskEnum(Enum):
    ADD_DEFAULT_ROW = "add_default_row"
    DATA_QUALITY_TESTS = "data_quality_tests"
    DUMMY_JOB_CLUSTER_FINISHED = "dummy_job_cluster_finished"
    EXECUTE_JOB_CLUSTER = "execute_job_cluster"
    GENERATE_DATABASE_TABLE_METRICS = "generate_database_table_metrics"
    LOAD_CDC_CLEAN = "load_cdc_clean"
    LOAD_CDC_RAW = "load_cdc_raw"
    LOAD_CDC_TRANSACTIONAL = "load_cdc_transactional"
    LOAD_API_RAW = "load_api_raw"
    LOAD_GSHEETS = "load_gsheets"
    LOAD_CUSTOM = "load_custom"
    LOAD_DMS_CDC_CLEAN = "load_dms_cdc_clean"
    LOAD_DMS_CDC_RAW = "load_dms_cdc_raw"
    LOAD_MONGO_RAW = "load_mongo_raw"
    LOAD_POSTGRES_RAW = "load_postgres_raw"
    LOAD_WONKA = "load_wonka"
    LOAD_QUERY = "load_query"
    LOAD_DELTA = "load_delta"
    LOAD_CDF_TO_DATAZORD = "load_cdf_to_datazord"
    OPTIMIZE_DELTA_TABLE = "optimize_delta_table"
    REGISTER_DELTA_TABLE = "register_delta_table"
    REPROCESSING_GUARD = "reprocessing_guard"
    SKIP_RUN = "skip_run"
    SYNC_METADATA = "sync_metadata"
    LOAD_CORE_MODEL = "load_core_model"
    BUILD_QUBE_DIMENSION = "build_qube_dimension"
    BUILD_QUBE_MEASURE = "build_qube_measure"
    BUILD_QUBE_METRIC = "build_qube_metric"
    QUBE_REGISTER_DELTA_TABLE = "qube_register_delta_table"
    CREATE_QUERY_VIEW = "create_query_view"
