SELECT
    id AS id_affiliate_data,
    REV AS rev,
    rEVTYPE AS rev_type,
    ativo AS is_active,
    cidadeAtuacao AS operation_city,
    contadorPlanilhaDeLeads AS count_leads_sheet,
    contratosFechados AS closed_contracts,
    idPlanilhaGdocs AS id_gdocs_sheet,
    inicioAtuacao AS ts_operation_start,
    preferenciaPagamento AS payment_preference,
    principaisBairrosAtuacao AS main_operation_neighborhoods,
    tipoAfiliado AS affiliate_type_old,
    ultimoCalculoComissaoIndicado AS ts_last_commission_calculation_indicated,
    usuario_id AS id_user,
    verificado AS is_verified,
    indicadoPor_id AS id_indicated_by,
    ativo_MOD AS mod_is_active,
    numeroCreci AS creci_number,
    dataComunicacaoEnvioCartao AS ts_card_sent_communication,
    semanaUltimaComunicacaoBalanco AS last_week_balance_communication,
    roofTopper AS is_roof_topper,
    roofTopper_MOD AS mod_is_roof_topper,
    origin,
    affiliateType AS affiliate_type,
    doormanAffiliateData_id AS id_doorman_affiliate_data
FROM
    datalake_ebdb_test_raw.DadosAfiliado_AUD