---
tables_list:
  - AgentSupervisor
  - AgentStateRawData
  - Campaign
  - CampaignCustomer
  - ConfigReasons
  - Customer
  - Disposition
  - DispositionDetail
  - DispositionPlan
  - Info_AgentStatus
  - Info_CallDirection
  - Info_CampaignType
  - Info_DispositionType
  - Info_PbxDisposition
  - Info_ReasonType
  - Info_StatusId
  - LoginRawData
  - MailingInformation
  - AttemptsRawData
  - Reason
  - Users
  - PbxBillingData
  - QUINTO_ANDAR_20200505_Mailing
  - OPS_Mailing_LayoutId_4
  - OPS_Mailing_LayoutId_7
list_out_of_pattern:
  - QUINTO_ANDAR_20200505_Mailing: mailing
  - OPS_Mailing_LayoutId_4: reprocessing_mailing
  - OPS_Mailing_LayoutId_7: pp_multi_mailing
partition_cols:
  - year
  - month
  - day
