WITH count_metrics AS (
    SELECT 
        id_user,
        id_event_type,
        id_house,
        journey,
        subjourney,
        days_since_last_event,
        COUNT_IF(id_event_type=1) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS bookings,
        COUNT_IF(id_event_type=1 AND dt_secretary_action IS NOT NULL) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS bookings_by_sec,
        COUNT_IF(id_event_type=1 AND dt_agent_action IS NOT NULL) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS bookings_by_agent,
        COUNT_IF(id_event_type=1 AND dt_buyer_action IS NOT NULL) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS bookings_by_buyer,
        COUNT_IF(id_event_type=2) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS visits_completed,
        COUNT_IF(id_event_type=2 AND dt_secretary_action IS NOT NULL) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS visits_completed_by_sec,
        COUNT_IF(id_event_type=2 AND dt_agent_action IS NOT NULL) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS visits_completed_by_agent,
        COUNT_IF(id_event_type=2 AND dt_buyer_action IS NOT NULL) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS visits_completed_by_buyer,
        COUNT_IF(id_event_type=7) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS visits_cancelled,
        COUNT_IF(id_event_type=7 AND dt_secretary_action IS NOT NULL) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS visits_cancelled_by_sec,
        COUNT_IF(id_event_type=7 AND dt_agent_action IS NOT NULL) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS visits_cancelled_by_agent,
        COUNT_IF(id_event_type=7 AND dt_buyer_action IS NOT NULL) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS visits_cancelled_by_buyer,
        COUNT_IF(id_event_type=1) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS houses,
        COUNT_IF(id_event_type=3) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS offers_submitted,
        COUNT_IF(id_event_type=4) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS offers_accepted,
        COUNT_IF(id_event_type=8) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS offers_rejected,
        COUNT(dt_secretary_action) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS secretary_action,
        COUNT(dt_agent_action) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS agent_action,
        COUNT(dt_buyer_action) OVER (PARTITION BY id_user, subjourney ORDER BY ts_event) AS buyer_action,
        COUNT_IF(id_event_type=1) OVER (PARTITION BY id_user ORDER BY ts_event) AS booking_per_user,
        COUNT_IF(id_event_type=7 OR id_event_type=2) OVER (PARTITION BY id_user ORDER BY ts_event) AS visit_closed_per_user,
        dt_active_search,
        dt_secretary_action,
        dt_agent_action,
        dt_buyer_action,
        dt_event,
        ts_event
    FROM 
        datalake_sale_journey.sale_journey
)
SELECT
    MD5(cm.id_user || '-' || cm.journey || '-' || cm.subjourney) AS sk_subjourney,
    cm.id_user || '-' || cm.journey || '-' || cm.subjourney AS bk_subjourney,
    MD5(cm.id_user || '-' || cm.journey) AS sk_journey,
    cm.id_user || '-' || cm.journey AS bk_journey,
    COALESCE(cm.id_user, -1) AS sk_user,
    COALESCE(cm.id_event_type, -1) AS sk_event_type,
    COALESCE(cm.id_house, -1) AS sk_house,
    COALESCE(BIGINT(DATE_FORMAT(cm.dt_event, 'yyyyMMdd')), -1) AS sk_event_date,
    COALESCE(BIGINT(DATE_FORMAT(cm.dt_active_search, 'yyyyMMdd')), -1) AS sk_active_search_date,
    COALESCE(BIGINT(DATE_FORMAT(cm.dt_secretary_action, 'yyyyMMdd')), -1) AS sk_secretary_action_date,
    COALESCE(BIGINT(DATE_FORMAT(cm.dt_agent_action, 'yyyyMMdd')), -1) AS sk_agent_action_date,
    COALESCE(BIGINT(DATE_FORMAT(cm.dt_buyer_action, 'yyyyMMdd')), -1) AS sk_buyer_action_date,
    cm.journey,
    cm.subjourney,
    cm.days_since_last_event,
    cm.bookings AS total_bookings,
    cm.bookings_by_sec AS total_bookings_by_sec,
    cm.bookings_by_agent AS total_bookings_by_agent,
    cm.bookings_by_buyer AS total_bookings_by_buyer,
    cm.visits_completed AS total_visits_complete,
    cm.visits_completed_by_sec AS total_visits_complete_by_sec,
    cm.visits_completed_by_agent AS total_visits_complete_by_agent,
    cm.visits_completed_by_buyer AS total_visits_complete_by_buyer,
    cm.visits_cancelled AS total_visits_cancelled,
    cm.visits_cancelled_by_sec AS total_visits_cancelled_by_sec,
    cm.visits_cancelled_by_agent AS total_visits_cancelled_by_agent,
    cm.visits_cancelled_by_buyer AS total_visits_cancelled_by_buyer,
    cm.houses AS total_houses_booked,
    cm.offers_submitted AS total_offers_submitted,
    cm.offers_accepted AS total_offers_accepted,
    cm.offers_rejected AS total_offers_offers_rejected,
    cm.secretary_action AS total_secretary_action,
    cm.agent_action AS total_agent_action,
    cm.buyer_action AS total_buyer_action,
    (cm.booking_per_user - cm.visit_closed_per_user) AS pending_visits_per_user,
    dd.day,
    dd.month,
    dd.year,
    NOW() AS ts_load
FROM 
    count_metrics AS cm
JOIN
    dw_public.dim_date AS dd
        ON COALESCE(BIGINT(DATE_FORMAT(cm.dt_event, 'yyyyMMdd')), -1) = dd.sk_date
QUALIFY
    ROW_NUMBER() OVER (PARTITION BY cm.id_user, cm.journey, cm.subjourney ORDER BY cm.ts_event DESC) = 1
