SELECT
    id_note,
    id_hubspot_owner,
    ids_attachments,
    ids_associated_tickets,
    ids_associated_contacts,
    ids_associated_companies,
    ids_associated_deals,
    note_body,
    ts_note,
    ts_created,
    ts_updated,
    year,
    month,
    day
FROM
    datalake_hubspot.note_history
QUALIFY
    ROW_NUMBER() OVER(PARTITION BY id_note ORDER BY ts_updated DESC) = 1