SELECT
  id,
  visitante_id AS id_visitor,
  agente_id AS id_agent,
  coordinateid AS id_coordinate,
  encerrado AS is_closed,
  imovel_id AS id_house,
  primeiravez AS is_first_time,
  visita_id AS id_visit,
  fluxolocacao_id AS id_rent_flow,
  reagendadode_id AS id_rescheduled_booking,
  followupdetails_id AS id_fup_details,
  jobfotografo_id AS id_photo_job,
  atendente_id AS id_attendant,
  origemultimaatualizacao_id AS id_last_update_origin,
  external_id AS id_schedule,
  structured AS structured,
  codigo AS code,
  durationinslots AS slots_duration,
  businesscontext AS business_context,
  intention AS buyer_intention,
  checkinstatus AS checkin_status,
  visitordatetime AS visitor_id_date_slot,
  status,
  preferecontato AS contact_preference,
  hash,
  slotdia AS slot_day,
  fupvisita AS visit_fup,
  tipo AS type,
  agentefixo AS is_agent_fixed,
  comentariofupvisita AS visit_fup_comment,
  informeinquilinopendente AS is_tenant_notification_pending,
  confirmado AS is_confirmed,
  permitirconflito AS is_conflict_allowed,
  data AS dt_booking,
  proxnotfup AS ts_next_not_fup,
  datafupvisita AS ts_visit_fup,
  avisadoentrouemnegociacao AS ts_negotiation_start_notified,
  criadoem AS ts_created,
  atualizadoem AS ts_updated
FROM
  datalake_ebdb_raw.Agendamento
