SELECT
  id_offer AS sk_offer,
  id_buyer AS sk_buyer,
  id_owner AS sk_owner,
  id_house AS sk_house,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_sale_agreement_signed,1, 10),'-','') AS BIGINT), -1) AS sk_sale_agreement_signed_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_onboarding_ended,1, 10),'-','') AS BIGINT), -1) AS sk_onboarding_ended_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_sale_agreement_cancelled,1, 10),'-','') AS BIGINT), -1) AS sk_sale_agreement_cancelled_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_legal_analysis_ended,1, 10),'-','') AS BIGINT), -1) AS sk_legal_analysis_ended_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_legaut_analysis_started,1, 10),'-','') AS BIGINT), -1) AS sk_legaut_analysis_started_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_legaut_analysis_ended,1, 10),'-','') AS BIGINT), -1) AS sk_legaut_analysis_ended_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_legal_risk_started,1, 10),'-','') AS BIGINT), -1) AS sk_legal_risk_started_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_legal_risk_ended,1, 10),'-','') AS BIGINT), -1) AS sk_legal_risk_ended_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_bank_legal_analysis_started,1, 10),'-','') AS BIGINT), -1) AS sk_bank_legal_analysis_started,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_credit_analysis_started,1, 10),'-','') AS BIGINT), -1) AS sk_credit_analysis_started_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_credit_analysis_ended,1, 10),'-','') AS BIGINT), -1) AS sk_credit_analysis_ended_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_financing_started,1, 10),'-','') AS BIGINT), -1) AS sk_financing_started_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_financing_ended,1, 10),'-','') AS BIGINT), -1) AS sk_financing_ended_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_notes_registry_started,1, 10),'-','') AS BIGINT), -1) AS sk_notes_registry_started_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_notes_registry_ended,1, 10),'-','') AS BIGINT), -1) AS sk_notes_registry_ended_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_house_registry_started,1, 10),'-','') AS BIGINT), -1) AS sk_house_registry_started_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_house_registry_ended,1, 10),'-','') AS BIGINT), -1) AS sk_house_registry_ended_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_sale_key_delivered,1, 10),'-','') AS BIGINT), -1) AS sk_sale_key_delivered_date,
  COALESCE(CAST(REPLACE(SUBSTRING(dt_sale_transacton_paid,1, 10),'-','') AS BIGINT), -1) AS sk_sale_transaction_paid_date,
  --
  id_closing_specialist,
  id_pre_specialist,
  id_post_specialist,
  id_start_financing_specialist,
  id_follow_up_financing_specialist,
  id_end_financing_specialist,
  id_credit_specialist,
  id_notes_registry_specialist,
  id_real_estate_register_specialist,
  --
  days_sale_agreement_signed_to_house_registry_started,
  days_sale_agreement_signed_to_house_registry_ended,
  days_sale_agreement_signed_to_sale_agreement_cancelled,
  days_sale_agreement_signed_to_onboarding_ended,
  days_sale_agreement_signed_to_credit_analysis_started,
  days_sale_agreement_signed_to_credit_analysis_ended,
  days_sale_agreement_signed_to_financing_started,
  days_sale_agreement_signed_to_notes_registry_started,
  days_sale_agreement_signed_to_notes_registry_ended,
  days_sale_agreement_signed_to_legaut_analysis_started,
  days_sale_agreement_signed_to_legaut_analysis_ended,
  days_sale_agreement_signed_to_legal_risk_ended,
  days_sale_agreement_signed_to_bank_legal_analysis_started,
  days_legal_risk_started_to_legal_risk_ended,
  days_legal_risk_ended_to_legal_analysis_ended,
  days_legaut_analysis_started_to_legaut_analysis_ended,
  days_legaut_analysis_ended_to_legal_risk_ended,
  days_legal_analysis_ended_notes_registry_ended,
  days_bank_legal_analysis_started_to_financing_ended,
  days_bank_legal_analysis_started_to_house_registry_started,
  days_credit_analysis_started_to_credit_analysis_ended,
  days_credit_analysis_ended_to_bank_legal_analysis_started,
  days_financing_started_to_financing_ended,
  days_financing_ended_to_house_registry_ended,
  days_financing_ended_to_house_registry_started,
  days_notes_registry_started_to_notes_registry_ended,
  days_house_registry_started_to_house_registry_ended,
  days_notes_registry_ended_to_house_registry_started,
  days_notes_registry_ended_to_house_registry_ended,
  days_house_registry_ended_to_sale_key_delivered,
  days_house_registry_ended_to_sale_transaction_paid,
  --
  ts_updated,
  ts_load AS ts_monday_load,
  NOW() AS ts_load
FROM
    datalake_sale_closing_flows.closing_flow
