SELECT
  judicial_process,
  judgment,
  judgment_second_instance,
  COALESCE(judgment_second_instance, judgment) AS judgment_last,
  agreement_in,
  no_strings_attached_agreement,
  county,
  judge_rapporteur,
  procedural_duration,
  procedural_duration_until_sentencing,
  judge,
  segment,
  verdict,
  status,
  time_between_dismissal_and_distribution,
  grouped_time_between_dismissal_and_distribution,
  trt,
  lawsuit_value,
  condemnation_judgment_value,
  final_execution,
  verdict_value,
  defendant_segment,
  position_held,
  CASE
    WHEN position_held IN ('Vendedor de imóveis', 
                            'Executiva de Vendas', 
                            'Diretora executiva de vendas', 
                            'Executiva de vendas', 
                            'Executivo de vendas', 
                            'Vendedor', 
                            'Vendedora de imóveis', 
                            'Operador de call center', 
                            'Vendedora', 
                            'Assistente de vendas', 
                            'Auxiliar de vendas imobiliárias', 
                            'Atendente de vendas', 
                            'Promotora de Vendas', 
                            'Assistente técnico de vendas', 
                            'Representante comercial de vendas', 
                            'Vendedor de imóveis/ Analista de Crédito', 
                            'Promotora de vendas de imóveis em construção') THEN 'vendedor' 
    WHEN position_held IN ('Consultor imobiliário', 
                            'Consultora natura orientadora', 
                            'Consultora Natura Orientadora', 
                            'Consultora Natura Orientadora II', 
                            'Consultora Natura', 
                            'Consultor de vendas', 
                            'Revendedora Executiva', 
                            'Consultora de vendas', 
                            'Consultora líder', 
                            'Líder de Negócios', 
                            'Coordenadora Natura Orientadora', 
                            'Recrutadora de Corretores', 
                            'Gestora de Equipe de Vendas', 
                            'Diretor de marketing e novos negócios') THEN 'consultora orientadora' 
    WHEN position_held IN ('Motorista') THEN 'motorista' 
    WHEN position_held IN ('Corretor de imóveis', 
                            'Corretor de Imóveis', 
                            'Corretor Imobiliário', 
                            'Corretora de imóveis') THEN 'corretor de imóveis' 
    WHEN position_held IN ('Motofretista', 
                            'Motofretista/operador logístico', 
                            'Motociclista entregador', 
                            'Motoboy', 
                            'Entregador', 
                            'Motoqueiro- entregador', 
                            'Entregador Delivery', 
                            'Motorista de Coleta e Entrega') THEN 'motofretista' 
    ELSE 'outros'
  END AS position_held_group,
  is_sentence_reverted,
  is_sentence_reverted_second_instance,
  COALESCE(is_sentence_reverted_second_instance, is_sentence_reverted) AS is_sentence_reverted_last,
  is_active_platform_user,
  dt_distribuition,
  dt_admission,
  dt_resignation
FROM 
  datalake_gsheets_clean.legal_base_docato