sheets_info:
  forecast_costs_supply_daily:
    sheet_id: 1-d6ETiprXYx6DRYIfg2PblFODxNwsIZHO6WnY9f8pfY
    sheet_name: forecast_supply_costs
    clean_table_name: forecast_costs_supply_daily
    sheet_context: growth

  forecast_supply_daily:
    sheet_id: 1JzGUC-BCSkRP5jiFrnrksdBKkPfPHqDzEvOGXkXVgQ8
    sheet_name: forecast_supply
    clean_table_name: forecast_supply_daily
    sheet_context: growth

  mkt_cost_target:
    sheet_id: 1lOcpeZ2YBrpqFi_sIJxt98sgbMfGEES7uhAASxzOuyg
    sheet_name: targets
    clean_table_name: mkt_cost_target
    sheet_context: growth

  rental_prospect_target:
    sheet_id: 1taBS_WX9zDX5Qsn6PHlAT-yise-EJsLADrrZg6-yztc
    sheet_name: targets
    clean_table_name: rental_prospect_target
    sheet_context: growth

  rental_tof_daily_target:
    sheet_id: 1OcIYUi2dFL5-1FW5xSHWHreRGYn7p3Z_gCAyHzQsxQM
    sheet_name: targets
    clean_table_name: rental_tof_daily_target
    sheet_context: growth

  rental_tof_monthly_target:
    sheet_id: 1Ji4j5-MpBymO7-UvMkoC4Wx3aOcm6EhUbTkmdDX6tEE
    sheet_name: targets
    clean_table_name: rental_tof_monthly_target
    sheet_context: growth

  rental_tof_weekly_target:
    sheet_id: 1TfiFaINTa3BEy9d73tR3uW1A3FhLMSLKW7cjDW0Jjgw
    sheet_name: targets
    clean_table_name: rental_tof_weekly_target
    sheet_context: growth

  supply_targets_2022:
    sheet_id: 1rU-ptg-ZtD0WdnbXnUVpGw8Lrf-0grc2IitwEmn2yZ0
    sheet_name: supply_targets_2022
    clean_table_name: supply_targets_2022
    sheet_context: for_rent_targets

  supply_targets_2024:
    sheet_id: 1wMxo1URFvbx11Yj0O4vpNJ20S4CftOCnuyx9q5WR7Eo
    sheet_name: supply_targets_2024
    clean_table_name: supply_targets_2024
    sheet_context: for_rent_targets
  
  supply_targets_2025:
    sheet_id: 1VjT9_onWiIVDcsCXgwz6AdvbS_7PadWT-kdd0ara2hY
    sheet_name: rent_supply_targets_2025
    clean_table_name: supply_targets_2025
    sheet_context: for_rent_targets

  supply_targets_2024_cohort:
    sheet_id: 1V5HQxP9pI9pm7P4si59P40TJvGxGS1doVUTX-R3h0iY
    sheet_name: supply_targets_2024_cohort
    clean_table_name: supply_targets_2024_cohort
    sheet_context: for_rent_targets

  rent_supply_targets_cohort_2025:
    sheet_id: 1UAal1Buce509lxAXRjs7206UB_hnYdl6F5Yk0Mu9gcA
    sheet_name: rent_supply_targets_cohort_2025
    clean_table_name: rent_supply_targets_cohort_2025
    sheet_context: for_rent_targets

  rent_supply_budget_2024:
    sheet_id: 1KKsISTNvrwmP-XTZvBg06TRl4tdtFj2DuqtoK29tM_U
    sheet_name: supply_targets_2024
    clean_table_name: rent_supply_budget_2024
    sheet_context: for_rent_targets

  rent_supply_budget_2025:
    sheet_id: 16O4qMihQqod70lnoJ3hDHzjUzt17mDmkipr9BOgBvBk
    sheet_name: rent_supply_targets_2025
    clean_table_name: rent_supply_budget_2025
    sheet_context: for_rent_targets

  sale_prospect_target:
    sheet_id: 1KT6ZqNaxqWWc8V9vdBUjHQbiV_PsHKRxkN9_6IsBL8g
    sheet_name: targets
    clean_table_name: sale_prospect_target
    sheet_context: growth

  sale_tof_daily_target:
    sheet_id: 1Al9_yFNONYeOElnKUY-ZWZB1e2RlLWIzkRBOkJEcglw
    sheet_name: targets
    clean_table_name: sale_tof_daily_target
    sheet_context: growth

  sale_tof_monthly_target:
    sheet_id: 1YIKHbpVODGkuyP9D7qB_zmg5sZpJw63DkykyPdT-qjg
    sheet_name: targets
    clean_table_name: sale_tof_monthly_target
    sheet_context: growth

  sale_tof_weekly_target:
    sheet_id: 1Xwb1T6FMSmhzx3xR-PnAHRaOn6IS1f4s6-eLyaDhwCw
    sheet_name: targets
    clean_table_name: sale_tof_weekly_target
    sheet_context: growth

  supply_funnel_unique:
      sheet_id: 1WhUjDG1gYEZPlADVEloRw_1bbWsY96p1tTi8VQ4ndiA
      sheet_name: supply_funil_unique
      clean_table_name: supply_funnel_unique
      sheet_context: growth