SELECT
    id,
    rev,
    revtype AS rev_type,
    workContract_id AS id_work_contract,
    preferredRegion_id AS id_preferred_region,
    companyUuid AS uuid_company,
    companyUuid_MOD AS mod_uuid_company,
    perfil AS profile,
    tipoAgente AS agent_type,
    cargoImobiliaria AS position_in_real_estate_agency,
    identificacaoImobiliaria AS real_estate_agency,
    numeroCRECI AS creci_number,
    code,
    ativo AS is_active,
    edicaoAgendaBloqueada AS is_blocked_schedule_edition,
    passiveLeadReceiver AS is_passive_lead_receiver,
    serviceLinkActive AS is_service_link_active,
    opted_for_online_support AS has_opted_for_online_support,
    tipoAgente_MOD AS mod_agent_type,
    cargoImobiliaria_MOD AS mod_position_in_real_estate_agency,
    identificacaoImobiliaria_MOD AS mod_real_estate_agency,
    numeroCRECI_MOD AS mod_creci_number,
    code_MOD AS mod_code,
    passiveLeadReceiver_MOD AS mod_passive_lead_receiver,
    serviceLinkActive_MOD AS mod_service_link_active,
    opted_for_online_support_MOD AS has_opted_for_online_support_MOD
FROM
    datalake_ebdb_raw.dadosagente_aud 