drop table if exists staging.zendesk_dim_ticket;
create table if not exists staging.zendesk_dim_ticket (
	sk_ticket bigint,
	subject varchar(MAX),
	description varchar(MAX),
	ticket_via varchar(15),
	channel varchar(15),
	group_name varchar,
	priority varchar(10),
	recipient varchar,
	tags varchar(MAX),
	status varchar(20),
	has_public_comments boolean,
	custom_fields varchar(MAX),
	score varchar(20),
	reason varchar,
	comment varchar(MAX),
	request_type varchar,
	client_type varchar(30),
	customer_type_tag varchar(50),
	contact_motivation_tag varchar(50),
	contact_theme_tag varchar(100),
	ts_created timestamp,
	ts_created_local timestamp,
	ts_updated timestamp,
	ts_updated_local timestamp,
	ts_load timestamp
);