drop table if exists staging.zendesk_fact_tickets;
create table if not exists staging.zendesk_fact_tickets (
    sk_ticket bigint,
    sk_house_listing bigint,
    sk_contract bigint,
    sk_client bigint,
    sk_owner bigint,
    sk_zendesk_requester_user bigint,
    sk_zendesk_submitter_user bigint,
    sk_zendesk_assignee_user bigint,
    sk_created_date integer,
    sk_created_date_local integer,
    sk_solved_date integer,
    sk_solved_date_local integer,
    sk_closed_date integer,
    sk_closed_date_local integer,
    sk_initially_assigned integer,
    sk_initially_assigned_local integer,
    sk_last_assigned integer,
    sk_last_assigned_local integer,
    sk_extraction_date integer,
    total_group_stations integer,
    total_assignee_stations integer,
    minutes_first_reply_time_calendar integer,
    minutes_first_reply_time_business integer,
    minutes_first_resolution_time_calendar integer,
    minutes_first_resolution_time_business integer,
    minutes_requester_wait_time_calendar integer,
    minutes_requester_wait_time_business integer,
    minutes_agent_wait_time_calendar integer,
    minutes_agent_wait_time_business integer,
    minutes_on_hold_time_calendar integer,
    minutes_on_hold_time_business integer,
    minutes_full_resolution_time_calendar integer,
    minutes_full_resolution_time_business integer,
    reopens,
    replies,
    ts_initially_assigned timestamp,
    ts_initially_assigned_local timestamp with time zone,
    ts_last_assigned timestamp,
    ts_last_assigned_local timestamp with time zone,
    ts_solved timestamp,
    ts_solved_local timestamp with time zone,
    ts_updated timestamp,
    ts_updated_local timestamp with time zone,
    ts_closed timestamp,
    ts_closed_local timestamp with time zone,
    ts_load timestamp
);
