SELECT
  id AS id_contract,
  imovel_id AS id_house,
  google_drive_id AS id_google_drive,
  property_address_id AS id_property_address,
  mailing_address_id AS id_mailing_address,
  landlord_account_id AS id_landlord_account,
  tenant_account_id AS id_tenant_account,
  landlord_user_id AS id_landlord_user,
  tenant_user_id AS id_tenant_user,
  condo_manager_id AS id_condo_manager,
  info_payment_id AS id_payment_info,
  partner_id AS id_partner,
  external_id AS id_external,
  status,
  guarantee,
  condominium_from_account_type,
  iptu_from_account_type,
  iptu_to_account_type,
  condominium_payer,
  cover_image_url,
  version,
  GET_JSON_OBJECT(contract_rent_model,'$.rentalAdministrator') AS contract_rent_model,
  landlord_transfer_funds_day,
  tenant_charge_day,
  condominium_amount,
  brokerage_fee,
  iptu_installments,
  iptu_amount,
  rental_amount,
  administration_fee,
  monthly_discount,
  home_insurance_amount,
  can_chat,
  auto_igpm AS is_auto_igpm,
  deleted AS is_deleted,
  created_on AS ts_created,
  updated_on AS ts_updated,
  last_sync AS ts_last_synced,
  start_charge AS ts_charge_started,
  start_period AS ts_period_started,
  end_period AS ts_period_ended
FROM
  datalake_mission_control_test_raw.contract
