DROP TABLE IF EXISTS sale.dim_listing;
CREATE TABLE sale.dim_listing (
	sk_sale_listing BIGINT PRIMARY KEY,
	sk_house BIGINT,
	consultant_type VARCHAR(50),
	first_consultant_type VARCHAR(50),
	status VARCHAR,
	price BIGINT,
	predicted_price BIGINT,
	predicted_price_certainty VARCHAR,
	closing_status VARCHAR,
	stranded_status VARCHAR,
	registration_abandoned_reason VARCHAR,
	unpublished_reason VARCHAR,
	short_url VARCHAR,
	partner_3p_supply VARCHAR,
	is_3p_supply BOOLEAN,
	is_3p_supply_5a BOOLEAN,
	is_3p_supply_bh BOOLEAN,
	is_casa_mineira_migration BOOLEAN,
	is_primary_market BOOLEAN,
	is_for_rent BOOLEAN,
	has_active_rental_contract BOOLEAN,
	has_house_been_rented BOOLEAN,
	dt_consultant_started DATE,
	ts_consultant_deleted TIMESTAMP,
	ts_created TIMESTAMP,
	ts_first_publication TIMESTAMP,
	ts_last_publication TIMESTAMP,
	ts_first_depublication TIMESTAMP,
	ts_last_depublication TIMESTAMP,
	ts_first_booking TIMESTAMP,
	ts_first_visit_completed TIMESTAMP,
	ts_first_offer_submitted TIMESTAMP,
	dt_first_offer_accepted TIMESTAMP,
	dt_first_sale_agreement_signed TIMESTAMP,
	ts_updated TIMESTAMP,
	ts_load TIMESTAMP
);
ALTER TABLE sale.dim_listing OWNER TO airflow;
