drop table sale.fact_listing_sale_flows;

create table sale.fact_listing_sale_flows (
  ods_id bigint,
  sk_house_listing bigint,
  sk_house_first_listing_date bigint,
  sk_house_listing_date bigint,
  sk_house_listing_de_publication_date bigint,
  sk_region bigint,
  sk_condo bigint,
  sk_sale_flow bigint,
  sk_booking bigint,
  sk_booking_created_date bigint,
  sk_visit_date bigint,
  sk_owner bigint,
  sk_user_agent bigint,
  sk_client bigint,
  sk_visit bigint,
  sk_agent_review_rating_date bigint,
  flg_visit_completed boolean,
  flg_visit_performed boolean,
  flg_visit_created_from_app boolean,
  visit_created_type varchar,
  flg_visit_last_updated_from_app boolean,
  booking_utm_campaign varchar(2000),
  booking_utm_content varchar,
  booking_utm_term varchar,
  days_booking_created_to_visit numeric(14,2),
  days_user_created_to_visit numeric(14,2),
  days_house_listing_to_visit numeric(14,2),
  funnel_step varchar(255),
  funnel_step_drop_reason varchar(255),
  ts_load timestamp default getdate()
)
