SELECT
  sk_propose,
  match_status,
  client_name,
  cpf_cnpj,
  billing_method,
  months_billing_direto,
  months_quintocred_cobra,
  total_months_of_service,
  expected_revenue_renewal,
  months_before_renewal,
  monthly_guarantee_before_renewal,
  months_after_renewal,
  monthly_guarantee_after_renewal,
  expected_revenue_aud,
  monthly_guarantee_before_aud,
  monthly_guarantee_after_aud,
  value_payment,
  delinquency_monthly_value,
  dt_month_renewal,
  dt_month_update_aud,
  dt_contract_started,
  dt_ended,
  dt_month_closing,
  dt_snapshot,
  NOW() AS ts_snapshot,
  YEAR(CURRENT_DATE()) AS year,
  MONTH(CURRENT_DATE()) AS month,
  DAY(CURRENT_DATE()) AS day
FROM
  dw_recon_quintocred.fact_monthly_revenue
