SELECT
  assigned_by_person_id AS id_assigned_by_person,
  assignment_id AS id_assignment,
  goal_id AS id_goal,
  person_id AS id_person,
  business_group_id AS id_business_group,
  reference_goal_id AS id_reference_goal,
  mass_request_id AS id_mass_request,
  requester_person_id AS id_person_requester,
  measure_calc_rule_code AS measure_calculation_rule_code,
  goal_access_level_code,
  percent_complete_code,
  goal_source_code,
  goal_type_code,
  goal_version_type_code,
  status_code,
  priority_code,
  goal_name,
  description,
  last_updated_by AS updated_by,
  last_modified_by AS modified_by,
  request_context,
  goal_approval_state,
  attribute1 AS description_of_minimum_achievement,
  attribute2 AS description_of_target_achievement,
  attribute3 AS description_of_maximum_achievement,
  attribute5 AS expected_completion_period,
  attribute_category AS goal_category,
  CAST(attribute_number1 AS FLOAT) AS mininum_value,
  CAST(attribute_number2 AS FLOAT) AS target_value,
  CAST(attribute_number3 AS FLOAT) AS maximum_value,
  CAST(attribute_number4 AS FLOAT) AS result_value,
  CAST(object_version_number AS INT) AS object_version_number,
  allow_del_goal_flag = 'Y' AS is_goal_deletable,
  published_flag = 'Y' AS is_goal_published,
  access_to_hierarchy_flag = 'Y' AS is_goal_accessible_to_hierarchy,
  allow_key_attr_update_flag = 'Y' AS is_key_attribute_update_allowed,
  private_flag = 'Y' AS is_goal_private,
  TO_DATE(start_date) AS dt_started,
  TO_DATE(target_completion_date) AS dt_target_completion,
  TO_TIMESTAMP(version_date) AS ts_version,
  TO_TIMESTAMP(last_modified_date) AS ts_modified,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_goal_raw.hrg_goals