SELECT
  business_group_id AS id_business_group,
  goal_plan_ext_id AS id_goal_plan_ext,
  goal_plan_id AS id_goal_plan,
  mass_request_id AS id_mass_request,
  review_period_id AS id_review_period,
  goal_access_level_code,
  goal_plan_type_code,
  request_ui_context_code,
  evaluation_type,
  created_by,
  last_updated_by AS updated_by,
  allow_pvt_goal_max_goal_flag = 'Y' AS is_private_goal_allowed_when_max_goal_is_reached,
  auto_associate_goal_flag = 'Y' AS is_goal_auto_associated,
  created_by_system = 'Y' AS is_created_by_system,
  enable_weighting_flag = 'Y' AS is_weighting_enabled,
  enforce_goal_weight_flag = 'Y' AS is_goal_weight_enforced,
  goal_plan_active_flag = 'A' AS is_active_goal_plan,
  include_in_perfdoc_flag = 'Y' AS is_included_in_performance_document,
  primary_goal_plan_flag = 'Y' AS is_primary_goal_plan,
  enforce_max_goals_in_gp_flag = 'Y' AS is_max_goals_enforced,
  CAST(max_goals_num_in_goal_plan AS INT) AS max_goals_in_goal_plan,
  CAST(object_version_number AS INT) AS object_version_number,
  TO_DATE(start_date) AS dt_started,
  TO_DATE(end_date) AS dt_ended,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_goal_raw.hrg_goal_plans_b
