SELECT
	id AS id_appointment,
	external_appointment_id AS id_external_appointment,
	external_appointment_id_mod AS mod_id_external_appointment,
	schedules_appointment_id AS id_schedules,
	schedules_appointment_id_mod AS mod_id_schedules,
	inspection_id AS id_inspection,
	inspection_id_mod AS mod_id_inspection,
	inspector_id AS id_inspector,
	inspector_id_mod AS mod_id_inspector,
	rev,
	revtype AS rev_type,
	revend AS rev_end,
	status,
	status_mod AS mod_status,
	inspection_mod AS mod_inspection,
	observation,
	observation_mod AS mod_observation,
	cancellation_reason,
	cancellation_reason_mod AS mod_cancellation_reason,
	fixed_agent AS is_fixed_agent,
	fixed_agent_mod AS mod_is_fixed_agent,
	scheduled_date AS dt_scheduled,
	scheduled_date_mod AS mod_dt_scheduled,
	updated_at AS ts_updated,
	updated_at_mod AS mod_ts_updated,
	created_at AS ts_created,
	created_at_mod AS mod_ts_created,
	year,
	month,
	day
FROM
	datalake_inspections_raw.appointment_aud
WHERE
	MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
