SELECT
    id AS id_assessment,
    inspection_id AS id_inspection,
    previous_assessment_id AS id_previous_assessment,
    key_location,
    key_location_details,
    house_supplies,
    source,
    scheduling_key_recovery,
    key_information,
    rev,
    revtype,
    revend,
    previous_assessment_id_mod AS mod_id_previous_assessment,
    inspection_mod AS mod_inspection,
    key_location_mod AS mod_key_location,
    key_location_details_mod AS mod_key_location_details,
    rooms_mod AS mod_rooms,
    source_mod AS mod_source,
    house_supplies_mod AS mod_house_supplies,
    scheduling_key_recovery_mod AS mod_scheduling_key_recovery,
    reviewers_mod AS mod_reviewers,
    key_information_mod AS mod_key_information,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    started_at_mod AS mod_ts_started,
    finished_at_mod AS mod_ts_finished,
    tenant_limit_revision_date_mod AS mod_dt_tenant_limit_revision,
    limit_budget_approval_date_mod AS mod_dt_limit_budget_approval,
    owner_limit_revision_date_mod AS mod_dt_owner_limit_revision,
    created_at AS ts_created,
    updated_at AS ts_updated,
    started_at AS ts_started,
    finished_at AS ts_finished,
    tenant_limit_revision_date AS dt_tenant_limit_revision,
    limit_budget_approval_date AS dt_limit_budget_approval,
    owner_limit_revision_date AS dt_owner_limit_revision,
    year,
    month,
    day
FROM
    datalake_inspections_raw.assessment_aud
WHERE
	MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
