SELECT
    id AS id_budget,
    uuid,
    owner_approval_comment,
    tenant_approval_comment,
    owner_approval_reason,
    tenant_approval_reason,
    owner_approved_by,
    tenant_approved_by,
    owner_approved,
    tenant_approved,
    total_cost,
    total_cost_mod AS mod_total_cost,
    owner_amount_payment,
    owner_amount_payment_mod AS mod_owner_amount_payment,
    tenant_amount_payment,
    tenant_amount_payment_mod AS mod_tenant_amount_payment,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    owner_approved_date AS dt_owner_approved,
    tenant_approved_date AS dt_tenant_approved,
    owner_deadline_date AS dt_owner_dead_line,
    tenant_deadline_date AS dt_tenant_dead_line,
    created_at AS ts_created,
    created_at_mod AS mod_ts_created,
    updated_at AS ts_updated,
    updated_at_mod AS mod_ts_updated,
    year,
    month,
    day
FROM
    datalake_inspections_raw.budget_aud
WHERE
	MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
