SELECT
    id AS id_item,
    item_group_id AS id_item_group,
    previous_item_id AS id_previous_item,
    type_id AS id_type,
    main_id AS id_main,
    uuid,
    comment,
    count,
    status,
    present AS is_present,
    active AS is_active,
    rev,
    revtype,
    revend,
    main_id_mod AS mod_id_main,
    uuid_mod AS mod_uuid,
    item_group_mod AS mod_item_group,
    type_mod AS mod_type,
    previous_item_mod AS mod_previous_item,
    comment_mod AS mod_comment,
    count_mod AS mod_count,
    status_mod AS mod_status,
    present_mod AS mod_is_present,
    active_mod AS mod_id_active,
    item_issues_mod AS mod_item_issue,
    reviews_mod AS mod_reviews,
    item_medias_mod AS mod_item_medias,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_inspections_raw.item_aud
WHERE
	MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
