SELECT
    id AS id_item_group,
    room_id AS id_room,
    type_id AS id_type,
    main_id AS id_main,
    reviewer_id AS id_reviewer,
    uuid,
    name,
    comment,
    status,
    rev,
    revtype,
    revend,
    is_inferior_quality,
    active_status AS is_active_status,
    active_is_inferior_quality AS is_active_inferior_quality,
    main_id_mod AS mod_id_main,
    reviewer_id_mod AS mod_id_reviewer,
    uuid_mod AS mod_uuid,
    name_mod AS mod_name,
    comment_mod AS mod_comment,
    status_mod AS mod_status,
    room_mod AS mod_room,
    type_mod AS mod_type,
    items_mod AS mod_items,
    repair_requests_mod AS mod_repair_request,
    reviewer_mod AS mod_reviewer,
    is_inferior_quality_mod AS mod_is_inferior_quality,
    active_status_mod AS mod_is_active_status,
    active_is_inferior_quality_mod AS mod_is_active_inferior_quality,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_inspections_raw.item_group_aud
WHERE
	MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
