SELECT
    id_vx_security,
    id_vortex_security_wave_effect,
    id_occurrence,
    id_invoice_bank,
    REGEXP_REPLACE(security_number, "\/*", "") AS security_number,
    assignor_cnpj_cpf,
    assignor_name,
    withdraw_cnpj_cpf,
    withdraw_name,
    occurrence,
    situation,
    asset_type,
    key_field,
    IF(wave_effect_generator = 'NAO', FALSE, TRUE) AS is_wave_effect_generator,
    nominal_value,
    payment_value,
    residual_value,
    reductions,
    fee,
    partial_payment,
    description_status,
    value_present_opening,
    payment_impact,
    CAST(REGEXP_EXTRACT(security_number, "\/(.*)") AS INT) AS installment_number,
    DATE_FORMAT(dt_payment, 'yyyyMM') AS accrual_year_month,
    dt_due,
    dt_payment,
    dt_liquidation
FROM
    datalake_gsheets_clean.fdic_liquidation_2021
UNION ALL
SELECT
    id_vx_security,
    id_vortex_security_wave_effect,
    id_occurrence,
    id_invoice_bank,
    REGEXP_REPLACE(security_number, "\/*", "") AS security_number,
    assignor_cnpj_cpf,
    assignor_name,
    withdraw_cnpj_cpf,
    withdraw_name,
    occurrence,
    situation,
    asset_type,
    key_field,
    IF(wave_effect_generator = 'NAO', FALSE, TRUE) AS is_wave_effect_generator,
    nominal_value,
    payment_value,
    residual_value,
    reductions,
    fee,
    partial_payment,
    description_status,
    value_present_opening,
    payment_impact,
    CAST(REGEXP_EXTRACT(security_number, "\/(.*)") AS INT) AS installment_number,
    DATE_FORMAT(dt_payment, 'yyyyMM') AS accrual_year_month,
    dt_due,
    dt_payment,
    dt_liquidation
FROM
    datalake_gsheets_clean.fdic_liquidation_2022
UNION ALL
SELECT
    id_vx_security,
    id_vortex_security_wave_effect,
    id_occurrence,
    id_invoice_bank,
    REGEXP_REPLACE(security_number, "\/*", "") AS security_number,
    assignor_cnpj_cpf,
    assignor_name,
    withdraw_cnpj_cpf,
    withdraw_name,
    occurrence,
    situation,
    asset_type,
    key_field,
    IF(wave_effect_generator = 'NAO', FALSE, TRUE) AS is_wave_effect_generator,
    nominal_value,
    payment_value,
    residual_value,
    reductions,
    fee,
    partial_payment,
    description_status,
    value_present_opening,
    payment_impact,
    CAST(REGEXP_EXTRACT(security_number, "\/(.*)") AS INT) AS installment_number,
    DATE_FORMAT(dt_payment, 'yyyyMM') AS accrual_year_month,
    dt_due,
    dt_payment,
    dt_liquidation
FROM
    datalake_gsheets_clean.fdic_liquidation_2023