SELECT
    city_group,
    business_type,
    rent_flow_origin,
    rental_administrator,
    visits_booked,
    visits_completed,
    offers_submitted,
    offers_accepted,
    evaluation_started,
    evaluation_positive,
    documentation_sent,
    credit_approved,
    contracts_signed,
    dt_target
FROM
    datalake_gsheets_clean.demand_targets_retro
UNION ALL
SELECT
    city_group,
    business_type,
    rent_flow_origin,
    rental_administrator,
    visits_booked,
    visits_completed,
    offers_submitted,
    offers_accepted,
    evaluation_started,
    evaluation_positive,
    documentation_sent,
    credit_approved,
    contracts_signed,
    dt_target
FROM
    datalake_gsheets_clean.demand_targets_2024
UNION ALL
SELECT
    city_group,
    business_type,
    rent_flow_origin,
    rental_administrator,
    visits_booked,
    visits_completed,
    offers_submitted,
    offers_accepted,
    evaluation_started,
    evaluation_positive,
    documentation_sent,
    credit_approved,
    contracts_signed,
    date AS dt_target
FROM
    datalake_gsheets_clean.demand_targets_2025