SELECT
    codigo_proposta AS id_proposal,
    codigo_operacao AS id_operation,
    prop_business_unit_uid AS id_business_unit,
    resultado AS analysis_result,
    CAST(calc_argonautv3_score AS BIGINT) AS v3_model_score,
    CAST(calc_argonautv4_score AS DECIMAL(32,2)) AS v4_model_score,
    CAST(calc_quantidade_proponentes AS BIGINT) AS proponents_count,
    CAST(calc_idade_rf1 AS BIGINT) AS first_proponent_age,
    CAST(calc_idade_rf2 AS BIGINT) AS second_proponent_age,
    CAST(calc_idade_rf3 AS BIGINT) AS third_proponent_age,
    CAST(calc_idade_rf4 AS BIGINT) AS forth_proponent_age,
    NULLIF(calc_tipo_renda_eleita, 'NaN') AS elected_income_type,
    NULLIF(calc_tipo_ocorrencia, 'NaN') AS refin_pefin_occurrence_type,
    SPLIT(NULLIF(calc_tipo_ocorrencia_total, 'NaN'), '#@#') AS refin_pefin_occurrence_type_list,
    TRANSFORM(SPLIT(NULLIF(calc_tipo_bloqueio_total, 'NaN'), '#@#'), x -> NULLIF(TRIM(x), "")) AS reason_document_on_blocklist_list,
    NULLIF(calc_rfpf_situacao, 'NaN') AS document_status_federal,
    SPLIT(NULLIF(calc_rfpf_situacao_total, 'NaN'), '#@#') AS document_status_federal_list,
    NULLIF(calc_bigdataboost_taxidstatus, 'NaN') AS bigdataboost_document_status,
    SPLIT(NULLIF(calc_bigdataboost_taxidstatus_acumulado, 'NaN'), '#@#') AS  bigdataboost_document_status_list,
    NULLIF(calc_bigdataboost_status, 'NaN') AS status_bigdataboost,
    NULLIF(calc_matchrate, 'NaN') AS matchrate,
    calc_modelo_def AS model_score,
    calc_decisao_json AS model_metadata,
    calc_bigdata_idade_amax AS bigdata_age_amax,
    calc_bigdata_idade_amin AS bigdata_age_amin,
    calc_bigdata_idade_bureau AS bigdata_age_bureau,
    calc_bigdata_entidades_empregadas_amin AS bigdata_entities_employed_amin,
    calc_bigdata_entidades_empregadas_sum AS bigdata_entities_employed_sum,
    calc_bigdata_entidades_empregadas_bureau AS bigdata_entities_employed_bureau,
    calc_bigdata_tel_profissionais_amax AS bigdata_professional_phones_amax,
    calc_bigdata_tel_profissionais_amin AS bigdata_professional_phones_amin,
    calc_bigdata_tel_profissionais_bureau AS bigdata_professional_phones_bureau,
    calc_bigdata_total_enderecos_sum AS bigdata_total_addresses_sum,
    calc_bigdata_total_enderecos_bureau AS bigdata_total_enderecos_bureau,
    calc_bigdata_origens_cobrancas_amax AS bigdata_origin_charges_amax,
    calc_bigdata_origens_cobrancas_bureau AS bigdata_origin_charges_bureau,
    calc_bigdata_total_passagens_emails_mean AS bigdata_total_tickets_emails_mean,
    calc_bigdata_total_passagens_emails_bureau AS bigdata_total_passagens_emails_bureau,
    calc_boavista_score_amax AS boavista_score_amax,
    calc_boavista_score_amin AS boavista_score_amin,
    calc_boavista_score_mean AS boavista_score_mean,
    calc_boavista_score_bureau AS boavista_score_bureau,
    TRANSFORM(SPLIT(NULLIF(calc_api_boavista_score_p5, 'NaN'), '#@#'), x -> CAST(x AS INT)) AS boavista_score_proponents,
    calc_serasa_score_csba_amax AS serasa_score_csba_amax,
    calc_serasa_score_csba_amin AS serasa_score_csba_amin,
    calc_serasa_score_csba_mean AS serasa_score_csba_mean,
    calc_serasa_score_csba_sum AS serasa_score_csba_sum,
    TRANSFORM(SPLIT(NULLIF(calc_serasa_score_csba_bureau, 'NaN'), '#@#'), x -> CAST(x AS INT)) AS serasa_score_csba_bureau,
    calc_serasa_score_hspn_amax AS serasa_score_hspn_amax,
    calc_serasa_score_hspn_amin AS serasa_score_hspn_amin,
    calc_serasa_score_hspn_mean AS serasa_score_hspn_mean,
    calc_serasa_score_hspn_sum AS serasa_score_hspn_sum,
    TRANSFORM(SPLIT(NULLIF(calc_serasa_score_hspn_bureau, 'NaN'), '#@#'), x -> CAST(x AS INT)) AS serasa_score_hspn_bureau,
    calc_transunion_dist_fronteira_m_amin AS transunion_dist_fronteira_m_amin,
    calc_transunion_dist_fronteira_m_bureau AS transunion_dist_fronteira_m_bureau,
    calc_transunion_indic_seg_6_amax AS transunion_indic_seg_6_amax,
    calc_transunion_indic_seg_6_amin AS transunion_indic_seg_6_amin,
    calc_transunion_indic_seg_6_bureau AS transunion_indic_seg_6_bureau,
    calc_transunion_indic_seg_24_sum AS transunion_indic_seg_24_sum,
    calc_transunion_indic_seg_24_bureau AS transunion_indic_seg_24_bureau,
    calc_transunion_percent_decl_10_01_amin AS transunion_percent_decl_10_01_amin,
    calc_transunion_percent_decl_10_01_bureau AS transunion_percent_decl_10_01_bureau,
    calc_transunion_decl_rest_3_amax AS transunion_decl_rest_3_amax,
    calc_transunion_decl_rest_3_amin AS transunion_decl_rest_3_amin,
    calc_transunion_decl_rest_3_bureau AS transunion_decl_rest_3_bureau,
    calc_transunion_percent_escol_04_amax AS transunion_percent_escol_04_amax,
    calc_transunion_percent_escol_04_mean AS transunion_percent_escol_04_mean,
    calc_transunion_percent_escol_04_bureau AS transunion_percent_escol_04_bureau,
    calc_transunion_percent_escol_10_amin AS transunion_percent_escol_10_amin,
    calc_transunion_percent_escol_10_bureau AS calc_transunion_percent_escol_10,
    calc_transunion_porte_empregador_amax AS transunion_employer_size_amax,
    calc_transunion_porte_empregador_mean AS transunion_employer_size_mean,
    calc_transunion_porte_empregador_bureau AS transunion_employer_size_bureau,
    calc_transunion_qtd_endereco_amin AS transunion_number_addresses_amin,
    calc_transunion_qtd_endereco_sum AS transunion_number_addresses_sum,
    calc_transunion_qtd_endereco_bureau AS transunion_number_addresses_bureau,
    TRANSFORM(SPLIT(NULLIF(calc_api_v3_serasa_score_hspn, 'NaN'), '#@#'), x -> CAST(x AS INT)) AS serasa_score_hspn_api_v3_list,
    TRANSFORM(SPLIT(NULLIF(calc_api_v4_serasa_score_hspn, 'NaN'), '#@#'), x -> CAST(x AS INT)) AS serasa_score_hspn_api_v4_list,
    TRANSFORM(SPLIT(NULLIF(calc_api_v4_bvs_score_p5, 'NaN'), '#@#'), x -> CAST(x AS INT)) AS bvs_score_api_v4,
    calc_neoway_income_bureau AS neoway_income_bureau,
    calc_neoway_income_mean AS neoway_income_mean,
    CAST(prop_valor_pacote AS DECIMAL(32,2)) AS proposal_package_amount,
    CAST(calc_renda_decl_total AS DECIMAL(32,2)) AS total_declared_income,
    CAST(calc_renda_eleita AS DECIMAL(32,2)) AS elected_income,
    CAST(calc_modelo_renda_total AS DECIMAL(32,2)) AS model_total_income,
    CAST(calc_valor_ocorrencia AS DECIMAL(32,2)) AS refin_pefin_occurrence_amount,
    CAST(calc_valor_protesto AS DECIMAL(32,2)) AS protest_amount,
    CAST(prop_valor_aluguel AS DECIMAL(32,2)) AS rent_amount,
    CAST(calc_comparacao_fonetica_nome AS DECIMAL(32,6)) AS name_check_rating,
    TRANSFORM(SPLIT(NULLIF(calc_valor_ocorrencia_total, 'NaN'), '#@#'), x -> CAST(x AS DECIMAL(32,2))) AS refin_pefin_occurrence_amount_list,
    TRANSFORM(SPLIT(NULLIF(calc_valor_protesto_total, 'NaN'), '#@#'), x -> CAST(x AS DECIMAL(32,2))) AS protest_amount_list,
    TRANSFORM(SPLIT(NULLIF(calc_comparacao_fonetica_nome_total, 'NaN'), '#@#'), x -> CAST(x AS DECIMAL(32,6))) AS name_check_rating_list,
    TRANSFORM(SPLIT(NULLIF(calc_renda_serasa_acumulado, 'NaN'), '#@#'), x -> CAST(x AS DECIMAL(32,2))) AS serasa_income,
    TRANSFORM(SPLIT(NULLIF(calc_renda_transunion_acumulado, 'NaN'), '#@#'), x -> CAST(x AS DECIMAL(32,2))) AS transunion_income,
    SPLIT(prop_cpf_titular, '#@#') AS proposal_cpfs,
    prop_estado AS proposal_state,
    prop_nome_imob AS proposal_name_real_state_company,
    prop_taxa_imobiliaria AS proposal_real_state_tax,
    prop_nasc_titular AS proposal_birth_date_proponents,
    prop_valor_item_pacote AS proposal_value_package_item,
    prop_tipo_imovel AS proposal_property_type,
    calc_tipo_matriz AS matrix_type,
    prop_cidade AS proposal_city,
    CAST(prop_renda_comprovada AS DECIMAL(32,2)) AS proposal_verified_income,
    prop_corretor AS proposal_real_state_agent,
    prop_natureza_renda AS proposal_nature_income,
    prop_renda_declarada AS proposal_declared_income,
    calc_percentual_aprovado AS proposal_approved_percentage,
    calc_reprovacao_automatica_imobiliaria_rs AS automatic_reproval_real_state_rs,
    calc_rating AS proposal_rating,
    CAST(CAST(prop_num_proposta AS DOUBLE) AS INT) AS proposal_number,
    calc_dti AS dti,
    calc_dti_maximo AS dti_max,
    calc_dti_real AS dti_real,
    calc_dti_presumido AS dti_presumed,
    CAST(calc_dti_apurado AS DECIMAL(32,2)) AS dti_calculated,
    CAST(calc_renda_apurada AS DECIMAL(32,2)) AS calculated_income,
    CAST(calc_bigidbgc_score AS DECIMAL(32,2)) AS score_bigid,
    CAST(calc_bigidbgc_score1 AS DECIMAL(32,2)) AS score_bigid_first_proponent,
    CAST(calc_bigidbgc_score2 AS DECIMAL(32,2)) AS score_bigid_second_proponent,
    CAST(calc_bigidbgc_score3 AS DECIMAL(32,2)) AS score_bigid_third_proponent,
    CAST(calc_bigidbgc_score4 AS DECIMAL(32,2)) AS score_bigid_forth_proponent,
    calc_faixa_pacote AS package_range,
    calc_valor_pacote AS package_value,
    calc_nome_principal AS main_proponent_name,
    calc_idade AS main_proponent_age,
    prop_email_titular AS main_proponent_email,
    calc_faixa_renda_presumida AS presumed_income_range,
    prop_ramo_atividade AS branch_activity,
    log_usuario AS log_user,
    log_resultado AS log_result,
    calc_status_decisao AS status_decision,
    calc_rating_random AS rating_random,
    calc_decisao_status AS decision_status,
    flx_decisao AS decision_flex,
    rgr_calcular_score AS calculate_score_result,
    vi_exec_bigid AS status_exec_bigid,
    calc_filtros AS status_filters,
    rgr_estrangeiro AS status_foreign_filter,
    calc_bigid_court_type AS bigid_court_type,
    calc_bigid_court_type_1 AS bigid_court_type_first_proponent,
    calc_bigid_court_type_2 AS bigid_court_type_second_proponent,
    calc_bigid_court_type_3 AS bigid_court_type_third_proponent,
    calc_bigid_court_type_4 AS bigid_court_type_forth_proponent,
    calc_bigid_main_subject AS bigid_main_subject,
    calc_bigid_main_subject_1 AS bigid_main_subject_first_proponent,
    calc_bigid_main_subject_2 AS bigid_main_subject_second_proponent,
    calc_bigid_main_subject_3 AS bigid_main_subject_third_proponent,
    calc_bigid_main_subject_4 AS bigid_main_subject_forth_proponent,
    calc_bigid_process_details_civel AS bigid_process_details_civel,
    calc_bigid_process_details_civel_1 AS bigid_process_details_civel_first_proponent,
    calc_bigid_process_details_civel_2 AS bigid_process_details_civel_second_proponent,
    calc_bigid_process_details_civel_3 AS bigid_process_details_civel_third_proponent,
    calc_bigid_process_details_civel_4 AS bigid_process_details_civel_forth_proponent,
    calc_bigid_process_details_criminal AS bigid_process_details_criminal,
    calc_bigid_process_details_criminal_1 AS bigid_process_details_criminal_first_proponent,
    calc_bigid_process_details_criminal_2 AS bigid_process_details_criminal_second_proponent,
    calc_bigid_process_details_criminal_3 AS bigid_process_details_criminal_third_proponent,
    calc_bigid_process_details_criminal_4 AS bigid_process_details_criminal_forth_proponent,
    calc_bigid_process_details_tributaria AS bigid_process_details_tax,
    calc_bigid_process_details_tributaria_1 AS bigid_process_details_tax_first_proponent,
    calc_bigid_process_details_tributaria_2 AS bigid_process_details_tax_second_proponent,
    calc_bigid_process_details_tributaria_3 AS bigid_process_details_tax_third_proponent,
    calc_bigid_process_details_tributaria_4 AS bigid_process_details_tax_forth_proponent,
    calc_bigid_type AS bigid_type,
    calc_bigid_type_1 AS bigid_type_first_proponent,
    calc_bigid_type_2 AS bigid_type_second_proponent,
    calc_bigid_type_3 AS bigid_type_third_proponent,
    calc_bigid_type_4 AS bigid_type_forth_proponent,
    calc_predictus_assuntos_cnj_titulo_1 AS subjects_predictus_first_proponent,
    calc_predictus_assuntos_cnj_titulo_2 AS subjects_predictus_second_proponent,
    calc_predictus_assuntos_cnj_titulo_3 AS subjects_predictus_third_proponent,
    calc_predictus_assuntos_cnj_titulo_4 AS subjects_predictus_forth_proponent,
    calc_rfpf_status_message_1 AS status_message_federal_first_proponent,
    calc_rfpf_status_message_2 AS status_message_federal_second_proponent,
    calc_rfpf_status_message_3 AS status_message_federal_third_proponent,
    calc_rfpf_status_message_4 AS status_message_federal_fourth_proponent,
    calc_predictus_status_message_1 AS predictus_status_message_first_proponent,
    calc_predictus_status_message_2 AS predictus_status_message_second_proponent,
    calc_predictus_status_message_3 AS predictus_status_message_third_proponent,
    calc_predictus_status_message_4 AS predictus_status_message_fourth_proponent,
    calc_smartgtwrf_base_consultada_1 AS smartgtwrf_base_first_proponent,
    calc_smartgtwrf_base_consultada_2 AS smartgtwrf_base_second_proponent,
    calc_smartgtwrf_base_consultada_3 AS smartgtwrf_base_third_proponent,
    calc_smartgtwrf_base_consultada_4 AS smartgtwrf_base_fourth_proponent,
    `smartgtwrf_5andar.result.message` AS smartgtwrf_message,
    prop_tipo_documento AS proposal_document_type,
    rgr_backgroundcheck_cad_localizado AS located_registration_bigid,
    rgr_backgroundcheck_sist_responde	AS sistem_reponse_bigig,
    rgr_predictus_capa_processual_dados_localizados	AS located_processes_predictus,
    rgr_predictus_capa_processual_sistema_responde	AS sistem_response_predictus,
    rgr_rfpf_cadastro_localizado	AS located_registration_federal,
    rgr_rfpf_sistema_responde	AS sistem_reponse_federal,
    flag_cnpj AS flag_cnpj,
    flag_fraude AS flag_fraud,
    CAST(IF(sucesso="S", TRUE, FALSE) AS BOOLEAN) AS is_success,
    CAST(IF(prop_resubmissao="S", TRUE, FALSE) AS BOOLEAN) AS is_resubmission,
    CAST(IF(rgr_valor_pacote="APROVADO", TRUE, FALSE) AS BOOLEAN) AS is_package_value_approved,
    CAST(IF(calc_argonautv3_flag_desenrola="true", TRUE, FALSE) AS BOOLEAN) AS is_desenrola_document,
    CAST(IF(calc_block="S", TRUE, FALSE) AS BOOLEAN) AS is_blocklist_document,
    TRANSFORM(SPLIT(NULLIF(calc_block_total, 'NaN'), '#@#'), x -> CAST(IF(x="S", TRUE, FALSE) AS BOOLEAN)) AS is_blocklist_document_list,
    CAST(IF(calc_estrangeiro="SIM", TRUE, FALSE) AS BOOLEAN) AS is_foreign_document,
    TRANSFORM(SPLIT(NULLIF(calc_estrangeiro_total, 'NaN'), '#@#'), x -> CAST(IF(x="SIM", TRUE, FALSE) AS BOOLEAN)) AS is_foreign_document_list,
    CAST(calc_processos AS BOOLEAN) AS has_lawsuits,
    CAST(IF(calc_pep1="SIM", TRUE, FALSE) AS BOOLEAN) AS is_first_proponent_pep,
    CAST(IF(calc_pep2="SIM", TRUE, FALSE) AS BOOLEAN) AS is_second_proponent_pep,
    CAST(IF(calc_pep3="SIM", TRUE, FALSE) AS BOOLEAN) AS is_third_proponent_pep,
    CAST(IF(calc_pep4="SIM", TRUE, FALSE) AS BOOLEAN) AS is_forth_proponent_pep,
    IF(`bigdataboost_5andar.result.message`= "CPF_MENOR_DE_IDADE_INFORME_DATA_NASCIMENTO", TRUE, FALSE) AS is_minor_age_document,
    IF(calc_bigdata_message_total LIKE "%CPF_MENOR_DE_IDADE_INFORME_DATA_NASCIMENTO%", TRUE, FALSE) AS is_minor_age_document_list,
    CAST(IF(`rfpfimg_5andar.result.message`="NAO ENCONTRADO", FALSE, TRUE) AS BOOLEAN) AS is_document_federal,
    TO_TIMESTAMP(log_dh_processamento,'yyyy-MM-dd HH:mm:ss') AS ts_dh_processed,
    TO_TIMESTAMP(REPLACE(instante, '.000', ''), 'yyyy-MM-dd HH:mm:ss') AS ts_operation,
    TO_TIMESTAMP(REPLACE(calc_mesa_dh_insercao, '.000', ''), 'yyyy-MM-dd HH:mm:ss') AS ts_inserted,
    year,
    month,
    day
FROM
    datalake_velo_neurotech_raw.logs_credit_granting
