SELECT
    id,
    client_id AS id_client,
    database_id AS id_database,
    sql_editor_id AS id_sql_editor,
    user_id AS id_user,
    tmp_table_name,
    tab_name,
    status,
    schema,
    sql,
    select_sql,
    executed_sql,
    limit,
    select_as_cta,
    select_as_cta_used,
    progress,
    rows,
    error_message,
    results_key,
    tracking_url,
    extra_json,
    tmp_schema_name,
    ctas_method,
    limiting_factor,
    start_running_time AS ts_start_running,
    end_result_backend_time AS ts_end_result_backend,
    start_time AS ts_start,
    changed_on AS ts_changed,
    end_time AS ts_end,
    year,
    month,
    day
FROM datalanke_superset_raw.query
WHERE MAKE_DATE(year, month, day) BETWEEN "{load_start_date}" AND "{load_end_date}"