SELECT
    CAST(idtitulovx AS BIGINT) AS id_vx_security,
    CAST(idtitulovortxorigemefeitovagao AS BIGINT) AS id_vortex_security_wave_effect,
    CAST(codigoocorrencia AS INT) AS id_occurrence,
    CAST(numeroboletobanco AS BIGINT) AS id_invoice_bank,
    numerotitulo AS security_number,
    cedentecnpjcpf AS assignor_cnpj_cpf,
    cedentenome AS assignor_name,
    sacadocnpjcpf AS withdraw_cnpj_cpf,
    sacadonome AS withdraw_name,
    ocorrencia AS occurrence,
    situacao AS situation,
    tipoativo AS asset_type,
    campochave AS key_field,
    geradorefeitovagao AS wave_effect_generator,
    CAST(valornominal AS FLOAT) AS nominal_value,
    CAST(valorpagamento AS FLOAT) AS payment_value,
    CAST(valorresidual AS FLOAT) AS residual_value,
    CAST(abatimentos AS FLOAT) AS reductions,
    CAST(juros AS FLOAT) AS fee,
    CAST(pagamentoparcial AS FLOAT) AS partial_payment,
    CAST(statusdescricao AS FLOAT) AS description_status,
    CAST(valorpresenteabertura AS FLOAT) AS value_present_opening,
    CAST(impactopagamento AS FLOAT) AS payment_impact,
    TO_DATE(datavencimento, "d/M/y") AS dt_due,
    TO_DATE(datapagamento, "d/M/y") AS dt_payment,
    TO_DATE(dataliquidacao, "d/M/y") AS dt_liquidation
FROM
    datalake_gsheets_raw.fdic_liquidation_2023