SELECT
    macro_taxonomy,
    micro_taxonomy,
    journey,
    sub_journey,
    line_owner,
    micro_taxonomy_description,
    ops_focal_point,
    is_active
FROM
    datalake_gsheets_raw.ticket_rate_classification
