SELECT
  user_pseudo_id AS id_user_pseudo,
  unique_session_id AS id_session,
  event_campaign_id AS id_event_campaign,
  lead_id AS id_lead,
  property_id AS id_property,
  stream_id AS id_stream,
  user_id_custom AS id_user_custom,
  session_campaign_id AS id_session_campaign,
  session_gads_ad_group_id AS id_session_gads_ad_group,
  CAST(ga_session_number AS INTEGER) AS ga_number,
  platform,
  session_source AS ses_src,
  session_medium AS ses_medium,
  session_campaign_name AS ses_cmp_name,
  session_ad_content AS ses_ad_content,
  session_ad_term AS ses_ad_term,
  session_source_platform AS ses_src_platform,
  session_creative_format AS ses_creative_format,
  session_marketing_tactic AS ses_mkt_tactic,
  session_gads_ad_group_name AS ses_gads_ad_grp_name,
  session_ga4_default_channel_group AS ses_ga4_def_channel_grp,
  event_name AS ev_name,
  event_campaign_name AS ev_cmp_name,
  event_source AS ev_src,
  event_medium AS ev_medium,
  event_term AS ev_term,
  event_content AS ev_content,
  event_source_platform AS ev_src_platform,
  event_creative_format AS ev_creative_format,
  event_marketing_tactic AS ev_mkt_tactics,
  event_gclid AS ev_gclid,
  site,
  city,
  country,
  region,
  hostname,
  device,
  lead_type,
  page_location,
  site_section,
  operation_type,
  CAST(total_events AS INTEGER) AS ev_total,
  event_date AS ts_event,
  event_timestamp_utc AS ts_event_timestamp_utc,
  last_update AS ts_last_update,
  year,
  month,
  day
FROM
  datalake_google_analytics_classified_raw.google_analytics_classified
WHERE 
  MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
