SELECT
    id_amplitude,
    ids_amplitude_attributed,
    id_app,
    id_device,
    id_event,
    id_session,
    id_inserted,
    id_user,
    id_schema,
    REGEXP_EXTRACT(GET_JSON_OBJECT(event_properties, '$.uri'), '.imovel\/(\\d+?)\/',1) AS id_house,
    idfa,
    adid,
    uuid,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_type,
    event_properties,
    is_attribution_event,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    is_paying,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    user_properties,
    ts_processed,
    year,
    month,
    day,
    GET_JSON_OBJECT(user_properties, '$.gclid') AS up_gclid,
    GET_JSON_OBJECT(user_properties, '$.utm_source') AS up_utm_source,
    GET_JSON_OBJECT(user_properties, '$.utm_medium') AS up_utm_medium,
    GET_JSON_OBJECT(user_properties, '$.utm_campaign') AS up_utm_campaign,
    GET_JSON_OBJECT(user_properties, '$.utm_content') AS up_utm_content,
    GET_JSON_OBJECT(user_properties, '$.utm_term') AS up_utm_term,
    GET_JSON_OBJECT(user_properties, '$.platform') AS up_platform,
    GET_JSON_OBJECT(user_properties, "$['[adjust] network']") AS up_adjust_network,
    GET_JSON_OBJECT(user_properties, "$['[adjust] campaign']") AS up_adjust_campaign,
    GET_JSON_OBJECT(user_properties, '$.entrance_uri') AS up_entrance_uri,
    GET_JSON_OBJECT(event_properties, '$.uri') AS ep_uri,
    COALESCE(
        GET_JSON_OBJECT(event_properties, '$.user_email_md5'),
        GET_JSON_OBJECT(event_properties, '$.tts_email_md5')
    ) AS ep_user_email_md5
FROM
    datalake_amplitude_new_clean.events
WHERE
    id_app = '170698' AND event_type = 'tts_success_page_viewed'
