SELECT
  id_amplitude,
  ids_amplitude_attributed,
  id_app,
  id_device,
  id_event,
  id_session,
  id_inserted,
  id_user,
  id_schema,
  idfa,
  adid,
  uuid,
  STRING(GET_JSON_OBJECT(event_properties, '$.offer_id')) AS id_offer,
  amplitude_event_type,
  city,
  country,
  region,
  data,
  device_brand,
  device_carrier,
  device_family,
  device_manufacturer,
  device_model,
  device_type,
  dma,
  event_type,
  event_properties,
  is_attribution_event,
  ip_address,
  location_lat,
  location_lng,
  os_name,
  os_version,
  platform,
  library,
  is_paying,
  start_version,
  language,
  version_name,
  sample_rate,
  user_properties,
  STRING(GET_JSON_OBJECT(user_properties, '$.platform')) AS up_app_type,
  STRING(GET_JSON_OBJECT(user_properties, '$.utm_source')) AS up_utm_source,
  STRING(GET_JSON_OBJECT(user_properties, '$.utm_medium')) AS up_utm_medium,
  STRING(GET_JSON_OBJECT(user_properties, '$.utm_campaign')) AS up_utm_campaign,
  STRING(GET_JSON_OBJECT(user_properties, '$.utm_content')) AS up_utm_content,
  STRING(GET_JSON_OBJECT(user_properties, '$.utm_term')) AS up_utm_term,
  DATE(ts_event) AS dt_event,
  ts_event,
  ts_server_uploaded,
  ts_user_created,
  ts_client_event,
  ts_client_uploaded,
  ts_server_received,
  ts_processed,
  year,
  month,
  day
FROM
  datalake_amplitude_new_clean.events
WHERE
  id_app = '170698' AND event_type = 'fs_mortgage_progress_step_clicked'
