SELECT
    id_amplitude,
    ids_amplitude_attributed,
    id_user,
    id_device,
    id_event,
    id_app,
    uuid,
    adid,
    id_session,
    id_schema,
    id_inserted,
    idfa,
    event_type,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    event_properties,
    GET_JSON_OBJECT(event_properties, '$.house_id') AS ep_house_id,
    GET_JSON_OBJECT(event_properties, '$.faq_category_id') AS faq_category_id,
    GET_JSON_OBJECT(event_properties, '$.faq_article_viewed') AS faq_article_viewed,
    GET_JSON_OBJECT(event_properties, '$.faq_category_name') AS faq_category_name,
    GET_JSON_OBJECT(event_properties, '$.origin') AS origin,
    user_properties,
    STRING(GET_JSON_OBJECT(user_properties, '$.platform')) AS up_app_type,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_source')) AS up_utm_source,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_medium')) AS up_utm_medium,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_campaign')) AS up_utm_campaign,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_content')) AS up_utm_content,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_term')) AS up_utm_term,
    GET_JSON_OBJECT(user_properties, '$.platform') AS up_platform,
    GET_JSON_OBJECT(user_properties, '$.referring_domain') AS up_referring_domain,
    is_paying,
    is_attribution_event,
    ts_server_received,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_processed,
    year,
    month,
    day
FROM
    datalake_amplitude_new_clean.events
WHERE
    id_app = '170698' AND event_type = 'faq_article_page_viewed'
