SELECT
    id_amplitude,
    ids_amplitude_attributed,
    id_app,
    id_device,
    id_event,
    id_session,
    id_inserted,
    id_user,
    id_schema,
    idfa,
    adid,
    uuid,
    TRANSFORM(SPLIT(GET_JSON_OBJECT(event_properties, '$.house_ids'), ','), x-> x::BIGINT) AS ids_houses,
    GET_JSON_OBJECT(event_properties, '$.id_agent')::BIGINT AS id_user_agent,
    GET_JSON_OBJECT(event_properties, '$.list_id') AS id_list,
    GET_JSON_OBJECT(event_properties, '$.list_name') AS list_name,
    GET_JSON_OBJECT(event_properties, '$.period') AS period,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_type,
    event_properties,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    user_properties,
    is_paying,
    is_attribution_event,
    DATE(ts_event) AS dt_event,
    ts_event,
    GET_JSON_OBJECT(event_properties, '$.date')::TIMESTAMP AS ts_desired_booking,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    ts_processed,
    year,
    month,
    day
FROM
    datalake_amplitude_new_clean.events
WHERE id_app = '170698' AND event_type = 'visit_list_request_schedule_button_clicked'
