SELECT
    id_amplitude,
    ids_amplitude_attributed,
    id_user,
    id_device,
    id_event,
    id_app,
    uuid,
    adid,
    id_session,
    id_schema,
    id_inserted,
    idfa,
    STRING(GET_JSON_OBJECT(event_properties, '$.house_id')) AS id_house,
    GET_JSON_OBJECT(event_properties, '$.search_id') AS id_search,
    TRANSFORM(FROM_JSON(GET_JSON_OBJECT(event_properties, '$.search_results_list'), 'array<string>'), x -> X::BIGINT) AS ids_search_results_list,
    event_type,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    event_properties,
    user_properties,
    STRING(GET_JSON_OBJECT(event_properties, '$.business_context')) AS business_context,
    STRING(GET_JSON_OBJECT(event_properties, '$.search_context')) AS search_context,
    STRING(GET_JSON_OBJECT(event_properties, '$.search_query_context')) AS search_query_context,
    STRING(GET_JSON_OBJECT(event_properties, '$.uri')) AS uri,
    REGEXP_EXTRACT(GET_JSON_OBJECT(event_properties, '$.uri'), '\/imovel\/([^\/|\?]+)', 1) AS search_location_slug,
    STRING(GET_JSON_OBJECT(event_properties, '$.view_mode')) AS view_mode,
    STRING(GET_JSON_OBJECT(event_properties, '$.sort_order')) AS sort_order,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_source')) AS utm_source,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_medium')) AS utm_medium,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_campaign')) AS utm_campaign,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_term')) AS utm_term,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_content')) AS utm_content,
    STRING(GET_JSON_OBJECT(user_properties , '$.platform')) AS up_platform,
    STRING(GET_JSON_OBJECT(user_properties, '$.entrance_uri')) AS entrance_uri,
    STRING(GET_JSON_OBJECT(user_properties, '$.referrer')) AS referrer,
    CASE
        WHEN GET_JSON_OBJECT(event_properties , '$.top5_house_id') <> '[]'
            THEN SPLIT(REGEXP_REPLACE(GET_JSON_OBJECT(event_properties , '$.top5_house_id'), '\\[|\\]|\\"', ''), ',')
        ELSE NULL
    END AS top5_house_id,
    is_paying,
    is_attribution_event,
    ts_server_received,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_processed,
    year,
    month,
    day
FROM
    datalake_amplitude_new_clean.events
WHERE
    id_app = '170698' AND event_type = 'search_page_viewed'
