SELECT
    CAST(id_amplitude AS INTEGER) AS id_amplitude,
    ids_amplitude_attributed,
    id_app,
    id_device,
    CAST(id_event AS INTEGER) AS id_event,
    CAST(id_session AS INTEGER) AS id_session,
    CAST(id_user AS INTEGER) AS id_user,
    id_schema,
    id_inserted,
    idfa,
    CAST(GET_JSON_OBJECT(event_properties, '$.house_id') AS INTEGER) AS id_house,
    adid,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    GET_JSON_OBJECT(event_properties, '$.early_credit_type') AS early_credit_event_type,
    event_type,
    event_properties,
    is_attribution_event,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    is_paying,
    region,
    start_version,
    user_properties,
    language,
    uuid,
    version_name,
    sample_rate,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_processed,
    year,
    month,
    day
FROM datalake_amplitude_new_clean.events
WHERE
    id_app = '170698' AND event_type = 'listing_early_credit_clicked'
