WITH first_administrator_informations AS (
  SELECT
    id_house_draft, 
    FROM_JSON(GET_JSON_OBJECT(administrators, '$.list'), 'array<string>')[0] AS first_administrator_informations
  FROM datalake_bob_clean.house_draft_aud
  WHERE GET_JSON_OBJECT(administrators, '$.list') IS NOT NULL 
)
SELECT
    hda.id_house_draft,
    id_client_side,
    id_original_lead,
    GET_JSON_OBJECT(first_administrator_informations, '$.mainId') AS id_main_administrator,
    rev, 
    rev_type,
    registrar,
    owners AS owners_informations,
    access AS house_access_informations, 
    administrators AS administrators_informations,
    NULLIF(GET_JSON_OBJECT(first_administrator_informations, '$.name'), '') AS main_administrator_name,
    NULLIF(GET_JSON_OBJECT(first_administrator_informations, '$.email'), '') AS main_administrator_email,
    NULLIF(GET_JSON_OBJECT(first_administrator_informations, '$.phone'), '') AS main_administrator_phone_number,    
    GET_JSON_OBJECT(details, '$.appliances') AS house_appliances,
    NULLIF(GET_JSON_OBJECT(details, '$.description'), '') AS house_description,
    GET_JSON_OBJECT(details, '$.frontDoorType') AS front_door_type,
    GET_JSON_OBJECT(details, '$.installations') AS installations,
    GET_JSON_OBJECT(details, '$.accessibilityItems') AS acessibility_items,
    CAST(GET_JSON_OBJECT(details, '$.movingAvailability.daysToVacate') AS SMALLINT) AS days_to_vacate,
    GET_JSON_OBJECT(details, '$.movingAvailability.availabilityType') AS availability_type,
    GET_JSON_OBJECT(details, '$.movingAvailability.awaitingAvailabilityReason') AS awaiting_availability_reason,
    NULLIF(GET_JSON_OBJECT(details, '$.movingAvailability.awaitingAvailabilityCustomReason'), '') AS awaiting_availability_custom_reason,
    CAST(GET_JSON_OBJECT(pricing, '$.rent') AS BIGINT) AS rent_price,
    CAST(GET_JSON_OBJECT(pricing, '$.salePrice') AS BIGINT) AS sale_price,
    CAST(GET_JSON_OBJECT(pricing, '$.condoPrice') AS BIGINT) AS condo_price,
    NULLIF(GET_JSON_OBJECT(pricing, '$.iptuList'), '[]') AS iptu_installment_informations,
    CAST(GET_JSON_OBJECT(pricing, '$.customAdmFee') AS DOUBLE) AS custom_administration_fee,
    NULLIF(GET_JSON_OBJECT(pricing, '$.specialConditions'), '[]') AS special_conditions,
    CAST(GET_JSON_OBJECT(blueprint, '$.suites') AS SMALLINT) AS suites,
    CAST(GET_JSON_OBJECT(blueprint, '$.garages') AS SMALLINT) AS garages,
    NULLIF(GET_JSON_OBJECT(blueprint, '$.garageDescription'), '') AS garages_description,
    CAST(GET_JSON_OBJECT(blueprint, '$.bedrooms') AS SMALLINT) AS bedrooms,
    CAST(GET_JSON_OBJECT(blueprint, '$.bathrooms') AS SMALLINT) AS bathrooms,
    GET_JSON_OBJECT(blueprint, '$.houseType') AS house_type,
    CAST(GET_JSON_OBJECT(blueprint, '$.totalArea') AS BIGINT) AS total_area,
    NULLIF(GET_JSON_OBJECT(business_context, '$.businessContextType'), '[]') AS business_context_type,
    status,
    type,
    CAST(GET_JSON_OBJECT(details, '$.isFurnished') AS BOOLEAN) AS is_furnished,
    CAST(GET_JSON_OBJECT(details, '$.isPenthouse') AS BOOLEAN) AS is_penthouse,
    CAST(GET_JSON_OBJECT(details, '$.isPetFriendly') AS BOOLEAN) AS is_pet_friendly,
    CAST(GET_JSON_OBJECT(pricing, '$.hasCondo') AS BOOLEAN) AS has_condo,
    CAST(GET_JSON_OBJECT(pricing, '$.iptuNotPaid') AS BOOLEAN) AS has_iptu_not_paid,
    CAST(GET_JSON_OBJECT(pricing, '$.acceptInstantOffer') AS BOOLEAN) AS is_accepting_instant_offer,
    mod_id_client_side,
    mod_id_original_lead,
    mod_registrar,
    mod_owners,
    mod_access,
    mod_administrators,
    mod_details,
    mod_pricing,
    mod_blueprint,
    mod_business_context,
    mod_status,
    mod_type,
    mod_ts_created,
    mod_ts_updated,
    CAST(CAST(GET_JSON_OBJECT(details, '$.movingAvailability.movingDate') AS BIGINT) AS TIMESTAMP) AS ts_moved_out,
    ts_created,
    ts_updated
FROM datalake_bob_clean.house_draft_aud hda 
LEFT JOIN first_administrator_informations fai
    ON fai.id_house_draft = hda.id_house_draft