class SparkTableStorageFormat:
    JSON = "JSON"
    PARQUET = "PARQUET"
    DEFAULT_RAW = JSON
    DEFAULT_CLEAN = PARQUET
    DEFAULT_CLEAN_STAGING = PARQUET
    DEFAULT_DW = PARQUET
    DEFAULT_DW_STAGING = PARQUET
