SELECT
    ID AS id,
    IDPropostaPRD AS id_proposal,
    IDUsuInc AS id_user_inc,
    IDUsuSolConf AS id_user_sol_conf,
    IDUsuConf AS id_user_confirmed,
    TipoProdutoOperacao AS operation_product_type,
    Canal AS channel,
    Prazo AS term,
    Taxa AS fee,
    IQ AS is_iq,
    Confirmado AS is_confirmed,
    VlrVendaImovel AS sale_property_value,
    VlrEntRecProp AS proposal_entry_value,
    VlrEntFGTS AS fgts_entry_value,
    VlrFinan AS financed_value,
    VlrAvalBco AS endorsement_bank_value,
    VlrTarAvalBco AS fee_endorsement_bank_value,
    VlrITBI AS itbi_value,
    VlrIQ AS iq_value,
    VlrTotalCont AS total_value,
    VlrPgtoVend AS payment_sale_value,
    TIMESTAMP(DataIQ) AS ts_iq,
    TIMESTAMP(DtInclusao) AS ts_inclusion,
    TIMESTAMP(DtSolConf) AS ts_sol_conf,
    TIMESTAMP(DtConfirmacao) AS ts_confirmation,
    TIMESTAMP(AtualizadoEm) AS ts_updated
FROM
    datalake_atta_raw.proposta_credimob_confval
