SELECT
    id                          AS id_proposal,
    idcliente                   AS id_client,
    IDConsultor                 AS id_consultant,
    IDCstImob                   AS id_pre_analysis,
    IDAnalistaCredito           AS id_credit_analyst,
    IDAnalistaJuridico          AS id_juridical_analyst,
    IDFornecEmissao             AS id_emission_provider,
    IDFranquia                  AS id_franchise,
    IDParceiro                  AS id_partner,
    IDProduto                   AS id_product,
    IDPropostaExt               AS id_offer,
    IDPropostaPrd               AS id_proposal_product,
    IDUsuDigitador              AS id_multibank_typist_user,
    CreatedBy                   AS created_by,
    SITUACAO                    AS id_proposal_situation,
    `STATUS`                    AS id_proposal_status,
    CPF                         AS client_cpf,
    Nome                        AS client_name,
    StatusTranslation           AS status_translation,
    ChosenBy                    AS chosen_by,
    MotivoCancelamento          AS cancellation_reason,
    Valor                       AS financing_value,
    TIMESTAMP(DtEntrada)        AS ts_registration,
    TIMESTAMP(DtFinalizacao)    AS ts_financing_ended,
    TIMESTAMP(DtUltAtu)         AS ts_last_updated,
    TIMESTAMP(ChosenAt)         AS ts_chosen
FROM
    datalake_atta_raw.proposta
