SELECT 
    id,
    datasource_id AS id_datasource,
    created_by_fk AS id_user_created,
    changed_by_fk AS id_user_changed,
    last_saved_by_fk AS id_user_last_saved,
    slice_name,
    datasource_type,
    datasource_name,
    viz_type,
    params,
    description,
    cache_timeout,
    perm,
    schema_perm,
    uuid,
    external_url,
    query_context,
    certified_by,
    certification_details,
    is_managed_externally,
    created_on AS ts_created,
    changed_on AS ts_changed,
    last_saved_at AS ts_last_saved,
    year,
    month,
    day
FROM datalake_superset_raw.slices
WHERE MAKE_DATE(year, month, day) BETWEEN {load_start_date} AND {load_end_date}