drop table if exists teravoz.fact_calls;
create table if not exists teravoz.fact_calls (
    sk_call varchar(30),
    sk_user bigint,
    sk_ticket bigint,
    sk_call_date bigint,
    sk_call_date_local bigint,
    total_queues smallint,
    total_unique_queues smallint,
    total_agents smallint,
    total_unique_agents smallint,
    seconds_total_call_duration int,
    seconds_total_talk_duration int,
    seconds_total_wait_duration int,
    seconds_total_ura_duration int,
    csat_rating smallint,
    is_call_answered boolean,
    is_csat_answered boolean,
    has_call_satisfied_customer boolean,
    is_call_ended_in_ura boolean,
    is_call_missed boolean,
    ts_ura_joined timestamp,
    ts_ura_joined_local timestamp,
    ts_ura_left timestamp,
    ts_ura_left_local timestamp,
    ts_first_call_answered timestamp,
    ts_first_call_answered_local timestamp,
    is_call_ended_and_answered_by_one_agent boolean,
    is_call_ended_and_answered_by_multiple_agents boolean,
    ts_started timestamp,
    ts_started_local timestamp,
    ts_csat_answered timestamp,
    ts_csat_answered_local timestamp,
    ts_ended timestamp,
    ts_ended_local timestamp,
    ts_load timestamp
)


