SELECT 
    id,
    visitor_id AS id_visitor,
    event_id AS id_event,
    reminder_type_id AS id_reminder_type,
    status,
    created_by,
    closed_by,
    creation_method,
    version,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    visitor_id_mod AS mod_id_visitor,
    event_id_mod AS mod_id_event,
    reminder_type_id_mod AS mod_id_reminder_type,
    status_mod AS mod_status,
    created_by_mod AS mod_created_by,
    closed_by_mod AS mod_closed_by,
    creation_method_mod AS mod_creation_method,
    date_mod AS mod_ts_reminder,
    closed_at_mod AS mod_ts_closed,
    date AS ts_reminder,
    created_at AS ts_created,
    updated_at AS ts_updated,
    closed_at AS ts_closed,
    year,
    month,
    day
FROM 
    datalake_hub_services_raw.reminder_aud