SELECT
    id,
    lead_id AS id_lead,
    responsible AS id_responsible,
    distributor AS id_distributor,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    version,
    active AS is_active,
    lead_id_mod AS mod_id_lead,
    active_mod AS mod_is_active,
    distributor_mod AS mod_id_distributor,
    responsible_mod AS mod_id_responsible,
    assigned_at_mod AS mod_ts_assigned,
    unassigned_at_mod AS mod_ts_unassigned,
    assigned_at AS ts_assigned,
    unassigned_at AS ts_unassigned,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_hub_services_raw.responsible_aud