SELECT
    id,
    user_id AS id_user,
    operation_event_id AS id_operation_event,    
    person_uuid AS uuid_person,
    operation_id AS id_operation,
    house_id AS id_house,
    operating_city_id AS id_operating_city,
    agent_id AS id_agent,
    agent_payment_id AS id_agent_payment,
    version,
    agent_type,
    agent_status,
    contract_type,
    operation_type,
    operation_agent_status,
    house_area,
    house_reference,
    meters_base_reference,
    meters_additional_reference,
    meters_total,
    additionals_total,
    fixed_reference,
    operation_business,
    schedule_date AS dt_schedule,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_partner_payment_raw.operation_payments