select
    firestore_id as id_firestore,
    bigint(houseId) as id_house,
    bigint(ownerId) as id_owner,
    bigint(partnerId) as id_partner,
    bigint(tenantId) as id_tenant,
    ownerIdString as owner_id_string,
    tenantIdString as tenant_id_string,
    code,
    comentario as comment,
    house,
    iteration,
    lastProposedRent as last_proposed_rent,
    lastProposedRentDraft as last_proposed_rent_draft,
    originOffer as origin_offer,
    originalRent as original_rent,
    originalTotal as original_total,
    rejectionReason as rejection_reason,
    rejectionReasonDescription as rejection_reason_description,
    resident,
    status,
    turn,
    type,
    tenantServiceFee,
    boolean(hasDraftTopics) as has_draft_topics,
    boolean(instantOffer) as is_instant_offer,
    boolean(visualized) as is_visualized,
    timestamp(lastSentDate) as ts_last_sent,
    timestamp(firstSentAt) as ts_first_sent,
    timestamp(deadline) as ts_deadline,
    timestamp(visualizedAt) as ts_visualized,
    timestamp(createdDate) as ts_created,
    timestamp(updated) as ts_updated,
    year,
    month,
    day
from datalake_firestore_raw.offers
where year={year} and month={month} and day={day}