SELECT
  id,
  _id,
  source_external_id AS id_external,
  rule_id AS id_rule,
  hugme_status,
  ra_status,
  ra,
  ra_reason,
  ra_feeling,
  favorable_assessment,
  information_source,
  source,
  company,
  last_feeling,
  feed_type,
  moderation,
  customer,
  user,
  account,
  rafone,
  can_like,
  commentary,
  complaint_title,
  complaint_content,
  complaint_response_content,
  interactions_count,
  interactions_not_readed_count,
  consumer_consideration,
  company_consideration,
  private_treatment_time,
  public_treatment_time,
  rating_time,
  CAST(rating AS INT) AS rating,
  CAST(rating_without_response AS INT) AS rating_without_response,
  CAST(comments_count AS INT) AS comments_count,
  CAST(redistributions_count AS INT) AS redistributions_count,
  redistributions_reason,
  CAST(ticket_moderations_count AS INT) AS ticket_moderations_count,
  CAST(ticket_messages_count AS INT) AS ticket_messages_count,
  contact_us,
  hugme_ticket_type,
  customer_interactions_count,
  company_interactions_count,
  CAST(assignment_count AS INT) AS assignment_count,
  duplicate_ticket,
  tags,
  extra_data,
  sticky_notes,
  autos,
  personalized_fields,
  attached,
  categories,
  historical,
  interactions,
  duplicate_tiqt,
  CAST(back_doing_business AS BOOLEAN) AS would_do_business_again,
  CAST(resolved_issue AS BOOLEAN) AS is_resolved_issue,
  CAST(active AS BOOLEAN) AS is_active,
  CAST(filed AS BOOLEAN) AS is_filed,
  CAST(request_moderation AS BOOLEAN) AS is_requested_moderation,
  CAST(request_evaluation AS BOOLEAN) AS is_requested_evaluation,
  CAST(frozen AS BOOLEAN) AS is_frozen,
  CAST(creation_date AS TIMESTAMP) AS ts_created,
  CAST(insertion_date AS TIMESTAMP) AS ts_inserted,
  CAST(complaint_response_date AS TIMESTAMP) AS ts_complaint_response,
  CAST(consumer_consideration_date AS TIMESTAMP) AS ts_consumer_consideration,
  CAST(company_consideration_date AS TIMESTAMP) AS ts_company_consideration,
  CAST(last_replica_date AS TIMESTAMP) AS ts_last_replica,
  CAST(last_modification_date AS TIMESTAMP) AS ts_last_modification,
  CAST(rating_date AS TIMESTAMP) AS ts_rating,
  CAST(closed_date AS TIMESTAMP) AS ts_closed,
  ts_load,
  year,
  month,
  day
FROM
  datalake_reclameaqui_raw.tickets
WHERE
  year = {year}
  AND month = {month}
  AND day = {day}