SELECT
    id AS id_house_draft,
    client_side_id AS id_client_side,
    original_lead_id AS id_original_lead,
    rev,
    revtype AS rev_type,
    registrar,
    owners,
    details,
    access,
    pricing,
    blueprint,
    status,
    business_context,
    type,
    administrators,
    attendance_info,
    client_side_id_mod AS mod_id_client_side,
    original_lead_id_mod AS mod_id_original_lead,
    registrar_mod AS mod_registrar,
    owners_mod AS mod_owners,
    details_mod AS mod_details,
    access_mod AS mod_access,
    pricing_mod AS mod_pricing,
    blueprint_mod AS mod_blueprint,
    status_mod AS mod_status,
    business_context_mod AS mod_business_context,
    type_mod AS mod_type,
    administrators_mod AS mod_administrators,
    attendance_info_mod AS mod_attendance_info,
    created_at_mod AS mod_ts_created,
    updated_at_mod AS mod_ts_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    YEAR(updated_at) AS year,
    MONTH(updated_at) AS month,
    DAY(updated_at) as day
FROM
    datalake_bob_raw.house_draft_aud
