SELECT
    house_draft_id AS id_house_draft,
    region_id AS id_region,
    rev,
    revtype AS rev_type,
    address,
    number,
    floor,
    complement,
    reference_point,
    neighborhood,
    city,
    state,
    zip_code,
    lat,
    lng,
    out_of_area AS is_out_of_area,
    house_draft_mod AS mod_id_house_draft,
    region_id_mod AS mod_id_region,
    address_mod AS mod_address,
    number_mod AS mod_number,
    floor_mod AS mod_floor,
    complement_mod AS mod_complement,
    reference_point_mod AS mod_reference_point,
    neighborhood_mod AS mod_neighborhood,
    city_mod AS mod_city,
    state_mod AS mod_state,
    zip_code_mod AS mod_zip_code,
    lat_mod AS mod_lat,
    lng_mod AS mod_lng,
    out_of_area_mod AS mod_is_out_of_area
FROM
    datalake_bob_raw.location_aud
