"""Migration EMR DAG — run transpiled queries on EMR, capture metrics to S3.

Auto-generated by emr-migration-v2 skill.
Run ID: 3eda59b6-f7c0-480d-b2d4-b04eabef7d51
Scope: for_rent/dw_inspections
"""

import os
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import urlparse

import yaml
from airflow import DAG, Dataset
from airflow.operators.python import PythonOperator

from bietlejuice.base.airflow.job_cluster_engine import (
    attach_emr_job_cluster_finished_work_prerequisites,
    attach_emr_terminate_cluster_work_prerequisites,
    attach_job_cluster_engine_to_context,
    get_job_cluster_completion_sink,
)
from bietlejuice.base.airflow.task_creators.dag_execution_context import (
    DagExecutionContext,
)
from bietlejuice.services.configuration_service import ConfigurationService

DAG_ID = "migration_emr_for_rent__dw_inspections"
RUN_ID = "3eda59b6-f7c0-480d-b2d4-b04eabef7d51"
DOMAIN = "for_rent"
SOURCE_DAG_NAME = "dw_inspections"
DATASET_URI = "migration:emr-for_rent__dw_inspections-complete"
RUN_PREFIX = "emr-migration/runs/3eda59b6-f7c0-480d-b2d4-b04eabef7d51"
REFERENCE_DATE = "2026-07-25"
RUNTIME = "emr"
SQL_DIR_NAME = "migration"

TABLES = [
    "dim_appointment_component",
    "dim_assessment",
    "dim_contestation",
    "dim_inspection",
    "dim_inspector",
    "dim_inspector_report",
    "dim_item",
    "dim_item_group",
    "dim_item_issue",
    "dim_item_media",
    "dim_item_review",
    "dim_repair_exempted",
    "dim_repair_request",
    "dim_reviewer",
    "dim_room",
    "fact_appointments",
    "fact_contestation",
    "fact_inspection",
    "fact_inspector_reports",
    "fact_item",
    "fact_item_attachment",
    "fact_item_issue",
    "fact_repair_request",
    "fact_report_inspections",
    "fact_report_review",
    "fact_reviewer_approval",
]

DAG_DIR = Path(__file__).resolve().parent
ENV = os.environ.get("ENVIRONMENT")
CONFIG_SERVICE = ConfigurationService(SOURCE_DAG_NAME)
BUCKET = CONFIG_SERVICE.get_config("datalake_bucket")
BIETLEJUICE_REPO_PATH = CONFIG_SERVICE.get_config("databricks_bietlejuice_repo_path")
METRIC_CAPTURE_JOB = (
    f"{BIETLEJUICE_REPO_PATH}/spark_jobs/migration_assets/metric_capture_job.py"
)
ARTIFACTS_URI = CONFIG_SERVICE.get_config("artifacts_bucket")
ARTIFACTS_BUCKET = urlparse(ARTIFACTS_URI).netloc or ARTIFACTS_URI

with open(DAG_DIR / f"{DAG_ID}_cluster.yml") as _f:
    CLUSTER_ARGS = yaml.safe_load(_f).get("cluster", {})


def _build_context(dag):
    ctx = DagExecutionContext(
        dag=dag,
        environment=ENV,
        bucket=BUCKET,
        base_spark_jobs_path=f"{BIETLEJUICE_REPO_PATH}/spark_jobs/base/",
        dag_args={},
        workflow_args={},
        cluster_args=CLUSTER_ARGS,
        databricks_conn_id=CLUSTER_ARGS.get("databricks_conn_id", "databricks_new_env"),
    )
    attach_job_cluster_engine_to_context(ctx, CONFIG_SERVICE)
    return ctx


def _get_s3_client():
    import boto3
    from airflow.models import Variable

    role_arn = Variable.get("DATASET_EVENTS_ASSUME_ROLE_ARN", default_var=None)
    if not role_arn:
        return boto3.client("s3")
    sts = boto3.client("sts")
    creds = sts.assume_role(
        RoleArn=role_arn,
        RoleSessionName="migration-s3-upload",
        DurationSeconds=3600,
    )["Credentials"]
    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
    ).client("s3")


def _upload_sql(**context):
    sql_dir = DAG_DIR / "queries" / SQL_DIR_NAME
    s3 = _get_s3_client()
    for table in TABLES:
        local_path = str(sql_dir / f"{table}.sql")
        s3_key = f"{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}.sql"
        s3.upload_file(local_path, ARTIFACTS_BUCKET, s3_key)


with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["migration", "emr", "validation"],
    default_args={"owner": "data-platform", "retries": 0},
    dagrun_timeout=timedelta(hours=4),
) as dag:
    ctx = _build_context(dag)

    upload_sql = PythonOperator(
        task_id="upload_sql",
        python_callable=_upload_sql,
    )

    execute_cluster = ctx.job_cluster_engine.create_execute_cluster_task(
        config_service=CONFIG_SERVICE,
        minimum_cluster_runtime_version=None,
        execute_job_cluster_local_id=None,
    )

    end = PythonOperator(
        task_id="end",
        python_callable=lambda **kw: None,
        outlets=[Dataset(DATASET_URI)],
    )

    capture_tasks = []

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_appointment_component",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_appointment_component",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_appointment_component",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_appointment_component",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_assessment",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_assessment",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_assessment",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_assessment",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_contestation",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_contestation",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_contestation",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_contestation",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_inspection",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_inspection",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_inspection",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_inspection",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_inspector",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_inspector",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_inspector",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_inspector",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_inspector_report",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_inspector_report",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_inspector_report",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_inspector_report",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_item",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_item",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_item_group",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item_group",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item_group",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_item_group",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_item_issue",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item_issue",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item_issue",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_item_issue",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_item_media",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item_media",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item_media",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_item_media",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_item_review",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item_review",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_item_review",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_item_review",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_repair_exempted",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_repair_exempted",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_repair_exempted",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_repair_exempted",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_repair_request",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_repair_request",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_repair_request",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_repair_request",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_reviewer",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_reviewer",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_reviewer",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_reviewer",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_room",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_room",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_room",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_room",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_appointments",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_appointments",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_appointments",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_appointments",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_contestation",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_contestation",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_contestation",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_contestation",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_inspection",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_inspection",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_inspection",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_inspection",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_inspector_reports",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_inspector_reports",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_inspector_reports",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_inspector_reports",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_item",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_item",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_item",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_item",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_item_attachment",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_item_attachment",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_item_attachment",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_item_attachment",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_item_issue",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_item_issue",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_item_issue",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_item_issue",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_repair_request",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_repair_request",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_repair_request",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_repair_request",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_report_inspections",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_report_inspections",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_report_inspections",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_report_inspections",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_report_review",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_report_review",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_report_review",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_report_review",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_reviewer_approval",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_reviewer_approval",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_reviewer_approval",
                "--run-id",
                RUN_ID,
                "--runtime",
                "emr",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_reviewer_approval",
                "--reference-date",
                REFERENCE_DATE,
            ],
            execution_timeout_hours=2,
        )
    )

    cluster_completion = get_job_cluster_completion_sink(ctx, execute_cluster, end)
    attach_emr_job_cluster_finished_work_prerequisites(
        ctx, job_cluster_finished_task=end, work_completion_tasks=capture_tasks
    )

    upload_sql >> execute_cluster >> capture_tasks >> cluster_completion
    attach_emr_terminate_cluster_work_prerequisites(
        ctx,
        cluster_completion,
        execute_job_cluster_task=execute_cluster,
        job_cluster_finished_task=end,
    )
