SELECT
  absence_type_id AS id_absence_type,
  legal_entity_id AS id_legal_entity,
  period_of_service_id AS id_period_of_service,
  person_id AS id_person,
  per_absence_entry_id AS id_per_absence_entry,
  enterprise_id AS id_enterprise,
  legislative_data_group_id AS id_legislative_data_group,
  absence_pattern_cd AS absence_pattern_code,
  absence_status_cd AS absence_status_code,
  approval_status_cd AS approval_status_code,
  created_by,
  last_updated_by AS updated_by,
  user_mode,
  approval_outcome,
  abs_record_source,
  comments,
  attribute_number2 AS vacation_cash_out_request,
  attribute1 AS period,
  attribute2 AS advance_13th_salary,
  attribute3 AS medical_leave_code,
  CAST(duration AS INT) AS days_duration,
  CAST(object_version_number AS INT) AS object_version_number,
  overridden = 'Y' AS is_overridden,
  absence_entry_basic_flag = 'Y' AS is_absence_entry_basic,
  single_day_flag = 'Y' AS is_single_day,
  employee_shift_flag = 'Y' AS is_employee_shift,
  certification_auth_flag = 'Y' AS is_certification_auth,
  initial_timely_notify_flag = 'Y' AS is_initial_timely_notify,
  period_of_incap_to_work_flag = 'Y' AS is_period_of_incap_to_work,
  late_notify_flag = 'Y' AS is_late_notify,
  payroll_chg_flag = 'Y' AS is_payroll_change,
  open_ended_flag = 'Y' AS is_open_ended,
  ess_duration_update = 'Y' AS is_ess_duration_update,
  TO_DATE(SPLIT(attribute1, '_')[0], 'dd/MM/yyyy') AS dt_period_started,
  TO_DATE(SPLIT(attribute1, '_')[1], 'dd/MM/yyyy') AS dt_period_ended,
  TO_DATE(start_date) AS dt_started,
  TO_DATE(end_date) AS dt_ended,
  TO_DATE(submitted_date) AS dt_submitted,
  TO_DATE(notification_date) AS dt_notificated,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  TO_TIMESTAMP(approval_datetime) AS ts_approved,
  TO_TIMESTAMP(start_datetime) AS ts_started,
  TO_TIMESTAMP(end_datetime) AS ts_ended,
  TO_TIMESTAMP(submitted_datetime) AS ts_submitted,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_absence_raw.anc_per_abs_entries