SELECT
  absence_type_id AS id_absence_type,
  enterprise_id AS id_enterprise,
  legislative_data_group_id AS id_legislative_data_group,
  absence_validation_formula_id AS id_absence_validation_formula,
  ben_elig_profile_id AS id_benefit_eligibility_profile,
  anc_absence_types_f_altcd AS absence_type_foreign_alternative_code,
  approval_routing_cd AS approval_routing_code,
  duration_uom_cd AS duration_unit_of_measure_code,
  legislation_code AS legislation_code,
  linkage_reason_cd AS linkage_reason_code,
  max_duration_rule_cd AS maximum_duration_rule_code,
  mgr_allow_updates_cd AS manager_allowed_updates_code,
  mgr_lock_if_confirm_cd AS manager_lock_if_confirmed_code,
  min_duration_rule_cd AS minimum_duration_rule_code,
  linkage_start_rule_cd AS linkage_start_rule_code,
  linkage_uom_cd AS linkage_unit_of_measure_code,
  management_type_cd AS management_type_code,
  pattern_cd AS pattern_code,
  agreement_flag,
  timecard_avail_flag AS timecard_available_flag,
  emp_allow_updates_cd AS employee_allowed_updates_code,
  emp_lock_if_confirm_cd AS employee_lock_if_confirmed_code,
  admin_allow_updates_cd AS administrator_allowed_updates_code,
  dur_calc_basis AS duration_calculation_basis,
  attach_type,
  base_name,
  created_by,
  last_updated_by AS updated_by,
  status,
  linkage_rule_cd = 'Y' AS has_linkage_rule_code,
  incl_openend_abs_eval = 'Y' AS has_open_ended_absence_evaluation,
  timekeeper_avail_flag = 'Y' AS is_timekeeper_available,
  attach_admin_flag = 'Y' AS is_attachment_enabled_for_administrator,
  attach_emp_flag = 'Y' AS is_attachment_enabled_for_employee,
  attach_mgr_flag = 'Y' AS is_attachment_enabled_for_manager,
  bidding_enabled_flag = 'Y' AS is_bidding_enabled,
  CAST(min_duration AS INT) AS minimum_duration,
  CAST(max_duration AS INT) AS maximum_duration,
  CAST(eval_extn_period AS INT) AS evaluation_extension_period,
  CAST(eval_period AS INT) AS evaluation_period,
  CAST(object_version_number AS INT) AS object_version_number,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  TO_DATE(effective_start_date) AS dt_effective_started,
  TO_DATE(effective_end_date) AS dt_effective_ended,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_absence_raw.anc_absence_types_f