SELECT
    id,
    marital_status_id AS id_marital_status,
    gender_identity_id AS id_gender_identity,
    name,
    last_name,
    email,
    salary,
    alternative_email,
    phone,
    cellphone,
    registration AS registration_number,
    gender,
    natural_from_state_uf,
    natural_from_city_name,
    gender_identity,
    relationship,
    ethnicity,
    documents,
    department,
    job,
    dismissal,
    supervisor,
    address,
    cost_center,
    salary_type,
    benefits,
    custom_fields,
    educations,
    experience_period,
    emergency_contacts,
    first_job AS is_first_job,
    time_tracking AS has_time_tracking,
    birth_date AS dt_birth,
    hiring_date AS dt_hiring
FROM
    datalake_convenia_details_raw.inactive_employee_details
