SELECT  
    'schedule_page_viewed' AS tof_event_type,
    ep_house_id,
    id_user,
    id_amplitude,
    id_device,
    business_context,
    entrance_uri,
    referrer,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_term,
    utm_content,
    up_platform,
    top5_house_id,
    ts_event,
    year,
    month,
    day
FROM 
    datalake_amplitude_clean.170698_schedule_page_viewed_events 
UNION ALL
SELECT  
    'search_page_viewed' AS tof_event_type,
    id_house as ep_house_id,
    id_user,
    id_amplitude,
    id_device,
    business_context,
    entrance_uri,
    referrer,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_term,
    utm_content,
    up_platform,
    top5_house_id,
    ts_event,
    year,
    month,
    day
FROM 
    datalake_amplitude_clean.170698_search_page_viewed_events 
UNION ALL
SELECT 
    'search_results_page_viewed' AS tof_event_type,
    ep_house_id,
    id_user,
    id_amplitude,
    id_device,
    business_context,
    entrance_uri,
    referrer,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_term,
    utm_content,
    up_platform,
    top5_house_id,
    ts_event,
    year,
    month,
    day
FROM 
    datalake_amplitude_clean.170698_search_results_page_viewed_events 
UNION ALL
SELECT      
    'listing_page_viewed' AS tof_event_type,
    ep_house_id,
    id_user,
    id_amplitude,
    id_device,
    business_context,
    entrance_uri,
    referrer,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_term,
    utm_content,
    up_platform,
    top5_house_id,
    ts_event,
    year,
    month,
    day
FROM 
    datalake_amplitude_clean.170698_listing_page_viewed_events
