SELECT
  GET_JSON_OBJECT(updated_message, '$.offerId') AS id_offer,
  CAST(GET_JSON_OBJECT(updated_message, '$.texto90.value') AS BIGINT) AS id_buyer,
  CAST(GET_JSON_OBJECT(updated_message, '$.texto1.value') AS BIGINT) AS id_house,
  CAST(GET_JSON_OBJECT(updated_message, '$.pessoas1.value') AS BIGINT) AS id_closing_specialist,
  CAST(GET_JSON_OBJECT(updated_message, '$.pessoas.value') AS BIGINT) AS id_consultant,
  CAST(GET_JSON_OBJECT(updated_message, '$.text1.value') AS BIGINT) AS id_agent,
  CAST(GET_JSON_OBJECT(updated_message, '$.text5.value') AS BIGINT) AS id_fifty_agent,
  CAST(REGEXP_EXTRACT(GET_JSON_OBJECT(updated_message, '$.lista_suspensa.value'), '(\\w+)') AS BIGINT) AS real_estate_register_office_number,
  CAST(REGEXP_EXTRACT(GET_JSON_OBJECT(updated_message, '$.forma_de_pagamento4.value'), '(\\w+)') AS BIGINT) AS payment_method,  
  CAST(GET_JSON_OBJECT(updated_message, '$.numbers.value') AS FLOAT) AS offer_acceptance_probability,
  CAST(GET_JSON_OBJECT(updated_message, '$.valor_do_an_ncio.value') AS FLOAT) AS listing_sale_price,
  CAST(GET_JSON_OBJECT(updated_message, '$.valor_da_proposta.value') AS FLOAT) AS price_offered_by_buyer,
  CAST(GET_JSON_OBJECT(updated_message, '$.valor_do_an_ncio2.value') AS FLOAT) AS price_offered_by_seller,
  CAST(GET_JSON_OBJECT(updated_message, '$.n_meros3.value') AS FLOAT) AS sale_price_agreed,
  CAST(GET_JSON_OBJECT(updated_message, '$.n_umero5.value') AS FLOAT) AS brokerage_fee,
  CAST(GET_JSON_OBJECT(updated_message, '$.entrada____7.value') AS FLOAT) AS deed_value,
  CAST(GET_JSON_OBJECT(updated_message, '$.n_meros9.value') AS FLOAT) AS fgts_value,
  CAST(GET_JSON_OBJECT(updated_message, '$.entrada____2.value') AS FLOAT) AS financing_value,
  CAST(GET_JSON_OBJECT(updated_message, '$.fgts____.value') AS FLOAT) AS payment_entry_amount,
  CAST(GET_JSON_OBJECT(updated_message, '$.entrada.value') AS FLOAT) AS value_in_cash,
  GET_JSON_OBJECT(updated_message, '$.texto41.value') AS financing_bank,
  GET_JSON_OBJECT(updated_message, '$.grupo.id') AS status,
  GET_JSON_OBJECT(updated_message, '$.status_de_negocia__o.value') AS offer_status,
  GET_JSON_OBJECT(updated_message, '$.status88.value') AS bank_analysis_status,
  GET_JSON_OBJECT(updated_message, '$.an_lise_de_cr_dito.value') AS credit_status, 
  GET_JSON_OBJECT(updated_message, '$.status9.value') AS notary_office_status,
  GET_JSON_OBJECT(updated_message, '$.cart_rio_de_notas.value') AS real_estate_register_office_status,
  GET_JSON_OBJECT(updated_message, '$.status4.value') AS house_dilligence_status,
  GET_JSON_OBJECT(updated_message, '$.status6.value') AS seller_dilligence_status,
  GET_JSON_OBJECT(updated_message, '$.status.value') AS sale_agreement_status,
  GET_JSON_OBJECT(updated_message, '$.ccv.value') AS payment_status,
  GET_JSON_OBJECT(updated_message, '$.status2.value') AS seller_payment_status,
  GET_JSON_OBJECT(updated_message, '$.status_do_processo.value') AS closing_status,
  GET_JSON_OBJECT(updated_message, '$.disparo_nps.value') AS sale_agreement_cancellation_reason,
  GET_JSON_OBJECT(updated_message, '$.motivo_de_descarte2.value') AS drop_reason_before_acceptance,
  GET_JSON_OBJECT(updated_message, '$.motivo_de_descarte_pr_.value') AS drop_reason_after_acceptance,
  GET_JSON_OBJECT(updated_message, '$.motivos_de_descarte__dm_.value') AS drop_reason,
  GET_JSON_OBJECT(updated_message, '$.status47.value') AS house_occupant,
  GET_JSON_OBJECT(updated_message, '$.status_12.value') AS land_tenure,
  COALESCE(CAST(GET_JSON_OBJECT(updated_message, '$.iq_morando_.value') AS BOOLEAN), FALSE) AS has_seller_debt_payments,
  CAST(GET_JSON_OBJECT(updated_message, '$.id_im_vel6.value') AS DATE) AS dt_submitted,
  CAST(GET_JSON_OBJECT(updated_message, '$.data_proposta.value') AS DATE) AS dt_accepted,
  CAST(GET_JSON_OBJECT(updated_message, '$.data21.value') AS DATE) AS dt_offer_dismissed,
  CAST(GET_JSON_OBJECT(updated_message, '$.data22.value') AS DATE) AS dt_last_follow_up,
  CAST(GET_JSON_OBJECT(updated_message, '$.data41.value') AS DATE) AS dt_last_buyer_follow_up,
  CAST(GET_JSON_OBJECT(updated_message, '$.data5.value') AS DATE) AS dt_last_seller_follow_up,
  CAST(GET_JSON_OBJECT(updated_message, '$.data_assinatura_ccv4.value') AS DATE) AS dt_sale_agreement_created,
  CAST(GET_JSON_OBJECT(updated_message, '$.data27.value') AS DATE) AS dt_sale_agreement_signed,
  CAST(GET_JSON_OBJECT(updated_message, '$.data0.value') AS DATE) AS dt_bank_legal_analysis_started,
  CAST(GET_JSON_OBJECT(updated_message, '$.data15.value') AS DATE) AS dt_financing_started,
  CAST(GET_JSON_OBJECT(updated_message, '$.data10.value') AS DATE) AS dt_financing_ended,
  CAST(GET_JSON_OBJECT(updated_message, '$.data_envio.value') AS DATE) AS dt_dilligence_started,
  CAST(GET_JSON_OBJECT(updated_message, '$.data_in_cio_dilig_ncia.value') AS DATE) AS dt_dilligence_ended,
  CAST(GET_JSON_OBJECT(updated_message, '$.data_retorno_dilig_ncia_para_cliente5.value') AS DATE) AS dt_credit_analysis_started,
  CAST(GET_JSON_OBJECT(updated_message, '$._cr_dito__in_cio.value') AS DATE) AS dt_credit_analysis_ended,
  CAST(GET_JSON_OBJECT(updated_message, '$.data_in_cio_cr_dito.value') AS DATE) AS dt_credit_analysis_result_answered,
  CAST(GET_JSON_OBJECT(updated_message, '$.data24.value') AS DATE) AS dt_notes_registry_started,
  CAST(GET_JSON_OBJECT(updated_message, '$.data95.value') AS DATE) AS dt_notes_registry_ended,
  CAST(GET_JSON_OBJECT(updated_message, '$.data_1.value') AS DATE) AS dt_house_registry_started,
  CAST(GET_JSON_OBJECT(updated_message, '$.data91.value') AS DATE) AS dt_house_registry_ended,
  CAST(GET_JSON_OBJECT(updated_message, '$.data09.value') AS DATE) AS dt_sale_transacton_paid,
  CAST(GET_JSON_OBJECT(updated_message, '$.data29.value') AS DATE) AS dt_sale_key_delivered,
  CAST(GET_JSON_OBJECT(updated_message, '$.data26.value') AS DATE) AS dt_kit_delivered
FROM datalake_firestore_clean.monday
