drop table if exists booking;
create table if not exists booking (
  id integer not null,
  data date not null,
  status varchar(255) NOT NULL,
  visit_intent varchar(100),
  buyer_intention varchar(100),
  tipo varchar(255) NOT NULL,
  confirmado varchar(100),
  encerrado varchar(100),
  "agenteFixo" varchar(100),
  "fupVisita" varchar(255),
  "dataFupVisita" timestamp,
  "reagendadoDe_id" integer,
  visitante_id bigint,
  visita_id bigint,
  imovel_id bigint,
  agente_id bigint,
  atendente_id bigint,
  "fluxoLocacao_id" bigint,
  "criadoEm" timestamp,
  "atualizadoEm" timestamp,
  "slotDia" integer,
  reason text,
  reason_category varchar(255),
  last_update_source varchar(255),
  is_visit_last_updated_from_app boolean,
  cancel_timestamp timestamp,
  ts_first_canceled_unevaluated timestamp,
  first_update_source varchar(255),
  is_visit_created_from_app boolean,
  visitor_arrived varchar(255),
  visitor_missing_reason varchar(255),
  agent_arrived varchar(255),
  agent_missing_reason varchar(255),
  owner_arrived varchar(255),
  owner_missing_reason varchar(255),
  successful_entrance varchar(255),
  troublesome_entrance varchar(255),
  checkin_status varchar(255),
  reason_enum varchar(255)
);