DROP TABLE IF EXISTS public.contract_person;
CREATE TABLE public.contract_person (
   id bigint,
   cpf varchar(19),
   dataExpedicaoRG date,
   dataNascimento date,
   email varchar(255),
   nome varchar(255),
   rg varchar(255),
   sexo varchar(255),
   telefone varchar(255),
   telefoneSecundario varchar(255),
   contrato_id bigint,
   bairro varchar(200),
   cep varchar(200),
   cidade varchar(200),
   complemento varchar(200),
   endereco varchar(200),
   estadoCivil varchar(255),
   numero varchar(200),
   orgaoExpedidor varchar(255),
   profissao varchar(254),
   estado_id bigint,
   tipo  varchar(255),
   nacionalidade varchar(254),
   atualizadoEm timestamp,
   criadoEm timestamp,
   usuario_id bigint,
   vaiMorar integer,
   legalRepresentative_cpf  varchar(18),
   legalRepresentative_email varchar(255),
   legalRepresentative_nome varchar(255),
   legalRepresentative_rg varchar(255),
   withRepresentative integer
)
WITH (oids = false);