drop table if exists contract;
create table if not exists contract (
  id bigint,
  rent numeric(14,2),
  day_month_due smallint,
  guarantee varchar,
  type varchar,
  status varchar,
  dt_start date,
  ts_signature timestamp,
  ts_draft_approved timestamp,
  dt_entrance date,
  dt_intended_end date,
  dt_annulment date,
  condo_payer varchar,
  condo_responsible varchar,
  iptu_payer varchar,
  iptu_responsible varchar,
  rental_insurance_installments smallint,
  rental_insurance_value numeric(14,2),
  home_insurance_installments smallint,
  home_insurance_value numeric(14,2),
  first_rental_commission numeric(14,2),
  monthly_administration_fee double precision,
  condo numeric(14,2),
  iptu numeric(14,2),
  tenant_service_fee numeric(5,2),
  is_tenant_service_fee_opt_out boolean,
  ts_tenant_service_fee_opt_out timestamp,
  signature_type varchar,
  closing_status varchar,
  ts_created timestamp,
  ts_updated timestamp,
  ts_canceled timestamp,
  cancellation_reason varchar,
  id_proposal bigint,
  id_house bigint,
  ts_analyst_annulment_input timestamp,
  contract_version varchar,
  is_ongoing_contract boolean
) with (oids = false)
;
