drop table if exists contract;
create table if not exists contract (
  id bigint,
  rent numeric(14,2),
  day_month_due smallint,
  guarantee varchar,
  type varchar,
  status varchar,
  dt_start date,
  ts_signature timestamp,
  ts_draft_approved timestamp,
  dt_entrance date,
  dt_intended_end date,
  dt_annulment date,
  condo_payer varchar,
  condo_responsible varchar,
  iptu_payer varchar,
  iptu_responsible varchar,
  rental_insurance_installments smallint,
  rental_insurance_value numeric(14,2),
  home_insurance_installments smallint,
  home_insurance_value numeric(14,2),
  first_rental_commission numeric(14,2),
  condo numeric(14,2),
  iptu numeric(14,2),
  signature_type varchar,
  closing_status varchar,
  ts_created timestamp,
  ts_updated timestamp,
  cancellation_reason varchar,
  id_proposal bigint
) with (oids = false)
;
