drop table public.fact_house_listing_flows;

create table public.fact_house_listing_flows (
	id bigint NOT NULL,
	lead_id integer,
	conversao_id integer,
	photo_job_id integer,
	imovel_id bigint,
	rep_id integer,
	affiliate_id integer,
	region_id integer,
	dt_lead timestamp without time zone,
	dt_prospect timestamp without time zone,
	dt_first_inside_sales_contact timestamp without time zone,
	dt_conversion timestamp without time zone,
	dt_qualified timestamp without time zone,
	dt_opportunity timestamp without time zone,
	dt_first_listing timestamp without time zone,
	dt_discarded timestamp without time zone,
	flow character varying(255) DEFAULT NULL::character varying,
	acquisition_method character varying(255) DEFAULT NULL::character varying,
	acquisition_channel character varying(255) DEFAULT NULL::character varying,
	acquisition_source character varying(255) DEFAULT NULL::character varying,
	funnel_step character varying(255) DEFAULT NULL::character varying,
	hours_lead_to_prospect decimal(10,1),
	hours_prospect_to_qualified decimal(10,1),
	hours_lead_to_first_inside_sales_contact decimal(10,1),
	hours_prospect_to_first_inside_sales_contact decimal(10,1),
	hours_qualified_to_opportunity decimal(10,1),
	hours_opportunity_to_listing decimal(10,1),
	hours_lead_to_listing decimal(10,1),
	days_lead_to_prospect decimal(10,1),
	days_prospect_to_qualified decimal(10,1),
	days_lead_to_first_inside_sales_contact decimal(10,1),
	days_prospect_to_first_inside_sales_contact decimal(10,1),
	days_qualified_to_opportunity decimal(10,1),
	days_opportunity_to_listing decimal(10,1),
	days_lead_to_listing decimal(10,1),
	days_lead_to_processing decimal(10,1)
)