drop table if exists house_rent_flow;
create table house_rent_flow (
  id_house_rent_flow bigint,
  id_house integer not null,
	dt_house_first_listing timestamp,
  id_booking integer,
  dt_booking_created timestamp,
  dt_visit timestamp,
  id_owner integer,
  id_user_agent integer,
  id_client integer,
  dt_client_sign_up timestamp,
  dt_agent_sign_up timestamp,
  id_visit integer,
  visit_completed integer,
  visit_created_from_app integer,
  visit_created_type varchar(14),
  visit_last_updated_from_app integer,
  visit_last_updated_type varchar(14),
  id_rent_flow integer,
  dt_rent_flow_created timestamp,
  id_offer integer,
  id_pre_proposal integer,
  id_proposal integer,
  dt_proposal_approved timestamp,
  id_contract integer,
  dt_contract_created timestamp,
  dt_contract_signed timestamp,
  dt_contract_annulment timestamp
)
;