drop table if exists public.imovel ;
create table public.imovel (
  id bigint default '0'::bigint not null,
  aluguel integer,
  bairro varchar(200) default null::character varying,
  cep varchar(200) default null::character varying,
  cidade varchar(200) default null::character varying,
  complemento varchar(200) default null::character varying,
  condominio integer,
  data_construcao varchar(255) default null::character varying,
  elevador smallint,
  email_contato varchar(200) default null::character varying,
  email_sessao_fotos varchar(200) default null::character varying,
  endereco varchar(200) default null::character varying,
  estado_conservacao varchar(255) default null::character varying,
  fotografo_preenche_dados integer,
  iptu integer,
  lat numeric(10,7) default null::numeric,
  lng numeric(10,7) default null::numeric,
  mobiliado integer,
  nivel_acabamento varchar(255) default null::character varying,
  numero varchar(200) default null::character varying,
  numero_banheiros integer,
  numero_quartos integer,
  numero_suites integer,
  numero_vagas integer,
  porcentagem_cadastro_completa integer,
  prefere_email_sessao_fotos integer,
  status varchar(255) default null::character varying,
  tel_contato1 varchar(20) default null::character varying,
  tel_contato2 varchar(20) default null::character varying,
  tel_sessao_fotos varchar(20) default null::character varying,
  tipo varchar(255) default null::character varying,
  tipo_porteiro varchar(255) default null::character varying,
  tipo_vagas varchar(255) default null::character varying,
  verificado integer,
  usuario_id bigint,
  codigo_promocao varchar(50) default null::character varying,
  cotar_seguro smallint,
  valor_total integer,
  expiration_date timestamp without time zone,
  first_publication timestamp without time zone,
  notificacao_anuncio_incompleto_proprietario smallint,
  notificacao_anuncio_incompleto_admin smallint,
  short_url varchar(64) default null::character varying,
  valor_seguro integer,
  instrucoes_agendamento text,
  plano_aceito varchar(255) default null::character varying,
  sugerir_reajuste_de_preco integer,
  permite_placa_aluga_se integer not null,
  descricao_lead text,
  prioridade_destaque_classificado integer,
  corretor_amigo text,
  porteiro_amigo text,
  dados_administradora_condominio varchar(200) default null::character varying,
  referencias text,
  condominio_incluso integer,
  coordenadas_manuais integer,
  iptu_incluso integer,
  followup_proprietario_subir_fotos integer,
  data_primeiro_verificado timestamp without time zone,
  tipo_colisao_lead varchar(255) default null::character varying,
  calculo_pagamento_lead_corretor timestamp without time zone,
  nome_imagem_capa varchar(200) default null::character varying,
  geo_hash varchar(16) default null::character varying,
  tipo_anuncio varchar(255) default null::character varying,
  infos_admin text,
  infos_admin_interna text,
  historico_agendamento_fotos text,
  calculo_pagamento_lead_afiliado timestamp without time zone,
  possui_banheiro_servico integer,
  possui_quarto_servico integer,
  bairro_padrao varchar(200) default null::character varying,
  tipo_condominio varchar(255) default null::character varying,
  tipo_iptu varchar(255) default null::character varying,
  disponivel_ate date,
  flag_verificar_preco_comparando_com_media integer,
  sempre_consultar_proprietario_visita smallint,
  email_publicacao_proprietario_enviado integer,
  status_conversao_imovel varchar(255) default null::character varying,
  matricula varchar(255) default null::character varying,
  ultimo_email_de_confirmacao_enviado timestamp without time zone,
  latlng text,
  ultimo_update_indice timestamp without time zone,
  titulo varchar(255) default null::character varying,
  suspenso_ate timestamp without time zone,
  external_id varchar(255) default null::character varying,
  em_negociacao smallint,
  em_negociacao_externa smallint,
  entrou_em_negociacao_externa timestamp without time zone,
  motivo_recusa_cardiff text,
  recaptado_em timestamp without time zone,
  job_fotografo_pendente smallint,
  requisitou_fotos_profissionais smallint,
  last_confirmation_availability timestamp without time zone,
  cartorio varchar(255) default null::character varying,
  penalization_score integer,
  receber_copia_contrato_padrao smallint,
  rank_score integer,
  ultima_publicacao timestamp without time zone,
  confirmado_informacoes_visita integer,
  estado_abreviacao varchar(200) default null::character varying,
  estado_nome varchar(200) default null::character varying,
  regiao_cidade varchar(200) default null::character varying,
  regiao_macro varchar(200) default null::character varying,
  regiao_sub varchar(200) default null::character varying,
  regiao_id integer,
  condominio_nome varchar(200) default null::character varying,
  local_nome varchar(255),
  info_visita_autorizacao_de_entrada integer,
  info_visita_proprietario_acompanha integer,
  info_visita_estamos_liberados integer,
  info_visita_prop_precisa_liberar integer,
  info_visita_chave_box_quintoandar integer,
  data_criacao timestamp without time zone default now() not null,
  atualizado_em timestamp without time zone,
  usuario_que_cadastrou_id integer,
  imovel_v3 integer,
  area_total integer,
  area_terreno integer,
  unpublished_reason varchar(255),
  exclusivity smallint,
  house_occupant varchar(50),
  key_type varchar(50),
  key_location varchar(50),
  visit_restriction varchar(50)
)
with (oids = false);
