drop table if exists lead;
create table if not exists lead (
  id bigint not null,
  area_total integer,
  bairro varchar(200),
  captado_em date,
  cep varchar(9),
  cidade varchar(200),
  complemento varchar(200),
  endereco varchar(200),
  nome_anunciante varchar(255),
  numero varchar(200),
  numero_banheiros integer,
  numero_quartos integer,
  numero_suites integer,
  url_anuncio varchar(255),
  telefone_anunciante varchar(100),
  tipo varchar(255),
  email varchar(250),
  email_captador varchar(250),
  telefone_captador varchar(250),
  dentro_area_atuacao integer default 0,
  lat numeric(10,7),
  lng numeric(10,7),
  condominio integer,
  iptu integer,
  reason varchar(255),
  reason_detail varchar(255),
  status varchar(255),
  processado smallint,
  origem varchar(255),
  external_id varchar(255),
  mencionar integer,
  automatically_discarded integer,
  proprietario_nome varchar(255),
  proprietario_email varchar(255),
  affiliate_type varchar(255),
  dados_afiliado_inicio_atuacao timestamp,
  dados_afiliado_cidade_atuacao varchar(100),
  region_id integer,
  atualizado_em timestamp,
  criado_em timestamp,
  utm_medium varchar(255),
  utm_campaign varchar(255),
  utm_source varchar(255),
  usuario_que_indicou_id bigint,
  codigo_imobiliaria varchar(255),
  flg_b2b boolean
);

create unique index lead_id_idx on lead (id);
CREATE INDEX lead_usuario_que_indicou_id_idx ON public."lead" (usuario_que_indicou_id);
CREATE INDEX lead_telefone_anunciante_idx ON public."lead" (telefone_anunciante);
CREATE INDEX lead_cidade_idx ON public."lead" (cidade);

