drop table public.listing_flows_with_reprocessed_leads;

create table public.listing_flows_with_reprocessed_leads (
	id bigint NOT NULL,
	lead_id integer,
	conversao_id integer,
	photo_job_id integer,
	imovel_id bigint,
	rep_id integer,
	isales_registrant_id integer,
	affiliate_id integer,
	region_id integer,
	dt_lead timestamp without time zone,
	dt_prospect timestamp without time zone,
	dt_first_contact timestamp without time zone,
	dt_conversion timestamp without time zone,
	dt_qualified timestamp without time zone,
	dt_opportunity timestamp without time zone,
	dt_first_listing timestamp without time zone,
	dt_discarded timestamp without time zone,
	ts_sales_company_sent timestamp without time zone,
	user_id_lead_first_discarder integer,
	user_id_lead_last_discarder integer,
	is_self_service_photo_job_scheduled boolean,
	flow character varying(255) DEFAULT NULL::character varying,
	acquisition_method character varying(255) DEFAULT NULL::character varying,
	acquisition_channel character varying(255) DEFAULT NULL::character varying,
	acquisition_source character varying(255) DEFAULT NULL::character varying,
	funnel_step character varying(255) DEFAULT NULL::character varying,
	hours_lead_to_prospect decimal(10,1),
	hours_prospect_to_qualified decimal(10,1),
	hours_lead_to_first_contact decimal(10,1),
	hours_prospect_to_first_contact decimal(10,1),
	hours_qualified_to_opportunity decimal(10,1),
	hours_opportunity_to_listing decimal(10,1),
	hours_lead_to_listing decimal(10,1),
	days_lead_to_prospect decimal(10,1),
	days_prospect_to_qualified decimal(10,1),
	days_lead_to_first_contact decimal(10,1),
	days_prospect_to_first_contact decimal(10,1),
	days_qualified_to_opportunity decimal(10,1),
	days_opportunity_to_listing decimal(10,1),
	days_lead_to_listing decimal(10,1),
	days_lead_to_processing decimal(10,1),
	acquisition_channel_rep character varying(255) DEFAULT NULL::character varying,
	origin_lead_usuario_que_indicou_id bigint,
	is_not_reprocessed boolean,
	is_b2b boolean,
	partner_id bigint,
	affiliate_type character varying(255) DEFAULT NULL::character varying,
	is_agent_referral boolean
);

CREATE INDEX reproc_leads_lead_id_idx ON public.listing_flows_with_reprocessed_leads USING btree (lead_id);
CREATE INDEX reproc_leads_imovel_id_idx ON public.listing_flows_with_reprocessed_leads USING btree (imovel_id);
