drop table if exists portability;
create table if not exists portability (
  id integer not null,
  id_house integer,
  id_flow integer,
  id_house_address_estado integer,
  id_region integer,
  is_tenant integer,
  owner_type varchar,
  ts_created timestamp,
  ts_updated timestamp,
  ts_contract_started timestamp,
  ts_contract_ended timestamp,
  current_condo_fee numeric(14,2),
  current_iptu_twelth numeric(14,2),
  current_rent numeric(14,2),
  house_address_neighboor varchar(200),
  house_address_cep varchar(200),
  house_address_city varchar(200),
  house_address_complement varchar(200),
  house_address_street varchar(200),
  house_address_number varchar(200),
  house_type varchar(200),
  lat numeric(10,7),
  lng numeric(10,7),
  owner_data_email varchar(100),
  owner_data_gender varchar(50),
  owner_data_name varchar(100),
  owner_data_phone_number varchar(50),
  status varchar(50),
  tenant_data_email varchar(100),
  tenant_data_gender varchar(50),
  tenant_data_name varchar(100),
  tenant_data_phone_number varchar(50),
  contract_observations varchar
);