drop table if exists pre_proposal;
create table if not exists pre_proposal (
  id integer not null,
  "aceitoAluguel" integer,
  "aceitoComprovarRenda" integer,
  "aceitoEncargos" integer,
  aluguel integer,
  "aluguelOriginal" integer,
  "condominioOriginal" integer,
  dt_analysis timestamp,
  edicao varchar(255),
  status varchar(255),
  "proprietarioAceitouCondicoes5A" integer,
  usuario_id bigint,
  imovel_id bigint,
  "criadoEm" timestamp,
  "atualizadoEm" timestamp,
  "ultimoUpdateEdicao" integer,
  "dataPrimerioEnvio" timestamp,
  code varchar(255),
  rejection_reason varchar(255),
  animais_condition integer,
  quando_vai_mudar_condition integer,
  quem_vai_morar_condition integer,
  special_conditions_count integer,
  remove_conditions integer,
  include_conditions integer,
  maintenance_or_repair_conditions integer,
  replace_or_modify_conditions integer,
  other_conditions integer
);