drop table if exists pre_proposal_AUD;
create table if not exists pre_proposal_AUD (
  "id" bigint not null,
  "REV" integer not null,
  "rEVTYPE" smallint,
  "aceitoAluguel" smallint,
  "aceitoAluguel_MOD" smallint,
  "aceitoComprovarRenda" smallint,
  "aceitoComprovarRenda_MOD" smallint,
  "aceitoEncargos" smallint,
  "aceitoEncargos_MOD" smallint,
  "aluguel" integer,
  "aluguel_MOD" smallint,
  "dataAprovacao" timestamp,
  "edicao" varchar(255),
  "edicao_MOD" smallint,
  "proprietarioAceitouCondicoes5A" smallint,
  "status" varchar(255),
  "status_MOD" smallint,
  "animais_id" bigint,
  "animais_MOD" smallint,
  "condicoes_MOD" smallint,
  "imovel_id" bigint,
  "imovel_MOD" smallint,
  "quandoVaiMudar_id" bigint,
  "quandoVaiMudar_MOD" smallint,
  "quemVaiMorar_id" bigint,
  "quemVaiMorar_MOD" smallint,
  "usuario_id" bigint,
  "usuario_MOD" smallint,
  "aluguelOriginal" integer,
  "condominioOriginal" integer,
  "iptuOriginal" integer,
  "homeOwnerInsuranceOriginalValue" decimal(18,4),
  "expirationDate" timestamp,
  "rejectionReason" varchar(255),
  "code" varchar(255),
  "visualizedDate" timestamp,
  "visualizedDate_MOD" smallint,
  primary key ("id","REV")
);