drop table if exists proposal;
create table if not exists proposal (
  id integer not null,
  "dataParaMudanca" public.datetime null,
  "dataProposta" public.datetime null,
  garantia VARCHAR(50) null,
  motivacao VARCHAR(100),
  "propostaAluguel" double precision null,
  status VARCHAR(50) null,
  "dataAprovacao" public.datetime,
  "inquilinoEnviouDocumentos" integer null,
  "dataDocumentosEnviados" public.datetime,
  "proprietarioEnviouDocumentos" integer null,
  "dataDocumentosProprietarioEnviados" timestamp,
  "inquilinoAceitouContrato" integer null,
  "proprietarioAceitouContrato" integer null,
  "statusDocumentacaoInq" VARCHAR(50) null,
  "statusDocumentacaoProp" VARCHAR(50) null,
  "fazerTermoAditivo" integer null,
  "preProposta_id" integer,
  "offer_id" integer,
  "criadoEm" timestamp null,
  "atualizadoEm" timestamp null,
  tenant_doc_sent_count integer null,
  tenant_first_doc_sent public.datetime,
  tenant_auto_first_doc_sent,
  credit_analysis_init_date timestamp,
  credit_analysis_end_date timestamp,
  doc_reused
)
WITH (oids = false);