drop table if exists proposal;
create table if not exists proposal (
  id integer not null,
  "dataParaMudanca" timestamp null,
  "dataProposta" timestamp null,
  garantia varchar(50) null,
  motivacao varchar(100),
  "propostaAluguel" double precision null,
  status varchar(50) null,
  "dataAprovacao" timestamp,
  "inquilinoEnviouDocumentos" integer,
  "dataDocumentosEnviados" timestamp,
  "proprietarioEnviouDocumentos" integer,
  "dataDocumentosProprietarioEnviados" timestamp,
  "inquilinoAceitouContrato" integer,
  "proprietarioAceitouContrato" integer,
  "statusDocumentacaoInq" varchar(50),
  "statusDocumentacaoProp" varchar(50),
  "fazerTermoAditivo" integer,
  "preProposta_id" integer,
  "offer_id" integer,
  "criadoEm" timestamp,
  "atualizadoEm" timestamp,
  tenant_doc_sent_count integer,
  tenant_first_doc_sent timestamp,
  tenant_auto_first_doc_sent timestamp,
  credit_analysis_init_date timestamp,
  credit_analysis_end_date timestamp,
  doc_reused integer,
  ts_processed timestamp,
  rejection_reason varchar
);