drop table if exists usuario;
create table usuario (
  id bigint primary key,
  nome varchar(255),
  bairro varchar(255),
  cep varchar(255),
  cidade varchar(255),
  complemento varchar(255),
  cpf varchar(255),
  data_nascimento timestamp,
  email varchar(255),
  email_alternativo varchar(255),
  endereco varchar(255),
  numero varchar(255),
  facebook_id varchar(255),
  linkedin_id varchar(255),
  sexo varchar(255),
  telefone_principal varchar(255),
  estado_abreviacao varchar(200),
  estado_nome varchar(200),
  bloqueado integer,
  rg varchar(30),
  dadosagente_perfil varchar(255),
  dadosagente_numero_creci varchar(255),
  dadosagente_ativo integer,
  aceita_sms integer,
  data_clickanuncie timestamp,
  dadosbancarios_banco_codigo varchar(255),
  dadosbancarios_banco varchar(255),
  dadosbancarios_agencia varchar(255),
  dadosbancarios_conta_corrente varchar(255),
  dadosbancarios_cpf_cnpj varchar(255),
  dadosbancarios_nome varchar(255),
  dadosbancarios_outro_titular integer,
  dadosbancarios_tipo_conta varchar(255),
  tipo_admin varchar(255),
  google_id varchar(255),
  dadosfotografo_inicio_contrato timestamp,
  dadosfotografo_tipo_contrato varchar(255),
  dadosfotografo_ativo integer,
  dadosvendedor_inicio_contrato timestamp,
  dadosafiliado_inicio_atuacao timestamp,
  dadosafiliado_cidade_atuacao varchar(100),
  dadosafiliado_preferencia_pagamento varchar(255),
  dadosafiliado_numero_creci varchar(255),
  dadosafiliado_semana_ultima_comunicacao_balanco integer,
  dadosafiliado_ativo integer,
  active integer,
  dados_agente_id bigint,
  dados_fotografo_id bigint,
  dados_vendedor_id bigint,
  dados_afiliado_id bigint,
  flg_doorman_affiliate smallint,
  dt_doorman_joined timestamp,
  tem_imovel smallint,
  tem_app_inquilino smallint,
  tem_contrato_ativo smallint,
  inquilino smallint,
  first_dt_document_sent timestamp,
  last_dt_document_sent timestamp,
  first_dt_sent_to_insurance timestamp,
  criado_em timestamp ,
  atualizado_em timestamp,
  contacorrente_id bigint
);

CREATE INDEX telefone_principal_idx ON public."usuario" (telefone_principal);
CREATE unique INDEX id_idx ON public."usuario" (id);
