select
    business_context,
    dimension_name,
    dimension_value,
    metric_name,
    metric_numerator,
    metric_denominator,
    metric_value,
    date_granularity,
    date
from
  datalake_search_metrics_service_raw.search_metrics
