SELECT
    NULLIF(broker, '') AS broker,
    NULLIF(company_cluster, '') AS company_cluster,
    NULLIF(account_manager, '') AS account_manager,
    NULLIF(ops_squad, '') AS ops_squad,
    NULLIF(secretaria_vendas, '') AS sale_secretariat,
    NULLIF(expert, '') AS expert,
    NULLIF(commercial_division, '') AS commercial_division,
    NULLIF(business_model, '') AS business_model,
    NULLIF(visit_booked, '') AS visit_booked,
    NULLIF(visit_confirmed, '') AS visit_confirmed,
    NULLIF(offer_sent, '') AS offer_sent,
    NULLIF(offer_accepted, '') AS offer_accepted,
    NULLIF(contract_signed_total, '') AS contract_signed_total,         
    NULLIF(contract_signed_high_ticket, '') AS contract_signed_high_ticket,
    NULLIF(ongoing_listing, '') AS ongoing_listing,
    NULLIF(first_listing_total, '') AS first_listing_total,
    NULLIF(first_listing_first_batch, '') AS first_listing_first_batch,
    NULLIF(first_listing_recurrent, '') AS first_listing_recurrent,
    NULLIF(first_listing_high_ticket, '') AS first_listing_high_ticket,
    NULLIF(leads_total, '') AS leads_total,
    NULLIF(leads_first_batch, '') AS leads_first_batch,
    NULLIF(leads_recurrent, '') AS leads_recurrent,
    NULLIF(leads_high_ticket, '') AS leads_high_ticket,
    NULLIF(month, '') AS dt_month,
    NULLIF(day, '') AS dt_day,
    NOW() AS ts_load
FROM
    datalake_gsheets_raw.3p_partners_performance_targets