SELECT
    COALESCE(id_payment, -1) AS sk_payment,
    COALESCE(id_propose, -1) AS sk_propose,
    COALESCE(id_occurrence, -1) AS sk_occurrence,
    COALESCE(CAST(id_propose_values AS BIGINT), -1) AS sk_propose_values,
    COALESCE(id_billing_type, -1) AS sk_billing_type,
    COALESCE(id_payment_type, -1) AS sk_payment_type,
    COALESCE(id_status, -1) AS sk_status,
    COALESCE(id_payment_gateway, -1) AS sk_payment_gateway,
    COALESCE(id_payment_category, -1) AS sk_payment_category,
    id_customer,
    id_unicid,
    id_subscription,
    billing_type,
    payment_type,
    status,
    payment_gateway,
    payment_category,
    invoice_url,
    description,
    due_amount,
    net_amount,
    is_paid_late,
    is_due_modified,
    is_occurrence,
    is_recurring_subscription,
    dt_created,
    dt_due,
    dt_due_original,
    dt_paid,
    dt_payment_confirmed,
    ts_updated,
    is_legacy,
    NOW() AS ts_load
FROM
    datalake_velo.payment_legacy
