WITH 
    requests AS (
        SELECT 
            judicial_process,
            bonus_salary,
            hazard_pay,
            night_surcharge,
            advance_notice,
            function_desviation,
            commissions_difference,
            vacations,
            cct_gratification,
            succumbence_fees,
            overtime_8_44,
            working_hours_overtime,
            reduced_nighttime_overtime,
            compensation_material_damage,
            compensation_moral_damage,
            compensation_pregnant_stability,
            sunday_holiday_labor,
            fine_467_clt,
            fine_477_clt,
            fine_cct,
            employment_relationship_recognition,
            repeat_undue_discounts,
            ctps_retification,
            rsr,
            joint_or_subsidiary_liability,
            bonus_salary_second_instance,
            hazard_pay_second_instance,
            night_surcharge_second_instance,
            advance_notice_second_instance,
            function_desviation_second_instance,
            commissions_difference_second_instance,
            vacations_second_instance,
            cct_gratification_second_instance,
            succumbence_fees_second_instance,
            overtime_8_44_second_instance,
            working_hours_overtime_second_instance,
            reduced_nighttime_overtime_second_instance,
            compensation_material_damage_second_instance,
            compensation_moral_damage_second_instance,
            compensation_pregnant_stability_second_instance,
            sunday_holiday_labor_second_instance,
            fine_467_clt_second_instance,
            fine_477_clt_second_instance,
            fine_cct_second_instance,
            employment_relationship_recognition_second_instance,
            repeat_undue_discounts_second_instance,
            ctps_retification_second_instance,
            rsr_second_instance,
            joint_or_subsidiary_liability_second_instance,
            COALESCE(bonus_salary_second_instance, bonus_salary) AS bonus_salary_last,
            COALESCE(hazard_pay_second_instance, hazard_pay) AS hazard_pay_last,
            COALESCE(night_surcharge_second_instance, night_surcharge) AS night_surcharge_last,
            COALESCE(advance_notice_second_instance, advance_notice) AS advance_notice_last,
            COALESCE(function_desviation_second_instance, function_desviation) AS function_desviation_last,
            COALESCE(commissions_difference_second_instance, commissions_difference) AS commissions_difference_last,
            COALESCE(vacations_second_instance, vacations) AS vacations_last,
            COALESCE(cct_gratification_second_instance, cct_gratification) AS cct_gratification_last,
            COALESCE(succumbence_fees_second_instance, succumbence_fees) AS succumbence_fees_last,
            COALESCE(overtime_8_44_second_instance, overtime_8_44) AS overtime_8_44_last,
            COALESCE(working_hours_overtime_second_instance, working_hours_overtime) AS working_hours_overtime_last,
            COALESCE(reduced_nighttime_overtime_second_instance, reduced_nighttime_overtime) AS reduced_nighttime_overtime_last,
            COALESCE(compensation_material_damage_second_instance, compensation_material_damage) AS compensation_material_damage_last,
            COALESCE(compensation_moral_damage_second_instance, compensation_moral_damage) AS compensation_moral_damage_last,
            COALESCE(compensation_pregnant_stability_second_instance, compensation_pregnant_stability) AS compensation_pregnant_stability_last,
            COALESCE(sunday_holiday_labor_second_instance, sunday_holiday_labor) AS sunday_holiday_labor_last,
            COALESCE(fine_467_clt_second_instance, fine_467_clt) AS fine_467_clt_last,
            COALESCE(fine_477_clt_second_instance, fine_477_clt) AS fine_477_clt_last,
            COALESCE(fine_cct_second_instance, fine_cct) AS fine_cct_last,
            COALESCE(employment_relationship_recognition_second_instance, employment_relationship_recognition) AS employment_relationship_recognition_last,
            COALESCE(repeat_undue_discounts_second_instance, repeat_undue_discounts) AS repeat_undue_discounts_last,
            COALESCE(ctps_retification_second_instance, ctps_retification) AS ctps_retification_last,
            COALESCE(rsr_second_instance, rsr) AS rsr_last,
            COALESCE(joint_or_subsidiary_liability_second_instance, joint_or_subsidiary_liability) AS joint_or_subsidiary_liability_last
        FROM 
            datalake_gsheets_clean.legal_base_docato
    ),
    requests_unpivot AS (
        SELECT 
            judicial_process, 
            STACK(72, 'advance_notice_last', advance_notice_last, 
                'advance_notice_second_instance', advance_notice_second_instance, 
                'advance_notice', advance_notice, 
                'bonus_salary_last', bonus_salary_last, 
                'bonus_salary_second_instance', bonus_salary_second_instance, 
                'bonus_salary', bonus_salary, 
                'cct_gratification_last', cct_gratification_last, 
                'cct_gratification_second_instance', cct_gratification_second_instance, 
                'cct_gratification', cct_gratification, 
                'commissions_difference_last', commissions_difference_last, 
                'commissions_difference_second_instance', commissions_difference_second_instance, 
                'commissions_difference', commissions_difference, 
                'compensation_material_damage_last', compensation_material_damage_last, 
                'compensation_material_damage_second_instance', compensation_material_damage_second_instance, 
                'compensation_material_damage', compensation_material_damage, 
                'compensation_moral_damage_last', compensation_moral_damage_last, 
                'compensation_moral_damage_second_instance', compensation_moral_damage_second_instance, 
                'compensation_moral_damage', compensation_moral_damage, 
                'compensation_pregnant_stability_last', compensation_pregnant_stability_last, 
                'compensation_pregnant_stability_second_instance', compensation_pregnant_stability_second_instance, 
                'compensation_pregnant_stability', compensation_pregnant_stability, 
                'ctps_retification_last', ctps_retification_last, 
                'ctps_retification_second_instance', ctps_retification_second_instance, 
                'ctps_retification', ctps_retification, 
                'employment_relationship_recognition_last', employment_relationship_recognition_last, 
                'employment_relationship_recognition_second_instance', employment_relationship_recognition_second_instance, 
                'employment_relationship_recognition', employment_relationship_recognition, 
                'fine_467_clt_last', fine_467_clt_last, 
                'fine_467_clt_second_instance', fine_467_clt_second_instance, 
                'fine_467_clt', fine_467_clt, 
                'fine_477_clt_last', fine_477_clt_last, 
                'fine_477_clt_second_instance', fine_477_clt_second_instance, 
                'fine_477_clt', fine_477_clt, 
                'fine_cct_last', fine_cct_last, 
                'fine_cct_second_instance', fine_cct_second_instance, 
                'fine_cct', fine_cct, 
                'function_desviation_last', function_desviation_last, 
                'function_desviation_second_instance', function_desviation_second_instance, 
                'function_desviation', function_desviation, 
                'hazard_pay_last', hazard_pay_last, 
                'hazard_pay_second_instance', hazard_pay_second_instance, 
                'hazard_pay', hazard_pay, 
                'joint_or_subsidiary_liability_last', joint_or_subsidiary_liability_last, 
                'joint_or_subsidiary_liability_second_instance', joint_or_subsidiary_liability_second_instance, 
                'joint_or_subsidiary_liability', joint_or_subsidiary_liability, 
                'night_surcharge_last', night_surcharge_last, 
                'night_surcharge_second_instance', night_surcharge_second_instance, 
                'night_surcharge', night_surcharge, 
                'overtime_8_44_last', overtime_8_44_last, 
                'overtime_8_44_second_instance', overtime_8_44_second_instance, 
                'overtime_8_44', overtime_8_44, 
                'reduced_nighttime_overtime_last', reduced_nighttime_overtime_last, 
                'reduced_nighttime_overtime_second_instance', reduced_nighttime_overtime_second_instance, 
                'reduced_nighttime_overtime', reduced_nighttime_overtime, 
                'repeat_undue_discounts_last', repeat_undue_discounts_last, 
                'repeat_undue_discounts_second_instance', repeat_undue_discounts_second_instance, 
                'repeat_undue_discounts', repeat_undue_discounts, 
                'rsr_last', rsr_last, 
                'rsr_second_instance', rsr_second_instance, 
                'rsr', rsr, 
                'succumbence_fees_last', succumbence_fees_last, 
                'succumbence_fees_second_instance', succumbence_fees_second_instance, 
                'succumbence_fees', succumbence_fees, 
                'sunday_holiday_labor_last', sunday_holiday_labor_last, 
                'sunday_holiday_labor_second_instance', sunday_holiday_labor_second_instance, 
                'sunday_holiday_labor', sunday_holiday_labor, 
                'vacations_last', vacations_last, 
                'vacations_second_instance', vacations_second_instance, 
                'vacations', vacations, 
                'working_hours_overtime_last', working_hours_overtime_last, 
                'working_hours_overtime_second_instance', working_hours_overtime_second_instance, 
                'working_hours_overtime', working_hours_overtime) AS (request, result) 
        FROM 
            requests
    ),
    requests_unpivot_clean AS (
        SELECT 
            judicial_process,
            CASE
                when SUBSTRING(request, -5) = '_last' THEN  LEFT(request, LENGTH(request) - 5)
                when SUBSTRING(request, -16) = '_second_instance' THEN LEFT(request, LENGTH(request) - 16)
                ELSE request
            END AS request_type,
            CASE
                WHEN substring(request, -5) = '_last' THEN  'last'
                WHEN substring(request, -16) = '_second_instance' THEN 'second instance'
                ELSE 'first'
            END AS instance,
            CASE
                WHEN result IN ('Indeferido', 'Indefeiro') THEN  'indeferido'
                WHEN result IN ('Deferido') THEN 'deferido'
                ELSE NULL
            END AS result
        FROM 
            requests_unpivot
    )

SELECT 
    judicial_process,
    request_type,
    instance,
    result
FROM 
    requests_unpivot_clean