SELECT 
    id_amplitude,
    ids_amplitude_attributed,
    CAST(GET_JSON_OBJECT(event_properties, '$.house_id') AS BIGINT) AS id_house,
    id_user,
    id_device,
    id_event,
    id_app,
    uuid,
    adid,
    id_session,
    id_schema,
    id_inserted,
    idfa,
    event_type,
    amplitude_event_type,
    GET_JSON_OBJECT(user_properties, '$.ab_beakman_owner_house_setup') AS up_ab_beakman_owner_house_setup,
    GET_JSON_OBJECT(user_properties, '$.rc_beakman_owners_listing_performance_rent_toggle') AS up_rc_beakman_owners_listing_performance_rent_toggle,
    GET_JSON_OBJECT(user_properties, '$.rc_beakman_owners_listing_performance_sale_toggle') AS up_rc_beakman_owners_listing_performance_sale_toggle,
    GET_JSON_OBJECT(event_properties, '$.business_contexts') AS ep_business_context,
    GET_JSON_OBJECT(event_properties, '$.content_business_context') AS ep_content_business_context,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    event_properties,
    user_properties,
    is_paying,
    is_attribution_event,
    ts_server_received,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_processed,
    year,
    month,
    day
FROM 
    datalake_amplitude_clean_staging.183047_property_performance_hub_price_card_button_clicked_events
WHERE 
    year={} 
    AND month={} 
    AND day={}