SELECT
    id_amplitude,
    ids_amplitude_attributed,
    CAST((GET_JSON_OBJECT(event_properties, '$.house_id')) AS BIGINT) AS id_house,
    id_user,
    GET_JSON_OBJECT(user_properties, '$.ab_beakman_owner_price_feedback') AS up_ab_beakman_owner_price_feedback,
    id_device,
    id_app,
    id_event,
    id_session,
    id_inserted,
    id_schema,
    idfa,
    adid,
    uuid,
    amplitude_event_type,
    city,
    country,
    region,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_type,
    event_properties,
    GET_JSON_OBJECT(event_properties, '$.house_business_contexts') AS ep_business_context,
    GET_JSON_OBJECT(event_properties, '$.rent_price_recommended_feedback') AS ep_rent_price_recommended_feedback,
    GET_JSON_OBJECT(event_properties, '$.sale_price_recommended_feedback') AS ep_sale_price_recommended_feedback,
    is_attribution_event,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    is_paying,
    start_version,
    language,
    version_name,
    sample_rate,
    user_properties,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    ts_processed,
    year,
    month,
    day
FROM 
    datalake_amplitude_clean_staging.183047_property_edit_hub_page_viewed_events
WHERE 
    year={} 
    AND month={} 
    AND day={}