SELECT
    id_amplitude,
    ids_amplitude_attributed,
    id_user,
    id_device,
    id_event,
    id_app,
    uuid,
    adid,
    id_session,
    id_schema,
    id_inserted,
    idfa,
    event_type,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    event_properties,
    CAST(GET_JSON_OBJECT(event_properties, '$.business_context') AS STRING) AS business_context,
    user_properties,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_campaign') AS STRING) AS utm_campaign,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_medium') AS STRING) AS utm_medium,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_source') AS STRING) AS utm_source,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_content') AS STRING) AS utm_content,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_term') AS STRING) AS utm_term,
    CAST(GET_JSON_OBJECT(user_properties , '$.platform') AS STRING) AS app_type,
    CAST(GET_JSON_OBJECT(user_properties , '$.referring_domain') AS STRING) AS referring_domain,
    is_paying,
    is_attribution_event,
    ts_server_received,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_processed,
    year,
    month,
    day
FROM
    datalake_amplitude_clean_staging.203461_inspector_app_add_photo_clicked_events
WHERE
    year={} and month={} and day={}
