select
    id,
    imovel_id as id_house,
    vistoriador_id as id_user_inspector,
    contrato_id as id_contract,
    schedule_id as id_booking,
    bigint(ref_id) as id_ref,
    finalReportPdfId as id_final_report_pdf,
    status,
    comentario as comment,
    hash,
    browserAprovacaoInquilino as browser_tenant_approval,
    browserAprovacaoProprietario as browser_owner_approval,
    comentarioInquilino as tenant_comment,
    comentarioProprietario as owner_comment,
    ipAprovacaoInquilino as ip_tenant_approval,
    ipAprovacaoProprietario as ip_owner_approval,
    soAprovacaoInquilino as os_tenant_approval,
    soAprovacaoProprietario as os_owner_approval,
    tipo as type,
    mode,
    shortRevisarInq as short_review_tenant,
    shortRevisarProp as short_review_owner,
    lastReportSent as last_report_sent,
    keyLocation as key_location,
    keyLocationDetails as key_location_details,
    version,
    scheduleObservations as schedule_observations,
    reportRevised as report_revised,
    aprovadoInquilino as is_tenant_approved,
    aprovadoProprietario as is_owner_approved,
    scheduleDoubleChecked as is_schedule_double_checked,
    reportFinished as is_report_finished,
    itenCommented as is_item_commented,
    finalReportCreated as is_final_report_created,
    inspectorGotAllInfo as has_inspector_got_all_info,
    finalReportSentAt as dt_final_report_sent,
    dataVistoria as dt_inspected,
    dataAprovacaoInquilino as ts_tenant_approved,
    dataAprovacaoProprietario as ts_owner_approved,
    partialTenantReportSentAt as ts_partial_tenant_report_sent,
    partialOwnerReportSentAt as ts_partial_owner_report_sent,
    expiraEm as ts_expired,
    criadoEm as ts_created,
    atualizadoEm as ts_updated
from
    datalake_ebdb_test_raw.vistoria
