SELECT
    id,
    contract_id AS id_contract,
    boleto_identifier AS id_boleto,
    external_id AS id_external,
    sync_status,
    cyber_sync_status,
    external_sub_status,
    external_status,
    purpose,
    negativate,
    our_number,
    entries,
    charge_data,
    payment_method,
    is_tenant_first_invoice,
    previously_negotiated,
    accrual_year_month,
    paid_amount,
    due_amount,
    due_date AS dt_due,
    paid_date AS dt_paid,
    sent_at AS ts_sent,
    creation_date AS ts_creation,
    created_at AS ts_created,
    updated_at AS ts_updated,
    last_received_at AS ts_last_received
FROM datalake_trato_feito_raw.bill
