SELECT
    id,
    external_id AS id_external,
    contract_id AS id_contract,
    status_syncs,
    creditor,
    document,
    document_type,
    marital_status,
    name,
    birth_date,
    phones,
    emails,
    client_type,
    debtor_origin,
    will_live_in_place,
    evictions_situation,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM datalake_trato_feito_raw.client
