SELECT
    id,
    external_id AS id_external,
    contract_id AS id_contract,
    person_uuid,
    status_syncs,
    creditor,
    document,
    document_type,
    marital_status,
    name,
    birth_date,
    phones,
    emails,
    client_type,
    debtor_origin,
    will_live_in_place,
    evictions_situation,
    deleted,
    negativated_boavista,
    negativated_serasa,
    negativation_updated_at AS ts_negativation_updated,
    created_at AS ts_created,
    updated_at AS ts_updated,
    NOW() AS ts_load
FROM datalake_trato_feito_raw.client
