SELECT
    CAST(id AS BIGINT) AS id_contract_segment_distribution_history,
    CAST(segment_id AS BIGINT) AS id_segment,
    CAST(audience_id AS BIGINT) AS id_audience,
    contract_id AS id_contract,
    customer_ids AS id_customer,
    active AS is_active,
    active_mod AS is_active_modified,
    segment_id_mod AS is_segment_modified,
    audience_id_mod AS is_audience_modified,
    contract_id_mod AS is_contract_modified,
    entered_segment_at_mod AS is_entered_segment_modified,
    entered_audience_at_mod AS is_entered_audience_modified,
    last_appearance_date_mod AS is_last_appearance_modified,
    customer_ids_mod AS is_id_customers_modified,
    CAST(rev AS BIGINT) AS revision_number,
    revtype AS revision_type,
    revend AS revision_end,
    last_appearance_date AS dt_last_appearance,
    entered_segment_at AS ts_entered_segment,
    entered_audience_at AS ts_entered_audience,
    created_at AS ts_created,
    updated_at AS ts_updated,
    NOW() AS ts_load
FROM
    datalake_trato_feito_raw.contract_segment_distribution_history
