SELECT
    id,
    external_id AS id_external,
    imovel_id AS id_imovel,
    debtor_id AS id_debtor,
    sync_status,
    cyber_sync_status,
    guarantee,
    external_status,
    version,
    rental_administrator,
    consultancy,
    rev,
    rental_amount,
    iptu_installments,
    iptu_amount,
    condominium_amount,
    total_amount,
    guarantee_start_date AS dt_guarantee_start,
    end_date AS dt_end,
    expected_end_date AS dt_expected_end,
    start_date AS dt_start,
    created_at AS ts_created,
    updated_at AS ts_updated,
    last_received_at AS ts_last_received,
    consultancy_updated_at AS ts_consultancy_updated
FROM datalake_trato_feito_raw.contract
