SELECT
    id AS id_legal_process_history,
    external_id AS id_external,
    entity_id AS id_entity,
    process_type,
    entity_type,
    law_firm,
    status,
    active AS is_active,
    status_order,
    version,
    rev,
    revtype,
    revend,
    process_type_mod AS has_process_type_modified,
    entity_type_mod AS has_entity_type_modified,
    law_firm_mod AS has_law_firm_modified,
    status_mod AS has_status_modified,
    active_mod AS has_active_modified,
    external_id_mod AS has_id_external_modified,
    entity_id_mod AS has_id_entity_modified,
    status_order_mod AS has_status_order_modified,
    last_update_event_at_mod AS has_ts_last_update_event_modified,
    last_update_event_at AS ts_last_update_event,
    created_at AS ts_created,
    updated_at AS ts_updated,
    NOW() AS ts_load
FROM datalake_trato_feito_raw.legal_process_history
