SELECT
    id,
    partner_id AS id_partner,
    file_id AS id_file,
    listing_id AS id_listing,
    lead_id AS id_lead,
    lead_uuid AS uuid_lead,
    real_estate_id AS id_real_estate,
    id_by_real_estate,
    status,
    brokers,
    location,
    pricing,
    owner,
    blueprint,
    details,
    access,
    administrators,
    photos,
    lead_hash,
    status_reason,
    cnpj,
    version,
    sent_to_main AS is_sent_to_main,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    partner_id_mod AS mod_id_partner,
    file_id_mod AS mod_id_file,
    listing_id_mod AS mod_id_listing,
    lead_id_mod AS mod_id_lead,
    lead_uuid_mod AS mod_uuid_lead,
    real_estate_id_mod AS mod_id_real_estate,
    id_by_real_estate_mod AS mod_id_by_real_estate,
    status_mod AS mod_status,
    brokers_mod AS mod_brokers,
    location_mod AS mod_location,
    pricing_mod AS mod_pricing,
    owner_mod AS mod_owner,
    blueprint_mod AS mod_blueprint,
    details_mod AS mod_details,
    access_mod AS mod_access,
    administrators_mod AS mod_administrators,
    photos_mod AS mod_photos,
    lead_hash_mod AS mod_lead_hash,
    status_reason_mod AS mod_status_reason,
    cnpj_mod AS mod_cnpj,
    sent_to_main_mod AS mod_is_sent_to_main,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_brokers_supply_processor_raw.lead3p_aud