SELECT
    city_group,
    first_listings,
    lead_context,
    opportunities,
    prospects,
    qualifieds,
    supply_channel,
    supply_origin,
    tier,
    halfyear,
    quarter,
    month,
    year,
    dt_week_started,
    dt_target
FROM
    datalake_gsheets_clean.supply_targets_2019
UNION ALL
SELECT
    city_group,
    first_listings,
    lead_context,
    opportunities,
    prospects,
    qualifieds,
    supply_channel,
    supply_origin,
    tier,
    halfyear,
    quarter,
    month,
    year,
    dt_week_started,
    dt_target
FROM
    datalake_gsheets_clean.supply_targets_2020
UNION ALL
SELECT
    city_group,
    first_listings,
    lead_context,
    opportunities,
    prospects,
    qualifieds,
    supply_channel,
    supply_origin,
    tier,
    halfyear,
    quarter,
    month,
    year,
    dt_week_started,
    dt_target
FROM
    datalake_gsheets_clean.supply_targets_2021
