SELECT
    id_ticket AS sk_ticket,
    id_main_ticket AS sk_main_ticket,
    id_group AS sk_group,
    id_assignee AS sk_assignee ,
    id_requester AS sk_requester,
    id_submitter AS sk_submitter,
    id_delinquency AS sk_delinquency,
    request_error,
    request_type,
    short_request_type,
    cancellation_reason,
    rejection_reason,
    broker_name,
    contact_reason,
    tenant_name,
    client_request,
    request_responsible,
    request_channel,
    exception_type,
    payment_period,
    name AS group_name,
    satisfaction_rating,
    satisfaction_reason,
    satisfaction_comments,
    smiley_scale,
    priority,
    recipient,
    ticket_via,
    ticket_type,
    description,
    ticket_url,
    tags,
    ticket_status,
    subject,
    ticket_order,
    has_incidents,
    is_public,
    is_last_register,
    has_payment_forwarded,
    dt_extracted,
    dt_request,
    ts_created,
    ts_created_local,
    ts_updated,
    ts_updated_local,
    ts_load
 FROM
    datalake_velo_zendesk.ticket_details
