SELECT
    id_ticket AS sk_ticket,
    id_assignee AS sk_assignee,
    id_group AS sk_group,
    id_requester AS sk_requester,
    id_submitter AS sk_submitter,
    id_propose AS sk_propose,
    request_type,
    ticket_via,
    status,
    group_stations,
    assignee_stations,
    waiting_period_creation,
    waiting_period_resolution,
    minutes_reply_calendar,
    minutes_reply_business,
    minutes_first_resolution_business,
    minutes_first_resolution_calendar,
    minutes_requester_wait_business,
    minutes_requester_wait_calendar,
    minutes_agent_wait_business,
    minutes_agent_wait_calendar,
    minutes_on_hold_business,
    minutes_on_hold_calendar,
    minutes_full_resolution_business,
    minutes_full_resolution_calendar,
    reopens,
    replies,
    overdue_amount,
    leadtime_calendar_days,
    leadtime_business_days,
    interval_first_response,
    first_day_of_month,
    broker_waiting_analyst,
    analyst_waiting_broker,
    ticket_order,
    has_payment_forwarded,
    dt_extracted,
    dt_request_return,
    dt_submission,
    dt_due_original,
    dt_started,
    dt_payment_scheduled,
    dt_payment_forwarded,
    ts_created,
    ts_created_local,
    ts_updated,
    ts_updated_local,
    ts_initially_assigned,
    ts_initially_assigned_local,
    ts_assigned,
    ts_solved,
    ts_solved_local,
    ts_load
FROM
    datalake_velo_zendesk.ticket_metrics
