SELECT
    id_house,
    NULLIF(LAST(has_bathtub, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_bathtub,
    NULLIF(LAST(has_shower_enclosure, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_shower_enclosure,
    NULLIF(LAST(has_balcony, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_balcony,
    NULLIF(LAST(has_stove_and_refrigerator, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_stove_and_refrigerator,
    NULLIF(LAST(has_private_pool, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_private_pool,
    NULLIF(LAST(has_bedroom_closets, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_bedroom_closets,
    NULLIF(LAST(has_bathroom_cabinets, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_bathroom_cabinets,
    NULLIF(LAST(has_kitchen_cabinets, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_kitchen_cabinets,
    NULLIF(LAST(has_air_conditioning, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_air_conditioning,
    NULLIF(LAST(has_gas_shower, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_gas_shower,
    NULLIF(LAST(has_pets_allowed, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_pets_allowed,
    NULLIF(LAST(has_maid_room, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_maid_room,
    NULLIF(LAST(has_maid_bathroom, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_maid_bathroom,
    NULLIF(LAST(has_assigned_parking_space, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_assigned_parking_space,
    NULLIF(LAST(has_gourmet_balcony, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_gourmet_balcony,
    NULLIF(LAST(is_penthouse_apartment, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS is_penthouse_apartment,
    NULLIF(LAST(has_reversible_extra_room, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_reversible_extra_room,
    NULLIF(LAST(has_stove, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_stove,
    NULLIF(LAST(has_refrigerator, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_refrigerator,
    NULLIF(LAST(has_morning_sun, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_morning_sun,
    NULLIF(LAST(has_afternoon_sun, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_afternoon_sun,
    NULLIF(LAST(has_blackout_curtains, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_blackout_curtains,
    NULLIF(LAST(has_sheer_curtain, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_sheer_curtain,
    NULLIF(LAST(has_soundproof_window, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_soundproof_window,
    NULLIF(LAST(has_ceiling_fan, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_ceiling_fan,
    NULLIF(LAST(has_large_windows, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_large_windows,
    NULLIF(LAST(has_unobstructed_view, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_unobstructed_view,
    NULLIF(LAST(has_quiet_street, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_quiet_street,
    NULLIF(LAST(has_electric_shower, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_electric_shower,
    NULLIF(LAST(has_microwave, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_microwave,
    NULLIF(LAST(has_sofa, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_sofa,
    NULLIF(LAST(has_washing_machine, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_washing_machine,
    NULLIF(LAST(has_dryer, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_dryer,
    NULLIF(LAST(has_washer_dryer_combo, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_washer_dryer_combo,
    NULLIF(LAST(has_laundry_sink, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_laundry_sink,
    NULLIF(LAST(has_window_screens, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_window_screens,
    NULLIF(LAST(has_clothesline, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_clothesline,
    NULLIF(LAST(has_three_pin_outlets, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_three_pin_outlets,
    NULLIF(LAST(has_television, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_television,
    NULLIF(LAST(has_dining_tables_and_chairs, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_dining_tables_and_chairs,
    NULLIF(LAST(has_coffee_maker, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_coffee_maker,
    NULLIF(LAST(has_barbecue, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_barbecue,
    NULLIF(LAST(has_step_free_access, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_step_free_access,
    NULLIF(LAST(has_cooktop, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_cooktop,
    NULLIF(LAST(has_kitchen_utensils, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_kitchen_utensils,
    NULLIF(LAST(has_double_bed, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_double_bed,
    NULLIF(LAST(has_single_bed, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_single_bed,
    NULLIF(LAST(has_bathroom_mirror, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_bathroom_mirror,
    NULLIF(LAST(has_electronic_lock, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_electronic_lock,
    NULLIF(LAST(has_electricity_included, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_electricity_included,
    NULLIF(LAST(has_adapted_bathroom, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_adapted_bathroom,
    NULLIF(LAST(has_walk_in_closet, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_walk_in_closet,
    NULLIF(LAST(has_open_kitchen, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_open_kitchen,
    NULLIF(LAST(has_office_tables_and_chairs, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_office_tables_and_chairs,
    NULLIF(LAST(has_garden, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_garden,
    NULLIF(LAST(has_spacious_rooms_and_corridors_doors, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_spacious_rooms_and_corridors_doors,
    NULLIF(LAST(has_backyard, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_backyard,
    NULLIF(LAST(has_single_house_on_the_property, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_single_house_on_the_property,
    NULLIF(LAST(has_laundry_area, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_laundry_area,
    NULLIF(LAST(has_private_garden_area, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_private_garden_area,
    NULLIF(LAST(has_elevator, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_elevator,
    NULLIF(LAST(has_playground, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_playground,
    NULLIF(LAST(has_condo_pool, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_condo_pool,
    NULLIF(LAST(has_condo_grill_area, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_condo_grill_area,
    NULLIF(LAST(has_sports_court, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_sports_court,
    NULLIF(LAST(has_gym, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_gym,
    NULLIF(LAST(has_party_hall, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_party_hall,
    NULLIF(LAST(has_sauna, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_sauna,
    NULLIF(LAST(has_condo_laundry, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_condo_laundry,
    NULLIF(LAST(has_piped_gas, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_piped_gas,
    NULLIF(LAST(has_automatic_gate, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_automatic_gate,
    NULLIF(LAST(has_gourmet_area, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_gourmet_area,
    NULLIF(LAST(is_near_metro_or_train, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS is_near_metro_or_train,
    NULLIF(LAST(has_playroom, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_playroom,
    NULLIF(LAST(has_handrail, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_handrail,
    NULLIF(LAST(has_tactile_floor, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_tactile_floor,
    NULLIF(LAST(has_access_ramps, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_access_ramps,
    NULLIF(LAST(has_game_room, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_game_room,
    NULLIF(LAST(has_accessible_parking_space, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_accessible_parking_space,
    NULLIF(LAST(has_green_area, TRUE) OVER(PARTITION BY id_house ORDER BY ts_change), 'NULL')::BOOLEAN AS has_green_area,
    ROW_NUMBER() OVER(PARTITION BY id_house, DATE(ts_change) ORDER BY ts_change DESC) = 1 AS is_last_status_of_day,
    ROW_NUMBER() OVER(PARTITION BY id_house ORDER BY ts_change DESC) = 1 AS is_current_version,
    ROW_NUMBER() OVER(PARTITION BY id_house ORDER BY ts_change) AS version,
    ts_change AS ts_version_started,
    LEAD(ts_change) OVER(PARTITION BY id_house ORDER BY ts_change) AS ts_version_ended
FROM (
    SELECT
        id_house,
        id_amenity,
        is_condo_amenity,
        COALESCE(CAST(has_feature AS STRING), 'NULL') AS has_feature,
        ts_change
    FROM
        datalake_ebdb_amenities.amenity_change_history AS ah
)
PIVOT(
    MAX(has_feature)
    FOR (id_amenity, is_condo_amenity) IN (
        -- House amenities
        (1, FALSE) AS has_bathtub,
        (2, FALSE) AS has_shower_enclosure,
        (3, FALSE) AS has_balcony,
        (4, FALSE) AS has_stove_and_refrigerator,
        (5, FALSE) AS has_private_pool,
        (7, FALSE) AS has_bedroom_closets,
        (8, FALSE) AS has_bathroom_cabinets,
        (9, FALSE) AS has_kitchen_cabinets,
        (10, FALSE) AS has_air_conditioning,
        (12, FALSE) AS has_gas_shower,
        (13, FALSE) AS has_pets_allowed,
        (14, FALSE) AS has_maid_room,
        (15, FALSE) AS has_maid_bathroom,
        (16, FALSE) AS has_assigned_parking_space,
        (17, FALSE) AS has_gourmet_balcony,
        (18, FALSE) AS is_penthouse_apartment,
        (19, FALSE) AS has_reversible_extra_room,
        (20, FALSE) AS has_stove,
        (21, FALSE) AS has_refrigerator,
        (22, FALSE) AS has_morning_sun,
        (23, FALSE) AS has_afternoon_sun,
        (24, FALSE) AS has_blackout_curtains,
        (25, FALSE) AS has_sheer_curtain,
        (26, FALSE) AS has_soundproof_window,
        (27, FALSE) AS has_ceiling_fan,
        (28, FALSE) AS has_large_windows,
        (29, FALSE) AS has_unobstructed_view,
        (30, FALSE) AS has_quiet_street,
        (31, FALSE) AS has_electric_shower,
        (32, FALSE) AS has_microwave,
        (33, FALSE) AS has_sofa,
        (34, FALSE) AS has_washing_machine,
        (35, FALSE) AS has_dryer,
        (36, FALSE) AS has_washer_dryer_combo,
        (37, FALSE) AS has_laundry_sink,
        (38, FALSE) AS has_window_screens,
        (39, FALSE) AS has_clothesline,
        (40, FALSE) AS has_three_pin_outlets,
        (41, FALSE) AS has_television,
        (42, FALSE) AS has_dining_tables_and_chairs,
        (43, FALSE) AS has_coffee_maker,
        (44, FALSE) AS has_barbecue,
        (45, FALSE) AS has_step_free_access,
        (46, FALSE) AS has_cooktop,
        (47, FALSE) AS has_kitchen_utensils,
        (48, FALSE) AS has_double_bed,
        (49, FALSE) AS has_single_bed,
        (50, FALSE) AS has_bathroom_mirror,
        (51, FALSE) AS has_electronic_lock,
        (52, FALSE) AS has_electricity_included,
        (53, FALSE) AS has_adapted_bathroom,
        (54, FALSE) AS has_walk_in_closet,
        (55, FALSE) AS has_open_kitchen,
        (56, FALSE) AS has_office_tables_and_chairs,
        (57, FALSE) AS has_garden,
        (58, FALSE) AS has_spacious_rooms_and_corridors_doors,
        (59, FALSE) AS has_backyard,
        (60, FALSE) AS has_single_house_on_the_property,
        (61, FALSE) AS has_laundry_area,
        (62, FALSE) AS has_private_garden_area,
        -- Condo amenities
        (0, TRUE) AS has_elevator,
        (1, TRUE) AS has_playground,
        (2, TRUE) AS has_condo_pool,
        (3, TRUE) AS has_condo_grill_area,
        (4, TRUE) AS has_sports_court,
        (5, TRUE) AS has_gym,
        (6, TRUE) AS has_party_hall,
        (7, TRUE) AS has_sauna,
        (8, TRUE) AS has_condo_laundry,
        (9, TRUE) AS has_piped_gas,
        (10, TRUE) AS has_automatic_gate,
        (11, TRUE) AS has_gourmet_area,
        (12, TRUE) AS is_near_metro_or_train,
        (13, TRUE) AS has_playroom,
        (14, TRUE) AS has_handrail,
        (15, TRUE) AS has_tactile_floor,
        (16, TRUE) AS has_access_ramps,
        (17, TRUE) AS has_game_room,
        (18, TRUE) AS has_accessible_parking_space,
        (19, TRUE) AS has_green_area
    )
)