SELECT
  sk_ra_ticket,
  ra_status,
  hugme_status,
  source,
  title,
  company,
  customer_cpf,
  customer_city,
  customer_state,
  customer_email,
  customer_phone_numbers,
  customer_tags,
  moderation_status,
  moderation_reason,
  total_moderations,
  rating,
  total_ratings_without_response,
  is_resolved,
  is_internal_process,
  would_do_business_again,
  ts_created,
  ts_last_replica,
  ts_complaint_response,
  ts_rating,
  ts_last_modification,
  ts_load,
  year,
  month,
  day
FROM (
  SELECT
    CAST(id AS BIGINT) AS sk_ra_ticket,
    ra_status['name'] AS ra_status,
    hugme_status['name'] AS hugme_status,
    source['name'] AS source,
    complaint_title AS title,
    company.name AS company,
    GET_JSON_OBJECT(customer_data, '$.cpf') AS customer_cpf,
    REPLACE(GET_JSON_OBJECT(customer_data, '$.city'), 'name:') AS customer_city,
    REPLACE(GET_JSON_OBJECT(customer_data, '$.state'), 'name:') AS customer_state,
    GET_JSON_OBJECT(customer_data, '$.email') AS customer_email,
    GET_JSON_OBJECT(customer_data, '$.phone_numbers') AS customer_phone_numbers,
    GET_JSON_OBJECT(customer_data, '$.tags') AS customer_tags,
    moderation['status'] AS moderation_status,
    moderation['reason'] AS moderation_reason,
    ticket_moderations_count AS total_moderations,
    CASE WHEN rating = -1 THEN NULL ELSE rating END AS rating,
    rating_without_response AS total_ratings_without_response,
    is_resolved_issue AS is_resolved,
    ra['internal_process'] AS is_internal_process,
    would_do_business_again,
    ts_created,
    ts_last_replica,
    ts_complaint_response,
    ts_rating,
    ts_last_modification,
    NOW() AS ts_load,
    year,
    month,
    day,
    ROW_NUMBER() OVER (PARTITION BY id ORDER BY ts_last_modification DESC) AS _w,
    id
  FROM datalake_reclameaqui_clean.tickets
  WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
) AS _t
WHERE
  _w = 1
