SELECT
  id_ticket,
  id_deal,
  id_company,
  id_stage,
  id_pipeline,
  id_hubspot_owner,
  id_stage_history,
  id_pipeline_history,
  content,
  subject,
  onboarding_type,
  field_sales,
  has_accepted_contact_with_agents,
  is_archived,
  dt_term_signed,
  dt_term_sent,
  dt_documents_received,
  dt_onboarding,
  ts_live_demand_only,
  ts_archived,
  ts_created,
  ts_updated,
  year,
  month,
  day
FROM (
  SELECT
    id_ticket,
    id_deal,
    id_company,
    id_stage,
    id_pipeline,
    id_hubspot_owner,
    id_stage_history,
    id_pipeline_history,
    content,
    subject,
    onboarding_type,
    field_sales,
    has_accepted_contact_with_agents,
    is_archived,
    dt_term_signed,
    dt_term_sent,
    dt_documents_received,
    dt_onboarding,
    ts_live_demand_only,
    ts_archived,
    ts_created,
    ts_updated,
    year,
    month,
    day,
    ROW_NUMBER() OVER (PARTITION BY id_ticket ORDER BY ts_updated DESC) AS _w
  FROM datalake_hubspot.ticket_history
) AS _t
WHERE
  _w = 1