DROP TABLE IF exists dim_booking;
CREATE TABLE dim_booking (
  sk_booking INTEGER,
  id_booking INTEGER,
  -- id_booking_original integer,
  valid_bookings_not_rescheduled boolean,
  dt_scheduling TIMESTAMP,
  type VARCHAR(50),
  confirmed VARCHAR(100),
  closed VARCHAR(100),
  visit_follow_up VARCHAR(100),
  dt_visit_follow_up TIMESTAMP,
  rescheduled_from_id INTEGER,
  id_visitor BIGINT,
  id_visit BIGINT,
  id_property BIGINT,
  id_agent BIGINT,
  id_attendant BIGINT,
  id_rental_flow bigint,
  status varchar(50),
  slot_dia INTEGER,
  reason VARCHAR(255),
  reason_category VARCHAR(255),
  responsible VARCHAR(255),
  app_type VARCHAR(255),
  media_source VARCHAR(255),
  adjust_network VARCHAR(255),
  utm_source VARCHAR(255),
  utm_medium VARCHAR(255),
  utm_campaign VARCHAR(255),
  dt_cancel TIMESTAMP WITHOUT TIME ZONE,
  dt_created TIMESTAMP WITHOUT TIME ZONE,
  dt_updated TIMESTAMP WITHOUT TIME ZONE,
  dt_timestamp TIMESTAMP WITHOUT TIME ZONE,
  last_update_source VARCHAR(255),
  first_update_source VARCHAR(255),
  visitor_arrived varchar(255),
  visitor_missing_reason varchar(255),
  agent_arrived varchar(255),
  agent_missing_reason varchar(255),
  owner_arrived varchar(255),
  owner_missing_reason varchar(255),
  successful_entrance varchar(255),
  troublesome_entrance varchar(255),
  CONSTRAINT dim_booking_pkey PRIMARY KEY(sk_booking)
);