drop table if exists fact_demand;
create table fact_demand (
  ods_id bigint,
	sk_house bigint,
	sk_house_first_listing_date integer,
	sk_house_listing_date integer,
	sk_house_de_publication_date integer,
	sk_house_first_offer_submitted_date integer,
	sk_region integer,
	sk_rent_flow integer,
	sk_booking integer,
	sk_booking_created_date integer,
	sk_visit_date integer,
	sk_owner integer,
	sk_user_agent integer,
	sk_agent_sign_up_date integer,
	sk_client integer,
	sk_client_sign_up_date integer,
	sk_visit integer,
	sk_negotiation integer,
	sk_offer integer,
	sk_offer_submitted_date integer,
	sk_offer_approved_date integer,
	sk_proposal integer,
	sk_proposal_approved_date integer,
	sk_tenant_first_document_sent_date integer,
	sk_contract integer,
	sk_contract_created_date integer,
	sk_contract_signed_date integer,
	sk_contract_annulment_date integer,
	sk_credit_analysis_init_date integer,
	sk_credit_analysis_end_date integer,
	sk_credit_analysis_approved_date integer,
	visit_created_from_app integer,
	visit_created_type varchar(14),
	visit_last_updated_from_app integer,
	visit_last_updated_type varchar(14),
  booking_to_visit numeric(14,4),
  offer_to_internal_analyis numeric(14,4),
  offer_to_credit_analysis_init_date numeric(14,4),
  credit_analysis_init_to_end numeric(14,4),
  proposal_approved_to_contract_signed numeric(14,4),
  dt_timestamp timestamp without time zone
) with oids
;