SELECT
  w.id_person,
  wr.PeriodOfServiceId AS id_period_of_service,
  wr.LegalEntityId AS id_legal_entity,
  wr.RecommendationAuthorizedByPersonId AS id_authorized_recommendation_person,
  a.AssignmentId AS id_assignment,
  a.PositionId AS id_position,
  a.BusinessUnitId AS id_business_unit,
  a.ProposedUserPersonTypeId AS id_proposed_user_person_type,
  a.UserPersonTypeId AS id_user_person_type,
  a.AssignmentStatusTypeId AS id_assignment_status_type,
  a.JobId AS id_job,
  a.GradeId AS id_grade,
  a.GradeLadderId AS id_grade_ladder,
  a.UnionId AS id_union,
  a.DepartmentId AS id_department,
  m.ManagerAssignmentId AS id_manager_assignment,
  wr.LegislationCode AS legislation_code,
  wr.LegislationName AS legislation_name,
  wr.LegalEmployerName AS legal_employer_name,
  wr.WorkerType AS worker_type,
  wr.WorkerTypeMeaning AS worker_type_meaning,
  wr.RevokeUserAccess AS revoke_user_access,
  wr.RecommendedForRehire AS recommended_for_rehire,
  wr.RecommendedForRehireMeaning AS recommended_for_rehire_meaning,
  wr.RecommendationReason AS recommendation_reason,
  wr.CreatedBy AS work_relationship_created_by,
  wr.LastUpdatedBy AS work_relationship_updated_by,
  a.AssignmentName AS assignment_name,
  a.ActionCode AS action_code,
  a.ReasonCode AS reason_code,
  a.BusinessUnitName AS business_unit_name,
  a.AssignmentType AS assignment_type,
  a.AssignmentStatusTypeCode AS assignment_status_type_code,
  a.AssignmentStatusType AS assignment_status_type,
  a.SystemPersonType AS system_person_type,
  a.UserPersonType AS user_person_type,
  a.ProposedUserPersonType AS proposed_user_person_type,
  a.PositionCode AS position_code,
  a.PositionName AS position_name,
  a.JobCode AS job_code,
  a.GradeCode AS grade_code,
  a.GradeLadderName AS grade_ladder_name,
  a.DepartmentName AS department_name,
  a.AssignmentCategory AS assignment_category,
  a.WorkerCategory AS worker_category,
  a.PermanentTemporary AS contract_type,
  a.HourlySalariedCode AS hourly_or_salaried,
  a.Frequency AS payment_frequency,
  a.SeniorityBasis AS seniority_basis,
  a.ProbationPeriodUnit AS probation_period_unit,
  a.NoticePeriodUOM AS notice_period_unit,
  a.UnionName AS union_name,
  a.InternalBuilding AS internal_building,
  a.InternalFloor AS internal_floor,
  a.InternalOfficeNumber AS internal_office_number,
  a.CreatedBy AS assignment_created_by,
  a.LastUpdatedBy AS assignment_updated_by,
  adff.vinculoEmpregaticio AS employment_bond,
  adff.marcaProduto AS brand,
  adff.trilha AS career_path,
  adff.processoRegimeDeContratacao AS hiring_process_code,
  adff.seguradora AS insurance_company,
  adff.tipoDeContrato AS contract_type_meaning,
  addf.__FLEX_Context AS additional_context,
  aeff.CategoryCode AS extended_category_code,
  aeff.AssignmentType AS extended_assignment_type,
  m.ManagerAssignmentNumber AS manager_assignment_number,
  m.ManagerType AS manager_type,
  m.ActionCode AS manager_action_code,
  m.ReasonCode AS manager_reason_code,
  wrddf._HIRING_TYPE_Display AS hiring_type_display,
  wrddf._HIRING_INDICATOR_Display AS hiring_indicator_display,
  wrdff.recrutador AS recruiter,
  wrdff.areaDeAtuacaoDoEstagiario AS intern_field_of_activity,
  wrdff.instituicaoDeEnsino AS educational_institution,
  m.CreatedBy AS manager_created_by,
  m.LastUpdatedBy AS manager_updated_by,
  w.person_number,
  wr.WorkerNumber AS worker_number,
  a.AssignmentNumber AS assignment_number,
  a.RetirementAge AS retirement_age,
  a.EffectiveSequence AS assignment_sequence,
  a.NormalHours AS normal_hours,
  a.ProbationPeriod AS probation_period,
  a.NoticePeriod AS notice_period,
  adff.targetPlr AS target_profit_sharing,
  adff.targetRvv AS target_rvv,
  adff.cargaHoraria AS work_hours_load,
  wrdff.mesesDeDuracaoDeEstagio AS internship_duration_months,
  adff.ApoliceSeguro AS insurance_policy,
  wr.PrimaryFlag = 'Y' AS is_primary_work_relationship,
  wr.OnMilitaryServiceFlag = 'Y' AS is_on_military_service,
  wr.ReadyToConvertFlag = 'Y' AS is_ready_to_convert,
  a.EffectiveLatestChange = 'Y' AS is_latest_change,
  a.PrimaryFlag = 'Y' AS is_primary,
  a.PrimaryAssignmentFlag = 'Y' AS is_primary_assignment,
  a.WorkAtHomeFlag = 'Y' AS is_working_from_home,
  a.GradeStepEligibilityFlag = 'Y' AS is_grade_step_eligible,
  a.LabourUnionMemberFlag = 'Y' AS is_union_member,
  a.SynchronizeFromPositionFlag = 'Y' AS is_synchronized_from_position,
  a.ManagerFlag = 'Y' AS is_manager,
  adff.funcionarioMarcaPonto = 'Y' AS is_clock_in_required,
  adff.compensaSabado = 'Y' AS is_saturday_compensated,
  wrddf._FIRST_EMPLOYMENT = 'Y' AS is_first_employment,
  IF(w.dt_effective > REPLACE('{load_start_date}', '-', ''), TRUE, FALSE) AS is_future_info,
  IF(w.dt_effective = REPLACE('{load_start_date}', '-', ''), TRUE, FALSE) AS is_current_info,
  IF(w.dt_effective < REPLACE('{load_start_date}', '-', ''), TRUE, FALSE) AS is_past_info,
  TO_DATE(CAST(w.dt_effective AS string), 'yyyyMMdd') AS dt_effective
  wr.StartDate AS dt_work_relationship_started,
  wr.LegalEmployerSeniorityDate AS dt_legal_seniority,
  wr.EnterpriseSeniorityDate AS dt_enterprise_seniority,
  wr.TerminationDate AS dt_terminated,
  wr.NotificationDate AS dt_notification,
  wr.LastWorkingDate AS dt_last_worked,
  wr.ProjectedTerminationDate AS dt_projected_termination,
  a.EffectiveStartDate AS dt_assignment_started,
  a.EffectiveEndDate AS dt_assignment_ended,
  a.ProjectedStartDate AS dt_projected_start,
  a.ProjectedEndDate AS dt_projected_end,
  a.ProbationEndDate AS dt_probation_ended,
  a.RetirementDate AS dt_retirement,
  adff.dataFinalDaExperiencia1 AS dt_experience_end_1,
  adff.dataFinalDaExperiencia2 AS dt_experience_end_2,
  wrdff.dataPrevistaParaTerminoDoEstag AS dt_expected_internship_end,
  addf.EffectiveStartDate AS dt_additional_started,
  addf.EffectiveEndDate AS dt_additional_ended,
  aeff.EffectiveStartDate AS dt_extended_started,
  aeff.EffectiveEndDate AS dt_extended_ended,
  m.EffectiveStartDate AS dt_manager_started,
  m.EffectiveEndDate AS dt_manager_ended,
  wr.CreationDate AS ts_work_relationship_created,
  wr.LastUpdateDate AS ts_work_relationship_updated,
  a.CreationDate AS ts_assignment_created,
  a.LastUpdateDate AS ts_assignment_updated,
  m.CreationDate AS ts_manager_created,
  m.LastUpdateDate AS ts_manager_updated,
  NOW() AS ts_load
FROM
  datalake_hr_system_clean.workers AS w
LATERAL VIEW OUTER
  EXPLODE(w.work_relationships) AS wr
LATERAL VIEW OUTER
  EXPLODE(wr.assignments) AS a
LATERAL VIEW OUTER
  EXPLODE(a.assignmentsDFF) AS adff
LATERAL VIEW OUTER
  EXPLODE(a.assignmentsDDF) AS addf
LATERAL VIEW OUTER
  EXPLODE(a.assignmentsEFF) AS aeff
LATERAL VIEW OUTER
  EXPLODE(a.managers) AS m
LATERAL VIEW OUTER
  EXPLODE(wr.workRelationshipsDDF) AS wrddf
LATERAL VIEW OUTER
  EXPLODE(wr.workRelationshipsDFF) AS wrdff
