SELECT
    uuid AS id_request_subtype,
    companyUuid AS id_company,
    requestTypeUuid AS id_request_type,
    requestSubtypeTemplateUuid AS id_request_subtype_template,
    externalId AS id_external,
    createdBy AS id_created_by_user,
    updatedBy AS id_updated_by_user,
    requestType AS request_type,
    name AS subtype_name,
    nameId AS subtype_name_key,
    translationKey AS translation_key,
    hoursCalculationType AS hours_calculation_type,
    approvalFlow AS approval_flow,
    attachment AS attachment_policy,
    comment AS comment_policy,
    active AS is_active,
    paid AS is_paid_subtype,
    discountDsr AS is_discount_dsr,
    createdAt AS ts_created,
    updatedAt AS ts_updated,
    deletedAt AS ts_deleted,
    complianceRules AS compliance_rules,
    customFields AS custom_fields,
    subtypeSpecificFields AS subtype_specific_fields,
    visibilityPermissionRoles AS visibility_permission_roles,
    ts_load,
    year,
    month,
    day
FROM
    datalake_oitchau_raw.requests_types_subtypes
