SELECT
    uuid AS id_request,
    userProfileUuid AS id_employee_profile,
    companyUuid AS id_company,
    requestTypeUuid AS id_request_type,
    requestSubtypeUuid AS id_request_subtype,
    createdBy AS id_created_by_user,
    externalId AS id_external,
    approvalStatus AS approval_status,
    approvalStage AS approval_stage,
    approvalFlow AS approval_flow,
    requestType AS request_type,
    requestSubtypeState AS request_subtype_state,
    hoursCalculationType AS hours_calculation_type,
    externalSource AS external_source,
    validity AS validity_value,
    validityType AS validity_type,
    version AS record_version,
    timezone AS timezone_name,
    `comment` AS request_comment,
    allDay AS is_all_day,
    paid AS is_paid_request,
    locked AS is_locked,
    isEndless AS is_endless,
    isNightShift AS is_night_shift,
    upToDate AS is_up_to_date,
    startTime AS ts_interval_started,
    endTime AS ts_interval_ended,
    createdAt AS ts_created,
    updatedAt AS ts_updated,
    updatedByUserAt AS ts_updated_by_user,
    deletedAt AS ts_deleted,
    syncedAt AS ts_synced,
    ts_load,
    customFields AS custom_fields,
    attachments AS attachments,
    logs AS request_logs,
    subtypeSpecificFields AS subtype_specific_fields,
    year,
    month,
    day
FROM
    datalake_oitchau_raw.requests
