SELECT
 m.id_offer,
 fo.id_buyer,
 fo.id_owner,
 fo.id_house,
 m.id_closing_specialist,
 m.id_pre_specialist,
 m.id_post_specialist,
 m.id_start_financing_specialist,
 m.id_follow_up_financing_specialist,
 m.id_end_financing_specialist,
 m.id_credit_specialist,
 m.id_notes_registry_specialist,
 m.id_real_estate_register_specialist,
 DATEDIFF(dt_house_registry_started, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_house_registry_started,
 DATEDIFF(dt_house_registry_ended, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_house_registry_ended,
 DATEDIFF(dt_sale_agreement_cancelled, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_sale_agreement_cancelled,
 DATEDIFF(dt_credit_analysis_started, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_credit_analysis_started,
 DATEDIFF(dt_credit_analysis_ended, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_credit_analysis_ended,
 DATEDIFF(dt_financing_started, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_financing_started,
 DATEDIFF(dt_notes_registry_started, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_notes_registry_started,
 DATEDIFF(dt_notes_registry_ended, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_notes_registry_ended,
 DATEDIFF(dt_legaut_analysis_started, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_legaut_analysis_started,
 DATEDIFF(dt_legaut_analysis_ended, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_legaut_analysis_ended,
 DATEDIFF(dt_legal_risk_ended, dt_sale_agreement_signed) AS days_sale_agreement_signed_to_legal_risk_ended,
 DATEDIFF(dt_legal_risk_ended, dt_legal_risk_started) AS days_legal_risk_started_to_legal_risk_ended,
 DATEDIFF(dt_legaut_analysis_ended, dt_legaut_analysis_started) AS days_legaut_analysis_started_to_legaut_analysis_ended,
 DATEDIFF(dt_credit_analysis_ended, dt_credit_analysis_started) AS days_credit_analysis_started_to_credit_analysis_ended,
 DATEDIFF(dt_financing_ended, dt_financing_started) AS days_financing_started_to_financing_ended,
 DATEDIFF(dt_house_registry_ended, dt_financing_ended) AS days_financing_ended_to_house_registry_ended,
 DATEDIFF(dt_house_registry_started, dt_financing_ended) AS days_financing_ended_to_house_registry_started,
 DATEDIFF(dt_notes_registry_ended, dt_notes_registry_started) AS days_notes_registry_started_to_notes_registry_ended,
 DATEDIFF(dt_house_registry_ended, dt_house_registry_started) AS days_house_registry_started_to_house_registry_ended,
 DATEDIFF(dt_house_registry_started, dt_notes_registry_ended) AS days_notes_registry_ended_to_house_registry_started,
 DATEDIFF(dt_house_registry_ended, dt_notes_registry_ended) AS days_notes_registry_ended_to_house_registry_ended,
 DATEDIFF(dt_sale_key_delivered, dt_house_registry_ended) AS days_house_registry_ended_to_sale_key_delivered,
 DATEDIFF(dt_sale_transacton_paid, dt_house_registry_ended) AS days_house_registry_ended_to_sale_transaction_paid,
 m.dt_sale_agreement_signed,
 m.dt_sale_agreement_cancelled,
 m.dt_onboarding_ended,
 m.dt_legal_analysis_ended,
 m.dt_legaut_analysis_started,
 m.dt_legaut_analysis_ended,
 m.dt_legal_risk_started,
 m.dt_legal_risk_ended,
 m.dt_credit_analysis_started,
 m.dt_credit_analysis_ended,
 m.dt_financing_started,
 m.dt_financing_ended,
 m.dt_notes_registry_started,
 m.dt_notes_registry_ended,
 m.dt_house_registry_started,
 m.dt_house_registry_ended,
 m.dt_sale_key_delivered,
 m.dt_sale_transacton_paid,
 m.ts_updated,
 m.ts_load
FROM
   datalake_firestore.monday AS m
LEFT JOIN
   datalake_firestore.sale_offer AS fo
      ON fo.id = m.id_offer
WHERE
   dt_sale_agreement_signed IS NOT NULL
   AND (m.negotiation_model = 'DM' OR m.negotiation_model IS NULL)