SELECT
	CAST(id AS BIGINT) AS id,
	CAST(COALESCE(userid, user_id) AS BIGINT) AS id_user,
	CAST(eventId AS BIGINT) AS id_event,
	COALESCE(referenceId, entity_id) AS id_entity,
	CAST(campaign_id AS BIGINT) AS id_campaign,
	COALESCE(referenceName, entity_name) AS entity_name,
	action,
	status,
	channel,
	profile,
	tags,
	destination,
	payload,
	payload:bodyTemplate AS template,
	payload:country AS country_code,
	payload:metadata AS metadata,
	ccost AS cost_center,
	scope,
	notificationCenterAcknowledge AS notification_center_acknowledge,
	CAST(COALESCE(sentAt, sent_at) AS TIMESTAMP) AS ts_sent,
	CAST(COALESCE(createdAt, created_at) AS TIMESTAMP) AS ts_created,
	CAST(COALESCE(updatedAt, updated_at) AS TIMESTAMP) AS ts_updated,
	year,
	month,
	day
FROM
	datalake_jaiminho_raw.user_notifications
