SELECT 
    INT(id) as id,
    condominio AS condo,
    cnpj,
    keyword,
    origem AS origin,
    data_construcao AS construction_year,
    cep AS zip_code,
    estado AS state,
    cidade AS city,
    bairro AS neighborhood,
    rua AS street,
    numero AS number,
    latitude AS lat,
    longitude AS lng,
    caracteristicas_condominio AS condo_features,
    possui_conta_corrente_ou_conta_pool AS account_type,
    possui_sindico_morador_ou_profissional AS type_syndic,
    administraco_propria_ou_terceirizada AS type_of_administration,
    funcionarios_terceirizados AS outsourced_employees,
    indice_inadimplencia AS non_payment_index,
    CAST(arrecadacao_mensal AS FLOAT) AS monthly_tax_revenues,
    quantidade_andares AS number_of_floors,
    quantidade_caixas_agua AS number_of_water_tanks,
    quantidade_funcionarios AS number_of_employees,
    quantidade_pavimentos_garagem AS number_of_garage_floors,
    quantidade_portoes_garagem AS number_of_garage_gates,
    CAST(quantidade_vagas_garagem AS FLOAT) AS number_of_garage_parking_slots,
    total_blocos AS total_blocks,
    total_elevadores AS total_elevators,
    total_portarias AS total_ordinances,
    total_unidades AS total_units,
    CAST(academia AS BOOLEAN) AS has_gym,
    CAST(areaGourmet AS BOOLEAN) AS has_gourmet_area,
    CAST(churrasqueira AS BOOLEAN) AS has_grill_area,
    CAST(elevador AS BOOLEAN) AS has_elevator,
    CAST(gas_encanado AS BOOLEAN) AS has_piped_gas,
    CAST(lavanderia AS BOOLEAN) AS has_laundry,
    CAST(piscina AS BOOLEAN) AS has_swim_pool,
    CAST(portaria AS BOOLEAN) AS has_entrance_hall,
    CAST(quadra_esportiva AS BOOLEAN) AS has_sports_court,
    CAST(salao_festa AS BOOLEAN) AS has_party_hall,
    realizam_reuso_agua AS has_water_reuse,
    CAST(sauna AS BOOLEAN) AS has_sauna,
    TIMESTAMP(date_updated) AS ts_updated,
    load_date
FROM
    datalake_sindico_net_raw.condominium