select distinct
    account_id,
	campaign_id,
	campaign_name,
	clicks,
	click_type,
	cost,
	date,
	device,
	impressions,
	account_name,
	hour_of_day,
	month,
	labels,
	week,
	year,
	acc,
	dt_created,
	absolute_top_impression_percentage,
	search_impression_share
from
    datalake_clean.marketing_google_campaigns