select distinct
    account_id,
	adgroup_id,
	adgroup_name,
	campaign_id,
	campaign_name,
	clicks,
	click_type,
	cost,
	date,
	device,
	keyword_id,
	impressions,
	match_type,
	labels,
	criteria,
	account_name,
	acc,
	dt_created,
	absolute_top_impression_percentage,
	search_impression_share
from
    datalake_clean.marketing_google_keywords