SELECT
    id,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    property_id AS id_property,
    proposal_external_id AS id_proposal_external,
    processed_events,
    proposal_status,
    contract_document_status,
    demand_document_status,
    supply_document_status,
    demand_contract_document_status,
    supply_contract_document_status,
    contract_deadline AS ts_contract_deadline,
    updated_at AS ts_updated,
    property_id_mod AS mod_id_property,
    proposal_external_id_mod AS mod_id_proposal_external,
    processed_events_mod AS mod_processed_events,
    proposal_status_mod AS mod_proposal_status,
    contract_document_status_mod AS mod_contract_document_status,
    demand_document_status_mod AS mod_demand_document_status,
    supply_document_status_mod AS mod_supply_document_status,
    demand_contract_document_status_mod AS mod_demand_contract_document_status,
    supply_contract_document_status_mod AS mod_supply_contract_document_status,
    contract_deadline_mod AS mod_ts_contract_deadline,
    year,
    month,
    day
FROM
    datalake_owner_properties_listing_raw.tb_accepted_rent_offer_aud
