SELECT
    id,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    owner_id AS id_owner,
    processed_events,
    rent_context,
    sale_context,
    visit,
    photo_job,
    address,
    cover_image,
    house_type,
    access_type,
    priority_listing_status_id AS id_priority_listing_status,
    priority_context,
    lead_id AS id_lead,
    main_property_id AS id_main_property,
    updated_at AS ts_updated,
    processed_events_mod AS mod_processed_events,
    owner_id_mod AS mod_id_owner,
    rent_context_mod AS mod_rent_context,
    sale_context_mod AS mod_sale_context,
    visit_mod AS mod_visit,
    photo_job_mod AS mod_photo_job,
    address_mod AS mod_address,
    cover_image_mod AS mod_cover_image,
    house_type_mod AS mod_house_type,
    access_type_mod AS mod_access_type,
    priority_listing_status_id_mod AS mod_id_priority_listing_status,
    priority_context_mod AS mod_priority_context,
    lead_id_mod AS mod_id_lead,
    main_property_id_mod AS mod_id_main_property,
    year,
    month,
    day
FROM
    datalake_owner_properties_listing_raw.tb_property_aud
