drop table if exists staging.dim_house_listing;
create table staging.dim_house_listing (
  sk_house_listing bigint not null,
  id_house bigint,
  short_id_house bigint,
  version smallint,
  status varchar,
  ts_listing_version_start timestamp,
  ts_listing_version_end timestamp,
  ts_house_registration_first_verification timestamp,
  ts_house_last_confirmation_availability timestamp,
  ts_house_first_publication timestamp,
  ts_house_last_publication timestamp,
  ts_publication timestamp,
  ts_de_publication timestamp,
  rent numeric(14,2),
  house_neighborhood varchar,
  house_zipcode varchar,
  house_city varchar,
  house_complement varchar,
  house_condo numeric(14,2),
  house_elevator smallint,
  house_address varchar,
  house_iptu numeric(14,2),
  house_lat numeric(14,7),
  house_lng numeric(14,7),
  is_house_furnished boolean,
  house_number varchar,
  house_bathrooms smallint,
  house_bedrooms smallint,
  house_suites smallint,
  house_garages smallint,
  house_status varchar,
  house_type varchar,
  house_entrance varchar,
  house_garage_type varchar,
  is_house_registration_verified boolean,
  house_total_value numeric(14,2),
  house_total_area numeric(14,2),
  house_construction_area numeric(14,2),
  house_condo_type varchar,
  house_iptu_type varchar,
  ts_house_create timestamp,
  ts_house_update timestamp,
  house_unpublished_reason varchar,
  listing_category_start varchar,
  listing_category_end varchar,
  is_last_version boolean,
  is_exclusive boolean,
  who_is_living varchar,
  key_type varchar,
  key_location varchar,
  has_visit_restriction boolean,
  ts_load timestamp
) with oids
;
