drop table if exists staging.dim_proposal;
create table if not exists staging.dim_proposal (
  sk_proposal integer,
  id_proposal integer,
  dt_proposal timestamp,
  guarantee varchar(50),
  renting_proposal_value double precision,
  status varchar(50),
  dt_proposal_approved timestamp,
  tenant_document_sent integer,
  dt_tenant_document_sent timestamp,
  owner_document_sent integer,
  dt_owner_document_sent timestamp without time zone,
  tenant_contract_accepted integer,
  owner_contract_accepted integer,
  status_doc_tenant varchar(50),
  status_doc_owner varchar(50),
  tenant_document_sent_count integer,
  dt_created timestamp,
  dt_updated timestamp,
  dt_timestamp timestamp without time zone,
  dt_tenant_first_document_sent timestamp,
  dt_tenant_auto_first_doc_sent timestamp,
  dt_credit_analysis_first_init timestamp,
  dt_credit_analysis_last_init timestamp,
  dt_credit_analysis_init timestamp,
  dt_credit_analysis_first_end timestamp,
  dt_credit_analysis_last_end timestamp,
  dt_credit_analysis_end timestamp,
  dt_credit_last_approved timestamp,
  dt_tenant_first_doc_complete timestamp,
  dt_tenant_last_doc_complete timestamp,
  dt_tenant_doc_complete timestamp,
  dt_first_credit_evaluation_init timestamp,
  dt_last_credit_evaluation_init timestamp,
  dt_first_credit_evaluation_positive timestamp,
  dt_last_credit_evaluation_positive timestamp,
  dt_first_credit_evaluation_negative timestamp,
  dt_last_credit_evaluation_negative timestamp,
  dt_guarantee timestamp,
  dt_first_doc_analysis_approved timestamp,
  dt_last_doc_analysis_approved timestamp,
  dt_first_doc_analysis_rejected timestamp,
  dt_last_doc_analysis_rejected timestamp,
  dt_guarantee_paid timestamp,
  status_sortinghat varchar(50),
  result_credit_evaluation varchar(50),
  credit_evaluation_count integer,
  flg_doc_reused integer,
  ts_processed timestamp,
  rejection_reason varchar,
  ts_load timestamp
)
;