DROP TABLE IF exists staging.dim_booking;
CREATE TABLE staging.dim_booking (
  sk_booking INTEGER,
  id_booking INTEGER,
  is_rescheduled boolean,
  dt_scheduling TIMESTAMP,
  visit_intent VARCHAR(100),
  buyer_intention VARCHAR(100),
  type VARCHAR(255),
  confirmed VARCHAR(100),
  performed VARCHAR(100),
  closed VARCHAR(100),
  visit_follow_up VARCHAR(255),
  dt_visit_follow_up TIMESTAMP,
  rescheduled_from_id INTEGER,
  id_visitor BIGINT,
  id_visit BIGINT,
  id_property BIGINT,
  id_agent BIGINT,
  id_attendant BIGINT,
  id_rental_flow bigint,
  status varchar(255),
  slot_dia INTEGER,
  reason VARCHAR(255),
  cancellation_reason VARCHAR(255),
  cancellation_reason_category VARCHAR(255),
  reason_category VARCHAR(255),
  responsible VARCHAR(255),
  app_type VARCHAR(255),
  media_source VARCHAR(255),
  adjust_network VARCHAR(255),
  utm_source VARCHAR(255),
  utm_medium VARCHAR(255),
  utm_campaign VARCHAR(2000),
  utm_content VARCHAR(255),
  utm_term VARCHAR(255),
  dt_cancel TIMESTAMP WITHOUT TIME ZONE,
  dt_created TIMESTAMP WITHOUT TIME ZONE,
  dt_updated TIMESTAMP WITHOUT TIME ZONE,
  last_update_source VARCHAR(255),
  first_update_source VARCHAR(255),
  visitor_arrived varchar(255),
  visitor_missing_reason varchar(255),
  agent_arrived varchar(255),
  agent_missing_reason varchar(255),
  owner_arrived varchar(255),
  owner_missing_reason varchar(255),
  successful_entrance varchar(255),
  troublesome_entrance varchar(255),
  checkin_status varchar(255),
  ts_scheduling_local TIMESTAMP WITHOUT TIME ZONE,
  ts_cancel_local TIMESTAMP WITHOUT TIME ZONE,
  ts_created_local TIMESTAMP WITHOUT TIME ZONE,
  ts_visit_follow_up_local TIMESTAMP WITHOUT TIME ZONE,
  is_first_booking_auto boolean,
  is_visit_created_from_app boolean,
  is_visit_last_updated_from_app boolean,
  flg_branded boolean,
  flg_via_reschedule boolean,
  sk_rent_flow_taxonomy bigint,
  mkt_category varchar(255),
  mkt_flow varchar(255),
  mkt_completion varchar(255),
  mkt_origin varchar(255),
  mkt_channel varchar(255),
  mkt_medium varchar(255),
  mkt_source varchar(255),
  mkt_platform varchar(255),
  ts_load TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT dim_booking_pkey PRIMARY KEY(sk_booking)
);