drop table if exists staging.dim_offer;
create table staging.dim_offer (
  sk_offer integer,
  id_offer integer,
  id_godfather integer,
  renting_value integer,
  renting_original_value integer,
  condo_original_value integer,
  dt_approved timestamp,
  editing varchar(50),
  status varchar(50),
  id_user integer,
  id_property integer,
  dt_created timestamp,
  dt_updated timestamp,
  dt_timestamp timestamp without time zone,
  offer_submitted boolean,
  ultimo_update_edicao integer,
  dt_first_sent timestamp,
  last_updated_date timestamp,
  expiration_date timestamp,
  last_rent_value_tenant decimal(18,4),
  last_rent_value_landlord decimal(18,4),
  total_rent_value decimal(18,4),
  rejection_reason varchar(255),
  animais_condition integer,
  quando_vai_mudar_condition integer,
  quem_vai_morar_condition integer,
  special_conditions_count integer,
  remove_conditions integer,
  include_conditions integer,
  maintenance_or_repair_conditions integer,
  replace_or_modify_conditions integer,
  price_conditions integer,
  other_conditions integer,
  type varchar(255),
  constraint dim_offer_pkey primary key(sk_offer)
)
;