drop table if exists staging.dim_contract;
create table staging.dim_contract (
  sk_contract integer,
  id_contract integer,
  email_invoice varchar(100),
  renting_value double precision,
  property_number integer,
  day_month_due integer,
  guarantee varchar(50),
  contract_type varchar(20),
  contract_status varchar(20),
  dt_calc_affiliate_comission timestamp without time zone,
  dt_calc_agent_comission timestamp without time zone,
  dt_contract_start date,
  dt_signature timestamp without time zone,
  dt_draft_approved timestamp without time zone,
  dt_entrance date,
  dt_contract_intended_end date,
  dt_contract_annulment date,
  bank_name varchar(50),
  condo_payer varchar(100),
  iptu_payer varchar(100),
  condo_responsible varchar(100),
  iptu_responsible varchar(100),
  rental_insurance_installments integer,
  rental_insurance_value double precision,
  home_insurance_installments integer,
  home_insurance_value double precision,
  first_rental_comission double precision,
  condo_value double precision,
  iptu_value double precision,
  signature_type varchar(50),
  dt_send_eletronic_contract timestamp without time zone,
  closing_status varchar(50),
  contract_signed varchar(50),
  contract_administration_signed varchar(50),
  contract_authorization_signed varchar(50),
  contract_renting_signed varchar(50),
  dt_ownership_changed varchar(50),
  dt_created timestamp without time zone,
  dt_updated timestamp without time zone,
  dt_timestamp timestamp without time zone
) ;
