drop table if exists staging.dim_lead;
CREATE TABLE staging.dim_lead (
  sk_lead BIGINT PRIMARY KEY,
  id BIGINT,
  area_total INTEGER,
  bairro VARCHAR(200),
  captado_em DATE,
  cep VARCHAR(9),
  cidade VARCHAR(200),
  complemento VARCHAR(200),
  endereco VARCHAR(200),
  nome_anunciante VARCHAR(255),
  numero VARCHAR(200),
  numero_banheiros INTEGER,
  numero_quartos INTEGER,
  numero_suites INTEGER,
  url_anuncio VARCHAR(255),
  telefone_anunciante VARCHAR(100),
  tipo VARCHAR(255),
  email VARCHAR(250),
  email_captador VARCHAR(250),
  telefone_captador VARCHAR(250),
  dentro_area_atuacao INTEGER,
  lat NUMERIC(10,7),
  lng NUMERIC(10,7),
  condominio INTEGER,
  iptu INTEGER,
  ub_page_variant VARCHAR(255),
  ub_page_name VARCHAR(255),
  reason VARCHAR(255),
  reason_detail VARCHAR(255),
  deadline_of_new_contact VARCHAR(255),
  status VARCHAR(255),
  processado SMALLINT,
  origem VARCHAR(255),
  is_enriched_data BOOLEAN,
  external_id VARCHAR(255),
  mencionar INTEGER,
  automatically_discarded INTEGER,
  proprietario_nome VARCHAR(255),
  proprietario_email VARCHAR(255),
  affiliate_type VARCHAR(255),
  dados_afiliado_inicio_atuacao TIMESTAMP WITHOUT TIME ZONE,
  dados_afiliado_cidade_atuacao VARCHAR(100),
  region_id INTEGER,
  atualizado_em TIMESTAMP WITHOUT TIME ZONE,
  criado_em TIMESTAMP WITHOUT TIME ZONE,
  utm_source VARCHAR(255),
  utm_medium VARCHAR(255),
  utm_campaign VARCHAR(255),
  utm_content VARCHAR(255),
  utm_term VARCHAR(255),
  tracking_platform VARCHAR(255),
  tracking_region VARCHAR(255),
  tracking_city VARCHAR(255),
  network VARCHAR(255),
  usuario_que_indicou_id VARCHAR(255),
  score_factor bigint,
  is_b2b boolean,
  b2b_type varchar,
  sales_company varchar,
  ts_sales_company_sent timestamp,
  sale_price bigint,
  is_for_rent boolean,
  is_for_sale boolean,
  load_timestamp TIMESTAMP WITHOUT TIME ZONE
) ;
