import requests
from retrying import retry
import json

from bietlejuice.jobs.composer.formatters import StringFormatter


class LabelStudioConnectionSync:
    """
    This class contains methods to synchronize the data contained in LabelStudio
    with a pre-configured connection to Storage S3.
    """

    def __init__(self, api_token, config_service, aws_credentials, bucket_name):
        self.api_headers = {"Authorization": f"Token {api_token}"}

        self.bucket_name = bucket_name

        self.aws_session_token = aws_credentials.get("aws_session_token")
        self.aws_access_key_id = aws_credentials.get("aws_access_key_id")
        self.aws_secret_access_key = aws_credentials.get("aws_secret_access_key")

        self.api_endpoint = config_service.get_config("endpoint")

    @staticmethod
    def __verify_response_content(api_response, expected_content, json_key):
        """
        This method checks if the content of the API response matches what is expected.
        @param api_response: json. Content returned by the API.
        @param expect_content: expected API content.
        @param json_key: specific key that will be verified.
        @return: json
        """
        if expected_content in StringFormatter.set_alphanumeric_snake_case(
            str(api_response.get(json_key))
        ):
            return api_response

    def __get_project_storage_info(self, project_id, project_name):
        """
        This method returns preconfigured storage information by a specific
        connection between Label Studio and Storage S3.
        @param project_id: project ID code generated by Label Studio.
        @param project_name: project name in the LabelStudio environment.
        @return: list
        """
        response = requests.get(
            f"{self.api_endpoint}storages/export/s3",
            headers=self.api_headers,
            params={"project": project_id},
        )
        if response:
            response = list(
                filter(
                    lambda storage: self.__verify_response_content(
                        storage, project_name, "prefix"
                    ),
                    json.loads(response.content),
                )
            )
            return response
        else:
            raise Exception(
                f"""m=__get_project_storage_info, project_name={project_name},
                    msg=The API returned an empty response body."""
            )

    def __update_s3_storage_connection_settings(self, storage_id, project_name):
        """
        The method updates AWS credentials in the LabelStudio connection.
        @param storage_id: storage connection ID code generated by Label Studio.
        """
        payloads = {
            "bucket": self.bucket_name,
            "prefix": f"raw/label_studio/sync/{project_name}",
            "aws_access_key_id": self.aws_access_key_id,
            "aws_secret_access_key": self.aws_secret_access_key,
            "aws_session_token": self.aws_session_token,
        }

        response = requests.patch(
            f"{self.api_endpoint}storages/export/s3/{storage_id}",
            payloads,
            headers=self.api_headers,
        )
        if not response.ok:
            raise Exception(
                f"""m=__update_s3_storage_connection_settings, storage_id={storage_id},
                msg=There seems to be some problem with the AWS credentials."""
            )

    @retry(stop_max_attempt_number=3, wait_fixed=60000)
    def __validate_s3_storage_connection(self, project_id, storage_infos):
        """
        The method validates S3 storage connection.
        @param project_id: project ID code generated by Label Studio.
        @param storage_infos: preconfigured storage information by a specific
        connection between Label Studio and Storage S3.
        """

        payloads = {
            "project": project_id,
            "bucket": storage_infos["bucket"],
            "prefix": storage_infos["prefix"],
            "aws_access_key_id": storage_infos["aws_access_key_id"],
            "aws_secret_access_key": storage_infos["aws_secret_access_key"],
            "aws_session_token": storage_infos["aws_session_token"],
        }
        response = requests.post(
            f"{self.api_endpoint}storages/export/s3/validate",
            payloads,
            headers=self.api_headers,
        )
        if not response.ok:
            raise Exception(
                f"""m=__validate_s3_storage_connection, project_id={project_id},
                msg=There seems to be some problem with the s3 storage connection settings."""
            )

    def __create_connection_s3_storage(self, project_id, project_name):
        payloads = {
            "project": project_id,
            "bucket": self.bucket_name,
            "prefix": f"raw/label_studio/sync/{project_name}",
            "aws_access_key_id": self.aws_access_key_id,
            "aws_secret_access_key": self.aws_secret_access_key,
            "aws_session_token": self.aws_session_token,
        }
        response = requests.post(
            f"{self.api_endpoint}storages/export/s3", payloads, headers=self.api_headers
        )
        if response.ok:
            return json.loads(response.content).get("id")
        else:
            raise Exception(
                f"""m=__validate_s3_storage_connection, project_id={project_id},
                msg=There seems to be some problem with the s3 storage connection settings."""
            )

    def get_projects_info(self):
        """
        This method returns projects of the Label Studio.
        @return: json
        """
        response = requests.get(
            f"{self.api_endpoint}projects", headers=self.api_headers
        )
        if response:
            return json.loads(response.content)
        else:
            raise Exception(
                f"""m=__get_project_id,
                    msg=The API returned an empty response body."""
            )

    def sync_data_s3_storage(self, project_id, project_name):
        """
        The method syncs the LabelStudio project data in S3 storage.
        @param project_id: project code in the LabelStudio environment.
        @param project_name: project name in the LabelStudio environment.
        """
        storages_info = self.__get_project_storage_info(project_id, project_name)
        if storages_info:
            storage = storages_info[0]
            storage_id = storage.get("id")
            self.__update_s3_storage_connection_settings(storage_id, project_name)
            # self.__validate_s3_storage_connection(
            #     project_id=project_id, storage_infos=storage
            # )
        else:
            storage_id = self.__create_connection_s3_storage(project_id, project_name)

        params = {"project": project_id, "use_blob_urls": False}

        response = requests.post(
            f"{self.api_endpoint}storages/export/s3/{storage_id}/sync",
            headers=self.api_headers,
            params=params,
        )
        if not response.ok and response.status_code != 504:
            raise Exception(
                f"""m=sync_data_s3_storage, project_name={project_name}, project_id={project_id}
                msg=Unable to sync data in storage. status_code={response.status_code}"""
            )
