SELECT
    NULLIF(id_rule_city_group_rent, '') AS id_rule_city_group_rent,
    NULLIF(id_rule_city_group_sale, '') AS id_rule_city_group_sale,
    NULLIF(email, '') AS email,
    NULLIF(team, '') AS team,
    NULLIF(entry_type, '') AS entry_type,
    BIGINT(NULLIF(invoice_number, '')) AS invoice_number,
    NULLIF(cnpj, '') AS cnpj,
    NULLIF(vendor_name, '') AS vendor_name,
    NULLIF(description, '') AS description,
    NULLIF(campaign_name, '') AS campaign_name,
    NULLIF(cost_category, '') AS cost_category,
    NULLIF(cost_subcategory, '') AS cost_subcategory,
    NULLIF(action, '') AS action,
    NULLIF(business_context, '') AS business_context,
    FLOAT(NULLIF(cost, '')) AS cost,
    NULLIF(has_cost_center_share, '') AS has_cost_center_share,
    NULLIF(id_rule_cost_center, '') AS id_rule_cost_center,
    NULLIF(has_city_group_share_1, '') AS has_city_group_share_1,
    NULLIF(cost_center, '') AS cost_center,
    NULLIF(has_city_group_share_2, '') AS has_city_group_share_2,
    NULLIF(city_group, '') AS city_group,
    TIMESTAMP(NULLIF(ts_entry,'')) AS ts_entry,
    DATE(NULLIF(dt_invoice, '')) AS dt_invoice,
    DATE(NULLIF(dt_service_started, '')) AS dt_service_started,
    DATE(NULLIF(dt_service_ended, '')) AS dt_service_ended
FROM
    datalake_marketing_offline_costs_raw.marketing_offline_manual_costs