SELECT
    id::BIGINT AS id_marketing_email,
    analyticsPageId AS id_analytics_page,
    canSpamSettingsId::BIGINT AS id_can_spam_settings,
    categoryId AS id_category,
    clonedFrom::BIGINT AS id_cloned_from,
    createdById::BIGINT AS id_created_by,
    feedbackSurveyId::BIGINT AS id_feedback_survey,
    portalId::BIGINT AS id_portal,
    primaryEmailCampaignId::BIGINT AS id_primary_email_campaign,
    publishedById::BIGINT AS id_published_by,
    subscription::BIGINT AS id_subscription,
    FROM_JSON(allEmailCampaignIds, 'array<bigint>') AS ids_all_email_campaigns,
    FROM_JSON(pastMabExperimentIds, 'array<bigint>') AS ids_past_mab_experiments,
    FROM_JSON(vidsIncluded, 'array<bigint>') AS ids_vids_included,
    FROM_JSON(vidsExcluded, 'array<bigint>') AS ids_vids_excluded,
    FROM_JSON(contentAccessRuleIds, 'array<bigint>') AS ids_content_access_rules,
    FROM_JSON(contentAccessRuleTypes, 'array<string>') AS content_access_rule_types,
    processingStatus AS processing_status,
    currentState AS current_state,
    securityState AS security_state,
    state,
    contentTypeCategory AS content_type_category,
    subcategory,
    analyticsPageType AS analytics_page_type,
    absoluteUrl AS absolute_url,
    audienceAccess AS audience_access,
    author AS author_email,
    authorName AS author_name,
    customReplyTo AS custom_reply_to,
    FROM_JSON(blogRssSettings, 'map<string, string>') AS blog_rss_settings,
    campaign,
    campaignName AS campaign_name,
    campaignUtm AS campaign_utm,
    domain,
    emailBody AS email_body,
    emailNote AS email_note,
    emailTemplateMode AS email_template_mode,
    emailType AS email_type,
    emailbodyPlainText AS email_body_plain_text,
    flexAreas AS flex_areas,
    fromName AS from_name,
    htmlTitle AS html_title,
    language,
    layoutSections AS layout_sections,
    liveDomain AS live_domain,
    metaDescription AS meta_description,
    name,
    previewKey AS preview_key,
    publishedByEmail AS published_by_email,
    publishedByName AS published_by_name,
    publishedUrl AS published_url,
    replyTo AS reply_to,
    resolvedDomain AS resolved_domain,
    rssEmailByText AS rss_email_by_text,
    rssEmailClickThroughText AS rss_email_click_through_text,
    rssEmailCommentText AS rss_email_comment_text,
    rssEmailUrl AS rss_email_url,
    sections,
    slug,
    smartEmailFields AS smart_email_fields,
    subject,
    subscriptionName AS subscription_name,
    teamPerms AS team_perms,
    templatePath AS template_path,
    translations,
    url,
    userPerms AS user_perms,
    abSampleSizeDefault AS ab_sample_size_default,
    abSamplingDefault AS ab_sampling_default,
    abSuccessMetric AS ab_success_metric,
    abHoursToWait::INT AS ab_hours_to_wait,
    abTestPercentage::INT AS ab_test_percentage,
    maxRssEntries::INT AS max_rss_entries,
    selected::INT AS selected,
    FROM_JSON(mailingListsExcluded, 'array<bigint>') AS mailing_lists_excluded,
    FROM_JSON(mailingListsIncluded, 'array<bigint>') AS mailing_lists_included,
    FROM_JSON(GET_JSON_OBJECT(stats, '$.counters'), 'map<string, int>') AS stats_counters,
    FROM_JSON(
        GET_JSON_OBJECT(stats, '$.deviceBreakdown'),
        'struct<open_device_type: map<string, int>, click_device_type: map<string, int>>'
    ) AS stats_device_breakdown,
    FROM_JSON(GET_JSON_OBJECT(stats, '$.ratios'), 'map<string, float>') AS stats_ratios,
    FROM_JSON(styleSettings, 'map<string, string>') AS style_settings,
    rssEmailImageMaxWidth::INT AS rss_email_image_max_width,
    ab::BOOLEAN AS is_ab,
    abVariation::BOOLEAN AS is_ab_variation,
    createPage::BOOLEAN AS has_create_page,
    pageExpiryEnabled::BOOLEAN AS is_page_expiry_enabled,
    pageRedirected::BOOLEAN AS is_page_redirected,
    transactional::BOOLEAN AS is_transactional,
    useRssHeadlineAsSubject::BOOLEAN AS is_using_rss_headline_as_subject,
    rssEmailEntryTemplateEnabled::BOOLEAN AS is_rss_email_entry_template_enabled,
    isGraymailSuppressionEnabled::BOOLEAN AS is_graymail_suppression_enabled,
    isRecipientFatigueSuppressionEnabled::BOOLEAN AS is_recipient_fatigue_suppression_enabled,
    isPublished::BOOLEAN AS is_published,
    currentlyPublished::BOOLEAN AS is_currently_published,
    customReplyToEnabled AS is_custom_reply_to_enabled,
    hasContentAccessRules::BOOLEAN AS has_content_access_rules,
    publishImmediately::BOOLEAN AS is_to_publish_immediately,
    visibleToAll::BOOLEAN AS is_visible_to_all,
    archivedInDashboard::BOOLEAN AS is_archived_in_dashboard,
    archived::BOOLEAN AS is_archived,
    TO_TIMESTAMP(NULLIF(freezeDate/1000, 0)) AS dt_freeze,
    TO_TIMESTAMP(NULLIF(publishDate/1000, 0)) AS dt_published,
    TO_TIMESTAMP(NULLIF(publishedAt/1000, 0)) AS ts_published,
    TO_TIMESTAMP(NULLIF(unpublishedAt/1000, 0)) AS ts_unpublished,
    TO_TIMESTAMP(NULLIF(archived_at/1000, 0)) AS ts_archived,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_hubspot_raw.marketing_email
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}
