SELECT
    id,
    id_invoice,
    id_original_invoice_external,
    id_contract,
    id_account,
    id_contract_internal,
    id_checkout_order,
    id_checkout_charge,
    id_idempotency,
    user,
    cdc_binlog_position,
    status,
    substatus,
    payment_status,
    paid_via,
    purpose,
    closing_mode,
    reason,
    due_amount,
    paid_amount,
    payment_paid_interest_amount,
    payment_paid_fine_amount,
    accrual_year_month,
    should_request_boleto,
    sispag_file,
    payment_company_use_number,
    payment_bank_code,
    payment_style_mapped,
    is_write_off,
    accrual_year_month_count,
    dt_due_adjusted,
    LAST_DAY(dt_reference) AS dt_closing,
    ts_write_off,
    ts_paid,
    ts_payment_confirmation,
    ts_payment_event,
    ts_payment_divergent_fixed,
    ts_payment_processing,
    ts_payment_credit,
    ts_payment_chargeback,
    ts_payment_refunded,
    ts_canceled,
    ts_sent,
    ts_due,
    ts_created,
    ts_synced,
    ts_nf_requested,
    ts_retsuko_created,
    ts_retsuko_updated,
    ts_cdc_transaction,
    ts_database_transaction,
    YEAR(LAST_DAY(dt_reference)) As year,
    MONTH(LAST_DAY(dt_reference)) AS month,
    DAY(LAST_DAY(dt_reference)) AS day,
    NOW() AS ts_load
FROM datalake_collections_aud.invoice_aud_daily
WHERE LAST_DAY(dt_reference) <= CURRENT_DATE
QUALIFY ROW_NUMBER() OVER(PARTITION BY id_invoice, DATE_TRUNC('MONTH', dt_reference) ORDER BY dt_reference DESC) = 1
