SELECT
    PbxBillingDataId AS id_pbx_billing_data,
    PbxDispositionId AS id_pbx_disposition,
    AgentId AS id_agent,
    CampaignId AS id_campaign,
    CallDirectionId AS id_call_direction,
    CustomerId AS id_customer,
    PhoneNumberId AS id_phone_humber,
    RecordId AS id_record,
    SessionId AS id_session,
    TelecomCallId AS id_telecom_call,
    TotalTime AS total_time,
    TrunkNumber AS trunk_number,
    Signaling AS signaling,
    SignalingExtraInfo AS signaling_extra_info,
    SignalingTime AS signaling_time,
    Route AS route,
    PbxName AS pbx_name,
    CampaignCode AS campaign_code,
    Channel AS channel,
    Company AS company,
    AlertingTime AS alerting_time,
    AnalysisTime AS analysis_time,
    Ani AS ani,
    BillingCode AS billing_code,
    Board AS board,
    ConversationTime AS conversation_time,
    DeviceName AS device_name,
    Dnis AS dnis,
    Link AS link,
    MailingName AS mailing_name,
    OriginalPhoneNumber AS original_phone_number,
    StartDate AS ts_started,
    year,
    month,
    day
FROM
    datalake_olos_dialer_raw.PbxBillingData
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')