SELECT
  CAST(NULLIF(proposal_id, '') AS INTEGER) AS id_proposal,
  NULLIF(_analyst_name, '') AS analyst_name,
  NULLIF(modelo_auditoria, '') AS audit_model,
  NULLIF(_background_e_cofirmacao_positiva, '') AS background_positive_confirmed,
  NULLIF(_comment, '') AS comment,
  NULLIF(_decisao_de_credito, '') AS credit_decision,
  NULLIF(_feedback_para_o_lider, '') AS feedbacks_to_leadership,
  NULLIF(_capacidade_financeira_full, '') AS full_financial_capacity,
  NULLIF(guarantee, '') AS guarantee,
  NULLIF(_hashtag, '') AS hashtag,
  NULLIF(jobtype, '') AS job_type,
  NULLIF(versao_modelo, '') AS model_version,
  NULLIF(_outras_regras, '') AS other_rules,
  NULLIF(range, '') AS range,
  NULLIF(reason, '') AS reason,
  NULLIF(_motivo_de_recusa_rejected, '') AS reject_reason,
  NULLIF(_analista_responsavel, '') AS responsible_analyst_name,
  NULLIF(result, '') AS result,
  NULLIF(risk_category, '') AS risk_category,
  NULLIF(_supervisor_name, '') AS supervisor_name,
  NULLIF(type, '') AS type,
  CAST(REGEXP_REPLACE(NULLIF(_renda, ''), ',', '.') AS FLOAT) AS income,
  CAST(REGEXP_REPLACE(NULLIF(package, ''), ',', '.') AS FLOAT) AS package,
  CAST(NULLIF(_nota_background, '') AS INTEGER) AS background_score,
  CAST(NULLIF(_nota_decisao, '') AS INTEGER) AS decision_score,
  CAST(REGEXP_REPLACE(NULLIF(nota, ''), ',', '.') AS FLOAT) AS final_score,
  CAST(NULLIF(_nota_capacidade_financeira, '') AS INTEGER) AS financial_capacity_score,
  CAST(NULLIF(_nota_outras_regras, '') AS INTEGER) AS other_rules_score,
  CAST(NULLIF(_nota_motivo_de_recusa, '') AS INTEGER) AS reject_reason_score,
  CAST(NULLIF(fator_de_rigor, '') AS INTEGER) AS rigor_factor,
  CAST(REGEXP_REPLACE(NULLIF(semaforo_de_risco_amostra, ''), ',', '.') AS FLOAT) AS semaforo_de_risco_score,
  CAST(NULLIF(_peso_background, '') AS INTEGER) AS weight_background,
  CAST(NULLIF(_peso_capacidade_financeira, '') AS INTEGER) AS weight_financial_capacity,
  CAST(NULLIF(_peso_decisao, '') AS INTEGER) AS weight_decision,
  CAST(NULLIF(_peso_outras_regras, '') AS INTEGER) AS weight_other_rules,
  CAST(NULLIF(_peso_motivo_recusa, '') AS INTEGER) AS weight_refuse_reasons,
  TO_DATE(NULLIF(data_analise, ''), 'dd/MM/yyyy') AS dt_analyzed,
  TO_DATE(NULLIF(data_auditoria, ''), 'dd/MM/yyyy') AS dt_audited,
  TO_TIMESTAMP(NULLIF(time, ''), 'dd/MM/yyyy HH:mm:ss') AS ts_created,
  CAST(NULLIF(mes, '') AS INTEGER) AS month,
  CAST(NULLIF(semana, '') AS INTEGER) AS week,
  CAST(NULLIF(dia, '') AS INTEGER) AS day
FROM 
  datalake_gsheets_raw.credit_decisions_auditing