SELECT
    id,
    dadosAgente_id AS id_agent,
    salesforceId AS id_salesforce,
    estado_id AS id_state,
    region_id AS id_region,
    externalId AS id_external,
    ownerDeviceId AS id_owner_device,
    proprietarioLead_id AS id_lead_owner,
    imobiliaria_id AS id_real_estate_agency,
    corretorQueIndicou_id AS id_agent_has_indicated,
    gerenteContas_id AS id_account_manager,
    afiliadoQueIndicou_id AS id_affiliate_has_indicated,
    agrupamentoLeadsPorTelefone_id AS id_leads_grouped_by_phone,
    areaTotal AS total_area,
    endereco AS address,
    numero AS house_number,
    complemento AS complement,
    bairro AS neighborhood,
    cidade AS city,
    cep AS zip_code,
    enderecoCaptado AS address_picked_up,
    nomeAnunciante AS advertiser_name,
    numeroBanheiros AS bathrooms,
    numeroQuartos AS bedrooms,
    numeroSuites AS suites,
    urlAnuncio AS ad_url,
    valor AS rent,
    telefoneAnunciante AS advertiser_phone,
    valorPorMetroQuad AS rent_per_square_meter,
    valorPorQuartos AS rent_per_bedroom,
    tipo AS type,
    email,
    infosExtras AS extra_infos,
    emailCaptador AS pick_up_email,
    telefoneAnuncianteDois AS advertiser_second_phone,
    telefoneAnuncianteTres AS advertiser_third_phone,
    telefoneCaptador AS pick_up_phone,
    lat,
    lng,
    latBkp AS lat_bkp,
    lngBkp AS lng_bkp,
    latBkp2 AS lat_bkp2,
    lngBkp2 AS lng_bkp2,
    condominio AS condo_price,
    iptu,
    reason,
    status,
    origem AS source,
    referencia AS reference,
    urlSource AS url_source,
    utmMedium AS utm_medium,
    utmCampaign AS utm_campaign,
    utmSource AS utm_source,
    outroBairro AS other_neighborhood,
    outraCidade AS other_city,
    recurringStatusCount AS recurring_status_count,
    codigoImobiliaria AS real_estate_agency_code,
    unbouncePageName AS unbounce_page_name,
    unbouncePageVariant AS unbounce_page_variant,
    unbouncePageUri AS unbounce_page_uri,
    salePrice AS sale_price,
    affiliateType AS affiliate_type,
    sistemaEnviouEmailViaClassificado AS has_sent_email_from_classifieds,
    envioEmailApresentacaoPos AS has_sent_presentation_email_after_registration,
    envioEmailApresentacaoPre AS has_sent_presentation_email_before_registration,
    processado AS has_processed,
    automaticallyDiscarded AS has_automatically_discarded,
    geradoAPartirDeDuplicacao AS is_generated_from_duplication,
    dentroAreaAtuacao AS is_inside_operation_area,
    hot AS is_hot,
    mencionar AS is_to_be_mentioned,
    fromRoofTopper AS is_from_roof_topper,
    exclusivityIntent AS is_exclusivity_intent,
    isEnrichedData AS is_enriched_data,
    forRent AS is_for_rent,
    forSale AS is_for_sale,
    anuncioCriadoEm AS dt_ad_created,
    captadoEm AS dt_picked_up,
    proximoFollowup AS ts_next_follow_up,
    lastUpdateStatusDate AS ts_last_status_updated,
    criadoEm AS ts_created,
    atualizadoEm AS ts_updated
FROM
    datalake_ebdb_test_raw.lead