with distinct_data as (
    select distinct * from datalake_raw.zendesk_tickets
)
select
    subject,
    created_at,
    description,
    external_id,
    type,
    replace(cast(json_extract(via, '$.channel') as varchar), '"') as channel,
    json_extract(via, '$.source') as source,
    updated_at,
    problem_id,
    due_at,
    id,
    assignee_id,
    generated_timestamp,
    raw_subject,
    forum_topic_id,
    custom_fields,
    allow_channelback,
    satisfaction_rating,
    submitter_id,
    priority,
    collaborator_ids ,
    tags,
    brand_id,
    metric_set,
    group_id,
    organization_id,
    recipient,
    is_public,
    has_incidents,
    status,
    requester_id
from distinct_data