SELECT
	id,
    feature_id AS id_feature,
    consolidated_id AS id_consolidated,
    business_entity_id AS id_business_entity,
    finance_entity_id AS id_finance_entity,
    external_payment_id AS id_external_payment,
    person_id AS id_person,
    amount,
    business_place,
    user_type,
    source_client,
    status,
    city_state,
    city,
    accounting_rule,
    accounting_type,
    person_card_code,
    person_document,
    person_document_type,
    sequence_code,
    description,
    cost_center,
    account_code,
    account_cfop_code,
    account_managerial_center,
    reversed,
    reference_year_month,
    DATE(event_date) AS dt_event,
    DATE(due_date) AS dt_due,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated
FROM
    datalake_sap_gateway_raw.invoice
