SELECT
    CAST(to_timestamp(timestamp, 'yyyy-MM-dd H:mm:ss') AS TIMESTAMP) AS creation_timestamp,
    CAST(to_timestamp(execucao, 'yyyy-MM-dd H:mm:ss') AS TIMESTAMP) AS execution_timestamp,
    CAST(incluirnadatade AS DATE) AS include_on_date,
    CAST(cobrarnadatade AS DATE) AS charge_on_date,
    CAST(solicitacao AS INT) AS request_id,
    CAST(contrato AS INT) AS contract_id,
    CAST(imovel AS INT) AS property_id,
    CAST(ticket AS INT) AS ticket_id,
    CAST(quantidadeparcelas AS INT) AS billing_installment_count,
    CAST(quantidadeparcelascobranca AS INT) AS payment_installment_count,
    CAST(cancelado AS INT) AS sheet_row_index,
    CAST(valorbandaid AS DECIMAL(10, 2)) AS bandaid_value,
    CAST(tarefa AS STRING) AS task_name,
    CAST(analista AS STRING) AS analyst_email,
    CAST(fatura_extra AS STRING) AS has_extra_invoice,
    CAST(de AS STRING) AS payer_type,
    CAST(para AS STRING) AS receiver_type,
    CAST(tipobandaid AS STRING) AS bandaid_type,
    CAST(parcelamento AS STRING) AS billing_installment_type,
    CAST(parcelamentocobranca AS STRING) AS payment_installment_type,
    CAST(resumo AS STRING) AS bandaid_summary,
    CAST(numerobandaid AS STRING) AS bandaid_reference_code,
    CAST(tipodespesa AS STRING) AS expense_type,
    CAST(statusbandaid AS STRING) AS bandaid_status,
    CAST(divergencia_fatura AS STRING) AS invoice_divergence_notes,
    CAST(taskrow AS STRING) AS cancellation_reason,
    CAST(solicitacao_cancelamento AS STRING) AS cancellation_request_by,
    CAST(titular_da_conta AS STRING) AS bank_account_holder_name,
    CAST(cpf AS STRING) AS tax_id,
    CAST(agencia AS STRING) AS bank_agency_code,
    CAST(banco AS STRING) AS bank_name,
    CAST(conta_corrente AS STRING) AS bank_account_code,
    CAST(tipo_de_conta AS STRING) AS bank_account_type,
    CAST(queue AS STRING) AS queue_context_name
FROM
    datalake_gsheets_raw.bandaid
