SELECT
    CAST(to_timestamp(timestamp, 'yyyy-MM-dd H:mm:ss') AS TIMESTAMP) AS creation_timestamp,
    CAST(to_date(data_de_rescisao, 'yyyy-MM-dd') AS DATE) AS termination_date,
    CAST(to_date(data_inicio, 'yyyy-MM-dd') AS DATE) AS billing_period_start_date,
    CAST(to_date(data_final, 'yyyy-MM-dd') AS DATE) AS billing_period_end_date,
    CAST(to_date(data_de_vencimento, 'yyyy-MM-dd') AS DATE) AS due_date,
    CAST(to_timestamp(data_cnab, 'yyyy-MM-dd H:mm') AS TIMESTAMP) AS cnab_generation_timestamp,
    CAST(to_date(vencimento_pdf, 'dd/MM/yyyy') AS DATE) AS pdf_extracted_due_date,
    CAST(solicitacao AS INT) AS request_id,
    CAST(contrato AS INT) AS contract_id,
    CAST(imovel AS INT) AS property_id,
    CAST(ticket_da_tratativa AS INT) AS ticket_id,
    CAST(temp_med_s AS INT) AS processing_time_seconds,
    CAST(`row` AS INT) AS sheet_row_index,
    CAST(format_inv_amount AS DECIMAL(10, 2)) AS formatted_invoice_value,
    CAST(valor_pdf AS DECIMAL(10, 2)) AS pdf_extracted_value,
    CAST(tarefa AS STRING) AS task_name,
    CAST(status_do_contrato AS STRING) AS contract_status,
    CAST(analista AS STRING) AS analyst_email,
    CAST(centro_de_custo AS STRING) AS cost_center_name,
    CAST(nome_da_concessionaria AS STRING) AS utility_company_name,
    CAST(valor_da_conta AS STRING) AS invoice_amount,
    CAST(cod_de_barras AS STRING) AS barcode_number,
    CAST(upload_da_conta AS STRING) AS invoice_file_url,
    CAST(resumo AS STRING) AS case_summary,
    CAST(despesa AS STRING) AS expense_type,
    CAST(tipo_de_cobranca AS STRING) AS billing_charge_type,
    CAST(status AS STRING) AS execution_status,
    CAST(observacao AS STRING) AS internal_notes,
    CAST(data_de_inicio_da_cobranca_ao_iq AS STRING) AS tenant_charge_start_date,
    CAST(data_final_da_cobranca_ao_iq AS STRING) AS tenant_charge_end_date,
    CAST(data_de_inicio_da_cobranca_ao_pp AS STRING) AS landlord_charge_start_date,
    CAST(data_final_da_cobranca_ao_pp AS STRING) AS landlord_charge_end_date,
    CAST(lancamentos_sr_barriga AS STRING) AS accounting_system_log,
    CAST(cnab AS STRING) AS cnab_file_id,
    CAST(id_da_botcity AS STRING) AS botcity_execution_id,
    CAST(acao_sugerida AS STRING) AS suggested_action,
    CAST(detalhe_justificativa AS STRING) AS action_justification,
    CAST(codigo_barras_pdf AS STRING) AS pdf_extracted_barcode,
    CAST(referencia_pdf AS STRING) AS pdf_extracted_reference_month,
    CAST(concessionaria_pdf AS STRING) AS pdf_extracted_utility_name,
    CAST(status_leitura_pdf AS STRING) AS pdf_reading_status,
    CAST(detalhe_leitura_pdf AS STRING) AS pdf_reading_details,
    CAST(check_pdf_x_planilha AS STRING) AS pdf_vs_sheet_check_status
FROM
    datalake_gsheets_raw.cnab_payment
