SELECT
    NULLIF(Active_Flow, '') AS active_flow,
    NULLIF(Active_Stock, '') AS active_stock,
    NULLIF(FPD, '') AS fpd,
    NULLIF(Property_Owners, '') AS property_owners,
    NULLIF(Ended_1_to_90, '') AS ended_1_to_90,
    NULLIF(Ended_91_to_360, '') AS ended_91_to_360,
    NULLIF(Ended_greater_360, '') AS ended_greater_360,
    NULLIF(Detractor_index, '') AS detractor_index,
    NULLIF(Active_Cushion_Effectiveness, '') AS active_cushion_effectiveness,
    NULLIF(Ended_Cushion_Effectiveness, '') AS ended_cushion_effectiveness,
    NULLIF(Resolution_Rate_120D, '') AS resolution_rate_120d,
    NULLIF(Resolution_Rate_120_to_240D, '') AS resolution_rate_120_to_240d,
    NULLIF(Resolution_Rate_greater_240D, '') AS resolution_rate_greater_240d,
    NULLIF(Resolution_Rate_240D_to_360D, '') AS resolution_rate_240d_to_360d,
    NULLIF(Resolution_Rate_greater_360D, '') AS resolution_rate_greater_360d,
    NULLIF(Resolution_Rate_MOB3, '') AS resolution_rate_mob3,
    NULLIF(Eficiencia_Processual, '') AS process_efficiency,
    NULLIF(Average_Overdue_Rent_Anomalies_greater_120, '') AS average_overdue_rent_anomalies_greater_120,
    NULLIF(Active_Flow_forecast, '') AS active_flow_forecast,
    NULLIF(Active_Stock_forecast, '') AS active_stock_forecast,
    NULLIF(FPD_forecast, '') AS fpd_forecast,
    NULLIF(Property_Owners_forecast, '') AS property_owners_forecast,
    NULLIF(Ended_1_to_90_forecast, '') AS ended_1_to_90_forecast,
    NULLIF(Ended_91_to_360_forecast, '') AS ended_91_to_360_forecast,
    NULLIF(Ended_greater_360_forecast, '') AS ended_greater_360_forecast,
    NULLIF(Detractor_index_forecast, '') AS detractor_index_forecast,
    NULLIF(Active_Cushion_Effectiveness_forecast, '') AS active_cushion_effectiveness_forecast,
    NULLIF(Ended_Cushion_Effectiveness_forecast, '') AS ended_cushion_effectiveness_forecast,
    NULLIF(Resolution_Rate_120D_forecast, '') AS resolution_rate_120d_forecast,
    NULLIF(Resolution_Rate_120_to_240D_forecast, '') AS resolution_rate_120_to_240d_forecast,
    NULLIF(Resolution_Rate_greater_240D_forecast, '') AS resolution_rate_greater_240d_forecast,
    NULLIF(Resolution_Rate_240D_to_360D_forecast, '') AS resolution_rate_240d_to_360d_forecast,
    NULLIF(Resolution_Rate_greater_360D_forecast, '') AS resolution_rate_greater_360d_forecast,
    NULLIF(Resolution_Rate_MOB3_forecast, '') AS resolution_rate_mob3_forecast,
    NULLIF(Eficiencia_Processual_forecast, '') AS process_efficiency_forecast,
    NULLIF(Average_Overdue_Rent_Anomalies_greater_120_forecast, '') AS average_overdue_rent_anomalies_greater_120_forecast,
    NULLIF(working_days_today, '') AS working_days_today,
    NULLIF(week_of_the_year, '') AS week_of_the_year,
    NULLIF(day, '') AS day,
    NULLIF(month, '') AS month,
    NULLIF(Date, '') AS dt_reference,
    NOW() AS ts_load
FROM
    datalake_gsheets_raw.collections_targets
