SELECT
    CAST(to_timestamp(timestamp, 'yyyy-MM-dd H:mm:ss') AS TIMESTAMP) AS creation_timestamp,
    CAST(to_timestamp(done_at, 'yyyy-MM-dd H:mm:ss') AS TIMESTAMP) AS execution_timestamp,
    CAST(solicitacao AS INT) AS request_id,
    CAST(contrato AS INT) AS contract_id,
    CAST(imovel AS INT) AS property_id,
    CAST(`row` AS INT) AS sheet_row_index,
    CAST(valor_total AS DECIMAL(10, 2)) AS total_value,
    CAST(valor_final_negociado AS DECIMAL(10, 2)) AS negotiated_final_value,
    CAST(parcelas_cobranca AS INT) AS billing_installments,
    CAST(parcelas_repasses AS INT) AS payout_installments,
    CAST(solicitante AS STRING) AS requester_email,
    CAST(time AS STRING) AS team_name,
    CAST(ticket AS STRING) AS ticket_id,
    CAST(resumo AS STRING) AS request_summary,
    CAST(tipo_de_multa AS STRING) AS penalty_type,
    CAST(cumpriu_aviso_previo AS STRING) AS complied_notice_period,
    CAST(tx_de_corretagem_corretor AS STRING) AS is_broker_fee_waived,
    CAST(tx_de_corretagem_5a AS STRING) AS is_company_fee_waived,
    CAST(getnet AS STRING) AS is_getnet_payment,
    CAST(isencao_de_juros AS STRING) AS is_interest_waived,
    CAST(bandaid_aberto AS STRING) AS is_bandaid_opened,
    CAST(id_do_bandaid AS STRING) AS bandaid_id,
    CAST(dados_iq_titular AS STRING) AS tenant_account_holder_name,
    CAST(dados_iq_cpfcnpj AS STRING) AS tenant_tax_id,
    CAST(dados_iq_banco AS STRING) AS tenant_bank_name,
    CAST(dados_iq_agencia AS STRING) AS tenant_bank_agency_code,
    CAST(dados_iq_conta AS STRING) AS tenant_bank_account_code,
    CAST(dados_iq_tipo_de_conta AS STRING) AS tenant_bank_account_type,
    CAST(log AS STRING) AS execution_log,
    CAST(bot AS STRING) AS bot_execution_id,
    CAST(aux_evictions AS STRING) AS eviction_aux_notes,
    CAST(split_queue AS STRING) AS split_queue_name,
    CAST(sendtoqueue AS STRING) AS queue_target_id
FROM
    datalake_gsheets_raw.early_termination_fee
