SELECT
    ID_Processo AS id_process,
    Contrato AS contract,
    Processo AS process,
    Tipo_entrada AS input_type,
    Categoria_entrada AS contract_category_at_registration,
    Tipo_acao AS action_type,
    Acao AS action,
    Escritorio AS office,
    Agencia_cobranca AS collection_agency,
    Camara AS chamber,
    Regiao AS region,
    Cidade AS city,
    Status_contrato AS contract_status,
    Status_elaw AS elaw_status,
    ultima_fase AS last_stage,
    Status_passagem AS passage_status,
    Reincidente AS is_reincident,
    Procedimento AS procedure,
    Motivo_consolidado AS consolidated_reason,
    Motivo_padronizado AS standardized_reason,
    Resultado AS result,
    Honorario_sucumbencia AS succumbency_fee,
    Total_pacote AS total_package,
    Total_divida AS total_due_amount,
    Dias_Inad_Registro AS overdue_days_at_registration,
    LDT_Estoque AS ldt_stock,
    Faixa_Estoque AS stock_range,
    LDT_Resolucao_Faixas AS ldt_resolution,
    Faixa_Resolucao AS resolution_range,
    LDT_Resolucao_Real AS real_ldt_resolution,
    LDT_Distribuicao_arbitral AS ldt_arbitral_distribution,
    LDT_Sentenca_arbitral AS ldt_arbitral_award,
    LDT_Distribuicao_judicial AS ldt_judiciary_distribution,
    LDT_Decisao_citacao_judicial AS ldt_judicial_summons_decision,
    LDT_Decisao_coercitivo AS ldt_coercive_decision,
    LDT_Decisao_emissao_coercitivo AS ldt_coercive_order_issuance_decision,
    Defesa_arbitral AS has_arbitration_defense,
    Redistribuicao AS has_redistribution,
    CAST(Pre_cadastro_arbitral AS DATE) AS dt_registered,
    CAST(distribuicao_arbitral AS DATE) AS dt_arbitral_distribution,
    CAST(Citacao_Arbitral AS DATE) AS dt_arbitral_citation,
    CAST(Contestacao_arbitral AS DATE) AS dt_arbitral_contestation,
    CAST(Sentenca_Arbitral AS DATE) AS dt_arbitral_sentence,
    CAST(Pre_Cadastro_judicial AS DATE) AS dt_judiciary_pre_registration,
    CAST(Distribuicao_judicial AS DATE) AS dt_judiciary_distribution,
    CAST(decisao_citacao_judicial AS DATE) AS dt_judicial_summons_decision,
    CAST(citacao_judicial AS DATE) AS dt_judicial_summons,
    CAST(contestacao_judicial AS DATE) AS dt_judicial_defense,
    CAST(decisao_coercitivo AS DATE) AS dt_coercive_decision,
    CAST(emissao_coercitivo AS DATE) AS dt_coercive_issuance,
    CAST(data_finalizando AS DATE) AS dt_finalizing,
    CAST(data_finalizado_ERC AS DATE) AS dt_finalized_erc,
    CAST(Data_quitacao AS DATE) AS dt_payment,
    CAST(Data_penhora AS DATE) AS dt_asset_attachment,
    CAST(Data_encerramento_elaw AS DATE) AS dt_elaw_closure,
    NOW() AS ts_load
FROM
    datalake_gsheets_raw.evictions_base
