SELECT
    CAST(to_timestamp(timestamp, 'yyyy-MM-dd H:mm:ss') AS TIMESTAMP) AS creation_timestamp,
    CAST(vencimento AS DATE) AS due_date,
    CAST(solicitacao AS INT) AS request_id,
    CAST(contrato AS INT) AS contract_id,
    CAST(imovel AS INT) AS property_id,
    CAST(ticket AS INT) AS ticket_id,
    CAST(valor AS DECIMAL(10, 2)) AS invoice_value,
    CAST(multa AS DECIMAL(10, 2)) AS penalty_value,
    CAST(parcelas AS INT) AS installment_count,
    CAST(tipo AS INT) AS hash_verification_id,
    CAST(linha AS INT) AS sheet_row_index,
    CAST(automacao AS STRING) AS automation_name,
    CAST(analista AS STRING) AS analyst_email,
    CAST(origem AS STRING) AS origin_source,
    CAST(despesa AS STRING) AS expense_type,
    CAST(de AS STRING) AS payer_type,
    CAST(para AS STRING) AS receiver_type,
    CAST(getnet AS STRING) AS is_getnet_payment,
    CAST(isentar_juros AS STRING) AS is_waive_interest,
    CAST(resumo AS STRING) AS invoice_summary,
    CAST(titular AS STRING) AS account_holder_name,
    CAST(banco AS STRING) AS bank_version_id,
    CAST(agencia AS STRING) AS bank_agency_code,
    CAST(conta AS STRING) AS bank_account_code,
    CAST(cpf AS STRING) AS tax_id,
    CAST(mes_vencimento AS STRING) AS due_month,
    CAST(execucao AS STRING) AS execution_date,
    CAST(ref_mes AS STRING) AS reference_month,
    CAST(cancelado AS STRING) AS is_canceled,
    CAST(observacao AS STRING) AS internal_notes
FROM
    datalake_gsheets_raw.extra_invoice
