SELECT
    NULLIF(id_offer, '') AS id_offer,
    id_house,
    business_unit_description,
    payment_model,
    sale_price_agreed,
    brokerage_fee,
    CAST(NULLIF(dt_sale_agreement_signed, '') AS DATE) AS dt_sale_agreement_signed,
    CAST(NULLIF(dt_legal_analysis, '') AS DATE) AS dt_legal_analysis,
    CAST(NULLIF(dt_cancelled, '') AS DATE) AS dt_cancelled,
    offer_cancelled,
    cancellation_brokerage,
    CAST(NULLIF(dt_payment_allowed, '') AS DATE) AS dt_payment_allowed,
    supply_x_demand,
    is_legal_entity,
    is_contract_amendment,
    gross_brokerage_amount,
    taxes_and_deductions,
    partner_fee_value_demand,
    brokerage_amount,
    brokerage_quinto_andar_amount,
    brokerage_estate_agent_amount,
    total_received,
    broker_payment,
    broker_discount,
    invoice_amount_current_period,
    invoice_amount,
    band_aid_cost,
    broker_payment_platform,
    broker_payment_rede_ti,
    accounting_receivables,
    accounting_brokerage_provision,
    accounting_cancellation_receivables,
    accounting_advance_broker_payment,
    accounting_advance_buyer_payment,
    accounting_buyer_amount_to_transfer,
    accounting_broker_amount_to_transfer,
    accounting_brokerage_revenue,
    accounting_cancellation_revenue,
    accounting_total_loss,
    accounting_band_aid_cost,
    loss_adjust_invoice_current_period,
    accounting_cancellation_revenue_previous_period,
    accounting_total_loss_previous_period,
    pipeline
FROM datalake_gsheets_raw.for_sale_manual_recon