SELECT
    CAST(to_timestamp(timestamp, 'yyyy-MM-dd H:mm:ss') AS TIMESTAMP) AS creation_timestamp,
    CAST(to_date(data_de_rescisao, 'yyyy-MM-dd') AS DATE) AS termination_date,
    CAST(to_date(data_inicio, 'yyyy-MM-dd') AS DATE) AS billing_period_start_date,
    CAST(to_date(data_final, 'yyyy-MM-dd') AS DATE) AS billing_period_end_date,
    CAST(to_date(data_de_vencimento, 'yyyy-MM-dd') AS DATE) AS due_date,
    CAST(to_date(data, 'yyyy-MM-dd') AS DATE) AS payment_record_date,
    CAST(solicitacao AS INT) AS request_id,
    CAST(contrato AS INT) AS contract_id,
    CAST(imovel AS INT) AS property_id,
    CAST(ticket_da_tratativa AS INT) AS ticket_id,
    CAST(id_da_botcity AS STRING) AS botcity_execution_id,
    CAST(temp_med_s AS INT) AS processing_time_seconds,
    CAST(format_inv_amount AS DECIMAL(10, 2)) AS formatted_invoice_value,
    CAST(tarefa AS STRING) AS task_name,
    CAST(status_do_contrato AS STRING) AS contract_status,
    CAST(analista AS STRING) AS analyst_email,
    CAST(centro_de_custo AS STRING) AS cost_center_name,
    CAST(nome_da_concessionaria AS STRING) AS utility_company_name,
    CAST(valor_da_conta AS STRING) AS invoice_amount,
    CAST(cod_de_barras AS STRING) AS barcode_number,
    CAST(upload_da_conta AS STRING) AS invoice_file_url,
    CAST(resumo AS STRING) AS case_summary,
    CAST(despesa AS STRING) AS expense_type,
    CAST(tipo_de_cobranca AS STRING) AS billing_charge_type,
    CAST(status_do_pagamento AS STRING) AS execution_status,
    CAST(observacao AS STRING) AS internal_notes,
    CAST(lancamentos_sr_barriga AS STRING) AS accounting_system_log,
    CAST(validacao_banco_do_codigo_de_barras AS STRING) AS barcode_bank_validation_status,
    CAST(validacao_tamanho_do_codigo_de_barras AS STRING) AS barcode_length_validation_status,
    CAST(validacao_duplicidade AS STRING) AS duplicate_validation_status,
    CAST(check_final AS STRING) AS final_check_status,
    CAST(data_de_inicio_da_cobranca_ao_iq AS STRING) AS tenant_charge_start_date,
    CAST(data_final_da_cobranca_ao_iq AS STRING) AS tenant_charge_end_date,
    CAST(data_de_inicio_da_cobranca_ao_pp AS STRING) AS landlord_charge_start_date,
    CAST(data_final_da_cobranca_ao_pp AS STRING) AS landlord_charge_end_date
FROM
    datalake_gsheets_raw.manual_payment
