SELECT
    CAST(NULLIF(imovel_id, '') AS BIGINT) AS sk_house,
    CAST(NULLIF(contrato_id, '') AS BIGINT) AS sk_contract,
    CAST(NULLIF(id_proposta_base, '') AS BIGINT) AS sk_base_proposal,
    CAST(NULLIF(id_parcela, '') AS BIGINT) AS sk_installment,
    CAST(NULLIF(produto_id, '') AS BIGINT) AS sk_product,
    CAST(NULLIF(banco, '') AS BIGINT) AS id_bank,
    NULLIF(Nome, '') AS owner_full_name,
    NULLIF(cpf_cnpj, '') AS owner_cpf_cnpj,
    NULLIF(cnpj_investidor, '') AS investor_cnpj,
    CAST(NULLIF(numero_parcela, '') AS BIGINT) AS installment_number,
    NULLIF(status, '') AS installment_status,
    NULLIF(Numero_CCB, '') AS ccb_number,
    NULLIF(Numero_CCCB, '') AS cccb_number,
    NULLIF(conta, '') AS bank_account_number,
    NULLIF(agencia, '') AS bank_branch_number,
    NULLIF(status_solicitacao, '') AS request_status,
    CAST(NULLIF(Qtde_Parcelas, '') AS BIGINT) AS installment_total_count,
    CAST(REPLACE(Soma_Parcelas, ',', '') AS DOUBLE) AS installment_total_sum,
    CAST(REPLACE(juros_parcela_contrato, ',', '') AS DOUBLE) AS contract_installment_interest,
    CAST(REPLACE(juros_remuneratorios, ',', '') AS DOUBLE) AS compensatory_interest,
    CAST(REPLACE(juros_mora, ',', '') AS DOUBLE) AS delay_interest,
    CAST(REPLACE(Taxa_Juros, ',', '') AS DOUBLE) AS interest_rate,
    CAST(REPLACE(multa, ',', '') AS DOUBLE) AS fine_value,
    CAST(REPLACE(principal_parcela_contrato, '.', '') AS DOUBLE) AS contract_main_installment_value,
    CAST(REPLACE(Valor_Principal, ',', '') AS DOUBLE) AS main_value,
    CAST(REPLACE(Valor_Juros, ',', '') AS DOUBLE) AS interest_value,
    CAST(REPLACE(valor_parcela, ',', '') AS DOUBLE) AS installment_value,
    CAST(REPLACE(valor_pago, ',', '') AS DOUBLE) AS paid_value,
    CAST(REPLACE(Valor_Bruto, ',', '') AS DOUBLE) AS gross_value,
    CAST(REPLACE(Valor_Liquido, ',', '') AS DOUBLE) AS net_value,
    CAST(REPLACE(IOF, ',', '') AS DOUBLE) AS iof_tax_value,
    CAST(REPLACE(Fee_MOVA, ',', '') AS DOUBLE) AS mova_fee_value,
    TO_DATE(NULLIF(data_contrato_gerado, ''), 'd/M/y') AS dt_generated_contract,
    TO_DATE(NULLIF(data_contrato_assinado, ''), 'd/M/y') AS dt_signed_contract,
    TO_DATE(NULLIF(data_vencimento, ''), 'd/M/y') AS dt_expiration,
    TO_DATE(NULLIF(data_pagamento_parcela, ''), 'd/M/y') AS dt_installment_payment,
    TO_DATE(NULLIF(data_pagamento, ''), 'd/M/y') AS dt_payment,
    TO_DATE(NULLIF(Data_Liquidacao, ''), 'd/M/y') AS dt_settle,
    TO_TIMESTAMP(NULLIF(created_at, ''), 'y-M-d H:m:s') AS ts_created_at
FROM
    datalake_gsheets_raw.mova_lra_owners
