SELECT
    ticket AS id_ticket,
	proposta AS id_propose,
	nome_do_analista AS analyst_name,
    qual_o_tipo_de_rescisao AS termination_type,
    o_processo_foi_aderente AS was_adherent,
    qual_a_causa_raiz_identificada AS root_cause,
    houve_prejuizo_por_erro_de_processo AS loss_due_process_error,
    se_houve_prejuizo_ocasionado_por_processo_qual_o_valor AS loss_amount_due_process_error,
    houve_prejuizo_ocasionado_por_excecoes AS loss_due_exception,
    se_houve_prejuizo_ocasionado_por_excecoes_qual_o_valor AS loss_amount_due_exception,
    houve_prejuizo_relacionado_a_produto AS loss_due_product,
    se_houve_prejuizo_ocasionado_por_produto_qual_o_valor AS loss_amount_due_product,
    houve_prejuizo_financeiro AS financial_loss,
    qual_o_valor_que_impacta_como_prejuizo_final AS financial_loss_amount,
    pontuacao AS score,
    nota AS grade,
    prejuizo_financeiro AS value_financial_loss,
    contestado AS contested,
    erro_critico AS critical_error,
    1_analista_e_preciso_amavel_cortes_integro_ou_empatico_com_o_parceiro_ AS analyst_is_polite,
    2_analista_atende_prontamente_pedidosolicitacao_do_parceiro_quando_tem_esta_possibilidade AS analyst_attends_requests,
    3_analista_mantem_a_calma_com_o_parceiro_quando_o_mesmo_discorda_de_alguma_informacao AS analyst_maintains_calm_with_the_partner,
    1_analista_fala_bem_ou_concorda_com_citacao_positiva_sobre_a_quintocredconcorrentecolaboradorclientes_ou_parceiros AS analyst_agrees_with_positive_citation,
    2_analista_faz_comentariosorientacoes_devidas_e_eticas_ao_parceiro AS analyst_makes_ethical_comments,
    3_analista_afirma_obrigacao_ou_direito_previsto_em_contrato AS analyst_affirms_foreseen_items_in_contract,
    4_analista_se_atenta_aos_dados_pessoais_de_outros_clientes_e_ou_parceiros_nao_infligindo_a_lgpd AS analyst_not_inflicting_lgpd,
    5_analista_passa_informacoes_veridicas_sobre_o_produtoempresa AS analyst_passes_true_information,
    1_solucao_do_atendimento_tem_valores_corretos_nao_causando_prejuizo_financeiro_para_a_quintocred AS service_solution_has_correct_values_quintocred,
    2_solucao_do_atendimento_tem_valores_corretos_nao_causando_prejuizo_financeiro_para_o_parceiro AS service_solution_has_correct_values_partner,
    3_solucao_do_atendimento_segue_o_fluxo_desenhado_no_processo_nao_impactando_no_sla_para_resolucao AS service_solution_follows_flow,
    data AS dt_monitoring,
    carimbo_de_datahora AS ts_form
FROM
    datalake_gsheets_raw.quintocred_termination_form
