SELECT
    NULLIF(id_proposta,'') AS id_propose,
    NULLIF(id_da_imobiliaria_,'') AS id_broker,
    NULLIF(_ticket_rescisao_,'') AS id_ticket_termination,
    NULLIF(inquilino,'') AS tenant,
    NULLIF(cpf,'') AS document,
    NULLIF(status_contrato,'') AS status_contract,
    NULLIF(_status_,'') AS status,
    NULLIF(imobiliaria_,'') AS broker_name,
    NULLIF(responsavel,'') AS responsible_name,
    NULLIF(_motivo_,'') AS reason,
    NULLIF(_historico_,'') AS history_comment,
    NULLIF(_enviado_exoneracao_,'') AS exoneration_sent,
    NULLIF(_prazo_exoneracao_,'') AS exoneration_deadline,
    NULLIF(exoneracao,'') AS status_exoneration,
    NULLIF(_procuracao_,'') AS status_power_of_attorney,
    NULLIF(contrato_adm,'') AS status_adm_contract,
    NULLIF(_rg_locador,'') AS status_document_renter,
    NULLIF(analista_backoffice,'') AS backoffice_analyst_name,
    NULLIF(_ativo_evic_,'') AS is_eviction_active,
    NULLIF(_obs_pretombamento_,'') AS pre_eviction_comment,
    NULLIF(status_evic,'') AS status_eviction,
    NULLIF(status_pretombamento,'') AS status_pre_eviction,
    TO_DATE(_suspensao_, 'dd/MM/yyyy') AS dt_suspension,
    TO_DATE(liberacao, 'dd/MM/yyyy') AS dt_release,
    TO_DATE(_data_de_envio_, 'dd/MM/yyyy') AS dt_sent,
    TO_DATE(data_recebimento_exoneracao, 'dd/MM/yyyy') AS dt_exoneration_received,
    TO_DATE(data_recebimento_prcuracao, 'dd/MM/yyyy') AS dt_power_of_attorney_received,
    TO_DATE(data_recebimento_contrato_de_adm, 'dd/MM/yyyy') AS dt_adm_contract_received,
    TO_DATE(data_recebimento_rg_locador, 'dd/MM/yyyy') AS dt_document_renter_received,
    TO_DATE(data_de_movimentacao_, 'dd/MM/yyyy') AS dt_movement,
    ts_load
FROM
    datalake_gsheets_raw.quintocred_pre_evictions
