SELECT
    ticket AS id_ticket,
	proposta AS id_propose,
	nome_do_analista AS analyst_name,
    qual_o_tipo_de_acionamento AS termination_type,
    o_processo_foi_aderente AS was_adherent,
    qual_a_causa_raiz_identificada AS root_cause,
    houve_prejuizo_por_erro_de_processo AS loss_due_process_error,
    se_houve_prejuizo_ocasionado_por_processo_qual_o_valor AS loss_amount_due_process_error,
    houve_prejuizo_ocasionado_por_excecoes AS loss_due_exception,
    qual_o_valor_que_impacta_como_prejuizo_final AS final_loss_amount,
    houve_prejuizo_relacionado_a_produto AS loss_due_product,
    se_houve_prejuizo_ocasionado_por_produto_qual_o_valor AS loss_amount_due_product,
    houve_prejuizo_financeiro AS financial_loss,
    se_houve_prejuizo_ocasionado_por_excecoes_qual_o_valor AS loss_amount_due_exception,
    pontuacao AS score,
    relato AS report,
    nota AS grade,
    valor_corrigido AS corrected_amount,
    prejuizo_financeiro AS value_financial_loss,
    contestado AS contested,
    erro_critico AS critical_error,
    data AS dt_monitoring,
    carimbo_de_datahora AS ts_form
FROM
    datalake_gsheets_raw.quintocred_claim_form
