SELECT
    id_ticket,
	id_proposta AS id_propose,
	nome_do_analista AS analyst_name,
    tipo_do_acionamento AS termination_type,
    nao_conformidade_em_entregamos_backoffice_ AS non_compliance_deliver_backoffice,
    nao_conformidade_em_entregamos_acionamento AS non_compliance_deliver_activation,
    nao_conformidade_em_existimos_pelo_cliente_retorno_ao_cliente AS non_compliance_client_return,
    nao_conformidade_em_existimos_pelo_cliente_eficiencia AS non_compliance_efficiency,
    nao_conformidade_em_comunicacao_comunicacao_escrita AS non_compliance_written_communication,
    nao_conformidade_em_comunicacao_registro_de_nota_interna AS non_compliance_internal_note,
    nao_conformidade_em_comunicacao_macro_ AS non_compliance_macro_communication,
    erro_critico_postura_inadequada AS critical_error_inadequate_posture,
    erro_critico_erro_critico_de_solucao AS critical_error_solution,
    erro_critico_falta_de_etica AS critical_error_lack_of_ethics,
    feedback,
    1_neste_atendimento_foi_identificado_alguma_divergencia_no_complemento_do_endereco AS divergence_identified_address_complement,
    2_houve_aprovacao_do_acionamento_faltando_algum_documento AS approval_of_activation_missing_document,
    3_qual_a_satisfacao_do_cliente AS customer_satisfaction,
    relato AS report,
    4_o_processo_foi_aderente AS was_adherent,
    qual_a_causa_raiz AS root_cause,
    houve_prejuizo_financeiro_para_quintocred AS loss_to_quintocred,
    se_houve_prejuizo_financeiro_qual_o_valor AS loss_amount_to_quintocred,
    houve_prejuizo_por_erro_de_processo AS loss_due_process_error,
    se_houve_prejuizo_ocasionado_por_processo_qual_o_valor AS loss_amount_due_process_error,
    houve_prejuizo_ocasionado_por_excecoes AS loss_due_exception,
    se_houve_prejuizo_ocasionado_por_excecoes_qual_o_valor AS loss_amount_due_exception,
    ha_suspeita_de_fraude AS suspected_fraud,
    houve_prejuizo_relacionado_a_produto AS loss_due_product,
    se_houve_prejuizo_relacionado_a_produto_qual_o_valor AS loss_amount_due_product,
    boleto_sem_a_data_e_referencia AS bill_without_date_and_reference,
    entregamos AS delivered,
    existimos_pelo_cliente AS exist_for_the_client,
    comunicacao AS communication,
    erro_critico AS critical_error,
    nota_final AS final_rate,
    prejuizo_financeiro AS financial_loss_amount,
    processo AS process,
    excecoes AS exception,
    contestado AS contested,
    produto AS product,
    data_monitoria AS dt_monitoring,
    carimbo_de_datahora AS ts_form
FROM
    datalake_gsheets_raw.quintocred_aux_form
