SELECT
    NULLIF(Executivo, '') AS executive,
    NULLIF(Team, '') AS team,
    NULLIF(Portfolio, '') AS portfolio,
    CAST(NULLIF(Contatos_Efetivos_Target, '') AS FLOAT) AS effective_contacts_target,
    CAST(NULLIF(Contatos_Efetivos_Actual, '') AS FLOAT) AS effective_contacts_actual,
    CAST(NULLIF(Unique_Effective_Contact_Target, '') AS FLOAT) AS unique_effective_contact_target,
    CAST(NULLIF(Unique_Effective_Contact_Actual, '') AS FLOAT) AS unique_effective_contact_actual,
    CAST(NULLIF(Total_Brokers_wES_Target, '') AS FLOAT) AS total_brokers_wes_target,
    CAST(NULLIF(MonthlyActiveBrokers_Target, '') AS FLOAT) AS monthly_active_brokers_target,
    CAST(NULLIF(Evaluation_Started_Target, '') AS FLOAT) AS evaluation_started_target,
    CAST(NULLIF(Credit_Approved_Target, '') AS FLOAT) AS credit_approved_target,
    CAST(NULLIF(New_Contracts_Target, '') AS FLOAT) AS new_contracts_target,
    CAST(NULLIF(ES2NC_Target, '') AS FLOAT) AS es2nc_target,
    CAST(NULLIF(Registrations_Target, '') AS FLOAT) AS registrations_target,
    CAST(NULLIF(Activations_Target, '') AS FLOAT) AS activations_target,
    CAST(NULLIF(Activations_actual, '') AS FLOAT) AS activations_actual,
    CAST(NULLIF(Calls_Target, '') AS FLOAT) AS calls_target,
    CAST(NULLIF(Calls_actual, '') AS FLOAT) AS calls_actual,
    NULLIF(Online_time_Target, '') AS online_time_target,
    NULLIF(Online_time_actual, '') AS online_time_actual,
    CAST(NULLIF(Appointments_Target, '') AS FLOAT) AS appointments_target,
    CAST(NULLIF(Appointments_actual, '') AS FLOAT) AS appointments_actual,
    CAST(NULLIF(Opportunities_Target, '') AS FLOAT) AS opportunities_target,
    CAST(NULLIF(Opportunities_actual, '') AS FLOAT) AS opportunities_actual,
    NULLIF(Date, '') AS date,
    NULLIF(Month, '') AS month,
    NULLIF(Year, '') AS year
FROM
    datalake_gsheets_raw.quintocred_executives_targets_commercial
