SELECT
    processo_id AS id_process,
    id_imob AS id_broker,
    parte_contraria_id AS id_opposing_party,
    id_status,
    cpf_cnpj,
    numero_do_contrato AS contract_number,
    numero_do_processo AS process_number,
    parte_contraria_nome AS name_opposing_party,
    processo_parte AS party_process,
    status,
    acao AS action_type,
    processo_classificacao AS process_class_type,
    processo_tipo_de_justica AS process_justice_type,
    escritorio_externo_responsavel AS external_office_responsible,
    fase AS process_fase,
    time AS team,
    estado AS state,
    motivo AS process_motive,
    nome_imob AS broker_name,
    nome_comercial_imob As broker_commercial_name,
    volume_pauta AS size_pauta,
    volume_andamento AS size_progress,
    lead_time_status AS status_lead_time,
    vol_promessa AS promise_volume,
    vol_promessa_mes AS promise_per_month_volume,
    contratos_ativos AS active_contracts,
    null AS contacts_per_month,
    lt_finalizacao AS finalization_batch,
    null AS has_progress,
    null AS has_pauta,
    exoneracao AS is_dismissal,
    arquivamento AS is_archived,
    em_analise AS has_analysis,
    finalizado AS is_finished,
    suspenso AS is_suspended,
    ag_retorno_imob AS has_broker_return,
    distrib_escrit AS has_written_distribution,
    lt_finalizacao AS lt_finalization,
    lt_estoque_retirar AS lt_inventory_remove,
    exoneracao AS exoneration,
    registro_x_ag_exoner AS record_x_ag_exoneration,
    em_analise AS under_analysis,
    ag_retorno_imob AS ag_return_imob,
    registro_x_tombado_assessoria AS record_x_seized_advisory,
    tombamento_escr AS registration_written,
    pre_tombamento AS pre_registration,
    tomb_escr_x_distribuido AS registration_written_x_distributed,
    suspenso_x_distrib_escrit AS suspended_x_distributed_written,
    registro_x_distrib_escrit AS record_x_distributed_written,
    liminar_ind AS preliminary_ind,
    liminar_def AS preliminary_def,
    citacao_positiva AS positive_notification,
    citacao_negativa AS negative_notification,
    citacao_neg_abandono AS negative_notification_abandonment,
    mandado_exp_imissao AS mandate_exp_imission,
    mandado_exp_coercitivo AS mandate_exp_coercive,
    lt_registro_x_finalizacao AS lt_record_x_finalization,
    distribuido_x_limin_ind AS distributed_x_preliminary_ind,
    distribuido_x_limin_def AS distributed_x_preliminary_def,
    limin_ind_x_limin_def AS preliminary_ind_x_preliminary_def,
    liminar_x_mandado AS preliminary_x_mandate,
    limin_def_x_citacao_pos AS preliminary_def_x_positive_notification,
    mandado_x_citacao AS mandate_x_notification,
    citacao_neg_x_citacao_pos AS negative_notification_x_positive_notification,
    citacao_neg_x_finalizacao AS negative_notification_x_finalization,
    citacao_pos_x_finalizacao AS positive_notification_x_finalization,
    mandado_imissao_x_finalizacao AS mandate_imission_x_finalization,
    mandado_coercitivo_x_finalizacao AS mandate_coercive_x_finalization,
    lt_divida_x_tombamento AS lt_debt_x_registration,
    divida_vigente_target AS current_debt_target,
    distrib_arbitral AS arbitral_distribution,
    cit_n_arbitral AS arbitral_notification,
    sentenca_arbitral AS arbitral_sentence,
    registro_cs_arbitral AS arbitral_cs_record,
    decisao_intimacao_arbitral AS arbitral_notification_decision,
    intimacao_cs_arbitral AS arbitral_cs_notification,
    impugnacao_cs_arbitral AS arbitral_cs_objection,
    registro_x_distr_arbitral AS record_x_arbitral_distribution,
    distr_arbitral_x_sentenca_arbitral AS arbitral_distribution_x_arbitral_sentence,
    sentenca_arbitral_x_distr_escritorio AS arbitral_sentence_x_distributed_office,
    distr_escritorio_x_mandado AS distributed_office_x_mandate,
    distr_escritorio_x_decisao_intimacao AS distributed_office_x_notification_decision,
    carteira_iaf AS iaf_portfolio,
    escritorio_legado_atual AS current_legacy_office,
    valor_atual AS current_value,
    valor_original AS original_value,
    valor_pago AS paid_value,
    valor_pendente AS pending_value,
    valor_pacote AS package_value,
    TO_DATE(exoneracao_data, 'yyyy-MM-dd') AS dt_exoneration,
    TO_DATE(ag_retorno_imob_data, 'yyyy-MM-dd') AS dt_ag_return_imob,
    TO_DATE(tombamento_escr_data, 'yyyy-MM-dd') AS  dt_registration_written,
    TO_DATE(pre_tombamento_data, 'yyyy-MM-dd') AS  dt_pre_registration,
    TO_DATE(liminar_ind_data, 'yyyy-MM-dd') AS  dt_preliminary_ind,
    TO_DATE(liminar_def_data, 'yyyy-MM-dd') AS  dt_preliminary_def,
    TO_DATE(mandado_exp_data, 'yyyy-MM-dd') AS  dt_mandate_exp,
    TO_DATE(citacao_positiva_data, 'yyyy-MM-dd') AS  dt_positive_notification,
    TO_DATE(citacao_negativa_abandono_data, 'yyyy-MM-dd') AS  dt_negative_notification_abandonment,
    TO_DATE(mandado_exp_imissao_data, 'yyyy-MM-dd') AS  dt_mandate_exp_imission,
    TO_DATE(mandado_exp_coercitivo_data, 'yyyy-MM-dd') AS  dt_mandate_exp_coercive,
    TO_DATE(distrib_arbitral_data, 'yyyy-MM-dd') AS  dt_arbitral_distribution,
    TO_DATE(cit_n_arbitral_data, 'yyyy-MM-dd') AS  dt_arbitral_notification,
    TO_DATE(sentenca_arbitral_data, 'yyyy-MM-dd') AS  dt_arbitral_sentence,
    TO_DATE(registro_cs_arbitral_data, 'yyyy-MM-dd') AS  dt_arbitral_cs_record,
    TO_DATE(decisao_intimacao_arbitral_data, 'yyyy-MM-dd') AS  dt_arbitral_notification_decision,
    TO_DATE(intimacao_cs_arbitral_data, 'yyyy-MM-dd') AS  dt_arbitral_cs_notification,
    TO_DATE(impugnacao_cs_arbitral_data, 'yyyy-MM-dd') AS  dt_arbitral_cs_objection,
    TO_DATE(data_registro_ajustada, 'yyyy-MM-dd') AS dt_adjusted_record,
    TO_DATE(apto_reanalise_data, 'yyyy-MM-dd') AS dt_reanalisys_allowed,
    TO_DATE(suspenso_data, 'yyyy-MM-dd') AS dt_suspended,
    TO_DATE(data_status, 'yyyy-MM-dd') AS dt_status,  
    TO_DATE(ag_retorno_imob_data, 'yyyy-MM-dd') AS dt_broker_return,
    TO_DATE(em_analise_data, 'yyyy-MM-dd') AS dt_analysis,
    TO_DATE(exoneracao_data, 'yyyy-MM-dd') AS dt_dismissal,
    CAST(NULL AS DATE) AS dt_finalized,
    TO_DATE(citacao_neg_data, 'yyyy-MM-dd') AS dt_negative_citation,
    TO_DATE(data_registrado, 'yyyy-MM-dd') AS dt_register,
    TO_DATE(distribuicao, 'yyyy-MM-dd') AS dt_distribution,
    ts_load
FROM
    datalake_gsheets_raw.quintocred_process_evictions
