SELECT
    processo_id AS id_process,
    id_externo AS id_external,
    id_imob AS id_broker,
    parte_contraria_id AS id_opposing_party,
    id_status,
    grupo_id AS id_group,
    numero_do_contrato AS contract_number,
    numero_do_processo AS process_number,
    empresa AS company,
    parte_contraria_nome AS name_opposing_party,
    processo_parte AS party_process,
    tipo_de_parte AS type_party_process,
    status,
    resumo AS summary,
    grupo AS group,
    acao AS action_type,
    processo_classificacao AS process_class_type,
    processo_tipo_de_justica AS process_justice_type,
    escritorio_externo_responsavel AS external_office_responsible,
    fase AS process_fase,
    time AS team,
    cpf_cnpj,
    estado AS state,
    pais AS country,
    motivo AS process_motive,
    nome_imob AS broker_name,
    nome_comercial_imob As broker_commercial_name,
    volume_pauta AS size_pauta,
    volume_andamento AS size_progress,
    lead_time_status AS status_lead_time,
    vol_promessa AS promise_volume,
    vol_promessa_mes AS promise_per_month_volume,
    contratos_ativos AS active_contracts,
    vol_contato_pos_mes AS contacts_per_month,
    lt_finalizacao AS finalization_batch,
    existe_andamento AS has_progress,
    existe_pauta AS has_pauta,
    exoneracao AS is_dismissal,
    arquivamento AS is_archived,
    em_analise AS has_analysis,
    finalizado AS is_finished,
    suspenso AS is_suspended,
    ag_retorno_imob AS has_broker_return,
    distrib_escrit AS has_written_distribution,
    TO_DATE(apto_reanalise_data, 'yyyy-MM-dd') AS dt_reanalisys_allowed,
    TO_DATE(suspenso_data, 'yyyy-MM-dd') AS dt_suspended,
    TO_DATE(data_status, 'yyyy-MM-dd') AS dt_status,
    TO_DATE(distrib_escrit_data, 'yyyy-MM-dd') AS dt_written_distribution,
    TO_DATE(ag_retorno_imob_data, 'yyyy-MM-dd') AS dt_broker_return,
    TO_DATE(em_analise_data, 'yyyy-MM-dd') AS dt_analysis,
    TO_DATE(exoneracao_data, 'yyyy-MM-dd') AS dt_dismissal,
    TO_DATE(finalizado_data, 'yyyy-MM-dd') AS dt_finalized,
    TO_DATE(citacao_neg_data, 'yyyy-MM-dd') AS dt_negative_citation,
    TO_DATE(data_pagamento, 'yyyy-MM-dd') AS dt_paid,
    TO_DATE(data_registrado, 'yyyy-MM-dd') AS dt_register,
    TO_DATE(distribuicao, 'yyyy-MM-dd') AS dt_distribution,
    ts_load
FROM
    datalake_gsheets_raw.quintocred_process_evictions
