SELECT
    NULLIF(id_proposta,'') AS id_propose,
    NULLIF(id_da_imobiliaria,'') AS id_broker,
    NULLIF(ticket_rescisao,'') AS id_ticket_termination,
    NULLIF(inquilino,'') AS tenant,
    NULLIF(cpf,'') AS document,
    NULLIF(status_contrato,'') AS status_contract,
    NULLIF(status,'') AS status,
    NULLIF(imobiliaria,'') AS broker_name,
    NULLIF(responsavel,'') AS responsible_name,
    NULLIF(motivo,'') AS reason,
    NULLIF(historico,'') AS history_comment,
    NULLIF(enviado_exoneracao,'') AS exoneration_sent,
    NULLIF(prazo_exoneracao,'') AS exoneration_deadline,
    NULLIF(exoneracao,'') AS status_exoneration,
    NULLIF(procuracao,'') AS status_power_of_attorney,
    NULLIF(contrato_adm,'') AS status_adm_contract,
    NULLIF(rg_locador,'') AS status_document_renter,
    NULLIF(analista_backoffice,'') AS backoffice_analyst_name,
    NULLIF(ativo_evic,'') AS is_eviction_active,
    NULLIF(obs_pretombamento,'') AS pre_eviction_comment,
    NULLIF(status_evic,'') AS status_eviction,
    NULLIF(status_pretombamento,'') AS status_pre_eviction,
    TO_DATE(suspensao, 'dd/MM/yyyy') AS dt_suspension,
    TO_DATE(liberacao, 'dd/MM/yyyy') AS dt_release,
    TO_DATE(data_de_envio, 'dd/MM/yyyy') AS dt_sent,
    TO_DATE(data_recebimento_exoneracao, 'dd/MM/yyyy') AS dt_exoneration_received,
    TO_DATE(data_recebimento_prcuracao, 'dd/MM/yyyy') AS dt_power_of_attorney_received,
    TO_DATE(data_recebimento_contrato_de_adm, 'dd/MM/yyyy') AS dt_adm_contract_received,
    TO_DATE(data_recebimento_rg_locador, 'dd/MM/yyyy') AS dt_document_renter_received,
    TO_DATE(data_de_movimentacao, 'dd/MM/yyyy') AS dt_movement,
    ts_load
FROM
    datalake_gsheets_raw.quintocred_pre_evictions
