SELECT
    CAST(evaluation_started AS INTEGER) AS evaluation_started,
    CAST(credit_approved AS INTEGER) AS credit_approved,
    CAST(new_contract AS INTEGER) AS new_contract,
    CAST(ended_contract AS INTEGER) AS ended_contract,
    CAST(ongoing_contract AS INTEGER) AS ongoing_contract,
    CAST(gmv_new_contract AS INTEGER) AS gmv_new_contract,
    CAST(gmv_ongoing_contract AS INTEGER) AS gmv_ongoing_contract,
    CAST(gmv_ended_contract AS INTEGER) AS gmv_ended_contract,
    CAST(avg_ticket_new_contract AS INTEGER) AS avg_ticket_new_contract,
    CAST(avg_ticket_ended_contract AS INTEGER) AS avg_ticket_ended_contract,
    CAST(avg_ticket_ongoing_contract AS INTEGER) AS avg_ticket_ongoing_contract,
    activation_fee,
    CAST(revenue_new_contract AS INTEGER) AS revenue_new_contract,
    CAST(revenue_ongoing_contract AS INTEGER) AS revenue_ongoing_contract,
    take_rate_new_contract,
    take_rate_ongoing_contract,
    CAST(monthly_brokers_w_evaluation_accumulated AS INTEGER) AS monthly_brokers_w_evaluation_accumulated,
    CAST(daily_brokers_w_evaluation AS INTEGER) AS daily_brokers_w_evaluation,
    CAST(monthly_active_brokers_accumulated AS INTEGER) AS monthly_active_brokers_accumulated,
    CAST(daily_active_brokers AS INTEGER) AS daily_active_brokers,
    CAST(total_active_brokers_w_evaluation_accumulated AS INTEGER) AS total_active_brokers_w_evaluation_accumulated,
    CAST(daily_total_active_brokers_w_evaluation AS INTEGER) AS daily_total_active_brokers_w_evaluation,
    CAST(total_active_brokers AS INTEGER) AS total_active_brokers,
    CAST(first_active_brokers AS INTEGER) AS first_active_brokers,
    CAST(pre_active_brokers_w_evaluation AS INTEGER) AS pre_active_brokers_w_evaluation,
    CAST(claims_total AS INTEGER) AS claims_total,
    CAST(claims_active AS INTEGER) AS claims_active,
    CAST(claims_termination AS INTEGER) AS claims_termination,
    CAST(avg_ticket_claims_total AS INTEGER) AS avg_ticket_claims_total,
    CAST(avg_ticket_claims_active AS INTEGER) AS avg_ticket_claims_active,
    CAST(avg_ticket_claims_termination AS INTEGER) AS avg_ticket_claims_termination,
    CAST(claims_created_tickets AS INTEGER) AS claims_created_tickets,
    CAST(collections_total_projected AS INTEGER) AS collections_total_projected,
    CAST(collections_active_projected AS INTEGER) AS collections_active_projected,
    CAST(collections_termination_projected AS INTEGER) AS collections_termination_projected,
    CAST(evictions_solved_cases AS INTEGER) AS evictions_solved_cases,
    CAST(evictions_new_cases AS INTEGER) AS evictions_new_cases,
    CAST(evictions_ongoing_cases AS INTEGER) AS evictions_ongoing_cases,
    month,
    quarter,
    halfyear AS half_year,
    year,
    TO_DATE(date, 'mm-dd-yyyy') AS dt_reference,
    TO_DATE(week_start, 'mm-dd-yyyy') AS dt_week
FROM
    datalake_gsheets_raw.quintocred_coincident_targets
