SELECT
    CAST(proposal_created AS INTEGER) AS proposal_created,
    CAST(evaluation_started AS INTEGER) AS evaluation_started,
    CAST(credit_approved AS INTEGER) AS credit_approved,
    CAST(contract_started AS INTEGER) AS contract_started,
    CAST(active_contract_started AS INTEGER) AS active_contract_started,
    CAST(ended_contracts AS INTEGER) AS ended_contracts,
    CAST(ongoing_contracts AS INTEGER) AS ongoing_contracts,
    CAST(gmv_new_contracts AS INTEGER) AS gmv_new_contracts,
    CAST(gmv_ongoing_contracts AS INTEGER) AS gmv_ongoing_contracts,
    CAST(gmv_ended_contracts AS INTEGER) AS gmv_ended_contracts,
    CAST(late_payments_fee AS INTEGER) AS late_payments_fee,
    CAST(average_ticket_new_contracts AS INTEGER) AS average_ticket_new_contracts,
    CAST(average_ticket_ended_contracts AS INTEGER) AS average_ticket_ended_contracts,
    CAST(average_ticket_ongoing_contracts AS INTEGER) AS average_ticket_ongoing_contracts,
    CAST(activation_fee AS INTEGER) AS activation_fee,
    CAST(revenue_new_contracts AS INTEGER) AS revenue_new_contracts,
    CAST(revenue_ongoing_contracts AS INTEGER) AS revenue_ongoing_contracts,
    CAST(take_rate_new_contracts AS INTEGER) AS take_rate_new_contracts,
    CAST(take_rate_ongoing_contracts AS INTEGER) AS take_rate_ongoing_contracts,
    CAST(brokers_with_proposal AS INTEGER) AS brokers_with_proposal,
    CAST(monthly_active_brokers AS INTEGER) AS monthly_active_brokers,
    CAST(total_brokers_with_proposal AS INTEGER) AS total_brokers_with_proposal,
    CAST(total_brokers AS INTEGER) AS total_brokers,
    CAST(first_active AS INTEGER) AS first_active,
    CAST(pre_active_brokers_with_proposal AS INTEGER) AS pre_active_brokers_with_proposal,
    CAST(evaluation_started_total_brokers AS INTEGER) AS evaluation_started_total_brokers,
    CAST(evaluation_started_pre_active_bokers AS INTEGER) AS evaluation_started_pre_active_bokers,
    CAST(claims AS INTEGER) AS claims,
    CAST(avg_ticket_claims AS INTEGER) AS avg_ticket_claims,
    CAST(avg_ticket_active_claims AS INTEGER) AS avg_ticket_active_claims,
    CAST(avg_ticket_termination_claims AS INTEGER) AS avg_ticket_termination_claims,
    CAST(created_tickets AS INTEGER) AS created_tickets,
    CAST(collections AS INTEGER) AS collections,
    CAST(collections_active_claims AS INTEGER) AS collections_active_claims,
    CAST(collections_termination_claims AS INTEGER) AS collections_termination_claims,
    CAST(evictions AS INTEGER) AS evictions,
    CAST(monthly_active_brokers_day AS INTEGER) AS monthly_active_brokers_day,
    CAST(total_brokers_day AS INTEGER) AS total_brokers_day,
    CAST(evictions_new_cases AS INTEGER) AS evictions_new_cases,
    CAST(evictions_ongoing_cases AS INTEGER) AS evictions_ongoing_cases,
    CAST(monthly_brokers_with_proposal AS INTEGER) AS monthly_brokers_with_proposal,
    CAST(monthly_brokers_w_proposal_day AS INTEGER) AS monthly_brokers_w_proposal_day,
    weekday,
    workdays,
    collections_ops,
    month,
    quarter,
    half_year,
    year,
    holiday AS is_holiday,
    work_day AS is_work_day,
    true AS is_true,
    DATE(date) AS dt_reference,
    DATE(week_start) AS dt_week
FROM
    datalake_gsheets_raw.quintocred_targets
