SELECT
    NULLIF(Executivo, '') AS executive,
    NULLIF(Team, '') AS team,
    NULLIF(Portfolio, '') AS group,
    CAST(NULLIF(Contatos_Efetivos_Target, '') AS FLOAT) AS target_contatos,
    CAST(NULLIF(Contatos_Efetivos_Actual, '') AS FLOAT) AS effective_contacts,
    CAST(NULLIF(Unique_Effective_Contact_Target, '') AS FLOAT) AS target_unique_effective_contact,
    CAST(NULLIF(Unique_Effective_Contact_Actual, '') AS FLOAT) AS unique_effective_contact,
    CAST(NULLIF(Total_Brokers_wES_Target, '') AS FLOAT) AS brokers_wes,
    CAST(NULLIF(MonthlyActiveBrokers_Target, '') AS FLOAT) AS monthly_active_brokers,
    CAST(NULLIF(Evaluation_Started_Target, '') AS FLOAT) AS target_evaluation_started,
    CAST(NULLIF(Credit_Approved_Target, '') AS FLOAT) AS target_credit_approved,
    CAST(NULLIF(New_Contracts_Target, '') AS FLOAT) AS target_new_contract,
    CAST(NULLIF(ES2NC_Target, '') AS FLOAT) AS es2nc_target,
    CAST(NULLIF(Registrations_Target, '') AS FLOAT) AS registrations,
    CAST(NULLIF(Activations_Target, '') AS FLOAT) AS target_activations,
    CAST(NULLIF(Activations_actual, '') AS FLOAT) AS activations,
    CAST(NULLIF(Calls_Target, '') AS FLOAT) AS calls_target,
    CAST(NULLIF(Calls_actual, '') AS FLOAT) AS calls,
    NULLIF(Online_time_Target, '') AS online_time_target,
    NULLIF(Online_time_actual, '') AS online_time,
    CAST(NULLIF(Appointments_Target, '') AS FLOAT) AS appointments_target,
    CAST(NULLIF(Appointments_actual, '') AS FLOAT) AS appointments,
    CAST(NULLIF(Opportunities_Target, '') AS FLOAT) AS opportunities_target,
    CAST(NULLIF(Opportunities_actual, '') AS FLOAT) AS opportunities,
    NULLIF(Date, '') AS date,
    NULLIF(Month, '') AS month,
    NULLIF(Year, '') AS year
FROM
    datalake_gsheets_raw.quintocred_executives_targets_commercial
