
SELECT
    COALESCE(id_booking, -1) AS sk_booking,
    COALESCE(id_sale_flow, -1) AS sk_sale_flow,
    COALESCE(id_house, -1) AS sk_house,
    COALESCE(id_region, -1) AS sk_region,
    COALESCE(id_business_unit, -1) AS sk_business_unit,
    COALESCE(sk_company_supply, -1) AS sk_company_supply,
    COALESCE(sk_company_demand, -1) AS sk_company_demand,
    COALESCE(id_agent, -1) AS sk_agent,
    COALESCE(id_user_agent, -1) AS sk_user_agent,
    COALESCE(id_user_en, -1) AS sk_user_en,
    COALESCE(id_fixed_agent, -1) AS sk_fixed_agent,
    COALESCE(id_buyer, -1) AS sk_buyer,
    COALESCE(id_seller, -1) AS sk_seller,
    COALESCE(id_user_creation, -1) AS sk_user_creation,
    COALESCE(id_user_cancelation, -1) AS sk_user_cancelation,
    COALESCE(id_visit, -1) AS sk_visit,
    visit_code AS sk_visit_code,
    COALESCE(id_offer, -1) AS sk_offer,
    COALESCE(id_agent_booking_review, -1) AS sk_agent_booking_review,
    COALESCE(id_buyer_booking_review, -1) AS sk_buyer_booking_review,
    COALESCE(BIGINT(DATE_FORMAT(ts_booking_created, 'yyyyMMdd')), -1) AS sk_booking_created_date,
    COALESCE(BIGINT(DATE_FORMAT(ts_visit, 'yyyyMMdd')), -1) AS sk_visit_date,
    COALESCE(BIGINT(DATE_FORMAT(ts_visit_canceled, 'yyyyMMdd')), -1) AS sk_visit_canceled_date,
    COALESCE(BIGINT(DATE_FORMAT(ts_visit_completed, 'yyyyMMdd')), -1) AS sk_visit_completed_date,
    COALESCE(BIGINT(DATE_FORMAT(ts_visit_follow_up, 'yyyyMMdd')), -1) AS sk_visit_follow_up_date,
    COALESCE(BIGINT(DATE_FORMAT(ts_agent_review_rating, 'yyyyMMdd')), -1) AS sk_agent_review_rating_date,
    COALESCE(BIGINT(DATE_FORMAT(ts_buyer_review_rating, 'yyyyMMdd')), -1) AS sk_buyer_review_rating_date,
    COALESCE(BIGINT(DATE_FORMAT(ts_visit_checkin, 'yyyyMMdd')), -1) AS sk_visit_checkin_date,
    hub_agent_region,
    is_hub_flow,
    is_house_rented,
    is_virtual_visit,
    days_visit_cancelled_to_visit,
    days_visit_booked_to_visit,
    days_visit_booked_to_visit_cancelled,
    days_visit_booked_to_visit_completed,
    hours_booking_to_offer,
    hours_visit_to_offer,
    ts_booking_created,
    ts_visit,
    ts_visit_canceled,
    ts_visit_completed,
    ts_visit_follow_up,
    ts_visit_checkin,
    ts_agent_review_rating,
    ts_buyer_review_rating,
    NOW() AS ts_load
FROM
    datalake_sale_visit.sale_visit
