SELECT 
    id,
    database_id AS id_database,
    created_by_fk AS id_user_created,
    changed_by_fk AS id_user_changed,
    table_name,
    main_dttm_col,
    "offset",
    "description",
    is_featured,
    cache_timeout,
    default_endpoint,
    "schema",
    "sql" AS sql_code,
    params,
    perm,
    filter_select_enabled,
    fetch_values_predicate,
    is_sqllab_view,
    template_params,
    schema_perm,
    extra,
    uuid,
    is_managed_externally,
    external_url,
    normalize_columns,
    created_on AS ts_created,
    changed_on AS ts_changed,
    year,
    month,
    day
FROM datalake_superset_raw.tables
WHERE year = {year} AND month = {month} AND day = {day}