-- Widened to the full PROPERTY payload plus the three derived gestor columns the
-- extraction spreadsheet builds from imoveis_gestores[0] (Gestor principal).
-- identificador_imo, endereco_imo, cidade_imo and estado_imo are legacy aliases kept
-- because downstream consumers already read them.
WITH property_row AS (
    SELECT
        id,
        vendor_natural_key,
        CAST(payload AS STRING) AS payload_json,
        synced_at
    FROM
        datalake_benvi_manager_raw.lake_mirror
    WHERE
        resource_code = 'PROPERTY'
)
SELECT
    id,
    vendor_natural_key AS id_imovel_imo,
    get_json_object(payload_json, '$.imoveis_gestores[0].id_gestor_ges') AS id_gestor_ges,
    get_json_object(payload_json, '$.imoveis_gestores[0].st_nome_ges') AS st_nome_ges,
    get_json_object(payload_json, '$.imoveis_gestores[0].st_email_ges') AS st_email_ges,
    get_json_object(payload_json, '$.st_identificador_imo') AS identificador_imo,
    get_json_object(payload_json, '$.st_endereco_imo') AS endereco_imo,
    get_json_object(payload_json, '$.st_cidade_imo') AS cidade_imo,
    get_json_object(payload_json, '$.st_estado_imo') AS estado_imo,
    get_json_object(payload_json, '$.id_filial_fil') AS id_filial_fil,
    get_json_object(payload_json, '$.st_nome_fil') AS st_nome_fil,
    get_json_object(payload_json, '$.st_identificador_imo') AS st_identificador_imo,
    CAST(get_json_object(payload_json, '$.vl_aluguel_imo') AS DOUBLE) AS vl_aluguel_imo,
    CAST(get_json_object(payload_json, '$.vl_condominio_imo') AS DOUBLE) AS vl_condominio_imo,
    CAST(get_json_object(payload_json, '$.vl_parcelaiptu_imo') AS DOUBLE) AS vl_parcelaiptu_imo,
    get_json_object(payload_json, '$.st_tipo_imo') AS st_tipo_imo,
    get_json_object(payload_json, '$.st_codigoiptu_imo') AS st_codigoiptu_imo,
    get_json_object(payload_json, '$.nm_parcelasiptu_imo') AS nm_parcelasiptu_imo,
    get_json_object(payload_json, '$.nm_txiptuproprietario_imo') AS nm_txiptuproprietario_imo,
    get_json_object(payload_json, '$.nm_txiptuinquilino_imo') AS nm_txiptuinquilino_imo,
    CAST(get_json_object(payload_json, '$.fl_responsavelcondominio_imo') AS INT) AS fl_responsavelcondominio_imo,
    get_json_object(payload_json, '$.st_cep_imo') AS st_cep_imo,
    get_json_object(payload_json, '$.st_endereco_imo') AS st_endereco_imo,
    get_json_object(payload_json, '$.st_bairro_imo') AS st_bairro_imo,
    get_json_object(payload_json, '$.st_complemento_imo') AS st_complemento_imo,
    get_json_object(payload_json, '$.st_cidade_imo') AS st_cidade_imo,
    get_json_object(payload_json, '$.st_estado_imo') AS st_estado_imo,
    get_json_object(payload_json, '$.st_numero_imo') AS st_numero_imo,
    get_json_object(payload_json, '$.st_areautil_imo') AS st_areautil_imo,
    get_json_object(payload_json, '$.st_areatotal_imo') AS st_areatotal_imo,
    get_json_object(payload_json, '$.nm_quartos_imo') AS nm_quartos_imo,
    get_json_object(payload_json, '$.nm_suites_imo') AS nm_suites_imo,
    get_json_object(payload_json, '$.nm_banheiros_imo') AS nm_banheiros_imo,
    get_json_object(payload_json, '$.nm_salas_imo') AS nm_salas_imo,
    get_json_object(payload_json, '$.nm_varandas_imo') AS nm_varandas_imo,
    get_json_object(payload_json, '$.nm_garagens_imo') AS nm_garagens_imo,
    get_json_object(payload_json, '$.nm_piscinas_imo') AS nm_piscinas_imo,
    get_json_object(payload_json, '$.st_codagua_imo') AS st_codagua_imo,
    get_json_object(payload_json, '$.st_codenergia_imo') AS st_codenergia_imo,
    get_json_object(payload_json, '$.st_codgas_imo') AS st_codgas_imo,
    get_json_object(payload_json, '$.st_observacao_imo') AS st_observacao_imo,
    get_json_object(payload_json, '$.st_cartorio_imo') AS st_cartorio_imo,
    get_json_object(payload_json, '$.st_matriculacartorio_imo') AS st_matriculacartorio_imo,
    get_json_object(payload_json, '$.st_cib_imo') AS st_cib_imo,
    get_json_object(payload_json, '$.st_administradora_imo') AS st_administradora_imo,
    get_json_object(payload_json, '$.st_condominio_imo') AS st_condominio_imo,
    CAST(get_json_object(payload_json, '$.fl_responsaveliptu_imo') AS INT) AS fl_responsaveliptu_imo,
    CAST(get_json_object(payload_json, '$.fl_responsavelagua_imo') AS INT) AS fl_responsavelagua_imo,
    get_json_object(payload_json, '$.nm_txaguaproprietario_imo') AS nm_txaguaproprietario_imo,
    get_json_object(payload_json, '$.nm_txaguainquilino_imo') AS nm_txaguainquilino_imo,
    get_json_object(payload_json, '$.tx_locacao_imo') AS tx_locacao_imo,
    get_json_object(payload_json, '$.nm_repassegarantido_imo') AS nm_repassegarantido_imo,
    CAST(get_json_object(payload_json, '$.fl_diafixorepasse_imo') AS INT) AS fl_diafixorepasse_imo,
    CAST(get_json_object(payload_json, '$.fl_status_imo') AS INT) AS fl_status_imo,
    get_json_object(payload_json, '$.tx_adm_imo') AS tx_adm_imo,
    CAST(get_json_object(payload_json, '$.fl_txadmvalorfixo_imo') AS INT) AS fl_txadmvalorfixo_imo,
    CAST(get_json_object(payload_json, '$.fl_txlocacaovalorfixo_imo') AS INT) AS fl_txlocacaovalorfixo_imo,
    get_json_object(payload_json, '$.nm_parcelastxlocacao_imo') AS nm_parcelastxlocacao_imo,
    get_json_object(payload_json, '$.nm_diarepasse_imo') AS nm_diarepasse_imo,
    CAST(get_json_object(payload_json, '$.vl_venda_imo') AS DOUBLE) AS vl_venda_imo,
    get_json_object(payload_json, '$.st_codigosequencial_imo') AS st_codigosequencial_imo,
    get_json_object(payload_json, '$.st_codigocidadedimob_imo') AS st_codigocidadedimob_imo,
    get_json_object(payload_json, '$.st_tipodimob_imo') AS st_tipodimob_imo,
    get_json_object(payload_json, '$.st_identificadorimportacao_imo') AS st_identificadorimportacao_imo,
    get_json_object(payload_json, '$.id_administradora_adm') AS id_administradora_adm,
    get_json_object(payload_json, '$.st_iptugaragem_imo') AS st_iptugaragem_imo,
    get_json_object(payload_json, '$.st_sincrofilial_imo') AS st_sincrofilial_imo,
    CAST(get_json_object(payload_json, '$.fl_split_imo') AS INT) AS fl_split_imo,
    get_json_object(payload_json, '$.id_foto_imo') AS id_foto_imo,
    get_json_object(payload_json, '$.st_codigospu_imo') AS st_codigospu_imo,
    get_json_object(payload_json, '$.id_gestor_imo') AS id_gestor_imo,
    get_json_object(payload_json, '$.st_txlixo_imo') AS st_txlixo_imo,
    get_json_object(payload_json, '$.st_codbombeiro_imo') AS st_codbombeiro_imo,
    get_json_object(payload_json, '$.id_condominio_cond') AS id_condominio_cond,
    get_json_object(payload_json, '$.st_avaliacao_imo') AS st_avaliacao_imo,
    get_json_object(payload_json, '$.st_detalhes_imo') AS st_detalhes_imo,
    get_json_object(payload_json, '$.nm_meseslocacao_imo') AS nm_meseslocacao_imo,
    get_json_object(payload_json, '$.tx_anual_imo') AS tx_anual_imo,
    get_json_object(payload_json, '$.st_destinacao_imo') AS st_destinacao_imo,
    get_json_object(payload_json, '$.nm_mesesisencaomulta_imo') AS nm_mesesisencaomulta_imo,
    CAST(get_json_object(payload_json, '$.fl_imoveltombado_imo') AS INT) AS fl_imoveltombado_imo,
    CAST(get_json_object(payload_json, '$.fl_tipoisencao_imo') AS INT) AS fl_tipoisencao_imo,
    CAST(get_json_object(payload_json, '$.fl_admcondominio_imo') AS INT) AS fl_admcondominio_imo,
    CAST(get_json_object(payload_json, '$.fl_contapessoa_imo') AS INT) AS fl_contapessoa_imo,
    COALESCE(
        TO_DATE(SUBSTR(get_json_object(payload_json, '$.dt_contapessoa_imo'), 1, 10), 'MM/dd/yyyy'),
        TO_DATE(SUBSTR(get_json_object(payload_json, '$.dt_contapessoa_imo'), 1, 10), 'yyyy-MM-dd')
    ) AS dt_contapessoa_imo,
    COALESCE(
        TO_DATE(SUBSTR(get_json_object(payload_json, '$.dt_atualizacao_imo'), 1, 10), 'MM/dd/yyyy'),
        TO_DATE(SUBSTR(get_json_object(payload_json, '$.dt_atualizacao_imo'), 1, 10), 'yyyy-MM-dd')
    ) AS dt_atualizacao_imo,
    CAST(get_json_object(payload_json, '$.fl_motivorescisao_imo') AS INT) AS fl_motivorescisao_imo,
    COALESCE(
        TO_DATE(SUBSTR(get_json_object(payload_json, '$.dt_rescisao_imo'), 1, 10), 'MM/dd/yyyy'),
        TO_DATE(SUBSTR(get_json_object(payload_json, '$.dt_rescisao_imo'), 1, 10), 'yyyy-MM-dd')
    ) AS dt_rescisao_imo,
    get_json_object(payload_json, '$.nm_txanualcobrarmes_imo') AS nm_txanualcobrarmes_imo,
    CAST(get_json_object(payload_json, '$.fl_cobrartxanual_imo') AS INT) AS fl_cobrartxanual_imo,
    CAST(get_json_object(payload_json, '$.fl_txanualcobrarsemcontrato_imo') AS INT) AS fl_txanualcobrarsemcontrato_imo,
    CAST(get_json_object(payload_json, '$.fl_txanualcobrarproporcional_imo') AS INT) AS fl_txanualcobrarproporcional_imo,
    CAST(get_json_object(payload_json, '$.fl_txanualcobrarvalordomes_imo') AS INT) AS fl_txanualcobrarvalordomes_imo,
    COALESCE(
        TO_DATE(SUBSTR(get_json_object(payload_json, '$.dt_entrada_imo'), 1, 10), 'MM/dd/yyyy'),
        TO_DATE(SUBSTR(get_json_object(payload_json, '$.dt_entrada_imo'), 1, 10), 'yyyy-MM-dd')
    ) AS dt_entrada_imo,
    CAST(get_json_object(payload_json, '$.fl_reembolsoiss_imo') AS INT) AS fl_reembolsoiss_imo,
    get_json_object(payload_json, '$.st_apelido_imo') AS st_apelido_imo,
    CAST(get_json_object(payload_json, '$.vl_txadmvalorminimo_imo') AS DOUBLE) AS vl_txadmvalorminimo_imo,
    get_json_object(payload_json, '$.id_integracaoimoveis_imo') AS id_integracaoimoveis_imo,
    get_json_object(payload_json, '$.st_codigocontribuinte_imo') AS st_codigocontribuinte_imo,
    CAST(get_json_object(payload_json, '$.fl_ligacaoeletrica_imo') AS INT) AS fl_ligacaoeletrica_imo,
    get_json_object(payload_json, '$.st_uuidassinaturapaybox_imo') AS st_uuidassinaturapaybox_imo,
    CAST(get_json_object(payload_json, '$.fl_ocultarowli_imo') AS INT) AS fl_ocultarowli_imo,
    get_json_object(payload_json, '$.nm_txanualcobrarsobre_imo') AS nm_txanualcobrarsobre_imo,
    get_json_object(payload_json, '$.nm_txanualnmparcelas_imo') AS nm_txanualnmparcelas_imo,
    CAST(get_json_object(payload_json, '$.fl_txanualconfigpadrao_imo') AS INT) AS fl_txanualconfigpadrao_imo,
    CAST(get_json_object(payload_json, '$.fl_segurodesativado_imo') AS INT) AS fl_segurodesativado_imo,
    get_json_object(payload_json, '$.st_nome_cond') AS st_nome_cond,
    get_json_object(payload_json, '$.endereco_formatado') AS endereco_formatado,
    get_json_object(payload_json, '$.nome_formatado') AS nome_formatado,
    get_json_object(payload_json, '$.nome_proprietario') AS nome_proprietario,
    get_json_object(payload_json, '$.cnpj_proprietario') AS cnpj_proprietario,
    get_json_object(payload_json, '$.id_proprietario') AS id_proprietario,
    get_json_object(payload_json, '$.nascimento_proprietario') AS nascimento_proprietario,
    get_json_object(payload_json, '$.celular_proprietario') AS celular_proprietario,
    get_json_object(payload_json, '$.email_proprietario') AS email_proprietario,
    get_json_object(payload_json, '$.identificador_formatado') AS identificador_formatado,
    get_json_object(payload_json, '$.id_sacado_sac') AS id_sacado_sac,
    get_json_object(payload_json, '$.nome_inquilino') AS nome_inquilino,
    get_json_object(payload_json, '$.cnpj_inquilino') AS cnpj_inquilino,
    get_json_object(payload_json, '$.id_inquilino') AS id_inquilino,
    get_json_object(payload_json, '$.id_contrato_con') AS id_contrato_con,
    get_json_object(payload_json, '$.contratos') AS contratos,
    get_json_object(payload_json, '$.detalhes_formatado') AS detalhes_formatado,
    get_json_object(payload_json, '$.imoveis_gestores') AS imoveis_gestores,
    get_json_object(payload_json, '$.inquilinos') AS inquilinos,
    get_json_object(payload_json, '$.proprietarios_beneficiarios') AS proprietarios_beneficiarios,
    synced_at AS ts_synced
FROM
    property_row
