SELECT
    serial,
    sku,
    model,
    operating_system,
    operating_system_version,
    processor,
    CAST(memory AS INT) AS memory_gb,
    hostname,
    owner AS device_owner,
    contract_number,
    stock_subheading,
    location,
    tracked_by,
    document_country,
    employee_email,
    employee_name,
    employee_corporate_email,
    employee_cost_center_code,
    employee_department,
    employee_group,
    employee_registration_number,
    tax_id,
    term_contract AS term_contract_months,
    CAST(rent_price AS DECIMAL(10, 2)) AS rent_price,
    DATE(signature_date) AS dt_contract_signed,
    DATE(start_contract) AS dt_contract_started,
    DATE(end_contract) AS dt_contract_ended,
    DATE(start_term) AS dt_term_started,
    DATE(end_term) AS dt_term_ended,
    DATE(last_contact) AS dt_last_contacted,
    DATE(last_update) AS dt_last_updated,
    ts_load,
    year,
    month,
    day
FROM
    datalake_plugify_raw.device_inventory
