SELECT
    programapilototrazquemcomprapro_id AS id,
    dadosdoassociado_infos AS associate_infos,
    dadosdoassociado_infos_label AS associate_infos_label,
    dadosdoassociado_qualoseucpf AS associate_cpf,
    dadosdoassociado_nometelefone AS associate_name_and_phone,
    dadosdoassociado_dadosdocomprador_nomedocomprador AS buyer_name,
    dadosdoassociado_dadosdocomprador_telefonedocomprador AS buyer_phone,
    dadosdoassociado_dadosdocomprador_emaildocomprador AS buyer_email,
    dadosdoassociado_dadosdocomprador_qualoimoveleouregiaodeinteressedocompradorinformeaquiocodigodoimovellinkdoanuncioenderecooubairroessainformacaoeessencialparaocadastrodocompradoreparavalidarasuaparticipacaonoprograma AS house_or_region_of_interest,
    dadosdoassociado_dadosdocomprador_porfavorcompartilhequaisquerinformacoessobreocompradoreouoimovelbuscadoquesejamrelevantesparaqueaintermediacaoimobiliariasejabemsucedidaexfaixadeprecodoimovelbuscadoespecificacoestecnicasdoimoveletc AS additional_info,
    dadosdoassociado_dadosdocomprador_preferenciapeloatendimentodedeterminadocorretorassociadonamodalidadecompraevenda_opcionalvocegostariadeindicarumcorretorassociadodoquintoandarnamodalidadecompraevendaparaatenderaocompradorcadastradoporvocesesimpreenchacom AS indicated_sale_associate,
    entry_status,
    dadosdoassociado_dadosdocomprador_ocompradorestacientedocadastro::BOOLEAN AS is_buyer_aware_of_register,
    dadosdoassociado_vocefoiconvidadoaparticipardestepilotopeloquintoandar::BOOLEAN AS is_associate_invited_by_quintoandar,
    entry_datecreated::TIMESTAMP AS dt_entry_created,
    entry_datesubmitted::TIMESTAMP AS dt_entry_submitted,
    entry_dateupdated::TIMESTAMP AS dt_entry_updated
FROM
    datalake_gsheets_raw.tqc_pro_pilot_program_cognito_form
