"""Migration Comparison DAG — compare Twin and EMR metrics, produce verdict.

Auto-generated by emr-migration-v2 skill.
Run ID: 3eda59b6-f7c0-480d-b2d4-b04eabef7d51
Scope: growth/amplitude_subpartitioned
"""

import sys
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import urlparse

from airflow import DAG, Dataset
from airflow.operators.python import PythonOperator

from bietlejuice.services.configuration_service import ConfigurationService

_PLATFORM_DIR = str(Path(__file__).resolve().parent.parent)
if _PLATFORM_DIR not in sys.path:
    sys.path.insert(0, _PLATFORM_DIR)

DAG_ID = "migration_compare_growth__amplitude_subpartitioned"
RUN_ID = "3eda59b6-f7c0-480d-b2d4-b04eabef7d51"
DOMAIN = "growth"
DAG_NAME = "amplitude_subpartitioned"
RUN_PREFIX = "emr-migration/runs/3eda59b6-f7c0-480d-b2d4-b04eabef7d51"
TWIN_DATASET = "migration:twin-growth__amplitude_subpartitioned-complete"
EMR_DATASET = "migration:emr-growth__amplitude_subpartitioned-complete"

TABLES = [
    "155696_refer_lead_referred_events",
    "155697_refer_lead_referred_events",
    "160023_affiliate_lead_referred_events",
    "170135_in_app_survey_answered_events",
    "170135_in_app_survey_completed_events",
    "170135_in_app_survey_dismissed_events",
    "170135_in_app_survey_displayed_events",
    "170135_in_app_survey_received_events",
    "170135_in_app_survey_viewed_events",
    "170135_offer_submitted_events",
    "170135_piloto_cw_message_sent_events",
    "170698_adjust_install_events",
    "170698_alert_subscription_confirmed_events",
    "170698_apply_filters_events",
    "170698_appsflyer_install_events",
    "170698_banner_perform_action_events",
    "170698_chat_menu_item_clicked_events",
    "170698_chat_pp_iq_channel_list_page_viewed_events",
    "170698_chat_screen_page_viewed_events",
    "170698_chatcrpp_button_clicked_events",
    "170698_checkout_order_credit_card_payment_button_tapped_events",
    "170698_checkout_order_credit_card_payment_failure_view_events",
    "170698_checkout_order_credit_card_payment_pending_view_events",
    "170698_checkout_order_credit_card_payment_success_view_events",
    "170698_checkout_order_credit_card_try_again_tapped_events",
    "170698_classifieds_viewed_events",
    "170698_coll_negotiation_menu_page_onload_events",
    "170698_coll_negotiation_menu_page_payment_cta_onclick_events",
    "170698_coll_negotiation_menu_page_payment_option_select_onclick_events",
    "170698_coll_negotiation_waiting_button_clicked_events",
    "170698_coll_negotiation_waiting_page_swipe_events",
    "170698_coll_negotiation_waiting_page_viewed_events",
    "170698_coll_review_check_negotiation_cta_onclick_events",
    "170698_coll_review_check_negotiation_page_onload_events",
    "170698_concierge_trigger_events",
    "170698_consorcio_cta_clicked_events",
    "170698_consorcio_lead_generated_events",
    "170698_consorcio_page_viewed_events",
    "170698_contact_broker_clicked_events",
    "170698_contract_docusign_signed_events",
    "170698_contract_page_viewed_events",
    "170698_contract_payment_summary_clicked_events",
    "170698_contract_payment_summary_viewed_events",
    "170698_copy_inspection_report_link_button_clicked_events",
    "170698_cxp_fine_info_page_viewed_events",
    "170698_cxp_fine_invoice_button_clicked_events",
    "170698_cxp_fine_more_info_button_clicked_events",
    "170698_cxp_fine_negotiate_button_clicked_events",
    "170698_cxp_flow_payments_page_viewed_events",
    "170698_cxp_main_page_next_steps_button_clicked_events",
    "170698_cxp_main_page_off_inspection_button_clicked_events",
    "170698_cxp_main_page_payments_button_clicked_events",
    "170698_cxp_main_page_post_exit_inspection_button_clicked_events",
    "170698_cxp_main_page_post_exit_page_viewed_events",
    "170698_cxp_main_page_post_exit_payments_button_clicked_events",
    "170698_cxp_main_page_postpone_termination_button_clicked_events",
    "170698_cxp_main_page_property_return_button_clicked_events",
    "170698_cxp_next_steps_page_viewed_events",
    "170698_cxp_payments_page_payment_receipts_button_clicked_events",
    "170698_cxp_payments_page_termination_fine_button_clicked_events",
    "170698_debug_visit_schedule_confirmed_events",
    "170698_doc_tenants_address_submit_events",
    "170698_doc_tenants_address_viewed_events",
    "170698_doc_tenants_basicinfo_submit_events",
    "170698_doc_tenants_basicinfo_viewed_events",
    "170698_doc_tenants_document_photo_clicked_events",
    "170698_doc_tenants_income_clicked_events",
    "170698_doc_tenants_income_submit_events",
    "170698_doc_tenants_list_viewed_events",
    "170698_doc_tenants_personal_submit_events",
    "170698_doc_tenants_personal_viewed_events",
    "170698_doc_tenants_selfie_clicked_events",
    "170698_doc_tenants_selfieok_submit_events",
    "170698_doc_tenants_submit_complete_events",
    "170698_edit_account_info_clicked_events",
    "170698_evaluation_anchor_clicked_events",
    "170698_evaluation_anchor_result_clicked_events",
    "170698_evaluation_anchor_viewed_events",
    "170698_evaluation_drop_clicked_events",
    "170698_evaluation_error_viewed_events",
    "170698_evaluation_errordialog_viewed_events",
    "170698_evaluation_onboarding_clicked_events",
    "170698_evaluation_onboarding_dismissed_events",
    "170698_evaluation_onboarding_viewed_events",
    "170698_evaluation_result_action_bar_clicked_events",
    "170698_evaluation_result_close_clicked_events",
    "170698_evaluation_result_cta_clicked_events",
    "170698_evaluation_result_guarantee_clicked",
    "170698_evaluation_result_newevaluation_clicked_events",
    "170698_evaluation_result_redoevaluation_clicked_events",
    "170698_evaluation_result_reservation_clicked_events",
    "170698_evaluation_result_search_clicked_events",
    "170698_evaluation_result_secondary_clicked_events",
    "170698_evaluation_result_senddocs_clicked_events",
    "170698_evaluation_result_viewed_events",
    "170698_evaluation_runevaluation_clicked_events",
    "170698_evaluation_selecttenants_viewed_events",
    "170698_evaluation_setvalue_viewed_events",
    "170698_evaluation_summary_viewed_events",
    "170698_evaluation_tenantform_viewed_events",
    "170698_evaluation_tenantslist_submitted_events",
    "170698_evaluation_timeout_result_clicked_events",
    "170698_evaluation_timeout_viewed_events",
    "170698_faq_article_page_viewed_events",
    "170698_feed_recommendation_page_viewed_events",
    "170698_fs_mortgage_progress_step_clicked_events",
    "170698_fs_mortgage_track_progress_button_clicked_events",
    "170698_fs_mortgage_track_progress_page_viewed_events",
    "170698_fs_mortgage_track_status_viewed_events",
    "170698_fs_task_page_viewed_events",
    "170698_help_center_article_clicked_events",
    "170698_help_center_article_recommendation_clicked_events",
    "170698_help_center_article_recommendation_viewed_events",
    "170698_help_center_call_cancel_button_clicked_events",
    "170698_help_center_call_request_button_clicked_events",
    "170698_help_center_call_viewed_events",
    "170698_help_center_faq_clicked_events",
    "170698_help_center_page_viewed_events",
    "170698_help_center_question_mark_clicked_events",
    "170698_help_center_wait_call_viewed_events",
    "170698_home_page_viewed_events",
    "170698_homes_subscription_confirmed_events",
    "170698_house_card_clicked_events",
    "170698_inspection_budgetapproval_home_page_viewed_events",
    "170698_inspection_review_home_page_viewed_events",
    "170698_lead_intent_confirmed_events",
    "170698_lead_intent_events",
    "170698_listing_early_credit_clicked_events",
    "170698_listing_favorite_remove_events",
    "170698_listing_favorite_set_events",
    "170698_listing_open_gallery_view_events",
    "170698_listing_page_viewed_events",
    "170698_listing_photosphere_opened_events",
    "170698_listing_video_started_events",
    "170698_login_confirmation_viewed_events",
    "170698_mc_landing_page_viewed",
    "170698_mortgage_home_viewed_events",
    "170698_my_checkout_page_viewed_events",
    "170698_my_rent_pending_invoices_card_view_events",
    "170698_native_home_page_viewed_events",
    "170698_native_home_section_banner_events",
    "170698_native_home_section_tiles_list_events",
    "170698_ntc_notification_clicked_events",
    "170698_offboarding_inspections_repairs_task_button_clicked_events",
    "170698_offboarding_keys_task_start_setup_page_viewed_events",
    "170698_offboarding_keys_task_success_page_viewed_events",
    "170698_offboarding_repair_guidelines_entry_inspection_clicked_events",
    "170698_offboarding_repair_guidelines_negotiate_repairs_card_viewed_events",
    "170698_offboarding_repair_guidelines_task_accordion_clicked_events",
    "170698_offboarding_repairs_task_success_page_viewed_events",
    "170698_offboarding_terminationcontrol_inspection_page_viewed_events",
    "170698_offboarding_terminationcontrol_page_viewed_events",
    "170698_offboarding_utilitybills_receipts_page_viewed_events",
    "170698_offer_accepted_new_events",
    "170698_offer_canceled_new_events",
    "170698_offer_submitted_events",
    "170698_offer_submitted_new_events",
    "170698_offerinfo_page_viewed_events",
    "170698_overdue_invoices_invoice_pay_button_clicked_events",
    "170698_overdue_invoices_invoice_pay_total_button_clicked_events",
    "170698_overdue_invoices_page_viewed_events",
    "170698_overdue_invoices_payment_option_clicked_events",
    "170698_overdue_invoices_payment_option_viewed_events",
    "170698_overdue_invoices_payment_options_closed_events",
    "170698_overdue_invoices_total_payment_option_clicked_events",
    "170698_overdue_invoices_total_payment_option_viewed_events",
    "170698_owner_termination_management_page_viewed_events",
    "170698_pending_invoices_exception_cta_clicked_events",
    "170698_pending_invoices_exception_cta_goback_clicked_events",
    "170698_pending_invoices_exception_page_viewed_events",
    "170698_pending_invoices_invoice_pay_button_clicked_events",
    "170698_pending_invoices_negotiation_cta_clicked_events",
    "170698_pending_invoices_overdue_card_viewed_events",
    "170698_pending_invoices_page_viewed_events",
    "170698_pending_invoices_pay_invoice_cta_clicked_events",
    "170698_pending_invoices_pay_total_cta_clicked_events",
    "170698_pending_invoices_payment_option_clicked_events",
    "170698_pi_negotiation_payment_option_clicked_events",
    "170698_pi_negotiation_payment_option_closed_events",
    "170698_pi_negotiation_started_page_viewed_events",
    "170698_piloto_cw_message_sent_events",
    "170698_price_suggestion_address_submitted_events",
    "170698_price_suggestion_page_viewed_events",
    "170698_profiling_complete_clicked_events",
    "170698_pv_management_area_viewed_events",
    "170698_pv_management_hub_viewed_events",
    "170698_recset_impression_events",
    "170698_recset_viewed_events",
    "170698_repair_center_ps_iq_budget_sent_budget_details_clicked_events",
    "170698_rm_invoice_page_viewed_events",
    "170698_rm_invoice_payment_option_clicked_events",
    "170698_rm_invoice_pix_copy_paste_clicked_events",
    "170698_rm_myrent_page_viewed_events",
    "170698_rm_pending_invoices_page_viewed_events",
    "170698_sale_offer_form_accepted_events",
    "170698_schedule_page_viewed_events",
    "170698_search_page_viewed_events",
    "170698_search_results_page_viewed_events",
    "170698_select_listing_visit_button_clicked_events",
    "170698_session_start_events",
    "170698_share_listing_events",
    "170698_tap_intent_selection_register_property_events",
    "170698_tile_perform_action_events",
    "170698_tts_success_page_viewed_events",
    "170698_unavailable_listing_viewed_events",
    "170698_user_accepted_scr_terms_clicked_event_events",
    "170698_user_has_been_blocked_on_ivr_events",
    "170698_user_ivr_still_accessible_events",
    "170698_user_merge",
    "170698_user_tried_to_call_again_after_blocked_events",
    "170698_visit_fitting_page_viewed_events",
    "170698_visit_fitting_requested_success_page_viewed_events",
    "170698_visit_hoursalert_confirmed_events",
    "170698_visit_intent_clicked_events",
    "170698_visit_list_request_schedule_button_clicked_events",
    "170698_visit_schedule_clicked_events",
    "170698_visit_schedule_confirmed_events",
    "170698_visit_schedule_continue_clicked_events",
    "183047_ad_improvements_first_access_page_viewed_events",
    "183047_ad_improvements_intent_button_clicked_events",
    "183047_ad_improvements_page_viewed_events",
    "183047_ad_improvements_price_in_range_page_viewed_events",
    "183047_ad_improvements_price_recommendation_accepted_button_clicked_events",
    "183047_ad_improvements_price_recommendation_page_viewed_events",
    "183047_ad_improvements_price_strategy_button_clicked_events",
    "183047_atlas_db_address_search_events",
    "183047_atlas_db_house_characteristics_events",
    "183047_chatcrpp_blocked_message_alert_shown_events",
    "183047_chatcrpp_chat_conversation_started_events",
    "183047_chatcrpp_chat_page_viewed_events",
    "183047_chatcrpp_suspicious_message_sent_events",
    "183047_chatcrpp_warning_message_alert_shown_events",
    "183047_contract_page_viewed_events",
    "183047_contract_termination_page_viewed_events",
    "183047_entry_model_change_confirmed_button_clicked_events",
    "183047_entry_model_change_success_page_viewed_events",
    "183047_entry_model_details_page_viewed_events",
    "183047_entry_model_form_page_viewed_events",
    "183047_faq_article_page_viewed_events",
    "183047_fs_mortgage_track_progress_button_clicked_events",
    "183047_fs_mortgage_track_progress_page_viewed_events",
    "183047_fs_mortgage_track_status_viewed_events",
    "183047_fs_task_page_viewed_events",
    "183047_help_center_article_clicked_events",
    "183047_help_center_article_recommendation_clicked_events",
    "183047_help_center_article_recommendation_viewed_events",
    "183047_help_center_faq_clicked_events",
    "183047_help_center_page_viewed_events",
    "183047_help_center_question_mark_clicked_events",
    "183047_house_in_early_relisting_events",
    "183047_house_management_deep_link_handled_events",
    "183047_inspection_report_button_clicked_events",
    "183047_intro_page_viewed_events",
    "183047_landing_page_viewed_events",
    "183047_lead_form_submitted_events",
    "183047_listing_location_submitted_events",
    "183047_listing_overpriced_comms_routine_eligible_events",
    "183047_listing_overpriced_comms_routine_excluded_events",
    "183047_listing_published_events",
    "183047_listing_terms_confirmed_events",
    "183047_lra_simple_simulation_clicked_events",
    "183047_mortgage_home_viewed_events",
    "183047_mra_acceptance_viewed_events",
    "183047_mra_description_clicked_events",
    "183047_mra_description_viewed_events",
    "183047_mra_widget_clicked_events",
    "183047_native_home_page_viewed_events",
    "183047_native_home_section_properties_list_events",
    "183047_offboarding_keys_task_button_clicked_events",
    "183047_offboarding_keys_task_select_location_page_viewed_events",
    "183047_offboarding_keys_task_success_page_viewed_events",
    "183047_offer_accepted_new_events",
    "183047_offer_canceled_new_events",
    "183047_offer_list_page_viewed_events",
    "183047_offer_submitted_new_events",
    "183047_offers_list_results_viewed_events",
    "183047_price_edit_confirmed_button_clicked_events",
    "183047_price_edit_intent_button_clicked_events",
    "183047_price_edit_page_viewed_events",
    "183047_price_edit_query_parameters_tracked_events",
    "183047_price_edit_review_page_viewed_events",
    "183047_price_report_landing_rent_page_viewed_events",
    "183047_price_report_landing_sale_page_viewed_events",
    "183047_price_suggestion_advertise_clicked_events",
    "183047_price_suggestion_form_submitted_events",
    "183047_price_suggestion_page_viewed_events",
    "183047_price_suggestion_sale_form_submitted_events",
    "183047_price_suggestion_sale_page_viewed_events",
    "183047_property_details_page_viewed_events",
    "183047_property_edit_hub_page_viewed_events",
    "183047_property_edit_price_intent_button_clicked_events",
    "183047_property_list_page_viewed_events",
    "183047_property_list_success_page_viewed_events",
    "183047_property_page_viewed_events",
    "183047_property_performance_hub_available_hours_button_clicked_events",
    "183047_property_performance_hub_available_hours_card_button_clicked_events",
    "183047_property_performance_hub_button_clicked_events",
    "183047_property_performance_hub_page_viewed_events",
    "183047_property_performance_hub_price_button_clicked_events",
    "183047_property_performance_hub_price_card_button_clicked_events",
    "183047_property_performance_hub_switched_events",
    "183047_pv_management_area_viewed_events",
    "183047_pv_management_hub_viewed_events",
    "183047_relisting_early_visits_confirmed_events",
    "183047_rent_pricing_new_listing_form_submitted_events",
    "183047_rent_pricing_new_listing_page_viewed_events",
    "183047_reviews_page_viewed_events",
    "183047_rm_myrent_page_viewed_events",
    "183047_sale_calculator_edition_form_submitted_events",
    "183047_sale_calculator_page_viewed_events",
    "183047_sale_price_page_viewed_events",
    "183047_sale_pricing_existing_listing_form_submitted_events",
    "183047_sale_pricing_existing_listing_page_viewed_events",
    "183047_sale_pricing_new_listing_form_submitted_events",
    "183047_sale_pricing_new_listing_page_viewed_events",
    "183047_terms_page_viewed_events",
    "183047_user_merge",
    "183049_offer_submitted_events",
    "203461_inspector_app_add_photo_clicked_events",
    "205027_intro_page_viewed_events",
    "205027_referral_form_accepted_events",
    "205027_referral_form_discarded_events",
    "233592_agenda_visit_list_page_viewed_events",
    "233592_agent_with_keys_property_indication_button_clicked_events",
    "233592_agent_with_keys_property_indication_copy_button_clicked_events",
    "233592_agent_with_keys_property_indication_error_events",
    "233592_agent_with_keys_property_indication_page_viewed_events",
    "233592_agent_with_keys_property_indication_search_feedback_events",
    "233592_chatcrpp_accep_terms_button_clicked_events",
    "233592_chatcrpp_allchats_page_viewed_events",
    "233592_chatcrpp_blocked_message_alert_shown_events",
    "233592_chatcrpp_chat_conversation_started_events",
    "233592_chatcrpp_chat_page_viewed_events",
    "233592_chatcrpp_suspicious_message_sent_events",
    "233592_chatcrpp_warning_message_alert_shown_events",
    "233592_entry_model_validation_button_clicked_events",
    "233592_keys_management_page_viewed_events",
    "233592_keys_management_property_indication_card_clicked_events",
    "233592_recommend_send_an_offer_events",
    "233592_shortcut_more_visits_intent_clicked_events",
    "233592_shortcut_more_visits_success_page_viewed_events",
    "233592_shortcut_more_visits_viewed_events",
    "233592_talk_to_the_owner_events",
    "233592_tts_helps_button_clicked_events",
    "233592_visit_finalization_agent_profilling_button_clicked_events",
    "233592_visit_finalization_agent_success_page_viewed_events",
    "250821_photo_session_detail_viewed_events",
    "283048_register_form_completed_events",
    "370096_properties_entry_model_drawer_update_error_events",
    "370096_property_publish_success_events",
    "417002_datahub_entity_action_events",
    "417002_datahub_entity_section_view_events",
    "417002_datahub_entity_view_events",
    "417002_datahub_home_page_view_events",
    "417002_datahub_page_view_events",
    "417002_datahub_search_events",
    "417002_datahub_search_result_click_events",
    "417002_datahub_search_results_view_events",
    "417002_datahub_select_auto_complete_option_events",
    "440441_home_page_viewed_events",
    "440441_listing_registration_location_page_viewed_events",
    "440441_sale_offer_list_details_button_clicked_events",
    "525551_listing_page_viewed_events",
    "525551_schedule_visit_at_5a_button_clicked_events",
    "525551_search_page_viewed_events",
]

_CONFIG = ConfigurationService("amplitude_subpartitioned")
ARTIFACTS_URI = _CONFIG.get_config("artifacts_bucket")
ARTIFACTS_BUCKET = urlparse(ARTIFACTS_URI).netloc or ARTIFACTS_URI

default_args = {
    "owner": "data-platform",
    "retries": 0,
}

with DAG(
    dag_id=DAG_ID,
    default_args=default_args,
    schedule=[Dataset(TWIN_DATASET), Dataset(EMR_DATASET)],
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["migration", "comparison", "validation"],
    dagrun_timeout=timedelta(hours=4),
) as dag:

    def _get_s3_client():
        import boto3
        from airflow.models import Variable

        role_arn = Variable.get("DATASET_EVENTS_ASSUME_ROLE_ARN", default_var=None)
        if not role_arn:
            return boto3.client("s3")
        sts = boto3.client("sts")
        creds = sts.assume_role(
            RoleArn=role_arn,
            RoleSessionName="migration-s3-compare",
            DurationSeconds=3600,
        )["Credentials"]
        return boto3.Session(
            aws_access_key_id=creds["AccessKeyId"],
            aws_secret_access_key=creds["SecretAccessKey"],
            aws_session_token=creds["SessionToken"],
        ).client("s3")

    def run_comparison(**context):
        """Read metrics from S3, compare, write verdict."""
        from migration_assets.comparison import (
            compare_table,
            list_s3_jsons,
            read_s3_json,
            write_s3_json,
        )

        s3 = _get_s3_client()
        bucket = ARTIFACTS_BUCKET

        twin_prefix = f"{RUN_PREFIX}/twin/{DOMAIN}/{DAG_NAME}/"
        emr_prefix = f"{RUN_PREFIX}/emr/{DOMAIN}/{DAG_NAME}/"
        verdict_prefix = f"{RUN_PREFIX}/verdicts/{DOMAIN}/{DAG_NAME}/"

        twin_keys = list_s3_jsons(bucket, twin_prefix, s3_client=s3)
        emr_keys = list_s3_jsons(bucket, emr_prefix, s3_client=s3)

        twin_by_table = {}
        for key in twin_keys:
            metric = read_s3_json(f"{ARTIFACTS_URI}/{key}", s3_client=s3)
            table_name = metric.get(
                "table_name", key.split("/")[-1].replace(".json", "")
            )
            twin_by_table[table_name] = metric

        emr_by_table = {}
        for key in emr_keys:
            metric = read_s3_json(f"{ARTIFACTS_URI}/{key}", s3_client=s3)
            table_name = metric.get(
                "table_name", key.split("/")[-1].replace(".json", "")
            )
            emr_by_table[table_name] = metric

        all_tables = (
            TABLES
            if TABLES
            else sorted(set(twin_by_table.keys()) | set(emr_by_table.keys()))
        )
        if not all_tables:
            raise RuntimeError("No metric files found for either runtime")

        summary_uri = f"{ARTIFACTS_URI}/{verdict_prefix}summary.json"
        write_s3_json(
            summary_uri,
            {"version": 1, "run_id": RUN_ID, "status": "in_progress"},
            s3_client=s3,
        )

        verdicts = {}
        passed = warned = failed = 0

        for table_name in all_tables:
            twin_m = twin_by_table.get(
                table_name,
                {
                    "table_name": table_name,
                    "error": "Missing twin metric",
                    "run_id": RUN_ID,
                },
            )
            emr_m = emr_by_table.get(
                table_name,
                {
                    "table_name": table_name,
                    "error": "Missing EMR metric",
                    "run_id": RUN_ID,
                },
            )

            for label, metric in [("twin", twin_m), ("emr", emr_m)]:
                metric_run_id = metric.get("run_id", "")
                if metric_run_id and metric_run_id != RUN_ID:
                    metric["error"] = (
                        f"run_id mismatch: expected {RUN_ID}, got {metric_run_id} ({label})"
                    )
            verdict = compare_table(twin_m, emr_m)
            verdict_uri = f"{ARTIFACTS_URI}/{verdict_prefix}{table_name}.json"
            write_s3_json(verdict_uri, verdict, s3_client=s3)

            v = verdict["verdict"]
            verdicts[table_name] = v
            if v == "PASS":
                passed += 1
            elif v == "WARN":
                warned += 1
            else:
                failed += 1

        summary = {
            "version": 1,
            "run_id": RUN_ID,
            "scope_id": f"{DOMAIN}__{DAG_NAME}",
            "total_tables": len(all_tables),
            "passed": passed,
            "warned": warned,
            "failed": failed,
            "tables": verdicts,
            "overall_verdict": "FAIL" if failed else ("WARN" if warned else "PASS"),
            "pr_gate_eligible": failed == 0,
        }
        summary_uri = f"{ARTIFACTS_URI}/{verdict_prefix}summary.json"
        write_s3_json(summary_uri, summary, s3_client=s3)

        context["ti"].xcom_push(key="overall_verdict", value=summary["overall_verdict"])
        context["ti"].xcom_push(
            key="pr_gate_eligible", value=summary["pr_gate_eligible"]
        )

    compare_all = PythonOperator(
        task_id="compare_all",
        python_callable=run_comparison,
    )
