SELECT
  Address AS address,
  `Content Type` AS content_type,
  `Status Code` AS status_code,
  Status AS status,
  Indexability AS indexability,
  `Indexability Status` AS indexability_status,
  `Title 1` AS title_content,
  `Title 1 Pixel Width` AS title_pixel_width,
  `Meta Description 1` AS meta_description_content,
  `Meta Description 1 Pixel Width` AS meta_description_pixel_width,
  `Meta Keywords 1` AS meta_keywords_content,
  `H1-1` AS h1_content,
  `H1-2` AS secondary_h1_content, 
  `H2-1` AS h2_content,
  `H2-2` AS secondary_h2_content,
  `Meta Robots 1` AS meta_robots_content,
  `X-Robots-Tag 1` AS x_robots_tag_content,
  `Meta Refresh 1` AS meta_refresh_content,
  `Canonical Link Element 1` AS canonical_link_element,
  `Redirect URL` AS redirect_url,
  `Redirect Type` AS redirect_type,
  `Language` AS language,
  `HTTP Version` AS http_version,
  `Supply 1` AS supply,
  `URL Encoded Address` AS url_encoded_address,
  `Size (bytes)` AS size_in_bytes,
  `Transferred (bytes)` AS transferred_bytes,
  `Total Transferred (bytes)` AS total_transferred_bytes,
  `CO2 (mg)` AS carbon_emissions,
  `Word Count` AS word_count,
  `Sentence Count` AS sentence_count,
  `Average Words Per Sentence` AS average_words_per_sentence,
  `Flesch Reading Ease Score` AS flesch_reading_ease_score,
  `Readability` AS readability,
  `Text Ratio` AS text_ratio,
  `Crawl Depth` AS crawl_depth,
  `Folder Depth` AS folder_depth,
  `Inlinks` AS inlink_count,
  `Unique Inlinks` AS unique_inlink_count,
  `% of Total` AS percentage_of_total,
  `Outlinks` AS outlink_count,
  `Unique Outlinks` AS unique_outlink_count,
  `Response Time` AS response_time,
  `Last Modified` AS ts_last_modified,
  `Crawl Timestamp` AS ts_crawl,
  `Device` AS device,
  YEAR(date) AS year,
  MONTH(date) AS month,
  DAY(date) AS day
FROM 
  datalake_ada_crawls_raw.internal_all
WHERE 
  date BETWEEN '{load_start_date}' AND '{load_end_date}'