SELECT
  Address AS address,
  `Content Type` AS content_type,
  CAST( `Status Code` AS BIGINT) AS status_code,
  Status AS status,
  Indexability AS indexability,
  `Indexability Status` AS indexability_status,
  `Title 1` AS title_content,
  `Meta Description 1` AS meta_description_content,
  `Meta Keywords 1` AS meta_keywords_content,
  `H1-1` AS h1_content,
  `H1-2` AS secondary_h1_content, 
  `H2-1` AS h2_content,
  `H2-2` AS secondary_h2_content,
  `Meta Robots 1` AS meta_robots_content,
  `X-Robots-Tag 1` AS x_robots_tag_content,
  `Meta Refresh 1` AS meta_refresh_content,
  `Canonical Link Element 1` AS canonical_link_element,
  `Redirect URL` AS redirect_url,
  `Redirect Type` AS redirect_type,
  `Language` AS language,
  `HTTP Version` AS http_version,
  `Supply 1` AS supply,
  `URL Encoded Address` AS url_encoded_address,
  `Title 1 Pixel Width` AS title_pixel_width,
  `Meta Description 1 Pixel Width` AS meta_description_pixel_width,
  CAST(`Size (bytes)` AS BIGINT) AS size_in_bytes,
  CAST(`Transferred (bytes)` AS BIGINT) AS transferred_bytes,
  CAST(`Total Transferred (bytes)` AS BIGINT) AS total_transferred_bytes,
  CAST(REPLACE(`CO2 (mg)`, ',', '.') AS DOUBLE) AS carbon_emissions,
  CAST(`Word Count` AS BIGINT) AS word_count,
  CAST(`Sentence Count` AS BIGINT) AS sentence_count,
  CAST(REPLACE(`Average Words Per Sentence`, ',', '.') AS DOUBLE) AS average_words_per_sentence,
  CAST(REPLACE(`Flesch Reading Ease Score`, ',', '.') AS DOUBLE) AS flesch_reading_ease_score,
  `Readability` AS readability,
  CAST(REPLACE(`Text Ratio`, ',', '.') AS DOUBLE) AS text_ratio,
  CAST(`Crawl Depth` AS BIGINT) AS crawl_depth,
  CAST(`Folder Depth` AS BIGINT) AS folder_depth,
  CAST(`Inlinks` AS BIGINT) AS inlink_count,
  CAST(`Unique Inlinks` AS BIGINT) AS unique_inlink_count,
  CAST(REPLACE(`% of Total`, ',', '.') AS DOUBLE) AS percentage_of_total,
  CAST(`Outlinks` AS BIGINT) AS outlink_count,
  CAST(`Unique Outlinks` AS BIGINT) AS unique_outlink_count,
  CAST(REPLACE(`Response Time`, ',', '.') AS DOUBLE) AS response_time,
  `Last Modified` AS ts_last_modified,
  `Crawl Timestamp` AS ts_crawl,
  CAST(date AS TIMESTAMP) AS dt_report,
  `Device` AS device,
  YEAR(date) AS year,
  MONTH(date) AS month,
  DAY(date) AS day
FROM 
  datalake_ada_crawls_raw.internal_all
WHERE 
  date BETWEEN '{load_start_date}' AND '{load_end_date}'