drop table if exists unit_economics.fact_property_economics;

CREATE TABLE unit_economics.fact_property_economics (
	sk_house_listing int8 NOT NULL,
	property_id int8 NOT NULL,
	sk_contract int8 NOT NULL,
	sk_cash_flow_date int8 NOT NULL,
	vl_owner_campaigns decimal(14,4),
	vl_affiliate_campaigns decimal(14,4),
	vl_inside_sales decimal(14,4),
	vl_photos decimal(14,4),
	vl_affiliate_bonus decimal(14,4),
	vl_lockbox decimal(14,4),
	vl_tenant_campaigns decimal(14,4),
	vl_cs_pre_sale decimal(14,4),
	vl_field_ops decimal(14,4),
	vl_bo_pre_sale decimal(14,4),
	vl_agent_hours decimal(14,4),
	vl_st_pis_cofins decimal(14,4),
	flg_expected_sales_tax_pis_cofins int4,
	vl_st_iss decimal(14,4),
	flg_expected_sales_tax_iss int4,
	vl_affiliate_commission decimal(14,4),
	flg_expected_affiliate_commission int4,
	vl_agent_commission decimal(14,4),
	flg_expected_agent_commission int4,
	vl_delay_fine decimal(14,4),
	flg_expected_delay_fine int4,
	vl_termination_fine decimal(14,4),
	vl_brokerage_fee decimal(14,4),
	flg_expected_brokerage_fee int4,
	vl_management_fee decimal(14,4),
	flg_expected_management_fee int4,
	vl_rent_value decimal(14,4),
	vl_cs_post_sale decimal(14,4),
	flg_expected_cs_post_sale int4,
	vl_collection decimal(14,4),
	flg_expected_collection int4,
	vl_bo_onboarding decimal(14,4),
	flg_expected_bo_onboarding int4,
	vl_bo_ongoing decimal(14,4),
	flg_expected_bo_ongoing int4,
	vl_bo_offboarding decimal(14,4),
	flg_expected_bo_offboarding int4,
	vl_inspections decimal(14,4),
	flg_expected_inspection int4,
	vl_default_fee decimal(14,4),
	vl_insurance_fee decimal(14,4),
	flg_expected_insurance_fee int4
) ;
