select
  revtype as rev_type,
  businesscontext as business_context,
  checkinstatus as checkin_status,
  status,
  agente_mod as mod_id_agent,
  imovel_id as id_house,
  imovel_mod as mod_id_house,
  data_mod as mod_dt_booking,
  datafupvisita as ts_visit_fup,
  fluxolocacao_id as id_rent_flow,
  data as dt_booking,
  slotdia as slot_day,
  agentefixo as is_agent_fixed,
  id,
  visitante_id as id_visitor,
  visitante_mod as mod_id_visitor,
  agente_id as id_agent,
  fupvisita as visit_fup,
  reagendadode_id as id_rescheduled_booking,
  informeinquilinopendente_mod as mod_is_tenant_notification_pending,
  slotdia_mod as mod_slot_day,
  rev,
  agentefixo_mod as mod_is_fixed_agent,
  informeinquilinopendente as is_tenant_notification_pending,
  status_mod as mod_status,
  comentariofupvisita as visit_fup_comment,
  atendente_mod as mod_id_attendant,
  reagendadode_mod as mod_id_rescheduled_booking,
  checkinstatus_mod as mod_checkin_status,
  atendente_id as id_attendant,
  origemultimaatualizacao_id as id_last_update_origin,
  tipo as type,
  structured as structured,
  structured_MOD AS mod_structured
from datalake_ebdb_raw.Agendamento_AUD
