SELECT
    id,
    realEstateAgentRating_id AS id_real_estate_agent_rating,
    visitante_id AS id_visitor,
    agente_id AS id_agent,
    origemCriacao_id AS id_creation_origin,
    origemUltimaAtualizacao_id AS id_last_update_origin,
    houseRating_id AS id_house_rating,
    house_id AS id_house,
    codigo AS code,
    slot,
    numeroSlots AS slot_count,
    request_slot AS slot_request,
    tipo AS type,
    status,
    computed_status,
    bookingType AS booking_type,
    behavior,
    business_model,
    business_context,
    agenteFixo AS is_fixed_agent,
    structured,
    dia AS dt_visit,
    request_date AS dt_request,
    confirmation_expiration_date AS dt_confirmation_expiration,
    criadoEm AS ts_created,
    atualizadoEm AS ts_updated
FROM
    datalake_ebdb_test_raw.Visita
