SELECT
    action_occurrence_id AS id_action_occurrence,
    action_id AS id_action,
    action_reason_id AS id_action_reason,
    ref_action_occurrence_id AS id_reference_action_occurrence,
    business_unit_id AS id_business_unit,
    entity_id AS id_entity,
    parent_entity_key_id AS id_parent_entity_key,
    business_group_id AS id_business_group,
    proposed_action_id AS id_proposed_action,
    proposed_reason_id AS id_proposed_reason,
    legal_entity_id AS id_legal_entity,
    action_type_code,
    category_code,
    entity_type,
    parent_entity_type,
    proposed_action_type,
    proposed_worker_type,
    submitted_by,
    created_by,
    last_updated_by AS updated_by,
    CAST(object_version_number AS INT) AS object_version_number,
    TO_DATE(action_date) AS dt_action_occurred,
    TO_DATE(freeze_start_date) AS dt_freeze_started,
    TO_DATE(freeze_until_date) AS dt_freeze_started,
    TO_TIMESTAMP(creation_date) AS ts_created,
    TO_TIMESTAMP(last_update_date) AS ts_updated,
    NOW() AS ts_load,
    year,
    month,
    day
FROM
    datalake_pin_core_raw.per_action_occurrences