SELECT
  action_occurrence_id AS id_action_occurrence,
  assignment_id AS id_assignment,
  business_group_id AS id_business_group,
  business_unit_id AS id_business_unit,
  assignment_status_type_id AS id_assignment_status_type,
  source_assignment_id AS id_source_assignment,
  id_flex_num AS id_flex_number,
  legal_entity_id AS id_legal_entity,
  grade_id AS id_grade,
  grade_ladder_pgm_id AS id_grade_ladder_pgm,
  work_terms_assignment_id AS id_work_terms_assignment,
  union_id AS id_union,
  organization_id AS id_organization,
  job_id AS id_job,
  period_of_service_id AS id_period_of_service,
  person_id AS id_person,
  parent_assignment_id AS id_parent_assignment,
  person_type_id AS id_person_type,
  assignment_number,
  hourly_salaried_code,
  action_code,
  category_code,
  reason_code,
  legislation_code,
  assignment_status_type,
  assignment_type,
  proposed_worker_type,
  system_person_type,
  asg_information_category AS assignment_information_category,
  employee_category,
  employment_category,
  UPPER(assignment_name) AS assignment_name,
  created_by,
  last_updated_by AS updated_by,
  record_creator,
  seniority_basis,
  frequency,
  CAST(object_version_number AS INT) AS object_version_number,
  CAST(assignment_sequence AS INT) AS assignment_sequence,
  CAST(effective_sequence AS INT) AS effective_sequence,
  CAST(normal_hours AS FLOAT) AS normal_hours,
  allow_asg_override_flag = 'Y' AS is_assignment_override_allowed,
  auto_end_flag = 'Y' AS is_auto_ended,
  gsp_eligibility_flag = 'Y' AS is_included_in_grade_step_progression,
  position_override_flag = 'Y' AS is_position_override,
  primary_assignment_flag = 'Y' AS is_primary_assignment,
  primary_flag = 'Y' AS is_primary,
  primary_work_relation_flag = 'Y' AS is_primary_work_relation,
  primary_work_terms_flag = 'Y' AS is_primary_work_terms,
  labour_union_member_flag = 'Y' AS is_labour_union_member,
  manager_flag = 'Y' AS is_manager,
  permanent_temporary_flag = 'R' AS is_permanent_position,
  effective_latest_change = 'Y' AS is_effective_latest_change,
  rehire_recommendation = 'Y' AS is_recommended_for_rehire,
  work_at_home = 'Y' AS is_working_at_home,
  TO_DATE(effective_start_date) AS dt_effective_started,
  TO_DATE(effective_end_date) AS dt_effective_ended,
  TO_DATE(freeze_start_date) AS dt_freeze_started,
  TO_DATE(freeze_until_date) AS dt_freeze_until,
  TO_DATE(projected_start_date) AS dt_projected_started,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_core_raw.per_all_assignments_m