SELECT
  business_group_id AS id_business_group,
  organization_id AS id_organization,
  attribute4 AS id_salu,
  attribute20 AS id_greenhouse,
  action_occurrence_id AS id_action_occurrence,
  organization_code,
  attribute1 AS cost_center_code,
  created_by,
  last_updated_by AS updated_by,
  attribute3 AS directorate,
  NULLIF(TRIM(attribute5), '-') AS business,
  NULLIF(TRIM(attribute6), '-') AS product,
  NULLIF(TRIM(attribute8), '-') AS vertical,
  attribute9 AS vice_presidency,
  NULLIF(TRIM(attribute10), '-') AS chapter,
  NULLIF(TRIM(attribute11), '-') AS brand,
  NULLIF(TRIM(attribute12), '-') AS structure,
  NULLIF(TRIM(attribute13), '-') AS team,
  NULLIF(TRIM(attribute15), '-') AS line,
  NULLIF(TRIM(attribute16), '-') AS name_owner_l1,
  NULLIF(TRIM(attribute17), '-') AS name_owner_l2,
  NULLIF(TRIM(attribute18), '-') AS name_owner_l3,
  NULLIF(TRIM(attribute19), '-') AS headcount_type,
  internal_external_flag AS organization_scope,
  CAST(object_version_number AS INT) AS object_version_number,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  TO_DATE(effective_start_date) AS dt_effective_started,
  COALESCE(
    NULLIF(TO_DATE(effective_end_date), DATE('4712-12-31')),
    DATE('9999-12-31')
  ) AS dt_effective_ended,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_core_raw.hr_all_organization_units_f