SELECT
  geography_id AS id_geography,
  import_batch_id AS id_import_batch,
  geography_element1_id AS id_geography_element1,
  geography_element2_id AS id_geography_element2,
  geography_element3_id AS id_geography_element3,
  geography_element4_id AS id_geography_element4,
  geography_element5_id AS id_geography_element5,
  geography_element6_id AS id_geography_element6,
  geography_element7_id AS id_geography_element7,
  geography_element8_id AS id_geography_element8,
  geography_element9_id AS id_geography_element9,
  geography_element10_id AS id_geography_element10,
  request_id AS id_request,
  created_by,
  last_updated_by AS updated_by,
  created_by_module,
  geography_type,
  geography_name,
  geography_use,
  geography_code,
  country_code,
  geography_element1,
  geography_element1_code,
  geography_element2,
  geography_element2_code,
  geography_element3,
  geography_element3_code,
  geography_element4,
  geography_element4_code,
  geography_element5,
  geography_element5_code,
  geography_element6,
  geography_element7,
  geography_element8,
  geography_element9,
  geography_element10,
  geography_number,
  timezone_code,
  job_definition_name,
  job_definition_package,
  default_geo_provider,
  default_geo_version,
  CAST(object_version_number AS INT) AS object_version_number,
  multiple_parent_flag = 'Y' AS is_multiple_parent,
  geocode_flag = 'Y' AS is_geocoding_enabled,
  hidden_flag = 'Y' AS is_hidden,
  TO_DATE(start_date) AS dt_started,
  TO_DATE(end_date) AS dt_ended,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_core_raw.hz_geographies
