SELECT
    grade_ladder_id AS id_grade_ladder,
    action_occurrence_id AS id_action_occurrence,
    grade_set_id AS id_grade_set,
    business_group_id AS id_business_group,
    legislative_data_group_id AS id_legislative_data_group,
    prog_action_id AS id_prog_action,
    prog_action_reason_id AS id_prog_action_reason,
    salary_action_id AS id_salary_action,
    salary_action_reason_id AS id_salary_action_reason,
    grade_type,
    auto_progression_code,
    progression_style_code,
    progression_date_code,
    auto_sal_change_code AS auto_salary_change_code,
    salary_change_date_code,
    salary_calc_method_code AS salary_calculation_method_code,
    rate_change_date_code,
    created_by,
    last_updated_by AS updated_by,
    CAST(object_version_number AS INT) AS object_version_number,
    active_status = 'A' AS is_active,
    update_salary_flag = 'Y' AS is_salary_updated,
    TO_DATE(effective_start_date) AS dt_effective_started,
    TO_DATE(effective_end_date) AS dt_effective_ended,
    TO_TIMESTAMP(creation_date) AS ts_created,
    TO_TIMESTAMP(last_update_date) AS ts_updated,
    NOW() AS ts_load,
    year,
    month,
    day
FROM
    datalake_pin_core_raw.per_grade_ladders_f