SELECT
  action_occurrence_id AS id_action_occurrence,
  job_id AS id_job,
  grade_ladder_id AS id_grade_ladder,
  job_family_id AS id_job_family,
  set_id AS id_set,
  business_group_id AS id_business_group,
  job_code,
  category_code,
  active_status,
  created_by,
  last_updated_by AS updated_by,
  attribute1 AS contribution_level,
  attribute3 AS work_arrangement,
  attribute4 AS weekly_hours,
  approval_authority,
  IF(med_checkup_req = 'Y', TRUE, FALSE) AS has_medical_checkup_requirement,
  IF(benchmark_job_flag = 'Y', TRUE, FALSE) AS is_benchmark_job,
  IF(attribute2 = 'Sim', TRUE, FALSE) AS is_time_clocking_required,
  CAST(object_version_number AS INT) AS object_version_number,
  CAST(attribute_number1 AS FLOAT) AS target_plr,
  CAST(attribute_number2 AS FLOAT) AS target_rvv,
  CAST(attribute_number3 AS FLOAT) AS target_sop,
  CAST(attribute_number4 AS FLOAT) AS target_hiring_sop,
  CAST(attribute_number5 AS FLOAT) AS target_bonus_tech_usd,
  CAST(attribute8 AS FLOAT) AS target_plr_salary_multiplier,
  TO_DATE(effective_end_date) AS dt_effective_ended,
  TO_DATE(effective_start_date) AS dt_effective_started,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_core_raw.per_jobs_f
