SELECT
  person_id AS id_person,
  person_legislative_id AS id_person_legislative,
  business_group_id AS id_business_group,
  created_by,
  last_updated_by AS updated_by,
  legislation_code,
  marital_status,
  sex,
  highest_education_level,
  attribute_category AS nationality,
  attribute1 AS electoral_zone,
  attribute2 AS polling_station,
  attribute4 AS vote_registration_number,
  attribute9 AS gender_identity,
  attribute10 AS sexual_orientation,
  attribute11 AS neurodiversity,
  attribute13 AS housing_type,
  attribute14 AS quinto_andar_joining_method,
  attribute15 AS country_situation,
  attribute26 AS disability_self_declaration_description,
  CAST(object_version_number AS INT) AS object_version_number,
  COALESCE(attribute6 = 'S', FALSE) AS has_disability,
  COALESCE(attribute5 = 'S', FALSE) AS has_salary_advance,
  TO_DATE(marital_status_date) AS dt_marital_status,
  TO_DATE(effective_end_date) AS dt_effective_ended,
  TO_DATE(effective_start_date) AS dt_effective_started,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_core_raw.per_people_legislative_f
