SELECT
  seniority_date_id AS id_seniority_date,
  business_group_id AS id_business_group,
  person_id AS id_person,
  level_object_id AS id_level_object,
  ess_request_id AS id_ess_request,
  CAST(seniority_field_number AS BIGINT) AS id_triggering_field_number,
  last_update_login AS id_last_update_session,
  seniority_date_code AS seniority_rule_code,
  calculation_type,
  level_code AS seniority_level_code,
  seniority_field AS triggering_field_code,
  seniority_field_key,
  record_creator AS created_by_process,
  created_by,
  last_updated_by,
  CAST(object_version_number AS INT) AS object_version_number,
  CAST(seniority_los_years AS INT) AS years_tenure,
  CAST(seniority_los_months AS INT) AS months_tenure,
  CAST(seniority_los_days AS INT) AS days_tenure,
  CAST(seniority_los_total_days AS INT) AS days_tenure_total,
  CAST(overlapping_period_in_days AS INT) AS days_overlapping_period,
  CAST(auto_adjustment_days AS INT) AS days_auto_adjustment,
  CAST(total_auto_adjustment_days AS INT) AS days_auto_adjustment_total,
  CAST(total_adjustment_days AS INT) AS days_adjustment_total,
  auto_adjustment_comments,
  TO_DATE(effective_start_date) AS dt_effective_started,
  TO_DATE(effective_end_date) AS dt_effective_ended,
  TO_DATE(entry_date) AS dt_first_assigned,
  TO_DATE(seniority_date) AS dt_seniority,
  TO_DATE(base_seniority_date) AS dt_base_seniority,
  TO_DATE(exit_date) AS dt_exited,
  TO_DATE(last_ess_run_date) AS dt_last_ess_run,
  TO_TIMESTAMP(creation_date) AS ts_created,
  TO_TIMESTAMP(last_update_date) AS ts_updated,
  NOW() AS ts_load,
  year,
  month,
  day
FROM
  datalake_pin_core_raw.per_seniority_dates_f
