SELECT
  id,
  REV,
  REVTYPE AS rev_type,
  bairro AS neighborhood,
  cep AS zip_code,
  cidade AS city,
  complemento AS complement,
  cpf,
  dataExpedicaoRG AS dt_rg_created,
  dataNascimento AS dt_birth,
  email,
  endereco AS address,
  estadoCivil AS marital_status,
  legalRepresentative_cpf AS legal_representative_cpf,
  legalRepresentative_email AS legal_representative_email,
  legalRepresentative_nome AS legal_representative_name,
  legalRepresentative_rg AS legal_representative_rg,
  nacionalidade AS nationality,
  nome AS name,
  numero AS number,
  orgaoExpedidor AS issuing_body,
  profissao AS profession,
  rg,
  sexo AS gender,
  telefone AS phone_number,
  telefoneSecundario AS secondary_phone,
  tipo AS type,
  usuario_id AS id_user,
  vaiMorar AS will_live,
  withRepresentative AS is_with_representative,
  contrato_id AS id_contract,
  estado_id AS id_state,
  usuarioId_MOD AS mod_id_user
FROM
  datalake_ebdb_test_raw.contratopessoa_aud