SELECT
    id,
    insurance_id AS id_insurance,
    rev,
    revend AS rev_end,
    revtype AS rev_type,
    requester,
    invoice_management_type,
    approver_user_id AS id_approver_user,
    status,
    canceller_user_id AS id_canceller_user,
    cancellation_reason,
    created_at_mod AS mod_created_at,
    updated_at_mod AS mod_updated_at,
    requester_mod AS mod_requester,
    external_policy_start_date_mod AS mod_date_external_policy_start,
    external_policy_end_date_mod AS mod_date_external_policy_end,
    start_date_mod AS mod_date_start,
    end_date_mod AS mod_date_end,
    insurance_id_mod AS mod_id_insurance,
    invoice_management_type_mod AS mod_invoice_management_type,
    approver_user_id_mod AS mod_id_approver_user,
    approved_at_mod AS mod_approved_at,
    status_mod AS mod_status,
    cancelled_at_mod AS mod_cancelled_at,
    canceller_user_id_mod AS mod_id_canceller_user,
    cancellation_reason_mod AS mod_cancellation_reason,
    DATE(external_policy_start_date) AS dt_external_policy_start,
    DATE(external_policy_end_date) AS dt_external_policy_end,
    DATE(start_date) AS dt_start,
    DATE(end_date) AS dt_end,
    TIMESTAMP(approved_at) AS ts_approved,
    TIMESTAMP(cancelled_at) AS ts_cancelled,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated,
    year,
    month,
    day
FROM
    datalake_betopera_raw.insurance_optout_aud
