SELECT
    id_entry,
    id_invoice,
    sk_contract,
    sk_invoice_reversed_entry,
    version,
    accounting_version,
    locale,
    localidade,
    guarantee,
    rental_administrator,
    bill_item,
    description,
    purpose,
    invoice_account_type,
    from_account_type,
    to_account_type,
    account_type,
    account_classification,
    status,
    entry_status,
    payment_status,
    reason,
    producer,
    entry_producer,
    closing_mode,
    paid_via,
    entry_created_time,
    contract_status,
    conta_contabil,
    conta_contabil_secundaria,
    is_contract_b2b,
    is_rental_paid_in_advance,
    is_reversed,
    is_write_off,
    is_not_invoiceable_inconsiderable,
    is_not_invoicable,
    has_negotiation,
    has_installments,
    due_amount,
    invoice_due_amount,
    invoice_paid_amount,
    accrual_year_month,
    entry_accrual_year_month,
    entry_creation_accrual_year_month,
    ended_before_started,
    pp_pays,
    entry_sort_ascend,
    entry_by_accrual_sort_ascend,
    is_cap,
    only_one_sided,
    post_divergence,
    conta_resultado,
    has_paid_amount,
    has_receivable_amount,
    is_not_invoiceable_inconsiderable_workaround,
    is_not_invoiceable_inconsiderable_early_termination,
    DATE(entry_created_date) AS entry_created_date,
    DATE(invoice_created_date) AS invoice_created_date,
    DATE(invoice_due_date) AS invoice_due_date,
    DATE(invoice_paid_date) AS invoice_paid_date,
    DATE(invoice_canceled_date) AS invoice_canceled_date,
    DATE(invoice_reversal_date) AS invoice_reversal_date,
    DATE(invoice_write_off_date) AS invoice_write_off_date,
    invoice_paid_date_next_business_day,
    real_invoice_paid_date,
    contract_start,
    contract_annulment,
    ts_retsuko_updated,
    NOW() AS ts_snapshot,
    YEAR(CURRENT_DATE()) AS year,
    MONTH(CURRENT_DATE()) AS month,
    DAY(CURRENT_DATE()) AS day
FROM
    datalake_accounting_funnel.cap_union_invoice
