SELECT
  id,
  atualizadoEm AS ts_updated,
  criadoEm AS ts_created,
  dataVigencia AS ts_validity,
  status,
  contrato_id AS id_contrato,
  fluxoLocacao_id AS id_rent_flow,
  dataEnvioApolice AS ts_policy_sent,
  dataEnvioEmailVigenciaLongaInquilino AS ts_long_form_policy_sent_via_email_tenant,
  dataEnvioEmailVigenciaLongaProprietario AS ts_long_form_policy_sent_via_email_landlord,
  dataSolicitacaoApolice AS ts_policy_solicited,
  googleDriveId AS id_google_drive,
  termoEntregaItens AS terms_of_item_delivery,
  boletoCondominioTransferencia AS hAS_transfered_payment_slip_condominium,
  dataConfirmaDadosMudanca  AS ts_confirmed_data_change,
  numeroBoletosAbertos AS number_of_open_payments,
  valorBoletoAberto AS value_of_open_payment,
  openEnergyBill AS open_energy_bill,
  openGASBill AS open_gAS_bill,
  openWaterBill AS open_water_bill,
  shortTermSent AS ts_short_term_sent,
  keyLocation AS key_location,
  keyLocationDetails AS key_location_details,
  missingFinanceData AS is_missing_financial_data,
  shortTermTenantSent AS ts_short_term_tenant_sent,
  shortTermLandlordSent AS ts_short_term_landlord_sent,
  version
FROM datalake_ebdb_test_raw.onboarding
