select
    id,
    zendesk_ticket_id as id_ticket,
    department_id as id_department,
    abandon_time,
    agent_ids,
    agent_names,
    conversions,
    count,
    department_name,
    duration,
    engagements,
    history,
    referrer_search_engine,
    referrer_search_terms,
    response_time,
    session,
    skills_requested,
    started_by,
    tags,
    type,
    visitor,
    webpath,
    comment,
    rating,
    deleted as is_deleted,
    dropped as is_dropped,
    missed as is_missed,
    unread as is_unread,
    proactive as is_proactive,
    triggered as is_triggered,
    skills_fulfilled as is_skills_fulfilled,
    timestamp(timestamp)  as ts_created,
    timestamp(update_timestamp)  as ts_updated,
    timestamp(end_timestamp ) as ts_ended,
    year,
    month,
    day
from
    {db}.chats
where
  year={year} and month={month} and day={day}