DROP TABLE IF EXISTS braze.fact_campaign_user_dispatch;
CREATE TABLE braze.fact_campaign_user_dispatch (
 	sk_braze_user VARCHAR,
 	sk_user_dispatch VARCHAR,
 	sk_campaign VARCHAR,
 	sk_variant_campaign VARCHAR,
 	user_type VARCHAR,
	event_channel VARCHAR,
	ts_email_sent TIMESTAMP,
	ts_email_delivered TIMESTAMP,
	ts_email_bounced TIMESTAMP,
	ts_email_unsubscribed TIMESTAMP,
	ts_email_spammed TIMESTAMP,
	ts_push_sent TIMESTAMP,
	ts_push_bounced TIMESTAMP,
	ts_sms_sent TIMESTAMP,
	ts_sms_send_to_carried TIMESTAMP,
	ts_sms_delivered TIMESTAMP,
	ts_sms_rejected TIMESTAMP,
	ts_sms_delivery_failed TIMESTAMP,
	ts_webhook_sent TIMESTAMP,
 	ts_inapp_impressioned TIMESTAMP,
 	total_email_opened BIGINT,
	ts_email_first_opened TIMESTAMP,
	ts_email_last_opened TIMESTAMP,
	total_email_clicked BIGINT,
	ts_email_first_clicked TIMESTAMP,
	ts_email_last_clicked TIMESTAMP,
	total_push_opened BIGINT,
	ts_push_first_opened TIMESTAMP,
	ts_push_last_opened TIMESTAMP,
	ts_load TIMESTAMP
);
ALTER TABLE braze.fact_campaign_user_dispatch OWNER TO airflow;
