SELECT
    id_earning AS sk_earning,
    id_earning_source AS sk_earning_source,
    id_revenue_share AS sk_revenue_share,
    id_contract AS sk_contract,
    id_sales_flow AS sk_sales_flow,
    id_author AS sk_author,
    uuid_cart,
    id_business_unit AS sk_business_unit,
    uuid_company,
    uuid_person,
    business_context,
    domain_type,
    incentive_system,
    calculated_from,
    currency,
    external_receiver_type,
    earning_status,
    earning_status_reason,
    invalidation_reason,
    earning_source_status,
    earning_source_status_reason,
    revenue_share_relation_type,
    revenue_share_type,
    base_amount,
    revenue_share_total_amount,
    revenue_amount,
    revenue_percentage,
    incentive_engine_external_condition_type,
    tier_name,
    tier_priority,
    classifier_min_score,
    classifier_resume,
    qualifier_min_score,
    qualifier_resume,
    is_authored_by_system,
    ts_created,
    ts_invalidated,
    ts_updated,
    dt_load,
    year,
    month,
    day
FROM
    datalake_big_agent.earnings
