SELECT
    NULLIF(city_group, '') AS city_group,
    NULLIF(planning_conversion, '') AS planning_conversion,
    NULLIF(planning_operation, '') AS planning_operation,
    NULLIF(planning_cluster, '') AS planning_cluster,
    NULLIF(company_report_origin, '') AS company_report_origin,    
    CAST(REPLACE(NULLIF(prospects_fr, ''), ',', '') AS FLOAT) AS prospects_fr,
    CAST(REPLACE(NULLIF(qualifieds_fr, ''), ',', '') AS FLOAT) AS qualifieds_fr,
    CAST(REPLACE(NULLIF(available_qualifieds_fr, ''), ',', '') AS FLOAT) AS available_qualifieds_fr,
    CAST(REPLACE(NULLIF(opportunities_fr, ''), ',', '') AS FLOAT) AS opportunities_fr, 
    CAST(REPLACE(NULLIF(first_listings_fr, ''), ',', '') AS FLOAT) AS first_listings_fr,
    CAST(REPLACE(NULLIF(prospects_fs, ''), ',', '') AS FLOAT) AS prospects_fs,
    CAST(REPLACE(NULLIF(qualifieds_fs, ''), ',', '') AS FLOAT) AS qualifieds_fs,
    CAST(REPLACE(NULLIF(available_qualifieds_fs, ''), ',', '') AS FLOAT) AS available_qualifieds_fs,
    CAST(REPLACE(NULLIF(opportunities_fs, ''), ',', '') AS FLOAT) AS opportunities_fs, 
    CAST(REPLACE(NULLIF(first_listings_fs, ''), ',', '') AS FLOAT) AS first_listings_fs,
    CAST(REPLACE(NULLIF(fator_prospects, ''), ',', '') AS FLOAT) AS fator_prospects,
    CAST(REPLACE(NULLIF(fator_qualifieds, ''), ',', '') AS FLOAT) AS fator_qualifieds,
    CAST(REPLACE(NULLIF(fator_available_qualifieds, ''), ',', '') AS FLOAT) AS fator_available_qualifieds,
    CAST(REPLACE(NULLIF(fator_opportunities, ''), ',', '') AS FLOAT) AS fator_opportunities, 
    CAST(REPLACE(NULLIF(fator_first_listings, ''), ',', '') AS FLOAT) AS fator_first_listings,
    CAST(REPLACE(NULLIF(prospects_fs, ''), ',', '') AS FLOAT) AS fator_prospects_aux_2,
    CAST(REPLACE(NULLIF(qualifieds_fs, ''), ',', '') AS FLOAT) AS fator_qualifieds_aux_2,
    CAST(REPLACE(NULLIF(available_qualifieds_fs, ''), ',', '') AS FLOAT) AS fator_available_qualifieds_aux_2,
    CAST(REPLACE(NULLIF(opportunities_fs, ''), ',', '') AS FLOAT) AS fator_opportunities_aux_2, 
    CAST(REPLACE(NULLIF(first_listings_fs, ''), ',', '') AS FLOAT) AS fator_first_listings_aux_2,
    CAST(REPLACE(NULLIF(prospects_fs, ''), ',', '') AS FLOAT) AS volume_prospects_unique,
    CAST(REPLACE(NULLIF(qualifieds_fs, ''), ',', '') AS FLOAT) AS volume_qualifieds_unique,
    CAST(REPLACE(NULLIF(available_qualifieds_fs, ''), ',', '') AS FLOAT) AS volume_available_qualifieds_unique,
    CAST(REPLACE(NULLIF(opportunities_fs, ''), ',', '') AS FLOAT) AS volume_opportunities_unique, 
    CAST(REPLACE(NULLIF(first_listings_fs, ''), ',', '') AS FLOAT) AS volume_first_listings_unique,
    CAST(NULLIF(year_month, '') AS DATE) AS year_month_date,
    CAST(NULLIF(date, '') AS DATE) AS date
FROM
    datalake_gsheets_raw.supply_funnel_unique