WITH closing_union AS(
  SELECT
    id_invoice,
    id_contract,
    accrual_year_month,
    closing_month_status,
    due_amount,
    frequency,
    invoice_type,
    city,
    contract_guarantee,
    is_guarantee_paid,
    is_before_started,
    is_before_started_raw,
    is_canceled_in_dead_time,
    is_international,
    is_paid_in_closing_day,
    is_writtendown_in_dead_time,
    is_write_off,
    is_contract_write_off,
    has_repair_offboarding_bill_item,
    paid_amount,
    payment_status,
    user,
    origin_factor,
    dt_closing,
    dt_contract_signature,
    dt_annulment,
    dt_due,
    dt_paid,
    dt_sent,
    dt_write_off,
    dt_snapshot
  FROM
    datalake_losses.closing

  UNION

  SELECT
    id_invoice,
    id_contract,
    accrual_year_month,
    closing_month_status,
    due_amount,
    frequency,
    invoice_type,
    NULL AS city,
    contract_guarantee,
    is_guarantee_paid,
    is_before_started,
    is_before_started_raw,
    is_canceled_in_dead_time,
    is_international,
    is_paid_in_closing_day,
    is_writtendown_in_dead_time,
    NULL AS is_write_off,
    NULL AS is_contract_write_off,
    NULL AS has_repair_offboarding_bill_item,
    paid_amount,
    payment_status,
    user,
    origin_factor,
    dt_closing,
    dt_contract_signature,
    dt_annulment,
    dt_due,
    dt_paid,
    dt_sent,
    NULL AS dt_write_off,
    dt_snapshot
  FROM
    datalake_losses.historical_closing
)
SELECT
    COALESCE(id_invoice, -1) AS sk_invoice,
    COALESCE(id_contract, -1) AS sk_contract,
    accrual_year_month,
    closing_month_status,
    city,
    contract_guarantee,
    due_amount,
    invoice_type,
    paid_amount as invoice_paid_amount,
    is_before_started,
    is_before_started_raw,
    is_canceled_in_dead_time,
    is_guarantee_paid,
    is_international,
    is_paid_in_closing_day,
    is_writtendown_in_dead_time,
    is_write_off,
    is_contract_write_off,
    has_repair_offboarding_bill_item,
    payment_status,
    origin_factor,
    dt_annulment,
    dt_closing,
    dt_contract_signature,
    dt_due,
    dt_paid,
    dt_sent,
    dt_write_off,
    dt_snapshot,
    NOW() AS ts_load
FROM
    closing_union
