WITH closing_union AS(
  SELECT
    id_invoice,
    id_contract,
    accrual_year_month,
    closing_month_status,
    due_amount,
    frequency,
    invoice_type,
    city,
    contract_guarantee,
    is_guarantee_paid,
    is_before_started,
    is_before_started_raw,
    is_canceled_in_dead_time,
    is_international,
    is_paid_in_closing_day,
    is_writtendown_in_dead_time,
    is_write_off,
    is_contract_write_off,
    has_repair_offboarding_bill_item,
    paid_amount,
    payment_status,
    user,
    origin_factor,
    dt_created,
    dt_canceled,
    dt_closing,
    dt_contract_signature,
    dt_annulment,
    dt_due,
    dt_due_adjusted_retsuko,
    dt_paid,
    dt_sent,
    dt_write_off,
    dt_snapshot
  FROM
    datalake_losses.closing

  UNION

  SELECT
    c.id_invoice,
    c.id_contract,
    c.accrual_year_month,
    c.closing_month_status,
    c.due_amount,
    c.frequency,
    c.invoice_type,
    NULL AS city,
    c.contract_guarantee,
    c.is_guarantee_paid,
    c.is_before_started,
    c.is_before_started_raw,
    c.is_canceled_in_dead_time,
    c.is_international,
    c.is_paid_in_closing_day,
    c.is_writtendown_in_dead_time,
    FALSE AS is_write_off,
    FALSE AS is_contract_write_off,
    FALSE AS has_repair_offboarding_bill_item,
    c.paid_amount,
    c.payment_status,
    c.user,
    c.origin_factor,
    NULL AS dt_created,
    NULL AS dt_canceled,
    c.dt_closing,
    c.dt_contract_signature,
    c.dt_annulment,
    c.dt_due,
    IF(dd.is_brz_fintech_business_day, c.dt_due, dd.next_brz_fintech_business_day) AS dt_due_adjusted_retsuko,
    c.dt_paid,
    c.dt_sent,
    NULL AS dt_write_off,
    c.dt_snapshot
  FROM
    datalake_losses.historical_closing AS c
  LEFT JOIN
      dw_public.dim_date dd
            ON (dd.sk_date = CAST(DATE_FORMAT(DATE(c.dt_due), "yyyyMMdd") AS BIGINT))

)
SELECT
    COALESCE(id_invoice, -1) AS sk_invoice,
    COALESCE(id_contract, -1) AS sk_contract,
    accrual_year_month,
    closing_month_status,
    city,
    contract_guarantee,
    due_amount,
    invoice_type,
    paid_amount as invoice_paid_amount,
    is_before_started,
    is_before_started_raw,
    is_canceled_in_dead_time,
    is_guarantee_paid,
    is_international,
    is_paid_in_closing_day,
    is_writtendown_in_dead_time,
    is_write_off,
    is_contract_write_off,
    has_repair_offboarding_bill_item,
    payment_status,
    origin_factor,
    dt_created,
    dt_canceled,
    dt_annulment,
    dt_closing,
    dt_contract_signature,
    dt_due,
    dt_due_adjusted_retsuko,
    dt_paid,
    dt_sent,
    dt_write_off,
    dt_snapshot,
    NOW() AS ts_load
FROM
    closing_union
