SELECT
    COALESCE(id_contract, -1) AS sk_contract,
    COALESCE(id_invoice, -1) AS sk_invoice,
    due_amount,
    provision_balance_p1_delay_d,
    provision_balance_p2_delay_d,
    provision_balance_p3_delay_d,
    provision_balance_p4_delay_d, 
    provision_balance_p1_delay_b, 
    provision_balance_p2_delay_b, 
    provision_balance_p3_delay_b, 
    provision_balance_p4_delay_b, 
    provision_balance_p1_delay_a, 
    provision_balance_p2_delay_a,
    provision_balance_p3_delay_a,
    provision_balance_p4_delay_a,
    provision_balance_p1_delay_c,
    provision_balance_p2_delay_c,
    provision_balance_p3_delay_c,
    provision_balance_p4_delay_c,
    user,
    dt_closing,
    NOW() AS ts_load
FROM
    datalake_losses.provision