WITH union_cte AS (
    SELECT *
    FROM
        datalake_nexxera_clean.cnab_charges_recupera_quintoandar

    UNION ALL


    SELECT *
    FROM
        datalake_nexxera_clean.cnab_charges_recupera_velo

    UNION ALL


    SELECT *
    FROM
        datalake_nexxera_clean.cnab_charges_recupera_velo_2
),
df AS (

    SELECT DISTINCT
        id_bank,
        id_document_type,
        recupera_creditor_name,
        bank_agency,
        bank_account,
        account_verification_digit,
        TRIM(cpf_cnpj) AS cpf_cnpj,
        TRIM(company_use) AS company_use,
        CONCAT(TRIM(our_number), TRIM(our_number_verification_digit)) AS our_number,
        TRIM(document_number) AS document_number,
        TRIM(payers_name) AS payers_name,
        TRIM(occurrence_code) AS occurrence_code,
        CASE
            WHEN OCCURRENCE_CODE = '02' THEN 'ENTRADA CONFIRMADA COM POSSIBILIDADE DE MENSAGEM (NOTA 20 – TABELA 10)'
            WHEN OCCURRENCE_CODE = '03' THEN 'ENTRADA REJEITADA (NOTA 20 – TABELA 1)'
            WHEN OCCURRENCE_CODE = '04' THEN 'ALTERAÇÃO DE DADOS – NOVA ENTRADA OU ALTERAÇÃO/EXCLUSÃO DE DADOS ACATADA'
            WHEN OCCURRENCE_CODE = '05' THEN 'ALTERAÇÃO DE DADOS – BAIXA'
            WHEN OCCURRENCE_CODE = '06' THEN 'LIQUIDAÇÃO NORMAL'
            WHEN OCCURRENCE_CODE = '07' THEN 'LIQUIDAÇÃO PARCIAL – COBRANÇA INTELIGENTE (B2B)'
            WHEN OCCURRENCE_CODE = '08' THEN 'LIQUIDAÇÃO EM CARTÓRIO'
            WHEN OCCURRENCE_CODE = '09' THEN 'BAIXA SIMPLES'
            WHEN OCCURRENCE_CODE = '10' THEN 'BAIXA POR TER SIDO LIQUIDADO'
            WHEN OCCURRENCE_CODE = '11' THEN 'EM SER (SÓ NO RETORNO MENSAL)'
            WHEN OCCURRENCE_CODE = '12' THEN 'ABATIMENTO CONCEDIDO'
            WHEN OCCURRENCE_CODE = '13' THEN 'ABATIMENTO CANCELADO'
            WHEN OCCURRENCE_CODE = '14' THEN 'VENCIMENTO ALTERADO'
            WHEN OCCURRENCE_CODE = '15' THEN 'BAIXAS REJEITADAS (NOTA 20 – TABELA 4)'
            WHEN OCCURRENCE_CODE = '16' THEN 'INSTRUÇÕES REJEITADAS (NOTA 20 – TABELA 3)'
            WHEN OCCURRENCE_CODE = '17' THEN 'ALTERAÇÃO/EXCLUSÃO DE DADOS REJEITADOS (NOTA 20 – TABELA 2)'
            WHEN OCCURRENCE_CODE = '18' THEN 'COBRANÇA CONTRATUAL – INSTRUÇÕES/ALTERAÇÕES REJEITADAS/PENDENTES (NOTA 20 – TABELA 5)'
            WHEN OCCURRENCE_CODE = '19' THEN 'CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE PROTESTO'
            WHEN OCCURRENCE_CODE = '20' THEN 'CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE SUSTAÇÃO DE PROTESTO /TARIFA'
            WHEN OCCURRENCE_CODE = '21' THEN 'CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE NÃO PROTESTAR'
            WHEN OCCURRENCE_CODE = '23' THEN 'TÍTULO ENVIADO A CARTÓRIO/TARIFA'
            WHEN OCCURRENCE_CODE = '24' THEN 'INSTRUÇÃO DE PROTESTO REJEITADA / SUSTADA / PENDENTE (NOTA 20 – TABELA 7)'
            WHEN OCCURRENCE_CODE = '25' THEN 'ALEGAÇÕES DO PAGADOR (NOTA 20 – TABELA 6)'
            WHEN OCCURRENCE_CODE = '26' THEN 'TARIFA DE AVISO DE COBRANÇA'
            WHEN OCCURRENCE_CODE = '27' THEN 'TARIFA DE EXTRATO POSIÇÃO (B40X)'
            WHEN OCCURRENCE_CODE = '28' THEN 'TARIFA DE RELAÇÃO DAS LIQUIDAÇÕES'
            WHEN OCCURRENCE_CODE = '29' THEN 'TARIFA DE MANUTENÇÃO DE TÍTULOS VENCIDOS'
            WHEN OCCURRENCE_CODE = '30' THEN 'DÉBITO MENSAL DE TARIFAS (PARA ENTRADAS E BAIXAS)'
            WHEN OCCURRENCE_CODE = '32' THEN 'BAIXA POR TER SIDO PROTESTADO'
            WHEN OCCURRENCE_CODE = '33' THEN 'CUSTAS DE PROTESTO'
            WHEN OCCURRENCE_CODE = '34' THEN 'CUSTAS DE SUSTAÇÃO'
            WHEN OCCURRENCE_CODE = '35' THEN 'CUSTAS DE CARTÓRIO DISTRIBUIDOR'
            WHEN OCCURRENCE_CODE = '36' THEN 'CUSTAS DE EDITAL'
            WHEN OCCURRENCE_CODE = '37' THEN 'TARIFA DE EMISSÃO DE BOLETO/TARIFA DE ENVIO DE DUPLICATA'
            WHEN OCCURRENCE_CODE = '38' THEN 'TARIFA DE INSTRUÇÃO'
            WHEN OCCURRENCE_CODE = '39' THEN 'TARIFA DE OCORRÊNCIAS'
            WHEN OCCURRENCE_CODE = '40' THEN 'TARIFA MENSAL DE EMISSÃO DE BOLETO/TARIFA MENSAL DE ENVIO DE DUPLICATA'
            WHEN OCCURRENCE_CODE = '41' THEN 'DÉBITO MENSAL DE TARIFAS – EXTRATO DE POSIÇÃO (B4EP/B4OX)'
            WHEN OCCURRENCE_CODE = '42' THEN 'DÉBITO MENSAL DE TARIFAS – OUTRAS INSTRUÇÕES'
            WHEN OCCURRENCE_CODE = '43' THEN 'DÉBITO MENSAL DE TARIFAS – MANUTENÇÃO DE TÍTULOS VENCIDOS'
            WHEN OCCURRENCE_CODE = '44' THEN 'DÉBITO MENSAL DE TARIFAS – OUTRAS OCORRÊNCIAS'
            WHEN OCCURRENCE_CODE = '45' THEN 'DÉBITO MENSAL DE TARIFAS – PROTESTO'
            WHEN OCCURRENCE_CODE = '46' THEN 'DÉBITO MENSAL DE TARIFAS – SUSTAÇÃO DE PROTESTO'
            WHEN OCCURRENCE_CODE = '47' THEN 'BAIXA COM TRANSFERÊNCIA PARA DESCONTO'
            WHEN OCCURRENCE_CODE = '48' THEN 'CUSTAS DE SUSTAÇÃO JUDICIAL'
            WHEN OCCURRENCE_CODE = '51' THEN 'TARIFA MENSAL REF A ENTRADAS BANCOS CORRESPONDENTES NA CARTEIRA'
            WHEN OCCURRENCE_CODE = '52' THEN 'TARIFA MENSAL BAIXAS NA CARTEIRA'
            WHEN OCCURRENCE_CODE = '53' THEN 'TARIFA MENSAL BAIXAS EM BANCOS CORRESPONDENTES NA CARTEIRA'
            WHEN OCCURRENCE_CODE = '54' THEN 'TARIFA MENSAL DE LIQUIDAÇÕES NA CARTEIRA'
            WHEN OCCURRENCE_CODE = '55' THEN 'TARIFA MENSAL DE LIQUIDAÇÕES EM BANCOS CORRESPONDENTES NA CARTEIRA'
            WHEN OCCURRENCE_CODE = '56' THEN 'CUSTAS DE IRREGULARIDADE'
            WHEN OCCURRENCE_CODE = '57' THEN 'INSTRUÇÃO CANCELADA (NOTA 20 – TABELA 8)'
            WHEN OCCURRENCE_CODE = '59' THEN 'BAIXA POR CRÉDITO EM C/C ATRAVÉS DO SISPAG'
            WHEN OCCURRENCE_CODE = '60' THEN 'ENTRADA REJEITADA CARNÊ (NOTA 20 – TABELA 1)'
            WHEN OCCURRENCE_CODE = '61' THEN 'TARIFA EMISSÃO AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)'
            WHEN OCCURRENCE_CODE = '62' THEN 'DÉBITO MENSAL DE TARIFA – AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)'
            WHEN OCCURRENCE_CODE = '63' THEN 'TÍTULO SUSTADO JUDICIALMENTE'
            WHEN OCCURRENCE_CODE = '64' THEN 'ENTRADA CONFIRMADA COM RATEIO DE CRÉDITO'
            WHEN OCCURRENCE_CODE = '65' THEN 'PAGAMENTO COM CHEQUE – AGUARDANDO COMPENSAÇÃO'
            WHEN OCCURRENCE_CODE = '69' THEN 'CHEQUE DEVOLVIDO (NOTA 20 – TABELA 9)'
            WHEN OCCURRENCE_CODE = '71' THEN 'ENTRADA REGISTRADA, AGUARDANDO AVALIAÇÃO'
            WHEN OCCURRENCE_CODE = '72' THEN 'BAIXA POR CRÉDITO EM C/C ATRAVÉS DO SISPAG SEM TÍTULO CORRESPONDENTE'
            WHEN OCCURRENCE_CODE = '73' THEN 'CONFIRMAÇÃO DE ENTRADA NA COBRANÇA SIMPLES – ENTRADA NÃO ACEITA NA COBRANÇA CONTRATUAL'
            WHEN OCCURRENCE_CODE = '74' THEN 'INSTRUÇÃO DE NEGATIVAÇÃO EXPRESSA REJEITADA (NOTA 20 – TABELA 11)'
            WHEN OCCURRENCE_CODE = '75' THEN 'CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA'
            WHEN OCCURRENCE_CODE = '76' THEN 'CHEQUE COMPENSADO'
            WHEN OCCURRENCE_CODE = '77' THEN 'CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE EXCLUSÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA'
            WHEN OCCURRENCE_CODE = '78' THEN 'CONFIRMAÇÃO DE RECEBIMENTO DE INSTRUÇÃO DE CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA'
            WHEN OCCURRENCE_CODE = '79' THEN 'NEGATIVAÇÃO EXPRESSA INFORMACIONAL (NOTA 20 – TABELA 12)'
            WHEN OCCURRENCE_CODE = '80' THEN 'CONFIRMAÇÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA – TARIFA'
            WHEN OCCURRENCE_CODE = '82' THEN 'CONFIRMAÇÃO DO CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA – TARIFA'
            WHEN OCCURRENCE_CODE = '83' THEN 'CONFIRMAÇÃO DE EXCLUSÃO DE ENTRADA EM NEGATIVAÇÃO EXPRESSA POR LIQUIDAÇÃO – TARIFA'
            WHEN OCCURRENCE_CODE = '85' THEN 'TARIFA POR BOLETO (ATÉ 03 ENVIOS) COBRANÇA ATIVA ELETRÔNICA'
            WHEN OCCURRENCE_CODE = '86' THEN 'TARIFA EMAIL COBRANÇA ATIVA ELETRÔNICA'
            WHEN OCCURRENCE_CODE = '87' THEN 'TARIFA SMS COBRANÇA ATIVA ELETRÔNICA'
            WHEN OCCURRENCE_CODE = '88' THEN 'TARIFA MENSAL POR BOLETO (ATÉ 03 ENVIOS) COBRANÇA ATIVA ELETRÔNICA'
            WHEN OCCURRENCE_CODE = '89' THEN 'TARIFA MENSAL EMAIL COBRANÇA ATIVA ELETRÔNICA'
            WHEN OCCURRENCE_CODE = '90' THEN 'TARIFA MENSAL SMS COBRANÇA ATIVA ELETRÔNICA'
            WHEN OCCURRENCE_CODE = '91' THEN 'TARIFA MENSAL DE EXCLUSÃO DE ENTRADA DE NEGATIVAÇÃO EXPRESSA'
            WHEN OCCURRENCE_CODE = '92' THEN 'TARIFA MENSAL DE CANCELAMENTO DE NEGATIVAÇÃO EXPRESSA'
            WHEN OCCURRENCE_CODE = '93' THEN 'TARIFA MENSAL DE EXCLUSÃO DE NEGATIVAÇÃO EXPRESSA POR LIQUIDAÇÃO'
        END AS occurrence_code_description,
        file_name,
        regexp_extract(file_name, r'_([0-9]+)\.', 1) AS file_name_sulfix,
        due_amount,
        interest_amount,
        net_amount,
        billing_fee_amount,
        iof_amount,
        rebate_amount,
        discount_amount,
        others_credit_amount,
        dt_due,
        dt_credit,
        dt_occurrence_code,
        ts_ingested,
        year,
        month,
        day
    FROM
        union_cte
)

SELECT DISTINCT
    id_bank,
    id_document_type,
    recupera_creditor_name,
    bank_agency,
    bank_account,
    account_verification_digit,
    cpf_cnpj,
    company_use,
    our_number,
    document_number,
    payers_name,
    occurrence_code,
    occurrence_code_description,
    file_name,
    ROW_NUMBER() OVER (PARTITION BY our_number ORDER BY year, month, day, file_name_sulfix) AS payment_attempts,
    IF(ROW_NUMBER() OVER (PARTITION BY our_number ORDER BY year DESC, month DESC, day DESC, file_name_sulfix DESC) = 1, TRUE, FALSE) AS is_latest_attempt,
    due_amount,
    interest_amount,
    net_amount,
    billing_fee_amount,
    iof_amount,
    rebate_amount,
    discount_amount,
    others_credit_amount,
    dt_due,
    dt_credit,
    dt_occurrence_code,
    ts_ingested,
    year,
    month,
    day
FROM
    df
