SELECT 
    id,
    charge_id AS id_charge, 
    requester_id AS id_requester, 
    transaction_id AS id_transaction,
    due_amount,
    interest_amount,
    fine_amount,
    paid_amount,
    interest_amount_percentage,
    fine_amount_percentage,
    status,
    payer_identifiable_document,
    beneficiary_identifiable_document,
    your_number,
    barcode,
    payer_name,
    payer_person_type,
    payer_email,
    payer_city,
    payer_neighborhood,
    payer_state,
    payer_street_address,
    payer_zipcode,
    beneficiary_name,
    interest_type,
    fine_type,
    beneficiary_account,
    beneficiary_agency,
    beneficiary_dac,
    our_number_verification_digit,
    charge_messages,
    typeable_line,
    requester_name,
    our_number,
    pix_link,
    emv,
    qr_code,
    operation_history,
    DATE(due_date) AS dt_due, 
    DATE(emission_date) AS dt_emission, 
    DATE(paid_at) AS dt_paid, 
    DATE(credit_date) AS dt_credit,
    DATE(interest_start_at) AS dt_interest_start, 
    DATE(fine_start_at) AS dt_fine_start, 
    DATE(last_date_to_pay) AS dt_last_to_pay, 
    TIMESTAMP(started_processing_at) AS ts_started_processing,
    TIMESTAMP(created_at) AS ts_created, 
    TIMESTAMP(updated_at) AS ts_updated
FROM 
    datalake_checkout_raw.bolecode