SELECT 
    id, 
    business_entity_id AS id_business_entity, 
    finance_entity_id AS id_finance_entity, 
    charge_id AS id_charge, 
    requester_id AS id_requester, 
    CAST(due_amount AS DOUBLE) AS due_amount, 
    CAST(interest_amount AS DOUBLE) AS interest_amount, 
    CAST(fine_amount AS DOUBLE) AS fine_amount, 
    CAST(paid_amount AS DOUBLE) AS paid_amount, 
    CAST(interest_amount_percentage AS DOUBLE) AS interest_amount_percentage, 
    CAST(fine_amount_percentage AS DOUBLE) AS fine_amount_percentage, 
    CAST(interest_paid_amount AS DOUBLE) AS interest_paid_amount,
    CAST(fine_paid_amount AS DOUBLE) AS fine_paid_amount,
    status, 
    payer_identifiable_document, 
    beneficiary_identifiable_document, 
    your_number, 
    barcode, 
    payer_name, 
    payer_person_type, 
    payer_email, 
    payer_city, 
    payer_neighborhood, 
    payer_state, 
    payer_street_address, 
    payer_zipcode, 
    beneficiary_name, 
    interest_type, 
    fine_type, 
    beneficiary_account, 
    beneficiary_agency, 
    beneficiary_dac, 
    our_number_verification_digit, 
    charge_messages, 
    typeable_line, 
    requester_name, 
    our_number, 
    operation_history,
    written_down_by,
    write_down_reason,
    is_inferred_paid_at,
    DATE(due_date) AS dt_due, 
    DATE(emission_date) AS dt_emission, 
    DATE(paid_at) AS dt_paid, 
    DATE(credit_date) AS dt_credit,
    DATE(interest_start_at) AS dt_interest_start, 
    DATE(fine_start_at) AS dt_fine_start, 
    DATE(last_date_to_pay) AS dt_last_to_pay, 
    DATE(written_down_at) AS dt_written_down,
    DATE(last_synced_at) AS dt_last_synced,
    TIMESTAMP(started_processing_at) AS ts_started_processing, 
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated
FROM 
    datalake_checkout_raw.boleto