SELECT 
    id,
    charge_id AS id_charge,
    requester_id AS id_requester,
    credit_card_id AS id_credit_card,
    acquire_auth_code AS id_acquire_auth_code,
    business_entity_id AS id_business_entity,
    finance_entity_id AS id_finance_entity,
    external_id AS id_external,
    code,
    acquire_name,
    acquire_nsu,
    acquire_tid,
    block_entity,
    canceled_by_email,
    cancellation_reason,
    capture_fail_reason,
    card_brand,
    fine_type,
    first_six_digits,
    interest_type,
    installments,
    last_four_digits,
    max_installments,
    min_installments,
    payer_city,
    payer_email,
    payer_identifiable_document,
    payer_name,
    payer_neighborhood,
    payer_person_type,
    payer_state,
    payer_street_address,
    payer_zipcode,
    raw_response,
    requester_name,
    status,
    token,
    acquire_fee_amount,
    convenience_fee_amount,
    due_amount,
    fine_amount,
    fine_amount_percentage,
    fine_paid_amount,
    fixed_cost_of_transaction,
    installment_fee_amount,
    interest_amount,
    interest_amount_percentage,
    interest_paid_amount,
    paid_amount,
    refund_amount,
    due_date AS dt_due,
    fine_start_at AS dt_fine_start,
    interest_start_at AS dt_interest_start,
    last_date_to_pay AS dt_last_date_to_pay,
    created_at AS ts_created,
    canceled_at AS ts_canceled,
    paid_at AS ts_paid,
    updated_at AS ts_updated
FROM 
    datalake_checkout_raw.credit_card_status_log
