SELECT
    id,
    charge_id AS id_charge,
    transaction_id AS id_transaction,
    bank_payment_id AS id_bank_payment,
    requester_id AS id_requester,
    due_amount,
    status,
    pix_link,
    emv,
    qr_code,
    payer_name,
    payer_identifiable_document,
    payer_person_type,
    payer_email,
    payer_city,
    payer_neighborhood,
    payer_state,
    payer_street_address,
    payer_zipcode,
    requester_name,
    expiration_in_seconds,
    payer_solicitation,
    additional_info,
    TIMESTAMP(registered_at) AS ts_registered,
    TIMESTAMP(started_processing_at) AS ts_started_processing,
    TIMESTAMP(paid_at) AS ts_paid,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(updated_at) AS ts_updated
FROM
    datalake_checkout_raw.pix
