SELECT
  id_test_execution,
  stats.suites,
  stats.tests,
  stats.passes,
  stats.pending,
  stats.failures,
  stats.duration,
  stats.testsRegistered AS tests_registered,
  stats.passPercent AS pass_percent,
  stats.pendingPercent AS pending_percent,
  stats.other,
  stats.skipped,
  stats.hasOther AS has_other,
  stats.hasSkipped AS has_skipped,
  stats.start AS ts_start,
  stats.end AS ts_end,
  pwa,
  dt
FROM datalake_cypress_reports_raw.cypress_reports
