SELECT
    id_house,
    id_house_listing,
    city_group,
    city_name,
    region_code,
    listing_age,
    quality_score,
    liquidity_score,
    qt_lpv_1d_for_rent,
    qt_lpv_3d_for_rent,
    qt_lpv_7d_for_rent,
    qt_lpv_14d_for_rent,
    qt_lpv_21d_for_rent,
    qt_lpv_1d_for_sale,
    qt_lpv_3d_for_sale,
    qt_lpv_7d_for_sale,
    qt_lpv_14d_for_sale,
    qt_lpv_21d_for_sale,
    days_last_lpv_14_below_3,
    days_last_lpv_14_above_8,
    demand_score,
    dt_publication_for_sale,
    dt_publication_for_rent,
    dt_snapshot
FROM
    reverse_demand_score.listing_demand_score
WHERE
    DATE(dt_snapshot) = CURRENT_DATE()
    -- TO-DO: Add filter for campaigns (collecting with BizOps team)