SELECT 
  sk_propose,
  id_payment_min,
  flow_type,
  gateway,
  activator_amount,
  monthly_guarantee,
  annual_guarantee,
  total_charged,
  total_paid,
  value_upfront_signatures,
  expected_appropriated_months,
  expected_appropriated_amount,
  expected_months_to_be_appropriated,
  expected_amount_to_be_appropriated,
  has_activation,
  has_payment_advance,
  is_direct_billing,
  mobs_in_between_due_dates,
  dt_due_min,
  dt_due_max,
  dt_month_last_day, 
  dt_paid_min,
  dt_paid_max,
  dt_month_appropriation_start,
  dt_month_ref_creation,
  dt_contract_started,
  dt_ended,
  dt_created,
  NOW() AS ts_snapshot,
  YEAR(CURRENT_DATE()) AS year,
  MONTH(CURRENT_DATE()) AS month,
  DAY(CURRENT_DATE()) AS day
FROM 
  dw_recon_quintocred.fact_customer_advance
