SELECT
  sk_propose,
  sk_propose_rh,
  our_number, 
  tenant_name,
  gateway,
  billing_type,
  status_payment,
  type_rh,
  payment_status_rh, 
  source_bill_item,
  description,
  holder_name, 
  holder_document, 
  holder_bank, 
  holder_agency, 
  holder_account, 
  type_account, 
  your_number, 
  status, 
  occurrence_code, 
  payment_type, 
  paying_bank, 
  paying_agency, 
  paying_account, 
  paying_digit,
  activator_amount,
  monthly_guarantee,
  payment_value,
  paid_value_rh,
  days_contract_life,
  dt_contract_started,
  dt_ended_official,
  dt_due_payment,
  dt_paid_payment,
  dt_created_rh,
  dt_due_rh, 
  dt_paid_rh,
  NOW() AS ts_snapshot,
  YEAR(CURRENT_DATE()) AS year,
  MONTH(CURRENT_DATE()) AS month,
  DAY(CURRENT_DATE()) AS day
FROM
  dw_recon_quintocred.fact_pending_transfers_detailed
