select
    id,
    imovel_id as id_house,
    analysis_date as ts_analyzed,
    score_5A,
    score_5A_best_subset,
    score_cardif,
    score_cardif_best_subset,
    status,
    comment,
    analyst_name,
    supervisor_name,
    rent_value,
    condo_value,
    iptu_value,
    timestamp(created_at) as ts_created,
    timestamp(updated_at) as ts_updated,
    home_area,
    home_bathrooms,
    home_city,
    home_garages,
    home_region,
    home_suites,
    home_type,
    home_zipcode,
    drive_id as id_drive,
    reason,
    home_insurance_value,
    risk_level,
    risk_level_best_subset,
    process_date as ts_processed,
    home_exclusive_5A as is_home_exclusive_5A,
    home_last_published_at as ts_home_last_published,
    bypass_pre_analysis as has_bypassed_pre_analysis,
    pre_analysis_result,
    pre_analysis_reason,
    proposal_source
from datalake_sorting_hat_raw.proposal
