SELECT
    BIGINT(id_cbpagamento_int) AS id_agreement_payment,
    BIGINT(id_cbitembordero_int) AS id_agreement_detail,
    BIGINT(id_cbcontrato_int) AS id_contract,
    BIGINT(id_geusuario_int) AS id_user,
    BIGINT(id_cbtipopagamento_int) AS id_cbtipopagamento,
    BIGINT(id_geempresa_int) AS id_geempresa,
    BIGINT(id_gefilial_int) AS id_gefilial,
    BIGINT(id_gecliente_int) AS id_gecliente,
    BIGINT(sequencia_int) AS sequence,
    serie_recibo_str AS receipt_series,
    observacao_txt AS observation,
    tipo_recibo_str AS receipt_type,
    situacao_str AS bill_status,
    pc_magnetico_str AS magnetic,
    situacao_pagto_str AS payment_status,
    tipo_pagamento_str AS payment_type,
    IF(parcelado_str = "S", TRUE, FALSE) AS is_paid_in_installments,
    observacao_boleto_str AS bank_slip_note,
    produto_str AS product,
    quitacao_str AS discharge,
    senha_str AS password,
    INT(chave_acesso_int) AS access_key,
    modalidade_num AS modality,
    parcelamento_str AS installment,
    colchao_str AS mattress,
    BIGINT(recibo_num) AS receipt,
    CAST(REPLACE(principal_num, ',', '.') AS DECIMAL(10, 2)) AS principal,
    CAST(REPLACE(cp_num, ',', '.') AS DECIMAL(10, 2)) AS cp,
    CAST(REPLACE(multa_num, ',', '.') AS DECIMAL(10, 2)) AS fine,
    CAST(REPLACE(notificacao_num, ',', '.') AS DECIMAL(10, 2)) AS notification,
    CAST(REPLACE(despesa_banco_num, ',', '.') AS DECIMAL(10, 2)) AS bank_expense,
    CAST(REPLACE(desconto_num, ',', '.') AS DECIMAL(10, 2)) AS discount,
    CAST(REPLACE(desconto_principal_num, ',', '.') AS DECIMAL(10, 2)) AS principal_discount,
    CAST(REPLACE(abatimento_num, ',', '.') AS DECIMAL(10, 2)) AS reduction,
    CAST(REPLACE(juros_mora_num, ',', '.') AS DECIMAL(10, 2)) AS default_interest,
    CAST(REPLACE(honorarios_num, ',', '.') AS DECIMAL(10, 2)) AS fees,
    CAST(REPLACE(comissionamento_num, ',', '.') AS DECIMAL(10, 2)) AS commissioning,
    CAST(REPLACE(valor_total_num, ',', '.') AS DECIMAL(10, 2)) AS total_amount,
    CAST(REPLACE(retido_num, ',', '.') AS DECIMAL(10, 2)) AS retained,
    CAST( REPLACE(acrescimo_num, ',', '.') AS DECIMAL(10, 2)) AS addition,
    CAST(REPLACE(acrescimo_np_num, ',', '.') AS DECIMAL(10, 2)) AS addition_np,
    CAST(REPLACE(percentual_desconto_num, ',', '.') AS DECIMAL(10, 2)) AS percentage_discount,
    TO_DATE(data_calculo_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_calculation,
    TO_DATE(data_pagamento_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_payment,
    TO_DATE(data_cadastro_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_register,
    TO_DATE(data_retorno_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_return,
    TO_DATE(data_retorno_banco_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_bank_return,
    TO_TIMESTAMP(tstamp_mdm_inclusao, 'dd/MM/yyyy HH:mm:ss') AS ts_insert,
    TO_TIMESTAMP(tstamp_mdm_alteracao, 'dd/MM/yyyy HH:mm:ss') AS ts_update,
    TO_TIMESTAMP(tstamp, 'dd/MM/yyyy HH:mm:ss') AS ts_timestamp,
    NOW() AS ts_load
FROM datalake_paschoalotto_raw.cbpagamento
