SELECT
    BIGINT(id_cbitembordero_int) AS id_agreement_detail,
    BIGINT(id_cbbordero_int) AS id_negotiation,
    BIGINT(id_cbcontrato_int) AS id_contract,
    BIGINT(id_geqlendereco_int) AS id_address,
    BIGINT(id_geqlcontato_int) AS id_contact,
    BIGINT(id_geusuario_int) AS id_user,
    BIGINT(id_cbinstrucao1_int) AS id_cbinstrucao1,
    BIGINT(id_cbinstrucao2_int) AS id_cbinstrucao2,
    BIGINT(id_geusuario_boleto_int) AS id_geusuario_boleto,
    BIGINT(id_gecidade_int) AS id_gecidade,
    BIGINT(acordo_int) AS id_agreement,
    COALESCE(NULLIF(nosso_numero_str,""), nosso_numero_int) AS our_number,
    boleto_int AS bank_slip,
    comando_str As command,
    destino_str AS email_destination,
    linha_digitavel_str AS digitable_line,
    cod_barra_str AS bar_code,
    barra_str AS bank_slip_bar,
    INT(dv_int) AS bank_slip_dv,
    instrucao_1_str AS instruction_1,
    instrucao_2_str AS instruction_2,
    instrucao_3_str AS instruction_3,
    instrucao_4_str AS instruction_4,
    instrucao_5_str AS instruction_5,
    instrucao_6_str AS instruction_6,
    instrucao_7_str AS instruction_7,
    instrucao_final_str AS final_instruction,
    parcelamento_str AS installment,
    CASE
        WHEN pago_str = "C" THEN "cancelado (sistema)"
        WHEN pago_str = "S" THEN "pago"
        WHEN pago_str = "X" THEN "cancelado pelo supervisor (manual)"
        WHEN pago_str = "N" THEN "quebra / não pagamento do boleto"
        WHEN NULLIF(TRIM(pago_str), "") IS NULL THEN "stand by"
        ELSE pago_str
    END AS payment_status,
    IF(quitacao_str = "S", TRUE, FALSE) AS is_settlement,
    observacao_boleto_str AS bank_slip_note,
    CASE
        WHEN tipo_destino_str = "C" THEN "celular (sms)"
        WHEN tipo_destino_str = "E" THEN "email"
        WHEN tipo_destino_str = "O" THEN "outros meios de envio"
        WHEN tipo_destino_str = "W" THEN "web (paginas web)"
        ELSE tipo_destino_str
    END AS type_destiny,
    boleto_parcelamento_str AS bank_slip_installment,
    IF(tipo_geracao_str = "P", TRUE, FALSE) AS is_generated_by_operator,
    codigo_parcelamento_ws_str AS id_installment,
    IF(INT(acao_enviado_api_int) = 1, TRUE, FALSE) AS is_sent_action_api,
    IF(boletagem_enviada_int = 1, TRUE, FALSE) AS is_sent_billing,
    carta_boleto_quintoandar_str AS carta_boleto,
    IF(boletagem_remessa_quintoandar_str  = "S", TRUE, FALSE) AS is_boletagem_remessa,
    BIGINT(acordo_formalizado_int) AS formalized_agreement,
    arquivo_terc_str AS third_file,
    envio_jpg_str AS jpg_sent,
    INT(origem_ws_int) AS origin_ws,
    IF(notificacao_num = "1", TRUE, FALSE) AS has_notification,
    CAST(REPLACE(cp_original_num, ',', '.') AS DECIMAL(10, 2)) AS cp_original,
    CAST(REPLACE(cp_num, ',', '.') AS DECIMAL(10, 2)) AS cp,
    CAST(REPLACE(valor_desconto_num, ',', '.') AS DECIMAL(10, 2)) AS bank_slip_discount_amount,
    CAST(REPLACE(principal_num, ',', '.') AS DECIMAL(10, 2)) AS main_amount,
    CAST(REPLACE(multa_num, ',', '.') AS DECIMAL(10, 2)) AS fine_amount,
    CAST(REPLACE(despesa_banco_num, ',', '.') AS DECIMAL(10, 2)) AS bank_expense,
    CAST(REPLACE(desconto_num, ',', '.') AS DECIMAL(10, 2)) AS discount_amount,
    CAST(REPLACE(abatimento_num, ',', '.') AS DECIMAL(10, 2)) AS write_off,
    CAST(REPLACE(juros_mora_num, ',', '.') AS DECIMAL(10, 2)) AS default_interest,
    CAST(REPLACE(honorarios_num, ',', '.') AS DECIMAL(10, 2)) AS honorarium_amount,
    CAST(REPLACE(comissionamento_num, ',', '.') AS DECIMAL(10, 2)) AS commissioning,
    CAST(REPLACE(valor_total_num, ',', '.') AS DECIMAL(10, 2)) AS total_amount,
    CAST(REPLACE(retido_num, ',', '.') AS DECIMAL(10, 2)) AS retained,
    CAST(REPLACE(acrescimo_num, ',', '.') AS DECIMAL(10, 2)) AS addition,
    CAST(REPLACE(acrescimo_np_num, ',', '.') AS DECIMAL(10, 2)) AS addition_np,
    CAST(REPLACE(perc_desc_num, ',', '.') AS DECIMAL(10, 2)) AS discount_percentage,
    CAST(REPLACE(principal_original_num, ',', '.') AS DECIMAL(10, 2)) AS principal_original,
    CAST(REPLACE(desconto_original_num, ',', '.') AS DECIMAL(10, 2)) AS discount_original,
    CAST(REPLACE(pc_ho_num, ',', '.') AS DECIMAL(10, 2)) AS pc_ho,
    CAST(REPLACE(pc_comissionamento_num, ',', '.') AS DECIMAL(10, 2)) AS pc_commissioning,
    context,
    hora_boleto_tim AS hour_bank_skip,
    TO_DATE(data_envio_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_shipping,
    TO_DATE(data_reenvio_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_resend,
    TO_DATE(data_desconto_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_discount,
    TO_DATE(vencimento_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_due,
    TO_DATE(emissao_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_emission,
    TO_DATE(data_boleto_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_bank_slip,
    TO_TIMESTAMP(boleto_gravacao_tim, 'dd/MM/yyyy HH:mm:ss') AS ts_bank_slip_recording,
    TO_TIMESTAMP(tstamp_mdm_inclusao, 'dd/MM/yyyy HH:mm:ss') AS ts_insert,
    TO_TIMESTAMP(tstamp_mdm_alteracao, 'dd/MM/yyyy HH:mm:ss') AS ts_update,
    TO_TIMESTAMP(tstamp, 'dd/MM/yyyy HH:mm:ss') AS ts_tstamp,
    TO_TIMESTAMP(timestamp, 'dd/MM/yyyy HH:mm:ss') AS ts_timestamp,
    NOW() AS ts_load
FROM datalake_paschoalotto_raw.cbitembordero
