SELECT
    BIGINT(id_cbsitcontato_int) AS id_collection_history,
    BIGINT(id_geusuario_int) AS id_user,
    BIGINT(id_cbsituacaocontrato_int) AS id_customer_history,
    BIGINT(codigo_int) AS id_negotiation,
    BIGINT(id_gecliente_int) AS id_customer,
    BIGINT(id_gemotivonajuizamento_int) AS id_gemotivonajuizamento,
    BIGINT(id_geqlresponsavel_int) AS id_geqlresponsavel,
    BIGINT(id_geqlsituacao_int) AS id_geqlsituacao,
    BIGINT(id_geaplicacao_int) AS id_geaplicacao,
    BIGINT(id_getipodocumento_int) AS id_getipodocumento,
    BIGINT(id_gegrupotipodocumento_int) AS id_gegrupotipodocumento,
    BIGINT(id_geprocesso_int) AS id_geprocesso,
    BIGINT(id_gegrupoprocesso_int) AS id_gegrupoprocesso,
    BIGINT(id_geitemprocesso_int) AS id_geitemprocesso,
    BIGINT(id_cbvalortipodespesa_int) AS id_cbvalortipodespesa,
    BIGINT(id_gemotivoinadimplencia_int) AS id_gemotivoinadimplencia,
    BIGINT(id_sysatdinamico_int) AS id_sysatdinamico,
    BIGINT(id_jutipocontrole) AS id_jutipocontrole,
    descricao_str AS contact_description,
    INT(dias_cobranca_int) AS collection_days,
    exclui_contrato_str AS excludes_contract,
    tp_acao_str AS lawsuit,
    proxima_chamada_tim AS next_call,
    positivo_str AS positive,
    fup_banco_str AS fup_bank,
    primordial_str AS primordial,
    IF(envia_email_str = "S", TRUE, FALSE) AS has_email_sending,
    codigo_banco_str AS bank_code,
    tipo_contato_str AS contact_type,
    BIGINT(limite_stdby_int) AS limit_standby,
    preenchimento_obrigatorio_str AS mandatory_filling,
    IF(boleto_str = "S", TRUE, FALSE) AS has_bank_slip,
    IF(ouvidoria_str = "S", TRUE, FALSE) AS has_ombudsman,
    fup_filacobranca_str AS fup_collection_queue,
    provisionamento_str AS provisioning,
    liberacao_str AS release,
    IF(contatou_cliente_str = "S", TRUE, FALSE) AS has_contacted_customer,
    doc_anexo_str AS attached_document,
    historico_padrao_str AS default_history,
    documento_fisico_str AS physical_document,
    INT(tempo_ideal_int) AS ideal_time,
    INT(margem_tolerancia_int) AS tolerance_margin,
    monitor_ativo_str AS active_monitor,
    protesto_str AS protest,
    standby_automatico_str AS automatic_standby,
    email_automatico_str AS automatic_email,
    escolhe_usuario_agendamento_str AS choose_user_schedule,
    recebimento_str AS receipt,
    visualizacao_externa_str AS external_view,
    descricao_npcob_web_str AS npcob_description,
    abre_tela_depois_salvar_str AS open_screen_after_save,
    painel_npjur_str AS npjur_panel,
    agendamento_str AS scheduling,
    agendamento_por_str AS scheduling_by,
    INT(agendamento_dias_int) AS scheduling_days,
    agendamento_agenda_str AS scheduling_agenda,
    agendamento_unico_str AS single_scheduling,
    INT(situacao_parcela_int) AS installment_status,
    telefone_str AS telephone,
    situacao_cobranca_str AS collection_status,
    painel_jur_npjur_str AS panel_jur_npjur,
    mov_processo_str AS process,
    doc_str AS document,
    assunto_email_auto_txt AS email_subject,
    lancamento_unico_str AS unique_release,
    lancamento_depende_str AS release_depends,
    apenas_aberto_str AS just_open,
    solic_aju_str AS requests_lawsuit,
    at_str AS description,
    painel_custas_npjur_str AS panel_custas_npjur,
    painel_purgacao_str AS purge_panel,
    contato_alo_str AS alo_contact,
    lanca_movimento_npjur_str AS launches_movement_npjur,
    tipo_protocolo_npjur_bit AS protocol_type_npjur,
    classificacao_str AS classification,
    IF(gera_retorno = 1, TRUE, FALSE) AS has_return,
    IF(ativo_str = "S", TRUE, FALSE) AS is_active,
    IF(atualiza_data_contato_manual_str = "S", TRUE, FALSE) AS is_update_manual_contact_date,
    IF(class_at_str = "S", TRUE, FALSE) AS is_class_at,
    BOOLEAN(atendida_bit) AS has_answer,
    BOOLEAN(produtiva_bit) AS is_productive,
    BOOLEAN(cpc_bit) AS is_cpc,
    BOOLEAN(terceiro_bit) AS is_third,
    BOOLEAN(data_evento_bit) AS is_event_date,
    IF(data_envio_date = "S", TRUE, FALSE) AS is_shipping_date,
    painel_classificacao_str AS panel_classification,
    qtde_ocorrencia_follow_int AS quantity_occurrence_follow,
    horas_blacklist_int AS hours_blacklist,
    tp_acio_str AS trigger_type,
    atualiza_data_ultimo_contato_str AS updates_last_contact,
    TO_TIMESTAMP(tstamp, 'dd/MM/yyyy HH:mm:ss') AS ts_timestamp,
    NOW() AS ts_load
FROM datalake_paschoalotto_raw.cbsitcontato
QUALIFY ROW_NUMBER() OVER(PARTITION BY id_cbsitcontato_int ORDER BY DATE(CONCAT(year, "-", month, "-", day)) DESC, ts_load DESC) = 1
