SELECT
    BIGINT(id_cbparcela_int) AS id_debt,
    BIGINT(id_cbcontrato_int) AS id_contract,
    BIGINT(id_geusuario_int) AS id_user,
    BIGINT(id_esregua_int) AS id_esregua,
    BIGINT(id_str) AS id,
    BIGINT(parcela_int) AS installment,
    CASE
        WHEN situacao_int = "0" THEN "ABERTO"
        WHEN situacao_int = "1" THEN "BOLETO GERADO (MANUAL)"
        WHEN situacao_int = "2" THEN "BOLETO BANCO"
        WHEN situacao_int = "4" THEN "PAGO/BAIXA PAGAMENTO"
        WHEN situacao_int = "6" THEN "CANCELADO/RETIRADA"
        ELSE NULLIF(situacao_int,"")
    END AS installment_status,
    observacao_str AS installment_status_note,
    numero_unico_str AS id_invoice_seubarriga,
    quintoandar_des_contr_str AS id_contract_quintoandar,
    BIGINT(COALESCE(NULLIF(nosso_numero_int,""), nosso_numero_str)) AS our_number,
    tipo_str AS type,
    es_des_regis_str AS cpf,
    INT(contrato_int) AS contract,
    contrato_rao_str AS contract_rao,
    desc_indice_str AS index,
    alterado_edi_str AS changed,
    referencia_str AS reference,
    status_registro_str AS status_record,
    manual_str AS manual,
    INT(produto_int) AS product,
    nome_produto_str AS product_name,
    INT(modalidade_int) AS modality,
    INT(agencia_int) AS agency,
    INT(mci_int) AS mci,
    nome_portador_str AS bearer_name,
    ciclo_cartao_str AS card_cycle,
    idade_cartao_str AS card_age,
    situacao_cacs_str AS status_cacs,
    INT(COALESCE(NULLIF(ciclo_atraso_int,""), ciclo_atraso_str)) AS delay_cycle,
    notificado_str AS notified,
    nota_fiscal_str AS invoice,
    atribuicao_str AS attribution,
    segmento_str AS segment,
    batimento_str AS beat,
    texto_contabil_str AS accounting_text,
    sistema_str AS system,
    NULLIF(forma_pagamento_str,"") AS payment_format,
    velo_imobiliaria_str AS velo_real_estate,
    velo_contratos_str AS velo_contracts,
    CASE
        WHEN velo_pf_str = "PF" THEN "PESSOA FISICA"
        WHEN velo_pf_str = "PJ" THEN "PESSOA JURÍDICA"
        ELSE NULL
    END AS velo_person_type,
    context,
    INT(dias_atraso_int) AS delay_days,
    CAST(REPLACE(es_valor_corrigido_num, ',', '.') AS DECIMAL(10, 2)) AS corrected_amount,
    CAST(REPLACE(es_valor_encargos_num, ',', '.') AS DECIMAL(10, 2)) AS charges_amount,
    CAST(REPLACE(es_valor_minimo_num, ',', '.') AS DECIMAL(10, 2)) AS minimum_amount,
    CAST(REPLACE(valor_principal_num, ',', '.') AS DECIMAL(10, 2)) AS main_amount,
    CAST(REPLACE(valor_pago_num, ',', '.') AS DECIMAL(10, 2)) AS paid_amount,
    CAST(REPLACE(vlr_devedor_total_num, ',', '.') AS DECIMAL(10, 2)) AS total_debt_amount,
    CAST(REPLACE(saldo_devedor_num, ',', '.') AS DECIMAL(10, 2)) AS debt_balance,
    CAST(REPLACE(valor_devedor_num, ',', '.') AS DECIMAL(10, 2)) AS debt_amount,
    CAST(REPLACE(vencidop_num, ',', '.') AS DECIMAL(10, 2)) AS expired_amount,
    CAST(REPLACE(valor_multa_num, ',', '.') AS DECIMAL(10, 2)) AS fine_amount,
    CAST(REPLACE(valor_multa_quitacao_num, ',', '.') AS DECIMAL(10, 2)) AS fine_settlement_amount,
    CAST(REPLACE(valor_comissao_perm_num, ',', '.') AS DECIMAL(10, 2)) AS commission_amount,
    CAST(REPLACE(qtd_moeda_num, ',', '.') AS DECIMAL(10, 2)) AS currency_amount,
    CAST(REPLACE(indice_moeda_num, ',', '.') AS DECIMAL(10, 2)) AS currency_index,
    CAST(REPLACE(tarifa_cobranca_num, ',', '.') AS DECIMAL(10, 2)) AS fare_charge,
    CAST(REPLACE(cp_parcela_num, ',', '.') AS DECIMAL(10, 2)) AS cp_installment,
    CAST(REPLACE(valor_limite_num, ',', '.') AS DECIMAL(10, 2)) AS limit_amount,
    CAST(REPLACE(valor_gastos_num, ',', '.') AS DECIMAL(10, 2)) AS spent_amount,
    CAST(REPLACE(ultimo_pagamento_num, ',', '.') AS DECIMAL(10, 2)) AS last_payment,
    CAST(REPLACE(saldo_maximo_num, ',', '.') AS DECIMAL(10, 2)) AS max_balance,
    CAST(REPLACE(saldo_minimo_num, ',', '.') AS DECIMAL(10, 2)) AS min_balance,
    CAST(REPLACE(velo_alugueis_num, ',', '.') AS DECIMAL(10, 2)) AS velo_rentals,
    CAST(REPLACE(velo_danos_num, ',', '.') AS DECIMAL(10, 2)) AS velo_damage,
    CAST(REPLACE(velo_rescisao_num, ',', '.') AS DECIMAL(10, 2)) AS velo_rescission,
    CAST(REPLACE(velo_condominio_num, ',', '.') AS DECIMAL(10, 2)) AS velo_condominium,
    CAST(REPLACE(velo_assinatura_num, ',', '.') AS DECIMAL(10, 2)) AS velo_signature,
    CAST(REPLACE(velo_multa_num, ',', '.') AS DECIMAL(10, 2)) AS velo_fine,
    CAST(REPLACE(velo_juros_num, ',', '.') AS DECIMAL(10, 2)) AS velo_fees,
    TO_DATE(data_vencimento_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_due,
    TO_DATE(data_pagamento_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_payment,
    TO_DATE(data_primeira_distrib_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_first_contract_distribution,
    TO_DATE(data_ultima_distrib_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_last_contract_distribution,
    TO_DATE(data_limite_retorno_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_deadline_return,
    TO_DATE(data_performance_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_performance,
    TO_DATE(data_riscocl_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_riscocl,
    TO_DATE(data_entrada_ca_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_entry,
    TO_DATE(data_congelada_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_frozen,
    TO_DATE(data_ultima_fatura_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_last_invoice,
    TO_DATE(calculo_convencionais_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_conventional_calculation,
    TO_DATE(data_status_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_status,
    TO_DATE(data_validade_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_expiration,
    TO_DATE(ultimo_pagamento_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_last_payment,
    TO_DATE(data_fechamento_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_closing,
    TO_DATE(data_saldo_maximo_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_max_balance,
    TO_DATE(data_saldo_minimo_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_min_balance,
    TO_DATE(emissao_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_emission,
    TO_DATE(velo_data_inclusao_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_velo_inclusion,
    TO_TIMESTAMP(tstamp_mdm_inclusao, 'dd/MM/yyyy HH:mm:ss') AS ts_insert,
    TO_TIMESTAMP(tstamp_mdm_alteracao, 'dd/MM/yyyy HH:mm:ss') AS ts_update,
    TO_TIMESTAMP(tstamp, 'dd/MM/yyyy HH:mm:ss') AS ts_timestamp,
    NOW() AS ts_load,
    year,
    month,
    day
FROM datalake_paschoalotto_raw.cbparcela
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}
