SELECT
    BIGINT(id_cbparcelaitembordero_int) AS id_debt_negotiation_details,
    BIGINT(id_geusuario_int) AS id_user,
    BIGINT(id_cbitembordero_int) AS id_agreement_detail,
    BIGINT(id_cbparcela_int) AS id_debt,
    context,
    IF(INT(selecionado_int) = 1, TRUE, FALSE) AS is_selected,
    IF(notificacao_num = "1", TRUE, FALSE) AS has_notification,
    IF(despesa_banco_num = "1", TRUE, FALSE) AS has_bank_expense,
    IF(abatimento_num = "1", TRUE, FALSE) AS is_write_off,
    IF(honorarios_num = "1", TRUE, FALSE) AS has_honorarium,
    IF(comissionamento_num = "1", TRUE, FALSE) AS has_commissioning,
    CAST(REPLACE(principal_num, ',', '.') AS DECIMAL(10, 2)) AS main_amount,
    CAST(REPLACE(cp_num, ',', '.') AS DECIMAL(10, 2)) AS cp,
    CAST(REPLACE(multa_num, ',', '.') AS DECIMAL(10, 2)) AS fine_amount,
    CAST(REPLACE(desconto_num, ',', '.') AS DECIMAL(10, 2)) AS discount_amount,
    CAST(REPLACE(juros_mora_num, ',', '.') AS DECIMAL(10, 2)) AS default_interest,
    CAST(REPLACE(valor_total_num, ',', '.') AS DECIMAL(10, 2)) AS total_amount,
    CAST(REPLACE(retido_num, ',', '.') AS DECIMAL(10, 2)) AS retained,
    CAST(REPLACE(acrescimo_num, ',', '.') AS DECIMAL(10, 2)) AS addition,
    CAST(REPLACE(acrescimo_np_num, ',', '.') AS DECIMAL(10, 2)) AS addition_np,
    CAST(REPLACE(valor_parcela_num, ',', '.') AS DECIMAL(10, 2)) AS installment_amount,
    CAST(REPLACE(percentual_desconto_num, ',', '.') AS DECIMAL(10, 2)) AS discount_percentage,
    CAST(REPLACE(cp_original_num, ',', '.') AS DECIMAL(10, 2)) AS cp_original_amount,
    CAST(REPLACE(desconto_original_num, ',', '.') AS DECIMAL(10, 2)) AS original_discount,
    TO_DATE(data_vencimento_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_due,
    TO_DATE(data_arquivo_dat, 'dd/MM/yyyy HH:mm:ss') AS dt_file,
    TO_TIMESTAMP(tstamp_mdm_inclusao, 'dd/MM/yyyy HH:mm:ss') AS ts_insert,
    TO_TIMESTAMP(tstamp_mdm_alteracao, 'dd/MM/yyyy HH:mm:ss') AS ts_update,
    TO_TIMESTAMP(timestamp, 'dd/MM/yyyy HH:mm:ss') AS ts_timestamp,
    NOW() AS ts_load
FROM datalake_paschoalotto_raw.cbparcelaitembordero
QUALIFY ROW_NUMBER() OVER(PARTITION BY id_cbparcelaitembordero_int ORDER BY DATE(CONCAT(year, "-", month, "-", day)) DESC, ts_load DESC) = 1
