SELECT
    BIGINT(id_cbbordero_int) AS id_negotiation,
    BIGINT(id_cbtiponegocio_int) AS id_product,
    BIGINT(id_gecliente_int) AS id_customer,
    BIGINT(id_geusuario_int) AS id_user,
    BIGINT(id_geempresa_int) AS id_geempresa,
    BIGINT(id_gefilial_int) AS id_gefilial,
    BIGINT(id_fibanco_int) AS id_fibanco,
    BIGINT(id_ficcbanco_int) AS id_ficcbanco,
    BIGINT(id_cbtipopagamento_int) AS id_cbtipopagamento,
    BIGINT(id_cbtiponegocio_int) AS id_cbtiponegocio,
    BIGINT(id_cbconvenio_int) AS id_cbconvenio,
    BIGINT(id_geusuario_execut_int) AS id_geusuario_execut,
    BIGINT(bordero_int) AS bordereau,
    BIGINT(itens_int) AS items,
    INT(situacao_int) AS status,
    arquivo_str AS file,
    INT(carteira_int) AS portfolio,
    gerado_str AS generated,
    IF(followup_str = 0, FALSE, TRUE) AS is_followup,
    INT(modelo_carta_int) AS letter_template,
    INT(tipo_nosso_numero_int) AS our_number_type,
    repete_contrato_str AS repeat_contract,
    quitacao_str AS discharge,
    tipo_bordero_str AS bordereau_type,
    origem_str AS origin,
    forma_pagamento_api_recupera_str AS payment_type,
    link_cartao_api_recupera_str AS card_link,
    BIGINT(seq_calculo) AS calculation,
    COALESCE(BIGINT(numero_acordo_ws_int), BIGINT(numero_acordo_ws_str)) AS agreement_number_ws,
    CAST(REPLACE(total_num, ',', '.') AS DECIMAL(10, 2)) AS total,
    TO_DATE(data_dat, 'dd/MM/yyyy HH:mm:ss') AS date,
    TO_TIMESTAMP(tstamp, 'dd/MM/yyyy HH:mm:ss') AS ts_tstamp,
    TO_TIMESTAMP(timestamp, 'dd/MM/yyyy HH:mm:ss') AS ts_timestamp,
    NOW() AS ts_load,
    year,
    month,
    day
FROM datalake_paschoalotto_raw.cbbordero
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}
