SELECT
    BIGINT(id_cbtiponegocio_int) AS id_product,
    npjur_id_jupessoa AS id_npjur,
    codigo_str AS code,
    descricao_str AS description,
    quitacao_str AS settlement,
    inclusao_despesa_str AS expense_inclusion,
    descricao_npjur_str AS description_npjur,
    mostra_parcela_str AS installment_shown,
    cgc_str AS company_cnpj,
    cep_str AS zip_code,
    endereco1_str AS address_complement,
    endereco2_str AS address,
    neg_uf_str AS state,
    neg_bairro_str AS neighborhood,
    context,
    taxa_ano_str AS annual_interest_rate,
    CAST(REPLACE(dias_quitacao_num, ',', '.') AS DECIMAL(10, 2)) AS days_for_payment,
    CAST(REPLACE(parcelas_num, ',', '.') AS DECIMAL(10, 2)) AS installments_number,
    CAST(REPLACE(valor_mora_num, ',', '.') AS DECIMAL(10, 2)) AS fine_amount,
    CAST(REPLACE(valor_cp_num, ',', '.') AS DECIMAL(10, 2)) AS amount_cp,
    TO_TIMESTAMP(tstamp, 'dd/MM/yyyy HH:mm:ss') AS ts_timestamp,
    NOW() AS ts_load
FROM datalake_paschoalotto_raw.cbtiponegocio
QUALIFY ROW_NUMBER() OVER(PARTITION BY id_cbtiponegocio_int ORDER BY DATE(CONCAT(year, "-", month, "-", day)) DESC, ts_load DESC) = 1
