DROP TABLE datalake_raw.autodialer_team_gz;

CREATE EXTERNAL TABLE datalake_raw.autodialer_team (
  id int, 
  active string, 
  descricao string, 
  agenda_act string, 
  agenda_expirar_contato_act string, 
  agenda_expirar_contato_dias int, 
  agenda_ordenar_contato string, 
  agenda_contato_status_1 string, 
  agenda_contato_status_2 string, 
  agenda_contato_status_3 string, 
  agenda_contato_status_4 string, 
  agenda_contato_status_5 string, 
  agenda_contato_origem_act string, 
  agenda_contato_origem_canais string, 
  chat_act string, 
  chat_classificacao_auto_act string, 
  chat_nsalas_act string, 
  chat_nsalas_qde int, 
  email string, 
  email_act string, 
  email_qde int, 
  fone_atendimento_auto_act string, 
  fone_classificacao_auto_act string, 
  fone_classificacao_interna_act string, 
  fone_classificacao_entrada_act string, 
  fone_classificacao_saida_act string, 
  fone_conferencia_act string, 
  fone_dialpad_act string, 
  fone_dtmf_act string, 
  fone_controle_audio_act string, 
  fone_controle_audio_fone int, 
  fone_controle_audio_mic int, 
  fone_controle_audio_dtmf int, 
  fone_registro_act string, 
  fone_registro_tmp string, 
  fone_exibir_espera_act string, 
  fone_posatendimento_act string, 
  fone_posatendimento_interna_act string, 
  fone_posatendimento_entrada_act string, 
  fone_posatendimento_saida_act string, 
  kpi_telefone_atendimento string, 
  kpi_telefone_ociosidade string, 
  mensageria_act string, 
  wfaq_act string, 
  qualificar_chamada_act string, 
  qualificar_chamada_interna_act string, 
  qualificar_chamada_entrada_act string, 
  qualificar_chamada_saida_act string, 
  easy_wfaq_conf_id int, 
  easy_call_empresa_conf_id int, 
  easy_call_operacao_conf_id int, 
  easy_work_colaborador_conf_id int, 
  easy_work_colaborador_conf_ids string, 
  easy_atend_mensageria_conf_id int, 
  easy_pabx_serv_fila_universal_classificacao_conf_id int, 
  easy_pabx_serv_fila_universal_classificacao_sub_conf_id int, 
  mensageria_mail_act string, 
  mensageria_sms_act string, 
  mensageria_form_act string, 
  mensageria_facebook_act string, 
  mensageria_twitter_act string, 
  mensageria_instagram_act string, 
  mensageria_ws_act string, 
  mensageria_pbx_act string, 
  mensageria_estoque_min int, 
  mensageria_popup_act string, 
  contato_act string, 
  lead_act string, 
  lead_origem_act string, 
  lead_origem_canais string, 
  lead_estoque_min int, 
  lead_meta_min int, 
  lead_autoopen_act string, 
  lead_autoopen_tmp string, 
  lead_autorelease_act string, 
  propostas_act string, 
  propostas_estoque_min int)
ROW FORMAT SERDE 
  'org.openx.data.jsonserde.JsonSerDe' 
LOCATION
  's3://5a-datalake/raw/autodialer/team.gz/'
TBLPROPERTIES (
  'compressionType'='gzip')