SELECT
    codigo_proposta AS id_proposal,
    codigo_operacao AS id_operation,
    resultado AS analysis_result,
    calc_modelo_def AS model_score,
    calc_decisao_json AS model_metadata,
    calc_bigdata_idade_amax AS bigdata_age_amax,
    calc_bigdata_idade_amin AS bigdata_age_amin,
    calc_bigdata_idade_bureau AS bigdata_age_bureau,
    calc_bigdata_total_enderecos_sum AS bigdata_total_addresses_sum,
    calc_bigdata_total_passagens_emails_mean AS bigdata_total_tickets_emails_mean,
    calc_boavista_score_amax AS boavista_score_amax,
    calc_boavista_score_amin AS boavista_score_amin,
    calc_boavista_score_mean AS boavista_score_mean,
    calc_boavista_score_bureau AS boavista_score_bureau,
    calc_serasa_score_csba_amax AS serasa_score_csba_amax,
    calc_serasa_score_csba_amin AS serasa_score_csba_amin,
    calc_serasa_score_csba_mean AS serasa_score_csba_mean,
    calc_serasa_score_csba_sum AS serasa_score_csba_sum,
    calc_serasa_score_hspn_amax AS serasa_score_hspn_amax,
    calc_serasa_score_hspn_amin AS serasa_score_hspn_amin,
    calc_serasa_score_hspn_sum AS serasa_score_hspn_sum,
    calc_transunion_dist_fronteira_m_amin AS transunion_dist_fronteira_m_amin,
    calc_transunion_indic_seg_24_sum AS transunion_indic_seg_24_sum,
    calc_transunion_percent_decl_10_01_amin AS transunion_percent_decl_10_01_amin,
    calc_transunion_percent_escol_10_amin AS transunion_percent_escol_10_amin,
    calc_neoway_income_bureau AS neoway_income_bureau,
    calc_neoway_income_mean AS neoway_income_mean,
    prop_estado AS proposal_state,
    prop_taxa_imobiliaria AS proposal_real_state_tax,
    prop_nasc_titular AS proposal_birth_date_proponents,
    prop_valor_item_pacote AS proposal_value_package_item,
    prop_tipo_imovel AS proposal_property_type,
    prop_cidade AS proposal_city,
    prop_renda_comprovada AS proposal_verified_income,
    prop_corretor AS proposal_real_state_agent,
    prop_natureza_renda AS proposal_nature_income,
    prop_renda_declarada AS proposal_declared_income,
    calc_percentual_aprovado AS proposal_approved_percentage,
    calc_rating AS proposal_rating,
    prop_num_proposta AS proposal_number,
    calc_dti AS dti,
    calc_dti_maximo AS dti_max,
    calc_dti_real AS dti_real,
    calc_dti_presumido AS dti_presumed,
    calc_dti_apurado AS dti_calculated,
    calc_faixa_pacote AS package_range,
    calc_valor_pacote AS package_value,
    calc_nome_principal AS main_proponent_name,
    calc_idade AS main_proponent_age,
    prop_email_titular AS main_proponent_email,
    calc_faixa_renda_presumida AS presumed_income_range,
    calc_modelo_renda_total AS model_total_income,
    calc_renda_eleita AS elected_income,
    prop_ramo_atividade AS branch_activity,
    log_usuario AS log_user,
    log_resultado AS log_result,
    calc_status_decisao AS status_decision,
    calc_rating_random AS rating_random,
    calc_decisao_status AS decision_status,
    flx_decisao AS decision_flex,
    rgr_calcular_score AS calculate_score_result,
    vi_exec_bigid AS status_exec_bigid,
    calc_filtros AS status_filters,
    rgr_estrangeiro AS status_foreign_filter,
    flag_cnpj AS flag_cnpj,
    flag_fraude AS flag_fraud,
    CAST(IF(sucesso="S", TRUE, FALSE) AS BOOLEAN) AS is_success,
    CAST(IF(prop_resubmissao="S", TRUE, FALSE) AS BOOLEAN) AS is_resubmission,
    CAST(IF(rgr_valor_pacote="APROVADO", TRUE, FALSE) AS BOOLEAN) AS is_package_value_approved,
    CAST(calc_processos AS BOOLEAN) AS has_lawsuits,
    TO_TIMESTAMP(REPLACE(instante, '.000', ''), 'yyyy-MM-dd HH:mm:ss') AS ts_operation,
    year,
    month,
    day
FROM
    datalake_velo_neurotech_raw.logs_credit_granting
