class GchatWebhooksEnum:
    """
    Mapping of webhooks on GChat.
    """

    AE_ALERTS_PROD = "GCHAT_AE_ALERTS_PROD_WEBHOOK"
    AE_ALERTS_FORNO = "GCHAT_AE_ALERTS_FORNO_WEBHOOK"
    DATA_ALERTS = "GCHAT_DATA_ALERTS_WEBHOOK"
    DATA_QUALITY_PROD = "GCHAT_DATA_QUALITY_PROD_WEBHOOK"
    DATA_QUALITY_FORNO = "GCHAT_DATA_QUALITY_FORNO_WEBHOOK"
    GCHAT_SCHEMA_CHANGES = "GCHAT_SCHEMA_CHANGES_WEBHOOK"
    GCHAT_CDC_METRICS = "GCHAT_CDC_METRICS_WEBHOOK"
    GCHAT_CDC_EBDB_ALERTS = "GCHAT_EBDB_ALERTS_WEBHOOK"
    FINTECH_ALERTS_PROD = "GCHAT_FINTECH_ALERTS_PROD_WEBHOOK"
