class GchatWebhooksEnum:
    """
    Mapping of webhooks on GChat.
    """

    DATA_QUALITY_PROD = "GCHAT_DATA_QUALITY_PROD_WEBHOOK"
    DATA_QUALITY_FORNO = "GCHAT_DATA_QUALITY_FORNO_WEBHOOK"
    AE_ALERTS_PROD = "GCHAT_AE_ALERTS_PROD_WEBHOOK"
    AE_ALERTS_FORNO = "GCHAT_AE_ALERTS_FORNO_WEBHOOK"
