CREATE OR REPLACE VIEW datalake_amplitude_clean.visit_intent_clicked_events AS
SELECT
    server_received_time,
    app,
    device_carrier,
    schema,
    city,
    user_id,
    uuid,
    event_time,
    platform,
    os_version,
    amplitude_id,
    processed_time,
    user_creation_time,
    version_name,
    ip_address,
    paying,
    dma,
    client_upload_time,
    insert_id,
    library,
    amplitude_attribution_ids,
    device_type,
    device_manufacturer,
    start_version,
    location_lng,
    server_upload_time,
    event_id,
    location_lat,
    os_name,
    amplitude_event_type,
    device_brand,
    data,
    device_id,
    language,
    device_model,
    country,
    region,
    is_attribution_event,
    adid,
    session_id,
    device_family,
    sample_rate,
    idfa,
    client_event_time,
    year,
    month,
    day,
    event_type,
    get_json_object(user_properties, '$.AB_SCHEDULING_SUGGESTION') as user__a_b__s_c_h_e_d_u_l_i_n_g__s_u_g_g_e_s_t_i_o_n,
    get_json_object(user_properties, '$.HouseCardSize') as user__house_card_size,
    get_json_object(user_properties, '$.Location_enabled') as user__location_enabled,
    get_json_object(user_properties, '$.Total_booked_visits') as user__total_booked_visits,
    get_json_object(user_properties, '$.Total_booking_clicks') as user__total_booking_clicks,
    get_json_object(user_properties, '$.Total_cancelled_visits') as user__total_cancelled_visits,
    get_json_object(user_properties, '$.Total_confirmed_visits') as user__total_confirmed_visits,
    get_json_object(user_properties, '$.Total_map_price_flag_clicks') as user__total_map_price_flag_clicks,
    get_json_object(user_properties, '$.Total_rescheduled_visits') as user__total_rescheduled_visits,
    get_json_object(user_properties, '$.Total_viewed_listings') as user__total_viewed_listings,
    get_json_object(user_properties, '$.aa_firstFold_landing') as user_aa_first_fold_landing,
    get_json_object(user_properties, '$.aa_hurry_up') as user_aa_hurry_up,
    get_json_object(user_properties, '$.aa_landing_page') as user_aa_landing_page,
    get_json_object(user_properties, '$.aa_new_card') as user_aa_new_card,
    get_json_object(user_properties, '$.aa_new_house_card') as user_aa_new_house_card,
    get_json_object(user_properties, '$.ab-originals-all-or-nothing') as user_aboriginalsallornothing,
    get_json_object(user_properties, '$.ab_100_test') as user_ab_100_test,
    get_json_object(user_properties, '$.ab_30_test') as user_ab_30_test,
    get_json_object(user_properties, '$.ab_announce_cta') as user_ab_announce_cta,
    get_json_object(user_properties, '$.ab_announce_cta_owners') as user_ab_announce_cta_owners,
    get_json_object(user_properties, '$.ab_announce_owners_cta') as user_ab_announce_owners_cta,
    get_json_object(user_properties, '$.ab_appbar_color') as user_ab_appbar_color,
    get_json_object(user_properties, '$.ab_booked_plus_similar') as user_ab_booked_plus_similar,
    get_json_object(user_properties, '$.ab_booking_pressure') as user_ab_booking_pressure,
    get_json_object(user_properties, '$.ab_bookinginfo') as user_ab_bookinginfo,
    get_json_object(user_properties, '$.ab_card_booking') as user_ab_card_booking,
    get_json_object(user_properties, '$.ab_carousel_landing_page') as user_ab_carousel_landing_page,
    get_json_object(user_properties, '$.ab_checkin') as user_ab_checkin,
    get_json_object(user_properties, '$.ab_confirmation_schedule') as user_ab_confirmation_schedule,
    get_json_object(user_properties, '$.ab_contextual_search') as user_ab_contextual_search,
    get_json_object(user_properties, '$.ab_cp_pressure') as user_ab_cp_pressure,
    get_json_object(user_properties, '$.ab_credit_simulation_box') as user_ab_credit_simulation_box,
    get_json_object(user_properties, '$.ab_draft_inversion') as user_ab_draft_inversion,
    get_json_object(user_properties, '$.ab_draftinversion') as user_ab_draftinversion,
    get_json_object(user_properties, '$.ab_enhanced_mk') as user_ab_enhanced_mk,
    get_json_object(user_properties, '$.ab_enhanced_tags') as user_ab_enhanced_tags,
    get_json_object(user_properties, '$.ab_exposed_filters') as user_ab_exposed_filters,
    get_json_object(user_properties, '$.ab_favorite_carousel_animation') as user_ab_favorite_carousel_animation,
    get_json_object(user_properties, '$.ab_favorite_listing_animation') as user_ab_favorite_listing_animation,
    get_json_object(user_properties, '$.ab_favorite_listing_button_type') as user_ab_favorite_listing_button_type,
    get_json_object(user_properties, '$.ab_favorite_listing_tooltip') as user_ab_favorite_listing_tooltip,
    get_json_object(user_properties, '$.ab_featured_filters_price') as user_ab_featured_filters_price,
    get_json_object(user_properties, '$.ab_filter_leak') as user_ab_filter_leak,
    get_json_object(user_properties, '$.ab_filters_bedroom') as user_ab_filters_bedroom,
    get_json_object(user_properties, '$.ab_girafa') as user_ab_girafa,
    get_json_object(user_properties, '$.ab_girafa_switch') as user_ab_girafa_switch,
    get_json_object(user_properties, '$.ab_homes_carousel') as user_ab_homes_carousel,
    get_json_object(user_properties, '$.ab_homes_filter_tooltip') as user_ab_homes_filter_tooltip,
    get_json_object(user_properties, '$.ab_homes_labelmobile') as user_ab_homes_labelmobile,
    get_json_object(user_properties, '$.ab_homes_text') as user_ab_homes_text,
    get_json_object(user_properties, '$.ab_house_card_size') as user_ab_house_card_size,
    get_json_object(user_properties, '$.ab_hurry_up') as user_ab_hurry_up,
    get_json_object(user_properties, '$.ab_hurryup_schedule') as user_ab_hurryup_schedule,
    get_json_object(user_properties, '$.ab_instant_booking') as user_ab_instant_booking,
    get_json_object(user_properties, '$.ab_intersection_observer') as user_ab_intersection_observer,
    get_json_object(user_properties, '$.ab_intersection_observer_new') as user_ab_intersection_observer_new,
    get_json_object(user_properties, '$.ab_intro_second_fold_3') as user_ab_intro_second_fold_3,
    get_json_object(user_properties, '$.ab_landing_first_fold') as user_ab_landing_first_fold,
    get_json_object(user_properties, '$.ab_landing_form') as user_ab_landing_form,
    get_json_object(user_properties, '$.ab_landing_intercom') as user_ab_landing_intercom,
    get_json_object(user_properties, '$.ab_landing_lean_form') as user_ab_landing_lean_form,
    get_json_object(user_properties, '$.ab_listing_homes') as user_ab_listing_homes,
    get_json_object(user_properties, '$.ab_listing_pois') as user_ab_listing_pois,
    get_json_object(user_properties, '$.ab_listing_share') as user_ab_listing_share,
    get_json_object(user_properties, '$.ab_listing_videodialog') as user_ab_listing_videodialog,
    get_json_object(user_properties, '$.ab_listing_videodialog2') as user_ab_listing_videodialog2,
    get_json_object(user_properties, '$.ab_login_displaymode') as user_ab_login_displaymode,
    get_json_object(user_properties, '$.ab_map_button_title') as user_ab_map_button_title,
    get_json_object(user_properties, '$.ab_map_homes_button_animation') as user_ab_map_homes_button_animation,
    get_json_object(user_properties, '$.ab_map_list_mode') as user_ab_map_list_mode,
    get_json_object(user_properties, '$.ab_mk_layout') as user_ab_mk_layout,
    get_json_object(user_properties, '$.ab_mobile_infinite_scroll') as user_ab_mobile_infinite_scroll,
    get_json_object(user_properties, '$.ab_new_card') as user_ab_new_card,
    get_json_object(user_properties, '$.ab_new_house_card') as user_ab_new_house_card,
    get_json_object(user_properties, '$.ab_new_house_card_v2') as user_ab_new_house_card_v2,
    get_json_object(user_properties, '$.ab_originals_all_or_nothing') as user_ab_originals_all_or_nothing,
    get_json_object(user_properties, '$.ab_originals_cards') as user_ab_originals_cards,
    get_json_object(user_properties, '$.ab_originals_filter') as user_ab_originals_filter,
    get_json_object(user_properties, '$.ab_originals_landing_carousel') as user_ab_originals_landing_carousel,
    get_json_object(user_properties, '$.ab_originals_ready_listing') as user_ab_originals_ready_listing,
    get_json_object(user_properties, '$.ab_originals_stories') as user_ab_originals_stories,
    get_json_object(user_properties, '$.ab_pclick_online') as user_ab_pclick_online,
    get_json_object(user_properties, '$.ab_pclick_v01') as user_ab_pclick_v01,
    get_json_object(user_properties, '$.ab_photosphere') as user_ab_photosphere,
    get_json_object(user_properties, '$.ab_premature_login') as user_ab_premature_login,
    get_json_object(user_properties, '$.ab_prevent_housecard_show_photos') as user_ab_prevent_housecard_show_photos,
    get_json_object(user_properties, '$.ab_price_filter_expansion_checkbox') as user_ab_price_filter_expansion_checkbox,
    get_json_object(user_properties, '$.ab_publicationdate') as user_ab_publicationdate,
    get_json_object(user_properties, '$.ab_relisting') as user_ab_relisting,
    get_json_object(user_properties, '$.ab_results_counter') as user_ab_results_counter,
    get_json_object(user_properties, '$.ab_save_filters') as user_ab_save_filters,
    get_json_object(user_properties, '$.ab_schedule_button') as user_ab_schedule_button,
    get_json_object(user_properties, '$.ab_schedule_call') as user_ab_schedule_call,
    get_json_object(user_properties, '$.ab_schedule_label') as user_ab_schedule_label,
    get_json_object(user_properties, '$.ab_scheduling_suggestion') as user_ab_scheduling_suggestion,
    get_json_object(user_properties, '$.ab_search_rank') as user_ab_search_rank,
    get_json_object(user_properties, '$.ab_search_ranking') as user_ab_search_ranking,
    get_json_object(user_properties, '$.ab_second_step_scheduling') as user_ab_second_step_scheduling,
    get_json_object(user_properties, '$.ab_similar_houses') as user_ab_similar_houses,
    get_json_object(user_properties, '$.ab_similarity_carousel') as user_ab_similarity_carousel,
    get_json_object(user_properties, '$.ab_supported_neighborhoods_form') as user_ab_supported_neighborhoods_form,
    get_json_object(user_properties, '$.ab_supported_regions_empty_search') as user_ab_supported_regions_empty_search,
    get_json_object(user_properties, '$.ab_test') as user_ab_test,
    get_json_object(user_properties, '$.ab_testing_photos') as user_ab_testing_photos,
    get_json_object(user_properties, '$.ab_trending_carousel') as user_ab_trending_carousel,
    get_json_object(user_properties, '$.ab_two_steps_scheduling') as user_ab_two_steps_scheduling,
    get_json_object(user_properties, '$.ab_unbounce_pwa') as user_ab_unbounce_pwa,
    get_json_object(user_properties, '$.ab_user_documents_required') as user_ab_user_documents_required,
    get_json_object(user_properties, '$.ab_value_proposition') as user_ab_value_proposition,
    get_json_object(user_properties, '$.ab_visit_button_color') as user_ab_visit_button_color,
    get_json_object(user_properties, '$.ab_wafflemenu_button') as user_ab_wafflemenu_button,
    get_json_object(user_properties, '$.abc_100_test') as user_abc_100_test,
    get_json_object(user_properties, '$.abc_search_ranking') as user_abc_search_ranking,
    get_json_object(user_properties, '$.accessibility_enabled') as user_accessibility_enabled,
    get_json_object(user_properties, '$.chat_onboarding') as user_chat_onboarding,
    get_json_object(user_properties, '$.email') as user_email,
    get_json_object(user_properties, '$.entrance_uri') as user_entrance_uri,
    get_json_object(user_properties, '$.favorite_new_layout') as user_favorite_new_layout,
    get_json_object(user_properties, '$.gclid') as user_gclid,
    get_json_object(user_properties, '$.grandpaUserId') as user_grandpa_user_id,
    get_json_object(user_properties, '$.initial_entrance_uri') as user_initial_entrance_uri,
    get_json_object(user_properties, '$.initial_gclid') as user_initial_gclid,
    get_json_object(user_properties, '$.initial_referrer') as user_initial_referrer,
    get_json_object(user_properties, '$.initial_referring_domain') as user_initial_referring_domain,
    get_json_object(user_properties, '$.initial_utm_campaign') as user_initial_utm_campaign,
    get_json_object(user_properties, '$.initial_utm_content') as user_initial_utm_content,
    get_json_object(user_properties, '$.initial_utm_medium') as user_initial_utm_medium,
    get_json_object(user_properties, '$.initial_utm_source') as user_initial_utm_source,
    get_json_object(user_properties, '$.initial_utm_term') as user_initial_utm_term,
    get_json_object(user_properties, '$.inspectiondocs_button_clicked') as user_inspectiondocs_button_clicked,
    get_json_object(user_properties, '$.last_utm_campaign') as user_last_utm_campaign,
    get_json_object(user_properties, '$.last_utm_content') as user_last_utm_content,
    get_json_object(user_properties, '$.last_utm_medium') as user_last_utm_medium,
    get_json_object(user_properties, '$.last_utm_source') as user_last_utm_source,
    get_json_object(user_properties, '$.last_utm_term') as user_last_utm_term,
    get_json_object(user_properties, '$.leadFormOnHomePageExperiment') as user_lead_form_on_home_page_experiment,
    get_json_object(user_properties, '$.lead_firestore_id') as user_lead_firestore_id,
    get_json_object(user_properties, '$.login_status') as user_login_status,
    get_json_object(user_properties, '$.nbr-listings-viewed') as user_nbrlistingsviewed,
    get_json_object(user_properties, '$.nbr-searches-concluded') as user_nbrsearchesconcluded,
    get_json_object(user_properties, '$.nbr_homes_subscribed') as user_nbr_homes_subscribed,
    get_json_object(user_properties, '$.nbr_initial_offers_submitted') as user_nbr_initial_offers_submitted,
    get_json_object(user_properties, '$.nbr_listings_favorited') as user_nbr_listings_favorited,
    get_json_object(user_properties, '$.nbr_listings_viewed') as user_nbr_listings_viewed,
    get_json_object(user_properties, '$.nbr_onboarding_screens_viewed') as user_nbr_onboarding_screens_viewed,
    get_json_object(user_properties, '$.nbr_photos_viewed') as user_nbr_photos_viewed,
    get_json_object(user_properties, '$.nbr_photospheres_preview_viewed') as user_nbr_photospheres_preview_viewed,
    get_json_object(user_properties, '$.nbr_photospheres_viewed') as user_nbr_photospheres_viewed,
    get_json_object(user_properties, '$.nbr_searches_concluded') as user_nbr_searches_concluded,
    get_json_object(user_properties, '$.nbr_visits_scheduled') as user_nbr_visits_scheduled,
    get_json_object(user_properties, '$.originals') as user_originals,
    get_json_object(user_properties, '$.phased_rollout_checkin') as user_phased_rollout_checkin,
    get_json_object(user_properties, '$.phasedrollout_test') as user_phasedrollout_test,
    get_json_object(user_properties, '$.places_token_autocomplete') as user_places_token_autocomplete,
    get_json_object(user_properties, '$.platform') as user_platform,
    get_json_object(user_properties, '$.property') as user_property,
    get_json_object(user_properties, '$.referrer') as user_referrer,
    get_json_object(user_properties, '$.referring_domain') as user_referring_domain,
    get_json_object(user_properties, '$.reservation') as user_reservation,
    get_json_object(user_properties, '$.similar_props_carousel') as user_similar_props_carousel,
    get_json_object(user_properties, '$.swizzling') as user_swizzling,
    get_json_object(user_properties, '$.task_expansion_clicked') as user_task_expansion_clicked,
    get_json_object(user_properties, '$.twabrowserpackage') as user_twabrowserpackage,
    get_json_object(user_properties, '$.twabrowserversioncode') as user_twabrowserversioncode,
    get_json_object(user_properties, '$.twabrowserversionname') as user_twabrowserversionname,
    get_json_object(user_properties, '$.twaversion') as user_twaversion,
    get_json_object(user_properties, '$.upload_page_viewed') as user_upload_page_viewed,
    get_json_object(user_properties, '$.user_email') as user_user_email,
    get_json_object(user_properties, '$.user_id') as user_user_id,
    get_json_object(user_properties, '$.utm_campaign') as user_utm_campaign,
    get_json_object(user_properties, '$.utm_content') as user_utm_content,
    get_json_object(user_properties, '$.utm_medium') as user_utm_medium,
    get_json_object(user_properties, '$.utm_source') as user_utm_source,
    get_json_object(user_properties, '$.utm_term') as user_utm_term,
    get_json_object(user_properties, '$.webPushToken') as user_web_push_token,
    get_json_object(user_properties, '$.web_mobile_mode') as user_web_mobile_mode,
    get_json_object(event_properties, '$.accepts_pets') as event_accepts_pets,
    get_json_object(event_properties, '$.adj_city') as event_adj_city,
    get_json_object(event_properties, '$.adj_macro_region') as event_adj_macro_region,
    get_json_object(event_properties, '$.adj_sub_region') as event_adj_sub_region,
    get_json_object(event_properties, '$.apartment_id') as event_apartment_id,
    get_json_object(event_properties, '$.business_context') as event_business_context,
    get_json_object(event_properties, '$.city') as event_city,
    get_json_object(event_properties, '$.country') as event_country,
    get_json_object(event_properties, '$.current_page') as event_current_page,
    coalesce(get_json_object(event_properties, '$.dom_performance'), get_json_object(event_properties, '$.domPerformance')) as event_dom_performance,
    get_json_object(event_properties, '$.element_type') as event_element_type,
    get_json_object(event_properties, '$.event_type') as event_event_type,
    get_json_object(event_properties, '$.from_similar') as event_from_similar,
    get_json_object(event_properties, '$.has_listing_video') as event_has_listing_video,
    get_json_object(event_properties, '$.homes_email') as event_homes_email,
    coalesce(get_json_object(event_properties, '$.house_id'), get_json_object(event_properties, '$.houseId')) as event_house_id,
    get_json_object(event_properties, '$.house_tags') as event_house_tags,
    get_json_object(event_properties, '$.is_exclusive') as event_is_exclusive,
    get_json_object(event_properties, '$.is_furnished') as event_is_furnished,
    get_json_object(event_properties, '$.is_prox_metro') as event_is_prox_metro,
    get_json_object(event_properties, '$.listing') as event_listing,
    get_json_object(event_properties, '$.m2') as event_m2,
    get_json_object(event_properties, '$.macro_region') as event_macro_region,
    get_json_object(event_properties, '$.macro_region_id') as event_macro_region_id,
    get_json_object(event_properties, '$.nbr_bathrooms') as event_nbr_bathrooms,
    get_json_object(event_properties, '$.nbr_dorms') as event_nbr_dorms,
    get_json_object(event_properties, '$.nbr_parking_slots') as event_nbr_parking_slots,
    get_json_object(event_properties, '$.neighborhood') as event_neighborhood,
    coalesce(get_json_object(event_properties, '$.network_performance'), get_json_object(event_properties, '$.networkPerformance')) as event_network_performance,
    get_json_object(event_properties, '$.originals_type') as event_originals_type,
    get_json_object(event_properties, '$.price') as event_price,
    get_json_object(event_properties, '$.referrer') as event_referrer,
    get_json_object(event_properties, '$.search_id') as event_search_id,
    get_json_object(event_properties, '$.search_rank.rank') as event_search_rank_rank,
    get_json_object(event_properties, '$.search_rank.resultsOrigin') as event_search_rank_results_origin,
    get_json_object(event_properties, '$.search_rank.searchClient') as event_search_rank_search_client,
    get_json_object(event_properties, '$.search_rank.searchMode') as event_search_rank_search_mode,
    get_json_object(event_properties, '$.search_rank.sortMode') as event_search_rank_sort_mode,
    get_json_object(event_properties, '$.state') as event_state,
    get_json_object(event_properties, '$.sub_region') as event_sub_region,
    get_json_object(event_properties, '$.sub_region_id') as event_sub_region_id,
    get_json_object(event_properties, '$.type_property') as event_type_property,
    get_json_object(event_properties, '$.uri') as event_uri,
    get_json_object(event_properties, '$.valor_aluguel') as event_valor_aluguel,
    get_json_object(event_properties, '$.valor_condominio') as event_valor_condominio,
    get_json_object(event_properties, '$.valor_total') as event_valor_total
FROM
    datalake_amplitude_clean.events
WHERE
    event_type = 'visit_intent_clicked';
