SELECT
  col_1 AS id_registration,
  col_9 AS id_authorization,
  col_45 AS id_hash,
  col_41 AS id_bpag,
  col_42 AS id_erp,
  col_43 AS id_product,
  col_39 AS id_flag,
  col_37 AS id_acquirer,
  col_21 AS id_occurrence,
  col_26 AS id_bank_compensation,
  col_29 AS id_bank_grouper,
  col_17 AS id_nexxera_adjustment,
  col_19 AS id_transaction,
  col_2 AS acquirer_name,
  col_3 AS establishment_cnpj,
  col_4 AS adjusted_pos,
  col_5 AS original_pos,
  col_8 AS nsu_cv,
  col_14 AS launch_type,
  col_16 AS adjustment_original_reason,
  col_20 AS nexxera_detail_adjustment_code,
  col_22 AS launch_status,
  CAST(col_27 AS INT) AS deposit_agency,
  CAST(col_28 AS INT) AS deposit_account,
  col_31 AS card_number,
  col_36 AS capture_type,
  col_38 AS total_installments,
  col_40 AS tef_pos,
  col_44 AS product_name,
  col_11 AS installment_number,
  col_6 AS current_summary_number,
  col_7 AS original_summary_number,
  col_18 AS receipt_number,
  col_33 AS process_number,
  col_34 AS reference_number,
  CAST(col_32 / 100 AS DECIMAL(15,2)) AS service_charge_value,
  CAST(col_25 / 100 AS DECIMAL(15,2)) AS summary_discount_value,
  CAST(col_12 / 100 AS DECIMAL(15,2)) AS adjustment_value,
  CAST(col_24 / 100 AS DECIMAL(15,2)) AS summary_net_amount,
  CAST(col_15 / 100 AS DECIMAL(15,2)) AS installment_gross_amount,
  TO_DATE(col_10, 'ddMMyy') AS dt_sale_adjustment,
  TO_DATE(col_13, 'ddMMyy') AS dt_adjustment_launch,
  TO_DATE(col_35, 'ddMMyy') AS dt_reference_negotiation,
  TO_DATE(col_30, 'ddMMyy') AS dt_summary_adjustment,
  TO_DATE(col_23, 'ddMMyy') AS dt_sent_to_bank,
  TO_TIMESTAMP(CONCAT(year, '-', month, '-', day)) AS ts_ingested,
  year,
  month,
  day
FROM
    datalake_nexxera_raw.adjustments
WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
    AND col_1 = 12
