SELECT
    id_nexxera_adjustment,
    id_flag,
    id_bpag,
    id_erp,
    id_product,
    id_hash,
    id_acquirer,
    id_bank_grouper,
    id_authorization,
    id_occurrence,
    id_bank_compensation,
    tid,
    current_summary_number,
    original_summary_number,
    process_number,
    reference_number,
    establishment_cnpj,
    adjusted_pos,
    original_pos,
    tef_pos,
    nsu_cv,
    launch_type,
    adjustment_original_reason,
    receipt_number,
    nexxera_detail_adjustment_code,
    deposit_agency,
    deposit_account,
    card_number,
    product_name,
    acquirer_name,
    launch_status,
    registration_type,
    capture_type,
    installment_number,
    total_installments,
    CAST(adjustment_value AS DECIMAL(10,2)),
    CAST(service_charge_value AS DECIMAL(10,2)),
    CAST(installment_gross_amount AS DECIMAL(10,2)),
    CAST(summary_net_amount AS DECIMAL(10,2)),
    CAST(summary_discount_value AS DECIMAL(10,2)),
    dt_reference_negotiation,
    dt_summary_adjustment,
    dt_adjustment_launch,
    dt_sale_adjustment,
    dt_sent_to_bank,
    year,
    month,
    day
FROM
    datalake_nexxera_raw.adjustments
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}
