SELECT
  col_1 AS id_registration,
  col_7 AS id_authorization,
  col_8 AS id_bank_deposit,
  col_18 AS id_reconciliation,
  col_21 AS id_bpag,
  col_26 AS id_bank_grouper,
  col_27 AS id_erp,
  col_46 AS id_acquirer,
  col_47 AS id_flag,
  col_52 AS id_hash,
  col_38 AS id_bank_liquidated,
  col_20 AS id_transaction,
  col_2 AS acquirer_name,
  col_3 AS establishment_cnpj,
  col_4 AS acquirer_pos,
  col_5 AS rv_summary_number,
  col_6 AS nsu_cv,
  CAST(col_9 AS INTEGER) AS agency_deposit,
  CAST(col_10 AS INTEGER) AS account_deposit,
  col_12 AS installment_number,
  col_13 AS total_installments,
  col_16 AS sale_type,
  col_19 AS receipt_number,
  col_22 AS nsu_tef,
  col_23 AS payment_status,
  col_25 AS flag,
  col_28 AS card_number,
  col_30 AS terminal_number,
  col_31 AS capture_type,
  CAST(col_39 AS INTEGER) AS agency_liquidated,
  CAST(col_40 AS INTEGER) AS account_liquidated,
  col_44 AS reconciliation_status,
  col_45 AS information_origin,
  CAST(col_48 AS INTEGER) AS tef_pos,
  col_49 AS launch_type,
  col_54 AS manual_bank_reconciliation,
  CAST(col_17 / 100 AS DECIMAL(15,2)) AS installment_gross_amount,
  CAST(col_29 / 100 AS DECIMAL(15,2)) AS installment_discount_value,
  CAST(col_32 / 100 AS DECIMAL(15,2)) AS total_sale_gross_amount,
  CAST(col_33 / 100 AS DECIMAL(15,2)) AS total_sale_discount_amount,
  CAST(col_34 / 100 AS DECIMAL(15,2)) AS total_sale_net_amount,
  CAST(col_37 / 100 AS DECIMAL(15,2)) AS discount_charge,
  CAST(col_41 / 100 AS DECIMAL(15,2)) AS credit_installment_gross_amount,
  CAST(col_42 / 100 AS DECIMAL(15,2)) AS credit_installment_discount_amount,
  CAST(col_43 / 100 AS DECIMAL(15,2)) AS credit_installment_net_amount,
  CAST(col_50 / 100 AS DECIMAL(15,2)) AS installment_antecipation_discount_amount,
  CAST(col_51 / 100 AS DECIMAL(15,2)) AS installment_antecipation_net_amount,
  CAST(col_14 / 100 AS DECIMAL(15,2)) AS installment_net_amount,
  col_36 AS hr_summary_sale,
  TO_DATE(SUBSTR(col_35, 0, 6), 'ddMMyy') AS dt_summary_sale,
  TO_DATE(SUBSTR(col_53, 0, 6), 'ddMMyy') AS dt_deposit,
  TO_DATE(SUBSTR(col_24, 0, 6), 'ddMMyy') AS dt_sent_to_bank,
  TO_DATE(SUBSTR(col_11, 0, 6), 'ddMMyy') AS dt_sale,
  TO_DATE(SUBSTR(col_15, 0, 6), 'ddMMyy') AS dt_installment_credit,
  TO_TIMESTAMP(CONCAT(year, '-', month, '-', day)) AS ts_ingested,
  year,
  month,
  day
FROM
    datalake_nexxera_raw.financial
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}
    AND col_1 = 11
