SELECT
  col_1 AS id_registration,
  col_7 AS id_authorization,
  col_8 AS id_bank_deposit,
  col_18 AS id_reconciliation,
  col_21 AS id_bpag,
  col_26 AS id_bank_grouper,
  col_27 AS id_erp,
  col_46 AS id_acquirer,
  col_47 AS id_flag,
  col_52 AS id_hash,
  col_38 AS id_bank_liquidated,
  col_20 AS id_transaction,
  col_2 AS acquirer_name,
  col_3 AS establishment_cnpj,
  col_4 AS acquirer_pos,
  col_5 AS rv_summary_number,
  col_6 AS nsu_cv,
  col_9 AS agency_deposit,
  col_10 AS account_deposit,
  col_12 AS installment_number,
  col_13 AS total_installments,
  col_16 AS sale_type,
  col_19 AS receipt_number,
  col_22 AS nsu_tef,
  col_23 AS payment_status,
  col_25 AS flag,
  col_28 AS card_number,
  col_30 AS terminal_number,
  col_31 AS capture_type,
  col_39 AS agency_liquidated,
  col_40 AS account_liquidated,
  col_44 AS reconciliation_status,
  col_45 AS information_origin,
  col_48 AS tef_pos,
  col_49 AS launch_type,
  col_54 AS manual_bank_reconciliation,
  col_17 AS installment_gross_amount,
  col_29 AS installment_discount_value,
  col_32 AS total_sale_gross_amount,
  col_33 AS total_sale_discount_amount,
  col_34 AS total_sale_net_amount,
  col_37 AS discount_charge,
  col_41 AS credit_installment_gross_amount,
  col_42 AS credit_installment_discount_amount,
  col_43 AS credit_installment_net_amount,
  col_50 AS installment_antecipation_discount_amount,
  col_51 AS installment_antecipation_net_amount,
  col_14 AS installment_net_amount,
  col_36 AS hr_summary_sale,
  col_35 AS dt_summary_sale,
  col_53 AS dt_deposit,
  col_24 AS dt_sent_to_bank,
  col_11 AS dt_sale,
  col_15 AS dt_installment_credit,
  year,
  month,
  day
FROM
    datalake_nexxera_raw.transaction
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}
    AND col_1 = 11
