SELECT
    id_creditor,
    id_customer,
    id_product,
    id_contract,
    id_indicator,
    indicator_content,
    content_description,
    ts_load
FROM
    datalake_recupera_homolog_raw.indicator_contracts
