SELECT
    CAST(e.id_user AS BIGINT) AS id_user,
    e.id_app,
    e.city,
    GET_JSON_OBJECT(e.user_properties, '$.platform') AS platform,
    e.os_name,
    e.event_type,
    GET_JSON_OBJECT(e.user_properties, '$.country') AS country,
    GET_JSON_OBJECT(e.event_properties, '$.action_type') AS action_type,
    COALESCE(GET_JSON_OBJECT(e.event_properties, '$.current_page'), GET_JSON_OBJECT(e.event_properties, '$.pageName')) AS current_page,
    GET_JSON_OBJECT(e.event_properties, '$.reason') AS reason,
    GET_JSON_OBJECT(e.event_properties, '$.uri') AS uri,
    NULLIF(TRIM(COALESCE(GET_JSON_OBJECT(e.event_properties, '$.visit_code'), REGEXP_EXTRACT(GET_JSON_OBJECT(e.event_properties, '$.uri'), 'visitCode=([A-Z0-9]+)', 1))), '') AS visit_code,
    GET_JSON_OBJECT(e.event_properties, '$.visit_label') AS visit_label,
    e.user_properties,
    e.event_properties,
    CAST(GET_JSON_OBJECT(e.user_properties, '$.login_status') AS BOOLEAN) AS has_login_status,
    COALESCE(
      GET_JSON_OBJECT(e.event_properties, '$.pageName') = 'AgendaDetalhes'
        OR e.event_type IN ('agenda_visit_detail_page_call_clicked','agenda_visit_detail_page_wpp_clicked')
        OR e.event_type IN ('agenda_visit_card_action_clicked') AND GET_JSON_OBJECT(e.event_properties, '$.action_type') = 'SEND_INTRODUCTION' AND GET_JSON_OBJECT(e.event_properties, '$.current_page') = 'Agenda'
        OR e.event_type IN ('agenda_visit_detail_action_clicked') AND GET_JSON_OBJECT(e.event_properties, '$.action_type') = 'SEND_INTRODUCTION' AND GET_JSON_OBJECT(e.event_properties, '$.current_page') = 'AgendaDetalhes'
        OR e.event_type IN ('visitorinfo_phone_clicked','visitorinfo_whatsapp_clicked'),
      FALSE
    ) AS is_cqa_event,
    CAST(GET_JSON_OBJECT(e.user_properties, '$.isSaleAgent') AS BOOLEAN) AS is_sale_agent,
    CAST(GET_JSON_OBJECT(e.user_properties, '$.isRentAgent') AS BOOLEAN) AS is_rent_agent,
    e.ts_event,
    e.year,
    e.month,
    e.day
FROM
    datalake_amplitude_clean.events AS e
WHERE
    MAKE_DATE(e.year, e.month, e.day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
    AND e.id_app = 233592
    AND e.id_user IS NOT NULL
    AND e.event_type in (
        'agenda_visit_list_page_viewed',
        'finished_schedulings_page_viewed',
        'my_clients_page_viewed',
        'chatcrpp_chat_page_viewed',
        'time_block_tab_changed',
        'rent_progress_status_page_viewed',
        'entrance_info_page_viewed',
        'error_page_view',
        'error_page_refresh_button_clicked',
        'forbidden_page_view',
        'forbidden_page_home_button_clicked',
        'logged_out',
        'onboarding_notification_activate_button_clicked',
        'onboarding_notification_ignore_button_clicked',
        'onboarding_notification_page_view',
        'onboarding_notification_seen',
        'onboarding_update_page_view',
        'onboarding_update_start_button_clicked',
        'welcome_page_view',
        'welcome_page_login',
        'welcome_page_accreditation',
        'region_blocking_page_view',
        'region_blocking_page_home_button_clicked',
        'referral_sheet_view',
        'referral_sheet_copy_link_button_clicked',
        'referral_sheet_share_link_button_clicked',
        'menu_help_and_service_button_clicked',
        'menu_go_to_quintoandar_arena__button_clicked',
        'menu_go_to_agent_space_button_clicked',
        'agenda_day_tab_changed',
        'new_visit_pageview',
        'new_visit_house_input_clicked',
        'new_visit_date_input_clicked',
        'new_visit_date_time_type_selected',
        'new_visit_confirm_clicked',
        'new_visit_success_pageview',
        'visit_cancel_page_viewed',
        'agenda_visit_detail_page_viewed',
        'confirm_visit_page_viewed',
        'confirm_visit_button_clicked',
        'visit_confirmed',
        'reschedule_page_viewed',
        'visit_cancellation_intent_button_clicked',
        'cancel_visit_specify_reason_page_viewed',
        'cancel_visit_confirm_cancellation_page_viewed',
        'chatcrpp_allchats_page_viewed',
        'chatcrpp_access_chat_clicked',
        'chatcrpp_accep_terms_button_clicked',
        'time_block_new_block_clicked',
        'crm_CP_page_viewed',
        'owner_contact_success_page_viewed',
        'agenda_visit_detail_page_call_clicked',
        'agenda_visit_detail_page_wpp_clicked',
        'agenda_visit_detail_action_clicked',
        'agenda_visit_card_action_clicked',
        'visitorinfo_phone_clicked',
        'visitorinfo_whatsapp_clicked'
    )