SELECT
    id_amplitude,
    ids_amplitude_attributed,
    id_app,
    id_device,
    id_event,
    id_session,
    id_inserted,
    id_user,
    id_schema,
    idfa,
    adid,
    uuid,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_type,
    event_properties,
    is_attribution_event,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    is_paying,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    user_properties,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    ts_processed,
    year,
    month,
    day,
    GET_JSON_OBJECT(user_properties, '$.gclid') as up_gclid,
    GET_JSON_OBJECT(user_properties, '$.utm_source') as up_utm_source,
    GET_JSON_OBJECT(user_properties, '$.utm_medium') as up_utm_medium,
    GET_JSON_OBJECT(user_properties, '$.utm_campaign') as up_utm_campaign,
    GET_JSON_OBJECT(user_properties, '$.utm_content') as up_utm_content,
    GET_JSON_OBJECT(user_properties, '$.utm_term') as up_utm_term,
    GET_JSON_OBJECT(user_properties, '$.platform') as up_platform,
    GET_JSON_OBJECT(REPLACE(user_properties, '[adjust]', '(adjust)'), '$.(adjust) network') as up_adjust_network,
    GET_JSON_OBJECT(user_properties, '$.entrance_uri') as up_entrance_uri,
    GET_JSON_OBJECT(event_properties, '$.house_id') as ep_house_id,
    GET_JSON_OBJECT(event_properties, '$.visit_code') as ep_visit_code
FROM
    datalake_amplitude_clean.events
WHERE
    id_app = '170698' AND event_type = 'debug_visit_schedule_confirmed'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'