SELECT
    id_amplitude,
    ids_amplitude_attributed,
    adid,
    id_app,
    id_device,
    id_event,
    id_session,
    idfa,
    TRY_CAST(id_user AS INT) AS id_user,
    uuid,
    id_schema,
    id_inserted,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_type,
    event_properties,
    is_attribution_event,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    is_paying,
    region,
    start_version,
    user_properties,
    language,
    version_name,
    sample_rate,
    GET_JSON_OBJECT(event_properties, '$.business_context') AS ep_business_context,
    TRY_CAST(GET_JSON_OBJECT(event_properties, '$.house_id') AS INT) AS ep_id_house,
    TRY_CAST(GET_JSON_OBJECT(event_properties, '$.agent_id') AS INT) AS ep_id_agent,
    GET_JSON_OBJECT(user_properties, '$.utm_source') AS up_utm_source,
    GET_JSON_OBJECT(user_properties, '$.utm_medium') AS up_utm_medium,
    GET_JSON_OBJECT(user_properties, '$.utm_campaign') AS up_utm_campaign,
    GET_JSON_OBJECT(user_properties, '$.utm_term') AS up_utm_term,
    GET_JSON_OBJECT(user_properties, '$.utm_content') AS up_utm_content,
    GET_JSON_OBJECT(user_properties, '$.platform') AS up_app_type,
    GET_JSON_OBJECT(event_properties, '$.message_content') AS ep_message_content,
    DATE(ts_event) AS dt_event,
    ts_event,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    ts_server_uploaded,
    ts_processed,
    ts_user_created,
    year,
    month,
    day
FROM
    datalake_amplitude_new_clean.events
WHERE
    id_app = '170698' AND event_type = 'piloto_cw_message_sent'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'