SELECT
    id_amplitude,
    id_device,
    id_event,
    id_session,
    id_user,
    uuid,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    event_properties,
    os_name,
    os_version,
    platform,
    GET_JSON_OBJECT(user_properties, '$.gclid') AS up_gclid,
    GET_JSON_OBJECT(user_properties, '$.utm_source') AS up_utm_source,
    GET_JSON_OBJECT(user_properties, '$.utm_medium') AS up_utm_medium,
    GET_JSON_OBJECT(user_properties, '$.utm_campaign') AS up_utm_campaign,
    GET_JSON_OBJECT(user_properties, '$.utm_content') AS up_utm_content,
    GET_JSON_OBJECT(user_properties, '$.utm_term') AS up_utm_term,
    GET_JSON_OBJECT(user_properties, '$.platform') AS up_platform,
    GET_JSON_OBJECT(user_properties, "$['[adjust] network']") AS up_adjust_network,
    GET_JSON_OBJECT(user_properties, "$['[adjust] campaign']") AS up_adjust_campaign,
    GET_JSON_OBJECT(user_properties, "$['[AppsFlyer] appsflyer id']") AS up_appsflyer_appsflyer_id,
    GET_JSON_OBJECT(user_properties, "$['[AppsFlyer] campaign']") AS up_appsflyer_campaign,
    GET_JSON_OBJECT(user_properties, "$['[AppsFlyer] installed at']") AS up_appsflyer_installed_at,
    GET_JSON_OBJECT(user_properties, "$['[AppsFlyer] media source']") AS up_appsflyer_media_source,
    GET_JSON_OBJECT(user_properties, "$['[AppsFlyer] network name']") AS up_appsflyer_network_name,
    GET_JSON_OBJECT(user_properties, '$.entrance_uri') AS up_entrance_uri,
    is_attribution_event,
    ts_event,
    ts_user_created,
    ts_client_event,
    user_properties,
    ts_processed,
    year,
    month,
    day
FROM
    datalake_amplitude_new_clean.events
WHERE
    id_app = '170698' AND event_type = 'login_confirmation_viewed'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'