SELECT
    id_amplitude,
    ids_amplitude_attributed,
    id_app,
    id_device,
    id_event,
    id_session,
    id_inserted,
    id_user,
    id_schema,
    idfa,
    adid,
    uuid,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_type,
    event_properties,
    is_attribution_event,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    is_paying,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    user_properties,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    ts_processed,
    year,
    month,
    day,
        CAST(GET_JSON_OBJECT(event_properties, '$.house_id') AS BIGINT) AS ep_house_id,
        GET_JSON_OBJECT(event_properties, '$.alert_target_date') AS ep_alert_target_date,
        CAST(COALESCE(GET_JSON_OBJECT(event_properties, '$.alert_slot_from'), '') AS BIGINT) AS ep_alert_slot_from,
        CAST(COALESCE(GET_JSON_OBJECT(event_properties, '$.alert_slot_to'), '') AS BIGINT) AS ep_alert_slot_to
FROM
        datalake_amplitude_clean.events
    WHERE
    id_app = '170698' AND event_type = 'visit_hoursalert_confirmed'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'