SELECT
id_amplitude,
    ids_amplitude_attributed,
    id_app,
    id_device,
    id_event,
    id_session,
    id_inserted,
    id_user,
    id_schema,
    idfa,
    adid,
    uuid,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_type,
    event_properties,
    is_attribution_event,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    is_paying,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    user_properties,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    ts_processed,
    year,
    month,
    day,
    CAST(GET_JSON_OBJECT(event_properties, '$.formfield_lead_id') AS STRING) AS id_lead_ebdb,
    CAST(GET_JSON_OBJECT(user_properties, '$.initial_utm_campaign') AS STRING) AS initial_utm_campaign,
    CAST(GET_JSON_OBJECT(user_properties, '$.initial_utm_medium') AS STRING) AS initial_utm_medium,
    CAST(GET_JSON_OBJECT(user_properties, '$.initial_utm_source') AS STRING) AS initial_utm_source,
    CAST(GET_JSON_OBJECT(user_properties, '$.initial_utm_content') AS STRING) AS initial_utm_content,
    CAST(GET_JSON_OBJECT(user_properties, '$.initial_utm_term') AS STRING) AS initial_utm_term,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_campaign') AS STRING) AS utm_campaign,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_medium') AS STRING) AS utm_medium,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_source') AS STRING) AS utm_source,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_content') AS STRING) AS utm_content,
    CAST(GET_JSON_OBJECT(user_properties, '$.utm_term') AS STRING) AS utm_term,
    CAST(GET_JSON_OBJECT(user_properties , '$.platform') AS STRING) AS app_type,
    CAST(GET_JSON_OBJECT(user_properties , '$.referring_domain') AS STRING) AS referring_domain,
    CAST(TRIM(GET_JSON_OBJECT(event_properties, '$.formfield_lead_uuid')) AS STRING) AS formfield_lead_uuid,
    CAST(TRIM(GET_JSON_OBJECT(event_properties, '$.lead_id')) AS STRING) AS id_lead,
    CAST(GET_JSON_OBJECT(user_properties, '$.country') AS STRING) AS country_code
FROM
    datalake_amplitude_clean.events
WHERE
    id_app = '183047' AND event_type = 'price_suggestion_form_submitted'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'