SELECT
    id_amplitude,
    ids_amplitude_attributed,
    CAST((GET_JSON_OBJECT(event_properties, '$.house_id')) AS BIGINT) AS id_house,
    id_user,
    id_device,
    id_event,
    id_app,
    uuid,
    adid,
    id_session,
    id_schema,
    id_inserted,
    idfa,
    event_type,
    amplitude_event_type,
    GET_JSON_OBJECT(user_properties, '$.ab_beakman_native_owner_home_toggle') AS ab_beakman_native_owner_home_toggle,
    GET_JSON_OBJECT(user_properties, '$.platform') AS up_platform,
    COALESCE(GET_JSON_OBJECT(event_properties, '$.active_nbr_of_properties'),GET_JSON_OBJECT(event_properties, '$.active_nbr_of_properties_in_page')) AS ep_active_number_of_houses,
    COALESCE(GET_JSON_OBJECT(event_properties, '$.nbr_of_properties'),GET_JSON_OBJECT(event_properties, '$.total_nbr_of_properties')) AS ep_total_number_of_houses,
    GET_JSON_OBJECT(event_properties, '$.offset') AS ep_offset,
    GET_JSON_OBJECT(event_properties, '$.properties_ids') AS ep_house_ids,
    COALESCE(GET_JSON_OBJECT(event_properties, '$.rent_properties_statuses'),GET_JSON_OBJECT(event_properties, '$.rent_properties_status')) AS ep_rent_house_status,
    COALESCE(GET_JSON_OBJECT(event_properties, '$.sale_properties_statuses'),GET_JSON_OBJECT(event_properties, '$.sale_properties_status')) AS ep_sale_house_status,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    event_properties,
    user_properties,
    is_paying,
    is_attribution_event,
    ts_server_received,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_processed,
    year,
    month,
    day
FROM
  datalake_amplitude_clean.events
WHERE
    id_app = '183047' AND event_type = 'native_home_section_properties_list'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
