SELECT
    id_amplitude,
    ids_amplitude_attributed,
    id_app,
    id_device,
    id_event,
    id_session,
    id_inserted,
    id_user,
    id_schema,
    idfa,
    adid,
    uuid,
    amplitude_event_type,
    city,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_type,
    GET_JSON_OBJECT(event_properties, '$.scenarioType') AS recommendation_scenario_type,
    GET_JSON_OBJECT(event_properties, '$.renderId') AS recommendation_render_id,
    GET_JSON_OBJECT(event_properties, '$.renderType') AS recommendation_render_type,
    GET_JSON_OBJECT(event_properties, '$.index') AS recommendation_index,
    GET_JSON_OBJECT(event_properties, '$.moduleId') AS recommendation_module_id,    
    event_properties,
    is_attribution_event,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    is_paying,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    user_properties,
    DATE(ts_event) AS dt_event,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    ts_processed,
    year,
    month,
    day
FROM
    datalake_amplitude_clean.events
WHERE
    id_app = '417002' AND event_type = 'RecommendationClickEvent'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'