SELECT
    id_amplitude,
    ids_amplitude_attributed,
    id_app,
    id_device,
    id_event,
    id_session,
    id_inserted,
    id_user,
    id_schema,
    GET_JSON_OBJECT(event_properties, '$.5a_house_id') AS id_house,
    GET_JSON_OBJECT(event_properties, '$.imovelweb_house_id') AS id_house_imovelweb,
    idfa,
    adid,
    uuid,
    amplitude_event_type,
    city,
    GET_JSON_OBJECT(event_properties, '$.business_context') AS business_context,
    GET_JSON_OBJECT(event_properties, '$.supply_origin') AS supply_origin,
    GET_JSON_OBJECT(event_properties, '$.supply_partner') AS supply_partner,
    GET_JSON_OBJECT(event_properties, '$.click_origin') AS click_origin,
    GET_JSON_OBJECT(event_properties, '$.ad_type') AS ad_type,
    country,
    data,
    device_brand,
    device_carrier,
    device_family,
    device_manufacturer,
    device_model,
    device_type,
    dma,
    event_type,
    event_properties,
    ip_address,
    location_lat,
    location_lng,
    os_name,
    os_version,
    platform,
    library,
    region,
    start_version,
    language,
    version_name,
    sample_rate,
    STRING(GET_JSON_OBJECT(user_properties, '$.platform')) AS up_app_type,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_source')) AS up_utm_source,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_medium')) AS up_utm_medium,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_campaign')) AS up_utm_campaign,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_content')) AS up_utm_content,
    STRING(GET_JSON_OBJECT(user_properties, '$.utm_term')) AS up_utm_term,
    user_properties,
    GET_JSON_OBJECT(event_properties, '$.search_results_page_number') AS search_results_page_number,
    GET_JSON_OBJECT(event_properties, '$.search_results_page_position') AS search_results_page_position,
    GET_JSON_OBJECT(event_properties, '$.Search_results_overall_position') AS search_results_overall_position,
    is_paying,
    is_attribution_event,
    DATE(ts_event) AS dt_event,
    ts_event,
    ts_server_uploaded,
    ts_user_created,
    ts_client_event,
    ts_client_uploaded,
    ts_server_received,
    ts_processed,
    year,
    month,
    day
FROM
    datalake_amplitude_new_clean.events
WHERE
    id_app = '525551' AND event_type = 'listing_page_viewed'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'