drop table if exists stitch.users;
create external table if not exists stitch.users (
    id string,
    active string,
    alias string,
    chat_only string,
    created_at string,
    custom_role_id string,
    default_group_id string,
    details string,
    email string,
    external_id string,
    last_login_at string,
    locale string,
    locale_id string,
    moderator string,
    name string,
    notes string,
    only_private_comments string,
    organization_id string,
    permanently_deleted string,
    phone string,
    photo string,
    report_csv,
    restricted_agent,
    role string,
    role_type string,
    shared string,
    shared_agent string,
    shared_phone_number string,
    signature string,
    suspended string,
    tags string,
    ticket_restriction string,
    time_zone string,
    two_factor_auth_enabled string,
    updated_at string,
    url string,
    user_fields string,
    verified string
)