drop table if exists payment.fact_banking_file_payments;
create table if not exists payment.fact_banking_file_payments (
    sk_banking_file_payment varchar(30) primary key,
    sk_invoice bigint,
    sk_payment_request bigint,
    sk_contract bigint,
    sk_company_use varchar(30),
    sk_occurrence_code varchar(10),
    sk_charge_payer_user varchar(100),
    sk_transfer_payee_user varchar(100),
    sk_account_payable_corporate_user varchar(100),
    is_payee_savings_acc boolean,
    sk_created_date int,
    sk_issued_date int,
    sk_updated_date int,
    sk_due_date int,
    sk_fine_due_date int,
    sk_paid_date int,
    brl_due_amount decimal(15,2),
    brl_paid_amount decimal(15,2),
    brl_fine_amount decimal(13,2),
    brl_one_day_interest decimal(13,4),
    brl_charged_interest decimal(13,2),
    ts_load timestamp
)