"""Migration Twin DAG — run original queries on Databricks, capture metrics to S3.

Auto-generated by emr-migration-v2 skill.
Run ID: 4b35a737-1a52-4bf6-a58e-a079d7eae3f3
Scope: support_and_service/dw_customer_support
"""

import os
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

import yaml
from airflow import DAG, Dataset
from airflow.operators.python import PythonOperator

from bietlejuice.base.airflow.job_cluster_engine import (
    attach_emr_job_cluster_finished_work_prerequisites,
    attach_emr_terminate_cluster_work_prerequisites,
    attach_job_cluster_engine_to_context,
    get_job_cluster_completion_sink,
)
from bietlejuice.base.airflow.task_creators.dag_execution_context import (
    DagExecutionContext,
)
from bietlejuice.services.configuration_service import ConfigurationService

DAG_ID = "migration_twin_support_and_service__dw_customer_support"
RUN_ID = "4b35a737-1a52-4bf6-a58e-a079d7eae3f3"
DOMAIN = "support_and_service"
SOURCE_DAG_NAME = "dw_customer_support"
DATASET_URI = "migration:twin-support_and_service__dw_customer_support-complete"
RUN_PREFIX = "emr-migration/runs/4b35a737-1a52-4bf6-a58e-a079d7eae3f3"
RUNTIME = "twin"
SQL_DIR_NAME = "dw"

TABLES = [
    "dim_analyst",
    "dim_channel",
    "dim_chatbot",
    "dim_department",
    "dim_ra_ticket",
    "dim_taxonomy",
    "dim_ticket",
    "dim_zendesk_user",
    "fact_analysts_performance",
    "fact_backlog_metrics_tasks",
    "fact_chat_messages",
    "fact_chat_metrics",
    "fact_customer_contacts",
    "fact_ivr_interactions",
    "fact_sessions_chatbot",
    "fact_single_door_events",
    "fact_task_metrics",
    "fact_ticket_events",
    "fact_tickets",
    "fact_tickets_backlog",
]

DAG_DIR = Path(__file__).resolve().parent
ENV = os.environ.get("ENVIRONMENT")
CONFIG_SERVICE = ConfigurationService(SOURCE_DAG_NAME)
BUCKET = CONFIG_SERVICE.get_config("datalake_bucket")
BIETLEJUICE_REPO_PATH = CONFIG_SERVICE.get_config("databricks_bietlejuice_repo_path")
METRIC_CAPTURE_JOB = (
    f"{BIETLEJUICE_REPO_PATH}/spark_jobs/migration_assets/metric_capture_job.py"
)
ARTIFACTS_URI = CONFIG_SERVICE.get_config("artifacts_bucket")
ARTIFACTS_BUCKET = urlparse(ARTIFACTS_URI).netloc or ARTIFACTS_URI

with open(DAG_DIR / f"{DAG_ID}_cluster.yml") as _f:
    CLUSTER_ARGS = yaml.safe_load(_f).get("cluster", {})


def _build_context(dag):
    ctx = DagExecutionContext(
        dag=dag,
        environment=ENV,
        bucket=BUCKET,
        base_spark_jobs_path=f"{BIETLEJUICE_REPO_PATH}/spark_jobs/base/",
        dag_args={},
        workflow_args={},
        cluster_args=CLUSTER_ARGS,
        databricks_conn_id=CLUSTER_ARGS.get("databricks_conn_id", "databricks_new_env"),
    )
    attach_job_cluster_engine_to_context(ctx, CONFIG_SERVICE)
    return ctx


def _get_s3_client():
    import boto3
    from airflow.models import Variable

    role_arn = Variable.get("DATASET_EVENTS_ASSUME_ROLE_ARN", default_var=None)
    if not role_arn:
        return boto3.client("s3")
    sts = boto3.client("sts")
    creds = sts.assume_role(
        RoleArn=role_arn,
        RoleSessionName="migration-s3-upload",
        DurationSeconds=3600,
    )["Credentials"]
    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
    ).client("s3")


def _upload_sql(**context):
    sql_dir = DAG_DIR / "queries" / SQL_DIR_NAME
    s3 = _get_s3_client()
    for table in TABLES:
        local_path = str(sql_dir / f"{table}.sql")
        s3_key = f"{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}.sql"
        s3.upload_file(local_path, ARTIFACTS_BUCKET, s3_key)


with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["migration", "twin", "validation"],
    default_args={"owner": "data-platform", "retries": 0},
) as dag:
    ctx = _build_context(dag)

    upload_sql = PythonOperator(
        task_id="upload_sql",
        python_callable=_upload_sql,
    )

    execute_cluster = ctx.job_cluster_engine.create_execute_cluster_task(
        config_service=CONFIG_SERVICE,
        minimum_cluster_runtime_version=None,
        execute_job_cluster_local_id=None,
    )

    end = PythonOperator(
        task_id="end",
        python_callable=lambda **kw: None,
        outlets=[Dataset(DATASET_URI)],
    )

    capture_tasks = []

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_analyst",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_analyst",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_analyst",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_analyst",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_channel",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_channel",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_channel",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_channel",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_chatbot",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_chatbot",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_chatbot",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_chatbot",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_department",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_department",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_department",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_department",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_ra_ticket",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_ra_ticket",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_ra_ticket",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_ra_ticket",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_taxonomy",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_taxonomy",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_taxonomy",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_taxonomy",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_ticket",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_ticket",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_ticket",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_ticket",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_zendesk_user",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_zendesk_user",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_zendesk_user",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_zendesk_user",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_analysts_performance",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_analysts_performance",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_analysts_performance",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_analysts_performance",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_backlog_metrics_tasks",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_backlog_metrics_tasks",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_backlog_metrics_tasks",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_backlog_metrics_tasks",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_chat_messages",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_chat_messages",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_chat_messages",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_chat_messages",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_chat_metrics",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_chat_metrics",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_chat_metrics",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_chat_metrics",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_customer_contacts",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_customer_contacts",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_customer_contacts",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_customer_contacts",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_ivr_interactions",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_ivr_interactions",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_ivr_interactions",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_ivr_interactions",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_sessions_chatbot",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_sessions_chatbot",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_sessions_chatbot",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_sessions_chatbot",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_single_door_events",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_single_door_events",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_single_door_events",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_single_door_events",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_task_metrics",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_task_metrics",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_task_metrics",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_task_metrics",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_ticket_events",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_ticket_events",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_ticket_events",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_ticket_events",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_tickets",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_tickets",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_tickets",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_tickets",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_tickets_backlog",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_tickets_backlog",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_tickets_backlog",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_tickets_backlog",
            ],
            execution_timeout_hours=0.5,
        )
    )

    cluster_completion = get_job_cluster_completion_sink(ctx, execute_cluster, end)
    attach_emr_job_cluster_finished_work_prerequisites(
        ctx, job_cluster_finished_task=end, work_completion_tasks=capture_tasks
    )

    upload_sql >> execute_cluster >> capture_tasks >> cluster_completion
    attach_emr_terminate_cluster_work_prerequisites(
        ctx,
        cluster_completion,
        execute_job_cluster_task=execute_cluster,
        job_cluster_finished_task=end,
    )
