---
custom_cluster:
  driver_node_type_id: r5d.4xlarge
  node_type_id: r5n.4xlarge
  num_workers: 4
  aws_attributes:
    availability: ON_DEMAND
  spark_version: 12.2.x-scala2.12
spark_conf:
  spark.driver.maxResultSize: "0"
