"""Migration Twin DAG — run original queries on Databricks, capture metrics to S3.

Auto-generated by emr-migration-v2 skill.
Run ID: 3eda59b6-f7c0-480d-b2d4-b04eabef7d51
Scope: growth/amplitude_subpartitioned
"""

import os
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import urlparse

import yaml
from airflow import DAG, Dataset
from airflow.operators.python import PythonOperator

from bietlejuice.base.airflow.job_cluster_engine import (
    attach_emr_job_cluster_finished_work_prerequisites,
    attach_emr_terminate_cluster_work_prerequisites,
    attach_job_cluster_engine_to_context,
    get_job_cluster_completion_sink,
)
from bietlejuice.base.airflow.task_creators.dag_execution_context import (
    DagExecutionContext,
)
from bietlejuice.services.configuration_service import ConfigurationService

DAG_ID = "migration_twin_growth__amplitude_subpartitioned"
RUN_ID = "3eda59b6-f7c0-480d-b2d4-b04eabef7d51"
DOMAIN = "growth"
SOURCE_DAG_NAME = "amplitude_subpartitioned"
DATASET_URI = "migration:twin-growth__amplitude_subpartitioned-complete"
RUN_PREFIX = "emr-migration/runs/3eda59b6-f7c0-480d-b2d4-b04eabef7d51"
REFERENCE_DATE = "2026-07-25"
RUNTIME = "twin"
SQL_DIR_NAME = "clean"

TABLES = [
    "155696_refer_lead_referred_events",
    "155697_refer_lead_referred_events",
    "160023_affiliate_lead_referred_events",
    "170135_in_app_survey_answered_events",
    "170135_in_app_survey_completed_events",
    "170135_in_app_survey_dismissed_events",
    "170135_in_app_survey_displayed_events",
    "170135_in_app_survey_received_events",
    "170135_in_app_survey_viewed_events",
    "170135_offer_submitted_events",
    "170135_piloto_cw_message_sent_events",
    "170698_adjust_install_events",
    "170698_alert_subscription_confirmed_events",
    "170698_apply_filters_events",
    "170698_appsflyer_install_events",
    "170698_banner_perform_action_events",
    "170698_chat_menu_item_clicked_events",
    "170698_chat_pp_iq_channel_list_page_viewed_events",
    "170698_chat_screen_page_viewed_events",
    "170698_chatcrpp_button_clicked_events",
    "170698_checkout_order_credit_card_payment_button_tapped_events",
    "170698_checkout_order_credit_card_payment_failure_view_events",
    "170698_checkout_order_credit_card_payment_pending_view_events",
    "170698_checkout_order_credit_card_payment_success_view_events",
    "170698_checkout_order_credit_card_try_again_tapped_events",
    "170698_classifieds_viewed_events",
    "170698_coll_negotiation_menu_page_onload_events",
    "170698_coll_negotiation_menu_page_payment_cta_onclick_events",
    "170698_coll_negotiation_menu_page_payment_option_select_onclick_events",
    "170698_coll_negotiation_waiting_button_clicked_events",
    "170698_coll_negotiation_waiting_page_swipe_events",
    "170698_coll_negotiation_waiting_page_viewed_events",
    "170698_coll_review_check_negotiation_cta_onclick_events",
    "170698_coll_review_check_negotiation_page_onload_events",
    "170698_concierge_trigger_events",
    "170698_consorcio_cta_clicked_events",
    "170698_consorcio_lead_generated_events",
    "170698_consorcio_page_viewed_events",
    "170698_contact_broker_clicked_events",
    "170698_contract_docusign_signed_events",
    "170698_contract_page_viewed_events",
    "170698_contract_payment_summary_clicked_events",
    "170698_contract_payment_summary_viewed_events",
    "170698_copy_inspection_report_link_button_clicked_events",
    "170698_cxp_fine_info_page_viewed_events",
    "170698_cxp_fine_invoice_button_clicked_events",
    "170698_cxp_fine_more_info_button_clicked_events",
    "170698_cxp_fine_negotiate_button_clicked_events",
    "170698_cxp_flow_payments_page_viewed_events",
    "170698_cxp_main_page_next_steps_button_clicked_events",
    "170698_cxp_main_page_off_inspection_button_clicked_events",
    "170698_cxp_main_page_payments_button_clicked_events",
    "170698_cxp_main_page_post_exit_inspection_button_clicked_events",
    "170698_cxp_main_page_post_exit_page_viewed_events",
    "170698_cxp_main_page_post_exit_payments_button_clicked_events",
    "170698_cxp_main_page_postpone_termination_button_clicked_events",
    "170698_cxp_main_page_property_return_button_clicked_events",
    "170698_cxp_next_steps_page_viewed_events",
    "170698_cxp_payments_page_payment_receipts_button_clicked_events",
    "170698_cxp_payments_page_termination_fine_button_clicked_events",
    "170698_debug_visit_schedule_confirmed_events",
    "170698_doc_tenants_address_submit_events",
    "170698_doc_tenants_address_viewed_events",
    "170698_doc_tenants_basicinfo_submit_events",
    "170698_doc_tenants_basicinfo_viewed_events",
    "170698_doc_tenants_document_photo_clicked_events",
    "170698_doc_tenants_income_clicked_events",
    "170698_doc_tenants_income_submit_events",
    "170698_doc_tenants_list_viewed_events",
    "170698_doc_tenants_personal_submit_events",
    "170698_doc_tenants_personal_viewed_events",
    "170698_doc_tenants_selfie_clicked_events",
    "170698_doc_tenants_selfieok_submit_events",
    "170698_doc_tenants_submit_complete_events",
    "170698_edit_account_info_clicked_events",
    "170698_evaluation_anchor_clicked_events",
    "170698_evaluation_anchor_result_clicked_events",
    "170698_evaluation_anchor_viewed_events",
    "170698_evaluation_drop_clicked_events",
    "170698_evaluation_error_viewed_events",
    "170698_evaluation_errordialog_viewed_events",
    "170698_evaluation_onboarding_clicked_events",
    "170698_evaluation_onboarding_dismissed_events",
    "170698_evaluation_onboarding_viewed_events",
    "170698_evaluation_result_action_bar_clicked_events",
    "170698_evaluation_result_close_clicked_events",
    "170698_evaluation_result_cta_clicked_events",
    "170698_evaluation_result_guarantee_clicked",
    "170698_evaluation_result_newevaluation_clicked_events",
    "170698_evaluation_result_redoevaluation_clicked_events",
    "170698_evaluation_result_reservation_clicked_events",
    "170698_evaluation_result_search_clicked_events",
    "170698_evaluation_result_secondary_clicked_events",
    "170698_evaluation_result_senddocs_clicked_events",
    "170698_evaluation_result_viewed_events",
    "170698_evaluation_runevaluation_clicked_events",
    "170698_evaluation_selecttenants_viewed_events",
    "170698_evaluation_setvalue_viewed_events",
    "170698_evaluation_summary_viewed_events",
    "170698_evaluation_tenantform_viewed_events",
    "170698_evaluation_tenantslist_submitted_events",
    "170698_evaluation_timeout_result_clicked_events",
    "170698_evaluation_timeout_viewed_events",
    "170698_faq_article_page_viewed_events",
    "170698_feed_recommendation_page_viewed_events",
    "170698_fs_mortgage_progress_step_clicked_events",
    "170698_fs_mortgage_track_progress_button_clicked_events",
    "170698_fs_mortgage_track_progress_page_viewed_events",
    "170698_fs_mortgage_track_status_viewed_events",
    "170698_fs_task_page_viewed_events",
    "170698_help_center_article_clicked_events",
    "170698_help_center_article_recommendation_clicked_events",
    "170698_help_center_article_recommendation_viewed_events",
    "170698_help_center_call_cancel_button_clicked_events",
    "170698_help_center_call_request_button_clicked_events",
    "170698_help_center_call_viewed_events",
    "170698_help_center_faq_clicked_events",
    "170698_help_center_page_viewed_events",
    "170698_help_center_question_mark_clicked_events",
    "170698_help_center_wait_call_viewed_events",
    "170698_home_page_viewed_events",
    "170698_homes_subscription_confirmed_events",
    "170698_house_card_clicked_events",
    "170698_inspection_budgetapproval_home_page_viewed_events",
    "170698_inspection_review_home_page_viewed_events",
    "170698_lead_intent_confirmed_events",
    "170698_lead_intent_events",
    "170698_listing_early_credit_clicked_events",
    "170698_listing_favorite_remove_events",
    "170698_listing_favorite_set_events",
    "170698_listing_open_gallery_view_events",
    "170698_listing_page_viewed_events",
    "170698_listing_photosphere_opened_events",
    "170698_listing_video_started_events",
    "170698_login_confirmation_viewed_events",
    "170698_mc_landing_page_viewed",
    "170698_mortgage_home_viewed_events",
    "170698_my_checkout_page_viewed_events",
    "170698_my_rent_pending_invoices_card_view_events",
    "170698_native_home_page_viewed_events",
    "170698_native_home_section_banner_events",
    "170698_native_home_section_tiles_list_events",
    "170698_ntc_notification_clicked_events",
    "170698_offboarding_inspections_repairs_task_button_clicked_events",
    "170698_offboarding_keys_task_start_setup_page_viewed_events",
    "170698_offboarding_keys_task_success_page_viewed_events",
    "170698_offboarding_repair_guidelines_entry_inspection_clicked_events",
    "170698_offboarding_repair_guidelines_negotiate_repairs_card_viewed_events",
    "170698_offboarding_repair_guidelines_task_accordion_clicked_events",
    "170698_offboarding_repairs_task_success_page_viewed_events",
    "170698_offboarding_terminationcontrol_inspection_page_viewed_events",
    "170698_offboarding_terminationcontrol_page_viewed_events",
    "170698_offboarding_utilitybills_receipts_page_viewed_events",
    "170698_offer_accepted_new_events",
    "170698_offer_canceled_new_events",
    "170698_offer_submitted_events",
    "170698_offer_submitted_new_events",
    "170698_offerinfo_page_viewed_events",
    "170698_overdue_invoices_invoice_pay_button_clicked_events",
    "170698_overdue_invoices_invoice_pay_total_button_clicked_events",
    "170698_overdue_invoices_page_viewed_events",
    "170698_overdue_invoices_payment_option_clicked_events",
    "170698_overdue_invoices_payment_option_viewed_events",
    "170698_overdue_invoices_payment_options_closed_events",
    "170698_overdue_invoices_total_payment_option_clicked_events",
    "170698_overdue_invoices_total_payment_option_viewed_events",
    "170698_owner_termination_management_page_viewed_events",
    "170698_pending_invoices_exception_cta_clicked_events",
    "170698_pending_invoices_exception_cta_goback_clicked_events",
    "170698_pending_invoices_exception_page_viewed_events",
    "170698_pending_invoices_invoice_pay_button_clicked_events",
    "170698_pending_invoices_negotiation_cta_clicked_events",
    "170698_pending_invoices_overdue_card_viewed_events",
    "170698_pending_invoices_page_viewed_events",
    "170698_pending_invoices_pay_invoice_cta_clicked_events",
    "170698_pending_invoices_pay_total_cta_clicked_events",
    "170698_pending_invoices_payment_option_clicked_events",
    "170698_pi_negotiation_payment_option_clicked_events",
    "170698_pi_negotiation_payment_option_closed_events",
    "170698_pi_negotiation_started_page_viewed_events",
    "170698_piloto_cw_message_sent_events",
    "170698_price_suggestion_address_submitted_events",
    "170698_price_suggestion_page_viewed_events",
    "170698_profiling_complete_clicked_events",
    "170698_pv_management_area_viewed_events",
    "170698_pv_management_hub_viewed_events",
    "170698_recset_impression_events",
    "170698_recset_viewed_events",
    "170698_repair_center_ps_iq_budget_sent_budget_details_clicked_events",
    "170698_rm_invoice_page_viewed_events",
    "170698_rm_invoice_payment_option_clicked_events",
    "170698_rm_invoice_pix_copy_paste_clicked_events",
    "170698_rm_myrent_page_viewed_events",
    "170698_rm_pending_invoices_page_viewed_events",
    "170698_sale_offer_form_accepted_events",
    "170698_schedule_page_viewed_events",
    "170698_search_page_viewed_events",
    "170698_search_results_page_viewed_events",
    "170698_select_listing_visit_button_clicked_events",
    "170698_session_start_events",
    "170698_share_listing_events",
    "170698_tap_intent_selection_register_property_events",
    "170698_tile_perform_action_events",
    "170698_tts_success_page_viewed_events",
    "170698_unavailable_listing_viewed_events",
    "170698_user_accepted_scr_terms_clicked_event_events",
    "170698_user_has_been_blocked_on_ivr_events",
    "170698_user_ivr_still_accessible_events",
    "170698_user_merge",
    "170698_user_tried_to_call_again_after_blocked_events",
    "170698_visit_fitting_page_viewed_events",
    "170698_visit_fitting_requested_success_page_viewed_events",
    "170698_visit_hoursalert_confirmed_events",
    "170698_visit_intent_clicked_events",
    "170698_visit_list_request_schedule_button_clicked_events",
    "170698_visit_schedule_clicked_events",
    "170698_visit_schedule_confirmed_events",
    "170698_visit_schedule_continue_clicked_events",
    "183047_ad_improvements_first_access_page_viewed_events",
    "183047_ad_improvements_intent_button_clicked_events",
    "183047_ad_improvements_page_viewed_events",
    "183047_ad_improvements_price_in_range_page_viewed_events",
    "183047_ad_improvements_price_recommendation_accepted_button_clicked_events",
    "183047_ad_improvements_price_recommendation_page_viewed_events",
    "183047_ad_improvements_price_strategy_button_clicked_events",
    "183047_atlas_db_address_search_events",
    "183047_atlas_db_house_characteristics_events",
    "183047_chatcrpp_blocked_message_alert_shown_events",
    "183047_chatcrpp_chat_conversation_started_events",
    "183047_chatcrpp_chat_page_viewed_events",
    "183047_chatcrpp_suspicious_message_sent_events",
    "183047_chatcrpp_warning_message_alert_shown_events",
    "183047_contract_page_viewed_events",
    "183047_contract_termination_page_viewed_events",
    "183047_entry_model_change_confirmed_button_clicked_events",
    "183047_entry_model_change_success_page_viewed_events",
    "183047_entry_model_details_page_viewed_events",
    "183047_entry_model_form_page_viewed_events",
    "183047_faq_article_page_viewed_events",
    "183047_fs_mortgage_track_progress_button_clicked_events",
    "183047_fs_mortgage_track_progress_page_viewed_events",
    "183047_fs_mortgage_track_status_viewed_events",
    "183047_fs_task_page_viewed_events",
    "183047_help_center_article_clicked_events",
    "183047_help_center_article_recommendation_clicked_events",
    "183047_help_center_article_recommendation_viewed_events",
    "183047_help_center_faq_clicked_events",
    "183047_help_center_page_viewed_events",
    "183047_help_center_question_mark_clicked_events",
    "183047_house_in_early_relisting_events",
    "183047_house_management_deep_link_handled_events",
    "183047_inspection_report_button_clicked_events",
    "183047_intro_page_viewed_events",
    "183047_landing_page_viewed_events",
    "183047_lead_form_submitted_events",
    "183047_listing_location_submitted_events",
    "183047_listing_overpriced_comms_routine_eligible_events",
    "183047_listing_overpriced_comms_routine_excluded_events",
    "183047_listing_published_events",
    "183047_listing_terms_confirmed_events",
    "183047_lra_simple_simulation_clicked_events",
    "183047_mortgage_home_viewed_events",
    "183047_mra_acceptance_viewed_events",
    "183047_mra_description_clicked_events",
    "183047_mra_description_viewed_events",
    "183047_mra_widget_clicked_events",
    "183047_native_home_page_viewed_events",
    "183047_native_home_section_properties_list_events",
    "183047_offboarding_keys_task_button_clicked_events",
    "183047_offboarding_keys_task_select_location_page_viewed_events",
    "183047_offboarding_keys_task_success_page_viewed_events",
    "183047_offer_accepted_new_events",
    "183047_offer_canceled_new_events",
    "183047_offer_list_page_viewed_events",
    "183047_offer_submitted_new_events",
    "183047_offers_list_results_viewed_events",
    "183047_price_edit_confirmed_button_clicked_events",
    "183047_price_edit_intent_button_clicked_events",
    "183047_price_edit_page_viewed_events",
    "183047_price_edit_query_parameters_tracked_events",
    "183047_price_edit_review_page_viewed_events",
    "183047_price_report_landing_rent_page_viewed_events",
    "183047_price_report_landing_sale_page_viewed_events",
    "183047_price_suggestion_advertise_clicked_events",
    "183047_price_suggestion_form_submitted_events",
    "183047_price_suggestion_page_viewed_events",
    "183047_price_suggestion_sale_form_submitted_events",
    "183047_price_suggestion_sale_page_viewed_events",
    "183047_property_details_page_viewed_events",
    "183047_property_edit_hub_page_viewed_events",
    "183047_property_edit_price_intent_button_clicked_events",
    "183047_property_list_page_viewed_events",
    "183047_property_list_success_page_viewed_events",
    "183047_property_page_viewed_events",
    "183047_property_performance_hub_available_hours_button_clicked_events",
    "183047_property_performance_hub_available_hours_card_button_clicked_events",
    "183047_property_performance_hub_button_clicked_events",
    "183047_property_performance_hub_page_viewed_events",
    "183047_property_performance_hub_price_button_clicked_events",
    "183047_property_performance_hub_price_card_button_clicked_events",
    "183047_property_performance_hub_switched_events",
    "183047_pv_management_area_viewed_events",
    "183047_pv_management_hub_viewed_events",
    "183047_relisting_early_visits_confirmed_events",
    "183047_rent_pricing_new_listing_form_submitted_events",
    "183047_rent_pricing_new_listing_page_viewed_events",
    "183047_reviews_page_viewed_events",
    "183047_rm_myrent_page_viewed_events",
    "183047_sale_calculator_edition_form_submitted_events",
    "183047_sale_calculator_page_viewed_events",
    "183047_sale_price_page_viewed_events",
    "183047_sale_pricing_existing_listing_form_submitted_events",
    "183047_sale_pricing_existing_listing_page_viewed_events",
    "183047_sale_pricing_new_listing_form_submitted_events",
    "183047_sale_pricing_new_listing_page_viewed_events",
    "183047_terms_page_viewed_events",
    "183047_user_merge",
    "183049_offer_submitted_events",
    "203461_inspector_app_add_photo_clicked_events",
    "205027_intro_page_viewed_events",
    "205027_referral_form_accepted_events",
    "205027_referral_form_discarded_events",
    "233592_agenda_visit_list_page_viewed_events",
    "233592_agent_with_keys_property_indication_button_clicked_events",
    "233592_agent_with_keys_property_indication_copy_button_clicked_events",
    "233592_agent_with_keys_property_indication_error_events",
    "233592_agent_with_keys_property_indication_page_viewed_events",
    "233592_agent_with_keys_property_indication_search_feedback_events",
    "233592_chatcrpp_accep_terms_button_clicked_events",
    "233592_chatcrpp_allchats_page_viewed_events",
    "233592_chatcrpp_blocked_message_alert_shown_events",
    "233592_chatcrpp_chat_conversation_started_events",
    "233592_chatcrpp_chat_page_viewed_events",
    "233592_chatcrpp_suspicious_message_sent_events",
    "233592_chatcrpp_warning_message_alert_shown_events",
    "233592_entry_model_validation_button_clicked_events",
    "233592_keys_management_page_viewed_events",
    "233592_keys_management_property_indication_card_clicked_events",
    "233592_recommend_send_an_offer_events",
    "233592_shortcut_more_visits_intent_clicked_events",
    "233592_shortcut_more_visits_success_page_viewed_events",
    "233592_shortcut_more_visits_viewed_events",
    "233592_talk_to_the_owner_events",
    "233592_tts_helps_button_clicked_events",
    "233592_visit_finalization_agent_profilling_button_clicked_events",
    "233592_visit_finalization_agent_success_page_viewed_events",
    "250821_photo_session_detail_viewed_events",
    "283048_register_form_completed_events",
    "370096_properties_entry_model_drawer_update_error_events",
    "370096_property_publish_success_events",
    "417002_datahub_entity_action_events",
    "417002_datahub_entity_section_view_events",
    "417002_datahub_entity_view_events",
    "417002_datahub_home_page_view_events",
    "417002_datahub_page_view_events",
    "417002_datahub_search_events",
    "417002_datahub_search_result_click_events",
    "417002_datahub_search_results_view_events",
    "417002_datahub_select_auto_complete_option_events",
    "440441_home_page_viewed_events",
    "440441_listing_registration_location_page_viewed_events",
    "440441_sale_offer_list_details_button_clicked_events",
    "525551_listing_page_viewed_events",
    "525551_schedule_visit_at_5a_button_clicked_events",
    "525551_search_page_viewed_events",
]

DAG_DIR = Path(__file__).resolve().parent
ENV = os.environ.get("ENVIRONMENT")
CONFIG_SERVICE = ConfigurationService(SOURCE_DAG_NAME)
BUCKET = CONFIG_SERVICE.get_config("datalake_bucket")
BIETLEJUICE_REPO_PATH = CONFIG_SERVICE.get_config("databricks_bietlejuice_repo_path")
METRIC_CAPTURE_JOB = (
    f"{BIETLEJUICE_REPO_PATH}/spark_jobs/migration_assets/metric_capture_job.py"
)
ARTIFACTS_URI = CONFIG_SERVICE.get_config("artifacts_bucket")
ARTIFACTS_BUCKET = urlparse(ARTIFACTS_URI).netloc or ARTIFACTS_URI

with open(DAG_DIR / f"{DAG_ID}_cluster.yml") as _f:
    CLUSTER_ARGS = yaml.safe_load(_f).get("cluster", {})


def _build_context(dag):
    ctx = DagExecutionContext(
        dag=dag,
        environment=ENV,
        bucket=BUCKET,
        base_spark_jobs_path=f"{BIETLEJUICE_REPO_PATH}/spark_jobs/base/",
        dag_args={},
        workflow_args={},
        cluster_args=CLUSTER_ARGS,
        databricks_conn_id=CLUSTER_ARGS.get("databricks_conn_id", "databricks_new_env"),
    )
    attach_job_cluster_engine_to_context(ctx, CONFIG_SERVICE)
    return ctx


def _get_s3_client():
    import boto3
    from airflow.models import Variable

    role_arn = Variable.get("DATASET_EVENTS_ASSUME_ROLE_ARN", default_var=None)
    if not role_arn:
        return boto3.client("s3")
    sts = boto3.client("sts")
    creds = sts.assume_role(
        RoleArn=role_arn,
        RoleSessionName="migration-s3-upload",
        DurationSeconds=3600,
    )["Credentials"]
    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
    ).client("s3")


def _upload_sql(**context):
    sql_dir = DAG_DIR / "queries" / SQL_DIR_NAME
    s3 = _get_s3_client()
    for table in TABLES:
        local_path = str(sql_dir / f"{table}.sql")
        s3_key = f"{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}.sql"
        s3.upload_file(local_path, ARTIFACTS_BUCKET, s3_key)


with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["migration", "twin", "validation"],
    default_args={"owner": "data-platform", "retries": 0},
    dagrun_timeout=timedelta(hours=4),
) as dag:
    ctx = _build_context(dag)

    upload_sql = PythonOperator(
        task_id="upload_sql",
        python_callable=_upload_sql,
    )

    end = PythonOperator(
        task_id="end",
        python_callable=lambda **kw: None,
        outlets=[Dataset(DATASET_URI)],
    )

    MAX_TASKS_PER_CLUSTER = 100
    batches = [
        TABLES[i : i + MAX_TASKS_PER_CLUSTER]
        for i in range(0, len(TABLES), MAX_TASKS_PER_CLUSTER)
    ]

    for batch_idx, batch_tables in enumerate(batches):
        local_id = None if batch_idx == 0 else batch_idx + 1

        batch_execute = ctx.job_cluster_engine.create_execute_cluster_task(
            config_service=CONFIG_SERVICE,
            minimum_cluster_runtime_version=None,
            execute_job_cluster_local_id=local_id,
        )

        batch_captures = []
        for table in batch_tables:
            batch_captures.append(
                ctx.job_cluster_engine.create_spark_python_task(
                    spark_job_path=METRIC_CAPTURE_JOB,
                    task_id=f"capture_{table}",
                    job_parameters=[
                        "--sql-s3-uri",
                        f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}",
                        "--result-s3-uri",
                        f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}",
                        "--run-id",
                        RUN_ID,
                        "--runtime",
                        "databricks",
                        "--domain",
                        DOMAIN,
                        "--dag-name",
                        SOURCE_DAG_NAME,
                        "--table-name",
                        table,
                        "--reference-date",
                        REFERENCE_DATE,
                    ],
                    execution_timeout_hours=2,
                )
            )

        batch_completion = get_job_cluster_completion_sink(
            ctx, batch_execute, end, local_id
        )
        attach_emr_job_cluster_finished_work_prerequisites(
            ctx, job_cluster_finished_task=end, work_completion_tasks=batch_captures
        )

        upload_sql >> batch_execute >> batch_captures >> batch_completion
        attach_emr_terminate_cluster_work_prerequisites(
            ctx,
            batch_completion,
            execute_job_cluster_task=batch_execute,
            job_cluster_finished_task=end,
        )
