SELECT
    id_prospect_agent AS sk_prospect_agent,
    id_agent AS sk_agent,
    id_qualification AS sk_qualification,
    id_business_unit AS sk_business_unit,
    id_region AS sk_region,
    uuid_prospect,
    uuid_person,
    legal_entity_type,
    status,
    qualification_state,
    creci_validation_status,
    contract_signature_status,
    contract_template_name,
    business_association,
    business_context_applied,
    quintoandar_knowledge,
    social,
    creci,
    creci_uf,
    commuting_method,
    referral_code,
    maximum_acquisition_per_month,
    minimum_acquisition_per_month,
    maximum_available_days,
    minimum_available_days,
    years_of_experience,
    is_available_on_weekends,
    is_accepted_alternative_context,
    is_accepted_alternative_region,
    is_last_prospect_person_converted,
    ts_creci_validation_approved,
    ts_contract_process_initiated,
    ts_contract_signed,
    ts_contract_process_finished,
    ts_created,
    ts_updated
FROM
    datalake_agent_accreditation.prospect_agent
