SELECT
    business_context,
    display_type,
    experiments,
    experiments_variants,
    dt_rec_received,

    COUNT(1) AS count_recsets,

    --k_3
    SUM(precision_at_3) AS sum_precision_at_3,
    SUM(recall_at_3) AS sum_recall_at_3,
    SUM(2 * (precision_at_3 * recall_at_3) / (precision_at_3 +recall_at_3)) AS sum_f1_at_3,
    SUM(hit_rate_at_3) AS sum_hit_rate_at_3,
    SUM(rr_at_3) AS sum_rr_at_3,
    SUM(ap_at_3) AS sum_ap_at_3,
    SUM(ndcg_at_3) AS sum_ndcg_at_3,
    -- SUM(diversity_at_3) AS sum_diversity_at_3,
    SUM(repetition_at_3) AS sum_repetition_at_3,
    SUM(rec_to_favorite_at_3) AS sum_rec_to_favorite_at_3,
    SUM(rec_to_sale_flow_one_day_at_3) AS sum_rec_to_sale_flow_one_day_at_3,
    SUM(rec_to_sale_flow_fourteen_days_at_3) AS sum_rec_to_sale_flow_fourteen_days_at_3,
    SUM(rec_to_rent_flow_one_day_at_3) AS sum_rec_to_rent_flow_one_day_at_3,
    SUM(rec_to_rent_flow_seven_days_at_3) AS sum_rec_to_rent_flow_seven_days_at_3,
    SUM(hit_rec_to_sale_flow_one_day_at_3) AS sum_hit_rec_to_sale_flow_one_day_at_3,
    SUM(hit_rec_to_sale_flow_fourteen_days_at_3) AS sum_hit_rec_to_sale_flow_fourteen_days_at_3,
    SUM(hit_rec_to_rent_flow_one_day_at_3) AS sum_hit_rec_to_rent_flow_one_day_at_3,
    SUM(hit_rec_to_rent_flow_seven_days_at_3) AS sum_hit_rec_to_rent_flow_seven_days_at_3,
    SUM(popularity_at_3) AS sum_popularity_at_3,
    SUM(true_positive_and_sale_flow_fourteen_days_at_3) AS sum_true_positive_and_sale_flow_fourteen_days_at_3,
    SUM(true_positive_and_rent_flow_seven_days_at_3) AS sum_true_positive_and_rent_flow_seven_days_at_3,
    SUM(hit_true_positive_and_sale_flow_fourteen_days_at_3) AS sum_hit_true_positive_and_sale_flow_fourteen_days_at_3,
    SUM(hit_true_positive_and_rent_flow_seven_days_at_3) AS sum_hit_true_positive_and_rent_flow_seven_days_at_3,
    SUM(count_true_positive_at_3) AS sum_true_positive_at_3,

    --k_5
    SUM(precision_at_5) AS sum_precision_at_5,
    SUM(recall_at_5) AS sum_recall_at_5,
    SUM(2 * (precision_at_5 * recall_at_5) / (precision_at_5 +recall_at_5)) AS sum_f1_at_5,
    SUM(hit_rate_at_5) AS sum_hit_rate_at_5,
    SUM(rr_at_5) AS sum_rr_at_5,
    SUM(ap_at_5) AS sum_ap_at_5,
    SUM(ndcg_at_5) AS sum_ndcg_at_5,
    -- SUM(diversity_at_5) AS sum_diversity_at_5,
    SUM(repetition_at_5) AS sum_repetition_at_5,
    SUM(rec_to_favorite_at_5) AS sum_rec_to_favorite_at_5,
    SUM(rec_to_sale_flow_one_day_at_5) AS sum_rec_to_sale_flow_one_day_at_5,
    SUM(rec_to_sale_flow_fourteen_days_at_5) AS sum_rec_to_sale_flow_fourteen_days_at_5,
    SUM(rec_to_rent_flow_one_day_at_5) AS sum_rec_to_rent_flow_one_day_at_5,
    SUM(rec_to_rent_flow_seven_days_at_5) AS sum_rec_to_rent_flow_seven_days_at_5,
    SUM(hit_rec_to_sale_flow_one_day_at_5) AS sum_hit_rec_to_sale_flow_one_day_at_5,
    SUM(hit_rec_to_sale_flow_fourteen_days_at_5) AS sum_hit_rec_to_sale_flow_fourteen_days_at_5,
    SUM(hit_rec_to_rent_flow_one_day_at_5) AS sum_hit_rec_to_rent_flow_one_day_at_5,
    SUM(hit_rec_to_rent_flow_seven_days_at_5) AS sum_hit_rec_to_rent_flow_seven_days_at_5,
    SUM(popularity_at_5) AS sum_popularity_at_5,
    SUM(true_positive_and_sale_flow_fourteen_days_at_5) AS sum_true_positive_and_sale_flow_fourteen_days_at_5,
    SUM(true_positive_and_rent_flow_seven_days_at_5) AS sum_true_positive_and_rent_flow_seven_days_at_5,
    SUM(hit_true_positive_and_sale_flow_fourteen_days_at_5) AS sum_hit_true_positive_and_sale_flow_fourteen_days_at_5,
    SUM(hit_true_positive_and_rent_flow_seven_days_at_5) AS sum_hit_true_positive_and_rent_flow_seven_days_at_5,
    SUM(count_true_positive_at_5) AS sum_true_positive_at_5,

    --k_10
    SUM(precision_at_10) AS sum_precision_at_10,
    SUM(recall_at_10) AS sum_recall_at_10,
    SUM(2 * (precision_at_10 * recall_at_10) / (precision_at_10 +recall_at_10)) AS sum_f1_at_10,
    SUM(hit_rate_at_10) AS sum_hit_rate_at_10,
    SUM(rr_at_10) AS sum_rr_at_10,
    SUM(ap_at_10) AS sum_ap_at_10,
    SUM(ndcg_at_10) AS sum_ndcg_at_10,
    -- SUM(diversity_at_10) AS sum_diversity_at_10,
    SUM(repetition_at_10) AS sum_repetition_at_10,
    SUM(rec_to_favorite_at_10) AS sum_rec_to_favorite_at_10,
    SUM(rec_to_sale_flow_one_day_at_10) AS sum_rec_to_sale_flow_one_day_at_10,
    SUM(rec_to_sale_flow_fourteen_days_at_10) AS sum_rec_to_sale_flow_fourteen_days_at_10,
    SUM(rec_to_rent_flow_one_day_at_10) AS sum_rec_to_rent_flow_one_day_at_10,
    SUM(rec_to_rent_flow_seven_days_at_10) AS sum_rec_to_rent_flow_seven_days_at_10,
    SUM(hit_rec_to_sale_flow_one_day_at_10) AS sum_hit_rec_to_sale_flow_one_day_at_10,
    SUM(hit_rec_to_sale_flow_fourteen_days_at_10) AS sum_hit_rec_to_sale_flow_fourteen_days_at_10,
    SUM(hit_rec_to_rent_flow_one_day_at_10) AS sum_hit_rec_to_rent_flow_one_day_at_10,
    SUM(hit_rec_to_rent_flow_seven_days_at_10) AS sum_hit_rec_to_rent_flow_seven_days_at_10,
    SUM(popularity_at_10) AS sum_popularity_at_10,
    SUM(true_positive_and_sale_flow_fourteen_days_at_10) AS sum_true_positive_and_sale_flow_fourteen_days_at_10,
    SUM(true_positive_and_rent_flow_seven_days_at_10) AS sum_true_positive_and_rent_flow_seven_days_at_10,
    SUM(hit_true_positive_and_sale_flow_fourteen_days_at_10) AS sum_hit_true_positive_and_sale_flow_fourteen_days_at_10,
    SUM(hit_true_positive_and_rent_flow_seven_days_at_10) AS sum_hit_true_positive_and_rent_flow_seven_days_at_10,
    SUM(count_true_positive_at_10) AS sum_true_positive_at_10
FROM
    datalake_recommendations.recommendation_metrics_agg_recset
WHERE
    recommendation_metrics_agg_recset.dt_rec_received
      BETWEEN DATE_SUB(DATE('{start_date}'), {days_past}) AND DATE('{end_date}')
GROUP BY
    business_context,
    display_type,
    experiments,
    experiments_variants,
    dt_rec_received
