SELECT 
    contrato AS id_contract,
    imovel AS id_house,
    bairro AS house_district,
    cidade AS house_city,
    regiao AS house_region,
    hsl_5a AS hsl_or_5a,
    status_vt,
    atualizacao_tarde AS late_update,
    status_ct,
    atendida_pela_rede AS served_by_network,
    atendida_pela_randstad AS serverd_by_randstad,
    motivo_cancelamento AS cancellation_reason,
    analista AS agent_name,
    motivo_nao_agendamento AS reasons_not_scheduling,
    sem_contato_com_pp_iq AS no_contact_with_pp_iq,
    CAST(n_tentativas_ligacoes AS BIGINT) AS number_of_attempts,
    whatsapp AS whatsapp_number,
    email,
    canal_resposta AS response_channel,
    qual_sla AS sla_response,
    motivo_sla AS sla_reason,
    periodo AS load_period,
    existiu_contato_com_pp AS contact_with_pp,
    precisou_remanejar_vistoria AS needed_rehandle_inspection,
    agendado AS scheduled,
    b2b,
    TO_DATE(ultimo_agendamento, 'dd/MM/yyyy') AS dt_last_scheduled,
    TO_DATE(vigencia, 'dd/MM/yyyy') AS dt_effectived,
    CAST(ts_load AS TIMESTAMP) AS ts_load,
    CAST(year AS BIGINT) AS year,
    CAST(month AS BIGINT) AS month,
    CAST(day AS BIGINT) AS day
FROM
    datalake_gsheets_raw.agendamento_vistoria_entrada