SELECT
    contrato AS id_contract,
    imovel AS id_house,
    bairro AS house_district,
    cidade AS house_city,
    bairro_cidade AS house_address,
    regiao AS house_region,
    link_crm AS crm_url,
    foxter_cia_imobiliaria AS company,
    hsl_5a AS hsl_or_5a,
    status_ct, 
    status_vt,
    CAST(leadtime AS BIGINT) AS leadtime,
    atualizacao_tarde AS late_update,
    motivo_cancelamento AS cancellation_reason,
    analista AS agent_name,
    motivos_nao_agendamento AS reasons_not_scheduling,
    acompanhante_vistoria AS escort_in_inspection,
    resumo_caso AS summary_case,
    regional AS regional_description,
    contantou_PP AS contacted_PP,
    CAST(numero_tentativas AS BIGINT) AS number_of_attempts,
    whatsapp AS whatsapp_number,
    email,
    canal_resposta AS response_channel,
    load AS load_period,
    agendado AS scheduled,
    b2b,
    tarefa_aberta AS open_task,
    DATE(data_saida) AS dt_departured,
    TO_DATE(data_recisao, 'dd/MM/yyyy') AS dt_rescission,
    CAST(ts_load AS TIMESTAMP) AS ts_load,
    CAST(year AS BIGINT) AS year,
    CAST(month AS BIGINT) AS month,
    CAST(day AS BIGINT) AS day
FROM
    datalake_gsheets_raw.agendamento_vistoria_saida