SELECT
    id,
    sales_flow_id AS id_sales_flow,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    use_fgts AS has_fgts_draft,
    has_final_value_refund,
    is_seller_pj,
    is_buyer_pj,
    sales_flow_id_mod AS mod_id_sales_flow,
    use_fgts_mod AS mod_has_fgts_draf,
    has_final_value_refund_mod AS mod_has_final_value_refund,
    is_seller_pj_mod AS mod_is_seller_pj,
    is_buyer_pj_mod AS mod_is_buyer_pj,
    buyer_documentation_started_at_mod AS mod_ts_buyer_documentation_started,
    buyer_documentation_submitted_at_mod AS mod_ts_buyer_documentation_submitted,
    seller_documentation_started_at_mod AS mod_ts_seller_documentation_started,
    seller_documentation_submitted_at_mod AS mod_ts_seller_documentation_submitted,
    buyer_credit_started_at_mod AS mod_ts_buyer_credit_started,
    buyer_credit_submitted_at_mod AS mod_ts_buyer_credit_submitted,
    buyer_documentation_started_at AS ts_buyer_documentation_started,
    buyer_documentation_submitted_at AS ts_buyer_documentation_submitted,
    seller_documentation_started_at AS ts_seller_documentation_started,
    seller_documentation_submitted_at AS ts_seller_documentation_submitted,
    buyer_credit_started_at AS ts_buyer_credit_started,
    buyer_credit_submitted_at AS ts_buyer_credit_submitted,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM 
    datalake_sales_flow_test_raw.negotiation_aud