SELECT
    id,
    sales_flow_id AS id_sales_flow,
    reject_reason_id AS id_reject_reason,
    firestore_id AS id_firestore,
    hub_id AS id_hub,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    offer_price,
    sale_price,
    final_price,
    itbi_price,
    registry_price,
    deed_price,
    preemptive_right,
    discard_reason,
    status,
    used_offer_suggestion AS has_used_offer_suggestion,
    sales_flow_id_mod AS mod_id_sales_flow,
    firestore_id_mod AS mod_id_firestore,
    reject_reason_id_mod AS mod_id_reject_reason,
    hub_id_mod AS mod_id_hub,
    offer_price_mod AS mod_offer_price,
    sale_price_mod AS mod_sale_price,
    final_price_mod AS mod_final_price,
    itbi_price_mod AS mod_itbi_price,
    registry_price_mod AS mod_registry_price,
    deed_price_mod AS mod_deed_price,
    preemptive_right_mod AS mod_preemptive_right,
    discard_reason_mod AS mod_discard_reason,
    status_mod AS mod_status,
    used_offer_suggestion_mod AS mod_has_used_offer_suggestion,
    proposal_date_mod AS mod_dt_proposed,
    accepted_at_mod AS mod_ts_accepted,
    validated_at_mod AS mod_ts_validated,
    discarded_at_mod AS mod_ts_discarded,
    proposal_date AS dt_proposed,
    accepted_at AS ts_accepted,
    validated_at AS ts_validated,
    discarded_at AS ts_discarded,
    created_at AS ts_created,
    updated_at AS ts_updated,
    year,
    month,
    day
FROM
    datalake_sales_flow_test_raw.offer_aud