SELECT
    id_amplitude,
    id_app,
    id_device,
    id_event,
    id_session,
    id_user,
    id_inserted,
    city,
    country,
    data,
    device_family,
    device_type,
    event_type,
    event_properties,
    GET_JSON_OBJECT(event_properties, '$.operation_customer_edition') AS operation_customer_edition,
    GET_JSON_OBJECT(event_properties, '$.product') AS product,
    GET_JSON_OBJECT(event_properties, '$.operation_type') AS operation_type,
    GET_JSON_OBJECT(event_properties, '$.dejavuid') AS dejavuid,
    GET_JSON_OBJECT(event_properties, '$.match_response') AS match_response,
    GET_JSON_OBJECT(event_properties, '$.user_response') AS user_response,
    GET_JSON_OBJECT(event_properties, '$.login_status') AS login_status,
    GET_JSON_OBJECT(event_properties, '$.form_step') AS form_step,
    GET_JSON_OBJECT(event_properties, '$.match_type') AS match_type,
    GET_JSON_OBJECT(event_properties, '$.business_context') AS business_context,
    GET_JSON_OBJECT(event_properties, '$.lead_id') AS lead_id,
    ip_address,
    os_name,
    os_version,
    platform,
    library,
    region,
    start_version,
    user_properties,
    language,
    uuid,
    version_name,
    ts_event,
    ts_server_received,
    ts_server_uploaded,
    ts_processed,
    ts_client_event,
    ts_client_uploaded,
    year,
    month,
    day
FROM
    datalake_amplitude_clean.events
WHERE
    id_app = '183047' AND event_type = 'atlas_db_house_characteristics'
    AND MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'