SELECT
    id,
    development_contact_id AS id_development_contact,
    development_uuid,
    external_id,
    company_uuid,
    provider,
    name,
    description,
    construction_status,
    legal_permit,
    postal_code,
    street,
    street_number,
    neighborhood,
    city,
    state,
    latitude,
    longitude,
    towers,
    floors,
    apartments_per_floor,
    min_condominium_fee,
    min_iptu,
    launch_date,
    forecast_delivery_date,
    last_validated_at AS ts_last_validated,
    withdrawn_at AS ts_withdrawn,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_ebdb_raw.Development
