SELECT
    CAST(id_ticket AS BIGINT) AS sk_ticket,
    CAST(COALESCE(id_problem_ticket) AS BIGINT) AS sk_problem_ticket,
    IF(OCTET_LENGTH(subject) >= 65535, SUBSTRING(subject, 0, 60000), subject) AS subject,
    IF(OCTET_LENGTH(description) >= 65535, SUBSTRING(description, 0, 60000), description) AS description,
    via_channel AS ticket_via,
    channel,
    group_name,
    priority,
    recipient,
    tags,
    status,
    type AS ticket_type,
    custom_fields,
    CAST(GET_JSON_OBJECT(satisfaction_rating,'$.score') AS STRING) AS score,
    CAST(GET_JSON_OBJECT(satisfaction_rating,'$.reason') AS STRING) AS reason,
    CAST(GET_JSON_OBJECT(satisfaction_rating,'$.comment') AS STRING) AS comment,
    analyst_organization AS agent_organization,
    request_type,
    client_type,
    step_tag,
    customer_type_tag,
    contact_motivation_tag,
    contact_theme_tag,
    contact_theme_detail_tag,
    is_public AS has_public_comments,
    ts_created,
    ts_created - INTERVAL 3 HOUR AS ts_created_local,
    ts_updated,
    ts_updated - INTERVAL 3 HOUR AS ts_updated_local,
    NOW() AS ts_load
FROM
    datalake_zendesk.tickets_current
