SELECT
    CAST(id_ticket AS BIGINT) AS sk_ticket,
    CAST(COALESCE(id_problem_ticket) AS BIGINT) AS sk_problem_ticket,
    if(octet_length(subject)>=65535, substring(subject,0,60000), subject) AS subject,
    if(octet_length(description)>=65535, substring(description,0,60000), description) AS description,
    ticket_via,
    channel,
    group_name,
    priority,
    recipient,
    tags,
    status,
    ticket_type,
    custom_fields,
    score,
    reason,
    comment,
    request_type,
    client_type,
    step_tag,
    customer_type_tag,
    contact_motivation_tag,
    contact_theme_tag,
    contact_theme_detail_tag,
    has_public_comments,
    ts_created,
    ts_created_local,
    ts_updated,
    ts_updated_local,
    NOW() AS ts_load
FROM
    datalake_zendesk_ticket_funnels.ticket_funnel
