import time
from datetime import datetime

from collections import OrderedDict
from qa_python_utils.aws.athena import AthenaClient
from qa_python_utils.default_logger import logger

from bietlejuice.jobs.base.base_etl import BaseETL
from bietlejuice.jobs.new_etl import DATALAKE_QUERIES_DIR


class GoogleAdsClean(object):
    QUERY_PATH = 'marketing/google_ads/raw_to_clean'
    TABLE_PARTITION_DATE = '__PARTITION_DATE__'
    TABLE_PARTITION_ACCOUNT = '__PARTITION_ACCOUNT__'

    def __init__(self, s3_bucket, execution_date, table, accounts):
        self.s3_bucket = s3_bucket
        self.execution_date = execution_date
        self.table = table
        self.accounts = accounts
        self.partition_date = self.execution_date.strftime('%Y-%m-%d')
        self.athena_client = AthenaClient(self.s3_bucket)

    def run(self):
        transfer_methods = {
            'keyword': self.move_keywords_performance_report_to_clean,
            'campaign': self.move_campaigns_performance_report_to_clean,
        }

        transfer_methods[self.table].__call__()

    @logger
    def move_campaigns_performance_report_to_clean(self):
        r_cols = OrderedDict([
            ('valueallconv', str),
            ('searchimprshare', str),
            ('campaignid', str),
            ('gmailsaves', str),
            ('invalidclicks', str),
            ('clickassistedconv', str),
            ('labelids', str),
            ('valueconvcurrentmodel', str),
            ('interactionrate', str),
            ('valueconv', str),
            ('searchabstopis', str),
            ('costconvcurrentmodel', str),
            ('relativectr', str),
            ('videoplayedto100', str),
            ('startdate', str),
            ('avgcpm', str),
            ('searchlostisbudget', str),
            ('_sdc_report_datetime', str),
            ('impressions', str),
            ('avgimprfreqpercookie', str),
            ('contentlostisbudget', str),
            ('activeviewviewablectr', str),
            ('basecampaignid', str),
            ('enhancedcpcenabled', str),
            ('currency', str),
            ('avgposition', str),
            ('campaignstate', str),
            ('advertisingchannel', str),
            ('allconvvalue', str),
            ('clickshare', str),
            ('avgcpv', str),
            ('imprassistedconvlastclickconv', str),
            ('conversionscurrentmodel', str),
            ('mobilebidadj', str),
            ('networkwithsearchpartners', str),
            ('customparameter', str),
            ('budgetperiod', str),
            ('ctr', str),
            ('bidstrategyname', str),
            ('timezone', str),
            ('activeviewviewableimpressions', str),
            ('clicks', str),
            ('newsessions', str),
            ('allconv', str),
            ('bouncerate', str),
            ('invalidclickrate', str),
            ('conversions', str),
            ('desktopbidadj', str),
            ('videoplayedto75', str),
            ('campaigntrialtype', str),
            ('pagessession', str),
            ('viewthroughconv', str),
            ('avgsessiondurationseconds', str),
            ('allconvrate', str),
            ('bidstrategytype', str),
            ('monthofyear', str),
            ('cost', str),
            ('uniquecookies', str),
            ('phoneimpressions', str),
            ('searchexactmatchis', str),
            ('_sdc_table_version', str),
            ('activeviewviewableimprmeasurableimpr', str),
            ('contentlostisrank', str),
            ('network', str),
            ('labels', str),
            ('engagementrate', str),
            ('phonecalls', str),
            ('hasrecommendedbudget', str),
            ('budgetexplicitlyshared', str),
            ('interactiontypes', str),
            ('advertisingsubchannel', str),
            ('campaign', str),
            ('avgcpc', str),
            ('activeviewmeasurableimpr', str),
            ('campaignservingstatus', str),
            ('views', str),
            ('searchlostisrank', str),
            ('week', str),
            ('imprassistedconv', str),
            ('videoplayedto25', str),
            ('account', str),
            ('activeviewmeasurablecost', str),
            ('_sdc_received_at', str),
            ('crossdeviceconv', str),
            ('_sdc_sequence', str),
            ('customerid', str),
            ('targetroasmaximizeconversionvalue', str),
            ('gmailclickstowebsite', str),
            ('interactions', str),
            ('clientname', str),
            ('__sdc_primary_key', str),
            ('budget', str),
            ('activeviewavgcpm', str),
            ('imprassistedconvvalue', str),
            ('totalbudgetamount', str),
            ('recommendedbudgetamount', str),
            ('trackingtemplate', str),
            ('budgetid', str),
            ('avgcpe', str),
            ('finalurlsuffix', str),
            ('avgcost', str),
            ('clickassistedconvlastclickconv', str),
            ('month', str),
            ('tabletbidadj', str),
            ('_sdc_customer_id', str),
            ('costallconv', str),
            ('videoplayedto50', str),
            ('costconv', str),
            ('activeviewmeasurableimprimpr', str),
            ('day', str),
            ('ptr', str),
            ('totalconvvalue', str),
            ('gmailforwards', str),
            ('convvaluecurrentmodel', str),
            ('_sdc_batched_at', str),
            ('enddate', str),
            ('_sdc_extracted_at', str),
            ('convrate', str),
            ('viewrate', str),
            ('campaigngroupid', str),
            ('clickassistedconvvalue', str),
            ('engagements', str),
            ('contentimprshare', str),
            ('bidstrategyid', str),
            ('created_at', str),
            ('acc', str),
            ('created_dt', str)
        ])

        c_cols = OrderedDict([
            ('value_all_conv', str),
            ('search_impr_share', str),
            ('campaign_id', str),
            ('gmail_saves', str),
            ('invalid_clicks', str),
            ('click_assisted_conv', str),
            ('label_ids', str),
            ('value_conv_current_model', str),
            ('interaction_rate', str),
            ('value_conv', str),
            ('search_abs_top_is', str),
            ('cost_conv_current_model', str),
            ('relative_ctr', str),
            ('video_played_to_100', str),
            ('start_date', str),
            ('avg_cpm', str),
            ('search_lost_is_budget', str),
            ('_sdc_report_datetime', str),
            ('impressions', str),
            ('avg_impr_freq_per_cookie', str),
            ('content_lost_is_budget', str),
            ('active_view_viewable_ctr', str),
            ('base_campaign_id', str),
            ('enhanced_cpc_enabled', str),
            ('currency', str),
            ('avg_position', str),
            ('campaign_state', str),
            ('advertising_channel', str),
            ('all_conv_value', str),
            ('click_share', str),
            ('avg_cpv', str),
            ('imprassisted_conv_last_click_conv', str),
            ('conversions_current_model', str),
            ('mobile_bid_adj', str),
            ('network_with_search_partners', str),
            ('custom_parameter', str),
            ('budget_period', str),
            ('ctr', str),
            ('bid_strategy_name', str),
            ('timezone', str),
            ('active_view_viewable_impressions', str),
            ('clicks', str),
            ('new_sessions', str),
            ('all_conv', str),
            ('bounce_rate', str),
            ('invalid_click_rate', str),
            ('conversions', str),
            ('desktop_bid_adj', str),
            ('video_played_to_75', str),
            ('campaign_trial_type', str),
            ('pages_session', str),
            ('view_through_conv', str),
            ('avg_session_duration_seconds', str),
            ('all_conv_rate', str),
            ('bid_strategy_type', str),
            ('month_of_year', str),
            ('cost', str),
            ('unique_cookies', str),
            ('phone_impressions', str),
            ('search_exact_match_is', str),
            ('_sdc_table_version', str),
            ('active_view_viewable_impr_measurable_impr', str),
            ('content_lost_is_rank', str),
            ('network', str),
            ('labels', str),
            ('engagement_rate', str),
            ('phone_calls', str),
            ('has_recommended_budget', str),
            ('budget_explicitly_shared', str),
            ('interaction_types', str),
            ('advertising_sub_channel', str),
            ('campaign', str),
            ('avg_cpc', str),
            ('active_view_measurable_impr', str),
            ('campaign_serving_status', str),
            ('views', str),
            ('search_lost_is_rank', str),
            ('week', str),
            ('impr_assisted_conv', str),
            ('video_played_to_25', str),
            ('account', str),
            ('active_view_measurable_cost', str),
            ('_sdc_received_at', str),
            ('cross_device_conv', str),
            ('_sdc_sequence', str),
            ('customer_id', str),
            ('target_roas_maximize_conversion_value', str),
            ('gmail_clicks_to_website', str),
            ('interactions', str),
            ('client_name', str),
            ('__sdc_primary_key', str),
            ('budget', str),
            ('active_view_avg_cpm', str),
            ('impr_assisted_con_vvalue', str),
            ('total_budget_amount', str),
            ('recommended_budget_amount', str),
            ('tracking_template', str),
            ('budget_id', str),
            ('avg_cpe', str),
            ('final_url_suffix', str),
            ('avg_cost', str),
            ('click_assisted_conv_last_click_conv', str),
            ('month', str),
            ('tablet_bid_adj', str),
            ('_sdc_customer_id', str),
            ('cost_all_conv', str),
            ('video_played_to_50', str),
            ('cost_conv', str),
            ('active_view_measurable_impr_impr', str),
            ('day', str),
            ('ptr', str),
            ('total_conv_value', str),
            ('gmail_forwards', str),
            ('conv_value_current_model', str),
            ('_sdc_batched_at', str),
            ('end_date', str),
            ('_sdc_extracted_at', str),
            ('conv_rate', str),
            ('view_rate', str),
            ('campaign_group_id', str),
            ('click_assisted_conv_value', str),
            ('engagements', str),
            ('content_impr_share', str),
            ('bid_strategy_id', str)
        ])

        self.__move_to_clean(
            query_path=GoogleAdsClean.QUERY_PATH,
            table_name='marketing_googleads_campaigns',
            sql_file_name='keyword.sql',
            r_cols=r_cols,
            c_cols=c_cols
        )

    @logger
    def move_keywords_performance_report_to_clean(self):
        r_cols = OrderedDict([
            ('valueallconv', str),
            ('searchimprshare', str),
            ('mobilefinalurl', str),
            ('campaignid', str),
            ('gmailsaves', str),
            ('adrelevance', str),
            ('clickassistedconv', str),
            ('labelids', str),
            ('valueconvcurrentmodel', str),
            ('interactionrate', str),
            ('valueconv', str),
            ('costconvcurrentmodel', str),
            ('videoplayedto100', str),
            ('dayofweek', str),
            ('adgroupid', str),
            ('isnegative', str),
            ('avgcpm', str),
            ('_sdc_report_datetime', str),
            ('impressions', str),
            ('keywordstate', str),
            ('activeviewviewablectr', str),
            ('basecampaignid', str),
            ('enhancedcpcenabled', str),
            ('currency', str),
            ('avgposition', str),
            ('campaignstate', str),
            ('allconvvalue', str),
            ('avgcpv', str),
            ('imprassistedconvlastclickconv', str),
            ('appfinalurl', str),
            ('adgroupstate', str),
            ('conversionscurrentmodel', str),
            ('customparameter', str),
            ('maxcpm', str),
            ('ctr', str),
            ('estaddclickswkfirstpositionbid', str),
            ('bidstrategyname', str),
            ('timezone', str),
            ('activeviewviewableimpressions', str),
            ('clicks', str),
            ('newsessions', str),
            ('allconv', str),
            ('maxcpc', str),
            ('bouncerate', str),
            ('conversions', str),
            ('verticalid', str),
            ('videoplayedto75', str),
            ('adrelevancehist', str),
            ('landingpageexperience', str),
            ('pagessession', str),
            ('viewthroughconv', str),
            ('avgsessiondurationseconds', str),
            ('allconvrate', str),
            ('expectedclickthroughrate', str),
            ('bidstrategytype', str),
            ('monthofyear', str),
            ('cost', str),
            ('matchtype', str),
            ('searchexactmatchis', str),
            ('_sdc_table_version', str),
            ('activeviewviewableimprmeasurableimpr', str),
            ('firstpositioncpc', str),
            ('labels', str),
            ('estaddcostwkfirstpositionbid', str),
            ('engagementrate', str),
            ('criterionservingstatus', str),
            ('interactiontypes', str),
            ('campaign', str),
            ('avgcpc', str),
            ('activeviewmeasurableimpr', str),
            ('keywordid', str),
            ('destinationurl', str),
            ('views', str),
            ('searchlostisrank', str),
            ('keyword', str),
            ('week', str),
            ('imprassistedconv', str),
            ('baseadgroupid', str),
            ('hasqualityscore', str),
            ('videoplayedto25', str),
            ('account', str),
            ('activeviewmeasurablecost', str),
            ('_sdc_received_at', str),
            ('crossdeviceconv', str),
            ('_sdc_sequence', str),
            ('customerid', str),
            ('quarter', str),
            ('gmailclickstowebsite', str),
            ('interactions', str),
            ('topofpagecpc', str),
            ('clientname', str),
            ('year', str),
            ('landingpageexperiencehist', str),
            ('__sdc_primary_key', str),
            ('activeviewavgcpm', str),
            ('maxcpcsource', str),
            ('imprassistedconvvalue', str),
            ('trackingtemplate', str),
            ('biddingstrategysource', str),
            ('avgcpe', str),
            ('finalurlsuffix', str),
            ('qualscorehist', str),
            ('avgcost', str),
            ('clickassistedconvlastclickconv', str),
            ('month', str),
            ('expectedclickthroughratehist', str),
            ('_sdc_customer_id', str),
            ('costallconv', str),
            ('videoplayedto50', str),
            ('qualityscore', str),
            ('costconv', str),
            ('activeviewmeasurableimprimpr', str),
            ('day', str),
            ('firstpagecpc', str),
            ('totalconvvalue', str),
            ('gmailforwards', str),
            ('convvaluecurrentmodel', str),
            ('_sdc_batched_at', str),
            ('finalurl', str),
            ('adgroup', str),
            ('_sdc_extracted_at', str),
            ('convrate', str),
            ('viewrate', str),
            ('approvalstatus', str),
            ('clickassistedconvvalue', str),
            ('engagements', str),
            ('bidstrategyid', str),
            ('created_at', str),
            ('acc', str),
            ('created_dt', str)
        ])

        c_cols = OrderedDict([
            ('value_all_conv', str),
            ('search_impr_share', str),
            ('mobile_final_url', str),
            ('campaign_id', str),
            ('gmail_saves', str),
            ('ad_relevance', str),
            ('click_assistedconv', str),
            ('label_ids', str),
            ('value_conv_current_model', str),
            ('interaction_rate', str),
            ('value_conv', str),
            ('cost_conv_current_model', str),
            ('video_played_to_100', str),
            ('day_of_week', str),
            ('adgroup_id', str),
            ('is_negative', str),
            ('avg_cpm', str),
            ('_sdc_report_datetime', str),
            ('impressions', str),
            ('keyword_state', str),
            ('active_view_viewable_ctr', str),
            ('base_campaign_id', str),
            ('enhanced_cpc_enabled', str),
            ('currency', str),
            ('avg_position', str),
            ('campaign_state', str),
            ('all_conv_value', str),
            ('avg_cpv', str),
            ('imprassisted_conv_last_click_conv', str),
            ('app_final_url', str),
            ('ad_group_state', str),
            ('conversions_current_model', str),
            ('custom_parameter', str),
            ('max_cpm', str),
            ('ctr', str),
            ('est_add_clicks_wk_first_position_bid', str),
            ('bid_strategy_name', str),
            ('timezone', str),
            ('active_view_viewable_impressions', str),
            ('clicks', str),
            ('new_sessions', str),
            ('all_conv', str),
            ('max_cpc', str),
            ('bounce_rate', str),
            ('conversions', str),
            ('vertical_id', str),
            ('video_played_to_75', str),
            ('ad_relevance_hist', str),
            ('landing_page_experience', str),
            ('page_ssession', str),
            ('view_through_conv', str),
            ('avg_session_duration_seconds', str),
            ('all_conv_rate', str),
            ('expected_click_through_rate', str),
            ('bid_strategy_type', str),
            ('month_of_year', str),
            ('cost', str),
            ('match_type', str),
            ('searchexactmatchis', str),
            ('_sdc_table_version', str),
            ('active_view_viewable_impr_measurable_impr', str),
            ('first_position_cpc', str),
            ('labels', str),
            ('est_add_cost_wk_first_position_bid', str),
            ('engagement_rate', str),
            ('criterion_serving_status', str),
            ('interaction_types', str),
            ('campaign', str),
            ('avg_cpc', str),
            ('active_view_measurable_impr', str),
            ('keyword_id', str),
            ('destination_url', str),
            ('views', str),
            ('search_lost_is_rank', str),
            ('keyword', str),
            ('week', str),
            ('imprassisted_conv', str),
            ('base_adgroup_id', str),
            ('has_quality_score', str),
            ('video_played_to_25', str),
            ('account', str),
            ('active_view_measurable_cost', str),
            ('_sdc_received_at', str),
            ('cross_device_conv', str),
            ('_sdc_sequence', str),
            ('customer_id', str),
            ('quarter', str),
            ('gmail_clicks_to_website', str),
            ('interactions', str),
            ('top_of_page_cpc', str),
            ('client_name', str),
            ('year', str),
            ('landing_page_experience_hist', str),
            ('__sdc_primary_key', str),
            ('active_view_avg_cpm', str),
            ('max_cpc_source', str),
            ('impr_assisted_conv_value', str),
            ('tracking_template', str),
            ('bid_ding_strategy_source', str),
            ('avg_cpe', str),
            ('final_url_suffix', str),
            ('qualscorehist', str),
            ('avg_cost', str),
            ('click_assisted_conv_last_click_conv', str),
            ('month', str),
            ('expected_click_through_rate_hist', str),
            ('_sdc_customer_id', str),
            ('cost_all_conv', str),
            ('video_played_to_50', str),
            ('quality_score', str),
            ('cost_conv', str),
            ('active_view_measurable_impr_impr', str),
            ('day', str),
            ('first_page_cpc', str),
            ('total_conv_value', str),
            ('gmail_forwards', str),
            ('conv_value_current_model', str),
            ('_sdc_batched_at', str),
            ('final_url', str),
            ('adgroup', str),
            ('_sdc_extracted_at', str),
            ('conv_rate', str),
            ('view_rate', str),
            ('approval_status', str),
            ('click_assisted_conv_value', str),
            ('engagements', str),
            ('bid_strategy_id', str),
            ('created_at', str),
            ('acc', str),
            ('created_dt', str)
        ])

        self.__move_to_clean(
            query_path=GoogleAdsClean.QUERY_PATH,
            table_name='marketing_googleads_keywords',
            sql_file_name='keyword.sql',
            r_cols=r_cols,
            c_cols=c_cols
        )

    @logger(exclude=['r_cols', 'c_cols'])
    def __move_to_clean(self, table_name, sql_file_name, r_cols, c_cols, query_path):
        for account in self.accounts:
            key = 'clean/marketing/google_ads/{table_name}/acc={acc_partition}/' \
                  'created_dt={date_partition}/{file_name}.parquet' \
                .format(
                    table_name=table_name,
                    acc_partition=account,
                    date_partition=self.partition_date,
                    file_name=int(time.mktime(datetime.now().timetuple())) * 1000
                )

            query = BaseETL.get_query_from_file_name(
                '{query_base_dir}/{query_path}/{file_name}'.format(
                    query_base_dir=DATALAKE_QUERIES_DIR,
                    query_path=query_path,
                    file_name=sql_file_name))

            self.athena_client.create_parquet_from_query(
                key=key,
                query=query.format(date=self.execution_date.strftime("%Y-%m-%d"),
                                   account=account),
                raw_columns=r_cols,
                clean_columns=c_cols
            )
