class SlackWebhooksEnum:
    """
    Mapping of webhooks on Slack.
    """

    DATA_ALERTS = "SLACK_DATA_ALERTS_WEBHOOK"
    ALERTS_DE_AIRFLW_DGS = "SLACK_ALERTS_AIRFLOW_WEBHOOK"
    ALERTS_AIRFLOW_DE_DAGS_INMETRO = "AIRFLOW_ALERTS_INMETRO_SLACK_WEBHOOK"
    DE_TESTS = "SLACK_DE_TESTS_WEBHOOK"
