SELECT
    APAHID AS id_negotiation,
    CASE
        WHEN APFLAG = "S" THEN "Programado"
        WHEN APFLAG = "C" THEN "Concluído"
        WHEN APFLAG = "R" THEN "Quebrado"
        ELSE APFLAG
    END AS payment_flag,
    CASE
        WHEN APFLAG2 = "S" THEN "Programado"
        WHEN APFLAG2 = "C" THEN "Concluído"
        WHEN APFLAG2 = "R" THEN "Quebrado"
    END AS revalued_payment_flag,
    APDETID AS payment_sequence_number,
    APAMT AS amount_to_pay,
    APAMTPAY AS payment_amount,
    APINTAMT AS fees_amount,
    APAMZAMT AS amortization_amount,
    APBLNC AS final_balance,
    APINTTAXAMT AS interest_tax_amount,
    APNUMBLT,
    APIACORDO,
    APMIGRACAO,
    APNUMDOC,
    APITEMDOCNAT,
    APMONTMI,
    APDLQDT,
    APTPDOC,
    APCOMPANY,
    APPROMESSA,
    APEVENTO,
    APCHAVELEG,
    APANO,
    APCLASSERZE,
    APCODRZE,
    APATRIBUIC,
    APDTDOC,
    APDTLCTO,
    APDTENTRADA,
    APMOEDA,
    APREF,
    APDEBCRED,
    APMONTMD,
    APCODPAG,
    APCONDDIAS,
    APMEIOPAG,
    APBLOQ,
    APEMPNATURA,
    APPONTOS,
    APBLOQADV,
    APCHAVEADV,
    APNIVELADV,
    APAREAADV,
    APBANCO,
    APNOSSONUM,
    APCODGERMER,
    APCODREGEST,
    APCODGERVEN,
    APSETOR,
    APCODGRP,
    APNUMCICLO,
    APANOCICLO,
    APNUMPEDCLI,
    APLINHADIG,
    APPMTDATE,
    APPMTDDESC,
    APPMTAMT,
    APPMTSALDO,
    APPMTDOCEST,
    APPMTDTEST,
    APSTATUSVEN,
    APFLGBAIXA,
    APPMTCODE,
    BLMANDT,
    APANODOCNAT,
    APITEM,
    APDOCNATURA,
    APDOCACORDO,
    APIANODOCNAT,
    APIANO,
    APTPNEGOCIAC,
    APSSNUM,
    TPNEGOCIAC,
    APHONO,
    APINDATE AS ts_start_payment_term,
    APDUEDT AS ts_payment_deadline
FROM datalake_cyber_raw.agpmtdet
