SELECT
    CAID AS id_campaign,
    CANUMOFERTA AS offer_number,
    CAGRUPO AS billing_group,
    CASSNUM AS id_client,
    CACPFCGC AS cpf_cnpj,
    CADTPROC AS ts_boletagem_sent,
    CADTVAL AS ts_due_boletagem,
    CADTVCENTR AS ts_due_down_payment,
    CAQTDOFER AS total_ofers,
    CATYPE AS agreement_type,
    CARATE AS annual_interest_rate,
    CAPYTYPE AS interest_quota_type,
    CATOTPMT AS total_negotiated_with_fees,
    CATOTPMTSH AS total_negotiated_without_fees,
    CAHONO AS fees_amount,
    CAFREQ AS frequency,
    CAORIGEM AS origin,
    CAACCTCOB AS billing_account,
    CAAHID AS id_negotiation,
    CAQUE AS campaign_queue,
    CANOSSONUM AS our_number,
    CAPERENTR AS down_payment_percentage,
    CAAGENCY AS agency,
    CAVLRENTR AS down_payment_amount,
    CARATE2 AS grace_period_interest_rate,
    CAGRDAYS AS grace_period_days,
    CAAGING AS contract_delay_days,
    CATIPOBOL,
    CASTATUSCA,
    CATOTPARC,
    CAQTDPA
FROM datalake_cyber_raw.tb_campanha
