SELECT
    NR_CONTRATO AS id_contract,
    NR_CONTRATO_ORIGEM AS id_origin_contract,
    IN_ESTORNO AS id_contract_refund,
    ID_CLIENTE AS id_client,
    ID_PMTCODE AS id_transaction,
    IN_RENEGOCIACAO AS id_renegotiation,
    CD_USUARIO_FECHADO AS id_user_closed_batch,
    NR_GRUPO AS group_number,
    NR_CPFCNPJ AS cpf_cnpj,
    CD_MATRIZ AS company_headquarters_code,
    CD_REGIONAL AS regional_code,
    CD_FILIAL AS branch_code,
    CD_STATUS AS status_code,
    CD_TIPO_COBRANCA AS collection_type_code,
    ID_PMCOLLID AS manager,
    ID_PMQUE AS queue_transaction_recorded,
    ID_PMBATCH AS batch_number,
    ID_PMTAMT AS stack,
    ID_PMAGENCY AS agency,
    ID_PMTYPE AS error_code,
    ID_PMTDCOLM AS affected_column,
    ID_PMAMOUNT AS consecutive_check_number,
    ID_PMPRVVAL AS previous_column_value,
    ID_PMCURVAL AS field_value_after_calculation,
    ID_PMTDDESC AS transaction_description,
    ID_PMTDFLAG AS transaction_flag,
    ID_PMTDPCNT AS transaction_percentage,
    ID_PMTDSEQ AS transaction_sequence,
    NR_ATRASO_PARCELA AS installment_delay_number,
    NR_ATRASO_DTMOVTO AS movement_delay_number,
    NR_ATRASO_DISTRIB AS distributed_delay_number,
    NR_ATRASO_PAGAMENTO AS late_payment_number,
    NR_ATRASO_BASECAL AS calculation_base_delay_number,
    CD_TIPO_ATRASO AS delay_type_code,
    CD_ASSESSORIA_REMUNERADA AS paid_advisory_code,
    CD_ASSESSORIA_DETENTORA AS holding_advisory_code,
    CD_CRITERIO_REMUNERACAO AS remuneration_criteria_code,
    PE_REMUNERACAO AS remuneration_percentage,
    VL_REMUNERACAO AS remuneration_amount,
    PE_PART_ORIGEM AS percentage_participation_origin_contract,
    IN_FECHADO AS is_commission_closed,
    IN_GLOSA,
    DT_GLOSA,
    DS_MOTIVO_GLOSA,
    DT_IN_PARCIAL,
    IN_PARCIAL,
    PE_REMUN_SHARE,
    FLAG_ASS_DIGITAL,
    DT_MOVIMENTO AS ts_payment_sent,
    DT_PROCESSAMENTO AS ts_processing,
    ID_PMREFDT AS ts_transaction_referred,
    ID_PMTDATE AS ts_payment,
    ID_PMEDATE AS ts_payment_registration,
    DT_ASSESSORIA_REMUNERADA AS ts_paid_avisory,
    DT_ASSESSORIA_DETENTORA AS ts_holding_advisory,
    DT_IN_FECHADO AS ts_commission_closed,
    DT_PESQUISA AS ts_search,
    DT_INICIO_VIGENCIA As ts_start_validity,
    DT_FIM_VIGENCIA AS ts_end_validity
FROM datalake_cyber_raw.tb_comissoes
