SELECT
    U1ACCT AS id_contract,
    CASE
        WHEN U1ACCTG = "1" THEN "QuintoAndar"
        WHEN U1ACCTG = "2" THEN "QuintoCred"
        ELSE U1ACCTG
    END AS contract_group,
    CASE
        WHEN U1MOTBAIXA = "01" THEN "Pagamento"
        WHEN U1MOTBAIXA = "02" THEN "Outros"
        ELSE U1MOTBAIXA
    END AS reason_written_down,
    U1SSNUM AS id_client,
    U1CODCONT AS id_contract_external,
    U1CODIMO AS id_contract_property,
    U1IDFMAN AS id_oldest_negative_invoice
    U1SUBSET,
    U1FASECOB,
    U1DTRETOR,
    U1FLACNEGSPC,
    U1DTACNEGSPC,
    U1FLACINBSPC,
    U1DTINBACSPC,
    U1REAAVASPC,
    U1DTREAAVSPC,
    U1NEGAVASPC,
    U1DTNEGAVSPC,
    U1FLACNEGSER,
    U1DTACNEGSER,
    U1FLACINBSER,
    U1DTINBACSER,
    U1REAAVASER,
    U1NEGAVASER,
    U1DTREAAVSER,
    U1DTNEGAVSER,
    U1FLACNEGBVS,
    U1DTACNEGBVS,
    U1FLACINBBVS,
    U1DTINBACBVS,
    U1REAAVABVS,
    U1DTREAAVBVS,
    U1NEGAVABVS,
    U1DTNEGAVBVS,
    U1FLACNEGCDL,
    U1DTACNEGCDL,
    U1FLACINBCDL,
    U1DTINBACCDL,
    U1REAAVACDL,
    U1DTREAAVCDL,
    U1NEGAVACDL,
    U1DTNEGAVCDL,
    U1FLACNEGINT,
    U1DTACNEGINT,
    U1REAAVAINT,
    U1NEGAVAINT,
    U1FLACNEGCYB,
    U1DTACNEGCYB,
    U1FLACREAB,
    U1DTACREAB,
    U1FLATISEMAC,
    U1FLACAVAL,
    U1CPFCNPJ,
    U1RG AS rg,
    U1DTEMRG AS dt_rg_issuance,
    U1ORGEMRG AS rg_issuing_body,
    U1UFRG AS rg_state,
    U1DTNASC AS dt_birth,
    U1CIDNASC AS city_birth,
    U1UFNASC AS state_birth,
    U1NACIONALID AS nationality,
    U1SEXO AS gender,
    U1NOMMAE AS mother_name,
    U1NOMPAI AS father_name,
    U1ESTCIV AS marital_status,
    U1NMCONJ AS partner_name,
    U1ENDRESNUM AS residential_address_number,
    U1ENDRESPA AS residential_address_country,
    U1DDITELRES AS ddi_phone,
    U1DDITELCEL AS cellphone,
    U1EMAIL AS email,
    U1ENDCOMNUM,
    U1DDITELCOM AS business_phone_ddi,
    U1DDITELCCO AS business_cellphone_ddi,
    U1BCPHONE AS business_cellphone,
    U1DTINIVIG AS ts_contract_start,
    U1SCOCONT AS contract_score,
    U1VLRALUG AS contract_rental_amount,
    U1VLRCOND AS contract_condominium_amount,
    U1VLRIPTU AS contract_iptu_amount,
    U1VERCONT AS contract_version,
    U1GARANT AS contract_guarantee,
    U1DTGAR AS ts_start_guarantee,
    U1STATCONT AS contract_status,
    U1DTRESC AS ts_contract_end,
    U1SITEVIC AS eviction_step,
    U1DTDIEV AS ts_distribution_eviction,
    U1DTPRRES AS ts_expected_contract_end,
    U1ESCEVI AS eviction_law_firm,
    U1PERDIV AS percentage_debt_to_rent,
    U1MOTCOB AS reason_eviction,
    U1VLRFMAN AS oldest_negative_invoice_amount,
    U1VEFMAN AS dt_due_oldest_negative_invoice,
    U1NOMIMO AS real_state_agency,
    CASE
        WHEN U1FLGPAUSA = "S" THEN "Pausar cobrança"
        ELSE U1FLGPAUSA
    END AS flag_pause_collection,
    U1CT1 AS real_estate_agency_email,
    U1CT2,
    U1CT3,
    U1CT4,
    U1CT5,
    U1CN1,
    U1CN2,
    U1CN3,
    U1CN4,
    U1CN5,
    U1CD1,
    U1CD2,
    U1CD3,
    U1CD4,
    U1CD5,
    U1CT6,
    U1CT7,
    U1CT8,
    U1CT9,
    U1CT10,
    U1CI1,
    U1CI2,
    U1CI3,
    U1CI4,
    U1CI5,
    U1CI6,
    U1CI7,
    U1CI8,
    U1CI9,
    U1CI10,
    U1UUIDCLIE AS uuid_client_legacy,
    U1INDMOTPA,
    U1CDRETRSER,
    U1DTRETRSER,
    U1CDRETNSER,
    U1DTRETNSER,
    U1IDPARCNEG,
    U1ENDCOMPAI AS business_address_country,
    U1DTSOLBOL,
    U1TIPOBOL,
    U1TPPES,
    U1VLRPRMUAGR,
    U1VLRPRJUAG,
    U1VLVENC,
    U1NOCAMPANHA,
    U1VLCAMPANHA,
    U1VLCUSTASAG,
    U1DTMANFIN,
    U1DTMANCAD,
    U1CI11,
    U1CI13,
    U1CI14,
    U1CI15,
    U1CI16,
    U1CI17,
    U1CI18,
    U1CI19,
    U1CI29,
    U1CI20,
    U1CI21,
    U1CI22,
    U1CI23,
    U1CI24,
    U1CI25,
    U1CI26,
    U1CI27,
    U1CI28,
    U1CI30,
    U1CI12,
    U2DIASEVIC,
    U1DIASEMANA,
    U1DIASEVIC,
    U1QTDFAVENC,
    U1TPCOB,
    U1DAYS,
    U1CLASSCTR,
    U1OCOREVIC,
    U1CD6,
    U1CD7,
    U1CD8,
    U1CD9,
    U1CD10,
    U1CN6,
    U1CN7,
    U1CN8,
    U1CN9,
    U1CN10,
    U1INDCOR1,
    U1INDCOR2,
    U1INDCOR3,
    U1INDCOR4,
    U1INDCOR5,
    U1INDCOR6,
    U1INDCOR7,
    U1INDCOR8,
    U1INDCOR9,
    U1INDCOR10,
    U1INDCOR11,
    U1INDCOR12,
    U1INDCOR13,
    U1INDCOR14,
    U1INDCOR15,
    U1INDCOR16,
    U1INDCOR17,
    U1INDCOR18,
    U1INDCOR19,
    U1INDCOR20,
    U1INDCOR21,
    U1INDCOR22,
    U1INDCOR23,
    U1INDCOR24,
    U1INDCOR25,
    U1INDCOR26,
    U1INDCOR27,
    U1INDCOR28,
    U1INDCOR29,
    U1INDCOR30,
FROM datalake_cyber_raw.uda1
