SELECT
    U1ACCT AS id_contract,
    U1SSNUM AS id_client,
    U1CODCONT AS id_contract_external,
    U1CODIMO AS id_contract_property,
    U1IDFMAN AS id_oldest_negative_invoice,
    U1IDPARCNEG AS id_last_negative_installment,
    U1UUIDCLIE AS id_client_legacy,
    CASE
        WHEN U1ACCTG = "1" THEN "QuintoAndar"
        WHEN U1ACCTG = "2" THEN "QuintoCred"
        ELSE U1ACCTG
    END AS contract_group,
    CASE
        WHEN U1MOTBAIXA = "01" THEN "Pagamento"
        WHEN U1MOTBAIXA = "02" THEN "Outros"
        ELSE U1MOTBAIXA
    END AS reason_written_down,
    U1CPFCNPJ AS cpf_cnpj,
    U1RG AS rg,
    U1VLCAMPANHA AS agency_campaign,
    U1NOCAMPANHA AS campaign_indicator,
    IF(U1TIPOBOL = 'E', TRUE, FALSE) AS is_boletagem,
    U1CLASSCTR AS collection_classification,
    U1FASECOB AS collection_phase,
    IF(U1FLGPAUSA = "S",TRUE,FALSE) AS has_paused_collection,
    U1INDMOTPA AS reason_pause,
    U1SUBSET AS subset,
    IF(U1FLACNEGSPC = 1, TRUE, FALSE) AS has_spc_credit_denial,
    IF(U1FLACINBSPC = 1, TRUE, FALSE) AS has_inhibition_negative_spc,
    IF(U1REAAVASPC = 1, TRUE, FALSE) AS has_guarantor_rehabilitation_spc,
    IF(U1NEGAVASPC = 1, TRUE, FALSE) AS has_guarantor_negative_spc,
    IF(U1FLACNEGSER = 1, TRUE, FALSE) AS has_serasa_credit_denial,
    IF(U1FLACINBSER = 1, TRUE, FALSE) AS has_inhibition_negative_serasa,
    IF(U1REAAVASER = 1, TRUE, FALSE) AS has_guarantor_rehabilitation_serasa,
    IF(U1NEGAVASER = 1, TRUE, FALSE) AS has_guarantor_negative_serasa,
    IF(U1FLACNEGBVS = 1, TRUE, FALSE) AS has_bvs_credit_denial,
    IF(U1FLACINBBVS = 1, TRUE, FALSE) AS has_inhibition_negative_bvs,
    IF(U1REAAVABVS = 1, TRUE, FALSE) AS has_guarantor_rehabilitation_bvs,
    IF(U1NEGAVABVS = 1, TRUE, FALSE) AS has_guarantor_negative_bvs,
    IF(U1FLACINBCDL = 1, TRUE, FALSE) AS has_inhibition_negative_cdl,
    IF(U1FLACNEGCDL = 1, TRUE, FALSE) AS has_cdl_credit_denial,
    IF(U1REAAVACDL = 1, TRUE, FALSE) AS has_guarantor_rehabilitation_cdl,
    IF(U1NEGAVACDL = 1, TRUE, FALSE) AS has_guarantor_negative_cdl,
    IF(U1FLACNEGINT = 1, TRUE, FALSE) AS has_internal_credit_denial,
    IF(U1REAAVAINT = 1, TRUE, FALSE) AS has_guarantor_rehabilitation_internal,
    IF(U1NEGAVAINT = 1, TRUE, FALSE) AS has_guarantor_negative_internal,
    U1FLACNEGCYB AS has_negative_cyb,
    IF(U1FLACREAB = 1, TRUE, FALSE) AS has_rehabilitation_all_credit_bureaus,
    U1FLATISEMAC AS has_none_negative_bureau,
    U1ORGEMRG AS rg_issuing_body,
    U1UFRG AS rg_state,
    U1DTNASC AS ts_birth,
    U1CIDNASC AS city_birth,
    U1UFNASC AS state_birth,
    U1NACIONALID AS nationality,
    U1SEXO AS gender,
    U1NOMMAE AS mother_name,
    U1NOMPAI AS father_name,
    U1ESTCIV AS marital_status,
    U1NMCONJ AS partner_name,
    U1ENDRESNUM AS residential_address_number,
    U1ENDRESPA AS residential_address_country,
    U1DDITELRES AS ddi_phone,
    U1DDITELCEL AS cellphone,
    U1EMAIL AS email,
    U1ENDCOMNUM AS commercial_address_number,
    U1DDITELCOM AS business_phone_ddi,
    U1DDITELCCO AS business_cellphone_ddi,
    U1BCPHONE AS business_cellphone,
    U1SCOCONT AS contract_score,
    U1VLRALUG AS contract_rental_amount,
    U1VLRCOND AS contract_condominium_amount,
    U1VLRIPTU AS contract_iptu_amount,
    U1VERCONT AS contract_version,
    U1GARANT AS contract_guarantee,
    U1STATCONT AS contract_status,
    U1SITEVIC AS eviction_step,
    U1ESCEVI AS eviction_law_firm,
    U1PERDIV AS percentage_debt_to_rent,
    U1MOTCOB AS reason_eviction,
    U1VLRFMAN AS oldest_negative_invoice_amount,
    U1NOMIMO AS real_state_agency,
    U1DAYS AS delay_contamined_days,
    U1CT1 AS real_estate_agency_email,
    U1CDRETRSER AS bureau_latest_rehabilitation_rejection,
    U1CDRETNSER AS latest_bureau_denial_rejection,
    U1ENDCOMPAI AS business_address_country,
    U1TPPES AS person_type,
    U1VLRPRMUAGR AS residual_fine_amount,
    U1VLRPRJUAG AS residual_interest_amount,
    U1VLVENC AS debt_balance,
    U1VLCUSTASAG AS cost_amount,
    U1DIASEMANA AS week_day,
    U1QTDFAVENC AS open_invoices,
    U1TPCOB AS collection_flow,
    IF(U1OCOREVIC = 'S', TRUE, FALSE) AS has_restrictive_evic_occurrence,
    U1FLACAVAL AS has_guarantor_denial,
    U1DIASEVIC AS days_until_contract_updated_evic_queue,
    U1DTSOLBOL AS ts_boletagem_request,
    U1VEFMAN AS ts_due_oldest_negative_invoice,
    U1DTGAR AS ts_start_guarantee,
    U1DTINIVIG AS ts_contract_start,
    U1DTRESC AS ts_contract_end,
    U1DTDIEV AS ts_distribution_eviction,
    U1DTPRRES AS ts_expected_contract_end,
    U1DTRETOR AS ts_return,
    U1DTEMRG AS ts_rg_issuance,
    U1DTRETNSER AS ts_bureau_denial_rejection,
    U1DTRETRSER AS ts_last_rehabilitation_rejection,
    U1DTACNEGSPC AS ts_negative_spc,
    U1DTINBACSPC AS ts_inhibition_negative_spc,
    U1DTREAAVSPC AS ts_guarantor_reactivation_spc,
    U1DTNEGAVSPC AS ts_guarantor_negative_spc,
    U1DTACNEGSER AS ts_negative_serasa,
    U1DTINBACSER AS ts_inhibition_negative_serasa,
    U1DTREAAVSER AS ts_guarantor_reactivation_serasa,
    U1DTNEGAVSER AS ts_guarantor_negative_serasa,
    U1DTACNEGBVS AS ts_negative_bvs,
    U1DTINBACBVS AS ts_inhibition_negative_bvs,
    U1DTREAAVBVS AS ts_guarantor_reactivation_bvs,
    U1DTNEGAVBVS AS ts_guarantor_negative_bvs,
    U1DTACNEGCDL AS ts_negative_cdl,
    U1DTINBACCDL AS ts_inhibition_negative_cdl,
    U1DTREAAVCDL AS ts_guarantor_reactivation_cdl,
    U1DTNEGAVCDL AS ts_guarantor_negative_cdl,
    U1DTACNEGINT AS ts_negative_internal,
    U1DTACNEGCYB AS ts_negative_cyb,
    U1DTACREAB AS ts_rehabilitation_all_credit_bureaus,
    NOW() AS ts_load
FROM datalake_cyber_raw.uda1
