SELECT
    PAACCT AS id_contract,
    PAIDPARC AS id_invoice,
    PAIDBOL AS id_boleto_legacy,
    PABICODIGO AS id_bill_item,
    PAACCTG AS contract_group,
    CASE
        WHEN PASTATUS = 1 THEN "Ativa (em aberto)"
        WHEN PASTATUS = 2 THEN "Paga"
        WHEN PASTATUS = 3 THEN "Cancelada"
        WHEN PASTATUS = 4 THEN "Pausa"
        WHEN PASTATUS = 5 THEN "Previamente negociada"
        WHEN PASTATUS = 6 THEN "Em negociação"
        ELSE PASTATUS
    END AS invoice_status,
    PAVLPRINC AS invoice_main_amount,
    PAVLJUR AS invoice_interest_amount,
    PAVLMUL AS invoice_fine_amount,
    PADTVENC AS dt_due_invoice,
    PACUSTAS AS cost_withdrawal_quintocred,
    PAHONORARIOS AS fee_quintocred_eviction,
    PASTATFA AS invoice_status_legacy,
    PATPDIV AS invoice_purpose,
    PADTVENORI AS ts_due_original_debt,
    PADTCRIPA AS ts_invoice_creation,
    PATPCONTA AS account_type,
    PADTENVFA AS ts_sending_debt,
    PAAMENVFA AS invoice_accrual_year_month,
    PANOSSNUM AS our_number_original_invoice,
    PAINDNEG AS is_negative_bureaus,
    PAINDPRIFA AS is_tenant_first_invoice,
    PAPREVNEG AS has_previously_negotiated,
    PAINDMOTPA AS pause_reason,
    PADTLIMPA AS ts_limit_pause,
    PACODBANBOL AS code_bank_boleto,
    PADIGBANBOL AS digit_bank_boleto,
    PANOMBANBOL AS name_bank_boleto,
    PALINDIG1 AS digitable_line_boleto_1,
    PALINDIG2 AS digitable_line_boleto_2,
    PALINDIG3 AS digitable_line_boleto_3,
    PALINDIG4 AS digitable_line_boleto_4,
    PALINDIG5 AS digitable_line_boleto_5,
    PALINDIG6 AS digitable_line_boleto_6,
    PALINDIG7 AS digitable_line_boleto_7,
    PALINDIG8 AS digitable_line_boleto_8,
    PALOCPAGBOL AS payment_location_boleto,
    PADTVENCBOL AS ts_due_boleto,
    PATPPECEBOL,
    PATPDOPCBOL,
    PADOCPECEBOL,
    PANOCEBOL,
    PACODAGBOL AS code_digit_agency_boleto,
    PADTDOCBOL AS ts_document_boleto,
    PANUMDOBOL AS document_number_boleto,
    PANOSNUMBOL AS our_number_boleto,
    PAVLRBOL,
    PAVLDESCBOL,
    PAVLDEDUBOL,
    PAVLRMOMUBOL,
    PAVLACRBOL,
    PAVLRTOBOL,
    PATPPESABOL,
    PATPDPSABOL,
    PADOPESABOL,
    PANOSABOL,
    PASEREARBOL,
    PALININSTBOL1 AS instruction_line_boleto_1,
    PALININSTBOL2 AS instruction_line_boleto_2,
    PALININSTBOL3 AS instruction_line_boleto_3,
    PALININSTBOL4 AS instruction_line_boleto_4,
    PALININSTBOL5 AS instruction_line_boleto_5,
    PALININSTBOL6 AS instruction_line_boleto_6,
    PALININSTBOL7 AS instruction_line_boleto_7,
    PALININSTBOL8 AS instruction_line_boleto_8,
    PASEQREARBOL,
    PAVLRORI AS original_amount,
    PADTINSERT,
    PADTUPDATE,
    PABITITULO AS bill_item_title,
    PABIDESC AS bill_item_description,
    PABIVALOR AS bill_item_amount,
    PABIDTVENC AS ts_due_bill_item,
    PATIPO,
    PABIDTINSERT,
    PABIDTUPDATE,
    PABIDTEXCLUSAO,
    PABIFLGEXCLLOG
FROM datalake_cyber_raw.tb_parcela
