SELECT
    HD_ACCT AS id_contract,
    HD_SSNUM AS id_client,
    HD_ACCTG AS contract_group,
    CASE
        WHEN HD_ACCTG = "1" THEN "QuintoAndar"
        WHEN HD_ACCTG = "2" THEN "QuintoCred"
        ELSE HD_ACCTG
    END AS creditor,
    HD_CPFCNPJ AS cpf_cnpj_client,
    HD_MATRIZ AS head_office,
    HD_REGIONAL AS regional,
    HD_FILIAL AS branch,
    HD_FASE_COBRANCA AS collection_phase,
    HD_DIASATRASO AS delay_contamined_days,
    HD_REFSAFRA AS year_month,
    HD_ASSESSORIA AS agency,
    HD_NOVA_ASSESSORIA AS new_agency,
    HD_STATUS AS status,
    HD_NOVO_STATUS AS new_status,
    HD_ANOMES_RECEB AS year_month_received,
    HD_ANOMES_RECUPERADO AS year_month_recovered,
    HD_IN_PRESTACAO_ZERO AS zero_installment_flag,
    HD_DESEMPENHO AS flag_performance,
    HD_CRIT_SELECAO AS selection_criteria,
    HD_QUE1 AS segmentation_queue,
    HD_QUE2 AS commission_queue,
    HD_QUE3 AS agreement_queue,
    HD_QUE4 AS digital_channel_queue,
    HD_QUE5 AS eviction_queue,
    HD_QUE6 AS credit_denial_queue,
    HD_LABEL1 AS olos_dialer_label,
    HD_LABEL2 AS label_2,
    HD_LABEL3 AS campaign_label,
    HD_LABEL4 AS label_4,
    HD_LABEL5 AS pre_legal_label,
    HD_LABEL6 AS label_6,
    HD_VL_DIVIDA AS debt_amount,
    HD_VL_NOVA_DIVIDA AS new_debt_amount,
    HD_VL_SLD_DEVIDO AS balance_due_amount,
    HD_VL_NOVO_SLD_DEVIDO AS new_balance_due_amount,
    HD_VL_RECEB_ACUM AS accumulated_amount_received,
    HD_VL_RECEB_NO_MES AS received_amount_month,
    HD_VL_RECUPERADO AS recovered_amount,
    HD_VL_NOVAS_PREST AS new_installments_amount,
    HD_VL_PAGO_A_MAIOR AS paid_amount_the_biggest,
    HD_VL_EXCLUIDO AS excluded_amount,
    HD_DT_DISPONIBILIZACAO AS ts_distribution,
    HD_DT_NOVA_DISPONIB AS ts_redistribution,
    NOW() AS ts_load
FROM datalake_cyber_raw.tb_historico_disponibilizacao
