SELECT
    HAID AS id_agreement,
    HAACCT AS id_contract,
    AHIDPARC AS id_invoice,
    AHSSNUM AS id_client,
    HAACCTG AS contract_group,
    AHDAYS AS contract_delay_days,
    AHDLQDT AS ts_due_contract,
    AHCURBAL AS total_contract_amount,
    AHAMTDLQ AS contract_main_overdue_amount,
    AHVLJURATRA,
    AHMULTCON,
    AHVLVENC,
    AHVLRPRCAG AS main_amount_overdue,
    AHVLRPRCAVAG AS main_amount_due,
    AHVLRPRMUAGR AS residual_final_amount,
    AHVLRMUAGR AS agreement_fine_amount,
    AHVLRPRJUAG,
    AHVLRJUAG,
    AHVLRCUSAG,
    AHVLCUSTASAG,
    AHVLRHOREAG,
    AHVLRTXCARAG,
    AHVLPRINC,
    AHVLJUR,
    AHVLMUL,
    AHVLCUSTA,
    AHHONORARIOS,
    AHVLRDESPJUD
FROM datalake_cyber_raw.agr_hist
