SELECT
    HAID AS id_agreement,
    HAACCT AS id_contract,
    AHIDPARC AS id_invoice,
    AHSSNUM AS id_client,
    HAACCTG AS contract_group,
    AHDAYS AS contract_delay_days,
    AHDLQDT AS ts_due_contract,
    AHCURBAL AS total_contract_amount,
    AHAMTDLQ AS contract_main_overdue_amount,
    AHVLJURATRA,
    AHMULTCON,
    AHVLVENC,
    AHVLPRINC AS invoice_due_amount,
    AHVLRPRCAG AS total_amount_overdue,
    AHVLRPRCAVAG AS main_amount_due,
    AHVLRPRMUAGR AS residual_final_amount,
    AHVLRMUAGR AS agreement_fine_amount,
    AHVLRJUAG AS agreement_contract_interest_fees_amount,
    AHVLCUSTASAG AS agreement_eviction_costs_amount,
    AHVLRTXCARAG AS agreement_credit_card_fee,
    AHHONORARIOS AS agreement_honorarium,
    AHVLRPRJUAG,
    AHVLRCUSAG,
    AHVLRHOREAG,
    AHVLJUR,
    AHVLMUL,
    AHVLCUSTA,
    AHVLRDESPJUD
FROM datalake_cyber_raw.agr_hist
