SELECT
    n_cadastro_sql AS iptu_sql_registration_number,
    TRIM(matricula_imovel) AS house_registry_number,
    nome_logradouro AS address_street_name,
    numero AS address_number,
    complemento AS address_complement,
    bairro AS address_neighborhood,
    referencia AS address_reference,
    TRIM(cep) AS address_zipcode,
    TRIM(natureza_transacao) AS transaction_nature,
    TRIM(tipo_financiamento) AS financing_type,
    TRIM(cartorio_registro) AS house_registry_office,
    TRIM(situacao_sql) AS iptu_sql_status,
    TRIM(descricao_uso_iptu) AS iptu_use_description,
    TRIM(descricao_padrao_iptu) AS iptu_standard_description,
    valor_transacao_declarado AS declared_transaction_value,
    valor_venal_referencia AS reference_appraisal_value,
    proporcao_transmitida AS transmitted_proportion,
    valor_venal_referencia_proporcional AS proportional_reference_appraisal_value,
    base_calculo_adotada AS adopted_calculation_basis,
    valor_financiado AS financed_value,
    area_terreno_m2 AS land_area_m2,
    testada_m AS portion_public_road_land_m,
    fracao_ideal AS ideal_fraction,
    area_construida_m2 AS built_area_m2,
    TRIM(uso_iptu) AS iptu_use_code,
    TRIM(padrao_iptu) AS iptu_standard_code,
    acc_iptu AS iptu_registration_year,
    source_file,
    source_tab,
    data_transacao AS dt_transaction,
    dt_load,
    year,
    month,
    day
FROM
    datalake_itbi_raw.itbi_sp
WHERE
    dt_load = current_date