drop view if exists public.vw_dim_property;

create or replace view public.vw_dim_property as
SELECT
	((i.id || '00') || COALESCE(pl.version, 1))::bigint AS sk_property,
  i.id,
  pl.version,
  pl.min_version_time,
  pl.max_version_time,
  pl.status::varchar(255) as last_status_version,
  i.aluguel,
  i.bairro,
  i.cep,
  i.cidade,
  i.complemento,
  i.condominio,
  i.data_construcao,
  i.elevador,
  i.email_contato,
  i.email_sessao_fotos,
  i.endereco,
  i.estado_conservacao,
  i.fotografo_preenche_dados,
  i.iptu,
  i.lat,
  i.lng,
  i.mobiliado,
  i.nivel_acabamento,
  i.numero,
  i.numero_banheiros,
  i.numero_quartos,
  i.numero_suites,
  i.numero_vagas,
  i.porcentagem_cadastro_completa,
  i.prefere_email_sessao_fotos,
  i.status,
  i.tel_contato1,
  i.tel_contato2,
  i.tel_sessao_fotos,
  i.tipo,
  i.tipo_porteiro,
  i.tipo_vagas,
  i.verificado,
  i.usuario_id,
  i.codigo_promocao,
  i.cotar_seguro,
  i.valor_total,
  i.expiration_date,
  i.notificacao_anuncio_incompleto_proprietario,
  i.notificacao_anuncio_incompleto_admin,
  i.short_url,
  i.valor_seguro,
  i.plano_aceito,
  i.sugerir_reajuste_de_preco,
  i.permite_placa_aluga_se,
  i.prioridade_destaque_classificado,
  i.dados_administradora_condominio,
  i.condominio_incluso,
  i.coordenadas_manuais,
  i.iptu_incluso,
  i.followup_proprietario_subir_fotos,
  i.data_primeiro_verificado,
  i.tipo_colisao_lead,
  i.calculo_pagamento_lead_corretor,
  i.nome_imagem_capa,
  i.geo_hash,
  i.tipo_anuncio,
  i.calculo_pagamento_lead_afiliado,
  i.possui_banheiro_servico,
  i.possui_quarto_servico,
  i.bairro_padrao,
  i.tipo_condominio,
  i.tipo_iptu,
  i.disponivel_ate,
  i.flag_verificar_preco_comparando_com_media,
  i.sempre_consultar_proprietario_visita,
  i.email_publicacao_proprietario_enviado,
  i.status_conversao_imovel,
  i.ultimo_email_de_confirmacao_enviado,
  i.latlng,
  i.ultimo_update_indice,
  i.suspenso_ate,
  i.external_id,
  i.em_negociacao,
  i.em_negociacao_externa,
  i.entrou_em_negociacao_externa,
  i.motivo_recusa_cardiff,
  i.recaptado_em,
  i.job_fotografo_pendente,
  i.requisitou_fotos_profissionais,
  i.last_confirmation_availability,
  i.cartorio,
  i.penalization_score,
  i.receber_copia_contrato_padrao,
  i.rank_score,
  i.ultima_publicacao,
  i.confirmado_informacoes_visita,
  i.estado_abreviacao,
  i.estado_nome,
  i.regiao_cidade,
  i.regiao_macro,
  i.regiao_sub,
  i.regiao_id,
  i.condominio_nome,
  i.local_nome,
  i.first_publication,
  pl.min_version_time::date as publication_date,
  pl.de_publication_date,
  (date_part('epoch', c."dataAssinado"::timestamp - pl.min_version_time) / 86400)::int8 AS time_first_listing_to_contract_signed,
  (date_part('epoch', pl.de_publication_date - pl.min_version_time) / 86400)::int8 AS time_listing_to_depublication,
  coalesce(pl.version,0) as nr_listing,
  coalesce(pl.nr_renting::bigint, 0) as nr_renting,
  i.info_visita_autorizacao_de_entrada,
  i.info_visita_proprietario_acompanha,
  i.info_visita_estamos_liberados,
  i.info_visita_prop_precisa_liberar,
  i.info_visita_chave_box_quintoandar,
  i.data_criacao,
  i.atualizado_em,
  now() AS load_timestamp,
  i.usuario_que_cadastrou_id,
  i.imovel_v3 as property_v3,
  i.area_total as total_area,
  i.area_terreno as contruction_area,
  i.unpublished_reason as unpublished_reason,
  pl.start_version_category,
  pl.end_version_category,
  pl.is_last_version,
  i.exclusivity,
  CASE  WHEN SUBSTRING(i.id::VARCHAR(24) FOR 4) = '8927'
            THEN SUBSTRING(i.id::VARCHAR(24) FROM 5)
        WHEN SUBSTRING(i.id::VARCHAR(24) FOR 4) = '8928'
            THEN CONCAT('1',SUBSTRING(i.id::VARCHAR(24) FROM 5))
  END
  AS short_id_property
from
	imovel i
left join
	property_listing pl
	ON pl.id = i.id
left join
	contract c
	on c.id = pl.contract_id