drop view if exists vw_dim_house_listing;
create or replace view vw_dim_house_listing as
select
  ((h.id || '00') || coalesce(pl.version, 1))::bigint as sk_house_listing,
  h.id as id_house,
  h.id % 892700000 as short_id_house,
  pl.version as version,
  pl.status::varchar(255),
  pl.min_version_time as ts_listing_version_start,
  pl.max_version_time as ts_listing_version_end,
  h.data_primeiro_verificado as ts_house_registration_first_verification,
  h.last_confirmation_availability as ts_house_last_confirmation_availability,
  h.first_publication as ts_house_first_publication,
  h.ultima_publicacao as ts_house_last_publication,
  pl.min_version_time::date as ts_publication,
  pl.de_publication_date as ts_de_publication,
  pl.aluguel as rent,
  h.aluguel as house_rent,
  h.bairro as house_neighborhood,
  h.cep as house_zipcode,
  h.cidade as house_city,
  h.complemento as house_complement,
  h.condominio as house_condo,
  h.elevador as house_elevator,
  h.endereco as house_address,
  h.iptu as house_iptu,
  h.lat as house_lat,
  h.lng as house_lng,
  h.mobiliado::boolean as is_house_furnished,
  h.numero as house_number,
  h.numero_banheiros as house_bathrooms,
  h.numero_quartos as house_bedrooms,
  h.numero_suites as house_suites,
  h.numero_vagas as house_garages,
  h.status as house_status,
  h.tipo as house_type,
  h.tipo_porteiro as house_entrance,
  h.tipo_vagas as house_garage_type,
  h.verificado::boolean as is_house_registration_verified,
  h.valor_total as house_total_value,
  h.area_total as house_total_area,
  h.area_terreno as house_construction_area,
  h.tipo_condominio as house_condo_type,
  h.tipo_iptu as house_iptu_type,
  h.data_criacao as ts_house_create,
  h.atualizado_em as ts_house_update,
  h.registration_abandoned_reason as registration_abandoned_reason,
  h.unpublished_reason as house_unpublished_reason,
  pl.start_version_category as listing_category_start,
  pl.end_version_category as listing_category_end,
  pl.is_last_version::boolean,
  h.exclusivity::integer::boolean as is_exclusive,
  h.house_occupant as who_is_living,
  h.key_type,
  h.key_location,
  coalesce(h.visit_restriction = 'Restriction', false) as has_visit_restriction,
  h.predicted_price as house_predicted_price,
  now() as ts_load
from house h
left join house_listing pl
  on pl.id = h.id
