drop view if exists vw_dim_house_listing;
create or replace view vw_dim_house_listing as
select
  ((i.id || '00') || coalesce(pl.version, 1))::bigint as sk_house_listing,
  i.id as id_house,
  i.id % 892700000 as short_id_house,
  pl.version as version,
  pl.status::varchar(255),
  pl.min_version_time as ts_listing_version_start,
  pl.max_version_time as ts_listing_version_end,
  i.data_primeiro_verificado as ts_house_registration_first_verification,
  i.last_confirmation_availability as ts_house_last_confirmation_availability,
  i.first_publication as ts_house_first_publication,
  i.ultima_publicacao as ts_house_last_publication,
  pl.min_version_time::date as ts_publication,
  pl.de_publication_date as ts_de_publication,
  pl.aluguel as rent,
  i.bairro as house_neighborhood,
  i.cep as house_zipcode,
  i.cidade as house_city,
  i.complemento as house_complement,
  i.condominio as house_condo,
  i.elevador as house_elevator,
  i.endereco as house_address,
  i.iptu as house_iptu,
  i.lat as house_lat,
  i.lng as house_lng,
  i.mobiliado::boolean as is_house_furnished,
  i.numero as house_number,
  i.numero_banheiros as house_bathrooms,
  i.numero_quartos as house_bedrooms,
  i.numero_suites as house_suites,
  i.numero_vagas as house_garages,
  i.status as house_status,
  i.tipo as house_type,
  i.tipo_porteiro as house_entrance,
  i.tipo_vagas as house_garage_type,
  i.verificado::boolean as is_house_registration_verified,
  i.valor_total as house_total_value,
  i.area_total as house_total_area,
  i.area_terreno as house_construction_area,
  i.tipo_condominio as house_condo_type,
  i.tipo_iptu as house_iptu_type,
  i.data_criacao as ts_house_create,
  i.atualizado_em as ts_house_update,
  i.unpublished_reason as house_unpublished_reason,
  pl.start_version_category as listing_category_start,
  pl.end_version_category as listing_category_end,
  pl.is_last_version::boolean,
  i.exclusivity::integer::boolean as is_exclusive,
  i.house_occupant as who_is_living,
  i.key_type,
  i.key_location,
  coalesce(i.visit_restriction = 'Restriction', false) as has_visit_restriction,
  now() as ts_load
from imovel i
left join house_listing pl
  on pl.id = i.id
