SELECT
    id,
    contract_id AS id_contract,
    exit_inspection_id AS id_exit_inspection,
    current_step_id AS id_current_step,
    support_case as id_support_case,
    feedback,
    tenant_keys_location,
    owner_keys_location,
    requested_by,
    source,
    status,
    internal_status,
    cancellation_info,
    rescheduling_history,
    utility_bill_info,
    last_condominium_responsible,
    tenant_pending_tasks,
    category,
    inspection_date_offset_in_days,
    exit_inspection_required AS has_exit_inspection,
    relisting_enabled AS is_relisting,
    relisting_date AS dt_relisting,
    date AS dt_termination,
    vacancy_date AS dt_vacancy,
    end_date AS dt_ended_termination,
    canceled_at AS ts_canceled,
    created_at AS ts_created,
    updated_at AS ts_updated
FROM
    datalake_terminator_test_raw.termination
