SELECT
    id,
    termination_id AS id_termination,
    contract_adm_fee,
    category,
    rev,
    revtype AS rev_type,
    revend AS rev_end,
    period_occupancy_days,
    period_fee_missing_days,
    period_fee_days,
    period_fee_months,
    fee_ratio,
    fee_factor,
    contract_rental_amount,
    tenant_amount,
    landlord_amount,
    fee_prior_notice AS is_fee_prior_notice,
    pre_living AS is_pre_living,
    period_start_charge AS dt_period_started_charge,
    period_end_charge AS dt_period_ended_charge,
    period_min_end_date AS dt_period_min_ended,
    period_fee_end_date AS dt_period_fee_ended,
    request_date AS dt_requested,
    created_at AS ts_created,
    updated_at AS ts_updated,
    outdated_at AS ts_outdated,
    year,
    month,
    day
FROM
    datalake_terminator_test_raw.termination_fee_aud
