select
  id,
  visitante_id as id_visitor,
  agente_id as id_agent,
  coordinateid as id_coordinate,
  encerrado as is_closed,
  imovel_id as id_house,
  primeiravez as is_first_time,
  visita_id as id_visit,
  fluxolocacao_id as id_rent_flow,
  reagendadode_id as id_rescheduled_booking,
  followupdetails_id as id_fup_details,
  jobfotografo_id as id_photo_job,
  atendente_id as id_attendant,
  origemultimaatualizacao_id as id_last_update_origin,
  codigo as code,
  durationinslots as slots_duration,
  businesscontext as business_context,
  intention as buyer_intention,
  checkinstatus as checkin_status,
  visitordatetime as visitor_id_date_slot,
  status,
  preferecontato as contact_preference,
  hash,
  slotdia as slot_day,
  fupvisita as visit_fup,
  tipo as type,
  agentefixo as is_agent_fixed,
  comentariofupvisita as visit_fup_comment,
  informeinquilinopendente as is_tenant_notification_pending,
  confirmado as is_confirmed,
  permitirconflito as is_conflict_allowed,
  data as dt_booking,
  proxnotfup as ts_next_not_fup,
  datafupvisita as ts_visit_fup,
  avisadoentrouemnegociacao as ts_negotiation_start_notified,
  criadoem as ts_created,
  atualizadoem as ts_updated
from datalake_ebdb_raw.Agendamento
