select
  id,
  REV,
  REVTYPE as rev_type,
  bairro as neighborhood,
  cep as zip_code,
  cidade as city,
  complemento as complement,
  cpf,
  dataExpedicaoRG as dt_rg_created,
  dataNascimento as dt_birth,
  email,
  endereco as address,
  estadoCivil as marital_status,
  legalRepresentative_cpf as legal_representative_cpf,
  legalRepresentative_email as legal_representative_email,
  legalRepresentative_nome as legal_representative_name,
  legalRepresentative_rg as legal_representative_rg,
  nacionalidade as nationality,
  nome as name,
  numero as number,
  orgaoExpedidor as issuing_body,
  profissao as profession,
  rg,
  sexo as gender,
  telefone as phone_number,
  telefoneSecundario as secondary_phone,
  tipo as type,
  usuario_id as id_user,
  vaiMorar as will_live,
  withRepresentative as is_with_representative,
  contrato_id as id_contract,
  estado_id as id_state,
  usuarioId_MOD as mod_id_user
from datalake_ebdb_raw.contratopessoa_aud