SELECT
    id,
    imovel_id AS id_house,
    emailFatura AS invoice_email,
    observacao AS observation,
    valorAluguel AS rent,
    status,
    proposta_id AS id_proposal,
    numImovel AS house_number,
    criadoEm AS ts_created,
    diaMesCobranca AS billing_day_of_month,
    garantia AS guarantee_type,
    tipo AS type,
    usuario_id AS id_user,
    dataCalculoComissaoAfiliado AS ts_affiliate_comission_calculated,
    dataCalculoComissaoCorretor AS ts_agent_comission_calculated,
    agenciaBanco AS bank_agency,
    comentarioProprietario AS owners_comment,
    contaBanco AS bank_account,
    correspondencia_bairro AS neighborhood_for_mailing,
    correspondencia_cep AS zip_code_for_mailing,
    correspondencia_cidade AS city_for_mailing,
    correspondencia_complemento AS complement_for_mailing,
    correspondencia_logradouro AS street_for_mailing,
    correspondencia_numero AS house_number_for_mailing,
    dataEntrada AS dt_entered,
    dataInicio AS dt_started,
    iptu_parcelas AS iptu_installment,
    iptu_valor AS iptu,
    nomeBanco AS bank_name,
    paganteCondominio AS paying_condo,
    paganteIptu AS paying_iptu,
    responsavelCondominio AS responsible_for_condo,
    responsavelIptu AS responsible_for_iptu,
    seguroFianca_parcelas AS rental_guarantee_installment,
    seguroFianca_valor AS rental_guarantee_value,
    seguroResidencial_parcelas AS home_insurance_installment,
    seguroResidencial_valor AS home_insurance_value,
    taxaComissaoPrimeiroAluguel AS fist_rent_comission_fee,
    tipoContaBanco AS account_type,
    valorCondominio AS condo_price,
    valorIptu AS value_iptu, -- to force the memory: column name repeated
    correspondencia_estado_id AS id_mailing_state,
    comSeguroResidencial AS has_home_insurance,
    bairro AS neighborhood,
    cep AS zip_code,
    cidade AS city,
    complemento AS address_details,
    endereco AS address,
    numero AS number,
    estado_id AS id_state,
    dataFimContratoPrevisto AS ts_contract_expected_end, -- TODO [ODS] rename col to dt_contract_expected_end
    dataRescisao AS dt_termination,
    -- bank columns repeated, so I put 'data' in column name
    dadosBanco_agencia AS bank_data_agency,
    dadosBanco_contaCorrente AS bank_data_account,
    dadosBanco_cpfOuCnpj AS bank_data_cpf_cnpj,
    dadosBanco_nome AS bank_data_name,
    dadosBanco_outroTitular AS bank_data_other_holder,
    dadosBanco_tipoConta AS bank_data_account_type,
    atualizadoEm AS ts_updated,
    dadosBanco_banco_id AS id_bank_data,
    dataAssinado AS ts_signed,
    dataMinutaAprovada AS ts_minuta_approved,
    emTransitoInquilino AS is_tenant_in_transit,
    emTransitoProprietario AS is_owner_in_transit,
    recebidoAposAssinatura AS has_received_after_signature,
    termoAditivoAdicionado AS has_contract_amendment,
    tipoAssinatura AS signature_type,
    dataContratoEletronicoEnviado AS ts_electronic_contract_sent,
    todosAssinaramContratoEletronico AS has_everybody_signed_electronic_contract,
    statusClosing AS status_closing,
    contratoAssinado AS contract_signed,
    googleDriveId AS id_google_drive,
    tokenESignatureLocacao AS token_esignature_rent,
    tokenESignatureAdm AS token_esignature_adm,
    contratoAdministracaoAssinado AS management_contract_signed,
    contratoAutorizacaoEntradaAssinado AS authorization_contract_entry_signed,
    contratoLocacaoAssinado AS rent_contract_signed,
    dataTrocaTitularidade AS ts_ownership_swapped,
    policy,
    administrationFeeType_id AS id_administration_fee_type,           
    contractVersion_id AS id_contract_version,
    dataRescisaoPrevista AS ts_expected_termination,
    fairfaxStartDate AS ts_fair_fax_started,
    estateAgentBrokerageShare AS agent_brokerage_share
FROM
    datalake_ebdb_raw.`contrato`