SELECT
    id as id_lead,
    REV AS rev,
    rEVTYPE AS rev_type,
    anuncioCriadoEm AS dt_ad_created,
    areaTotal AS total_area,
    bairro AS neighborhood,
    captadoEm AS dt_picked_up,
    cep as zip_code,
    cidade AS city,
    complemento AS complement,
    condominio AS condo_price,
    dentroAreaAtuacao AS is_inside_operation_area,
    endereco AS address,
    enderecoCaptado AS address_picked_up,
    geradoAPartirDeDuplicacao AS has_generated_from_duplication,
    hot AS is_hot,
    infosExtras AS extra_infos,
    iptu,
    lat,
    lng,
    numero AS house_number,
    numeroBanheiros AS bathrooms,
    numeroQuartos AS bedrooms,
    numeroSuites AS suites,
    reason,
    reason_MOD as mod_reason,
    salesforceId AS id_salesforce,
    urlAnuncio AS ad_url,
    valor AS rent,
    estado_id AS id_state,
    nomeAnunciante AS advertiser_name,
    telefoneAnunciante AS advertiser_phone,
    valorPorMetroQuad AS rent_per_square_meter,
    valorPorQuartos AS rent_per_bedroom,
    tipo AS type,
    email,
    emailCaptador AS pick_up_email,
    telefoneAnuncianteDois AS advertiser_second_phone,
    telefoneAnuncianteTres AS advertiser_third_phone,
    telefoneCaptador AS pick_up_phone,
    proprietarioLead_id AS id_lead_owner,
    afiliadoQueIndicou_id AS id_affiliate_has_indicated,
    sistemaEnviouEmailViaClassificado AS has_sent_email_from_classifieds,
    status,
    status_MOD as mod_status,
    envioEmailApresentacaoPos AS has_sent_presentation_email_after_registration,
    envioEmailApresentacaoPos_MOD AS mod_has_sent_presentation_email_after_registration,
    envioEmailApresentacaoPre AS has_sent_presentation_email_before_registration,
    envioEmailApresentacaoPre_MOD AS mod_has_sent_presentation_email_before_registration,
    processado AS has_processed,
    processado_MOD AS mod_has_processed,
    origem AS source,
    externalId AS id_external,
    mencionar AS is_to_be_mentioned,
    referencia AS reference,
    automaticallyDiscarded AS has_automatically_discarded,
    region_id AS id_region,
    region_MOD as mod_region,
    urlSource AS url_source,
    utmMedium AS utm_medium,
    utmCampaign AS utm_campaign,
    utmSource AS utm_source,
    fromRoofTopper AS is_from_roof_topper,
    fromRoofTopper_MOD AS mod_is_from_roof_topper,
    outroBairro AS other_neighborhood,
    outraCidade AS other_city,
    lastUpdateStatusDate AS ts_last_status_updated,
    lastUpdateStatusDate_MOD as mod_ts_last_status_updated,
    recurringStatusCount AS recurring_status_count,
    recurringStatusCount_MOD AS mod_recurring_status_count,
    codigoImobiliaria AS real_estate_agency_code,
    exclusivityIntent AS is_exclusivity_intent,
    ownerDeviceId AS id_owner_device,
    unbouncePageName AS unbounce_page_name,
    unbouncePageVariant AS unbounce_page_variant,
    unbouncePageUri AS unbounce_page_uri,
    salePrice AS sale_price,
    forRent AS is_for_rent,
    forSale AS is_for_sale,
    affiliateType AS affiliate_type,
    dadosAgente_id AS id_agent
FROM
    datalake_ebdb_raw.`lead_aud`
