select
  id as id_listing_business_context,
  rev,
  revtype as rev_type,
  lastPublicationDate as ts_last_publication,
  lastPublicationDate_mod as mod_ts_last_publication,
  businessContext as business_context,
  businessContext_mod as mod_business_context,
  shortUrl as short_url,
  shortUrl_mod as mod_short_url,
  status,
  status_mod as mod_status,
  closingStatus as status_closing,
  closingStatus_mod as mod_status_closing,
  imovelId as id_house,
  selectedAction as selected_action,
  selectedAction_mod as mod_selected_action,
  statusReason as status_reason,
  statusReason_mod as mod_status_reason,
  calculatorPrice as calculator_price,
  calculatorPrice_mod as mod_calculator_price,
  firstPublicationDate as ts_first_publication,
  firstPublicationDate_mod as mod_ts_first_publication,
  atualizadoEm as ts_updated,
  criadoEm as ts_created
from datalake_ebdb_raw.ListingBusinessContext_AUD
