select
  scorecorretude as correctness_score,
  status,
  imovel_id as id_house,
  datapagamento as ts_payment,
  originlastupdate_id as id_last_update_origin,
  motivocancelamentojob as cancellation_reason,
  prefereemailsessaofotos as is_photo_session_email_preferred,
  dadosfotografo_id as id_photographer,
  fixed as is_fixed,
  telefonesessaofotos as photo_session_phone,
  retirarchave as key_pick_up,
  aprovado as is_approved,
  datainiciosessao as ts_session_started,
  naotentoucontato as has_tried_contact,
  id,
  emailsessaofotos as photo_session_email,
  telefonesessaofotossecundario as photo_session_secondary_email,
  problema as problem,
  lockbox as has_lockbox,
  atualizadoem as ts_updated,
  nomecontatosessaofotos as photo_session_contact_name,
  datauploadfotos as ts_photos_uploaded,
  textomotivocancelamento as cancellation_reason_text,
  datacriacao as ts_created,
  autorizacaoporescrito as has_written_authorization,
  outroschave as key_others,
  instrucoesagendamento as booking_instructions,
  origincreation_id as id_origin_creation,
  revisionimovel as house_revision,
  datajobpedido as ts_photo_job_requested,
  confirmado as is_confirmed,
  dataagendamento as ts_scheduled,
  tipocontrato as contract_type,
  dataaceitofotografo as ts_photographer_accepted,
  reservadopara_id as id_reserved_for,
  scorecompletude as completeness_score,
  semcontatoproprietario as has_no_landlord_contact
from datalake_ebdb_raw.JobFotografo