SELECT
    id,
    atualizadoEm AS ts_updated,
    criadoEm AS ts_created,
    aceitoAluguel AS has_rental_accepted,
    aceitoComprovarRenda AS has_income_proof_accepted,
    aceitoEncargos AS has_charge_accepted,
    aluguel AS rent,
    dataAprovacao AS ts_approved,
    edicao AS edition,
    proprietarioAceitouCondicoes5A AS is_owner_accept_condition,
    status,
    ultimoUpdateEdicao AS last_edition_updated,
    animais_id AS id_animals,
    usuario_id AS id_user,
    imovel_id AS id_house,
    quandoVaiMudar_id AS id_when_will_live,
    quemVaiMorar_id AS id_who_will_live,
    aluguelOriginal AS original_rent,
    condominioOriginal AS original_condo,
    iptuOriginal AS original_iptu,
    homeOwnerInsuranceOriginalValue AS original_home_insurance,
    expirationDate AS ts_expired,
    lastEdicaoUpdateDate AS ts_last_edition_updated,
    rejectionReason AS rejection_reason,
    code,
    visualizedDate AS ts_visualized
FROM
    datalake_ebdb_raw.preproposta
