SELECT
    id,
    active AS is_active,
    bairro AS neighborhood,
    cep AS zip_code,
    cidade AS city,
    complemento AS complement,
    cpf,
    dataNascimento AS dt_birth,
    email,
    emailAlternativo AS alternative_email,
    endereco AS address,
    facebookId AS id_facebook,
    foto AS photo,
    linkedInId AS id_linkedin,
    nome AS name,
    numero AS number,
    password,
    sexo AS gender,
    telefoneComercial AS business_phone,
    telefonePrincipal AS main_phone,
    telefoneSecundario AS secondary_phone,
    estado_id AS id_state,
    contadorlogin AS login_count,
    criadoEm AS ts_created,
    naoMePergunteTelefone AS do_not_ask_phone,
    bloqueado AS is_blocked,
    rg,
    dataExpedicaoRg AS ts_rg_created,
    detalhesLeadBuscaGuiada AS detail_lead_guided_search,
    recebeuBuscaGuiada AS has_received_guided_search,
    dadosAgente_id AS id_agent,
    aceitaSms AS has_accepted_sms,
    hashLoginBypass AS hash_login_bypass,
    preferenciaContato AS contact_preference,
    prefereContato AS desire_contact,
    dataClickAnuncie AS ts_click_anuncie,
    dadosBancarios_agencia AS bank_agency,
    dadosBancarios_contaCorrente AS bank_account,
    dadosBancarios_cpfOuCnpj AS bank_cpf_cnpj,
    -- TODO [ODS] rename to bank_person_name
    dadosBancarios_nome AS bank_name,
    dadosBancarios_outroTitular AS bank_another_holder,
    dadosBancarios_tipoConta AS bank_account_type,
    naoEnviarAvisoMensalProcura AS do_not_send_search_monthly_notice,
    codAtivacaoSms AS sms_activation_code,
    dataGeracaoCodSms AS ts_sms_code_created,
    tipoAdmin AS admin_type,
    atualizadoEm AS ts_updated,
    lastUpdateOportunidade AS ts_last_update_opportunity,
    dadosBancarios_banco_id AS id_bank,
    avisadoCondicoesCardiffEm AS ts_noticed_cardiff_conditions,
    captadoraEnviouEmailEm AS ts_collector_email_sent,
    enviadoAppECardiffEm AS ts_app_ecardiff_sent,
    googleId AS id_google,
    accountKitId AS id_account_kit,
    dadosFotografo_id AS id_photographer_data,
    dadosVendedor_id AS id_sales_rep,
    dadosAgente_id AS id_agent_rep,
    dadosAfiliado_id AS id_affiliates,
    contaCorrente_id AS id_account,
    oldPhone AS old_phone,
    userCrmData_id AS id_user_crm_data,
    loginRenewal AS ts_login_renewal,
    keycloakUserId AS id_keycloak_user,
    lastLoggedAt AS ts_last_logged,
    instantLogin AS is_instant_login
FROM
    datalake_ebdb_raw.`Usuario`
