# Adding here the columns to be used in the API

from pyspark.sql.types import BooleanType, LongType, StringType, StructField, StructType

API_RESPONSE_SCHEMA = StructType(
    [
        StructField("id_record", StringType(), True),
        StructField("idx", LongType(), True),
        StructField("api_logs", StringType(), True),
        StructField("success", BooleanType(), True),
        StructField("error", StringType(), True),
        StructField("query", StringType(), True),
        StructField("record_json", StringType(), True),
    ]
)


# Keep it only column name, Salesforce /describe endpoint will return the column type
SF_RAW_SCHEMA_COLS = {
    "task": [
        "Id",
        "WhoId",
        "WhatId",
        "WhoCount",
        "WhatCount",
        "Subject",
        "ActivityDate",
        "Status",
        "Priority",
        "IsHighPriority",
        "OwnerId",
        "Description",
        "Type",
        "IsDeleted",
        "AccountId",
        "IsClosed",
        "CreatedDate",
        "CreatedById",
        "LastModifiedDate",
        "LastModifiedById",
        "SystemModstamp",
        "IsArchived",
        "CallDurationInSeconds",
        "CallType",
        "CallDisposition",
        "CallObject",
        "ReminderDateTime",
        "IsReminderSet",
        "RecurrenceActivityId",
        "IsRecurrence",
        "RecurrenceStartDateOnly",
        "RecurrenceEndDateOnly",
        "RecurrenceTimeZoneSidKey",
        "RecurrenceType",
        "RecurrenceInterval",
        "RecurrenceDayOfWeekMask",
        "RecurrenceDayOfMonth",
        "RecurrenceInstance",
        "RecurrenceMonthOfYear",
        "RecurrenceRegeneratedType",
        "TaskSubtype",
        "CompletedDateTime",
        "IsABTest__c",
        "ContractIdOddOrEven__c",
        "ExperimentGroup__c",
        "PassDueDate__c",
        "ResponsabilityContestingIsGood__c",
        "TaskName__c",
        "Type__c",
        "TaskInteractionType__c",
        "FirstInteractionDate__c",
        "DelayMessage__c",
        "CaseCriticality__c",
        "Answer__c",
        "TaskCreatedDate__c",
        "Observation__c",
        "ContractId__c",
        "CallId__c",
        "CognitoLink__c",
        "EntityId__c",
        "FS_CRI_RegistrationCompleted__c",
        "FS_KeysReceived__c",
        "FS_OfferId__c",
        "FS_PurchaseSaleContract__c",
        "FS_ReasonDelay__c",
        "FS_Seller__c",
        "GetResponse__c",
        "KeyDeliveryDate__c",
        "PaidViaTed__c",
        "QuestionResolvedInformedCustomer__c",
        "RecordTypeId",
        "ReturnDateCustomer__c",
        "SchedulingDate__c",
        "SchedulingManagement__c",
        "SLA__c",
        "Source__c",
        "TaskAction__c",
        "TaskDueDateFormula__c",
        "TaskManagement__c",
        "WasDisagreement__c",
        "UnlistingReason__c",
        "CommunicationTask__c",
        "HSMSent__c",
        "SourceTask__c",
        "EmailSent__c",
        "CommunicationStatus__c",
    ],
    "recordtype": [
        "Id",
        "Name",
        "DeveloperName",
        "NamespacePrefix",
        "Description",
        "BusinessProcessId",
        "SobjectType",
        "IsActive",
        "IsPersonType",
        "CreatedById",
        "CreatedDate",
        "LastModifiedById",
        "LastModifiedDate",
        "SystemModstamp",
    ],
    "casemilestone": [
        "Id",
        "CaseId",
        "StartDate",
        "TargetDate",
        "CompletionDate",
        "MilestoneTypeId",
        "IsCompleted",
        "IsViolated",
        "SystemModstamp",
        "CreatedDate",
        "CreatedById",
        "LastModifiedDate",
        "LastModifiedById",
        "IsDeleted",
        "TargetResponseInMins",
        "TargetResponseInHrs",
        "TargetResponseInDays",
        "TimeRemainingInMins",
        "TimeRemainingInHrs",
        "TimeRemainingInDays",
        "ElapsedTimeInMins",
        "ElapsedTimeInHrs",
        "ElapsedTimeInDays",
        "TimeSinceTargetInMins",
        "TimeSinceTargetInHrs",
        "TimeSinceTargetInDays",
        "BusinessHoursId",
    ],
    "casefeed": [
        "Id",
        "ParentId",
        "Type",
        "CreatedById",
        "CreatedDate",
        "IsDeleted",
        "LastModifiedDate",
        "SystemModstamp",
        "CommentCount",
        "LikeCount",
        "Title",
        "Body",
        "LinkUrl",
        "IsRichText",
        "RelatedRecordId",
        "InsertedById",
        "NetworkScope",
        "Visibility",
        "BestCommentId",
    ],
    "emailmessage": [
        "Id",
        "ParentId",
        "ActivityId",
        "CreatedById",
        "LastModifiedById",
        "ReplyToEmailMessageId",
        "EmailTemplateId",
        "RelatedToId",
        "TextBody",
        "HtmlBody",
        "Headers",
        "Subject",
        "FromName",
        "FromAddress",
        "ValidatedFromAddress",
        "ToAddress",
        "CcAddress",
        "BccAddress",
        "Status",
        "MessageIdentifier",
        "ThreadIdentifier",
        "Incoming",
        "HasAttachment",
        "IsDeleted",
        "IsPrivateDraft",
        "IsExternallyVisible",
        "IsClientManaged",
        "IsTracked",
        "IsOpened",
        "IsBounced",
        "MessageDate",
        "FirstOpenedDate",
        "LastOpenedDate",
        "CreatedDate",
        "LastModifiedDate",
        # Required by the clean layer: SCD2 versioning orders on system_modstamp.
        "SystemModstamp",
        "ActivityDate",
        "ActivityDateTime",
        "ActivityMonth",
        "ActivityYear",
        "ActivityDay",
        "ActivityHour",
        "ActivityMinute",
    ],
}
