SELECT
    id AS id_message,
    incremental_id AS id_incremental,
    aggregate_id AS id_aggregate,
    correlation_id AS id_correlation,
    trace_id AS id_trace,
    aggregate_type,
    event_type,
    payload,
    metadata,
    headers,
    status,
    destination,
    last_error,
    provider,
    idempotency_key,
    retry_count,
    locked_by,
    creation_time,
    published != 0 AS is_published,
    TIMESTAMP(created_at) AS ts_created,
    TIMESTAMP(creation_datetime) AS ts_creation,
    TIMESTAMP(failed_at) AS ts_failed,
    TIMESTAMP(next_attempt_at) AS ts_next_attempt,
    TIMESTAMP(locked_at) AS ts_locked,
    TIMESTAMP(lease_until) AS ts_lease_until,
    TIMESTAMP(processed_at) AS ts_processed
FROM
    datalake_nazare_raw.message
