WITH parsed AS (
    SELECT
        BIGINT(`id`) AS id_revenue_share,
        BIGINT(offer_agent_id) AS id_offer_agent,
        BIGINT(offer_partner_id) AS id_offer_partner,
        output AS json_output,
        from_json(
            output,
            'STRUCT<
                `house-id`: BIGINT,
                `brokerage`: DOUBLE,
                `hub-bonus`: DOUBLE,
                `tier-name`: STRING,
                `tqc-bonus`: DOUBLE,
                `sale-price`: DOUBLE,
                `advance-bonus`: DOUBLE,
                `campaign-bonus`: DOUBLE,
                `offer-category`: STRING,
                `participant-id`: STRING,
                `business-unit-id`: INT,
                `participant-role`: STRING,
                `cancellation-date`: STRING,
                `offer-external-id`: STRING,
                `business-unit-name`: STRING,
                `gross-remuneration`: DOUBLE,
                `remuneration-bonus`: DOUBLE,
                `cancellation-reason`: STRING,
                `offer-signature-date`: STRING,
                `participant-paid-fee`: DOUBLE,
                `payment-allowed-date`: STRING,
                `remuneration-baseline`: DOUBLE,
                `supply-acquisition-share`: DOUBLE,
                `forbrokers-model-partner-brokerage-fee`: DOUBLE,
                `quintoandar-model-partner-brokerage-fee`: DOUBLE
            >'
        ) AS json_parsed,
        errors AS json_errors,
        TIMESTAMP(invalidated_at) AS ts_invalidated,
        TIMESTAMP(created_at) AS ts_created
    FROM
        datalake_nazare_raw.revenue_share_by_participant
)
SELECT
    id_revenue_share,
    id_offer_agent,
    id_offer_partner,
    CAST(json_parsed.`house-id` AS BIGINT) AS id_house,
    json_parsed.`participant-id` AS id_participant,
    CAST(json_parsed.`business-unit-id` AS INT) AS id_business_unit,
    json_parsed.`offer-external-id` AS id_offer_external,
    json_parsed.`tier-name` AS tier_name,
    json_parsed.`offer-category` AS offer_category,
    json_parsed.`participant-role` AS participant_role,
    json_parsed.`business-unit-name` AS business_unit_name,
    json_parsed.`cancellation-reason` AS cancellation_reason,
    json_parsed.`brokerage` AS brokerage,
    json_parsed.`hub-bonus` AS hub_bonus,
    json_parsed.`tqc-bonus` AS tqc_bonus,
    json_parsed.`sale-price` AS sale_price,
    json_parsed.`advance-bonus` AS advance_bonus,
    json_parsed.`campaign-bonus` AS campaign_bonus,
    json_parsed.`gross-remuneration` AS gross_remuneration,
    json_parsed.`remuneration-bonus` AS remuneration_bonus,
    json_parsed.`remuneration-baseline` AS remuneration_baseline,
    json_parsed.`participant-paid-fee` AS participant_paid_fee,
    json_parsed.`supply-acquisition-share` AS supply_acquisition_share,
    json_parsed.`forbrokers-model-partner-brokerage-fee` AS forbrokers_model_partner_brokerage_fee,
    json_parsed.`quintoandar-model-partner-brokerage-fee` AS quintoandar_model_partner_brokerage_fee,
    json_parsed.`cancellation-date` AS cancellation_date,
    DATE(json_parsed.`offer-signature-date`) AS dt_offer_signature,
    DATE(json_parsed.`payment-allowed-date`) AS dt_payment_allowed,
    json_output,
    json_errors,
    ts_invalidated,
    ts_created
FROM
    parsed
