SELECT
    BIGINT(`id`) AS id_revenue_share,
    BIGINT(offer_agent_id) AS id_offer_agent,
    BIGINT(offer_partner_id) AS id_offer_partner,
    output AS json_output,
    TO_JSON(NAMED_STRUCT(
        'house-id', GET_JSON_OBJECT(output, '$.house-id'),
        'brokerage', GET_JSON_OBJECT(output, '$.brokerage'),
        'hub-bonus', GET_JSON_OBJECT(output, '$.hub-bonus'),
        'tier-name', GET_JSON_OBJECT(output, '$.tier-name'),
        'tqc-bonus', GET_JSON_OBJECT(output, '$.tqc-bonus'),
        'sale-price', GET_JSON_OBJECT(output, '$.sale-price'),
        'advance-bonus', GET_JSON_OBJECT(output, '$.advance-bonus'),
        'campaign-bonus', GET_JSON_OBJECT(output, '$.campaign-bonus'),
        'offer-category', GET_JSON_OBJECT(output, '$.offer-category'),
        'participant-id', GET_JSON_OBJECT(output, '$.participant-id'),
        'business-unit-id', GET_JSON_OBJECT(output, '$.business-unit-id'),
        'participant-role', GET_JSON_OBJECT(output, '$.participant-role'),
        'cancellation-date', GET_JSON_OBJECT(output, '$.cancellation-date'),
        'offer-external-id', GET_JSON_OBJECT(output, '$.offer-external-id'),
        'business-unit-name', GET_JSON_OBJECT(output, '$.business-unit-name'),
        'gross-remuneration', GET_JSON_OBJECT(output, '$.gross-remuneration'),
        'remuneration-bonus', GET_JSON_OBJECT(output, '$.remuneration-bonus'),
        'cancellation-reason', GET_JSON_OBJECT(output, '$.cancellation-reason'),
        'offer-signature-date', GET_JSON_OBJECT(output, '$.offer-signature-date'),
        'participant-paid-fee', GET_JSON_OBJECT(output, '$.participant-paid-fee'),
        'payment-allowed-date', GET_JSON_OBJECT(output, '$.payment-allowed-date'),
        'remuneration-baseline', GET_JSON_OBJECT(output, '$.remuneration-baseline'),
        'supply-acquisition-share', GET_JSON_OBJECT(output, '$.supply-acquisition-share'),
        'forbrokers-model-partner-brokerage-fee', GET_JSON_OBJECT(output, '$.forbrokers-model-partner-brokerage-fee'),
        'quintoandar-model-partner-brokerage-fee', GET_JSON_OBJECT(output, '$.quintoandar-model-partner-brokerage-fee')
    )) AS json_output_pd,
    errors AS json_errors,
    TIMESTAMP(invalidated_at) AS ts_invalidated,
    TIMESTAMP(created_at) AS ts_created
FROM
    datalake_nazare_raw.revenue_share_by_participant
