WITH parsed AS (
    SELECT
        BIGINT(`id`) AS id_revenue_share,
        BIGINT(offer_agent_id) AS id_offer_agent,
        BIGINT(offer_partner_id) AS id_offer_partner,
        output AS json_output,
        from_json(
            output,
            'STRUCT<
                `house-id`: BIGINT,
                `brokerage`: DOUBLE,
                `hub-bonus`: DOUBLE,
                `tier-name`: STRING,
                `tqc-bonus`: DOUBLE,
                `sale-price`: DOUBLE,
                `advance-bonus`: DOUBLE,
                `campaign-bonus`: DOUBLE,
                `offer-category`: STRING,
                `participant-id`: STRING,
                `business-unit-id`: INT,
                `participant-role`: STRING,
                `cancellation-date`: STRING,
                `offer-external-id`: STRING,
                `business-unit-name`: STRING,
                `gross-remuneration`: DOUBLE,
                `remuneration-bonus`: DOUBLE,
                `cancellation-reason`: STRING,
                `offer-signature-date`: STRING,
                `participant-paid-fee`: DOUBLE,
                `payment-allowed-date`: STRING,
                `remuneration-baseline`: DOUBLE,
                `supply-acquisition-share`: DOUBLE,
                `forbrokers-model-partner-brokerage-fee`: DOUBLE,
                `quintoandar-model-partner-brokerage-fee`: DOUBLE
            >'
        ) AS json_parsed,
        errors AS json_errors,
        TIMESTAMP(invalidated_at) AS ts_invalidated,
        TIMESTAMP(created_at) AS ts_created,
        op_cdc,
        ts_cdc_transaction,
        ts_database_transaction
    FROM
        datalake_nazare_raw.revenue_share_by_participant
)
SELECT
    id_revenue_share,
    id_offer_agent,
    id_offer_partner,
    CAST(get_json_object(json_output, '$.house-id') AS BIGINT) AS id_house,
    get_json_object(json_output, '$.participant-id') AS id_participant,
    CAST(get_json_object(json_output, '$.business-unit-id') AS INT) AS id_business_unit,
    get_json_object(json_output, '$.offer-external-id') AS id_offer_external,
    get_json_object(json_output, '$.tier-name') AS tier_name,
    get_json_object(json_output, '$.offer-category') AS offer_category,
    get_json_object(json_output, '$.participant-role') AS participant_role,
    get_json_object(json_output, '$.business-unit-name') AS business_unit_name,
    get_json_object(json_output, '$.cancellation-reason') AS cancellation_reason,
    CAST(get_json_object(json_output, '$.brokerage') AS DOUBLE) AS brokerage,
    CAST(get_json_object(json_output, '$.hub-bonus') AS DOUBLE) AS hub_bonus,
    CAST(get_json_object(json_output, '$.tqc-bonus') AS DOUBLE) AS tqc_bonus,
    CAST(get_json_object(json_output, '$.sale-price') AS DOUBLE) AS sale_price,
    CAST(get_json_object(json_output, '$.advance-bonus') AS DOUBLE) AS advance_bonus,
    CAST(get_json_object(json_output, '$.campaign-bonus') AS DOUBLE) AS campaign_bonus,
    CAST(get_json_object(json_output, '$.gross-remuneration') AS DOUBLE) AS gross_remuneration,
    CAST(get_json_object(json_output, '$.remuneration-bonus') AS DOUBLE) AS remuneration_bonus,
    CAST(get_json_object(json_output, '$.remuneration-baseline') AS DOUBLE) AS remuneration_baseline,
    CAST(get_json_object(json_output, '$.participant-paid-fee') AS DOUBLE) AS participant_paid_fee,
    CAST(get_json_object(json_output, '$.supply-acquisition-share') AS DOUBLE) AS supply_acquisition_share,
    CAST(get_json_object(json_output, '$.forbrokers-model-partner-brokerage-fee') AS DOUBLE) AS forbrokers_model_partner_brokerage_fee,
    CAST(get_json_object(json_output, '$.quintoandar-model-partner-brokerage-fee') AS DOUBLE) AS quintoandar_model_partner_brokerage_fee,
    DATE(get_json_object(json_output, '$.cancellation-date')) AS dt_cancellation_date,
    DATE(get_json_object(json_output, '$.offer-signature-date')) AS dt_offer_signature,
    DATE(get_json_object(json_output, '$.payment-allowed-date')) AS dt_payment_allowed,
    json_output,
    json_errors,
    ts_invalidated,
    ts_created,
    op_cdc,
    ts_cdc_transaction,
    ts_database_transaction
FROM
    parsed
