SELECT
    CAST(amplitude_id AS BIGINT) AS id_amplitude,
    CAST(amplitude_attribution_ids AS ARRAY<STRING>) AS ids_amplitude_attributed,
    CAST(adid AS STRING) AS adid,
    CAST(amplitude_event_type AS STRING) AS amplitude_event_type,
    CAST(app AS BIGINT) AS id_app,
    CAST(city AS STRING) AS city,
    CAST(client_event_time AS TIMESTAMP) AS ts_client_event,
    CAST(client_upload_time AS TIMESTAMP) AS ts_client_uploaded,
    CAST(country AS STRING) AS country,
    CAST(data AS STRING) AS data,
    CAST(server_received_time AS TIMESTAMP) AS ts_server_received,
    CAST(device_brand AS STRING) AS device_brand,
    CAST(device_carrier AS STRING) AS device_carrier,
    CAST(device_family AS STRING) AS device_family,
    CAST(device_id AS STRING) AS id_device,
    CAST(device_manufacturer AS STRING) AS device_manufacturer,
    CAST(device_model AS STRING) AS device_model,
    CAST(device_type AS STRING) AS device_type,
    CAST(dma AS STRING) AS dma,
    CAST(event_id AS BIGINT) AS id_event,
    CAST(event_time AS TIMESTAMP) AS ts_event,
    CAST(event_type AS STRING) AS event_type,
    CAST(event_properties AS STRING) AS event_properties,
    CAST(is_attribution_event AS BOOLEAN) AS is_attribution_event,
    CAST(idfa AS STRING) AS idfa,
    CAST(ip_address AS STRING) AS ip_address,
    CAST(location_lat AS STRING) AS location_lat,
    CAST(location_lng AS STRING) AS location_lng,
    CAST(os_name AS STRING) AS os_name,
    CAST(os_version AS STRING) AS os_version,
    CAST(platform AS STRING) AS platform,
    CAST(library AS STRING) AS library,
    CAST(paying AS BOOLEAN) AS is_paying,
    CAST(region AS STRING) AS region,
    CAST(server_upload_time AS TIMESTAMP) AS ts_server_uploaded,
    CAST(session_id AS BIGINT) AS id_session,
    CAST(start_version AS STRING) AS start_version,
    CAST(user_creation_time AS TIMESTAMP) AS ts_user_created,
    CAST(user_id AS STRING) AS id_user,
    CAST(user_properties AS STRING) AS user_properties,
    CAST(language AS STRING) AS language,
    CAST(uuid AS STRING) AS uuid,
    CAST(version_name AS STRING) AS version_name,
    CAST(schema AS BIGINT) AS id_schema,
    CAST(processed_time AS TIMESTAMP) AS ts_processed,
    CAST(insert_id AS STRING) AS id_inserted,
    CAST(sample_rate AS STRING) AS sample_rate,
    CAST(year AS INT) AS year,
    CAST(month AS INT) AS month,
    CAST(day AS INT) AS day
FROM
    datalake_amplitude_new_raw.events
WHERE
    MAKE_DATE(year, month, day) BETWEEN '{load_start_date}' AND '{load_end_date}'
