DROP TABLE IF EXISTS staging.dim_property;
CREATE TABLE staging.dim_property (
  sk_property bigint NOT NULL,
  id BIGINT DEFAULT -1::bigint,
  version integer,
  min_version_time timestamp,
  max_version_time timestamp,
  last_status_version varchar(50),
  aluguel INTEGER,
  bairro VARCHAR(200) DEFAULT NULL::character varying,
  cep VARCHAR(200) DEFAULT NULL::character varying,
  cidade VARCHAR(200) DEFAULT NULL::character varying,
  complemento VARCHAR(200) DEFAULT NULL::character varying,
  condominio INTEGER,
  data_construcao VARCHAR(255) DEFAULT NULL::character varying,
  elevador SMALLINT,
  email_contato VARCHAR(200) DEFAULT NULL::character varying,
  email_sessao_fotos VARCHAR(200) DEFAULT NULL::character varying,
  endereco VARCHAR(200) DEFAULT NULL::character varying,
  estado_conservacao VARCHAR(255) DEFAULT NULL::character varying,
  fotografo_preenche_dados INTEGER,
  iptu INTEGER,
  lat NUMERIC(10,7) DEFAULT NULL::numeric::numeric(18,0),
  lng NUMERIC(10,7) DEFAULT NULL::numeric::numeric(18,0),
  mobiliado INTEGER,
  nivel_acabamento VARCHAR(255) DEFAULT NULL::character varying,
  numero VARCHAR(200) DEFAULT NULL::character varying,
  numero_banheiros INTEGER,
  numero_quartos INTEGER,
  numero_suites INTEGER,
  numero_vagas INTEGER,
  porcentagem_cadastro_completa INTEGER,
  prefere_email_sessao_fotos INTEGER,
  status VARCHAR(255) DEFAULT NULL::character varying,
  tel_contato1 VARCHAR(20) DEFAULT NULL::character varying,
  tel_contato2 VARCHAR(20) DEFAULT NULL::character varying,
  tel_sessao_fotos VARCHAR(20) DEFAULT NULL::character varying,
  tipo VARCHAR(255) DEFAULT NULL::character varying,
  tipo_porteiro VARCHAR(255) DEFAULT NULL::character varying,
  tipo_vagas VARCHAR(255) DEFAULT NULL::character varying,
  verificado INTEGER,
  usuario_id BIGINT,
  codigo_promocao VARCHAR(50) DEFAULT NULL::character varying,
  cotar_seguro SMALLINT,
  valor_total INTEGER,
  expiration_date TIMESTAMP WITHOUT TIME ZONE,
  notificacao_anuncio_incompleto_proprietario SMALLINT,
  notificacao_anuncio_incompleto_admin SMALLINT,
  short_url VARCHAR(64) DEFAULT NULL::character varying,
  valor_seguro INTEGER,
  plano_aceito VARCHAR(255) DEFAULT NULL::character varying,
  sugerir_reajuste_de_preco INTEGER,
  permite_placa_aluga_se INTEGER,
  prioridade_destaque_classificado INTEGER,
  dados_administradora_condominio VARCHAR(200) DEFAULT NULL::character varying,
  condominio_incluso INTEGER,
  coordenadas_manuais INTEGER,
  iptu_incluso INTEGER,
  followup_proprietario_subir_fotos INTEGER,
  data_primeiro_verificado TIMESTAMP WITHOUT TIME ZONE,
  tipo_colisao_lead VARCHAR(255) DEFAULT NULL::character varying,
  calculo_pagamento_lead_corretor TIMESTAMP WITHOUT TIME ZONE,
  nome_imagem_capa VARCHAR(200) DEFAULT NULL::character varying,
  geo_hash VARCHAR(16) DEFAULT NULL::character varying,
  tipo_anuncio VARCHAR(255) DEFAULT NULL::character varying,
  calculo_pagamento_lead_afiliado TIMESTAMP WITHOUT TIME ZONE,
  possui_banheiro_servico INTEGER,
  possui_quarto_servico INTEGER,
  bairro_padrao VARCHAR(200) DEFAULT NULL::character varying,
  tipo_condominio VARCHAR(255) DEFAULT NULL::character varying,
  tipo_iptu VARCHAR(255) DEFAULT NULL::character varying,
  disponivel_ate DATE,
  flag_verificar_preco_comparando_com_media INTEGER,
  sempre_consultar_proprietario_visita SMALLINT,
  email_publicacao_proprietario_enviado INTEGER,
  status_conversao_imovel VARCHAR(255) DEFAULT NULL::character varying,
  ultimo_email_de_confirmacao_enviado TIMESTAMP WITHOUT TIME ZONE,
  latlng VARCHAR(256),
  ultimo_update_indice TIMESTAMP WITHOUT TIME ZONE,
  suspenso_ate TIMESTAMP WITHOUT TIME ZONE,
  external_id VARCHAR(255) DEFAULT NULL::character varying,
  em_negociacao SMALLINT,
  em_negociacao_externa SMALLINT,
  entrou_em_negociacao_externa TIMESTAMP WITHOUT TIME ZONE,
  motivo_recusa_cardiff VARCHAR(256),
  recaptado_em TIMESTAMP WITHOUT TIME ZONE,
  job_fotografo_pendente SMALLINT,
  requisitou_fotos_profissionais SMALLINT,
  last_confirmation_availability TIMESTAMP WITHOUT TIME ZONE,
  cartorio VARCHAR(255) DEFAULT NULL::character varying,
  penalization_score INTEGER,
  receber_copia_contrato_padrao SMALLINT,
  rank_score INTEGER,
  ultima_publicacao TIMESTAMP WITHOUT TIME ZONE,
  confirmado_informacoes_visita INTEGER,
  estado_abreviacao VARCHAR(200) DEFAULT NULL::character varying,
  estado_nome VARCHAR(200) DEFAULT NULL::character varying,
  regiao_cidade VARCHAR(200) DEFAULT NULL::character varying,
  regiao_macro VARCHAR(200) DEFAULT NULL::character varying,
  regiao_sub VARCHAR(200) DEFAULT NULL::character varying,
  regiao_id INTEGER,
  condominio_nome VARCHAR(200) DEFAULT NULL::character varying,
  local_nome VARCHAR(255),
  first_publication TIMESTAMP WITHOUT TIME ZONE,
  publication_date TIMESTAMP WITHOUT TIME ZONE,
  de_publication_date TIMESTAMP WITHOUT TIME ZONE,
  time_first_listing_to_contract_signed integer,
  time_listing_to_depublication integer,
  nr_listing integer,
  nr_renting integer,
  info_visita_autorizacao_de_entrada integer,
  info_visita_proprietario_acompanha integer,
  info_visita_estamos_liberados integer,
  info_visita_prop_precisa_liberar integer,
  info_visita_chave_box_quintoandar integer,
  data_criacao TIMESTAMP WITHOUT TIME ZONE,
  atualizado_em TIMESTAMP WITHOUT TIME ZONE,
  load_timestamp TIMESTAMP WITHOUT TIME ZONE,
  usuario_que_cadastrou_id INTEGER,
  property_v3 INTEGER,
  total_area INTEGER,
  construction_area INTEGER,
  unpublished_reason VARCHAR(255),
  start_version_category varchar(255),
  end_version_category varchar(255),
  is_last_status INTEGER,
  exclusivity smallint,
  short_id INTEGER DEFAULT -1::INTEGER,
  CONSTRAINT dim_property_pkey PRIMARY KEY(sk_property)
) WITH OIDS;
