SELECT
  id,
  rev,
  revtype AS rev_type,
  revend AS rev_end,
  credit_proposal_reference_id AS id_credit_proposal_reference,
  analyst_reference_id AS id_analyst_reference,
  uuid AS uuid_credit_proposal_crawler_job,
  crawler_type AS crawler_type_name,
  state AS state_name,
  failure_reason,
  failure_category,
  step_failure,
  step_section_failure,
  retry_count,
  fields_filled,
  version,
  credit_proposal_reference_id_mod AS mod_id_credit_proposal_reference,
  analyst_reference_id_mod AS mod_id_analyst_reference,
  uuid_mod AS mod_uuid_credit_proposal_crawler_job,
  crawler_type_mod AS mod_crawler_type_name,
  state_mod AS mod_state_name,
  failure_reason_mod AS mod_failure_reason,
  failure_category_mod AS mod_failure_category,
  step_failure_mod AS mod_step_failure,
  step_section_failure_mod AS mod_step_section_failure,
  retry_count_mod AS mod_retry_count,
  fields_filled_mod AS mod_fields_filled,
  version_mod AS mod_version,
  created_at_mod AS mod_ts_created,
  updated_at_mod AS mod_ts_updated,
  created_at AS ts_created,
  updated_at AS ts_updated,
  year,
  month,
  day
FROM
  datalake_mortgage_management_service_raw.credit_proposal_crawler_job_aud
