SELECT
  id,
  rev,
  revtype AS rev_type,
  revend AS rev_end,
  mortgage_intention_uuid AS uuid_mortgage_intention,
  person_uuid AS uuid_person,
  source AS source_name,
  status AS status_name,
  mortgage_rules_country AS mortgage_rules_country_code,
  canceled_reason AS cancellation_reason,
  mortgage_term,
  expenses_amount,
  savings_amount,
  will_finance_expenses AS is_will_finance_expenses,
  will_use_savings AS is_will_use_savings,
  version,
  mortgage_intention_uuid_mod AS mod_uuid_mortgage_intention,
  person_uuid_mod AS mod_uuid_person,
  source_mod AS mod_source_name,
  status_mod AS mod_status_name,
  mortgage_rules_country_mod AS mod_mortgage_rules_country_code,
  canceled_reason_mod AS mod_cancellation_reason,
  mortgage_term_mod AS mod_mortgage_term,
  expenses_amount_mod AS mod_expenses_amount,
  savings_amount_mod AS mod_savings_amount,
  will_finance_expenses_mod AS mod_is_will_finance_expenses,
  will_use_savings_mod AS mod_is_will_use_savings,
  version_mod AS mod_version,
  canceled_at_mod AS mod_ts_canceled,
  created_at_mod AS mod_ts_created,
  updated_at_mod AS mod_ts_updated,
  canceled_at AS ts_canceled,
  created_at AS ts_created,
  updated_at AS ts_updated,
  year,
  month,
  day
FROM
  datalake_mortgage_management_service_raw.mortgage_intention_aud
