SELECT
  id,
  rev,
  revtype AS rev_type,
  revend AS rev_end,
  mortgage_intention_id AS id_mortgage_intention,
  source AS source_name,
  currency AS currency_code,
  event_source_id AS event_source_reference_id,
  financed_amount,
  down_payment,
  property_value,
  version,
  mortgage_intention_id_mod AS mod_id_mortgage_intention,
  source_mod AS mod_source_name,
  currency_mod AS mod_currency_code,
  event_source_id_mod AS mod_event_source_reference_id,
  financed_amount_mod AS mod_financed_amount,
  down_payment_mod AS mod_down_payment,
  property_value_mod AS mod_property_value,
  version_mod AS mod_version,
  created_at_mod AS mod_ts_created,
  updated_at_mod AS mod_ts_updated,
  created_at AS ts_created,
  updated_at AS ts_updated,
  year,
  month,
  day
FROM
  datalake_mortgage_management_service_raw.mortgage_intention_amounts_aud
