# Merge Keys are available only in Yaml 1.1.
redshift_template:
  dw: &redshift_anchor
    schema: datamarts
    runs_on: redshift
athena_template:
  dw: &athena_anchor
    schema: datamarts
    runs_on: athena
pipeline:
  ##<KEEP THIS COMMENTED AS A TEMPLATE>
  # <task-name-like-attribution-conversion-paths>:
  #   dw:
  #     sql_file: <query-file E.g: dw/queries/datamarts/offer_attribution_conversion_paths_demand.sql>
  #     table: <targe-table-name>
  #     schema: <target-schema-name> # TODO this will always be `datamart` (for both datalake and dw). This var is not used anymore
  #     runs_on: <backend-to-run-the-query> E.g: redshift or athena
  weekly_demand_metrics:
    dw:
      <<: *redshift_anchor
      sql_file: dw/queries/datamarts/for_rent/weekly_demand_metrics.sql
      table: weekly_demand_metrics
  house_weekly_entrance_info:
    dw:
      <<: *athena_anchor
      sql_file: dw/queries/datamarts/for_rent/house_weekly_entrance_info.sql
      table: house_weekly_entrance_info
  talk_to_agent:
    dw:
      <<: *athena_anchor
      sql_file: dw/queries/datamarts/for_rent/talk_to_agent.sql
      table: talk_to_agent
  funnel_demand_flows:
    dw:
      <<: *redshift_anchor
      sql_file: dw/queries/datamarts/for_rent/funnel_demand_flows.sql
      table: funnel_demand_flows
      depends_on:
        - talk_to_agent
  datamart_opportunity:
    dw:
      <<: *redshift_anchor
      sql_file: dw/queries/datamarts/for_rent/datamart_opportunity.sql
      table: datamart_opportunity
  quintoandar_consultant_listings:
    dw:
      <<: *redshift_anchor
      sql_file: dw/queries/datamarts/for_rent/quintoandar_consultant_listings.sql
      table: quintoandar_consultant_listings
  repressed_demand:
    dw:
      <<: *athena_anchor
      sql_file: dw/queries/datamarts/for_rent/repressed_demand.sql
      table: repressed_demand
  credit_proposal_attribute:
    dw:
      <<: *redshift_anchor
      sql_file: dw/queries/datamarts/for_rent/credit_proposal_attribute.sql
      table: credit_proposal_attribute
  funnel_credit_event_flows:
    dw:
      <<: *redshift_anchor
      sql_file: dw/queries/datamarts/for_rent/funnel_credit_event_flows.sql
      table: funnel_credit_event_flows
  funnel_weekly_credit_user_flow:
    dw:
      <<: *redshift_anchor
      sql_file: dw/queries/datamarts/for_rent/funnel_weekly_credit_user_flow.sql
      table: funnel_weekly_credit_user_flow
      depends_on:
        - funnel_demand_flows
  funnel_monthly_credit_user_flow:
    dw:
      <<: *redshift_anchor
      sql_file: dw/queries/datamarts/for_rent/funnel_monthly_credit_user_flow.sql
      table: funnel_monthly_credit_user_flow
      depends_on:
        - funnel_demand_flows
  lead_listing_flows:
    dw:
      <<: *redshift_anchor
      sql_file: dw/queries/datamarts/for_rent/lead_listing_flows.sql
      table: lead_listing_flows
      depends_on:
        - quintoandar_consultant_listings