DROP TABLE IF EXISTS customer_support.fact_ticket;
CREATE TABLE IF NOT EXISTS customer_support.fact_ticket (
    sk_ticket BIGINT,
    sk_taxonomy VARCHAR(40),
    sk_tags VARCHAR(40),
    sk_channel VARCHAR(40),
    sk_first_agent VARCHAR(40),
    sk_last_agent VARCHAR(40),
    sk_first_department VARCHAR(40),
    sk_main_department VARCHAR(40),
    sk_user BIGINT,
    sk_contract BIGINT,
    sk_main_session BIGINT,
    channel VARCHAR(5),
    csat_score INTEGER,
    status VARCHAR(20),
    first_department VARCHAR(100),
    main_department VARCHAR(100),
    total_departments INTEGER,
    total_segments INTEGER,
    full_resolution_time DOUBLE PRECISION,
    front_or_back VARCHAR(10),
    last_back_ticket BIGINT,
    back_tickets VARCHAR(1500),
    resolution_survey BOOLEAN,
    has_answered_csat BOOLEAN,
    has_back_ticket BOOLEAN,
    is_back_ticket_open BOOLEAN,
    is_solved BOOLEAN,
    is_fcr BOOLEAN,
    is_ticket_session BOOLEAN,
    is_fcr_customer BOOLEAN,
    is_recontact BOOLEAN,
    has_transfers BOOLEAN,
    total_minutes_reception_time FLOAT,
    total_minutes_talk_time FLOAT,
    total_minutes_queue_time FLOAT,
    total_minutes_wrap_up_time FLOAT,
    total_minutes_handling_time FLOAT,
    total_backoffice_minutes_time FLOAT,
    total_minutes_front_to_open_back_ticket_time FLOAT,
    ts_started TIMESTAMP,
    ts_closed TIMESTAMP,
    ts_solved TIMESTAMP,
    ts_load TIMESTAMP
);
ALTER TABLE customer_support.fact_ticket OWNER TO airflow;
