---
tables:
  address_data:
    extraction_type: incremental
  address_data_aud:
    extraction_type: incremental
  brokerage:
    extraction_type: incremental
  brokerage_aud:
    extraction_type: incremental
  buyer_data:
    extraction_type: incremental
  buyer_data_aud:
    extraction_type: incremental
  bypass:
    extraction_type: incremental
  bypass_aud:
    extraction_type: incremental
  card_noting:
    extraction_type: incremental
  card_noting_aud:
    extraction_type: incremental
  cash_payment:
    extraction_type: incremental
  cash_payment_aud:
    extraction_type: incremental
  ccv:
    extraction_type: incremental
  ccv_aud:
    extraction_type: incremental
  ccv_clause:
    extraction_type: incremental
  ccv_edition_reason:
    extraction_type: incremental
  ccv_edition_reason_aud:
    extraction_type: incremental
  ccv_termination:
    extraction_type: incremental
  clause_message:
    extraction_type: incremental
  closing_type:
    extraction_type: incremental
  closing_type_aud:
    extraction_type: incremental
  ccv_flow:
    extraction_type: incremental
  ccv_flow_aud:
    extraction_type: incremental
  ccv_party:
    extraction_type: incremental
  ccv_party_aud:
    extraction_type: incremental
  ccv_rule:
    extraction_type: incremental
  ccv_rule_aud:
    extraction_type: incremental
  contact:
    extraction_type: incremental
  contact_aud:
    extraction_type: incremental
  diligence:
    extraction_type: incremental
  diligence_aud:
    extraction_type: incremental
  diligence_appointment:
    extraction_type: incremental
  diligence_appointment_aud:
    extraction_type: incremental
  house:
    extraction_type: incremental
  house_aud:
    extraction_type: incremental
  house_registration_order:
    extraction_type: incremental
  house_registration_order_aud:
    extraction_type: incremental
  microstatus_order:
    extraction_type: incremental
  microstatus_order_aud:
    extraction_type: incremental
  mortgage:
    extraction_type: incremental
  mortgage_aud:
    extraction_type: incremental
  negotiation:
    extraction_type: incremental
  negotiation_aud:
    extraction_type: incremental
  notary:
    extraction_type: incremental
  notary_aud:
    extraction_type: incremental
  offer:
    extraction_type: incremental
  offer_aud:
    extraction_type: incremental
  payment:
    extraction_type: incremental
  payment_aud:
    extraction_type: incremental
  reject_reason:
    extraction_type: incremental
  reject_reason_aud:
    extraction_type: incremental
  revinfo:
    clean_table_name: rev_info
    extraction_type: incremental
    unixtime_measure: milliseconds
    date_filter_column: timestamp
  sales_flow:
    extraction_type: incremental
  sales_flow_aud:
    extraction_type: incremental
  sales_flow_contact:
    extraction_type: full
  sales_flow_contact_aud:
    extraction_type: incremental
  sales_flow_details:
    extraction_type: incremental
  sales_flow_details_aud:
    extraction_type: incremental
  sales_flow_invite:
    extraction_type: incremental
  sales_flow_invite_aud:
    extraction_type: incremental
  sales_flow_pendency:
    extraction_type: incremental
  sales_flow_pendency_aud:
    extraction_type: incremental
  sales_flow_tag:
    extraction_type: full
  sales_flow_tag_aud:
    extraction_type: incremental
  sales_flow_users:
    extraction_type: full
  sales_flow_users_aud:
    extraction_type: incremental
  screening_seller:
    extraction_type: incremental
  seller_data:
    extraction_type: incremental
  seller_data_aud:
    extraction_type: incremental
  seller_documentation:
    extraction_type: incremental
  seller_documentation_aud:
    extraction_type: incremental
  specialist:
    extraction_type: full
  specialist_aud:
    extraction_type: incremental
  status:
    extraction_type: incremental
  status_aud:
    extraction_type: incremental
  status_order:
    extraction_type: incremental
  status_order_aud:
    extraction_type: incremental
  status_record:
    extraction_type: incremental
  status_record_aud:
    extraction_type: incremental
  subtask:
    extraction_type: incremental
  tag:
    extraction_type: incremental
  tag_aud:
    extraction_type: incremental
  task:
    extraction_type: incremental
  task_association:
    extraction_type: incremental
  user_sample:
    extraction_type: incremental
  user_sample_aud:
    extraction_type: incremental
  users:
    extraction_type: incremental
  users_aud:
    extraction_type: incremental
partition_cols: ["year", "month", "day"]
