SELECT  
  id,
  external_offer_id AS id_external_offer,
  state_external_id AS id_state_external,
  house_id AS id_house,
  CAST(down_payment_amount AS DECIMAL(20,2)) AS down_payment_amount,
  CAST(entry_payment_amount AS DECIMAL(20,2)) AS entry_payment_amount,
  CAST(fgts_amount AS DECIMAL(20,2)) AS fgts_amount,
  CAST(financed_amount AS DECIMAL(20,2)) AS financed_amount,
  CAST(total_payment_amount AS DECIMAL(20,2)) AS total_payment_amount,
  CAST(brokerage_fee AS DECIMAL(10,5)) AS brokerage_fee,
  CAST(brokerage_quintoandar_fee AS DECIMAL(12,10)) AS brokerage_quintoandar_fee,
  CAST(brokerage_estate_agent_fee AS DECIMAL(12,10)) AS brokerage_estate_agent_fee,
  CAST(cash_payment_amount AS DECIMAL(20,2)) AS cash_payment_amount,
  revision,
  ledger_rule,
  category,
  payment_method,
  payment_model,
  address,
  house_number,
  complement,
  neighbourhood,
  city,
  postal_code,
  status,
  drive_folder,
  updated_by,
  cancellation_reason,
  errors,
  TIMESTAMP(event_date_time) AS ts_event,
  DATE(notary_start_date) AS dt_notary_start,
  TIMESTAMP(payment_allowed_at) AS ts_payment_allowed,
  DATE(revenue_share_calculated_at) AS dt_revenue_share_calculated,
  DATE(nf_scheduled_to) AS dt_nf_scheduled_to,
  DATE(signature_date) AS dt_signature,
  TIMESTAMP(created_at) AS ts_created,
  TIMESTAMP(cancelled_at) AS ts_cancelled
FROM 
  datalake_monopoly_raw.sale_revision