SELECT
    id,
    id_house as house_id,
    date(ts_analyzed) as analysis_date,
    score_5A,
    score_5A_best_subset,
    score_cardif,
    score_cardif_best_subset,
    status,
    comment,
    analyst_name,
    supervisor_name,
    rent_value,
    condo_value,
    iptu_value,
    date(ts_created) as created_at,
    date(ts_updated) as updated_at,
    home_area,
    home_bathrooms,
    home_city,
    home_garages,
    home_region,
    home_suites,
    home_type,
    home_zipcode,
    id_drive,
    reason,
    home_insurance_value,
    risk_level,
    risk_level_best_subset,
    date(dt_processed) as process_date,
    is_home_exclusive_5A as home_exclusive_5A,
    ts_home_last_published as dt_home_last_published,
    has_bypassed_pre_analysis as bypass_pre_analysis,
    pre_analysis_result,
    pre_analysis_reason
FROM datalake_sorting_hat_clean_prod.proposal proposal