SELECT
    id,
    name,
    cpf,
    income_nature,
    marital_status,
    gender,
    date(dt_admitted) as admission_date,
    cell_phone,
    phone,
    email,
    monthly_income,
    is_going_to_reside as will_reside,
    location_motive,
    second_doc_type,
    second_doc_number,
    second_doc_issuer,
    dt_second_doc_issued,
    nationality,
    dt_birthday as birthday,
    mother_name,
    zipcode,
    address,
    address_number,
    complement,
    neighborhood,
    city,
    state,
    residence_condition,
    residence_time,
    profession,
    employer_name,
    employer_phone,
    extra_income_origin,
    extra_income_value,
    id_proposal as proposal_id,
    boavista_score,
    serasa_score,
    id_screening_result
FROM datalake_sorting_hat_clean_prod.proponent proponent