SELECT
    email AS employee_email,
    name AS employee_name,
    registration AS employee_registration,
    personal_email AS employee_personal_email,
    company_grade,
    happiness_grade,
    happiness_reason,
    time_under_leadership AS current_leadership_time,
    period_1on1 AS frequency_one_one,
    healthy_leadership_relation,
    healthy_team_relation,
    my_work_was_recognized AS work_was_recognized,
    applied_knowledge,
    opportunity_and_development_satisfaction AS development_satisfaction,
    had_onboarding_support,
    high_stress_level,
    stress_influence,
    had_available_channels,
    felt_comfortable_with_my_leadership,
    comments_about_leadership_support,
    have_a_new_job AS has_new_job,
    compensation_was_a_factor AS is_compensation_factor,
    main_reason_for_exit AS reason_exit,
    additional_comments,
    directory AS employee_director,
    vertical AS employee_vertical,
    function AS employee_function,
    new_company_name AS employee_new_company,
    ts_load
FROM datalake_gsheets_people_raw.dismissal_forms_voluntary