SELECT 
    id AS id_employee,
    supervisorid AS id_supervisor,
    marital_status_id AS id_marital_status,
    job_id AS id_job,
    bank_id AS id_bank,
    registration AS registration,
    documentcpf AS document_cpf,
    documentrg AS document_rg,
    documentpis AS document_pis,
    company,
    name,
    last_name,
    email,
    alternative_email,
    status,
    motive,
    phone,
    cellphone,
    gender,
    natural_from_state_uf,
    natural_from_city_name,
    first_job AS first_job,
    gender_identityname AS gender_identity_name,
    relationshipname AS relationship_name,
    ethnicityname AS ethnicity_name,
    departmentname AS department_name,
    jobname AS job_name,
    supervisorname AS supervisor_name,
    supervisorlast_name AS supervisor_last_name,
    cost_centername AS cost_center_name,
    address AS address,
    addressnumber AS address_number,
    addresscomplement AS address_complement,
    addresszip_code AS address_zip_code,
    addressstate AS address_state,
    addresscity AS address_city,
    addressdistrict AS address_district,
    experience_periodname AS experience_period_name,
    experience_periodfirst_end AS experience_period_first_end,
    experience_periodsecond_end AS experience_period_second_end,
    experience_periodtotal_days AS experience_period_total_days,
    educational_level,
    course AS course,
    institution AS institution,
    graduation_year,
    banda AS band,
    trilha AS career_track,
    gender_identity AS gender_identity,
    sexual_orientation AS sexual_orientation,
    religiousness,
    neurodiversity,
    disability_type,
    social_name,
    mother_name,
    father_name,
    rg_expedition_date,
    rg_emission,
    rg_uf,
    ctps,
    ctps_uf,
    voter_card,
    voter_card_zone,
    voter_card_section,
    salary,
    utiliza_vt AS is_using_vt,
    recebe_adiantamento AS has_advance_payment,
    plano_odonto AS dental_plan,
    dependentes_plano AS plan_dependents,
    experience_period AS experience_period,
    bank_name,
    account_number,
    account_agency,
    account_digit,
    account_type_id,
    account_type_name,
    benvi_pt_onboarding,
    dismissal_date AS dt_dismissal,
    hiring_date AS dt_hiring,
    birth_date AS dt_birth,
    ctps_emission_date AS dt_ctps_emission,
    ts_load
FROM datalake_gsheets_people_raw.pre_full_merge_dismissals