SELECT
    id AS id_employee,
    name AS name,
    last_name AS last_name,
    registration AS registration,
    email AS email,
    status AS status,
    registro AS contract_type,
    departamento AS department,
    cargo AS office,
    centro_de_custo AS cost_center,
    motivo AS reason,
    descricao AS description,
    company AS company,
    salary AS salary,
    esta_ativo AS is_active,
    date_from AS dt_from,
    date_to AS dt_to,
    ts_load
FROM datalake_gsheets_people_raw.pre_full_merge_dismissals_salaries