SELECT
    Id AS id,
    OwnerId AS id_owner,
    CreatedById AS id_created_by,
    LastModifiedById AS id_last_modified_by,
    Pais__c AS id_country,
    Id_de_portal__c AS id_portal,
    Id_SAP__c AS external_sap_id,
    Id_unidad_de_negocio_Pardot__c AS external_pardot_business_unit_id,
    Name AS sales_organization_name,
    Organizacion_de_venta__c AS custom_sales_organization_name,
    CRM_Navent__c AS crm_navent_name,
    Vertical__c AS vertical_name,
    Portal__c AS portal_name,
    Perfil_crediticio__c AS credit_profile_name,
    Moneda_base__c AS base_currency,
    Monedas_aceptadas__c AS accepted_currencies,
    Vias_de_pago_aceptadas__c AS accepted_payment_methods,
    Descuentos_permitidos__c AS allowed_discounts,
    Duracion_descuentos__c AS discount_duration,
    Emails_envio_OS__c AS service_order_notification_emails,
    CurrencyIsoCode AS currency_iso_code,
    IsDeleted AS is_deleted,
    Campana_oblig_en_Oport__c AS is_campaign_mandatory_in_opportunity,
    Carga_Id_empresa_manual__c AS is_manual_company_id_upload_enabled,
    Renovacion_automatica_de_oportunidades__c AS is_opportunity_auto_renewal_enabled,
    Sincroniza_con_pardot__c AS is_pardot_sync_enabled,
    LastActivityDate AS dt_last_activity,
    CreatedDate AS ts_created,
    LastModifiedDate AS ts_last_modified,
    SystemModstamp AS ts_system_mod,
    LastViewedDate AS ts_last_viewed,
    LastReferencedDate AS ts_last_referenced,
    CAST(LastModifiedDate AS DATE) AS dt_updated,
    YEAR(LastModifiedDate) AS year,
    MONTH(LastModifiedDate) AS month,
    DAY(LastModifiedDate) AS day
FROM
    datalake_salesforce_classifieds_raw.organizacion_de_venta__c
WHERE
    MAKE_DATE(year, month, day) BETWEEN DATE('{load_start_date}') AND DATE('{load_end_date}')
