SELECT
    CAST(sk_user AS INTEGER) AS id_user,
    type,
    cluster,
    segment,
    CAST(recency AS INTEGER) AS recency,
    CAST(REPLACE(frequency,',','') AS FLOAT) AS frequency,
    CAST(soft_lead_last_month AS INTEGER) AS soft_lead_last_month,
    CAST(soft_lead_last_three_months AS INTEGER) AS soft_lead_last_three_months,
    CAST(total_soft_lead AS INTEGER) AS total_soft_lead,
    CAST(lead_last_month AS INTEGER) AS lead_last_month,
    CAST(lead_last_three_months AS INTEGER) AS lead_last_three_months,
    CAST(lead_last_six_months AS INTEGER) AS lead_last_six_months,
    CAST(lead_last_twelve_months AS INTEGER) AS lead_last_twelve_months,
    CAST(total_lead AS INTEGER) AS total_lead,
    CAST(qualified_last_month AS INTEGER) AS qualified_last_month,
    CAST(qualified_last_three_months AS INTEGER) AS qualified_last_three_months,
    CAST(qualified_last_six_months AS INTEGER) AS qualified_last_six_months,
    CAST(qualified_last_twelve_months AS INTEGER) AS qualified_last_twelve_months,
    CAST(total_qualified AS INTEGER) AS total_qualified,
    CAST(REPLACE(l2q_lm,',','') AS FLOAT) AS l2q_lm,
    CAST(REPLACE(l2q_l3m,',','') AS FLOAT) AS l2q_l3m,
    CAST(REPLACE(l2q_l6m,',','') AS FLOAT) AS l2q_l6m,
    CAST(REPLACE(l2q_l12m,',','') AS FLOAT) AS l2q_l12m,
    CAST(REPLACE(l2q_total,',','') AS FLOAT) AS l2q_total,
    CAST(RecencyScore AS INTEGER) AS recency_score,
    CAST(FrequencyScore AS INTEGER) AS frequency_score,
    CAST(ValueScore AS INTEGER) AS value_score,
    rfm,
    CAST(date_joined_program AS DATE) AS dt_joined_program,
    CAST(month_joined_program AS DATE) AS dt_month_joined_program
FROM
    datalake_gsheets_raw.affiliates_active_segmentation