SELECT
    NULLIF(usuario, '') AS user_name,
    NULLIF(perfil, '') AS profile,
    NULLIF(tipo, '') AS type,
    NULLIF(canal, '') AS channel,
    NULLIF(canal_1, '') AS channel_1,
    NULLIF(tipo_do_canal, '') AS channel_type,
    NULLIF(instancia, '') AS instance,
    NULLIF(contato, '') AS contact_name,
    CAST(NULLIF(numero_do_contato, '') AS STRING) AS contact_phone,
    NULLIF(status, '') AS status,
    NULLIF(status_1, '') AS status_1,
    NULLIF(template, '') AS template,
    NULLIF(tabulacao, '') AS tabulation,
    NULLIF(comentario, '') AS comment,
    NULLIF(protocolo, '') AS protocol,
    NULLIF(etiquetas, '') AS tags,
    NULLIF(equipe, '') AS team,
    NULLIF(centro_de_custos, '') AS cost_center,
    NULLIF(analista, '') AS analyst_name,
    CAST(NULLIF(telefone_5a, '') AS STRING) AS phone_5a,
    CAST(NULLIF(telefone_cliente, '') AS STRING) AS customer_phone,
    NULLIF(email_analista, '') AS analyst_email,
    NULLIF(hora, '') AS attendance_time,
    NULLIF(satisfacao, '') AS satisfaction_score,
    NULLIF(duracao, '') AS duration,
    NULLIF(tempo_de_espera, '') AS wait_time,
    NULLIF(tempo_estacionado, '') AS parked_time,
    CAST(NULLIF(qtd_palavras_boas, '') AS INTEGER) AS good_words_count,
    CAST(NULLIF(qtd_palavras_ruins, '') AS INTEGER) AS bad_words_count,
    CAST(NULLIF(duracao_minutos, '') AS FLOAT) AS duration_minutes,
    CAST(NULLIF(tempo_de_espera_minutos, '') AS FLOAT) AS wait_time_minutes,
    CAST(NULLIF(tempo_estacionado_minutos, '') AS FLOAT) AS parked_time_minutes,
    NULLIF(monthyear, '') AS month_year,
    TO_DATE(NULLIF(data, ''), 'dd/MM/yyyy') AS dt_contact,
    DATE(NULLIF(data_atendimento, '')) AS dt_attended,
    TIMESTAMP(NULLIF(data_hora, '')) AS ts_attended
FROM
    datalake_gsheets_raw.omni_acquisition_contact
