SELECT
    NULLIF(usuario, '') AS user_name,
    NULLIF(perfil, '') AS profile,
    NULLIF(tipo, '') AS type,
    NULLIF(canal, '') AS channel,
    NULLIF(status, '') AS status,
    NULLIF(status_1, '') AS status_1,
    NULLIF(equipe, '') AS team,
    NULLIF(ramal, '') AS extension,
    CAST(NULLIF(numero_contato, '') AS STRING) AS contact_phone,
    NULLIF(contato, '') AS contact_name,
    NULLIF(protocolo, '') AS protocol,
    NULLIF(tabulacao, '') AS tabulation,
    NULLIF(subtabulacao, '') AS sub_tabulation,
    NULLIF(observacao_tabulacao, '') AS tabulation_note,
    NULLIF(troncodid, '') AS trunk_did,
    NULLIF(hangup, '') AS hangup,
    NULLIF(centro_de_custos, '') AS cost_center,
    NULLIF(analista, '') AS analyst_name,
    CAST(NULLIF(telefone_5a, '') AS STRING) AS phone_5a,
    CAST(NULLIF(telefone_cliente, '') AS STRING) AS customer_phone,
    NULLIF(email_analista, '') AS analyst_email,
    NULLIF(hora, '') AS call_time,
    NULLIF(duracao, '') AS duration,
    TO_DATE(NULLIF(data, ''), 'dd/MM/yyyy') AS dt_contact,
    DATE(NULLIF(data_atendimento, '')) AS dt_attended,
    TIMESTAMP(NULLIF(data_hora, '')) AS ts_attended
FROM
    datalake_gsheets_raw.omni_acquisition_telephony
