WITH dict AS (
SELECT
  *
FROM (
  VALUES
    ('2-4-110', 'Saldo a vencer de Cartões (até 30 dias)'),
    ('2-10-110', 'Saldo a vencer de Cartões (até 30 dias)'),
    ('2-18-110', 'Saldo a vencer de Cartões (até 30 dias)'),
    ('4-6-110', 'Saldo a vencer de Cartões (até 30 dias)'),
    ('13-4-110', 'Saldo a vencer de Cartões (até 30 dias)'),
    ('2-4-120', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('2-4-130', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('2-4-140', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('2-10-120', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('2-10-130', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('2-10-140', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('2-18-120', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('2-18-130', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('2-18-140', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('4-6-120', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('4-6-130', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('4-6-140', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('13-4-120', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('13-4-130', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('13-4-140', 'Saldo a vencer de Cartões (31 a 180 dias)'),
    ('2-4-150', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-10-150', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-18-150', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('4-6-150', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('13-4-150', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-4-160', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-10-160', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-18-160', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('4-6-160', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('13-4-160', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-4-165', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-10-165', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-18-165', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('4-6-165', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('13-4-165', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-4-170', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-10-170', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-18-170', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('4-6-170', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('13-4-170', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-4-175', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-10-175', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-18-175', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('4-6-175', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('13-4-175', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-4-180', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-10-180', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-18-180', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('4-6-180', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('13-4-180', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-4-190', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-10-190', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('2-18-190', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('4-6-190', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('13-4-190', 'Saldo a vencer de Cartões (acima de 180 dias)'),
    ('9-1-110', 'Saldo a vencer de Imobiliário (até 30 dias)'),
    ('9-2-110', 'Saldo a vencer de Imobiliário (até 30 dias)'),
    ('9-1-120', 'Saldo a vencer de Imobiliário (31 a 180 dias)'),
    ('9-2-120', 'Saldo a vencer de Imobiliário (31 a 180 dias)'),
    ('9-1-130', 'Saldo a vencer de Imobiliário (31 a 180 dias)'),
    ('9-2-130', 'Saldo a vencer de Imobiliário (31 a 180 dias)'),
    ('9-1-140', 'Saldo a vencer de Imobiliário (31 a 180 dias)'),
    ('9-2-140', 'Saldo a vencer de Imobiliário (31 a 180 dias)'),
    ('9-1-150', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-2-150', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-1-160', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-2-160', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-1-165', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-2-165', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-1-170', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-2-170', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-1-175', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-2-175', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-1-180', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-2-180', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-1-190', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('9-2-190', 'Saldo a vencer de Imobiliário (acima de 180 dias)'),
    ('2-2-110', 'Saldo a vencer de Consignado (até 30 dias)'),
    ('2-2-120', 'Saldo a vencer de Consignado (31 a 180 dias)'),
    ('2-2-130', 'Saldo a vencer de Consignado (31 a 180 dias)'),
    ('2-2-140', 'Saldo a vencer de Consignado (31 a 180 dias)'),
    ('2-2-150', 'Saldo a vencer de Consignado (acima de 180 dias)'),
    ('2-2-160', 'Saldo a vencer de Consignado (acima de 180 dias)'),
    ('2-2-165', 'Saldo a vencer de Consignado (acima de 180 dias)'),
    ('2-2-170', 'Saldo a vencer de Consignado (acima de 180 dias)'),
    ('2-2-175', 'Saldo a vencer de Consignado (acima de 180 dias)'),
    ('2-2-180', 'Saldo a vencer de Consignado (acima de 180 dias)'),
    ('2-2-190', 'Saldo a vencer de Consignado (acima de 180 dias)'),
    ('4-1-110', 'Saldo a vencer de Veículos PF (até 30 dias)'),
    ('4-1-120', 'Saldo a vencer de Veículos PF (31 a 180 dias)'),
    ('4-1-130', 'Saldo a vencer de Veículos PF (31 a 180 dias)'),
    ('4-1-140', 'Saldo a vencer de Veículos PF (31 a 180 dias)'),
    ('4-1-150', 'Saldo a vencer de Veículos PF (acima de 180 dias)'),
    ('4-1-160', 'Saldo a vencer de Veículos PF (acima de 180 dias)'),
    ('4-1-165', 'Saldo a vencer de Veículos PF (acima de 180 dias)'),
    ('4-1-170', 'Saldo a vencer de Veículos PF (acima de 180 dias)'),
    ('4-1-175', 'Saldo a vencer de Veículos PF (acima de 180 dias)'),
    ('4-1-180', 'Saldo a vencer de Veículos PF (acima de 180 dias)'),
    ('4-1-190', 'Saldo a vencer de Veículos PF (acima de 180 dias)'),
    ('2-11-110', 'Saldo a vencer de Home Equity (até 30 dias)'),
    ('2-11-120', 'Saldo a vencer de Home Equity (31 a 180 dias)'),
    ('2-11-130', 'Saldo a vencer de Home Equity (31 a 180 dias)'),
    ('2-11-140', 'Saldo a vencer de Home Equity (31 a 180 dias)'),
    ('2-11-150', 'Saldo a vencer de Home Equity (acima de 180 dias)'),
    ('2-11-160', 'Saldo a vencer de Home Equity (acima de 180 dias)'),
    ('2-11-165', 'Saldo a vencer de Home Equity (acima de 180 dias)'),
    ('2-11-170', 'Saldo a vencer de Home Equity (acima de 180 dias)'),
    ('2-11-175', 'Saldo a vencer de Home Equity (acima de 180 dias)'),
    ('2-11-180', 'Saldo a vencer de Home Equity (acima de 180 dias)'),
    ('2-11-190', 'Saldo a vencer de Home Equity (acima de 180 dias)'),
    ('2-3-110', 'Saldo a vencer de Crédito Pessoal (até 30 dias)'),
    ('2-3-120', 'Saldo a vencer de Crédito Pessoal (31 a 180 dias)'),
    ('2-3-130', 'Saldo a vencer de Crédito Pessoal (31 a 180 dias)'),
    ('2-3-140', 'Saldo a vencer de Crédito Pessoal (31 a 180 dias)'),
    ('2-3-150', 'Saldo a vencer de Crédito Pessoal (acima de 180 dias)'),
    ('2-3-160', 'Saldo a vencer de Crédito Pessoal (acima de 180 dias)'),
    ('2-3-165', 'Saldo a vencer de Crédito Pessoal (acima de 180 dias)'),
    ('2-3-170', 'Saldo a vencer de Crédito Pessoal (acima de 180 dias)'),
    ('2-3-175', 'Saldo a vencer de Crédito Pessoal (acima de 180 dias)'),
    ('2-3-180', 'Saldo a vencer de Crédito Pessoal (acima de 180 dias)'),
    ('2-3-190', 'Saldo a vencer de Crédito Pessoal (acima de 180 dias)'),
    ('1-1-110', 'Saldo a vencer de Cheque Especial (até 30 dias)'),
    ('2-13-110', 'Saldo a vencer de Cheque Especial (até 30 dias)'),
    ('1-1-120', 'Saldo a vencer de Cheque Especial (31 a 180 dias)'),
    ('2-13-120', 'Saldo a vencer de Cheque Especial (31 a 180 dias)'),
    ('1-1-130', 'Saldo a vencer de Cheque Especial (31 a 180 dias)'),
    ('2-13-130', 'Saldo a vencer de Cheque Especial (31 a 180 dias)'),
    ('1-1-140', 'Saldo a vencer de Cheque Especial (31 a 180 dias)'),
    ('2-13-140', 'Saldo a vencer de Cheque Especial (31 a 180 dias)'),
    ('1-1-150', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('2-13-150', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('1-1-160', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('2-13-160', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('1-1-165', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('2-13-165', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('1-1-170', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('2-13-170', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('1-1-175', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('2-13-175', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('1-1-180', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('2-13-180', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('1-1-190', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('2-13-190', 'Saldo a vencer de Cheque Especial (acima de 180 dias)'),
    ('2-4-205', 'Saldo vencido de Cartões (até 30 dias)'),
    ('2-4-210', 'Saldo vencido de Cartões (até 30 dias)'),
    ('2-10-205', 'Saldo vencido de Cartões (até 30 dias)'),
    ('2-10-210', 'Saldo vencido de Cartões (até 30 dias)'),
    ('2-18-205', 'Saldo vencido de Cartões (até 30 dias)'),
    ('2-18-210', 'Saldo vencido de Cartões (até 30 dias)'),
    ('4-6-205', 'Saldo vencido de Cartões (até 30 dias)'),
    ('4-6-210', 'Saldo vencido de Cartões (até 30 dias)'),
    ('13-4-205', 'Saldo vencido de Cartões (até 30 dias)'),
    ('13-4-210', 'Saldo vencido de Cartões (até 30 dias)'),
    ('2-4-220', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-4-230', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-4-240', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-4-245', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-4-250', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-4-255', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-4-260', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-4-270', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-4-280', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-4-290', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-220', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-230', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-240', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-245', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-250', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-255', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-260', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-270', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-280', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-10-290', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-220', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-230', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-240', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-245', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-250', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-255', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-260', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-270', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-280', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('2-18-290', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-220', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-230', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-240', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-245', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-250', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-255', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-260', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-270', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-280', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('4-6-290', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-220', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-230', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-240', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-245', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-250', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-255', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-260', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-270', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-280', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('13-4-290', 'Saldo vencido de Cartões (acima de 30 dias)'),
    ('9-1-205', 'Saldo vencido de Imobiliário (até 30 dias)'),
    ('9-1-210', 'Saldo vencido de Imobiliário (até 30 dias)'),
    ('9-2-205', 'Saldo vencido de Imobiliário (até 30 dias)'),
    ('9-2-210', 'Saldo vencido de Imobiliário (até 30 dias)'),
    ('9-1-220', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-1-230', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-1-240', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-1-245', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-1-250', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-1-255', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-1-260', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-1-270', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-1-280', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-1-290', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-220', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-230', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-240', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-245', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-250', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-255', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-260', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-270', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-280', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('9-2-290', 'Saldo vencido de Imobiliário (acima de 30 dias)'),
    ('2-2-205', 'Saldo vencido de Consignado (até 30 dias)'),
    ('2-2-210', 'Saldo vencido de Consignado (até 30 dias)'),
    ('2-2-220', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('2-2-230', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('2-2-240', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('2-2-245', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('2-2-250', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('2-2-255', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('2-2-260', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('2-2-270', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('2-2-280', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('2-2-290', 'Saldo vencido de Consignado (acima de 30 dias)'),
    ('4-1-205', 'Saldo vencido de Veículos PF (até 30 dias)'),
    ('4-1-210', 'Saldo vencido de Veículos PF (até 30 dias)'),
    ('4-1-220', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('4-1-230', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('4-1-240', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('4-1-245', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('4-1-250', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('4-1-255', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('4-1-260', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('4-1-270', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('4-1-280', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('4-1-290', 'Saldo vencido de Veículos PF (acima de 30 dias)'),
    ('2-11-205', 'Saldo vencido de Home Equity (até 30 dias)'),
    ('2-11-210', 'Saldo vencido de Home Equity (até 30 dias)'),
    ('2-11-220', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-11-230', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-11-240', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-11-245', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-11-250', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-11-255', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-11-260', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-11-270', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-11-280', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-11-290', 'Saldo vencido de Home Equity (acima de 30 dias)'),
    ('2-3-205', 'Saldo vencido de Crédito Pessoal (até 30 dias)'),
    ('2-3-210', 'Saldo vencido de Crédito Pessoal (até 30 dias)'),
    ('2-3-220', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('2-3-230', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('2-3-240', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('2-3-245', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('2-3-250', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('2-3-255', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('2-3-260', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('2-3-270', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('2-3-280', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('2-3-290', 'Saldo vencido de Crédito Pessoal (acima de 30 dias)'),
    ('1-1-205', 'Saldo vencido de Cheque Especial (até 30 dias)'),
    ('1-1-210', 'Saldo vencido de Cheque Especial (até 30 dias)'),
    ('2-13-205', 'Saldo vencido de Cheque Especial (até 30 dias)'),
    ('2-13-210', 'Saldo vencido de Cheque Especial (até 30 dias)'),
    ('1-1-220', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('1-1-230', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('1-1-240', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('1-1-245', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('1-1-250', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('1-1-255', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('1-1-260', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('1-1-270', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('1-1-280', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('1-1-290', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-220', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-230', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-240', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-245', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-250', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-255', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-260', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-270', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-280', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('2-13-290', 'Saldo vencido de Cheque Especial (acima de 30 dias)'),
    ('19-1-20', 'Limite Global (vencimento até 360 dias)'),
    ('19-2-20', 'Limite de Cheque Especial (vencimento até 360 dias)'),
    ('19-4-20', 'Limite de Cartão de Crédito (vencimento até 360 dias)'),
    ('19-6-20', 'Limite de Crédito Pessoal (vencimento até 360 dias)'),
    ('19-1-40', 'Limite Global (vencimento acima de 360 dias)'),
    ('19-2-40', 'Limite de Cheque Especial (vencimento acima de 360 dias)'),
    ('19-4-40', 'Limite de Cartão de Crédito (vencimento acima de 360 dias)'),
    ('19-6-40', 'Limite de Crédito Pessoal (vencimento acima de 360 dias)'),
    ('2-4-110', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (até 30 dias)'),
    ('2-4-120', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (31 a 60 dias)'),
    ('2-4-130', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (61 a 90 dias)'),
    ('2-4-140', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (91 a 180 dias)'),
    ('2-4-150', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (acima de 180 dias)'),
    ('2-4-160', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (acima de 180 dias)'),
    ('2-4-165', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (acima de 180 dias)'),
    ('2-4-170', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (acima de 180 dias)'),
    ('2-4-175', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (acima de 180 dias)'),
    ('2-4-180', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (acima de 180 dias)'),
    ('2-4-190', 'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (acima de 180 dias)'),
    ('13-4-110', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (até 30 dias)'),
    ('13-4-120', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (31 a 60 dias)'),
    ('13-4-130', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (61 a 90 dias)'),
    ('13-4-140', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (91 a 180 dias)'),
    ('13-4-150', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-160', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-165', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-170', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-175', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-180', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-190', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('2-4-205', 'Saldo vencido de crédito rotativo vinculado à cartão (1 a 14 dias)'),
    ('2-4-210', 'Saldo vencido de crédito rotativo vinculado à cartão (15 a 30 dias)'),
    ('2-4-220', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-4-230', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-4-240', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-4-245', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-4-250', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-4-255', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-4-260', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-4-270', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-4-280', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-4-290', 'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)'),
    ('2-99-110', 'Saldo a vencer de Outros Empréstimos (até 30 dias)'),
    ('2-99-120', 'Saldo a vencer de Outros Empréstimos (31 a 60 dias)'),
    ('2-99-130', 'Saldo a vencer de Outros Empréstimos (61 a 90 dias)'),
    ('2-99-140', 'Saldo a vencer de Outros Empréstimos (91 a 180 dias)'),
    ('2-99-150', 'Saldo a vencer de Outros Empréstimos (acima de 180 dias)'),
    ('2-99-160', 'Saldo a vencer de Outros Empréstimos (acima de 180 dias)'),
    ('2-99-165', 'Saldo a vencer de Outros Empréstimos (acima de 180 dias)'),
    ('2-99-170', 'Saldo a vencer de Outros Empréstimos (acima de 180 dias)'),
    ('2-99-175', 'Saldo a vencer de Outros Empréstimos (acima de 180 dias)'),
    ('2-99-180', 'Saldo a vencer de Outros Empréstimos (acima de 180 dias)'),
    ('2-99-190', 'Saldo a vencer de Outros Empréstimos (acima de 180 dias)'),
    ('2-10-110', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (até 30 dias)'),
    ('2-10-120', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (31 a 60 dias)'),
    ('2-10-130', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (61 a 90 dias)'),
    ('2-10-140', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (91 a 180 dias)'),
    ('2-10-150', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (acima de 180 dias)'),
    ('2-10-160', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (acima de 180 dias)'),
    ('2-10-165', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (acima de 180 dias)'),
    ('2-10-170', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (acima de 180 dias)'),
    ('2-10-175', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (acima de 180 dias)'),
    ('2-10-180', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (acima de 180 dias)'),
    ('2-10-190', 'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (acima de 180 dias)'),
    ('13-4-110', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (até 30 dias)'),
    ('13-4-120', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (31 a 60 dias)'),
    ('13-4-130', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (61 a 90 dias)'),
    ('13-4-140', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (91 a 180 dias)'),
    ('13-4-150', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-160', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-165', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-170', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-175', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-180', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('13-4-190', 'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)'),
    ('2-3-120', 'Saldo a vencer de Crédito Pessoal (31 a 60 dias)'),
    ('2-3-130', 'Saldo a vencer de Crédito Pessoal (61 a 90 dias)'),
    ('2-3-140', 'Saldo a vencer de Crédito Pessoal (90 a 180 dias)'),
    ('2-99-205', 'Saldo vencido de Outros Empréstimos (até 30 dias)'),
    ('2-99-210', 'Saldo vencido de Outros Empréstimos (até 30 dias)'),
    ('2-99-220', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)'),
    ('2-99-230', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)'),
    ('2-99-240', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)'),
    ('2-99-245', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)'),
    ('2-99-250', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)'),
    ('2-99-255', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)'),
    ('2-99-260', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)'),
    ('2-99-270', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)'),
    ('2-99-280', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)'),
    ('2-99-290', 'Saldo vencido de Outros Empréstimos (acima de 30 dias)')
        ) AS a (modality_submodality_domain, custom_categories)
),
base AS (
SELECT
  cpf,
  `version`,
  mob,
  reference_date,
  financial_institution_count,
  start_relationship_date,
  ts_created,
  ts_updated,
  ts_next_updated,
  `value`,
  custom_categories
FROM
  datalake_arquivo_confidencial.scr
INNER JOIN
  dict
    ON dict.modality_submodality_domain = CAST(modality AS INT)||'-'||CAST(submodality AS INT)||'-'||CAST(domain AS INT)
)
SELECT
  cpf,
  `version`,
  mob,
  financial_institution_count,
  start_relationship_date,
  reference_date,
  `Saldo a vencer de Cartões (até 30 dias)` AS balance_due_on_credit_cards_up_to_30_days,
  `Saldo a vencer de Cartões (31 a 180 dias)` AS balance_due_on_credit_cards_31_to_180_days,
  `Saldo a vencer de Cartões (acima de 180 dias)` AS balance_due_on_credit_cards_over_180_days,
  `Saldo a vencer de Imobiliário (até 30 dias)` AS balance_due_on_real_estate_up_to_30_days,
  `Saldo a vencer de Imobiliário (31 a 180 dias)` AS balance_due_on_real_estate_31_to_180_days,
  `Saldo a vencer de Imobiliário (acima de 180 dias)` AS balance_due_on_real_estate_over_180_days,
  `Saldo a vencer de Consignado (até 30 dias)` AS balance_due_on_payroll_loan_up_to_30_days,
  `Saldo a vencer de Consignado (31 a 180 dias)` AS balance_due_on_payroll_loan_31_to_180_days,
  `Saldo a vencer de Consignado (acima de 180 dias)` AS balance_due_on_payroll_loan_over_180_days,
  `Saldo a vencer de Veículos PF (até 30 dias)` AS balance_due_on_vehicles_up_to_30_days,
  `Saldo a vencer de Veículos PF (31 a 180 dias)` AS balance_due_on_vehicles_31_to_180_days,
  `Saldo a vencer de Veículos PF (acima de 180 dias)` AS balance_due_on_vehicles_over_180_days,
  `Saldo a vencer de Home Equity (até 30 dias)` AS balance_due_on_home_equity_up_to_30_days,
  `Saldo a vencer de Home Equity (31 a 180 dias)` AS balance_due_on_home_equity_31_to_180_days,
  `Saldo a vencer de Home Equity (acima de 180 dias)` AS balance_due_on_home_equity_over_180_days,
  `Saldo a vencer de Crédito Pessoal (até 30 dias)` AS balance_due_on_personal_credit_up_to_30_days,
  `Saldo a vencer de Crédito Pessoal (31 a 180 dias)` AS balance_due_on_personal_credit_31_to_180_days,
  `Saldo a vencer de Crédito Pessoal (acima de 180 dias)` AS balance_due_on_personal_credit_over_180_days,
  `Saldo a vencer de Cheque Especial (até 30 dias)` AS balance_due_on_overdraft_check_up_to_30_days,
  `Saldo a vencer de Cheque Especial (31 a 180 dias)` AS balance_due_on_overdraft_check_31_to_180_days,
  `Saldo a vencer de Cheque Especial (acima de 180 dias)` AS balance_due_on_overdraft_check_over_180_days,
  `Saldo vencido de Cartões (até 30 dias)` AS overdue_balance_of_credit_cards_up_to_30_days,
  `Saldo vencido de Cartões (acima de 30 dias)` AS overdue_balance_of_credit_cards_over_30_days,
  `Saldo vencido de Imobiliário (até 30 dias)` AS overdue_balance_of_real_estate_up_to_30_days,
  `Saldo vencido de Imobiliário (acima de 30 dias)` AS overdue_balance_of_real_estate_over_30_days,
  `Saldo vencido de Consignado (até 30 dias)` AS overdue_balance_of_payroll_loan_up_to_30_days,
  `Saldo vencido de Consignado (acima de 30 dias)` AS overdue_balance_of_payroll_loan_over_30_days,
  `Saldo vencido de Veículos PF (até 30 dias)` AS overdue_balance_of_vehicles_up_to_30_days,
  `Saldo vencido de Veículos PF (acima de 30 dias)` AS overdue_balance_of_vehicles_over_30_days,
  `Saldo vencido de Home Equity (até 30 dias)` AS overdue_balance_of_home_equity_up_to_30_days,
  `Saldo vencido de Home Equity (acima de 30 dias)` AS overdue_balance_of_home_equity_over_30_days,
  `Saldo vencido de Crédito Pessoal (até 30 dias)` AS overdue_balance_of_personal_credit_up_to_30_days,
  `Saldo vencido de Crédito Pessoal (acima de 30 dias)` AS overdue_balance_of_personal_credit_over_30_days,
  `Saldo vencido de Cheque Especial (até 30 dias)` AS overdue_balance_of_overdraft_check_up_to_30_days,
  `Saldo vencido de Cheque Especial (acima de 30 dias)` AS overdue_balance_of_overdraft_check_over_30_days,
  `Limite Global (vencimento até 360 dias)` AS global_limit_expiration_up_to_360_days,
  `Limite de Cheque Especial (vencimento até 360 dias)` AS overdraft_check_limit_expiration_up_to_360_days,
  `Limite de Cartão de Crédito (vencimento até 360 dias)` AS credit_card_limit_expiration_over_up_to_360_days,
  `Limite de Crédito Pessoal (vencimento até 360 dias)` AS personal_credit_limit_expiration_up_to_360_days,
  `Limite Global (vencimento acima de 360 dias)` AS global_limit_expiration_over_360_days,
  `Limite de Cheque Especial (vencimento acima de 360 dias)` AS overdraft_check_limit_expiration_over_360_days,
  `Limite de Cartão de Crédito (vencimento acima de 360 dias)` AS credit_card_limit_expiration_over_360_days,
  `Limite de Crédito Pessoal (vencimento acima de 360 dias)` AS personal_credit_limit_expiration_over_360_days,
  `Saldo a vencer de Outros Empréstimos (até 30 dias)` AS balance_due_on_other_loans_up_to_30_days,
  `Saldo a vencer de Outros Empréstimos (31 a 60 dias)` AS balance_due_on_other_loans_31_to_60_days,
  `Saldo a vencer de Outros Empréstimos (61 a 90 dias)` AS balance_due_on_other_loans_61_to_90_days,
  `Saldo a vencer de Outros Empréstimos (91 a 180 dias)` AS balance_due_on_other_loans_91_to_180_days,
  `Saldo a vencer de Outros Empréstimos (acima de 180 dias)` AS balance_due_on_other_loans_over_180_days,
  `Saldo a vencer de crédito rotativo vinculado a cartão de crédito (até 30 dias)` AS balance_due_on_credit_card_linked_rotating_credit_up_to_30_days,
  `Saldo a vencer de crédito rotativo vinculado a cartão de crédito (31 a 60 dias)` AS balance_due_on_credit_card_linked_rotating_credit_31_to_60_days,
  `Saldo a vencer de crédito rotativo vinculado a cartão de crédito (61 a 90 dias)` AS balance_due_on_credit_card_linked_rotating_credit_61_to_90_days,
  `Saldo a vencer de crédito rotativo vinculado a cartão de crédito (91 a 180 dias)` AS balance_due_on_credit_card_linked_rotating_credit_91_to_180_days,
  `Saldo a vencer de crédito rotativo vinculado a cartão de crédito (acima de 180 dias)` AS balance_due_on_credit_card_linked_rotating_credit_over_180_days,
  `Saldo a vencer de cartões - compra à vista ou parcelado lojista (até 30 dias)` AS balance_due_on_credit_card_in_store_or_installments_up_to_30_days,
  `Saldo a vencer de cartões - compra à vista ou parcelado lojista (31 a 60 dias)` AS balance_due_on_credit_card_in_store_or_installments_31_to_60_days,
  `Saldo a vencer de cartões - compra à vista ou parcelado lojista (61 a 90 dias)` AS balance_due_on_credit_card_in_store_or_installments_61_to_90_days,
  `Saldo a vencer de cartões - compra à vista ou parcelado lojista (91 a 180 dias)` AS balance_due_on_credit_card_in_store_or_installments_91_to_180_days,
  `Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)` AS balance_due_on_credit_card_in_store_or_installments_over_180_days,
  `Saldo vencido de crédito rotativo vinculado à cartão (1 a 14 dias)` AS overdue_balance_of_credit_card_linked_rotating_credit_1_to_14_days,
  `Saldo vencido de crédito rotativo vinculado à cartão (15 a 30 dias)` AS overdue_balance_of_credit_card_linked_rotating_credit_15_to_30_days,
  `Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)` AS overdue_balance_of_credit_card_linked_rotating_credit_over_30_days,
  `Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (até 30 dias)` AS balance_due_on_credit_card_instalment_purchase_or_issuer_financed_withdrawal_up_to_30_days,
  `Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (31 a 60 dias)` AS balance_due_on_credit_card_instalment_purchase_or_issuer_financed_withdrawal_31_to_60_days,
  `Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (61 a 90 dias)` AS balance_due_on_credit_card_instalment_purchase_or_issuer_financed_withdrawal_61_to_90_days,
  `Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (91 a 180 dias)` AS balance_due_on_credit_card_instalment_purchase_or_issuer_financed_withdrawal_91_to_180_days,
  `Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (acima de 180 dias)` AS balance_due_on_credit_card_instalment_purchase_or_issuer_financed_withdrawal_over_180_days,
  `Saldo a vencer de Crédito Pessoal (31 a 60 dias)` AS balance_due_on_personal_credit_31_to_60_days,
  `Saldo a vencer de Crédito Pessoal (61 a 90 dias)` AS balance_due_on_personal_credit_61_to_90_days,
  `Saldo a vencer de Crédito Pessoal (90 a 180 dias)` AS balance_due_on_personal_credit_90_to_180_days,
  `Saldo vencido de Outros Empréstimos (até 30 dias)` AS overdue_balance_of_other_loans_up_to_30_days,
  `Saldo vencido de Outros Empréstimos (acima de 30 dias)` AS overdue_balance_of_other_loans_over_30_days,
  ts_created,
  ts_updated,
  ts_next_updated
FROM base
PIVOT(SUM(`value`) AS `value` FOR custom_categories IN ('Saldo a vencer de Cartões (até 30 dias)',
'Saldo a vencer de Cartões (31 a 180 dias)',
'Saldo a vencer de Cartões (acima de 180 dias)',
'Saldo a vencer de Imobiliário (até 30 dias)',
'Saldo a vencer de Imobiliário (31 a 180 dias)',
'Saldo a vencer de Imobiliário (acima de 180 dias)',
'Saldo a vencer de Consignado (até 30 dias)',
'Saldo a vencer de Consignado (31 a 180 dias)',
'Saldo a vencer de Consignado (acima de 180 dias)',
'Saldo a vencer de Veículos PF (até 30 dias)',
'Saldo a vencer de Veículos PF (31 a 180 dias)',
'Saldo a vencer de Veículos PF (acima de 180 dias)',
'Saldo a vencer de Home Equity (até 30 dias)',
'Saldo a vencer de Home Equity (31 a 180 dias)',
'Saldo a vencer de Home Equity (acima de 180 dias)',
'Saldo a vencer de Crédito Pessoal (até 30 dias)',
'Saldo a vencer de Crédito Pessoal (31 a 180 dias)',
'Saldo a vencer de Crédito Pessoal (acima de 180 dias)',
'Saldo a vencer de Cheque Especial (até 30 dias)',
'Saldo a vencer de Cheque Especial (31 a 180 dias)',
'Saldo a vencer de Cheque Especial (acima de 180 dias)',
'Saldo vencido de Cartões (até 30 dias)',
'Saldo vencido de Cartões (acima de 30 dias)',
'Saldo vencido de Imobiliário (até 30 dias)',
'Saldo vencido de Imobiliário (acima de 30 dias)',
'Saldo vencido de Consignado (até 30 dias)',
'Saldo vencido de Consignado (acima de 30 dias)',
'Saldo vencido de Veículos PF (até 30 dias)',
'Saldo vencido de Veículos PF (acima de 30 dias)',
'Saldo vencido de Home Equity (até 30 dias)',
'Saldo vencido de Home Equity (acima de 30 dias)',
'Saldo vencido de Crédito Pessoal (até 30 dias)',
'Saldo vencido de Crédito Pessoal (acima de 30 dias)',
'Saldo vencido de Cheque Especial (até 30 dias)',
'Saldo vencido de Cheque Especial (acima de 30 dias)',
'Limite Global (vencimento até 360 dias)',
'Limite de Cheque Especial (vencimento até 360 dias)',
'Limite de Cartão de Crédito (vencimento até 360 dias)',
'Limite de Crédito Pessoal (vencimento até 360 dias)',
'Limite Global (vencimento acima de 360 dias)',
'Limite de Cheque Especial (vencimento acima de 360 dias)',
'Limite de Cartão de Crédito (vencimento acima de 360 dias)',
'Limite de Crédito Pessoal (vencimento acima de 360 dias)',
'Saldo a vencer de Outros Empréstimos (até 30 dias)',
'Saldo a vencer de Outros Empréstimos (31 a 60 dias)',
'Saldo a vencer de Outros Empréstimos (61 a 90 dias)',
'Saldo a vencer de Outros Empréstimos (91 a 180 dias)',
'Saldo a vencer de Outros Empréstimos (acima de 180 dias)',
'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (até 30 dias)',
'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (31 a 60 dias)',
'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (61 a 90 dias)',
'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (91 a 180 dias)',
'Saldo a vencer de crédito rotativo vinculado a cartão de crédito (acima de 180 dias)',
'Saldo a vencer de cartões - compra à vista ou parcelado lojista (até 30 dias)',
'Saldo a vencer de cartões - compra à vista ou parcelado lojista (31 a 60 dias)',
'Saldo a vencer de cartões - compra à vista ou parcelado lojista (61 a 90 dias)',
'Saldo a vencer de cartões - compra à vista ou parcelado lojista (91 a 180 dias)',
'Saldo a vencer de cartões - compra à vista ou parcelado lojista (acima de 180 dias)',
'Saldo vencido de crédito rotativo vinculado à cartão (1 a 14 dias)',
'Saldo vencido de crédito rotativo vinculado à cartão (15 a 30 dias)',
'Saldo vencido de crédito rotativo vinculado à cartão (acima de 30 dias)',
'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (até 30 dias)',
'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (31 a 60 dias)',
'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (61 a 90 dias)',
'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (91 a 180 dias)',
'Saldo a vencer de cartões - compra, fatura parcelada ou saque financiado pela instituição emitente do cartão (acima de 180 dias)',
'Saldo a vencer de Crédito Pessoal (31 a 60 dias)',
'Saldo a vencer de Crédito Pessoal (61 a 90 dias)',
'Saldo a vencer de Crédito Pessoal (90 a 180 dias)',
'Saldo vencido de Outros Empréstimos (até 30 dias)',
'Saldo vencido de Outros Empréstimos (acima de 30 dias)'))
