"""Migration Twin DAG — run original queries on Databricks, capture metrics to S3.

Auto-generated by emr-migration-v2 skill.
Run ID: 4b35a737-1a52-4bf6-a58e-a079d7eae3f3
Scope: fintech/dw_credit_analysis
"""

import os
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

import yaml
from airflow import DAG, Dataset
from airflow.operators.python import PythonOperator

from bietlejuice.base.airflow.job_cluster_engine import (
    attach_emr_job_cluster_finished_work_prerequisites,
    attach_emr_terminate_cluster_work_prerequisites,
    attach_job_cluster_engine_to_context,
    get_job_cluster_completion_sink,
)
from bietlejuice.base.airflow.task_creators.dag_execution_context import (
    DagExecutionContext,
)
from bietlejuice.services.configuration_service import ConfigurationService

DAG_ID = "migration_twin_fintech__dw_credit_analysis"
RUN_ID = "4b35a737-1a52-4bf6-a58e-a079d7eae3f3"
DOMAIN = "fintech"
SOURCE_DAG_NAME = "dw_credit_analysis"
DATASET_URI = "migration:twin-fintech__dw_credit_analysis-complete"
RUN_PREFIX = "emr-migration/runs/4b35a737-1a52-4bf6-a58e-a079d7eae3f3"
RUNTIME = "twin"
SQL_DIR_NAME = "dw"

TABLES = [
    "dim_credit_analysis",
    "dim_credit_analysis_retenants",
    "dim_docpilot_proposal_extraction_results",
    "dim_drop_reason",
    "dim_experiment",
    "dim_guarantee_policy",
    "dim_proponent_proposal_informed_incomes",
    "dim_variant",
    "fact_credit_engine_analysis_request",
    "fact_early_credit",
    "fact_fintechops_tasks",
    "fact_offer_early_credit",
    "fact_proponent_income_sources",
    "fact_proposal_credit_flows",
]

DAG_DIR = Path(__file__).resolve().parent
ENV = os.environ.get("ENVIRONMENT")
CONFIG_SERVICE = ConfigurationService(SOURCE_DAG_NAME)
BUCKET = CONFIG_SERVICE.get_config("datalake_bucket")
BIETLEJUICE_REPO_PATH = CONFIG_SERVICE.get_config("databricks_bietlejuice_repo_path")
METRIC_CAPTURE_JOB = (
    f"{BIETLEJUICE_REPO_PATH}/spark_jobs/migration_assets/metric_capture_job.py"
)
ARTIFACTS_URI = CONFIG_SERVICE.get_config("artifacts_bucket")
ARTIFACTS_BUCKET = urlparse(ARTIFACTS_URI).netloc or ARTIFACTS_URI

with open(DAG_DIR / f"{DAG_ID}_cluster.yml") as _f:
    CLUSTER_ARGS = yaml.safe_load(_f).get("cluster", {})


def _build_context(dag):
    ctx = DagExecutionContext(
        dag=dag,
        environment=ENV,
        bucket=BUCKET,
        base_spark_jobs_path=f"{BIETLEJUICE_REPO_PATH}/spark_jobs/base/",
        dag_args={},
        workflow_args={},
        cluster_args=CLUSTER_ARGS,
        databricks_conn_id=CLUSTER_ARGS.get("databricks_conn_id", "databricks_new_env"),
    )
    attach_job_cluster_engine_to_context(ctx, CONFIG_SERVICE)
    return ctx


def _get_s3_client():
    import boto3
    from airflow.models import Variable

    role_arn = Variable.get("DATASET_EVENTS_ASSUME_ROLE_ARN", default_var=None)
    if not role_arn:
        return boto3.client("s3")
    sts = boto3.client("sts")
    creds = sts.assume_role(
        RoleArn=role_arn,
        RoleSessionName="migration-s3-upload",
        DurationSeconds=3600,
    )["Credentials"]
    return boto3.Session(
        aws_access_key_id=creds["AccessKeyId"],
        aws_secret_access_key=creds["SecretAccessKey"],
        aws_session_token=creds["SessionToken"],
    ).client("s3")


def _upload_sql(**context):
    sql_dir = DAG_DIR / "queries" / SQL_DIR_NAME
    s3 = _get_s3_client()
    for table in TABLES:
        local_path = str(sql_dir / f"{table}.sql")
        s3_key = f"{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/{table}.sql"
        s3.upload_file(local_path, ARTIFACTS_BUCKET, s3_key)


with DAG(
    dag_id=DAG_ID,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["migration", "twin", "validation"],
    default_args={"owner": "data-platform", "retries": 0},
) as dag:
    ctx = _build_context(dag)

    upload_sql = PythonOperator(
        task_id="upload_sql",
        python_callable=_upload_sql,
    )

    execute_cluster = ctx.job_cluster_engine.create_execute_cluster_task(
        config_service=CONFIG_SERVICE,
        minimum_cluster_runtime_version=None,
        execute_job_cluster_local_id=None,
    )

    end = PythonOperator(
        task_id="end",
        python_callable=lambda **kw: None,
        outlets=[Dataset(DATASET_URI)],
    )

    capture_tasks = []

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_credit_analysis",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_credit_analysis",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_credit_analysis",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_credit_analysis",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_credit_analysis_retenants",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_credit_analysis_retenants",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_credit_analysis_retenants",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_credit_analysis_retenants",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_docpilot_proposal_extraction_results",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_docpilot_proposal_extraction_results",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_docpilot_proposal_extraction_results",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_docpilot_proposal_extraction_results",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_drop_reason",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_drop_reason",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_drop_reason",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_drop_reason",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_experiment",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_experiment",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_experiment",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_experiment",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_guarantee_policy",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_guarantee_policy",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_guarantee_policy",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_guarantee_policy",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_proponent_proposal_informed_incomes",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_proponent_proposal_informed_incomes",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_proponent_proposal_informed_incomes",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_proponent_proposal_informed_incomes",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_dim_variant",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_variant",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/dim_variant",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "dim_variant",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_credit_engine_analysis_request",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_credit_engine_analysis_request",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_credit_engine_analysis_request",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_credit_engine_analysis_request",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_early_credit",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_early_credit",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_early_credit",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_early_credit",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_fintechops_tasks",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_fintechops_tasks",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_fintechops_tasks",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_fintechops_tasks",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_offer_early_credit",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_offer_early_credit",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_offer_early_credit",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_offer_early_credit",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_proponent_income_sources",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_proponent_income_sources",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_proponent_income_sources",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_proponent_income_sources",
            ],
            execution_timeout_hours=0.5,
        )
    )

    capture_tasks.append(
        ctx.job_cluster_engine.create_spark_python_task(
            spark_job_path=METRIC_CAPTURE_JOB,
            task_id="capture_fact_proposal_credit_flows",
            job_parameters=[
                "--sql-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/sql/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_proposal_credit_flows",
                "--result-s3-uri",
                f"{ARTIFACTS_URI}/{RUN_PREFIX}/{RUNTIME}/{DOMAIN}/{SOURCE_DAG_NAME}/fact_proposal_credit_flows",
                "--run-id",
                RUN_ID,
                "--runtime",
                "databricks",
                "--domain",
                DOMAIN,
                "--dag-name",
                SOURCE_DAG_NAME,
                "--table-name",
                "fact_proposal_credit_flows",
            ],
            execution_timeout_hours=0.5,
        )
    )

    cluster_completion = get_job_cluster_completion_sink(ctx, execute_cluster, end)
    attach_emr_job_cluster_finished_work_prerequisites(
        ctx, job_cluster_finished_task=end, work_completion_tasks=capture_tasks
    )

    upload_sql >> execute_cluster >> capture_tasks >> cluster_completion
    attach_emr_terminate_cluster_work_prerequisites(
        ctx,
        cluster_completion,
        execute_job_cluster_task=execute_cluster,
        job_cluster_finished_task=end,
    )
