SELECT
  id,
  dadosfotografo_id AS id_photographer_data,
  imovel_id AS id_house,
  origincreation_id AS id_origin_creation,
  reservadopara_id AS id_reserved_for,
  originlastupdate_id AS id_last_update_origin,
  telefonesessaofotos AS photo_session_phone,
  emailsessaofotos AS photo_session_email,
  telefonesessaofotossecundario AS photo_session_secondary_phone,
  nomecontatosessaofotos AS photo_session_contact_name,
  photoSender AS photo_sender_user_type,
  status,
  motivoAlteracao AS reason_of_change,
  motivocancelamentojob AS cancellation_reason,
  textomotivocancelamento AS cancellation_reason_text,
  scorecorretude AS correctness_score,
  retirarchave AS key_pick_up,
  outroschave AS key_others,
  problema AS problem,
  instrucoesagendamento AS booking_instructions,
  revisionimovel AS house_revision,
  tipocontrato AS contract_type,
  scorecompletude AS completeness_score,
  naotentoucontato AS has_tried_contact,
  lockbox AS has_lockbox,
  autorizacaoporescrito AS has_written_authorization,
  semcontatoproprietario AS has_no_landlord_contact,
  fixed AS is_fixed,
  prefereemailsessaofotos AS is_photo_session_email_preferred,
  aprovado AS is_approved,
  confirmado AS is_confirmed,
  dataaceitofotografo AS ts_photographer_accepted,
  datapagamento AS ts_payment,
  datainiciosessao AS ts_session_started,
  datauploadfotos AS ts_photos_uploaded,
  datajobpedido AS ts_photo_job_requested,
  dataagendamento AS ts_scheduled,
  datacriacao AS ts_created,
  atualizadoem AS ts_updated
FROM datalake_ebdb_test_raw.jobfotografo

