SELECT
    _id AS id,
    CAST(page_id AS BIGINT) AS id_page,
    CAST(interacted_page_id AS BIGINT) AS id_interacted_page,
    CAST(post_id AS BIGINT) AS id_post,
    CAST(operator_id AS BIGINT) AS id_operator,
    talk_id AS id_talk,
    CAST(sac_call_id AS BIGINT) AS id_sac_call,
    CAST(root_id AS BIGINT) id_root,
    CAST(replier AS BIGINT) id_replier,
    CAST(uid AS BIGINT) AS uid,
    CAST(pid AS BIGINT) AS pid,
    CAST(fb_pid AS BIGINT) AS pid_fb,
    CAST(fb_uid AS BIGINT) AS uid_fb,
    CAST(reply_pid AS BIGINT) AS pid_reply,
    CAST(long_updated_at AS BIGINT) AS id_long_updated,
    CAST(long_posted_at AS BIGINT) AS id_long_posted,
    CAST(crawled_at AS BIGINT) AS id_crawled,
    nlp_text_hash,
    channel,
    primary_channel,
    pages,
    title,
    name,
    operator_name,
    username,
    replier_name,
    authors,
    groups,
    gender,
    image_url,
    user_image_url,
    user_url,
    post_user_image_url,
    post_url,
    url_content,
    text,
    text_header,
    text_append,
    hashtags,
    sac_type,
    type,
    status,
    interests,
    attachments,
    themes,
    group_polarity,
    update_time_ago,
    features,
    spokesman,
    order_by,
    favorability,
    tags,
    lang,
    theme_polarity,
    mentions,
    CASE 
        WHEN location == "" THEN NULL
        ELSE location
    END AS location,
    CASE 
        WHEN emotion == "" THEN NULL
        ELSE emotion
    END AS emotion,
    receiver,
    shall_use_receiver,
    customer_info,
    anonymous_user,
    CAST(videoplays AS BIGINT) AS videoplays,
    CAST(reactions AS BIGINT) AS reactions, 
    CAST(reaction_like AS BIGINT) AS reaction_like,
    CAST(reaction_love AS BIGINT) AS reaction_love,
    CAST(reaction_sad AS BIGINT) AS reaction_sad,
    CAST(reaction_pride AS BIGINT) AS reaction_pride,
    CAST(reaction_angry AS BIGINT) AS reaction_angry,
    CAST(reaction_total AS BIGINT) AS reaction_total,
    CAST(reaction_wow AS BIGINT) AS reaction_wow,
    CAST(reaction_haha AS BIGINT) AS reaction_haha,
    CAST(reaction_thankful AS BIGINT) AS reaction_thankful,
    CAST(valoration AS FLOAT) AS valoration,
    CAST(footage AS BIGINT) AS footage,
    CAST(shares AS BIGINT) AS shares,
    CAST(max_shared_followers AS BIGINT) AS max_shared_followers,
    CAST(sentiment AS BIGINT) AS sentiment,
    CAST(impact AS BIGINT) AS impact,
    CAST(interactions AS BIGINT) AS interactions,
    CAST(comments AS BIGINT) AS comments,
    CAST(hot AS FLOAT) AS hot,
    CAST(followers AS BIGINT) AS followers,
    CAST(critical_level AS BIGINT) AS critical_level,
    CAST(fb_critical_level AS BIGINT) AS fb_critical_level,
    CAST(AAA_score AS FLOAT) AS AAA_score,
    CAST(dislikes AS BIGINT) AS dislikes,
    CAST(likes AS BIGINT) AS likes,
    CAST(replied AS BOOLEAN) AS is_replied,
    CAST(is_dynamic_post AS BOOLEAN) AS is_dynamic_post,
    CAST(hidden_by_user AS BOOLEAN) AS is_hidden_by_user,
    CAST(page_comment AS BOOLEAN) AS is_page_comment,
    CAST(is_root AS BOOLEAN) AS is_root,
    CAST(verified AS BOOLEAN) AS is_verified,
    CAST(hot_post AS BOOLEAN) AS is_hot_post,
    CAST(favorite AS BOOLEAN) AS is_favorited,
    CAST(max_shared_show_dossier AS BOOLEAN) AS is_max_shared_show_dossier,
    CAST(from_integration AS BOOLEAN) AS is_from_integration,
    CAST(is_ads AS BOOLEAN) AS is_ads,
    CAST(is_hidden AS BOOLEAN) AS is_hidden,
    CAST(spam AS BOOLEAN) AS is_spam,
    TO_TIMESTAMP(posted_at, 'dd/MM/yyyy HH:mm') AS ts_posted,
    TO_TIMESTAMP(metrics_updated_at, 'dd/MM/yyyy HH:mm') AS ts_metrics_updated,
    CAST(ts_load AS TIMESTAMP) AS ts_load,
    year,
    month,
    day
FROM
    datalake_stilingue_raw.smartcare_youtube_conversas
WHERE
    year = {year}
    AND month = {month}
    AND day = {day}